import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as C from '../src/contact.mjs';
import * as L from '../src/longitudinal.mjs';
import {verifyContact} from '../src/contact-recovery.mjs';
import {transaction} from '../src/db.mjs';
const note={note:'明确人工办理（虚构）',reason:'明确依据'},source=()=>({kind:'manual',id:null,version:null,revision:null}),now=()=>new Date().toISOString(),past=()=>new Date(Date.now()-1000).toISOString(),future=()=>new Date(Date.now()+86400000).toISOString(),fields=()=>({title:'明确客户联系（虚构）',purpose_note:'人工核对服务安排',due_at:future(),next_action:'责任人继续核对',owner_id:'front',...note}),consentFields=()=>({category:'service',channel:'phone',recipient_label:'虚构接收人',address:'synthetic-contact-only',source_note:'明确人工记录授权（虚构）',effective_at:past(),...note}),actual=(c)=>({consent_id:c.id,consent_revision:c.revision,occurred_at:now(),result:'sent',source_note:'员工人工录入发出结果（虚构）',content_summary:'明确服务联系摘要（虚构）',result_note:'发出尚无回执',due_at:future(),next_action:'等待实际回执后人工核对',reason:'明确实际来源'}),appointmentFields=()=>({starts_at:future(),ends_at:new Date(Date.now()+90000000).toISOString(),purpose_note:'明确服务预约',place_note:'虚构门店地点',source_note:'人工明确预约意向',owner_id:'front',...note});
async function setup(t,o){const x=await fixture(t,o);x.m=await x.login('manager');x.f=await x.login('front');x.pro=await x.login('professional');x.parent=await x.login('parent');return x;}
const write=(x,path,data,who=x.f,key)=>x.request('/api/contacts'+path,{...who,method:'POST',key,data:{expected_sequence:C.contactSequence(x.db,'a'),...data}});
async function grant(x,extra={}){const r=await write(x,'/consents',{customer_id:'one',...consentFields(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function contact(x,extra={}){const r=await write(x,'/cases',{customer_id:'one',purpose:'other_service',source:source(),source_note:'明确人工服务来源',...fields(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function event(x,c,action,extra={},who=x.f){return write(x,'/cases/'+c.id+'/events',{expected_revision:C.contactCase(x.db,c.id).revision,action,...note,...extra},who);}
async function attempt(x,c,g,extra={},who=x.f,key){return write(x,'/cases/'+c.id+'/attempts',{expected_revision:C.contactCase(x.db,c.id).revision,...actual(g),...extra},who,key);}
async function appointment(x,c,extra={}){const r=await write(x,'/cases/'+c.id+'/appointments',{expected_case_revision:C.contactCase(x.db,c.id).revision,...appointmentFields(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
const ae=(x,a,action,extra={})=>write(x,'/appointments/'+a.id+'/events',{action,expected_case_revision:C.contactCase(x.db,a.case_id).revision,expected_revision:C.customerAppointment(x.db,a.id).revision,...note,...extra}),receipt=(x,a,extra={})=>write(x,'/attempts/'+a.id+'/receipts',{expected_case_revision:C.contactCase(x.db,a.case_id).revision,expected_receipt_revision:C.contactAttempt(x.db,a.id).receipt_revision,status:'read',source:'staff_transcript',occurred_at:now(),source_note:'实际回执人工转录',result_note:'明确回执结果',reason:'明确来源',...extra}),all=db=>Object.fromEntries(C.contactTables.map(t=>[t,db.prepare('SELECT * FROM '+t).all()]));
function tamper(db,t,sql){const tr=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(t+'_no_update').sql;db.exec('DROP TRIGGER '+t+'_no_update');db.exec(sql);db.exec(tr);}
test('service and marketing authorization are separate snapshots and a shared phone gives no permission',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x,{purpose:'marketing'});assert.equal((await attempt(x,c,g)).status,409);const m=await grant(x,{category:'marketing'});assert.equal((await attempt(x,c,m)).status,201);verifyContact(x.db);});
test('sent is neither a receipt nor an arrival; explicit receipts append versions without completing contact',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),a=await attempt(x,c,g);assert.equal(a.status,201,JSON.stringify(a.body));assert.equal(a.body.record.receipt,null);assert.equal(C.contactCase(x.db,c.id).status,'waiting');assert.equal(x.db.prepare('SELECT count(*) n FROM visits').get().n,0);assert.equal((await receipt(x,a.body.record)).status,201);assert.equal((await receipt(x,a.body.record,{status:'unknown',result_note:'追加更正来源'})).status,201);assert.equal(C.contactAttempt(x.db,a.body.record.id).receipt_revision,2);assert.equal(C.contactCase(x.db,c.id).status,'waiting');verifyContact(x.db);});
test('failure enters named manual takeover; retry and delay require an explicit next action and date',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x);await attempt(x,c,g,{result:'no_answer',result_note:'无人接听，明确人工跟进'});assert.equal(C.contactCase(x.db,c.id).status,'handoff');assert.equal(C.contactCase(x.db,c.id).owner_id,'front');assert.equal((await event(x,c,'retry')).status,422);assert.equal((await event(x,c,'retry',{...fields()})).status,422);const {owner_id,...f}=fields();assert.equal((await event(x,c,'retry',f)).status,201);assert.equal((await event(x,c,'defer',{...f,next_action:'客户明确延期后再联系'})).status,201);verifyContact(x.db);});
test('owner transfer preserves creator, original attempt and independent appointment owner',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),a=await appointment(x,c);assert.equal((await event(x,c,'assign',{owner_id:'professional'},x.m)).status,201);assert.equal(C.contactCase(x.db,c.id).created_by,'front');assert.equal(C.customerAppointment(x.db,a.id).owner_id,'front');assert.equal((await attempt(x,c,g)).status,403);assert.equal((await attempt(x,c,g,{},x.pro)).status,201);verifyContact(x.db);});
test('withdrawal is terminal and immediately blocks new actual contacts and previous cached replay',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),i={expected_revision:c.revision,expected_sequence:C.contactSequence(x.db,'a'),...actual(g)},key='contact-fixed-replay',p='/cases/'+c.id+'/attempts',a=await write(x,p,i,x.f,key);assert.equal(a.status,201);assert.deepEqual((await write(x,p,i,x.f,key)).body,a.body);assert.equal((await write(x,'/consents/'+g.id+'/events',{action:'revoke',expected_revision:1,...note})).status,201);assert.equal((await write(x,p,i,x.f,key)).status,409);assert.equal((await write(x,'/consents/'+g.id+'/events',{action:'grant',expected_revision:2,...note})).status,422);assert.equal(x.db.prepare('SELECT count(*) n FROM contact_attempts').get().n,1);verifyContact(x.db);});
test('actual receipts remain recordable after later withdrawal without restoring permission to contact',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),a=(await attempt(x,c,g)).body.record;await write(x,'/consents/'+g.id+'/events',{action:'revoke',expected_revision:1,...note});assert.equal((await receipt(x,a)).status,201);assert.equal((await attempt(x,c,g)).status,409);verifyContact(x.db);});
test('customer/store/guardian boundaries protect consent address, workflow and writes',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x);for(const path of ['/cases/'+c.id,'/consents/'+g.id,'/customers/one/options'])assert.equal((await x.request('/api/contacts'+path,x.parent)).status,403);assert.equal((await x.request('/api/contacts/cases/'+c.id,await x.login('other'))).status,404);assert.equal((await write(x,'/consents',{customer_id:'other-child',...consentFields()})).status,404);const other=await grant(x,{customer_id:'two'});assert.equal((await attempt(x,c,other)).status,409);});
test('appointment is a recorded intention; rescheduling preserves old dates and does not occupy training resources',async t=>{const x=await setup(t),c=await contact(x),tables=['schedule_booking_events','schedule_slot_events','training_session_events','payment_events'],before=tables.map(n=>x.db.prepare('SELECT * FROM '+n).all()),a=await appointment(x,c);const i=appointmentFields();delete i.owner_id;assert.equal((await ae(x,a,'reschedule',i)).status,201);assert.equal(C.customerAppointment(x.db,a.id).history[1].starts_at,a.starts_at);assert.deepEqual(tables.map(n=>x.db.prepare('SELECT * FROM '+n).all()),before);verifyContact(x.db);});
test('appointment never automatically marks absent; early absence fails and manual cancellation preserves intent',async t=>{const x=await setup(t),c=await contact(x),a=await appointment(x,c),before=all(x.db);assert.equal(C.customerAppointment(x.db,a.id).status,'planned');assert.deepEqual(all(x.db),before);assert.equal((await ae(x,a,'no_show')).status,422);assert.equal((await ae(x,a,'cancel')).status,201);assert.equal((await ae(x,a,'reschedule',appointmentFields())).status,422);verifyContact(x.db);});
test('contact cancellation blocks unhandled appointments; contact resolution may retain explicitly explained future appointment',async t=>{const x=await setup(t),c=await contact(x),a=await appointment(x,c),end={resolution_reason:'已明确处理',next_step:'保留已确认预约，按明确日期到店',followup:null};assert.equal((await event(x,c,'cancel',end)).status,409);assert.equal((await event(x,c,'resolve',end)).status,201);assert.equal(C.customerAppointment(x.db,a.id).status,'planned');assert.equal((await ae(x,a,'cancel')).status,201);assert.equal((await event(x,c,'retry')).status,422);verifyContact(x.db);});
test('arrival requires an existing same-customer visit instead of marking delivered, arrived or clinically complete',async t=>{const x=await setup(t),c=await contact(x),a=await appointment(x,c);assert.equal((await ae(x,a,'arrive',{visit_id:'missing',arrived_at:now()})).status,409);const v=(await x.request('/api/customers/one/visits',{...x.f,method:'POST',data:{purpose:'明确到店（虚构）',cycle_ids:[]}})).body.visit;assert.equal((await ae(x,a,'arrive',{visit_id:v.id,arrived_at:now()})).status,201);assert.equal(C.contactCase(x.db,c.id).status,'open');assert.equal(x.db.prepare('SELECT status FROM visits WHERE id=?').get(v.id).status,'registered');verifyContact(x.db);});
test('marketing contacts cannot masquerade as service appointments',async t=>{const x=await setup(t),c=await contact(x,{purpose:'marketing'});assert.equal((await write(x,'/cases/'+c.id+'/appointments',{expected_case_revision:c.revision,...appointmentFields()})).status,422);assert.equal(x.db.prepare('SELECT count(*) n FROM customer_appointments').get().n,0);});
test('explicit review source freezes cycle/version and later source edits require a new contact',async t=>{const x=await setup(t),cycle=(await x.request('/api/customers/one/cycles',{...x.m,method:'POST',data:{type:'followup',goal:'明确需求'}})).body.cycle,c=L.createLongitudinalCase(x.db,'a','one',{cycle_id:cycle.id,cycle_version:1,title:'明确档案',baseline_note:'未取得指标',goal_note:'人工跟进',source_note:'人工来源',manifest:L.emptyLongitudinalManifest(),reason:'明确依据'},'professional');L.longitudinalCaseEvent(x.db,c.id,{action:'activate',...note},'professional');const p=L.createReviewPlan(x.db,c.id,{due_date:'2026-10-20',purpose:'明确复查',items_note:'明确项目来源',owner_id:'professional',source_note:'专业人员来源',manifest:L.emptyLongitudinalManifest(),...note},'professional'),ct=await contact(x,{purpose:'followup',source:{kind:'review',id:p.id,version:null,revision:1}}),g=await grant(x);assert.equal(ct.cycle_id,cycle.id);L.reviewPlanEvent(x.db,p.id,{action:'pause',...note},'professional');assert.equal((await attempt(x,ct,g)).status,409);verifyContact(x.db);});
test('fixed review appointment arrival rejects a visit capturing a different demand version',async t=>{const x=await setup(t),cy=(await x.request('/api/customers/one/cycles',{...x.m,method:'POST',data:{type:'followup',goal:'需求'}})).body.cycle,c=L.createLongitudinalCase(x.db,'a','one',{cycle_id:cy.id,cycle_version:1,title:'档案',baseline_note:'未取得资料',goal_note:'核对',source_note:'来源',manifest:L.emptyLongitudinalManifest(),reason:'明确'},'professional');L.longitudinalCaseEvent(x.db,c.id,{action:'activate',...note},'professional');const p=L.createReviewPlan(x.db,c.id,{due_date:'2026-10-20',purpose:'复查',items_note:'项目说明',owner_id:'professional',source_note:'来源',manifest:L.emptyLongitudinalManifest(),...note},'professional'),ct=await contact(x,{purpose:'followup',source:{kind:'review',id:p.id,version:null,revision:1}}),a=await appointment(x,ct),wrong=(await x.request('/api/customers/one/visits',{...x.f,method:'POST',data:{purpose:'到店',cycle_ids:[]}})).body.visit;assert.equal((await ae(x,a,'arrive',{visit_id:wrong.id,arrived_at:now()})).status,409);const right=(await x.request('/api/customers/one/visits',{...x.f,method:'POST',data:{purpose:'到店',cycle_ids:[cy.id]}})).body.visit;assert.equal((await ae(x,a,'arrive',{visit_id:right.id,arrived_at:now()})).status,201);verifyContact(x.db);});
test('unknown clinical/notification flags, duplicate or malformed source, future actual and false receipt times fail',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x);for(const e of [{send_now:true},{read:true},{occurred_at:future()},{result:'read'}])assert.equal((await attempt(x,c,g,e)).status,422);assert.equal((await write(x,'/cases',{customer_id:'one',purpose:'followup',source:{...source(),extra:1},source_note:'来源',...fields()})).status,422);const a=(await attempt(x,c,g)).body.record;assert.equal((await receipt(x,a,{occurred_at:'2020-01-01T00:00:00.000Z'})).status,422);assert.equal((await receipt(x,a,{source:'automatic'})).status,422);});
test('audit failure atomically removes attempt, paired case event, idempotency and sequence',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),before=all(x.db),seq=C.contactSequence(x.db,'a');x.db.exec("CREATE TRIGGER fail_contact_audit BEFORE INSERT ON audit_events WHEN NEW.action='contacts.attempt' BEGIN SELECT RAISE(ABORT,'test rejection'); END");assert.equal((await attempt(x,c,g)).status,500);assert.deepEqual(all(x.db),before);assert.equal(C.contactSequence(x.db,'a'),seq);});
test('store sequence and case/receipt revision conflicts prevent duplicate or stale writes',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x);assert.equal((await attempt(x,c,g,{expected_sequence:0})).status,409);const a=(await attempt(x,c,g)).body.record;assert.equal((await attempt(x,c,g,{expected_revision:1})).status,409);await receipt(x,a);assert.equal((await receipt(x,a,{expected_receipt_revision:0})).status,409);});
test('full list paging uses fixed sequence and does not truncate totals beyond thirty',async t=>{const x=await setup(t);for(let n=0;n<32;n++)await contact(x,{title:'联系 '+n});const r=(await x.request('/api/contacts/cases?limit=30',x.f)).body;assert.equal(r.total,32);assert.equal(r.items.length,30);assert.equal((await x.request('/api/contacts/cases?offset=30',x.f)).status,422);assert.equal((await x.request('/api/contacts/cases?offset=30&expected_sequence='+r.sequence,x.f)).body.items.length,2);await grant(x);assert.equal((await x.request('/api/contacts/cases?offset=30&expected_sequence='+r.sequence,x.f)).status,409);});
test('overdue is a read projection and never resolves failures or appointments',async t=>{const x=await setup(t),c=await contact(x,{due_at:'2020-01-01T00:00:00.000Z'}),before=all(x.db),r=(await x.request('/api/contacts/cases?status=overdue',x.f)).body;assert.equal(r.total,1);assert.equal(r.items[0].status,'open');assert.deepEqual(all(x.db),before);});
test('native guards enforce immutable authorization, separate purpose and paired failure transitions',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x);assert.throws(()=>x.db.prepare('UPDATE contact_consents SET category=? WHERE id=?').run('marketing',g.id),/immutable/);assert.throws(()=>C.contactCaseEvent(x.db,c.id,{action:'failed',...fields(),attempt_id:null},'front'),/transition/);assert.throws(()=>transaction(x.db,()=>C.recordContactAttempt(x.db,c.id,{...actual(g),consent_revision:2},'front')),/consent/);verifyContact(x.db);});
test('recovery rejects a false receipt, altered takeover state and later grant substituted into old attempt',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),a=(await attempt(x,c,g,{result:'failed'})).body.record;verifyContact(x.db);tamper(x.db,'contact_case_events',"UPDATE contact_case_events SET action='attempt',status='waiting' WHERE action='failed'");assert.throws(()=>verifyContact(x.db),/核对失败/);});
test('session withdrawal during request body waiting blocks a previous cached attempt replay',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),path='/api/contacts/cases/'+c.id+'/attempts',i={expected_sequence:C.contactSequence(x.db,'a'),expected_revision:c.revision,...actual(g)},key='pending-contact-replay';assert.equal((await x.request(path,{...x.f,method:'POST',data:i,key})).status,201);const data=JSON.stringify(i),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.f.cookie,'X-CSRF-Token':x.f.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{x.db.prepare("DELETE FROM sessions WHERE user_id='front'").run();req.end(data.slice(10));},20);});assert.equal(status,401);assert.equal(x.db.prepare('SELECT count(*) n FROM contact_attempts').get().n,1);});
test('consent withdrawal during body waiting blocks actual recording and leaves journal unchanged',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),path='/api/contacts/cases/'+c.id+'/attempts',i={expected_sequence:C.contactSequence(x.db,'a'),expected_revision:c.revision,...actual(g)},data=JSON.stringify(i),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.f.cookie,'X-CSRF-Token':x.f.csrf,'Idempotency-Key':'pending-consent','Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{C.contactConsentEvent(x.db,g.id,{action:'revoke',...note},'manager');req.end(data.slice(10));},20);});assert.equal(status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM contact_attempts').get().n,0);verifyContact(x.db);});
test('schema29 backup restores all eight contact tables and revokes sessions',async t=>{const x=await setup(t,{persist:true}),g=await grant(x),c=await contact(x),a=(await attempt(x,c,g)).body.record;await receipt(x,a);await appointment(x,c);const before=all(x.db),b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,38);const r=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(r.database);assert.deepEqual(all(d),before);assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyContact(d);d.close();});
test('schema28 upgrade preserves prior rows and adds no consent, message or appointment',t=>{const dir=mkdtempSync(join(tmpdir(),'contact-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,28)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('old','old')");d.close();const u=openDatabase(path);assert.equal(u.prepare('SELECT count(*) n FROM stores').get().n,1);for(const n of C.contactTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifyContact(u);u.close();});
test('timeline links contact, actual, receipt and appointment without exposing consent address to guardians',async t=>{const x=await setup(t),g=await grant(x),c=await contact(x),a=(await attempt(x,c,g)).body.record;await receipt(x,a);await appointment(x,c);const r=await x.request('/api/customers/one/timeline?limit=50',x.f);assert.equal(r.status,200);for(const k of ['contact_case','contact_attempt','contact_receipt','customer_appointment'])assert.ok(r.body.items.some(e=>e.kind===k));assert.equal(JSON.stringify(r.body).includes(g.address),false);});
import {seedDemoScenarios} from '../src/demo-data.mjs';
import {seedDemoContact} from '../src/demo-contact.mjs';
test('synthetic contact stages append only new contact history and repeat preserves all human edits',async t=>{const x=await fixture(t),d=x.db;d.exec("INSERT INTO stores VALUES('store-a','演示')");for(const [id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');seedDemoScenarios(d);const names=['customers','service_cycles','cycle_versions','visits','work_tasks','guardian_links','document_versions'],before=names.map(n=>d.prepare('SELECT * FROM '+n).all());assert.equal(seedDemoContact(d).cases,4);assert.deepEqual(names.map(n=>d.prepare('SELECT * FROM '+n).all()),before);const a=all(d);assert.equal(seedDemoContact(d).cases,0);assert.deepEqual(all(d),a);verifyContact(d);});
test('native guards cannot rewrite original appointment details at arrival or classify a future interval absent',async t=>{const x=await setup(t),c=await contact(x),a=await appointment(x,c);assert.throws(()=>C.customerAppointmentEvent(x.db,a.id,{action:'no_show',...note},'front'),/absence/);const first=x.db.prepare('SELECT * FROM customer_appointment_events WHERE appointment_id=?').get(a.id);assert.throws(()=>x.db.prepare('INSERT INTO customer_appointment_events('+Object.keys(first).join(',')+') VALUES('+Object.keys(first).map(()=>'?').join(',')+')').run(...Object.values({...first,id:crypto.randomUUID(),revision:2,sequence:C.contactSequence(x.db,'a')+1,action:'cancel',status:'cancelled',place_note:'偷改原地点'})),/transition/);verifyContact(x.db);});
test('contact work routes preserve existing family contact create/list/edit and never infer permission',async t=>{const x=await fixture(t),u=await x.login('front'),i={name:'家人（虚构）',relationship:'演示联系人',phone:'000-00001',source:'guardian_report',note:'仅联系资料',reason:'演示登记'};let r=await x.request('/api/customers/one/contacts',{...u,method:'POST',data:i});assert.equal(r.status,201);const id=r.body.contact.id;assert.equal((await x.request('/api/customers/one/contacts',u)).body.items[0].id,id);r=await x.request('/api/contacts/'+id,{...u,method:'POST',data:{...i,active:false,expected_revision:1}});assert.equal(r.status,200);assert.equal((await x.request('/api/customers/one/contact-work?kind=consents',u)).body.total,0);assert.equal(x.db.prepare('SELECT count(*) n FROM contact_consents').get().n,0);});
