import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
import {paymentTables,orderPayments,verifyPayments,insertPayment} from '../src/payments.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import {entitlementTables,entitlementPackage,entitlementAccount,entitlementEvent,entitlementSummary,createEntitlementAccount,insertEntitlementEvent,insertEntitlementPackageVersion} from '../src/entitlements.mjs';
import {verifyEntitlements} from '../src/entitlements-recovery.mjs';
import {createTrainingProject,createTrainingPlan,insertTrainingPlanVersion,insertTrainingPlanEvent} from '../src/training.mjs';
const packageInput=(extra={})=>({code:'SYNTHETIC-'+crypto.randomUUID(),name:'人工权益样例（虚构）',kind:'count',status:'active',service_scope:'虚构服务范围；不是专业方案',source_note:'仅业务登记演示，未知规则不推导',paid_note:null,gift_note:null,validity_note:null,deduction_note:null,freeze_note:null,reversal_note:null,refund_note:null,reason:'明确虚构依据',...extra});
const grant=(extra={})=>({origin:'paid',quantity:8,valid_start:null,valid_end:null,basis_reference:'SYNTHETIC-'+crypto.randomUUID(),basis_note:'明确人工购买或赠送原来源（虚构）',document_version_id:null,attachment_id:null,occurred_at:new Date().toISOString(),note:'明确权益登记（虚构）',reason:'明确虚构依据',...extra});
async function setup(t,{persist=false,kind='count'}={}){const x=await fixture(t,{persist}),m=await x.login('manager'),f=await x.login('front'),pro=await x.login('professional'),r=await x.request('/api/entitlements/packages',{...m,method:'POST',data:packageInput({kind})});assert.equal(r.status,201,JSON.stringify(r.body));const c=(await x.request('/api/customers/one/cycles',{...m,method:'POST',data:{type:'training',goal:'虚构训练需求'}})).body.cycle;return {...x,m,f,pro,p:r.body.package,c};}
async function account(x,extra={},who=x.f,key){const opt=(await x.request('/api/entitlements/customers/one/options',x.m)).body;return x.request('/api/customers/one/entitlements',{...who,method:'POST',key,data:{package_id:x.p.id,package_version:x.p.version,cycle_id:x.c.id,cycle_version:1,plan_id:null,plan_version:null,expected_account_count:opt.account_count,expected_customer_sequence:opt.customer_sequence,grant:grant(),...extra}});}
async function event(x,id,action,extra={},who=x.m,key){const a=entitlementAccount(x.db,id);return x.request('/api/entitlements/accounts/'+id+'/events',{...who,method:'POST',key,data:{action,expected_revision:a.revision,expected_customer_sequence:a.customer_sequence,...(action==='grant'?grant():{note:'明确原流水冲销（虚构）',reason:'明确纠正依据'}),...extra}});}
async function ready(x,extra={}){const r=await account(x,extra);assert.equal(r.status,201,JSON.stringify(r.body));return r.body;}
function rows(db){return Object.fromEntries(entitlementTables.map(n=>[n,db.prepare('SELECT * FROM '+n).all()]));}
function tamper(db,table,query,args=[]){const guard=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(table+'_no_update').sql;db.exec('DROP TRIGGER '+table+'_no_update');db.prepare(query).run(...args);db.exec(guard);}

test('purchase and gift have independent balances and unchanged acquisition/rule sources',async t=>{const x=await setup(t),r=await ready(x);const gift=(await event(x,r.account.id,'grant',{origin:'gift',quantity:3},x.f)).body.event,a=entitlementAccount(x.db,r.account.id);assert.equal(a.balances.paid.remaining,8);assert.equal(a.balances.gift.remaining,3);assert.equal(a.balances.paid.periods_retained,null);assert.equal(a.package.deduction_note,null);assert.equal(gift.origin,'gift');assert.equal(x.db.prepare('SELECT status FROM service_cycles WHERE id=?').get(x.c.id).status,'draft');assert.equal(x.db.prepare('SELECT count(*) n FROM payment_events').get().n,0);verifyEntitlements(x.db);});
test('period records keep explicit dates independently for paid/gift and reverse the complete original interval',async t=>{const x=await setup(t,{kind:'period'}),dates={quantity:null,valid_start:'2024-02-29',valid_end:'2024-03-01'},r=await ready(x,{grant:grant(dates)});await event(x,r.account.id,'grant',grant({...dates,origin:'gift'}));assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:1})).status,422);const rev=await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:null});assert.equal(rev.status,201);assert.equal(rev.body.event.valid_start,'2024-02-29');assert.equal(rev.body.account.balances.paid.remaining,null);assert.equal(rev.body.account.balances.paid.periods_retained,0);assert.equal(rev.body.account.balances.gift.periods_retained,1);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:null})).status,409);verifyEntitlements(x.db);});
test('count correction is append-only, bound to original paid/gift grant and cannot exceed its unreversed units',async t=>{const x=await setup(t),r=await ready(x);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:3},x.f)).status,403);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:3})).status,201);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:6})).status,422);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:5})).status,201);assert.equal(entitlementEvent(x.db,r.event.id).remaining_quantity,0);assert.equal(entitlementAccount(x.db,r.account.id).history.length,3);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:1})).status,409);});
test('later package kind or inactive catalog never replaces fixed acquired rules and old count ledger',async t=>{const x=await setup(t),r=await ready(x),p=entitlementPackage(x.db,x.p.id);const v=await x.request('/api/entitlements/packages/'+p.id+'/versions',{...x.m,method:'POST',data:{...packageInput({kind:'period',status:'inactive',validity_note:'新的人工说明'}),code:undefined,expected_version:p.version}});assert.equal(v.status,201,JSON.stringify(v.body));assert.equal((await account(x)).status,409);assert.equal((await event(x,r.account.id,'grant',{origin:'gift',quantity:2},x.f)).status,201);const a=entitlementAccount(x.db,r.account.id);assert.equal(a.kind,'count');assert.equal(a.package.version,1);assert.equal(a.package.validity_note,null);assert.equal(a.current_package_version,2);verifyEntitlements(x.db);});
test('fixed historic personal plan and demand survive independent adjustments and plan end',async t=>{const x=await setup(t),now=new Date().toISOString(),project=createTrainingProject(x.db,'a',{code:'PROJECT',name:'N',description:'D',instructions:'I',status:'active',reason:'R'},'professional',now),input={cycle_id:x.c.id,cycle_version:1,visit_id:null,title:'P',assessment:'A',goals:'G',owner_id:'professional',source:'staff_record',source_note:'S',items:[{project_id:project.id,project_version:1,instructions:'I'}],document_version_ids:[],attachment_ids:[],note:'N',reason:'R'},p=createTrainingPlan(x.db,'a','one',input,'professional',now);const r=await ready(x,{plan_id:p.plan.id,plan_version:1});insertTrainingPlanVersion(x.db,p.plan.id,{...input,title:'Later'},'professional');insertTrainingPlanEvent(x.db,p.plan.id,{action:'end',note:'N',reason:'R'},'professional');assert.equal(entitlementAccount(x.db,r.account.id).plan_version,1);assert.equal(entitlementAccount(x.db,r.account.id).balances.paid.remaining,8);verifyEntitlements(x.db);});
test('acquisition reference cannot duplicate retained same-customer same-origin rights across accounts, but full correction permits explicit rerecord',async t=>{const x=await setup(t),g=grant({basis_reference:'ORIGINAL-ITEM'}),r=await ready(x,{grant:g});assert.equal((await account(x,{grant:g})).status,409);await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:3});assert.equal((await account(x,{grant:g})).status,409);await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:5});assert.equal((await account(x,{grant:g})).status,201);assert.equal((await account(x,{grant:grant({...g,origin:'gift'})})).status,201);verifyEntitlements(x.db);});
test('staff financial reads and writes stay store scoped; professionals see a source-free technical summary only',async t=>{const x=await setup(t),r=await ready(x,{grant:grant({basis_reference:'PRIVATE-PROOF',basis_note:'PRIVATE-DETAIL'})}),other=await x.login('other'),g=await x.login('parent');assert.equal((await x.request('/api/entitlements/accounts/'+r.account.id,x.pro)).status,403);assert.equal((await x.request('/api/entitlements/packages',x.pro)).status,403);assert.equal((await x.request('/api/customers/one/entitlement-summary',x.pro)).status,200);assert.equal(JSON.stringify((await x.request('/api/customers/one/entitlement-summary',x.pro)).body).includes('PRIVATE'),false);assert.equal((await x.request('/api/entitlements/accounts/'+r.account.id,other)).status,404);assert.equal((await x.request('/api/customers/other-child/entitlement-summary',x.m)).status,404);assert.equal((await x.request('/api/customers/one/entitlement-summary',g)).status,403);assert.equal((await x.request('/api/entitlements/packages',{...x.f,method:'POST',data:packageInput()})).status,403);});
test('strict fields, canonical actual UTC, quantities and leap-date ranges reject invented deduction or automatic rules',async t=>{const x=await setup(t);for(const v of [grant({quantity:0}),grant({quantity:1.5}),grant({quantity:'2'}),grant({quantity:null}),grant({valid_start:'2026-02-30',valid_end:'2026-03-02'}),grant({valid_start:'2026-01-01',valid_end:null}),grant({occurred_at:new Date(Date.now()+100000).toISOString()}),grant({occurred_at:'2026-01-01'}),{...grant(),deduct:1}])assert.equal((await account(x,{grant:v})).status,422);assert.equal((await account(x,{paid_amount:1})).status,422);const r=await ready(x);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:1,origin:'gift'})).status,422);});
test('count and period cannot be mixed and unknown duration does not become a default interval',async t=>{const x=await setup(t,{kind:'period'});assert.equal((await account(x,{grant:grant({quantity:null})})).status,422);assert.equal((await account(x,{grant:grant({quantity:1,valid_start:'2026-01-01',valid_end:'2026-02-01'})})).status,422);assert.equal(entitlementSummary(x.db,'one').total,0);});
test('source context rejects retail cycles, cross-customer or stale standalone demand while retaining explicitly fixed plan sources',async t=>{const x=await setup(t);const c=(await x.request('/api/customers/one/cycles',{...x.m,method:'POST',data:{type:'retail',goal:'R'}})).body.cycle;assert.equal((await account(x,{cycle_id:c.id})).status,422);await x.request('/api/cycles/'+x.c.id+'/versions',{...x.m,method:'POST',data:{expected_version:1,goal:'新需求',source:'employee',revision_reason:'R'}});assert.equal((await account(x)).status,409);assert.equal((await account(x,{cycle_version:2})).status,201);});
test('idempotent initial grant replays after later catalog changes; competing account preview creates a single account',async t=>{const x=await setup(t),opt=(await x.request('/api/entitlements/customers/one/options',x.m)).body,i={package_id:x.p.id,package_version:1,cycle_id:x.c.id,cycle_version:1,plan_id:null,plan_version:null,expected_account_count:0,expected_customer_sequence:0,grant:grant()},key=crypto.randomUUID(),req=k=>x.request('/api/customers/one/entitlements',{...x.f,method:'POST',key:k,data:i});const r=await req(key);assert.equal(r.status,201);insertEntitlementPackageVersion(x.db,x.p.id,{...packageInput({kind:'period'}),code:undefined},'manager');assert.deepEqual((await req(key)).body,r.body);const x2=await setup(t),b=await x2.request('/api/entitlements/customers/one/options',x2.m),j={...i,package_id:x2.p.id,cycle_id:x2.c.id,expected_account_count:b.body.account_count,expected_customer_sequence:b.body.customer_sequence};const results=await Promise.all([1,2].map(()=>x2.request('/api/customers/one/entitlements',{...x2.f,method:'POST',data:j})));assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);});
test('account and shared customer sequence leases refuse silent adoption of other account operations',async t=>{const x=await setup(t),a=await ready(x),b=await ready(x),stale=entitlementAccount(x.db,a.account.id);await event(x,b.account.id,'grant',{origin:'gift',quantity:2});assert.equal((await event(x,a.account.id,'grant',{expected_revision:stale.revision,expected_customer_sequence:stale.customer_sequence})).status,409);const cur=entitlementAccount(x.db,a.account.id),input={action:'reverse',expected_revision:cur.revision,expected_customer_sequence:cur.customer_sequence,source_event_id:a.event.id,quantity:8,note:'N',reason:'R'},rs=await Promise.all([1,2].map(()=>x.request('/api/entitlements/accounts/'+a.account.id+'/events',{...x.m,method:'POST',data:input})));assert.deepEqual(rs.map(r=>r.status).sort(),[201,409]);assert.equal(entitlementAccount(x.db,a.account.id).balances.paid.remaining,0);});
test('catalog and account/grant audit failures roll every root/version/event back then allow retry',async t=>{const x=await setup(t),before=rows(x.db);x.db.exec("CREATE TRIGGER reject_rights_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'entitlement.%' BEGIN SELECT RAISE(ABORT,'synthetic audit failure'); END");assert.equal((await x.request('/api/entitlements/packages',{...x.m,method:'POST',data:packageInput()})).status,500);assert.equal((await account(x)).status,500);assert.deepEqual(rows(x.db),before);x.db.exec('DROP TRIGGER reject_rights_audit');assert.equal((await account(x)).status,201);});
test('reverse audit failure rolls correction, sequence and original balance back and identical retry succeeds once',async t=>{const x=await setup(t),r=await ready(x),a=entitlementAccount(x.db,r.account.id),i={action:'reverse',expected_revision:a.revision,expected_customer_sequence:a.customer_sequence,source_event_id:r.event.id,quantity:2,note:'N',reason:'R'},key=crypto.randomUUID(),req=()=>x.request('/api/entitlements/accounts/'+a.id+'/events',{...x.m,method:'POST',key,data:i});x.db.exec("CREATE TRIGGER reject_reverse_audit BEFORE INSERT ON audit_events WHEN NEW.action='entitlement.reverse' BEGIN SELECT RAISE(ABORT,'audit'); END");assert.equal((await req()).status,500);assert.equal(entitlementAccount(x.db,a.id).balances.paid.remaining,8);x.db.exec('DROP TRIGGER reject_reverse_audit');const a1=await req(),a2=await req();assert.equal(a1.status,201);assert.deepEqual(a2.body,a1.body);});
test('fixed source document/attachment versions retain old evidence; revoked attachment blocks new grants but permits correcting existing rights',async t=>{const x=await setup(t),doc=(await x.request('/api/customers/one/documents',{...x.m,method:'POST',data:{title:'D',kind:'general',content:'V1',source:'employee',reason:'R',attachment_ids:[]}})).body;assert.ok(doc);const upload=await fetch(x.origin+'/api/customers/one/attachments',{method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'text/plain','X-File-Name':encodeURIComponent('synthetic.txt')},body:'synthetic source'}),file=await upload.json();const did=doc.document?.id;const aid=file.attachment?.id||file.id;assert.ok(did&&aid,JSON.stringify({doc,file}));const r=await ready(x,{grant:grant({document_version_id:did,attachment_id:aid})});await x.request('/api/attachments/'+aid+'/revoke',{...x.m,method:'POST',data:{reason:'R'}});assert.equal((await event(x,r.account.id,'grant',{attachment_id:aid})).status,422);assert.equal((await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:1})).status,201);assert.equal(entitlementEvent(x.db,r.event.id).document_version_id,did);verifyEntitlements(x.db);});
test('a revoked pending reception request and forced initial password cannot write acquisitions',async t=>{const x=await setup(t),opt=(await x.request('/api/entitlements/customers/one/options',x.m)).body,i={package_id:x.p.id,package_version:1,cycle_id:x.c.id,cycle_version:1,plan_id:null,plan_version:null,expected_account_count:opt.account_count,expected_customer_sequence:opt.customer_sequence,grant:grant()},body=JSON.stringify(i);x.db.prepare('INSERT INTO user_security VALUES (?,1,1)').run('front');assert.equal((await account(x)).status,403);x.db.prepare('UPDATE user_security SET must_change_password=0 WHERE user_id=?').run('front');const r=await new Promise((resolve,reject)=>{const req=httpRequest(x.origin+'/api/customers/one/entitlements',{method:'POST',headers:{Cookie:x.f.cookie,'X-CSRF-Token':x.f.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}},res=>{let out='';res.on('data',s=>out+=s);res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.write(body.slice(0,8));setTimeout(()=>{x.db.prepare('DELETE FROM sessions WHERE user_id=?').run('front');req.end(body.slice(8));},20);});assert.equal(r,401);assert.equal(x.db.prepare('SELECT count(*) n FROM entitlement_accounts').get().n,0);});
test('native append-only, live actor, quantities and source copying guards protect the ledger independently of API',async t=>{const x=await setup(t),r=await ready(x);for(const n of entitlementTables){assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+(n==='entitlement_events'?'note':'created_at')+'='+"'changed'"),/immutable/);}assert.throws(()=>insertEntitlementEvent(x.db,r.account.id,{...grant({quantity:1.5}),action:'grant'},'manager'),/CHECK|mismatch/);assert.throws(()=>insertEntitlementEvent(x.db,r.account.id,{...grant(),action:'grant'},'professional'),/actor/);assert.throws(()=>insertEntitlementEvent(x.db,r.account.id,{action:'reverse',source_event_id:r.event.id,quantity:9,note:'N',reason:'R'},'manager'),/capacity/);verifyEntitlements(x.db);});
test('full totals and bounded history over one hundred do not cap balances or omit recoverable references',async t=>{const x=await setup(t),r=await ready(x);for(let n=0;n<105;n++)insertEntitlementEvent(x.db,r.account.id,{...grant({origin:'gift',quantity:1}),action:'grant'},'manager');const first=(await x.request('/api/entitlements/accounts/'+r.account.id+'?limit=50',x.m)).body.account;assert.equal(first.total,106);assert.equal(first.next_offset,50);assert.equal(first.history.length,50);assert.equal(first.balances.gift.remaining,105);assert.equal((await x.request('/api/entitlements/accounts/'+r.account.id+'?limit=50&offset=100',x.m)).body.account.history.length,6);assert.equal((await x.request('/api/customers/one/entitlement-summary',x.pro)).body.totals.find(x=>x.kind==='count').gift.retained,105);verifyEntitlements(x.db);});
test('customer timeline uses fixed acquisition sources and hides entitlement events from professionals and guardians',async t=>{const x=await setup(t),r=await ready(x);await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:2});const items=(await x.request('/api/customers/one/timeline?kind=entitlement',x.m)).body.items;assert.equal(items.length,2);assert.equal(items[0].details.package_version,1);assert.equal((await x.request('/api/customers/one/timeline?kind=entitlement',x.pro)).status,403);assert.equal((await x.request('/api/customers/one/timeline',x.pro)).body.items.some(e=>e.kind==='entitlement'),false);});
test('all four tables survive verified backup and independent restore with sessions cleared',async t=>{const x=await setup(t,{persist:true}),r=await ready(x);await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:2});const b=await createBackup(x.path,join(x.dir,'backup')),restored=await restoreBackup(b.backup,join(x.dir,'restored')),copy=openDatabase(restored.database);try{assert.deepEqual(rows(copy),rows(x.db));assert.deepEqual(entitlementSummary(copy,'one'),entitlementSummary(x.db,'one'));assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyEntitlements(copy);}finally{copy.close();}});
test('recovery rejects changed historical root actor, orphan initial source and over-reversed quantity even with guards reinstated',async t=>{const x=await setup(t,{persist:true}),r=await ready(x);tamper(x.db,'entitlement_accounts','UPDATE entitlement_accounts SET created_by=? WHERE id=?',['manager',r.account.id]);await assert.rejects(()=>createBackup(x.path,join(x.dir,'bad')),/权益/);tamper(x.db,'entitlement_accounts','UPDATE entitlement_accounts SET created_by=? WHERE id=?',['front',r.account.id]);const v=await event(x,r.account.id,'reverse',{source_event_id:r.event.id,quantity:1});tamper(x.db,'entitlement_events','UPDATE entitlement_events SET quantity=9 WHERE id=?',[v.body.event.id]);assert.throws(()=>verifyEntitlements(x.db),/权益/);});
test('same-millisecond catalog/acquisition and cross-account reversal/rerecord replay by captured sequences',async t=>{const x=await setup(t),now=new Date().toISOString(),input={package_id:x.p.id,package_version:1,cycle_id:x.c.id,cycle_version:1,plan_id:null,plan_version:null,grant:grant({basis_reference:'SAME',occurred_at:now})},r=createEntitlementAccount(x.db,'a','one',input,'front',now);insertEntitlementPackageVersion(x.db,x.p.id,packageInput(),'manager',now);insertEntitlementEvent(x.db,r.account.id,{action:'reverse',source_event_id:r.event.id,quantity:8,note:'N',reason:'R'},'manager',now);const r2=createEntitlementAccount(x.db,'a','one',{...input,package_version:2},'front',now);verifyEntitlements(x.db);tamper(x.db,'entitlement_accounts','UPDATE entitlement_accounts SET package_version=? WHERE id=?',[2,r.account.id]);assert.throws(()=>verifyEntitlements(x.db),/交叉顺序/);assert.ok(r2.account.id!==r.account.id);});
test('nonempty schema24 upgrade preserves every existing row and does not invent acquisitions or deductions',async t=>{const dir=mkdtempSync(join(tmpdir(),'entitlement-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const n of readdirSync('migrations').sort().slice(0,24)){db.exec(readFileSync(join('migrations',n),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(n,new Date().toISOString());}db.exec("INSERT INTO stores VALUES ('a','A');");db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('manager','manager','Manager',hashPassword('synthetic-password'),'manager','a');db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run('old','a','Old',null,null,null,new Date().toISOString(),'manager');const names=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='schema_migrations' ORDER BY name").all().map(x=>x.name),before=names.map(n=>db.prepare('SELECT * FROM '+n).all());db.close();db=openDatabase(path);try{names.forEach((n,i)=>assert.deepEqual(db.prepare('SELECT * FROM '+n).all(),before[i]));entitlementTables.forEach(n=>assert.equal(db.prepare('SELECT count(*) n FROM '+n).get().n,0));assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,39);verifyEntitlements(db);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
test('synthetic paid/gift, period, partial/full reversal and historical rules initialize once without changing previous business ledgers',async t=>{const db=openDatabase(':memory:');try{db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-password'),role,'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment','seedDemoAftercare','seedDemoAftercareWork','seedDemoReplacements','seedDemoDispositions','seedDemoRefunds','seedDemoParameters','seedDemoTraining'])demo[fn](db);const names=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='audit_events' AND name NOT LIKE 'entitlement_%' ORDER BY name").all().map(x=>x.name),before=names.map(n=>db.prepare('SELECT * FROM '+n).all());assert.deepEqual(demo.seedDemoEntitlements(db),{packages:2,package_versions:3,accounts:3,events:8});names.forEach((n,i)=>assert.deepEqual(db.prepare('SELECT * FROM '+n).all(),before[i]));const old=rows(db);assert.deepEqual(demo.seedDemoEntitlements(db),{packages:0,package_versions:0,accounts:0,events:0});assert.deepEqual(rows(db),old);verifyEntitlements(db);}finally{db.close();}});
