import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
import {paymentTables,orderPayments,verifyPayments,insertPayment} from '../src/payments.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import {familyTables,familySequence,practice,familyPractice,createPractice,practiceVersion,practiceEvent,reportPractice,reviewPractice,createReassessment,reassessmentEvent,canonicalManifest} from '../src/family-training.mjs';
import {verifyFamilyTraining} from '../src/family-training-recovery.mjs';
import {createTrainingProject,createTrainingPlan,insertTrainingPlanEvent,trainingPlan} from '../src/training.mjs';
const note={note:'人工安排（虚构）',reason:'明确来源（虚构）'},fields={title:'家庭观察练习（虚构）',instructions:'专业人员明确填写给家长的演示说明',due_date:null,source_note:'内部布置依据 PRIVATE-SOURCE',reason:note.reason};
async function setup(t,{persist=false}={}){const x=await fixture(t,{persist});x.m=await x.login('manager');x.f=await x.login('front');x.pro=await x.login('professional');x.parent=await x.login('parent');x.plans={};const pr=createTrainingProject(x.db,'a',{code:'DEMO-P',name:'虚构项目',description:'虚构',instructions:'明确说明',status:'active',reason:'虚构依据'},'professional');for(const id of ['one','two']){const c=(await x.request('/api/customers/'+id+'/cycles',{...x.m,method:'POST',data:{type:'training',goal:'虚构训练需求'}})).body.cycle,p=createTrainingPlan(x.db,'a',id,{cycle_id:c.id,cycle_version:1,visit_id:null,title:'虚构个人计划',assessment:'PRIVATE-ASSESSMENT',goals:'PRIVATE-GOALS',owner_id:'professional',source:'staff_record',source_note:'PRIVATE-PLAN',items:[{project_id:pr.id,project_version:1,instructions:'明确'}],document_version_ids:[],attachment_ids:[],...note},'professional');insertTrainingPlanEvent(x.db,p.plan.id,{action:'confirm',...note},'professional');x.plans[id]=trainingPlan(x.db,p.plan.id);}return x;}
async function write(x,path,data,who=x.pro,key){return x.request(path,{...who,method:'POST',key,data:{expected_sequence:familySequence(x.db,'a'),...data}});}
async function draft(x,extra={}){const p=x.plans.one,r=await write(x,'/api/family-training/practices',{...fields,plan_id:p.id,plan_version:p.version,expected_plan_revision:p.revision,recipient_id:'parent',session_id:null,session_revision:null,...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function event(x,a,action,who=x.pro,key){const r=practice(x.db,a.id);return write(x,'/api/family-training/practices/'+a.id+'/events',{expected_revision:r.revision,action,...note},who,key);}
async function published(x){const a=await draft(x),r=await event(x,a,'publish');assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
const actual=extra=>({source:'guardian_self_report',source_note:'家长明确自报',occurred_at:new Date(Date.now()-1000).toISOString(),minutes:null,completion:'unknown',feedback:'实际情况（虚构）',contact_requested:false,reason:'本人自报依据',...extra});
async function report(x,a,extra={},who=x.parent,key){const r=familyPractice(x.db,a.id,'parent'),data={...actual(),expected_revision:r?.revision||practice(x.db,a.id).revision,expected_version:r?.version||practice(x.db,a.id).released_version,...extra};if(who===x.parent)data.expected_report_count=r?.report_count||0;else data.expected_sequence=familySequence(x.db,'a');return x.request('/api/family-training/practices/'+a.id+'/reports',{...who,method:'POST',key,data});}
async function review(x,id,extra={}){return write(x,'/api/family-training/reports/'+id+'/reviews',{expected_review_revision:x.db.prepare('SELECT coalesce(max(revision),0) n FROM practice_reviews WHERE report_id=?').get(id).n,status:'noted',internal_note:'PRIVATE-REVIEW',share_feedback:false,family_feedback:null,followup:null,reason:'人工反馈依据',...extra});}
const manifest=()=>({sessions:[],reports:[],documents:[],followup:null});
async function assess(x,extra={}){const p=x.plans.one;return write(x,'/api/family-training/reassessments',{title:'阶段人工复评（虚构）',source_note:'人工明确来源',comparison_note:'未取得统一检查指标，记录人工对比',assessment_note:'阶段人工记录',next_step:'联系门店核对下一步',direction:'needs_information',manifest:manifest(),reason:note.reason,plan_id:p.id,plan_version:p.version,expected_plan_revision:p.revision,...extra});}
const all=db=>Object.fromEntries(familyTables.map(t=>[t,db.prepare('SELECT * FROM '+t+' ORDER BY rowid').all()]));
function tamper(db,t,sql){const trig=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(t+'_no_update').sql;db.exec('DROP TRIGGER '+t+'_no_update');db.exec(sql);db.exec(trig);}

test('family draft is hidden, explicit publication exposes only minimal intended fields',async t=>{const x=await setup(t),a=await draft(x);assert.equal((await x.request('/api/family-training/practices/'+a.id,x.parent)).status,404);await event(x,a,'publish');const r=await x.request('/api/family-training/practices/'+a.id,x.parent);assert.equal(r.status,200);assert.equal(r.body.record.instructions,fields.instructions);assert.equal(r.body.sequence,undefined);for(const secret of ['PRIVATE','owner_id','recipient_id','plan_id','cycle_id','history','documents','attachments'])assert.equal(JSON.stringify(r.body).includes(secret),false,secret);verifyFamilyTraining(x.db);});
test('new draft instructions stay internal until explicitly published',async t=>{const x=await setup(t),a=await published(x);const r=await write(x,'/api/family-training/practices/'+a.id+'/versions',{...fields,title:'新标题 PRIVATE-DRAFT',instructions:'PRIVATE-DRAFT',expected_revision:a.revision});assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(familyPractice(x.db,a.id,'parent').version,1);assert.equal(familyPractice(x.db,a.id,'parent').instructions,fields.instructions);await event(x,a,'publish');assert.equal(familyPractice(x.db,a.id,'parent').version,2);verifyFamilyTraining(x.db);});
test('withdrawal removes family access and close cannot resurface withdrawn contents',async t=>{const x=await setup(t),a=await published(x);await event(x,a,'withdraw',x.m);assert.equal(familyPractice(x.db,a.id,'parent'),null);await event(x,a,'close',x.m);assert.equal(familyPractice(x.db,a.id,'parent'),null);assert.equal((await event(x,a,'publish')).status,409);verifyFamilyTraining(x.db);});
test('closed published practice keeps own history and prevents new actual submissions',async t=>{const x=await setup(t),a=await published(x);assert.equal((await report(x,a)).status,201);await event(x,a,'close');assert.equal(familyPractice(x.db,a.id,'parent').reports.length,1);assert.equal((await report(x,a)).status,409);verifyFamilyTraining(x.db);});
test('revoked recipient authorization blocks reads, new writes, and idempotency replays',async t=>{const x=await setup(t),a=await published(x),key=crypto.randomUUID(),i={...actual(),expected_revision:a.revision,expected_version:1,expected_report_count:0},path='/api/family-training/practices/'+a.id+'/reports';const r=await x.request(path,{...x.parent,method:'POST',data:i,key});assert.equal(r.status,201);x.db.prepare('UPDATE guardian_links SET active=0 WHERE user_id=?').run('parent');assert.equal((await x.request('/api/family-training/practices/'+a.id,x.parent)).status,404);assert.equal((await x.request(path,{...x.parent,method:'POST',data:i,key})).status,404);assert.equal(x.db.prepare('SELECT count(*) n FROM practice_reports').get().n,1);verifyFamilyTraining(x.db);});
test('another authorized parent cannot access a practice intended for the named recipient',async t=>{const x=await setup(t),a=await published(x);x.db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('second','second','second',hashPassword('synthetic-only-password'),'guardian',null);x.db.prepare('INSERT INTO guardian_links(user_id,customer_id,active) VALUES (?,?,1)').run('second','one');const s=await x.login('second');assert.equal((await x.request('/api/family-training/practices/'+a.id,s)).status,404);assert.equal((await x.request('/api/customers/one/family-training',s)).body.total,0);});
test('parent cannot query internal options, reports, reassessments, store-wide listing or internal timeline',async t=>{const x=await setup(t),a=await published(x),r=await assess(x);assert.equal(r.status,201,JSON.stringify(r.body));for(const path of ['/api/family-training/practices','/api/family-training/customers/one/options','/api/family-training/reassessments/'+r.body.record.id,'/api/family-training/reports/nope','/api/customers/one/family-training?kind=reassessments','/api/customers/one/timeline'])assert.ok([403,404].includes((await x.request(path,x.parent)).status),path);assert.equal((await x.request('/api/family-training/practices/'+a.id+'/reports',x.parent)).status,405);});
test('staff transcription provenance is distinct and never appears as parent self report',async t=>{const x=await setup(t),a=await published(x);for(const source of ['guardian_transcript','staff_observation','device_transcript'])assert.equal((await report(x,a,{source,feedback:'PRIVATE-TRANSCRIPT'},x.f)).status,201);assert.equal(familyPractice(x.db,a.id,'parent').reports.length,0);assert.equal((await report(x,a,{source:'staff_observation'})).status,422);assert.equal((await report(x,a,{},x.f)).status,422);verifyFamilyTraining(x.db);});
test('nullable minutes and explicit zero remain distinct; future and invalid times are rejected',async t=>{const x=await setup(t),a=await published(x);assert.equal((await report(x,a,{minutes:null})).status,201);assert.equal((await report(x,a,{minutes:0,completion:'not_done'})).status,201);assert.deepEqual(familyPractice(x.db,a.id,'parent').reports.map(r=>r.minutes),[0,null]);for(const extra of [{minutes:-1},{minutes:1441},{occurred_at:'2030-01-01T00:00:00.000Z'},{occurred_at:'2026-02-30T00:00:00.000Z'},{contact_requested:'true'}])assert.equal((await report(x,a,extra)).status,422);verifyFamilyTraining(x.db);});
test('exact self-report replay is safe and concurrent stale report counter writes only once',async t=>{const x=await setup(t),a=await published(x),key=crypto.randomUUID(),path='/api/family-training/practices/'+a.id+'/reports',i={...actual(),expected_revision:a.revision,expected_version:1,expected_report_count:0};const first=await x.request(path,{...x.parent,method:'POST',data:i,key}),replay=await x.request(path,{...x.parent,method:'POST',data:i,key});assert.equal(first.status,201);assert.deepEqual(first.body,replay.body);assert.equal(JSON.stringify(first.body).includes('PRIVATE'),false);assert.equal((await x.request(path,{...x.parent,method:'POST',data:i,key:crypto.randomUUID()})).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM practice_reports').get().n,1);});
test('private feedback does not replace earlier shared feedback and transcripts cannot be shared',async t=>{const x=await setup(t),a=await published(x),r=await report(x,a);await review(x,r.body.report.id,{share_feedback:true,family_feedback:'给家长的明确反馈'});await review(x,r.body.report.id);const f=familyPractice(x.db,a.id,'parent');assert.equal(f.reports[0].family_feedback,'给家长的明确反馈');assert.equal(JSON.stringify(f).includes('PRIVATE-REVIEW'),false);const p=await report(x,a,{source:'device_transcript'},x.f);assert.equal((await review(x,p.body.report.id,{share_feedback:true,family_feedback:'不得自动发布'})).status,409);verifyFamilyTraining(x.db);});
test('follow-up status requires existing same-cycle task instead of silently generating or completing tasks',async t=>{const x=await setup(t),a=await published(x),r=await report(x,a);assert.equal((await review(x,r.body.report.id,{status:'needs_followup'})).status,422);assert.equal((await review(x,r.body.report.id,{status:'needs_followup',followup:{id:'missing',revision:1}})).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM work_tasks').get().n,0);const task=(await x.request('/api/customers/one/tasks',{...x.m,method:'POST',data:{title:'明确下一任务（虚构）',instructions:'请联系核对',cycle_id:a.cycle_id,cycle_version:a.cycle_version,visit_id:null,assignee_id:'professional',reason:'明确分派'}})).body.task;const feedback=await review(x,r.body.report.id,{status:'needs_followup',followup:{id:task.id,revision:task.revision}});assert.equal(feedback.status,201,JSON.stringify(feedback.body));assert.equal(feedback.body.report.reviews[0].followup_task_id,task.id);const re=await assess(x,{manifest:{...manifest(),followup:{id:task.id,revision:task.revision}}});assert.equal(re.status,201,JSON.stringify(re.body));await x.request('/api/tasks/'+task.id+'/accept',{...x.pro,method:'POST',data:{expected_revision:1,reason:'接收明确任务'}});assert.equal((await write(x,'/api/family-training/reassessments/'+re.body.record.id+'/events',{action:'check',expected_revision:1,...note})).status,409);verifyFamilyTraining(x.db);});
test('owner checks, store masking and manager emergency withdrawal are enforced',async t=>{const x=await setup(t),a=await published(x);assert.equal((await x.request('/api/family-training/practices/'+a.id,await x.login('other'))).status,404);assert.equal((await event(x,a,'publish',x.m)).status,403);assert.equal((await event(x,a,'withdraw',x.f)).status,403);assert.equal((await event(x,a,'withdraw',x.m)).status,201);});
test('plan pause blocks new publication but past actual self-report remains available with warning',async t=>{const x=await setup(t),a=await published(x);insertTrainingPlanEvent(x.db,x.plans.one.id,{action:'pause',...note},'professional');assert.equal(familyPractice(x.db,a.id,'parent').plan_changed,true);assert.equal((await report(x,a)).status,201);await event(x,a,'withdraw');assert.equal((await event(x,a,'publish')).status,409);});
test('reassessment captures report review version; changed sources require explicit new draft',async t=>{const x=await setup(t),a=await published(x),r=await report(x,a),ref={id:r.body.report.id,review_revision:0};const re=await assess(x,{manifest:{...manifest(),reports:[ref]}});assert.equal(re.status,201,JSON.stringify(re.body));await review(x,ref.id);const i={expected_revision:re.body.record.revision,action:'check',...note};assert.equal((await write(x,'/api/family-training/reassessments/'+re.body.record.id+'/events',i)).status,409);verifyFamilyTraining(x.db);});
test('checked reassessment is immutable, linked plan and entitlement histories remain unchanged',async t=>{const x=await setup(t),names=['training_plan_events','training_session_events','entitlement_events','schedule_booking_events'],before=names.map(n=>x.db.prepare('SELECT * FROM '+n).all()),r=await assess(x,{direction:'ending_review'});assert.equal(r.status,201,JSON.stringify(r.body));const id=r.body.record.id,c=await write(x,'/api/family-training/reassessments/'+id+'/events',{expected_revision:1,action:'check',...note});assert.equal(c.status,201,JSON.stringify(c.body));assert.deepEqual(names.map(n=>x.db.prepare('SELECT * FROM '+n).all()),before);assert.equal((await write(x,'/api/family-training/reassessments/'+id+'/events',{expected_revision:2,action:'check',...note})).status,409);verifyFamilyTraining(x.db);});
test('unknown, duplicate and cross-customer reassessment references fail before persistence',async t=>{const x=await setup(t),a=await published(x),r=await report(x,a);for(const m of [{...manifest(),extra:true},{...manifest(),sessions:[{id:'no',revision:1}]},{...manifest(),reports:[{id:r.body.report.id,review_revision:0},{id:r.body.report.id,review_revision:0}]},{...manifest(),documents:['missing']}])assert.ok([422,409].includes((await assess(x,{manifest:m})).status));assert.equal(x.db.prepare('SELECT count(*) n FROM training_reassessments').get().n,0);});
test('native guards reject invalid manifest shape, inappropriate actors and edits to immutable history',async t=>{const x=await setup(t),a=await published(x);assert.throws(()=>reportPractice(x.db,a.id,actual(),'front'));assert.throws(()=>x.db.prepare('UPDATE practice_assignments SET recipient_id=? WHERE id=?').run('manager',a.id),/immutable/);assert.throws(()=>createReassessment(x.db,x.plans.one,{title:'t',source_note:'s',comparison_note:'c',assessment_note:'a',next_step:'n',direction:'needs_information',manifest:{...manifest(),extra:true},reason:'r'},'professional'),/manifest/);});
test('recovery detects altered publication history and source-labelled actual data',async t=>{const x=await setup(t),a=await published(x);await report(x,a);verifyFamilyTraining(x.db);tamper(x.db,'practice_reports',"UPDATE practice_reports SET version=1,assignment_revision=1");assert.throws(()=>verifyFamilyTraining(x.db),/核对失败/);});
test('schema 27 backup restores all eight family tables and excludes sessions',async t=>{const x=await setup(t,{persist:true}),a=await published(x),r=await report(x,a);await review(x,r.body.report.id,{share_feedback:true,family_feedback:'明确反馈'});await assess(x,{manifest:{...manifest(),reports:[{id:r.body.report.id,review_revision:1}]}});const before=all(x.db),b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,42);const rr=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(rr.database);assert.deepEqual(all(d),before);assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyFamilyTraining(d);d.close();});
test('family list totals and page bounds remain complete without exposing store sequence',async t=>{const x=await setup(t);for(let n=0;n<32;n++){const a=await draft(x,{title:'虚构 '+n});await event(x,a,'publish');}const r=await x.request('/api/customers/one/family-training?limit=30',x.parent);assert.equal(r.status,200);assert.equal(r.body.total,32);assert.equal(r.body.items.length,30);assert.equal(r.body.next_offset,30);assert.equal(r.body.sequence,undefined);assert.equal((await x.request('/api/customers/one/family-training?limit=101',x.parent)).status,422);});
test('schema 26 upgrades without rewriting prior business records',t=>{const dir=mkdtempSync(join(tmpdir(),'optical-family-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path),files=readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,26);d.exec('PRAGMA foreign_keys=ON; CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of files){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(f,new Date().toISOString());}d.exec("INSERT INTO stores VALUES('old','old')");const before=d.prepare('SELECT * FROM stores').all();d.close();const u=openDatabase(path);assert.deepEqual(u.prepare('SELECT * FROM stores').all(),before);for(const table of familyTables)assert.equal(u.prepare('SELECT count(*) n FROM '+table).get().n,0);verifyFamilyTraining(u);u.close();});

test('recipient link revoked while request body is pending also blocks a cached self-report replay',async t=>{const x=await setup(t),a=await published(x),key='family-pending-replay',i={...actual(),expected_revision:a.revision,expected_version:1,expected_report_count:0},path='/api/family-training/practices/'+a.id+'/reports';assert.equal((await x.request(path,{...x.parent,method:'POST',data:i,key})).status,201);const data=JSON.stringify(i),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.parent.cookie,'X-CSRF-Token':x.parent.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{x.db.prepare("UPDATE guardian_links SET active=0 WHERE user_id='parent'").run();req.end(data.slice(10));},20);});assert.equal(status,404);assert.equal(x.db.prepare('SELECT count(*) n FROM practice_reports').get().n,1);});
test('report, journal, idempotency and audit roll back together when audit cannot commit',async t=>{const x=await setup(t),a=await published(x),before=all(x.db),seq=familySequence(x.db,'a');x.db.exec("CREATE TRIGGER fail_family_audit BEFORE INSERT ON audit_events WHEN NEW.action='family.report' BEGIN SELECT RAISE(ABORT,'test audit rejection'); END");assert.equal((await report(x,a)).status,500);assert.deepEqual(all(x.db),before);assert.equal(familySequence(x.db,'a'),seq);});
test('fixed historical check document stays selected after later document revision',async t=>{const x=await setup(t);const d=(await x.request('/api/customers/one/documents',{...x.pro,method:'POST',data:{title:'检查资料（虚构）',content:'明确人工记录',source:'external',attachment_ids:[]}})).body.document;await x.request('/api/documents/'+d.record_id+'/versions',{...x.pro,method:'POST',data:{expected_version:1,title:'检查资料 V2（虚构）',content:'后来的内容',source:'external',revision_reason:'明确修订',attachment_ids:[]}});const r=await assess(x,{manifest:{...manifest(),documents:[d.id]}});assert.equal(r.status,201,JSON.stringify(r.body));assert.deepEqual(r.body.record.manifest.documents,[d.id]);verifyFamilyTraining(x.db);});
test('timeline includes internal practice and reassessment fixed versions',async t=>{const x=await setup(t),a=await published(x);await assess(x);const r=await x.request('/api/customers/one/timeline?limit=50',x.m);assert.equal(r.status,200);assert.ok(r.body.items.some(e=>e.kind==='practice'&&e.entity_id===a.id&&e.details.version===1));assert.ok(r.body.items.some(e=>e.kind==='reassessment'));});
test('native store journal sequence cannot skip or reuse another kind sequence',async t=>{const x=await setup(t),a=await published(x),seq=familySequence(x.db,'a');const p=await report(x,a);const r=x.db.prepare('SELECT * FROM practice_reports WHERE id=?').get(p.body.report.id);assert.throws(()=>x.db.prepare('INSERT INTO practice_reports ('+Object.keys(r).join(',')+') VALUES ('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values({...r,id:crypto.randomUUID(),serial:2,sequence:seq})),/journal/);verifyFamilyTraining(x.db);});
test('recovery rejects later report review substituted into same-millisecond reassessment',async t=>{const x=await setup(t),a=await published(x),r=await report(x,a),re=await assess(x,{manifest:{...manifest(),reports:[{id:r.body.report.id,review_revision:0}]}});assert.equal(re.status,201);await review(x,r.body.report.id);const v=x.db.prepare('SELECT * FROM training_reassessment_versions WHERE reassessment_id=?').get(re.body.record.id),m=JSON.parse(v.manifest_json);m.reports[0].review_revision=1;const trig=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='training_reassessment_versions_no_update'").get().sql;x.db.exec('DROP TRIGGER training_reassessment_versions_no_update');x.db.prepare('UPDATE training_reassessment_versions SET manifest_json=? WHERE reassessment_id=?').run(JSON.stringify(m),re.body.record.id);x.db.exec(trig);assert.throws(()=>verifyFamilyTraining(x.db),/核对失败/);});
test('forced-password and inactive guardian cannot read shared feedback or replay submissions',async t=>{const x=await setup(t),a=await published(x);x.db.prepare('INSERT INTO user_security VALUES (?,1,1)').run('parent');assert.equal(familyPractice(x.db,a.id,'parent'),null);assert.equal((await report(x,a)).status,403);x.db.prepare('UPDATE user_security SET must_change_password=0 WHERE user_id=?').run('parent');x.db.prepare('UPDATE users SET active=0 WHERE id=?').run('parent');assert.equal((await x.request('/api/family-training/practices/'+a.id,x.parent)).status,401);});
test('synthetic family stages append to old business history once and preserve human edits on repeat',async t=>{const x=await fixture(t),d=x.db;d.exec("INSERT INTO stores VALUES ('store-a','示例门店')");for(const [id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional'],['demo-practice-parent','guardian']])d.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,role==='guardian'?null:'store-a');for(const fn of [demo.seedDemoScenarios,demo.seedDemoRetail,demo.seedDemoInventory,demo.seedDemoPayments,demo.seedDemoProcessing,demo.seedDemoFulfillment,demo.seedDemoAftercare,demo.seedDemoAftercareWork,demo.seedDemoReplacements,demo.seedDemoDispositions,demo.seedDemoRefunds,demo.seedDemoParameters,demo.seedDemoTraining,demo.seedDemoEntitlements,demo.seedDemoScheduling])fn(d);const names=['training_plan_events','training_session_events','entitlement_events','schedule_booking_events','payment_events','inventory_events','task_events'],before=names.map(n=>d.prepare('SELECT * FROM '+n).all());assert.equal(demo.seedDemoFamilyTraining(d).practices,2);assert.deepEqual(names.map(n=>d.prepare('SELECT * FROM '+n).all()),before);const snapshot=all(d);assert.equal(demo.seedDemoFamilyTraining(d).practices,0);assert.deepEqual(all(d),snapshot);verifyFamilyTraining(d);});
