import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {insertProductVersion} from '../src/retail.mjs';
import {physicalStock} from '../src/stock-ledger.mjs';
const now=()=>new Date().toISOString(),notes={note:'虚构实际办理',reason:'明确原始来源',next_step:'依实际后续办理'},metadata={lot_status:'unknown',lot_code:null,expiry_status:'unknown',expiry_date:null,location_status:'unknown',location_note:null,manufacturer_note:null,source_note:'虚构原收货资料',source_reference:'DEMO-ONLY',...notes},known={...metadata,lot_status:'recorded',lot_code:'DEMO-LOT',expiry_status:'provided',expiry_date:'2099-01-01',location_status:'recorded',location_note:'虚构隔离柜'},supplier={code:'TEST-SUPPLIER',name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构',settlement_note:null,source_note:'虚构',source_reference:'DEMO',status:'active',reason:'虚构'};
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-RECEIPT',name:'虚构实物',category:'lens',brand:null,specification:'原规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201);x.product=z.body.product;P.createSupplier(x.db,'a',supplier,'manager');x.purchase=P.createPurchase(x.db,'a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'虚构收货原采购',purpose_note:'实际用途',source_note:'虚构实际来源',source_reference:'DEMO',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'虚构明确来源',ordered_at:now(),order_reference:'DEMO-ORDER',...notes},action==='approve'?'manager':'front');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];return x;}
const input=(x,over={})=>({order_event_id:x.order.order_event_id,position:1,received_quantity:2,bound_quantity:2,received_at:now(),receiver_label:'虚构收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'虚构实际到货，不是自动验收',...metadata,...over});
async function receipt(x,over={},who=x.f,key=crypto.randomUUID()){const z=await x.request('/api/purchase-receipts',{...who,method:'POST',key,data:{expected_sequence:R.receivingSequence(x.db,'a'),...input(x,over)}});if(z.status===201)x.receipt=z.body.record;return z;}
const eventInput=(x,action,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,...notes,...(action.startsWith('quality_')?{checked_at:now(),requirement_source:'虚构明确人工验收要求，不是默认标准',require_lot:false,require_expiry:false,require_location:false,checks:[{label:'实际外观项目',result:action==='quality_pass'?'pass':'fail'}]}:{}),...(action==='inbound'?{inbound_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision}:{}),...over};};
async function act(x,action,over={},who=x.m,key=crypto.randomUUID()){return x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...who,method:'POST',key,data:eventInput(x,action,over)});}
async function revise(x,over={}){const r=R.receiptRecord(x.db,x.receipt.id);return x.request('/api/purchase-receipts/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,...metadata,...over}});}
const good=z=>assert.equal(z.status,201,JSON.stringify(z.body));
import * as Q from '../src/purchase-quality.mjs';
import {verifyPurchaseQuality} from '../src/purchase-quality-recovery.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
async function base(t,over={}){const x=await setup(t,over);good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound',{inbound_bucket:over.bucket||'available'}));return x;}
const qi=(x,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),receipt_id:r.id,receipt_version_id:r.version_id,quantity:1,source_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,custody_confirmed_at:now(),custody_source:'实际核对原收货箱与本批在库数量（虚构）',observed_at:now(),observation_note:'实际待复检情况（虚构）',source_reference:'DEMO-ACTUAL-CUSTODY',...notes,...over};};
async function caseCreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-quality',{...who,method:'POST',key,data:qi(x,over)});if(z.status===201)x.q=z.body.record;return z;}
const qe=(x,action,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,action,...notes,...(action==='release'?{expected_stock_sequence:c.stock.sequence,expected_outbound_revision:c.stock.outbound_revision}:{checked_at:now(),requirement_source:'本次实际人工要求（虚构），不是通用标准',require_lot:true,require_expiry:true,require_location:true,checks:[{label:'实际本批复检项目（虚构）',result:action==='quality_pass'?'pass':'fail'}]}),...over};};
async function qact(x,action,over={},who=x.p,key=crypto.randomUUID()){return x.request('/api/purchase-quality/'+x.q.id+'/events',{...who,method:'POST',data:qe(x,action,over),key});}
async function qrevise(x,over={},who=x.p){const r=R.receiptRecord(x.db,x.receipt.id),c=Q.purchaseQualityRecord(x.db,x.q.id);return x.request('/api/purchase-quality/'+c.id+'/versions',{...who,method:'POST',data:{expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,receipt_version_id:r.version_id,observed_at:now(),observation_note:'明确新增实际观察',source_reference:'DEMO-NEW-FACT',...notes,...over}});}
const verify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);};
import * as S from '../src/supplier-returns.mjs';
import {supplierReturnSequence} from '../src/supplier-return-ledger.mjs';
import {verifySupplierReturns} from '../src/supplier-return-recovery.mjs';
import {seedDemoSupplierReturns} from '../src/demo-supplier-returns.mjs';
const si=(x,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:supplierReturnSequence(x.db,'a'),case_id:c.id,quantity:2,source_note:'实际原批退供安排（虚构）',quality_version_id:c.version_id,quality_event_id:c.current.id,receipt_version_id:c.receipt_current.id,expected_case_return_revision:c.case_return_revision,return_basis:'人工明确退供依据（虚构），不预设正式政策',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-RETURN',...notes,...over};};
async function sb(t,opts={}){const x=await base(t,{bucket:'quarantined',...opts});good(await caseCreate(x,{quantity:2,source_bucket:'quarantined'}));good(await qact(x,'quality_fail'));return x;}
async function create(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns',{...who,method:'POST',data:si(x,over),key});if(z.status===201)x.s=z.body.record;return z;}
const se=(x,action,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id);return {expected_sequence:supplierReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,decision_basis:'本次人工商业依据（虚构）',...notes,...over};};
const sa=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/supplier-returns/'+x.s.id+'/events',{...who,method:'POST',data:se(x,action,over),key});
async function approved(x){good(await create(x));good(await sa(x,'submit'));good(await sa(x,'approve'));return x;}
const hi=(x,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id),s=r.source;return {expected_sequence:supplierReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,quantity:1,handed_at:now(),collector_label:'虚构实际接收人',destination_note:'虚构实际接收地点',external_reference:null,source_identity:null,source_note:'本次实际交出事实（虚构）',expected_stock_sequence:s.stock.sequence,expected_outbound_revision:s.stock.outbound_revision,expected_product_return_revision:s.stock.return_revision,expected_case_return_revision:s.balance.case_return_revision,expected_handed_quantity:r.balance.handed_quantity,reason:notes.reason,next_step:notes.next_step,...over};};
async function hand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns/'+x.s.id+'/handoffs',{...who,method:'POST',data:hi(x,over),key});if(z.status===201)x.h=z.body.record.handoffs[0];return z;}
const ri=(x,over={})=>({expected_sequence:supplierReturnSequence(x.db,'a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'可核对供应方实际收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const receive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/supplier-return-handoffs/'+x.h.id+'/receipts',{...who,method:'POST',data:ri(x,over),key});
const verified=x=>{verify(x);verifySupplierReturns(x.db);};

import * as E from '../src/purchase-extra-returns.mjs';
import {extraReturnSequence} from '../src/purchase-extra-return-ledger.mjs';
import {verifyExtraReturns} from '../src/purchase-extra-return-recovery.mjs';
async function extraBase(t,opts={}){const x=await setup(t,opts);good(await receipt(x,{received_quantity:4,bound_quantity:1}));return x;}
const ei=(x,over={})=>{const s=E.extraReturnSource(x.db,x.receipt.id);return {expected_sequence:extraReturnSequence(x.db,'a'),receipt_id:x.receipt.id,receipt_version_id:s.receipt_version.id,expected_receipt_sequence:R.receivingSequence(x.db,'a'),expected_receipt_return_revision:s.balance.receipt_return_revision,quantity:2,custody_confirmed_at:now(),custody_source:'人工实际核对超收原件身份数量和位置（虚构）',source_note:'原超收独立未入账来源（虚构）',return_basis:'明确人工退回依据（虚构）',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-EXTRA-RETURN',...notes,...over};};
async function ecreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-extra-returns',{...who,method:'POST',data:ei(x,over),key});if(z.status===201)x.e=z.body.record;return z;}
const eevent=(x,action,over={})=>{const e=E.extraReturnRecord(x.db,x.e.id);return {expected_sequence:extraReturnSequence(x.db,'a'),expected_revision:e.revision,expected_version:e.current_version,action,decision_basis:'真实人工商业决定（虚构）',...notes,...over};};
const eact=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/purchase-extra-returns/'+x.e.id+'/events',{...who,method:'POST',data:eevent(x,action,over),key});
async function eapprove(x){good(await ecreate(x));good(await eact(x,'submit'));good(await eact(x,'approve'));}
const ehi=(x,over={})=>{const r=E.extraReturnRecord(x.db,x.e.id);return {expected_sequence:extraReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,expected_receipt_return_revision:r.source.balance.receipt_return_revision,expected_handed_quantity:r.balance.handed_quantity,quantity:1,handed_at:now(),collector_label:'虚构接收人',destination_note:'虚构实际地点',external_reference:null,source_identity:null,source_note:'可核对超收实际交出（虚构）',reason:notes.reason,next_step:notes.next_step,...over};};
async function ehand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-extra-returns/'+x.e.id+'/handoffs',{...who,method:'POST',data:ehi(x,over),key});if(z.status===201)x.eh=z.body.record.handoffs[0];return z;}
const eri=(x,over={})=>({expected_sequence:extraReturnSequence(x.db,'a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'实际超收退回件的供应方收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const ereceive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/purchase-extra-handoffs/'+x.eh.id+'/receipts',{...who,method:'POST',data:eri(x,over),key});
const eVerify=x=>{verifyReceiving(x.db);verifyExtraReturns(x.db);};
import * as C from '../src/inventory-custody.mjs';
import {verifyCustody} from '../src/inventory-custody-recovery.mjs';
const ci=(x,over={})=>({receipt_id:x.receipt.id,expected_sequence:C.custodySequence(x.db,'a'),expected_source:C.custodySource(x.db,x.receipt.id).source_token,quantity:1,bucket:'available',observed_at:now(),identity_source:'人工实际核对原收货箱、本次所见数量与原单位（虚构）',location_label:'虚构A柜第1格',location_source:'已发生现场核对及可查位置来源（虚构）',source_reference:'DEMO-CUSTODY',...notes,...over});
async function ccreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/inventory-custody',{...who,method:'POST',data:ci(x,over),key});if(z.status===201)x.c=z.body.record;return z;}
const cv=(x,over={})=>{const r=C.custodyRecord(x.db,x.c.id),i=ci(x,over);delete i.receipt_id;return {...i,expected_revision:r.revision,expected_version:r.current_version};};
const cobserve=(x,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/inventory-custody/'+x.c.id+'/observations',{...who,method:'POST',data:cv(x,over),key});
const cwithdraw=(x,over={},who=x.m)=>{const r=C.custodyRecord(x.db,x.c.id);return x.request('/api/inventory-custody/'+x.c.id+'/events',{...who,method:'POST',data:{expected_sequence:C.custodySequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action:'withdraw',reason:'明确纠错撤回本版解释，不注销实物',next_step:'重新实际核对原身份数量和位置',...over}});};
const cVerify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);verifySupplierReturns(x.db);verifyCustody(x.db);};
import * as RC from '../src/inventory-reserved.mjs';
import {verifyReserved} from '../src/inventory-reserved-recovery.mjs';
import {insertOrderVersion} from '../src/retail.mjs';
import {insertReservation as rawReservation,orderInventory,verifyInventory} from '../src/inventory.mjs';
import {transaction} from '../src/db.mjs';
const insertReservation=(db,...args)=>transaction(db,()=>rawReservation(db,...args));
async function reservedBase(t,opts={}){const x=await base(t,opts),at=now(),serial=1;x.salesOrder='reserved-original-order';x.db.prepare('INSERT INTO retail_orders VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(x.salesOrder,'a','one',serial,'OW-'+at.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),null,null,null,'customer',at,'manager');insertOrderVersion(x.db,x.salesOrder,{title:'原预留订单（虚构）',notes:'虚构原件来源仍须实际核对',items:[{product_id:x.product.id,product_version:1,quantity:2,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构实际原单'},'manager','draft',at);x.reservation=insertReservation(x.db,x.salesOrder,'reserve','虚构明确原单SKU预留','manager').active;return x;}
const rci=(x,over={})=>({receipt_id:x.receipt.id,reservation_id:x.reservation.id,order_position:1,expected_sequence:RC.custodySequence(x.db,'a'),expected_source:RC.custodySource(x.db,x.receipt.id,x.reservation.id,1).source_token,quantity:1,bucket:'reserved',observed_at:now(),identity_source:'人工实际核对原收货箱、本原订单已预留原件与单位（虚构）',location_label:'虚构原单预留柜一格',location_source:'虚构已发生现场原件和原单位置对应',source_reference:'DEMO-ACTUAL-RESERVED',...notes,...over});
async function rcCreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/inventory-reserved',{...who,method:'POST',data:rci(x,over),key});if(z.status===201)x.rc=z.body.record;return z;}
const rcv=(x,over={})=>{const r=RC.custodyRecord(x.db,x.rc.id),i=rci(x,over);for(const k of ['receipt_id','reservation_id','order_position'])delete i[k];return {...i,expected_revision:r.revision,expected_version:r.current_version};};
const rcObserve=(x,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/inventory-reserved/'+x.rc.id+'/observations',{...who,method:'POST',data:rcv(x,over),key});
const rcWithdraw=(x,who=x.m)=>{const r=RC.custodyRecord(x.db,x.rc.id);return x.request('/api/inventory-reserved/'+x.rc.id+'/events',{...who,method:'POST',data:{expected_sequence:RC.custodySequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action:'withdraw',reason:'虚构明确撤回解释，保留真实预留',next_step:'实际重新核对原件'}});};
const rv=x=>{verifyReceiving(x.db);verifyInventory(x.db);verifyPurchaseQuality(x.db);verifyReserved(x.db);};
import {insertProcessingJob,insertProcessingEvent} from '../src/processing.mjs';
import {insertFulfillmentEvent} from '../src/fulfillment.mjs';
import {dispatchRecord,verifyDispatch} from '../src/dispatch.mjs';
import {batchSequence} from '../src/inventory-batch-ledger.mjs';
function reservedDelivery(x,{other=false}={}){const at=now(),order=other?'other-available-order':x.salesOrder,quantity=other?1:2;if(other){x.db.prepare('INSERT INTO retail_orders VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(order,'a','one',2,'OW-'+at.slice(0,10).replaceAll('-','')+'-00002',null,null,null,'customer',at,'manager');insertOrderVersion(x.db,order,{title:'另一实际交付原单（虚构）',notes:null,items:[{product_id:x.product.id,product_version:1,quantity,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构原来源'},'manager','draft',at);}const j=insertProcessingJob(x.db,order,{lines:[{position:1,supply_mode:other?'purchase':'stock',processing_mode:'internal',supplier_name:other?'虚构供货方':null,assignee_id:'professional',due_date:null,instructions:'虚构实际备料，不生成专业参数'}],reason:'虚构原安排'},'manager',at);for(const action of ['receive','start','complete'])insertProcessingEvent(x.db,j.id,{action,position:1,quantity,reason:'虚构实际分项记录'},'manager',at);const pass=insertFulfillmentEvent(x.db,j.id,{action:'check_pass',position:1,quantity,source_id:null,checks:[{label:'本例虚构人工检查，不是通用专业标准',result:'pass',notes:'虚构来源'}],reason:'虚构原检查'},'manager',at).event;return insertFulfillmentEvent(x.db,j.id,{action:'deliver',position:1,quantity,source_id:pass.id,receiver_name:'虚构领取人',receipt_note:'虚构实际签收',handed_at:at,reason:'虚构原事实'},'manager',at).event.id;}

import {insertDispatch} from '../src/dispatch.mjs';
import {reservedBatchSequence} from '../src/inventory-reserved-batch-ledger.mjs';
import {outboundBatches,receiptBatchSold} from '../src/inventory-batch-ledger.mjs';
import {verifyBatches} from '../src/inventory-batch-recovery.mjs';
import {reservedBatchTables} from '../src/inventory-reserved-batches.mjs';
import {verifyReservedBatches} from '../src/inventory-reserved-batch-recovery.mjs';
async function shippingBase(t,opts={}){const x=await reservedBase(t,opts);x.delivery=reservedDelivery(x);good(await rcCreate(x,{quantity:2}));return x;}
const shipInput=(x,over={})=>{const r=dispatchRecord(x.db,x.delivery),c=RC.custodyRecord(x.db,x.rc.id);return {expected_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,expected_dispatched:r.dispatched,expected_reservation_revision:r.reservation_revision,quantity:1,reason:'本次人工实际原件交出（虚构）',expected_reserved_batch_sequence:reservedBatchSequence(x.db,'a'),expected_reserved_custody_sequence:RC.custodySequence(x.db,'a'),reserved_batch_source_note:'虚构实际原单预留原件交出来源',reserved_batch_sources:[{custody_id:c.id,custody_version_id:c.version_id,custody_event_id:c.current.id,quantity:1,source_reference:'DEMO-ACTUAL-RESERVED-SALE',note:'虚构明确本次原件实际交出'}],...over};};
const ship=(x,data=shipInput(x),who=x.m,key=crypto.randomUUID())=>x.request('/api/fulfillment/events/'+x.delivery+'/dispatch',{...who,method:'POST',data,key});
const bv=x=>{rv(x);verifyCustody(x.db);verifyBatches(x.db);verifyDispatch(x.db);verifyReservedBatches(x.db);};
const candidates=x=>'/api/inventory/reservations/'+x.reservation.id+'/lines/1/batch-sources';
function altered(db,table,sql){const rows=db.prepare("SELECT name,sql FROM sqlite_schema WHERE type='trigger' AND tbl_name=?").all(table);for(const x of rows)db.exec('DROP TRIGGER '+x.name);db.exec(sql);for(const x of rows)db.exec(x.sql);}
test('actual original reserved dispatch traces fixed receipt and delivered customer with exactly one physical reserved debit',async t=>{const x=await shippingBase(t),before=physicalStock(x.db,x.product.id),funds=x.db.prepare('SELECT * FROM payment_events').all(),stockRows=x.db.prepare('SELECT count(*) n FROM inventory_events').get().n,z=await ship(x);good(z);assert.equal(z.body.event.source_mode,'reserved');assert.equal(z.body.batch_source.source_mode,'reserved');assert.equal(z.body.batch_source.items[0].reservation_id,x.reservation.id);assert.equal(z.body.batch_source.items[0].receipt_id,x.receipt.id);assert.equal(physicalStock(x.db,x.product.id).reserved,before.reserved-1);assert.equal(physicalStock(x.db,x.product.id).available,before.available);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_events').get().n,stockRows);assert.deepEqual(x.db.prepare('SELECT * FROM payment_events').all(),funds);const trace=await x.request('/api/purchase-receipts/'+x.receipt.id+'/delivered-batches',x.f);assert.equal(trace.body.items[0].customer_id,'one');assert.equal(trace.body.items[0].source_mode,'reserved');assert.equal(trace.body.known_attributed_quantity,1);assert.equal(trace.body.current_batch_custody_quantity,null);const tl=await x.request('/api/customers/one/timeline?kind=dispatch',x.m);assert.equal(tl.body.items[0].details.batch_source.items[0].receipt_id,x.receipt.id);const sources=await x.request('/api/inventory/products/'+x.product.id+'/sources?kind=receipt',x.m);assert.equal(sources.body.items[0].explicit_batch_sales_quantity,1);bv(x);});
test('post-sales original reserved observation must be explicitly renewed before remaining actual original quantity can ship',async t=>{const x=await shippingBase(t),data=shipInput(x);good(await ship(x,data));assert.equal(RC.custodyRecord(x.db,x.rc.id).source_current,false);assert.equal((await x.request(candidates(x),x.m)).body.total,0);assert.equal((await ship(x,data)).status,409);assert.equal((await rcObserve(x,{quantity:2})).status,409);good(await rcObserve(x,{quantity:1}));good(await ship(x));assert.equal(receiptBatchSold(x.db,x.receipt.id),2);assert.equal(physicalStock(x.db,x.product.id).reserved,0);bv(x);});
test('actual reserved negative retry preserves exact original fact after observation withdrawal and later receipt metadata',async t=>{const x=await shippingBase(t),data=shipInput(x),key='reserved-negative',z=await ship(x,data,x.m,key);good(z);good(await rcWithdraw(x));good(await revise(x,{...known,lot_code:'AFTER-ACTUAL-SALE'}));const replay=await ship(x,data,x.m,key);good(replay);assert.deepEqual(replay.body,z.body);assert.equal((await ship(x,{...data,reason:'改意图'},x.m,key)).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_reserved_batch_declarations').get().n,1);bv(x);});
test('duplicate original roots and incomplete sums and invalid field objects fail with no actual debit',async t=>{const x=await shippingBase(t),before=physicalStock(x.db,x.product.id);for(const data of [shipInput(x,{quantity:2}),shipInput(x,{reserved_batch_sources:[]}),shipInput(x,{reserved_batch_sources:null}),shipInput(x,{reserved_batch_sources:[{...shipInput(x).reserved_batch_sources[0],guess:true}]}),shipInput(x,{quantity:2,reserved_batch_sources:[shipInput(x).reserved_batch_sources[0],shipInput(x).reserved_batch_sources[0]]}),{...shipInput(x),reserved_batch_sources:undefined}])assert.equal((await ship(x,data)).status,422);assert.deepEqual(physicalStock(x.db,x.product.id),before);bv(x);});
test('available and reserved original observations remain separate exact namespaces',async t=>{const x=await shippingBase(t),data=shipInput(x);assert.equal((await ship(x,{...data,batch_sources:data.reserved_batch_sources})).status,422);insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'receive',quantity:2,reason:'独立另一箱实际到货',created_by:'manager'});good(await ccreate(x,{quantity:2}));good(await rcObserve(x,{quantity:2}));assert.equal((await ship(x,{...shipInput(x),reserved_batch_sources:[{...data.reserved_batch_sources[0],custody_id:x.c.id,custody_version_id:x.c.version_id,custody_event_id:x.c.current.id}]})).status,404);x.delivery=reservedDelivery(x,{other:true});assert.equal((await ship(x)).status,409);bv(x);});
test('another original reservation cannot substitute existing root even for same SKU',async t=>{const x=await reservedBase(t);good(await rcCreate(x,{quantity:2}));insertReservation(x.db,x.salesOrder,'release','释放原预留','manager');x.reservation=insertReservation(x.db,x.salesOrder,'reserve','重新实际预留','manager').active;x.delivery=reservedDelivery(x);assert.equal((await ship(x)).status,404);assert.equal((await x.request(candidates(x),x.m)).body.total,0);bv(x);});
test('current actor actions are scoped: front desk writes, professional reads, guardian and another store refused',async t=>{const x=await shippingBase(t);assert.equal((await ship(x,shipInput(x),x.p)).status,403);assert.equal((await ship(x,shipInput(x),x.g)).status,403);assert.equal((await ship(x,shipInput(x),x.o)).status,404);assert.equal((await x.request(candidates(x),x.p)).status,200);assert.equal((await x.request(candidates(x),x.g)).status,403);assert.equal((await x.request(candidates(x),x.o)).status,404);good(await ship(x,shipInput(x),x.f));bv(x);});
test('audit failure rolls back actual outbound, declaration, source references, contexts and retry cache as one operation',async t=>{const x=await shippingBase(t),before=physicalStock(x.db,x.product.id),data=shipInput(x),key='reserved-audit';x.db.exec("CREATE TRIGGER fail_reserved_batch_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test');END");assert.equal((await ship(x,data,x.m,key)).status,500);assert.deepEqual(physicalStock(x.db,x.product.id),before);assert.equal(reservedBatchSequence(x.db,'a'),0);x.db.exec('DROP TRIGGER fail_reserved_batch_audit');good(await ship(x,data,x.m,key));bv(x);});
test('legacy actual reserved dispatch without selected original source stays unknown',async t=>{const x=await shippingBase(t),data=shipInput(x);for(const k of ['reserved_batch_sources','reserved_batch_source_note','expected_reserved_batch_sequence','expected_reserved_custody_sequence'])delete data[k];const z=await ship(x,data);good(z);assert.equal(z.body.batch_source.status,'not_recorded');assert.equal(reservedBatchSequence(x.db,'a'),0);bv(x);});
test('two simultaneous original reserved choices create one actual debit and refuse stale second source',async t=>{const x=await shippingBase(t),data=shipInput(x),z=await Promise.all([ship(x,data),ship(x,data)]);assert.deepEqual(z.map(z=>z.status).sort(),[201,409]);assert.equal(receiptBatchSold(x.db,x.receipt.id),1);bv(x);});
test('known reserved sales cannot be reclaimed as custody or protected quality using another same SKU box',async t=>{const x=await shippingBase(t);good(await ship(x));insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'receive',quantity:3,reason:'另一箱同款不是原件',created_by:'manager'});assert.equal((await ccreate(x,{quantity:2})).status,409);assert.equal((await caseCreate(x,{quantity:2})).status,409);good(await caseCreate(x,{quantity:1}));bv(x);});
test('independent observations of two positions share one original receipt capacity and full actual quantity',async t=>{const x=await shippingBase(t),first=RC.custodyRecord(x.db,x.rc.id);good(await rcCreate(x,{quantity:2,location_label:'虚构第二实际位置'}));const data=shipInput(x,{quantity:2});data.reserved_batch_sources.unshift({custody_id:first.id,custody_version_id:first.version_id,custody_event_id:first.current.id,quantity:1,source_reference:'DEMO-FIRST',note:'第一实际原件位置'});good(await ship(x,data));assert.equal(receiptBatchSold(x.db,x.receipt.id),2);bv(x);});
test('changed receipt original metadata cannot be silently adopted by a selected actual reserved source',async t=>{const x=await shippingBase(t),data=shipInput(x);good(await revise(x,{...known,lot_code:'CHANGED-SOURCE'}));assert.equal((await ship(x,data)).status,409);good(await rcObserve(x,{quantity:2}));const z=await ship(x);good(z);good(await revise(x,{...known,lot_code:'AFTER-FACT'}));assert.deepEqual((await x.request('/api/inventory/outbounds/'+z.body.event.id+'/batches',x.m)).body.items,z.body.batch_source.items);bv(x);});
test('reserved candidate and combined delivered trace paging use fixed source leases for both streams',async t=>{const x=await shippingBase(t),path=candidates(x),z=await x.request(path,x.m);assert.equal(z.body.items[0].known_capacity,2);assert.equal((await x.request(path+'?offset=1',x.m)).status,409);assert.equal((await x.request(path+'?offset=1&expected_source='+z.body.source_token,x.m)).status,200);const trace='/api/purchase-receipts/'+x.receipt.id+'/delivered-batches',old=(await x.request(trace,x.m)).body;good(await ship(x));assert.equal((await x.request(path+'?offset=1&expected_source='+z.body.source_token,x.m)).status,409);assert.equal((await x.request(trace+'?offset=1&expected_sequence='+old.sequence+'&expected_reserved_sequence='+old.reserved_sequence,x.m)).status,409);const fresh=(await x.request(trace,x.m)).body;assert.equal((await x.request(trace+'?offset=1&expected_sequence='+fresh.sequence+'&expected_reserved_sequence='+fresh.reserved_sequence,x.m)).status,200);bv(x);});
test('nine reserved actual tables survive verified backup and independent restoration with sessions revoked',async t=>{const x=await shippingBase(t,{persist:true});good(await ship(x));good(await rcObserve(x,{quantity:1}));const b=await createBackup(x.path,join(x.dir,'backup')),z=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(z.database);t.after(()=>d.close());for(const n of reservedBatchTables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all());assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyReservedBatches(d);});
test('native quantity and immutable exact sources reject bypass without partial actual debit',async t=>{const x=await shippingBase(t),before=physicalStock(x.db,x.product.id);assert.throws(()=>insertDispatch(x.db,x.delivery,shipInput(x,{quantity:2,reserved_batch_sources:[{...shipInput(x).reserved_batch_sources[0],quantity:3}]}),'manager'),/reserved batch/);assert.deepEqual(physicalStock(x.db,x.product.id),before);good(await ship(x));for(const n of reservedBatchTables){if(!x.db.prepare('SELECT count(*) n FROM '+n).get().n)continue;const key=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+key+'='+key),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}bv(x);});
async function paused(x,data,change){const payload=JSON.stringify(data),req=httpRequest(x.origin+'/api/fulfillment/events/'+x.delivery+'/dispatch',{method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}}),done=new Promise((resolve,reject)=>{req.on('error',reject);req.on('response',r=>{let s='';r.on('data',x=>s+=x);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(s)}));});});req.write(payload.slice(0,12));await new Promise(r=>setTimeout(r,60));try{await change();}finally{req.end(payload.slice(12));}return done;}
test('paused original-source body rechecks changed live role and reset-password gate before any actual fact',async t=>{const x=await shippingBase(t),before=physicalStock(x.db,x.product.id);assert.equal((await paused(x,shipInput(x),()=>x.db.exec("UPDATE users SET role='reception' WHERE id='manager'"))).status,401);assert.deepEqual(physicalStock(x.db,x.product.id),before);x.db.exec("UPDATE users SET role='manager' WHERE id='manager'");assert.equal((await paused(x,shipInput(x),()=>x.db.prepare('INSERT INTO user_security(user_id,must_change_password) VALUES(?,1)').run('manager'))).status,403);assert.equal(reservedBatchSequence(x.db,'a'),0);});
test('paused original-source body refuses withdrawn current observation rather than substituting it',async t=>{const x=await shippingBase(t);assert.equal((await paused(x,shipInput(x),()=>RC.custodyEvent(x.db,x.rc.id,{action:'withdraw',...notes},'manager'))).status,409);assert.equal(reservedBatchSequence(x.db,'a'),0);bv(x);});
test('same-millisecond later observation cannot replace earlier reserved actual source prefix',async t=>{const x=await shippingBase(t),at=now();insertDispatch(x.db,x.delivery,shipInput(x),'manager',at);const v=RC.custodyObservation(x.db,x.rc.id,{...rci(x),quantity:1,observed_at:at},'manager',at);bv(x);altered(x.db,'inventory_reserved_reserved_sales_context',"UPDATE inventory_reserved_reserved_sales_context SET reserved_sequence=0 WHERE version_id='"+v.version_id+"'");assert.throws(()=>verifyReservedBatches(x.db),/同刻/);});
test('same-millisecond original receipt metadata must retain ordering against actual reserved batch declaration',async t=>{const x=await shippingBase(t),at=now();insertDispatch(x.db,x.delivery,shipInput(x),'manager',at);R.receiptVersion(x.db,x.receipt.id,{...known,lot_code:'SAME-MS-LATER'},'front',at);bv(x);altered(x.db,'inventory_reserved_batch_declarations','UPDATE inventory_reserved_batch_declarations SET receipt_sequence='+R.receivingSequence(x.db,'a'));assert.throws(()=>verifyReservedBatches(x.db),/同刻|原观察/);});
test('native orphan or incomplete original reserved sources cannot pass recovery',async t=>{const x=await shippingBase(t);good(await ship(x));altered(x.db,'inventory_reserved_batch_refs','DELETE FROM inventory_reserved_batch_refs');assert.throws(()=>verifyReservedBatches(x.db),/完整实际来源/);});

import {seedDemoReservedBatches} from '../src/demo-inventory-reserved-batches.mjs';
import {seedDemoBatches} from '../src/demo-inventory-batches.mjs';
test('seven separately sourced original reserved actual stages preserve all old rows and physical balances and repeat exactly',async t=>{const x=await shippingBase(t);for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');x.db.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'demo-manager');const tables=x.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),snapshot=()=>Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()])),before=snapshot(),stock=physicalStock(x.db,x.product.id);assert.deepEqual(seedDemoReservedBatches(x.db),{receipts:7,custodies:7,outbounds:6,declarations:5});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);assert.deepEqual(physicalStock(x.db,x.product.id),stock);bv(x);const after=snapshot();assert.deepEqual(seedDemoReservedBatches(x.db),{receipts:0,custodies:0,outbounds:0,declarations:0});assert.deepEqual(snapshot(),after);});
test('nonempty schema43 upgrade preserves old actual available and reserved dispatch and captures no inferred original reserved declaration',t=>{const dir=mkdtempSync(join(tmpdir(),'reserved-sales-upgrade-')),path=join(dir,'old.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));const d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,43)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');d.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'demo-manager');seedDemoBatches(d);const old=d.prepare('SELECT * FROM inventory_outbounds ORDER BY rowid').all(),refs=d.prepare('SELECT * FROM inventory_batch_refs ORDER BY rowid').all();assert.ok(old.length);d.close();const u=openDatabase(path);t.after(()=>u.close());assert.deepEqual(u.prepare('SELECT * FROM inventory_outbounds ORDER BY rowid').all(),old);assert.deepEqual(u.prepare('SELECT * FROM inventory_batch_refs ORDER BY rowid').all(),refs);assert.equal(reservedBatchSequence(u,'a'),0);assert.equal(u.prepare('SELECT count(*) n FROM inventory_reserved_sales_dispatch_context WHERE legacy=1').get().n,old.length);verifyReservedBatches(u);verifyBatches(u);});
test('available and reserved actual sources share original bound protection while retaining independent captured historical prefixes',async t=>{const x=await shippingBase(t);good(await ship(x));insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'receive',quantity:2,reason:'另一箱额外可用实物不代原件',created_by:'manager'});good(await ccreate(x,{quantity:1}));x.delivery=reservedDelivery(x,{other:true});const r=dispatchRecord(x.db,x.delivery),c=C.custodyRecord(x.db,x.c.id);const data={expected_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,expected_dispatched:r.dispatched,expected_reservation_revision:r.reservation_revision,quantity:1,reason:'明确实际可用原件交出',expected_batch_sequence:batchSequence(x.db,'a'),expected_custody_sequence:C.custodySequence(x.db,'a'),batch_source_note:'明确已发生原件来源',batch_sources:[{custody_id:c.id,custody_version_id:c.version_id,custody_event_id:c.current.id,quantity:1,source_reference:'DEMO-AVAILABLE-AFTER-RESERVED',note:'原件最后一件实际交出'}]};good(await ship(x,data));assert.equal(receiptBatchSold(x.db,x.receipt.id),2);const trace=(await x.request('/api/purchase-receipts/'+x.receipt.id+'/delivered-batches',x.m)).body;assert.equal(trace.known_attributed_quantity,2);assert.deepEqual(trace.items.map(i=>i.source_mode).sort(),['available','reserved']);assert.equal((await ccreate(x,{quantity:1})).status,409);assert.equal((await rcObserve(x,{quantity:1})).status,409);bv(x);});
