import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
async function product(request,m,extra={}){const r=await request('/api/retail/products',{...m,method:'POST',data:{sku:'SKU-'+crypto.randomUUID().slice(0,8),name:'虚构镜架',category:'frame',brand:null,specification:'虚构型号',unit:'副',list_price_cents:19900,status:'active',reason:'虚构目录',...extra}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.product;}
async function order(request,m,items){const r=await request('/api/customers/one/retail-orders',{...m,method:'POST',data:{title:'库存订单（虚构）',notes:null,items:items.map(x=>({product_id:x.id,product_version:x.version,quantity:x.quantity||1,unit_price_cents:100,note:null})),reason:'虚构开单'}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.order;}
async function stock(request,m,p,action='receive',quantity=10,extra={},key=crypto.randomUUID()){const current=(await request('/api/inventory/products/'+p.id,m)).body;return request('/api/inventory/products/'+p.id+'/events',{...m,method:'POST',key,data:{expected_product_version:current.product?.version||p.version,expected_sequence:current.stock?.sequence||0,action,quantity,reason:'虚构库存操作',...extra}});}
async function inventory(request,m,id){const r=await request('/api/retail/orders/'+id+'/inventory',m);assert.equal(r.status,200);return r.body.inventory;}
function postReservation(request,m,state,action='reserve',extra={},key=crypto.randomUUID()){return request('/api/retail/orders/'+state.order_id+'/inventory/'+action,{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,reason:'虚构'+action,...(action==='reserve'?{stock_versions:state.stock_versions}:{}),...extra}});}
function revise(request,m,o,extra={}){return request('/api/retail/orders/'+o.id+'/versions',{...m,method:'POST',data:{expected_version:o.version,title:o.title,notes:'虚构修订说明',items:o.items.map(({product_id,product_version,quantity,unit_price_cents,note})=>({product_id,product_version,quantity,unit_price_cents,note})),document_version_ids:[],attachment_ids:[],reason:'虚构修订',...extra}});}
const counts=db=>Object.fromEntries(inventoryTables.map(t=>[t,db.prepare('SELECT count(*) n FROM '+t).get().n]));
test('inventory employee reads, manager-only stock writes, front reservations and store/guardian boundaries',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),f=await login('front'),p=await login('professional'),g=await login('parent'),other=await login('other'),item=await product(request,m),o=await order(request,m,[item]);for(const s of [m,f,p])assert.equal((await request('/api/inventory/products',s)).status,200);for(const s of [f,p,g])assert.equal((await stock(request,s,item)).status,403);assert.equal((await request('/api/inventory/products',g)).status,403);assert.equal((await request('/api/inventory/products/'+item.id,other)).status,404);assert.equal((await request('/api/retail/orders/'+o.id+'/inventory',other)).status,404);await stock(request,m,item);assert.equal((await postReservation(request,p,await inventory(request,p,o.id))).status,403);assert.equal((await postReservation(request,f,await inventory(request,f,o.id))).status,201);assert.equal((await request('/api/inventory/products')).status,401);
});
test('inventory starts unrecorded and exact ledger transitions conserve all physical stock without touching order amounts',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m);assert.equal(stockBalance(db,p.id).recorded,false);assert.equal((await stock(request,m,p,'receive',10)).status,201);assert.equal((await stock(request,m,p,'isolate',3)).status,201);assert.equal((await stock(request,m,p,'unquarantine',2)).status,201);const b=stockBalance(db,p.id);assert.deepEqual([b.available,b.reserved,b.quarantined,b.on_hand,b.sequence],[9,0,1,10,3]);assert.equal((await stock(request,m,p,'isolate',10)).body.error.code,'INSUFFICIENT_STOCK');assert.equal((await stock(request,m,p,'unquarantine',2)).status,409);assert.equal(stockBalance(db,p.id).sequence,3);verifyInventory(db);
});
test('inventory rejects services, invalid quantities, fabricated balances/payment fields and CSRF',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),service=await product(request,m,{category:'service',unit:'次'});assert.equal((await request('/api/inventory/products/'+service.id,m)).body.error.code,'SERVICE_NOT_STOCKED');assert.equal((await request('/api/inventory/products',m)).body.total,1);for(const quantity of [0,-1,0.1,1000001,'1'])assert.equal((await stock(request,m,p,'receive',quantity)).status,422);for(const action of ['sell','refund','reserve','release','paid'])assert.equal((await stock(request,m,p,action)).status,422);assert.equal((await stock(request,m,p,'receive',2,{available:100})).status,422);assert.equal((await stock(request,{...m,csrf:'wrong'},p)).status,403);assert.deepEqual(counts(db),{inventory_events:0,inventory_order_events:0,inventory_order_lines:0});
});
test('inventory optimistic stock and catalog versions reject old intents and identical keys replay once',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),input={expected_product_version:1,expected_sequence:0,action:'receive',quantity:5,reason:'虚构入库'},path='/api/inventory/products/'+p.id+'/events',key='stock-same-intent';const first=await request(path,{...m,method:'POST',key,data:input}),again=await request(path,{...m,method:'POST',key,data:input});assert.equal(first.status,201);assert.deepEqual(again.body,first.body);assert.equal((await request(path,{...m,method:'POST',data:input})).body.error.code,'STOCK_CONFLICT');assert.equal((await request(path,{...m,method:'POST',key,data:{...input,quantity:6}})).body.error.code,'IDEMPOTENCY_CONFLICT');assert.equal(stockBalance(db,p.id).available,5);
});
test('inventory aggregates duplicate product lines, excludes services and reserves every physical row or none',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),service=await product(request,m,{category:'service',unit:'次'}),o=await order(request,m,[{...p,quantity:2},{...p,quantity:3},service]);await stock(request,m,p,'receive',4);let s=await inventory(request,m,o.id);assert.equal(s.requirements.length,1);assert.equal(s.requirements[0].required,5);assert.equal(s.requirements[0].shortage,1);assert.equal(s.service_lines,1);assert.equal((await postReservation(request,m,s)).body.error.code,'INSUFFICIENT_STOCK');assert.equal(counts(db).inventory_order_events,0);await stock(request,m,p,'receive',1);s=await inventory(request,m,o.id);const saved=await postReservation(request,m,s);assert.equal(saved.status,201,JSON.stringify(saved.body));assert.equal(saved.body.inventory.active.lines.length,2);assert.deepEqual([stockBalance(db,p.id).available,stockBalance(db,p.id).reserved],[0,5]);assert.equal(db.prepare('SELECT subtotal_cents FROM retail_order_versions WHERE order_id=?').get(o.id).subtotal_cents,600);verifyInventory(db);
});
test('inventory multi-product shortage rejects atomically and quarantine cannot be reserved',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),a=await product(request,m),b=await product(request,m),o=await order(request,m,[a,b]);await stock(request,m,a,'receive',2);await stock(request,m,b,'receive',1);await stock(request,m,b,'isolate',1);const before=counts(db);assert.equal((await postReservation(request,m,await inventory(request,m,o.id))).status,409);assert.deepEqual(counts(db),before);assert.equal(stockBalance(db,a.id).available,2);assert.equal(stockBalance(db,b.id).quarantined,1);
});
test('competing orders reserve the last item once and isolation races cannot spend reserved stock',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),a=await order(request,m,[p]),b=await order(request,m,[p]);await stock(request,m,p,'receive',1);const sa=await inventory(request,m,a.id),sb=await inventory(request,m,b.id),results=await Promise.all([postReservation(request,m,sa),postReservation(request,m,sb)]);assert.deepEqual(results.map(x=>x.status).sort(),[201,409]);assert.deepEqual([stockBalance(db,p.id).available,stockBalance(db,p.id).reserved],[0,1]);assert.equal((await stock(request,m,p,'isolate',1)).status,409);verifyInventory(db);
});
test('reservation and release fix original rows, release once, allow later revision and re-reservation',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[{...p,quantity:2}]);await stock(request,m,p,'receive',5);const s=await inventory(request,m,o.id),reserve=await postReservation(request,m,s);assert.equal(reserve.status,201);assert.equal((await postReservation(request,m,reserve.body.inventory)).body.error.code,'ALREADY_RESERVED');assert.equal((await revise(request,m,o)).body.error.code,'ORDER_RESERVED');assert.equal((await request('/api/retail/orders/'+o.id+'/cancel',{...m,method:'POST',data:{expected_version:1,reason:'虚构取消'}})).body.error.code,'ORDER_RESERVED');const release=await postReservation(request,m,reserve.body.inventory,'release');assert.equal(release.status,201);assert.equal(release.body.inventory.active,null);assert.equal(release.body.inventory.history[0].source_id,reserve.body.inventory.active.id);assert.equal((await postReservation(request,m,release.body.inventory,'release')).body.error.code,'NOT_RESERVED');const revised=await revise(request,m,o,{items:[{product_id:p.id,product_version:1,quantity:3,unit_price_cents:100,note:null}]});assert.equal(revised.status,201);const again=await postReservation(request,m,await inventory(request,m,o.id));assert.equal(again.status,201);assert.equal(again.body.inventory.active.order_version,2);assert.equal(stockBalance(db,p.id).reserved,3);assert.equal(db.prepare('SELECT count(*) n FROM inventory_order_events').get().n,3);verifyInventory(db);
});
test('reservation conflict, duplicate submission and reserve/revise race cannot mix versions',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);await stock(request,m,p,'receive',2);const s=await inventory(request,m,o.id),results=await Promise.all([postReservation(request,m,s,'reserve',{},'same-reservation'),postReservation(request,m,s,'reserve',{},'same-reservation')]);assert.deepEqual(results.map(x=>x.status),[201,201]);assert.deepEqual(results[0].body,results[1].body);assert.equal(counts(db).inventory_order_events,1);assert.equal((await postReservation(request,m,s)).body.error.code,'RESERVATION_CONFLICT');await postReservation(request,m,results[0].body.inventory,'release');const fresh=await inventory(request,m,o.id),race=await Promise.all([postReservation(request,m,fresh),revise(request,m,o)]);assert.equal(race.filter(x=>x.status===201).length,1);verifyInventory(db);
});
test('service-only or cancelled orders cannot reserve and new reserve cannot use inactive or mismatched-unit catalog',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),service=await product(request,m,{category:'service',unit:'次'}),o=await order(request,m,[service]),p=await product(request,m),normal=await order(request,m,[p]);assert.equal((await postReservation(request,m,await inventory(request,m,o.id),'reserve',{stock_versions:[{product_id:service.id,sequence:0}]})).body.error.code,'NO_STOCK_ITEMS');await request('/api/retail/orders/'+normal.id+'/cancel',{...m,method:'POST',data:{expected_version:1,reason:'虚构取消'}});assert.equal((await postReservation(request,m,await inventory(request,m,normal.id))).body.error.code,'ORDER_CANCELLED');assert.equal(counts(db).inventory_order_events,0);
});
test('stock accounting unit/category locks after ledger exists while reprice/deactivate preserve history and permit release',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);await stock(request,m,p);const data={expected_version:1,name:p.name,category:p.category,brand:p.brand,specification:p.specification,unit:p.unit,list_price_cents:p.list_price_cents,status:p.status,reason:'虚构目录修订'},path='/api/retail/products/'+p.id+'/versions';assert.equal((await request(path,{...m,method:'POST',data:{...data,unit:'对'}})).body.error.code,'STOCK_UNIT_LOCKED');assert.equal((await request(path,{...m,method:'POST',data:{...data,category:'service'}})).status,409);const reserve=await postReservation(request,m,await inventory(request,m,o.id));assert.equal(reserve.status,201);assert.equal((await request(path,{...m,method:'POST',data:{...data,list_price_cents:29900,status:'inactive'}})).status,201);assert.equal((await postReservation(request,m,reserve.body.inventory,'release')).status,201);assert.equal((await postReservation(request,m,await inventory(request,m,o.id))).body.error.code,'STOCK_PRODUCT_CHANGED');verifyInventory(db);
});
test('stock audit failure and multi-line reservation/release audit failure roll back all ledgers and retry intent',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);db.exec("CREATE TRIGGER reject_stock_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'inventory.%' BEGIN SELECT RAISE(ABORT,'audit failure');END");assert.equal((await stock(request,m,p)).status,500);assert.equal(counts(db).inventory_events,0);db.exec('DROP TRIGGER reject_stock_audit');await stock(request,m,p);for(const action of ['reserve','release']){const s=await inventory(request,m,o.id),before=counts(db),key='retry-'+action;db.exec("CREATE TRIGGER reject_stock_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'inventory.order.%' BEGIN SELECT RAISE(ABORT,'audit failure');END");assert.equal((await postReservation(request,m,s,action,{},key)).status,500);assert.deepEqual(counts(db),before);db.exec('DROP TRIGGER reject_stock_audit');assert.equal((await postReservation(request,m,s,action,{},key)).status,201);}verifyInventory(db);
});
test('inventory complete totals and literal paginated search do not sum incompatible units or cap counts at one hundred',async t=>{
 const {request,login}=await fixture(t),m=await login('manager');for(let i=0;i<105;i++)await product(request,m,{sku:'ITEM-'+String(i).padStart(3,'0'),unit:i%2?'副':'片'});const first=(await request('/api/inventory/products?limit=100',m)).body;assert.equal(first.total,105);assert.equal(first.counts.unrecorded,105);assert.equal(first.items.length,100);const second=(await request('/api/inventory/products?limit=100&offset='+first.next_offset,m)).body;assert.equal(second.items.length,5);assert.equal(new Set([...first.items,...second.items].map(x=>x.id)).size,105);assert.equal((await request('/api/inventory/products?q=%25',m)).body.total,0);for(const query of ['limit=0','limit=101','offset=-1','state=sold'])assert.equal((await request('/api/inventory/products?'+query,m)).status,422);
});
test('inventory immutable ledgers and direct database guards reject extra, bad arithmetic and occupied-order edits',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);await stock(request,m,p,'receive',2);await postReservation(request,m,await inventory(request,m,o.id));for(const table of inventoryTables)assert.throws(()=>db.exec('DELETE FROM '+table),/immutable/);const h=db.prepare('SELECT * FROM retail_order_versions WHERE order_id=?').get(o.id),values=Object.values(h);values[1]=2;assert.throws(()=>db.prepare('INSERT INTO retail_order_versions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...values),/release inventory/);const e=db.prepare('SELECT * FROM inventory_events WHERE product_id=? ORDER BY sequence DESC LIMIT 1').get(p.id),v=Object.values(e);v[0]=crypto.randomUUID();v[4]++;v[5]='receive';v[10]=v[11]=null;assert.throws(()=>db.prepare('INSERT INTO inventory_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...v),/balance invalid/);
});
test('inventory backup and independent restore retain active reservations, released originals and quarantined balances',async t=>{
 const {request,login,db,path,dir}=await fixture(t,{persist:true}),m=await login('manager'),p=await product(request,m),a=await order(request,m,[p]),b=await order(request,m,[{...p,quantity:2}]);await stock(request,m,p,'receive',10);await stock(request,m,p,'isolate',2);const first=await postReservation(request,m,await inventory(request,m,a.id));await postReservation(request,m,first.body.inventory,'release');await postReservation(request,m,await inventory(request,m,b.id));const before=orderInventory(db,b.id),backup=await createBackup(path,join(dir,'backup')),restored=await restoreBackup(backup.backup,join(dir,'restore')),copy=openDatabase(restored.database);try{for(const table of inventoryTables)assert.deepEqual(copy.prepare('SELECT * FROM '+table).all(),db.prepare('SELECT * FROM '+table).all());assert.deepEqual(orderInventory(copy,b.id),before);assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n,0);}finally{copy.close();}
});
test('inventory recovery rejects tampered balances even after original protection trigger is reinstated',async t=>{
 const {request,login,db,path,dir}=await fixture(t,{persist:true}),m=await login('manager'),p=await product(request,m);await stock(request,m,p);const sql=db.prepare("SELECT sql FROM sqlite_schema WHERE name='inventory_events_no_update'").get().sql;db.exec('DROP TRIGGER inventory_events_no_update;UPDATE inventory_events SET available=available+1');db.exec(sql);await assert.rejects(createBackup(path,join(dir,'bad')),/库存数量流水/);
});
test('inventory pending request rechecks revoked session and first password gate before any write',async t=>{
 const {request,login,db,origin}=await fixture(t),m=await login('manager'),p=await product(request,m),data=JSON.stringify({expected_sequence:0,expected_product_version:1,action:'receive',quantity:2,reason:'虚构待处理请求'}),u=new URL(origin),response=new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path:'/api/inventory/products/'+p.id+'/events',method:'POST',headers:{Cookie:m.cookie,'X-CSRF-Token':m.csrf,'Idempotency-Key':'pending-stock-body','Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{let value='';r.on('data',x=>value+=x);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(value)}));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{db.prepare('DELETE FROM sessions WHERE user_id=?').run('manager');req.end(data.slice(10));},30);});assert.equal((await response).status,401);assert.equal(counts(db).inventory_events,0);const next=await login('manager');db.prepare('INSERT INTO user_security (user_id,must_change_password) VALUES (?,1)').run('manager');assert.equal((await request('/api/inventory/products',next)).body.error.code,'PASSWORD_CHANGE_REQUIRED');
});

test('inventory stale stock preview and competing release reject without double credit',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),f=await login('front'),p=await product(request,m),o=await order(request,m,[p]);await stock(request,m,p,'receive',3);let s=await inventory(request,m,o.id);await stock(request,m,p,'isolate',1);assert.equal((await postReservation(request,m,s)).body.error.code,'STOCK_CONFLICT');s=await inventory(request,m,o.id);assert.equal((await postReservation(request,m,s,'reserve',{stock_versions:[]})).status,422);const reserved=(await postReservation(request,m,s)).body.inventory,results=await Promise.all([postReservation(request,m,reserved,'release'),postReservation(request,f,reserved,'release')]);assert.deepEqual(results.map(x=>x.status).sort(),[201,409]);assert.deepEqual([stockBalance(db,p.id).available,stockBalance(db,p.id).reserved,stockBalance(db,p.id).quarantined],[2,0,1]);verifyInventory(db);
});
test('inventory customer timeline contains saved reservation/release and keeps pure stock entries independent',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);await stock(request,m,p);let state=(await postReservation(request,m,await inventory(request,m,o.id))).body.inventory;await postReservation(request,m,state,'release');const timeline=(await request('/api/customers/one/timeline?kind=inventory',m)).body;assert.equal(timeline.items.length,2);assert.equal(timeline.items[0].entity_id,o.id);assert.equal(timeline.items[0].details.action,'release');assert.equal(timeline.items[0].details.order_version,1);assert.equal((await request('/api/customers/two/timeline?kind=inventory',m)).body.items.length,0);
});
test('inventory ledger pagination retains complete one-hundred-plus history and original operation order',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m);for(let i=0;i<105;i++)assert.equal((await stock(request,m,p,'receive',1)).status,201);const first=(await request('/api/inventory/products/'+p.id+'?limit=100',m)).body,next=(await request('/api/inventory/products/'+p.id+'?limit=100&offset='+first.next_offset,m)).body;assert.equal(first.total,105);assert.equal(first.history.length,100);assert.equal(next.history.length,5);assert.deepEqual([...first.history,...next.history].map(x=>x.sequence),Array.from({length:105},(_,i)=>105-i));assert.equal(stockBalance(db,p.id).on_hand,105);verifyInventory(db);
});
function seedBase(db){db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');for(const name of ['seedDemoScenarios','seedDemoPeople','seedDemoProfiles','seedDemoCycleRevisions','seedDemoTasks','seedDemoTaskExecution','seedDemoTaskExceptions','seedDemoTaskEvidence','seedDemoTaskCompletions','seedDemoTaskAmendments','seedDemoTaskChains','seedDemoRetail'])demo[name](db);}
test('inventory synthetic available/reserved/quarantined/released stages do not reset later stock changes',()=>{
 const db=openDatabase(':memory:');try{seedBase(db);assert.deepEqual(demo.seedDemoInventory(db),{movements:14,reservations:3});assert.equal(orderInventory(db,'demo-order-revised').active.order_version,2);assert.equal(orderInventory(db,'demo-order-draft').active,null);const current=db.prepare("SELECT max(version) v FROM retail_product_versions WHERE product_id='demo-product-frame'").get();insertStockEvent(db,{product_id:'demo-product-frame',product_version:current.v,store_id:'store-a',action:'receive',quantity:7,reason:'后来补充的虚构数量',created_by:'demo-manager'});const sql=db.prepare('SELECT * FROM inventory_events ORDER BY product_id,sequence').all(),events=db.prepare('SELECT * FROM inventory_order_events').all();assert.deepEqual(demo.seedDemoInventory(db),{movements:0,reservations:0});assert.deepEqual(db.prepare('SELECT * FROM inventory_events ORDER BY product_id,sequence').all(),sql);assert.deepEqual(db.prepare('SELECT * FROM inventory_order_events').all(),events);assert.equal(db.prepare('SELECT count(*) n FROM work_tasks').get().n,26);verifyInventory(db);}finally{db.close();}
});
test('V0.16 populated retail upgrade preserves old orders/versions/quotes and invents no stock or reservations',()=>{
 const dir=mkdtempSync(join(tmpdir(),'optical-inventory-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);try{db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&x<'014').sort()){db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(file,new Date().toISOString());}seedBase(db);const tables=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations' ORDER BY name").all().map(x=>x.name),before=Object.fromEntries(tables.map(t=>[t,db.prepare('SELECT * FROM '+t).all()]));db.close();db=openDatabase(path);for(const table of tables)assert.deepEqual(db.prepare('SELECT * FROM '+table).all(),before[table]);for(const table of inventoryTables)assert.equal(db.prepare('SELECT count(*) n FROM '+table).get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,40);assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{db.close();rmSync(dir,{recursive:true,force:true});}
});

test('order lines captured before stock accounting cannot reserve a changed quantity unit or category',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),changed=await request('/api/retail/products/'+p.id+'/versions',{...m,method:'POST',data:{expected_version:1,name:p.name,category:'lens',brand:p.brand,specification:p.specification,unit:'片',list_price_cents:p.list_price_cents,status:'active',reason:'建账前改变虚构目录计量'}});assert.equal(changed.status,201);await stock(request,m,p,'receive',5);const state=await inventory(request,m,o.id);assert.equal(state.requirements[0].eligible,false);assert.equal((await postReservation(request,m,state)).body.error.code,'STOCK_PRODUCT_CHANGED');assert.equal(stockBalance(db,p.id).reserved,0);const revised=await revise(request,m,o,{items:[{product_id:p.id,product_version:2,quantity:2,unit_price_cents:100,note:null}]});assert.equal(revised.status,201);assert.equal((await postReservation(request,m,await inventory(request,m,o.id))).status,201);verifyInventory(db);
});
