import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {insertProductVersion} from '../src/retail.mjs';
import {physicalStock} from '../src/stock-ledger.mjs';
const now=()=>new Date().toISOString(),notes={note:'虚构实际办理',reason:'明确原始来源',next_step:'依实际后续办理'},metadata={lot_status:'unknown',lot_code:null,expiry_status:'unknown',expiry_date:null,location_status:'unknown',location_note:null,manufacturer_note:null,source_note:'虚构原收货资料',source_reference:'DEMO-ONLY',...notes},known={...metadata,lot_status:'recorded',lot_code:'DEMO-LOT',expiry_status:'provided',expiry_date:'2099-01-01',location_status:'recorded',location_note:'虚构隔离柜'},supplier={code:'TEST-SUPPLIER',name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构',settlement_note:null,source_note:'虚构',source_reference:'DEMO',status:'active',reason:'虚构'};
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-RECEIPT',name:'虚构实物',category:'lens',brand:null,specification:'原规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201);x.product=z.body.product;P.createSupplier(x.db,'a',supplier,'manager');x.purchase=P.createPurchase(x.db,'a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'虚构收货原采购',purpose_note:'实际用途',source_note:'虚构实际来源',source_reference:'DEMO',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'虚构明确来源',ordered_at:now(),order_reference:'DEMO-ORDER',...notes},action==='approve'?'manager':'front');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];return x;}
const input=(x,over={})=>({order_event_id:x.order.order_event_id,position:1,received_quantity:2,bound_quantity:2,received_at:now(),receiver_label:'虚构收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'虚构实际到货，不是自动验收',...metadata,...over});
async function receipt(x,over={},who=x.f,key=crypto.randomUUID()){const z=await x.request('/api/purchase-receipts',{...who,method:'POST',key,data:{expected_sequence:R.receivingSequence(x.db,'a'),...input(x,over)}});if(z.status===201)x.receipt=z.body.record;return z;}
const eventInput=(x,action,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,...notes,...(action.startsWith('quality_')?{checked_at:now(),requirement_source:'虚构明确人工验收要求，不是默认标准',require_lot:false,require_expiry:false,require_location:false,checks:[{label:'实际外观项目',result:action==='quality_pass'?'pass':'fail'}]}:{}),...(action==='inbound'?{inbound_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision}:{}),...over};};
async function act(x,action,over={},who=x.m,key=crypto.randomUUID()){return x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...who,method:'POST',key,data:eventInput(x,action,over)});}
async function revise(x,over={}){const r=R.receiptRecord(x.db,x.receipt.id);return x.request('/api/purchase-receipts/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,...metadata,...over}});}
const good=z=>assert.equal(z.status,201,JSON.stringify(z.body));
import * as Q from '../src/purchase-quality.mjs';
import {verifyPurchaseQuality} from '../src/purchase-quality-recovery.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
async function base(t,over={}){const x=await setup(t,over);good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound',{inbound_bucket:over.bucket||'available'}));return x;}
const qi=(x,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),receipt_id:r.id,receipt_version_id:r.version_id,quantity:1,source_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,custody_confirmed_at:now(),custody_source:'实际核对原收货箱与本批在库数量（虚构）',observed_at:now(),observation_note:'实际待复检情况（虚构）',source_reference:'DEMO-ACTUAL-CUSTODY',...notes,...over};};
async function caseCreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-quality',{...who,method:'POST',key,data:qi(x,over)});if(z.status===201)x.q=z.body.record;return z;}
const qe=(x,action,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,action,...notes,...(action==='release'?{expected_stock_sequence:c.stock.sequence,expected_outbound_revision:c.stock.outbound_revision}:{checked_at:now(),requirement_source:'本次实际人工要求（虚构），不是通用标准',require_lot:true,require_expiry:true,require_location:true,checks:[{label:'实际本批复检项目（虚构）',result:action==='quality_pass'?'pass':'fail'}]}),...over};};
async function qact(x,action,over={},who=x.p,key=crypto.randomUUID()){return x.request('/api/purchase-quality/'+x.q.id+'/events',{...who,method:'POST',data:qe(x,action,over),key});}
async function qrevise(x,over={},who=x.p){const r=R.receiptRecord(x.db,x.receipt.id),c=Q.purchaseQualityRecord(x.db,x.q.id);return x.request('/api/purchase-quality/'+c.id+'/versions',{...who,method:'POST',data:{expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,receipt_version_id:r.version_id,observed_at:now(),observation_note:'明确新增实际观察',source_reference:'DEMO-NEW-FACT',...notes,...over}});}
const verify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);};
import * as S from '../src/supplier-returns.mjs';
import {supplierReturnSequence} from '../src/supplier-return-ledger.mjs';
import {verifySupplierReturns} from '../src/supplier-return-recovery.mjs';
import {seedDemoSupplierReturns} from '../src/demo-supplier-returns.mjs';
const si=(x,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:supplierReturnSequence(x.db,'a'),case_id:c.id,quantity:2,source_note:'实际原批退供安排（虚构）',quality_version_id:c.version_id,quality_event_id:c.current.id,receipt_version_id:c.receipt_current.id,expected_case_return_revision:c.case_return_revision,return_basis:'人工明确退供依据（虚构），不预设正式政策',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-RETURN',...notes,...over};};
async function sb(t,opts={}){const x=await base(t,{bucket:'quarantined',...opts});good(await caseCreate(x,{quantity:2,source_bucket:'quarantined'}));good(await qact(x,'quality_fail'));return x;}
async function create(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns',{...who,method:'POST',data:si(x,over),key});if(z.status===201)x.s=z.body.record;return z;}
const se=(x,action,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id);return {expected_sequence:supplierReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,decision_basis:'本次人工商业依据（虚构）',...notes,...over};};
const sa=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/supplier-returns/'+x.s.id+'/events',{...who,method:'POST',data:se(x,action,over),key});
async function approved(x){good(await create(x));good(await sa(x,'submit'));good(await sa(x,'approve'));return x;}
const hi=(x,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id),s=r.source;return {expected_sequence:supplierReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,quantity:1,handed_at:now(),collector_label:'虚构实际接收人',destination_note:'虚构实际接收地点',external_reference:null,source_identity:null,source_note:'本次实际交出事实（虚构）',expected_stock_sequence:s.stock.sequence,expected_outbound_revision:s.stock.outbound_revision,expected_product_return_revision:s.stock.return_revision,expected_case_return_revision:s.balance.case_return_revision,expected_handed_quantity:r.balance.handed_quantity,reason:notes.reason,next_step:notes.next_step,...over};};
async function hand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns/'+x.s.id+'/handoffs',{...who,method:'POST',data:hi(x,over),key});if(z.status===201)x.h=z.body.record.handoffs[0];return z;}
const ri=(x,over={})=>({expected_sequence:supplierReturnSequence(x.db,'a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'可核对供应方实际收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const receive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/supplier-return-handoffs/'+x.h.id+'/receipts',{...who,method:'POST',data:ri(x,over),key});
const verified=x=>{verify(x);verifySupplierReturns(x.db);};

import {inventorySources} from '../src/inventory-sources.mjs';
const sources=(x,q='')=>x.request('/api/inventory/products/'+x.product.id+'/sources'+q,x.m);
test('same SKU overview connects receipt, quality and return with explicit original and actual quantities, without inferring batch custody',async t=>{const x=await sb(t);await approved(x);good(await hand(x));good(await receive(x));const z=await sources(x);assert.equal(z.status,200,JSON.stringify(z.body));assert.deepEqual(z.body.counts,{receipt:1,quality:1,supplier_return:1,reservation:0,dispatch:0,stock:2});const r=z.body.items.find(x=>x.kind==='receipt'),q=z.body.items.find(x=>x.kind==='quality'),s=z.body.items.find(x=>x.kind==='supplier_return');assert.equal(r.current_batch_custody_quantity,null);assert.equal(r.returned_quantity,1);assert.equal(r.protected_quantity,1);assert.equal(q.balance.remaining_quantity,1);assert.equal(s.balance.handed_quantity,1);assert.equal(s.balance.received_quantity,1);assert.equal(z.body.reconciliation.supplier_handed_quantity,1);assert.equal(z.body.stock.quarantined,1);assert.equal(z.body.reconciliation.batch_allocation_status,'not_implemented');});
test('unposted extra receipt remains a saved actual arrival and never appears as posted or inferred available stock',async t=>{const x=await setup(t);good(await receipt(x,{received_quantity:4,bound_quantity:2}));const z=await sources(x);assert.equal(z.status,200,JSON.stringify(z.body));const r=z.body.items[0];assert.equal(r.posted_quantity,0);assert.equal(r.unmatched_received_quantity,2);assert.equal(z.body.stock.recorded,false);assert.equal(r.current_batch_custody_quantity,null);});
test('complete counts, bounded pages and six-way classification do not repeat or omit same-millisecond sources',async t=>{const x=await sb(t);await approved(x);for(let i=0;i<32;i++)insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'receive',quantity:1,reason:'虚构另一来源实物 '+i,created_by:'manager'});const z=await sources(x);assert.equal(z.body.total,37);assert.equal(z.body.items.length,30);assert.equal((await sources(x,'?offset=30')).status,409);const b=await sources(x,'?offset=30&expected_source='+z.body.source_token);assert.equal(b.body.items.length,7);const keys=[...z.body.items,...b.body.items].map(x=>x.kind+':'+x.id);assert.equal(new Set(keys).size,37);const s=await sources(x,'?kind=stock&limit=100');assert.equal(s.body.total,34);assert.equal(s.body.items.length,34);});
test('current source token covers changes in physical stock, original receipt metadata, quality and return facts',async t=>{const x=await sb(t);await approved(x);for(const mutate of [()=>hand(x),()=>revise(x,{...known,lot_code:'LATEST-FACT'}),()=>qrevise(x,{expected_return_revision:1})]){const old=await sources(x);good(await mutate());assert.equal((await sources(x,'?offset=1&expected_source='+old.body.source_token)).status,409);}const r=await sources(x,'?kind=receipt');assert.equal(r.body.items[0].receipt.lot_code,'LATEST-FACT');});
test('store scope, guardian, disabled sessions and action permissions protect every source type',async t=>{const x=await sb(t);await approved(x);for(const q of ['','?kind=stock','?kind=supplier_return']){assert.equal((await x.request('/api/inventory/products/'+x.product.id+'/sources'+q,x.o)).status,404);assert.equal((await x.request('/api/inventory/products/'+x.product.id+'/sources'+q,x.g)).status,403);}assert.equal((await x.request('/api/inventory/products/'+x.product.id+'/sources',x.f)).status,200);x.db.exec("UPDATE users SET active=0 WHERE id='manager'");assert.equal((await sources(x)).status,401);});
test('filters, page bounds, stale explicit source and write methods are rejected without inventing facts',async t=>{const x=await sb(t);const before=x.db.prepare('SELECT count(*) n FROM audit_events').get().n;for(const q of ['?kind=money','?limit=101','?limit=-1','?offset=x','?invented_rule=1'])assert.equal((await sources(x,q)).status,422);assert.equal((await sources(x,'?expected_source=bad')).status,409);assert.equal((await x.request('/api/inventory/products/'+x.product.id+'/sources',{...x.m,method:'POST',data:{quantity:1}})).status,405);assert.equal(x.db.prepare('SELECT count(*) n FROM audit_events').get().n,before);});
test('independent restore reproduces source links, source tokens, current quantities and exact historical contexts',async t=>{const x=await sb(t,{persist:true});await approved(x);good(await hand(x));good(await receive(x));const product=x.db.prepare('SELECT p.id,p.store_id,p.sku,v.* FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id WHERE p.id=? ORDER BY version DESC LIMIT 1').get(x.product.id),before=inventorySources(x.db,product,{limit:100}),b=await createBackup(x.path,join(x.dir,'backup')),z=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(z.database);t.after(()=>d.close());assert.deepEqual(inventorySources(d,product,{limit:100}),before);});
test('historical inventory stock rows retain exact receipt and quality event references after later receipt correction',async t=>{const x=await sb(t);good(await qrevise(x));good(await qact(x,'quality_pass'));good(await qact(x,'release',{},x.m));good(await revise(x,{...known,lot_code:'AFTER-RELEASE'}));const z=await sources(x,'?kind=stock');assert.equal(z.status,200,JSON.stringify(z.body));const unq=z.body.items.find(x=>x.event.action==='unquarantine');assert.equal(unq.quality_refs.length,1);assert.equal(unq.quality_refs[0].case_id,x.q.id);const inbound=z.body.items.filter(x=>x.receipt_refs.length);assert.equal(inbound.length,2);assert.ok(inbound.every(r=>r.receipt_refs[0].receipt_id===x.receipt.id));});
import * as demo from '../src/demo-data.mjs';
import {insertReservation} from '../src/inventory.mjs';
import {insertDispatch} from '../src/dispatch.mjs';
test('saved original-order reservations and actual sales link through the same SKU without duplicating split original lines',async t=>{const db=openDatabase(':memory:');t.after(()=>db.close());db.exec("INSERT INTO stores VALUES('store-a','A')");const x={db};for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional'],['demo-parent','guardian']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,role==='guardian'?null:'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment'])demo[fn](x.db);const delivery=x.db.prepare("SELECT id FROM fulfillment_events WHERE job_id='demo-processing-fulfillment-delivered' AND position=2 AND action='deliver'").get().id,out=insertDispatch(x.db,delivery,{quantity:1,reason:'虚构实际出库'},'demo-manager').event;const product=db.prepare("SELECT p.id,p.store_id,p.sku,v.* FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id WHERE p.id='demo-product-lens' ORDER BY version DESC LIMIT 1").get();const z={body:inventorySources(db,product,{limit:100})};const sale=z.body.items.find(r=>r.kind==='dispatch'&&r.id===out.id);assert.equal(sale.event.quantity,1);assert.equal(sale.event.order_id,'demo-order-fulfillment-delivered');assert.equal(sale.event.quarantined_after,out.quarantined_after);const reservations=z.body.items.filter(r=>r.kind==='reservation');assert.equal(new Set(reservations.map(r=>r.id)).size,reservations.length);assert.ok(reservations.some(r=>r.active_quantity>0));assert.equal(z.body.reconciliation.sales_outbound.available,1);});
test('current SKU rename changes source token while original supplier and batch references preserve fixed source versions',async t=>{const x=await sb(t);const old=await sources(x);insertProductVersion(x.db,x.product.id,{...x.product,name:'新的当前名称',reason:'目录实际更正'},'manager');assert.equal((await sources(x,'?expected_source='+old.body.source_token)).status,409);const z=await sources(x);assert.equal(z.body.product.name,'新的当前名称');const r=z.body.items.find(r=>r.kind==='receipt');assert.equal(r.receipt.product_version,1);assert.equal(r.receipt.supplier_name,supplier.name);});
