import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('store-a','A'),('store-b','B')");for(const [id,role,store] of [['manager','manager','store-a'],['front','reception','store-a'],['professional','professional','store-a'],['other','manager','store-b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','store-a'],['two','store-a'],['other-child','store-b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='store-a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {insertProductVersion} from '../src/retail.mjs';
import {physicalStock} from '../src/stock-ledger.mjs';
const now=()=>new Date().toISOString(),notes={note:'虚构实际办理',reason:'明确原始来源',next_step:'依实际后续办理'},metadata={lot_status:'unknown',lot_code:null,expiry_status:'unknown',expiry_date:null,location_status:'unknown',location_note:null,manufacturer_note:null,source_note:'虚构原收货资料',source_reference:'DEMO-ONLY',...notes},known={...metadata,lot_status:'recorded',lot_code:'DEMO-LOT',expiry_status:'provided',expiry_date:'2099-01-01',location_status:'recorded',location_note:'虚构隔离柜'},supplier={code:'TEST-SUPPLIER',name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构',settlement_note:null,source_note:'虚构',source_reference:'DEMO',status:'active',reason:'虚构'};
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-RECEIPT',name:'虚构实物',category:'lens',brand:null,specification:'原规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201);x.product=z.body.product;P.createSupplier(x.db,'store-a',supplier,'manager');x.purchase=P.createPurchase(x.db,'store-a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'虚构收货原采购',purpose_note:'实际用途',source_note:'虚构实际来源',source_reference:'DEMO',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'虚构明确来源',ordered_at:now(),order_reference:'DEMO-ORDER',...notes},action==='approve'?'manager':'front');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];return x;}
const input=(x,over={})=>({order_event_id:x.order.order_event_id,position:1,received_quantity:2,bound_quantity:2,received_at:now(),receiver_label:'虚构收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'虚构实际到货，不是自动验收',...metadata,...over});
async function receipt(x,over={},who=x.f,key=crypto.randomUUID()){const z=await x.request('/api/purchase-receipts',{...who,method:'POST',key,data:{expected_sequence:R.receivingSequence(x.db,'store-a'),...input(x,over)}});if(z.status===201)x.receipt=z.body.record;return z;}
const eventInput=(x,action,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:R.receivingSequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,action,...notes,...(action.startsWith('quality_')?{checked_at:now(),requirement_source:'虚构明确人工验收要求，不是默认标准',require_lot:false,require_expiry:false,require_location:false,checks:[{label:'实际外观项目',result:action==='quality_pass'?'pass':'fail'}]}:{}),...(action==='inbound'?{inbound_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision}:{}),...over};};
async function act(x,action,over={},who=x.m,key=crypto.randomUUID()){return x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...who,method:'POST',key,data:eventInput(x,action,over)});}
async function revise(x,over={}){const r=R.receiptRecord(x.db,x.receipt.id);return x.request('/api/purchase-receipts/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:R.receivingSequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,...metadata,...over}});}
const good=z=>assert.equal(z.status,201,JSON.stringify(z.body));
import * as Q from '../src/purchase-quality.mjs';
import {verifyPurchaseQuality} from '../src/purchase-quality-recovery.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
async function base(t,over={}){const x=await setup(t,over);good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound',{inbound_bucket:over.bucket||'available'}));return x;}
const qi=(x,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'store-a'),receipt_id:r.id,receipt_version_id:r.version_id,quantity:1,source_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,custody_confirmed_at:now(),custody_source:'实际核对原收货箱与本批在库数量（虚构）',observed_at:now(),observation_note:'实际待复检情况（虚构）',source_reference:'DEMO-ACTUAL-CUSTODY',...notes,...over};};
async function caseCreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-quality',{...who,method:'POST',key,data:qi(x,over)});if(z.status===201)x.q=z.body.record;return z;}
const qe=(x,action,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'store-a'),expected_revision:c.revision,expected_version:c.current_version,action,...notes,...(action==='release'?{expected_stock_sequence:c.stock.sequence,expected_outbound_revision:c.stock.outbound_revision}:{checked_at:now(),requirement_source:'本次实际人工要求（虚构），不是通用标准',require_lot:true,require_expiry:true,require_location:true,checks:[{label:'实际本批复检项目（虚构）',result:action==='quality_pass'?'pass':'fail'}]}),...over};};
async function qact(x,action,over={},who=x.p,key=crypto.randomUUID()){return x.request('/api/purchase-quality/'+x.q.id+'/events',{...who,method:'POST',data:qe(x,action,over),key});}
async function qrevise(x,over={},who=x.p){const r=R.receiptRecord(x.db,x.receipt.id),c=Q.purchaseQualityRecord(x.db,x.q.id);return x.request('/api/purchase-quality/'+c.id+'/versions',{...who,method:'POST',data:{expected_sequence:Q.purchaseQualitySequence(x.db,'store-a'),expected_revision:c.revision,expected_version:c.current_version,receipt_version_id:r.version_id,observed_at:now(),observation_note:'明确新增实际观察',source_reference:'DEMO-NEW-FACT',...notes,...over}});}
const verify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);};
import * as S from '../src/supplier-returns.mjs';
import {supplierReturnSequence} from '../src/supplier-return-ledger.mjs';
import {verifySupplierReturns} from '../src/supplier-return-recovery.mjs';
import {seedDemoSupplierReturns} from '../src/demo-supplier-returns.mjs';
const si=(x,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:supplierReturnSequence(x.db,'store-a'),case_id:c.id,quantity:2,source_note:'实际原批退供安排（虚构）',quality_version_id:c.version_id,quality_event_id:c.current.id,receipt_version_id:c.receipt_current.id,expected_case_return_revision:c.case_return_revision,return_basis:'人工明确退供依据（虚构），不预设正式政策',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-RETURN',...notes,...over};};
async function sb(t,opts={}){const x=await base(t,{bucket:'quarantined',...opts});good(await caseCreate(x,{quantity:2,source_bucket:'quarantined'}));good(await qact(x,'quality_fail'));return x;}
async function create(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns',{...who,method:'POST',data:si(x,over),key});if(z.status===201)x.s=z.body.record;return z;}
const se=(x,action,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id);return {expected_sequence:supplierReturnSequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,action,decision_basis:'本次人工商业依据（虚构）',...notes,...over};};
const sa=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/supplier-returns/'+x.s.id+'/events',{...who,method:'POST',data:se(x,action,over),key});
async function approved(x){good(await create(x));good(await sa(x,'submit'));good(await sa(x,'approve'));return x;}
const hi=(x,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id),s=r.source;return {expected_sequence:supplierReturnSequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,quantity:1,handed_at:now(),collector_label:'虚构实际接收人',destination_note:'虚构实际接收地点',external_reference:null,source_identity:null,source_note:'本次实际交出事实（虚构）',expected_stock_sequence:s.stock.sequence,expected_outbound_revision:s.stock.outbound_revision,expected_product_return_revision:s.stock.return_revision,expected_case_return_revision:s.balance.case_return_revision,expected_handed_quantity:r.balance.handed_quantity,reason:notes.reason,next_step:notes.next_step,...over};};
async function hand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns/'+x.s.id+'/handoffs',{...who,method:'POST',data:hi(x,over),key});if(z.status===201)x.h=z.body.record.handoffs[0];return z;}
const ri=(x,over={})=>({expected_sequence:supplierReturnSequence(x.db,'store-a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'可核对供应方实际收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const receive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/supplier-return-handoffs/'+x.h.id+'/receipts',{...who,method:'POST',data:ri(x,over),key});
const verified=x=>{verify(x);verifySupplierReturns(x.db);};

import * as E from '../src/purchase-extra-returns.mjs';
import {extraReturnSequence} from '../src/purchase-extra-return-ledger.mjs';
import {verifyExtraReturns} from '../src/purchase-extra-return-recovery.mjs';
async function extraBase(t,opts={}){const x=await setup(t,opts);good(await receipt(x,{received_quantity:4,bound_quantity:1}));return x;}
const ei=(x,over={})=>{const s=E.extraReturnSource(x.db,x.receipt.id);return {expected_sequence:extraReturnSequence(x.db,'store-a'),receipt_id:x.receipt.id,receipt_version_id:s.receipt_version.id,expected_receipt_sequence:R.receivingSequence(x.db,'store-a'),expected_receipt_return_revision:s.balance.receipt_return_revision,quantity:2,custody_confirmed_at:now(),custody_source:'人工实际核对超收原件身份数量和位置（虚构）',source_note:'原超收独立未入账来源（虚构）',return_basis:'明确人工退回依据（虚构）',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-EXTRA-RETURN',...notes,...over};};
async function ecreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-extra-returns',{...who,method:'POST',data:ei(x,over),key});if(z.status===201)x.e=z.body.record;return z;}
const eevent=(x,action,over={})=>{const e=E.extraReturnRecord(x.db,x.e.id);return {expected_sequence:extraReturnSequence(x.db,'store-a'),expected_revision:e.revision,expected_version:e.current_version,action,decision_basis:'真实人工商业决定（虚构）',...notes,...over};};
const eact=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/purchase-extra-returns/'+x.e.id+'/events',{...who,method:'POST',data:eevent(x,action,over),key});
async function eapprove(x){good(await ecreate(x));good(await eact(x,'submit'));good(await eact(x,'approve'));}
const ehi=(x,over={})=>{const r=E.extraReturnRecord(x.db,x.e.id);return {expected_sequence:extraReturnSequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,expected_receipt_return_revision:r.source.balance.receipt_return_revision,expected_handed_quantity:r.balance.handed_quantity,quantity:1,handed_at:now(),collector_label:'虚构接收人',destination_note:'虚构实际地点',external_reference:null,source_identity:null,source_note:'可核对超收实际交出（虚构）',reason:notes.reason,next_step:notes.next_step,...over};};
async function ehand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-extra-returns/'+x.e.id+'/handoffs',{...who,method:'POST',data:ehi(x,over),key});if(z.status===201)x.eh=z.body.record.handoffs[0];return z;}
const eri=(x,over={})=>({expected_sequence:extraReturnSequence(x.db,'store-a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'实际超收退回件的供应方收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const ereceive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/purchase-extra-handoffs/'+x.eh.id+'/receipts',{...who,method:'POST',data:eri(x,over),key});
const eVerify=x=>{verifyReceiving(x.db);verifyExtraReturns(x.db);};
import * as C from '../src/inventory-custody.mjs';
import {verifyCustody} from '../src/inventory-custody-recovery.mjs';
const ci=(x,over={})=>({receipt_id:x.receipt.id,expected_sequence:C.custodySequence(x.db,'store-a'),expected_source:C.custodySource(x.db,x.receipt.id).source_token,quantity:1,bucket:'available',observed_at:now(),identity_source:'人工实际核对原收货箱、本次所见数量与原单位（虚构）',location_label:'虚构A柜第1格',location_source:'已发生现场核对及可查位置来源（虚构）',source_reference:'DEMO-CUSTODY',...notes,...over});
async function ccreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/inventory-custody',{...who,method:'POST',data:ci(x,over),key});if(z.status===201)x.c=z.body.record;return z;}
const cv=(x,over={})=>{const r=C.custodyRecord(x.db,x.c.id),i=ci(x,over);delete i.receipt_id;return {...i,expected_revision:r.revision,expected_version:r.current_version};};
const cobserve=(x,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/inventory-custody/'+x.c.id+'/observations',{...who,method:'POST',data:cv(x,over),key});
const cwithdraw=(x,over={},who=x.m)=>{const r=C.custodyRecord(x.db,x.c.id);return x.request('/api/inventory-custody/'+x.c.id+'/events',{...who,method:'POST',data:{expected_sequence:C.custodySequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,action:'withdraw',reason:'明确纠错撤回本版解释，不注销实物',next_step:'重新实际核对原身份数量和位置',...over}});};
const cVerify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);verifySupplierReturns(x.db);verifyCustody(x.db);};
import * as demo from '../src/demo-data.mjs';
import {dispatchRecord,insertDispatch,verifyDispatch} from '../src/dispatch.mjs';
import {batchCandidates,batchTables} from '../src/inventory-batches.mjs';
import {batchSequence,outboundBatches} from '../src/inventory-batch-ledger.mjs';
import {verifyBatches} from '../src/inventory-batch-recovery.mjs';
async function batchBase(t,opts={}){const x=await fixture(t,opts);for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional'],['demo-parent','guardian']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,role==='guardian'?null:'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment'])demo[fn](x.db);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});x.product=x.db.prepare("SELECT id,store_id FROM retail_products WHERE id='demo-product-lens'").get();P.createSupplier(x.db,'store-a',supplier,'manager');x.purchase=P.createPurchase(x.db,'store-a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'原批实际出库（虚构）',purpose_note:'虚构用途',source_note:'虚构独立原采购',source_reference:'DEMO-ACTUAL-BATCH',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'明确人工实际决定（虚构）',ordered_at:now(),order_reference:'DEMO-BATCH-ORDER',...notes},'manager');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound'));good(await ccreate(x,{quantity:2}));x.delivery=x.db.prepare("SELECT id FROM fulfillment_events WHERE job_id='demo-processing-fulfillment-delivered' AND position=2 AND action='deliver'").get().id;assert.equal(dispatchRecord(x.db,x.delivery).source_mode,'available');return x;}
const bi=(x,over={})=>{const r=dispatchRecord(x.db,x.delivery),c=C.custodyRecord(x.db,x.c.id);return {expected_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,expected_dispatched:r.dispatched,expected_reservation_revision:r.reservation_revision,quantity:1,reason:'人工实际原批出库（虚构）',expected_batch_sequence:batchSequence(x.db,'store-a'),expected_custody_sequence:C.custodySequence(x.db,'store-a'),batch_source_note:'本次已发生原件交出的可核对事实（虚构）',batch_sources:[{custody_id:c.id,custody_version_id:c.version_id,custody_event_id:c.current.id,quantity:1,source_reference:'DEMO-ACTUAL-SALES',note:'人工明确原收货箱与本次实物（虚构）'}],...over};};
const ship=(x,data=bi(x),who=x.m,key=crypto.randomUUID())=>x.request('/api/fulfillment/events/'+x.delivery+'/dispatch',{...who,method:'POST',data,key});
const bv=x=>{verifyReceiving(x.db);verifyDispatch(x.db);verifyPurchaseQuality(x.db);verifyCustody(x.db);verifyBatches(x.db);};
test('actual dispatch explicitly traces original procurement receipt and delivered customer with exactly one physical debit',async t=>{const x=await batchBase(t),before=physicalStock(x.db,x.product.id),money=x.db.prepare('SELECT * FROM payment_events').all(),z=await ship(x);good(z);assert.equal(z.body.batch_source.status,'recorded');assert.equal(z.body.batch_source.items[0].receipt_id,x.receipt.id);assert.equal(physicalStock(x.db,x.product.id).available,before.available-1);assert.deepEqual(x.db.prepare('SELECT * FROM payment_events').all(),money);const trace=await x.request('/api/purchase-receipts/'+x.receipt.id+'/delivered-batches',x.f);assert.equal(trace.body.known_attributed_quantity,1);assert.equal(trace.body.items[0].customer_id,'sample-intake');assert.equal(trace.body.current_batch_custody_quantity,null);assert.equal(trace.body.unrecorded_prior_delivered_source,'unknown');const tl=await x.request('/api/customers/sample-intake/timeline?kind=dispatch',x.m);assert.equal(tl.body.items.find(i=>i.event_id==='dispatch:'+z.body.event.id).details.batch_source.items[0].receipt_id,x.receipt.id);bv(x);});
test('after actual batch sales old observation is historical and new custody and quality cannot reclaim sold originals using unrelated same-SKU stock',async t=>{const x=await batchBase(t);good(await ship(x));assert.equal(C.custodyRecord(x.db,x.c.id).source_current,false);assert.equal((await cobserve(x,{quantity:2})).status,409);good(await cobserve(x,{quantity:1}));assert.equal((await caseCreate(x,{quantity:2})).status,409);good(await caseCreate(x,{quantity:1}));bv(x);});
test('one actual dispatch may explicitly use two independently observed positions in same original receipt but shares the bound capacity',async t=>{const x=await batchBase(t),first=C.custodyRecord(x.db,x.c.id);good(await ccreate(x,{quantity:2,location_label:'独立第二实见位置（虚构）'}));const data=bi(x,{quantity:2});data.batch_sources.unshift({custody_id:first.id,custody_version_id:first.version_id,custody_event_id:first.current.id,quantity:1,source_reference:'DEMO-FIRST-POSITION',note:'原件分处第一已知位置（虚构）'});good(await ship(x,data));assert.equal(x.db.prepare('SELECT sum(quantity) q FROM inventory_batch_refs').get().q,2);assert.equal(physicalStock(x.db,x.product.id).available>=0,true);bv(x);});
test('duplicate roots, incomplete sums, extra fields and orphan source metadata fail without physical or batch writes',async t=>{const x=await batchBase(t),before=physicalStock(x.db,x.product.id),n=x.db.prepare('SELECT count(*) n FROM inventory_outbounds').get().n;for(const data of [bi(x,{quantity:2}),bi(x,{batch_sources:null}),bi(x,{batch_sources:[]}),bi(x,{batch_sources:[{...bi(x).batch_sources[0],inferred:true}]}),{...bi(x),batch_sources:undefined},bi(x,{quantity:2,batch_sources:[bi(x).batch_sources[0],bi(x).batch_sources[0]]})])assert.equal((await ship(x,data)).status,422);assert.deepEqual(physicalStock(x.db,x.product.id),before);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_outbounds').get().n,n);bv(x);});
test('changed original metadata cannot be silently adopted while old actual attributed dispatch remains fixed',async t=>{const x=await batchBase(t),data=bi(x);good(await revise(x,{...known,lot_code:'LATER-ACTUAL-LOT'}));assert.equal((await ship(x,data)).status,409);good(await cobserve(x,{quantity:2}));const z=await ship(x);good(z);const refs=z.body.batch_source;good(await revise(x,{...known,lot_code:'AFTER-SALES-METADATA'}));assert.deepEqual((await x.request('/api/inventory/outbounds/'+z.body.event.id+'/batches',x.m)).body.items,refs.items);bv(x);});
test('successful negative actual dispatch retries replay exact original fact after custody withdrawal and metadata changes',async t=>{const x=await batchBase(t),data=bi(x),key='batch-negative-retry',z=await ship(x,data,x.m,key);good(z);good(await cwithdraw(x));good(await revise(x,{...known,lot_code:'RETRY-LATER'}));const again=await ship(x,data,x.m,key);good(again);assert.deepEqual(again.body,z.body);assert.equal((await ship(x,{...data,reason:'同key改来源'},x.m,key)).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_batch_declarations').get().n,1);bv(x);});
test('front desk actual writes and professional scoped reads remain separate from guardians and another store',async t=>{const x=await batchBase(t);assert.equal((await ship(x,bi(x),x.p)).status,403);assert.equal((await ship(x,bi(x),x.g)).status,403);assert.equal((await ship(x,bi(x),x.o)).status,404);const z=await ship(x,bi(x),x.f);good(z);for(const path of ['/api/inventory/products/'+x.product.id+'/batch-sources','/api/inventory/outbounds/'+z.body.event.id+'/batches','/api/purchase-receipts/'+x.receipt.id+'/delivered-batches']){assert.equal((await x.request(path,x.p)).status,200);assert.equal((await x.request(path,x.g)).status,403);assert.equal((await x.request(path,x.o)).status,404);}bv(x);});
test('audit failure rolls back original physical debit, declaration, seven source contexts and retry response atomically',async t=>{const x=await batchBase(t),data=bi(x),key='batch-audit',before=physicalStock(x.db,x.product.id);x.db.exec("CREATE TRIGGER batch_audit_fail BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test');END");assert.equal((await ship(x,data,x.m,key)).status,500);assert.deepEqual(physicalStock(x.db,x.product.id),before);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_batch_declarations').get().n,0);x.db.exec('DROP TRIGGER batch_audit_fail');good(await ship(x,data,x.m,key));good(await ship(x,data,x.m,key));bv(x);});
test('no selected original source stays explicitly unknown and creates no fabricated declaration',async t=>{const x=await batchBase(t),data=bi(x);for(const k of ['batch_sources','batch_source_note','expected_batch_sequence','expected_custody_sequence'])delete data[k];const z=await ship(x,data);good(z);assert.equal(z.body.batch_source.status,'not_recorded');assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_batch_declarations').get().n,0);bv(x);});
test('two simultaneous uses of one actual source retain exactly one debit with second stale choice refused',async t=>{const x=await batchBase(t),data=bi(x),z=await Promise.all([ship(x,data),ship(x,data)]);assert.deepEqual(z.map(x=>x.status).sort(),[201,409]);assert.equal(x.db.prepare('SELECT sum(quantity) n FROM inventory_batch_refs').get().n,1);bv(x);});
test('native immutable source, complete declaration and actual source chronology guards cannot be bypassed',async t=>{const x=await batchBase(t),before=physicalStock(x.db,x.product.id);assert.throws(()=>insertDispatch(x.db,x.delivery,bi(x,{batch_sources:[{...bi(x).batch_sources[0],quantity:3}],quantity:3}),'manager'),/batch|quantity|actual/);assert.deepEqual(physicalStock(x.db,x.product.id),before);good(await ship(x));for(const n of batchTables){if(!x.db.prepare('SELECT count(*) n FROM '+n).get().n)continue;const k=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+k+'='+k),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}bv(x);});
test('seven actual batch tables survive verified backup and independent restore with sessions revoked',async t=>{const x=await batchBase(t,{persist:true});good(await ship(x));good(await cobserve(x,{quantity:1}));const b=await createBackup(x.path,join(x.dir,'backup')),z=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(z.database);t.after(()=>d.close());for(const n of batchTables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all());assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyBatches(d);});
test('candidate pagination leases include original receipt and custody changes and never autofill quantity facts',async t=>{const x=await batchBase(t);const path='/api/inventory/products/'+x.product.id+'/batch-sources',z=await x.request(path,x.m);assert.equal(z.body.items[0].known_capacity,2);assert.equal((await x.request(path+'?offset=1',x.m)).status,409);const next=path+'?offset=1&expected_source='+z.body.source_token;assert.equal((await x.request(next,x.m)).status,200);good(await cwithdraw(x));assert.equal((await x.request(next,x.m)).status,409);assert.equal((await x.request(path,x.m)).body.total,0);bv(x);});

import {seedDemoBatches} from '../src/demo-inventory-batches.mjs';
test('seven separately sourced synthetic original batch sales stages preserve all old rows and SKU balances and repeat exactly',async t=>{const x=await batchBase(t),tables=x.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),snapshot=()=>Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()])),before=snapshot(),balances=x.db.prepare('SELECT id FROM retail_products').all().map(p=>[p.id,physicalStock(x.db,p.id)]);assert.deepEqual(seedDemoBatches(x.db),{receipts:7,custodies:7,outbounds:6,declarations:5});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);for(const[id,b]of balances)assert.deepEqual(physicalStock(x.db,id),b);bv(x);const after=snapshot();assert.deepEqual(seedDemoBatches(x.db),{receipts:0,custodies:0,outbounds:0,declarations:0});assert.deepEqual(snapshot(),after);});

import {insertReservation} from '../src/inventory.mjs';
test('reserved dispatch cannot borrow an available original observation and retains existing reservation proof',async t=>{const x=await batchBase(t);x.delivery=x.db.prepare("SELECT id FROM fulfillment_events WHERE job_id='demo-processing-parallel' AND position=1 AND action='deliver'").get().id;const r=dispatchRecord(x.db,x.delivery);if(r.source_mode!=='reserved')insertReservation(x.db,r.order_id,'reserve','明确虚构原单预留','manager');assert.equal(dispatchRecord(x.db,x.delivery).source_mode,'reserved');assert.equal((await ship(x)).status,409);const data=bi(x);for(const k of ['batch_sources','batch_source_note','expected_batch_sequence','expected_custody_sequence'])delete data[k];const z=await ship(x,data);good(z);assert.equal(z.body.event.source_mode,'reserved');assert.equal(z.body.batch_source.status,'not_recorded');bv(x);});
async function pausedBatch(x,data,change){const payload=JSON.stringify(data),req=httpRequest(x.origin+'/api/fulfillment/events/'+x.delivery+'/dispatch',{method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}}),done=new Promise((resolve,reject)=>{req.on('error',reject);req.on('response',r=>{let s='';r.on('data',x=>s+=x);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(s)}));});});req.write(payload.slice(0,12));await new Promise(resolve=>setTimeout(resolve,60));try{await change();}finally{req.end(payload.slice(12));}return done;}
test('paused actual-source body rechecks live actor and reset-password gate before creating any actual stock fact',async t=>{const x=await batchBase(t),before=physicalStock(x.db,x.product.id);assert.equal((await pausedBatch(x,bi(x),()=>x.db.exec("UPDATE users SET role='reception' WHERE id='manager'"))).status,401);assert.deepEqual(physicalStock(x.db,x.product.id),before);x.db.exec("UPDATE users SET role='manager' WHERE id='manager'");assert.equal((await pausedBatch(x,bi(x),()=>x.db.prepare('INSERT INTO user_security(user_id,must_change_password) VALUES(?,1)').run('manager'))).status,403);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_batch_declarations').get().n,0);});
test('paused actual-source body rejects changed observation without silently substituting newest custody',async t=>{const x=await batchBase(t),data=bi(x);assert.equal((await pausedBatch(x,data,()=>C.custodyEvent(x.db,x.c.id,{action:'withdraw',...notes},'manager'))).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_batch_declarations').get().n,0);bv(x);});
function altered(db,table,sql){const triggers=db.prepare("SELECT name,sql FROM sqlite_schema WHERE type='trigger' AND tbl_name=?").all(table);for(const x of triggers)db.exec('DROP TRIGGER '+x.name);db.exec(sql);for(const x of triggers)db.exec(x.sql);}
test('same-millisecond receipt metadata prefix cannot substitute a later original revision for actual dispatch',async t=>{const x=await batchBase(t),at=now();const result=insertDispatch(x.db,x.delivery,bi(x),'manager',at);R.receiptVersion(x.db,x.receipt.id,{...known,lot_code:'SAME-MS-LATER'},'front',at);bv(x);altered(x.db,'inventory_batch_declarations','UPDATE inventory_batch_declarations SET receipt_sequence='+R.receivingSequence(x.db,'store-a'));assert.throws(()=>verifyBatches(x.db),/原核对|同刻/);assert.equal(result.batch_source.status,'recorded');});
test('same-millisecond post-sales custody cannot be falsely moved before the earlier actual dispatch',async t=>{const x=await batchBase(t),at=now();insertDispatch(x.db,x.delivery,bi(x),'manager',at);const r=C.custodyObservation(x.db,x.c.id,{...ci(x),quantity:1,observed_at:at},'manager',at);bv(x);altered(x.db,'inventory_custody_version_batch_context',"UPDATE inventory_custody_version_batch_context SET batch_sequence=0 WHERE version_id='"+r.version_id+"'");assert.throws(()=>verifyBatches(x.db),/同刻/);});
test('orphan or incomplete native declarations fail recovery even if protected physical debit is present',async t=>{const x=await batchBase(t);good(await ship(x));altered(x.db,'inventory_batch_refs','DELETE FROM inventory_batch_refs');assert.throws(()=>verifyBatches(x.db),/完整实际来源/);});
test('nonempty schema41 upgrade keeps earlier sales unknown and preserves every original custody and quality row',t=>{const dir=mkdtempSync(join(tmpdir(),'batch-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,41)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('store-a','A')");for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional'],['demo-parent','guardian']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,role==='guardian'?null:'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment','seedDemoAftercare'])demo[fn](d);const old=d.prepare('SELECT * FROM inventory_outbounds ORDER BY rowid').all();assert.ok(old.length);d.close();const u=openDatabase(path);t.after(()=>u.close());assert.deepEqual(u.prepare('SELECT * FROM inventory_outbounds ORDER BY rowid').all(),old);assert.equal(u.prepare('SELECT count(*) n FROM inventory_batch_declarations').get().n,0);assert.equal(u.prepare("SELECT count(*) n FROM inventory_batch_boundary WHERE kind='outbound'").get().n,old.length);for(const e of old)assert.equal(outboundBatches(u,e.id).status,'not_recorded');verifyBatches(u);});
