import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as l from '../src/longitudinal.mjs';
import {verifyLongitudinal} from '../src/longitudinal-recovery.mjs';
import {seedDemoLongitudinal} from '../src/demo-longitudinal.mjs';
import {seedDemoScenarios} from '../src/demo-data.mjs';
const note={note:'人工安排（虚构）',reason:'明确依据'},manifest=l.emptyLongitudinalManifest,fields=()=>({title:'长期档案（虚构）',baseline_note:'资料未取得，不生成默认指标',goal_note:'明确跟进资料',source_note:'人工明确来源',manifest:manifest(),reason:'明确依据'}),actual=()=>({measured_at:new Date(Date.now()-1000).toISOString(),eye:'right',condition_status:'unknown',condition_note:'条件未明确，待补充',source:'staff_record',source_note:'人工记录来源',record_note:'实际资料文字记录（虚构）',manifest:manifest(),reason:'明确依据'}),planning=()=>({due_date:'2026-10-01',purpose:'明确复查安排（虚构）',items_note:'需补充检查条件与来源',owner_id:'professional',source_note:'明确复查安排来源',manifest:manifest(),...note});
async function setup(t,o){const x=await fixture(t,o);x.m=await x.login('manager');x.f=await x.login('front');x.pro=await x.login('professional');x.parent=await x.login('parent');x.cycle=(await x.request('/api/customers/one/cycles',{...x.m,method:'POST',data:{type:'followup',goal:'明确长期随访需求'}})).body.cycle;return x;}
const write=(x,path,data,who=x.pro,key)=>x.request('/api/longitudinal'+path,{...who,method:'POST',key,data:{expected_sequence:l.longitudinalSequence(x.db,'a'),...data}});
async function draft(x,extra={}){const r=await write(x,'/cases',{customer_id:'one',cycle_id:x.cycle.id,cycle_version:1,...fields(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function ce(x,c,action,extra={},who=x.pro){return write(x,'/cases/'+c.id+'/events',{expected_revision:l.longitudinalCase(x.db,c.id).revision,action,...note,...extra},who);}
async function active(x){const c=await draft(x),r=await ce(x,c,'activate');assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function obs(x,c,extra={}){const r=await write(x,'/cases/'+c.id+'/observations',{expected_case_revision:l.longitudinalCase(x.db,c.id).revision,...actual(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function plan(x,c,extra={}){const r=await write(x,'/cases/'+c.id+'/plans',{expected_case_revision:l.longitudinalCase(x.db,c.id).revision,...planning(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function pe(x,p,action,extra={},who=x.pro){return write(x,'/plans/'+p.id+'/events',{expected_revision:l.reviewPlan(x.db,p.id).revision,expected_case_revision:l.longitudinalCase(x.db,p.case_id).revision,action,...note,...extra},who);}
const complete=(o)=>({completed_at:new Date().toISOString(),resolution_note:'明确实际资料处理结果',next_step:'下一次另行明确安排',manifest:{...manifest(),observations:[{id:o.id,version:o.current_version}]}}),all=db=>Object.fromEntries(l.longitudinalTables.map(t=>[t,db.prepare('SELECT * FROM '+t).all()]));
function tamper(db,t,sql){const trigger=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(t+'_no_update').sql;db.exec('DROP TRIGGER '+t+'_no_update');db.exec(sql);db.exec(trigger);}
test('case captures fixed demand and descriptive versions without modifying service cycle',async t=>{const x=await setup(t),before=x.db.prepare('SELECT * FROM service_cycles').all(),c=await active(x),r=await write(x,'/cases/'+c.id+'/versions',{expected_revision:c.revision,...fields(),title:'明确修订'});assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.record.status,'active');assert.equal(r.body.record.version,2);assert.deepEqual(x.db.prepare('SELECT * FROM service_cycles').all(),before);verifyLongitudinal(x.db);});
test('reception reads while guardians and other stores cannot access internal dossier or mutations',async t=>{const x=await setup(t),c=await active(x);assert.equal((await x.request('/api/longitudinal/cases/'+c.id,x.f)).status,200);assert.equal((await x.request('/api/longitudinal/cases/'+c.id,x.parent)).status,403);assert.equal((await x.request('/api/longitudinal/cases/'+c.id,await x.login('other'))).status,404);assert.equal((await ce(x,c,'pause',{},x.f)).status,403);assert.equal((await write(x,'/cases',{customer_id:'one',cycle_id:x.cycle.id,cycle_version:1,...fields()},x.m)).status,403);});
test('draft forbids actual checks and planning, historical actual may be entered while paused',async t=>{const x=await setup(t),c=await draft(x);assert.equal((await write(x,'/cases/'+c.id+'/observations',{expected_case_revision:1,...actual()})).status,409);await ce(x,c,'activate');await ce(x,c,'pause');await obs(x,c);assert.equal((await write(x,'/cases/'+c.id+'/plans',{expected_case_revision:3,...planning()})).status,409);await ce(x,c,'resume');await plan(x,c);verifyLongitudinal(x.db);});
test('derived UTC overdue never completes or mutates a plan and excludes paused dates',async t=>{const x=await setup(t),c=await active(x),p=await plan(x,c),before=all(x.db);assert.equal(l.reviewPlan(x.db,p.id,{as_of:'2026-10-01'}).overdue,false);assert.equal(l.reviewPlan(x.db,p.id,{as_of:'2026-10-02'}).overdue,true);assert.deepEqual(all(x.db),before);await pe(x,p,'pause');assert.equal(l.reviewPlan(x.db,p.id,{as_of:'2026-10-09'}).overdue,false);verifyLongitudinal(x.db);});
test('left/right filtering includes one unsplit both record and conditions/source/date remain explicit',async t=>{const x=await setup(t),c=await active(x);for(const eye of ['right','left','both','not_specified'])await obs(x,c,{eye});const r=await x.request('/api/longitudinal/observations?eye=right&condition_status=unknown&condition=待补充&source=staff_record&from=2020-01-01&to=2030-01-01',x.f);assert.equal(r.status,200);assert.equal(r.body.total,2);assert.deepEqual(r.body.items.map(o=>o.eye).sort(),['both','right']);});
test('actual time and entry time are separate, future/noncanonical times and invented metrics fail',async t=>{const x=await setup(t),c=await active(x),o=await obs(x,c,{measured_at:'2020-01-01T00:00:00.000Z'});assert.ok(o.measured_at<o.created_at);for(const extra of [{measured_at:'2030-01-01T00:00:00.000Z'},{measured_at:'2020-01-01'},{diopters:1},{eye:'OD'},{condition_status:'comparable'}])assert.equal((await write(x,'/cases/'+c.id+'/observations',{expected_case_revision:c.revision,...actual(),...extra})).status,422);verifyLongitudinal(x.db);});
test('completion requires actual source and result, not deadline or scheduled date alone',async t=>{const x=await setup(t),c=await active(x),p=await plan(x,c);assert.equal((await pe(x,p,'complete',{...complete({id:'missing',current_version:1}),manifest:manifest()})).status,422);assert.equal((await pe(x,p,'complete',complete({id:'missing',current_version:1}))).status,409);const o=await obs(x,c);assert.equal((await pe(x,p,'complete',{...complete(o),completed_at:'2020-01-01T00:00:00.000Z'})).status,422);assert.equal((await pe(x,p,'complete',complete(o))).status,201);assert.equal(l.reviewPlan(x.db,p.id).status,'completed');assert.equal((await pe(x,p,'resume')).status,409);verifyLongitudinal(x.db);});
test('case closure requires resolving both scheduled and paused arrangements',async t=>{const x=await setup(t),c=await active(x),p=await plan(x,c),q=await plan(x,c);await pe(x,q,'pause');const closure={close_reason:'明确结束理由',next_step:'未来另建档案',followup:null};assert.equal((await ce(x,c,'close',closure)).status,409);await pe(x,p,'cancel',{resolution_note:'明确取消',next_step:'不再执行本安排',followup:null});assert.equal((await ce(x,c,'close',closure)).status,409);await pe(x,q,'complete',complete(await obs(x,c)));assert.equal((await ce(x,c,'close',closure)).status,201);assert.equal((await ce(x,c,'resume')).status,409);verifyLongitudinal(x.db);});
test('explicit transfer changes current ownership without changing original creator or individual plan owners',async t=>{const x=await setup(t),c=await active(x),p=await plan(x,c);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('new-pro','new-pro','新责任人',hashPassword('synthetic-only-password'),'professional','a');assert.equal((await ce(x,c,'transfer',{owner_id:'new-pro'},x.m)).status,201);const current=l.longitudinalCase(x.db,c.id);assert.equal(current.initial_owner_id,'professional');assert.equal(l.reviewPlan(x.db,p.id).owner_id,'professional');assert.equal((await write(x,'/cases/'+c.id+'/observations',{expected_case_revision:current.revision,...actual()})).status,403);assert.equal((await pe(x,p,'pause')).status,201);assert.equal((await pe(x,p,'assign',{owner_id:'new-pro'},x.m)).status,201);verifyLongitudinal(x.db);});
test('correction appends immutable versions and old planned sources survive while resume demands new selection',async t=>{const x=await setup(t),c=await active(x),o=await obs(x,c),p=await plan(x,c,{manifest:{...manifest(),observations:[{id:o.id,version:1}]}});assert.equal((await write(x,'/observations/'+o.id+'/versions',{expected_case_revision:c.revision,expected_version:1,...actual(),record_note:'更正来源'})).status,201);assert.equal(l.observation(x.db,o.id,1).record_note,o.record_note);await pe(x,p,'pause');assert.equal((await pe(x,p,'resume')).status,409);assert.equal((await pe(x,p,'revise',{...planning(),manifest:{...manifest(),observations:[{id:o.id,version:2}]}})).status,201);assert.equal((await pe(x,p,'resume')).status,201);verifyLongitudinal(x.db);});
test('historical document version remains fixed after later revision',async t=>{const x=await setup(t),d=(await x.request('/api/customers/one/documents',{...x.pro,method:'POST',data:{title:'资料（虚构）',content:'人工记录',source:'external',attachment_ids:[]}})).body.document,c=await draft(x,{manifest:{...manifest(),documents:[d.id]}});await x.request('/api/documents/'+d.record_id+'/versions',{...x.pro,method:'POST',data:{expected_version:1,title:'新资料',content:'后来的记录',source:'external',revision_reason:'修订来源',attachment_ids:[]}});assert.equal((await ce(x,c,'activate')).status,201);assert.deepEqual(l.longitudinalCase(x.db,c.id).manifest.documents,[d.id]);verifyLongitudinal(x.db);});
test('manifest rejects unknown, duplicate, cross-customer and cross-case references',async t=>{const x=await setup(t),a=await active(x),b=await active(x),o=await obs(x,b);for(const m of [{...manifest(),extra:true},{...manifest(),documents:['missing']},{...manifest(),observations:[{id:o.id,version:1}]},{...manifest(),observations:[{id:o.id,version:1},{id:o.id,version:1}]}])assert.ok([409,422].includes((await write(x,'/cases/'+a.id+'/plans',{expected_case_revision:a.revision,...planning(),manifest:m})).status));assert.equal(x.db.prepare('SELECT count(*) n FROM review_plans').get().n,0);});
test('stale store sequence, case revision and source version prevent writes',async t=>{const x=await setup(t),c=await active(x);assert.equal((await write(x,'/cases/'+c.id+'/plans',{expected_sequence:0,expected_case_revision:c.revision,...planning()})).status,409);assert.equal((await write(x,'/cases/'+c.id+'/plans',{expected_case_revision:1,...planning()})).status,409);const o=await obs(x,c);assert.equal((await write(x,'/observations/'+o.id+'/versions',{expected_case_revision:c.revision,expected_version:2,...actual()})).status,409);});
test('idempotent replay appends once and inactive/forced password sessions cannot replay',async t=>{const x=await setup(t),c=await active(x),i={expected_case_revision:c.revision,expected_sequence:l.longitudinalSequence(x.db,'a'),...actual()},path='/cases/'+c.id+'/observations',key='fixed-idempotency',a=await write(x,path,i,x.pro,key),b=await write(x,path,i,x.pro,key);assert.equal(a.status,201);assert.deepEqual(a.body,b.body);assert.equal(x.db.prepare('SELECT count(*) n FROM longitudinal_observations').get().n,1);x.db.prepare('INSERT INTO user_security VALUES(?,1,1)').run('professional');assert.equal((await write(x,path,i,x.pro,key)).status,403);});
test('audit failure rolls back all journal, root, idempotency and source writes',async t=>{const x=await setup(t),c=await active(x),before=all(x.db),seq=l.longitudinalSequence(x.db,'a');x.db.exec("CREATE TRIGGER fail_long_audit BEFORE INSERT ON audit_events WHEN NEW.action='longitudinal.observation.create' BEGIN SELECT RAISE(ABORT,'test audit rejection'); END");assert.equal((await write(x,'/cases/'+c.id+'/observations',{expected_case_revision:c.revision,...actual()})).status,500);assert.deepEqual(all(x.db),before);assert.equal(l.longitudinalSequence(x.db,'a'),seq);});
test('lists use full totals and fixed sequence for subsequent pages with bounded real dates',async t=>{const x=await setup(t),c=await active(x);for(let n=0;n<32;n++)await obs(x,c);const a=(await x.request('/api/longitudinal/observations?limit=30',x.f)).body;assert.equal(a.total,32);assert.equal(a.next_offset,30);assert.equal((await x.request('/api/longitudinal/observations?offset=30',x.f)).status,422);assert.equal((await x.request('/api/longitudinal/observations?offset=30&expected_sequence='+a.sequence,x.f)).body.items.length,2);await obs(x,c);assert.equal((await x.request('/api/longitudinal/observations?offset=30&expected_sequence='+a.sequence,x.f)).status,409);for(const q of ['limit=101','offset=-1','as_of=2026-02-30','from=2026-10-10&to=2026-10-01'])assert.equal((await x.request('/api/longitudinal/plans?'+q,x.f)).status,422);});
test('completion and cancellation preserve old plan fields; native writes enforce same rule',async t=>{const x=await setup(t),c=await active(x),p=await plan(x,c),o=await obs(x,c),i={...planning(),...complete(o),action:'complete',purpose:'偷改原目的'};assert.throws(()=>l.reviewPlanEvent(x.db,p.id,i,'professional'),/transition/);assert.equal(l.reviewPlan(x.db,p.id).revision,1);assert.throws(()=>x.db.prepare('UPDATE review_plans SET customer_id=? WHERE id=?').run('two',p.id),/immutable/);verifyLongitudinal(x.db);});
test('native source and journal guards reject inappropriate actors and stale case/manifest data',async t=>{const x=await setup(t),c=await active(x);assert.throws(()=>l.createObservation(x.db,c.id,actual(),'front'),/actor|owner|current case/);const o=await obs(x,c),e=x.db.prepare('SELECT * FROM longitudinal_observation_versions WHERE observation_id=?').get(o.id);assert.throws(()=>x.db.prepare('INSERT INTO longitudinal_observation_versions('+Object.keys(e).join(',')+') VALUES('+Object.keys(e).map(()=>'?').join(',')+')').run(...Object.values({...e,version:2,sequence:e.sequence})),/journal/);});
test('recovery rejects altered actual source and overwritten native completion fields',async t=>{const x=await setup(t),c=await active(x),o=await obs(x,c),p=await plan(x,c);await pe(x,p,'complete',complete(o));verifyLongitudinal(x.db);tamper(x.db,'review_plan_events',"UPDATE review_plan_events SET purpose='偷改' WHERE action='complete'");assert.throws(()=>verifyLongitudinal(x.db),/核对失败/);});
test('recovery rejects later correction substituted into an earlier source snapshot even in same millisecond',async t=>{const x=await setup(t),c=await active(x),at=new Date().toISOString(),o=l.createObservation(x.db,c.id,actual(),'professional',at),p=l.createReviewPlan(x.db,c.id,{...planning(),manifest:{...manifest(),observations:[{id:o.id,version:1}]}},'professional',at);l.observationVersion(x.db,o.id,{...actual(),record_note:'后来的更正'},'professional',at);verifyLongitudinal(x.db);const m=JSON.stringify({...manifest(),observations:[{id:o.id,version:2}]});const tr=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='review_plan_events_no_update'").get().sql;x.db.exec('DROP TRIGGER review_plan_events_no_update');x.db.prepare('UPDATE review_plan_events SET manifest_json=? WHERE plan_id=?').run(m,p.id);x.db.exec(tr);assert.throws(()=>verifyLongitudinal(x.db),/核对失败/);});
test('request body wait rechecks changed ownership and cached replay still checks active session',async t=>{const x=await setup(t),c=await active(x),path='/api/longitudinal/cases/'+c.id+'/observations',i={expected_sequence:l.longitudinalSequence(x.db,'a'),expected_case_revision:c.revision,...actual()},data=JSON.stringify(i),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.pro.cookie,'X-CSRF-Token':x.pro.csrf,'Idempotency-Key':'slow-body','Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{l.longitudinalCaseEvent(x.db,c.id,{action:'pause',...note},'manager');req.end(data.slice(10));},20);});assert.equal(status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM longitudinal_observations').get().n,0);});
test('explicit next-task reference must match customer/cycle/current revision and remains historical after task changes',async t=>{const x=await setup(t),c=await active(x),p=await plan(x,c),task=(await x.request('/api/customers/one/tasks',{...x.m,method:'POST',data:{title:'明确后续',instructions:'核对联系',cycle_id:x.cycle.id,cycle_version:1,visit_id:null,assignee_id:'professional',reason:'明确分派'}})).body.task;assert.equal((await pe(x,p,'cancel',{resolution_note:'明确取消',next_step:'另行跟进',followup:{id:task.id,revision:1}})).status,201);await x.request('/api/tasks/'+task.id+'/accept',{...x.pro,method:'POST',data:{expected_revision:1,reason:'明确接收'}});verifyLongitudinal(x.db);assert.equal((await ce(x,c,'close',{close_reason:'结束档案',next_step:'后续任务处理',followup:{id:task.id,revision:1}})).status,409);assert.equal((await ce(x,c,'close',{close_reason:'结束档案',next_step:'后续任务处理',followup:{id:task.id,revision:2}})).status,201);verifyLongitudinal(x.db);});
test('schema28 backs up seven tables and independent restore preserves data while revoking sessions',async t=>{const x=await setup(t,{persist:true}),c=await active(x),o=await obs(x,c),p=await plan(x,c);await pe(x,p,'complete',complete(o));const before=all(x.db),b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,36);const r=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(r.database);assert.deepEqual(all(d),before);assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyLongitudinal(d);d.close();});
test('schema27 upgrade leaves existing business records untouched and new longitudinal tables empty',t=>{const dir=mkdtempSync(join(tmpdir(),'optical-long-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,27)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,new Date().toISOString());}d.exec("INSERT INTO stores VALUES('old','old')");d.close();const u=openDatabase(path);assert.equal(u.prepare('SELECT count(*) n FROM stores').get().n,1);for(const t of l.longitudinalTables)assert.equal(u.prepare('SELECT count(*) n FROM '+t).get().n,0);verifyLongitudinal(u);u.close();});
test('customer timeline includes fixed case, actual and review events, guardian route stays internal',async t=>{const x=await setup(t),c=await active(x);await obs(x,c);await plan(x,c);const r=await x.request('/api/customers/one/timeline?limit=50',x.f);assert.equal(r.status,200);for(const k of ['longitudinal','observation','review_plan'])assert.ok(r.body.items.some(e=>e.kind===k));assert.equal((await x.request('/api/customers/one/timeline',x.parent)).status,403);});
test('synthetic stages append once and repeat preserves all prior business data and human edits',async t=>{const x=await fixture(t),d=x.db;d.exec("INSERT INTO stores VALUES('store-a','演示')");for(const [id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');seedDemoScenarios(d);const names=['service_cycles','cycle_versions','work_tasks','task_events','document_versions','visits','guardian_links'],before=names.map(n=>d.prepare('SELECT * FROM '+n).all());assert.equal(seedDemoLongitudinal(d).cases,2);assert.deepEqual(names.map(n=>d.prepare('SELECT * FROM '+n).all()),before);const a=all(d);assert.equal(seedDemoLongitudinal(d).cases,0);assert.deepEqual(all(d),a);verifyLongitudinal(d);});
import {createTrainingProject,createTrainingPlan,insertTrainingPlanEvent,trainingPlan} from '../src/training.mjs';
import {createReassessment,reassessmentEvent} from '../src/family-training.mjs';
test('checked training reassessment can be explicitly linked by same customer while a draft is rejected',async t=>{const x=await setup(t),tc=(await x.request('/api/customers/one/cycles',{...x.m,method:'POST',data:{type:'training',goal:'明确训练需求'}})).body.cycle,project=createTrainingProject(x.db,'a',{code:'SYNTH-P',name:'虚构项目',description:'虚构',instructions:'明确人工说明',status:'active',reason:'虚构依据'},'professional'),tp=createTrainingPlan(x.db,'a','one',{cycle_id:tc.id,cycle_version:1,visit_id:null,title:'明确个人计划',assessment:'未取得统一指标',goals:'人工记录',owner_id:'professional',source:'staff_record',source_note:'明确来源',items:[{project_id:project.id,project_version:1,instructions:'明确'}],document_version_ids:[],attachment_ids:[],...note},'professional');insertTrainingPlanEvent(x.db,tp.plan.id,{action:'confirm',...note},'professional');const re=createReassessment(x.db,trainingPlan(x.db,tp.plan.id),{title:'阶段复评（虚构）',source_note:'人工来源',comparison_note:'检查条件未确认',assessment_note:'人工复评记录',next_step:'明确继续安排',direction:'needs_information',manifest:{sessions:[],reports:[],documents:[],followup:null},reason:'明确依据'},'professional');assert.equal((await write(x,'/cases',{customer_id:'one',cycle_id:x.cycle.id,cycle_version:1,...fields(),manifest:{...manifest(),reassessments:[{id:re.id,version:1,revision:1}]}})).status,409);reassessmentEvent(x.db,re.id,{action:'check',...note},'professional');await draft(x,{manifest:{...manifest(),reassessments:[{id:re.id,version:1,revision:2}]}});verifyLongitudinal(x.db);});
test('revoked session during request-body wait blocks even a prior successful idempotent response',async t=>{const x=await setup(t),c=await active(x),path='/api/longitudinal/cases/'+c.id+'/observations',i={expected_sequence:l.longitudinalSequence(x.db,'a'),expected_case_revision:c.revision,...actual()},key='slow-replay';assert.equal((await x.request(path,{...x.pro,method:'POST',data:i,key})).status,201);const data=JSON.stringify(i),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.pro.cookie,'X-CSRF-Token':x.pro.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{x.db.prepare("DELETE FROM sessions WHERE user_id='professional'").run();req.end(data.slice(10));},20);});assert.equal(status,401);assert.equal(x.db.prepare('SELECT count(*) n FROM longitudinal_observations').get().n,1);});
