import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('store-a','A'),('store-b','B')");for(const [id,role,store] of [['manager','manager','store-a'],['front','reception','store-a'],['professional','professional','store-a'],['other','manager','store-b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','store-a'],['two','store-a'],['other-child','store-b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='store-a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}

import {moneyReview,moneyEntry,moneySnapshot} from '../src/money-review.mjs';
import {seedDemoMoneyReview} from '../src/demo-money-review.mjs';
import {orderPayments,insertPayment,verifyPayments} from '../src/payments.mjs';
import {insertRefundEvent,verifyRefunds} from '../src/refunds.mjs';
function seed(x){x.db.exec("INSERT INTO users VALUES('demo-manager','demo-manager','独立虚构负责人','dummy','manager','store-a',1),('demo-front','demo-front','独立虚构前台','dummy','reception','store-a',1)");x.db.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','store-a','独立虚构客户',null,null,null,new Date().toISOString(),'manager');assert.deepEqual(seedDemoMoneyReview(x.db),{orders:7,payment_events:7,refund_events:4});verifyPayments(x.db);verifyRefunds(x.db);}
const snapshot=db=>Object.fromEntries(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN('sessions','audit_events','idempotency') ORDER BY name").all().map(x=>[x.name,db.prepare('SELECT * FROM '+x.name+' ORDER BY rowid').all()]));
test('actual store review unifies original receipts, false-entry voids and executed refunds while keeping exact complete totals',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager'),r=await x.request('/api/money-review',m);assert.equal(r.status,200);assert.equal(r.body.total,8);assert.deepEqual(r.body.summary,{valid_collection_cents:'45000',executed_refund_cents:'3000',matched_recorded_difference_cents:'42000',excluded_false_receipt_cents:'6000'});assert.deepEqual(r.body.counts,{receive_valid:5,receive_voided:1,void_reference:1,refund_executed:1});assert.equal(r.body.items.reduce((s,x)=>s+BigInt(x.signed_recorded_cents),0n),42000n);assert.ok(r.body.items.every(x=>x.external_verification==='not_recorded'));assert.equal(r.body.accounting_status,'not_defined');});
test('void is a preserved false-entry explanation and never another refund or positive collection',async t=>{const x=await fixture(t);seed(x);const z=moneyReview(x.db,'store-a',{q:'voided'});assert.equal(z.total,2);assert.ok(z.items.every(x=>x.signed_recorded_cents===0));assert.equal(z.summary.valid_collection_cents,'0');assert.equal(z.summary.executed_refund_cents,'0');const v=z.items.find(x=>x.kind==='void');assert.equal(v.actual_date_kind,'original_receipt_reference');assert.equal(v.receipt_id,z.items.find(x=>x.kind==='receive').id);});
test('pending and approved proposals have no actual financial movement; execute contributes exactly its fixed source amount',async t=>{const x=await fixture(t);seed(x);const pending=x.db.prepare("SELECT * FROM refund_events WHERE id='demo-money-review-refund-refund-pending'").get();assert.equal(moneyReview(x.db,'store-a',{q:'refund-pending'}).total,1);insertRefundEvent(x.db,pending.order_id,{action:'approve',root_id:pending.id,note:'手工批准仅安排',reason:'未实际退款'},'demo-manager');assert.equal(moneyReview(x.db,'store-a',{kind:'refund'}).total,1);const executed=moneyReview(x.db,'store-a',{kind:'refund'}).items[0];assert.equal(executed.refund_id,'demo-money-review-refund-refund-executed');assert.equal(executed.amount_cents,3000);assert.equal(executed.signed_recorded_cents,-3000);});
test('only store managers read financial totals and details; staff, guardian and other store cannot substitute source identities',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager'),entry=moneyReview(x.db,'store-a').items[0];for(const id of ['front','professional','parent']){const u=await x.login(id);for(const path of ['/api/money-review','/api/money-review/'+entry.kind+'/'+entry.id])assert.equal((await x.request(path,u)).status,403);}const other=await x.login('other');assert.equal((await x.request('/api/money-review',other)).body.total,0);assert.equal((await x.request('/api/money-review/'+entry.kind+'/'+entry.id,other)).status,404);assert.equal((await x.request('/api/money-review/'+entry.kind+'/'+entry.id,m)).status,200);});
test('same literal/date/method/kind/state filters apply to every complete summary and displayed original fact',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager');for(const filters of [{kind:'refund'},{state:'receive_voided'},{method:'cash'},{q:'refund-executed'},{q:'%'},{q:'_'},{basis:'recorded',from:'2999-01-01'},{kind:'void',method:'transfer'}]){const p=new URLSearchParams({...filters,limit:'100'}),r=await x.request('/api/money-review?'+p,m);assert.equal(r.status,200);assert.equal(r.body.items.length,r.body.total);assert.equal(String(r.body.items.reduce((sum,x)=>sum+BigInt(x.signed_recorded_cents),0n)),r.body.summary.matched_recorded_difference_cents);}assert.equal((await x.request('/api/money-review?q=%',m)).body.total,0);});
test('bounded list paging counts beyond one hundred and refuses changed financial facts or mixed filters',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager'),id='demo-money-review-unpaid';for(let n=0;n<105;n++)insertPayment(x.db,id,'receive',{amount_cents:1,method:'cash',reference:'FICTIONAL-PAGING-'+n,received_at:new Date().toISOString(),reason:'开发明确原实收'},'demo-front');const a=await x.request('/api/money-review?limit=100',m);assert.equal(a.body.total,113);assert.equal(a.body.items.length,100);assert.equal((await x.request('/api/money-review?offset=100',m)).status,409);const b=await x.request('/api/money-review?offset=100&expected_source='+a.body.source_token,m);assert.equal(b.body.items.length,13);assert.deepEqual(b.body.summary,a.body.summary);assert.equal((await x.request('/api/money-review?offset=100&kind=receive&expected_source='+a.body.source_token,m)).status,409);insertPayment(x.db,id,'receive',{amount_cents:1,method:'cash',reference:'FICTIONAL-PAGING-LATER',received_at:new Date().toISOString(),reason:'后续实收'},'demo-front');assert.equal((await x.request('/api/money-review?offset=100&expected_source='+a.body.source_token,m)).status,409);});
test('current receipt validity changes after false-entry void and makes earlier detail adoption stale',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager'),r=moneyReview(x.db,'store-a',{q:'partial'}).items[0],s=moneySnapshot(x.db,'store-a');insertPayment(x.db,r.order_id,'void',{source_id:r.id,reason:'明确原误录作废'},'demo-manager');assert.equal((await x.request('/api/money-review/receive/'+r.id+'?expected_source='+s.source_token,m)).status,409);assert.equal(moneyEntry(x.db,'store-a','receive',r.id).state,'receive_voided');assert.equal(moneyReview(x.db,'store-a',{q:'partial'}).summary.valid_collection_cents,'0');});
test('original fixed order, customer, receipt and refund identities remain exact without exposing clinical notes',async t=>{const x=await fixture(t);seed(x);for(const e of moneyReview(x.db,'store-a').items){const o=x.db.prepare('SELECT * FROM retail_orders WHERE id=?').get(e.order_id),p=x.db.prepare('SELECT * FROM payment_events WHERE id=?').get(e.receipt_id);assert.equal(e.customer_id,o.customer_id);assert.equal(e.store_id,o.store_id);assert.equal(e.order_version,p.order_version);assert.equal(e.currency,'CNY');for(const k of ['decision_basis','receiver_name','instructions','receipt_note','notes','role','password_hash'])assert.equal(Object.hasOwn(e,k),false);}verifyPayments(x.db);verifyRefunds(x.db);});
test('read-only review adds no financial, customer, clinical, stock, audit or account facts',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager'),before=snapshot(x.db),changes=x.db.prepare('SELECT total_changes() n').get().n,r=await x.request('/api/money-review',m);for(const e of r.body.items)assert.equal((await x.request('/api/money-review/'+e.kind+'/'+e.id,m)).status,200);assert.deepEqual(snapshot(x.db),before);assert.equal(x.db.prepare('SELECT total_changes() n').get().n,changes);});
test('strict real UTC date filters, bounded paging, repeated parameters and unsupported verbs reject without side effects',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager');for(const q of ['from=2026-02-30','from=2026-10-10&to=2026-10-01','kind=approved','state=income','method=bank_auto','basis=fiscal','limit=101','offset=-1','limit=1&limit=2','extra=x','q='+('a'.repeat(121))])assert.equal((await x.request('/api/money-review?'+q,m)).status,422);assert.equal((await x.request('/api/money-review',{...m,method:'POST',data:{}})).status,405);assert.equal((await x.request('/api/money-review/receive/missing',m)).status,404);});
test('relevant current customer and author names change source leases while another store activity does not',async t=>{const x=await fixture(t);seed(x);const m=await x.login('manager'),s=moneySnapshot(x.db,'store-a').source_token;x.db.exec("UPDATE users SET display_name='另一店后续名称' WHERE id='other'");assert.equal(moneySnapshot(x.db,'store-a').source_token,s);x.db.exec("UPDATE users SET display_name='本记录操作者后续名称' WHERE id='demo-front'");assert.notEqual(moneySnapshot(x.db,'store-a').source_token,s);const z=await x.request('/api/money-review',m);assert.ok(z.body.items.some(x=>x.author_name==='本记录操作者后续名称'));});
test('actual source records restore independently with identical filtered totals and no invented income, stock or prepaid ledger',async t=>{const x=await fixture(t,{persist:true});seed(x);const before=moneyReview(x.db,'store-a'),b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,46);const r=await restoreBackup(b.backup,join(x.dir,'restored')),db=openDatabase(r.database);assert.deepEqual(moneyReview(db,'store-a'),before);assert.equal(db.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyPayments(db);verifyRefunds(db);db.close();});
test('seven own synthetic source stages preserve every prior money and inventory row and never seed an unpaid zero receipt',async t=>{const x=await fixture(t);seed(x);const before=snapshot(x.db);assert.deepEqual(seedDemoMoneyReview(x.db),{orders:0,payment_events:0,refund_events:0});assert.deepEqual(snapshot(x.db),before);assert.equal(x.db.prepare("SELECT count(*) n FROM payment_events WHERE order_id='demo-money-review-unpaid'").get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_events').get().n,0);const id='demo-money-review-partial';insertPayment(x.db,id,'receive',{amount_cents:100,method:'cash',reference:'FICTIONAL-LATER-052',received_at:new Date().toISOString(),reason:'后续人工实际登记'},'demo-front');assert.deepEqual(seedDemoMoneyReview(x.db),{orders:0,payment_events:0,refund_events:0});assert.equal(orderPayments(x.db,id).recorded_cents,3100);});
import {formatCents} from '../public/money-review.js';
test('exact cent strings format large and negative facts without rounding away the original last cent',()=>{assert.equal(formatCents('9007199254740993'),'¥90,071,992,547,409.93');assert.equal(formatCents('-9007199254740993'),'-¥90,071,992,547,409.93');assert.equal(formatCents('1'),'¥0.01');});
test('matching a void explanation alone counts its original excluded amount once while both matching sources never double it',async t=>{const x=await fixture(t);seed(x);const z=moneyReview(x.db,'store-a',{kind:'void'});assert.equal(z.summary.excluded_false_receipt_cents,'6000');assert.equal(z.summary.valid_collection_cents,'0');assert.equal(moneyReview(x.db,'store-a',{q:'voided'}).summary.excluded_false_receipt_cents,'6000');});
