import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
import {paymentTables,orderPayments,verifyPayments,insertPayment} from '../src/payments.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
async function product(request,m,extra={}){const r=await request('/api/retail/products',{...m,method:'POST',data:{sku:'SKU-'+crypto.randomUUID().slice(0,8),name:'虚构镜架',category:'frame',brand:null,specification:'虚构型号',unit:'副',list_price_cents:19900,status:'active',reason:'虚构目录',...extra}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.product;}
async function order(request,m,items){const r=await request('/api/customers/one/retail-orders',{...m,method:'POST',data:{title:'库存订单（虚构）',notes:null,items:items.map(x=>({product_id:x.id,product_version:x.version,quantity:x.quantity||1,unit_price_cents:100,note:null})),reason:'虚构开单'}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.order;}
async function stock(request,m,p,action='receive',quantity=10,extra={},key=crypto.randomUUID()){const current=(await request('/api/inventory/products/'+p.id,m)).body;return request('/api/inventory/products/'+p.id+'/events',{...m,method:'POST',key,data:{expected_product_version:current.product?.version||p.version,expected_sequence:current.stock?.sequence||0,action,quantity,reason:'虚构库存操作',...extra}});}
async function inventory(request,m,id){const r=await request('/api/retail/orders/'+id+'/inventory',m);assert.equal(r.status,200);return r.body.inventory;}
function postReservation(request,m,state,action='reserve',extra={},key=crypto.randomUUID()){return request('/api/retail/orders/'+state.order_id+'/inventory/'+action,{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,reason:'虚构'+action,...(action==='reserve'?{stock_versions:state.stock_versions}:{}),...extra}});}
function revise(request,m,o,extra={}){return request('/api/retail/orders/'+o.id+'/versions',{...m,method:'POST',data:{expected_version:o.version,title:o.title,notes:'虚构修订说明',items:o.items.map(({product_id,product_version,quantity,unit_price_cents,note})=>({product_id,product_version,quantity,unit_price_cents,note})),document_version_ids:[],attachment_ids:[],reason:'虚构修订',...extra}});}

async function payments(request,m,id){const r=await request('/api/retail/orders/'+id+'/payments',m);assert.equal(r.status,200,JSON.stringify(r.body));return r.body.payments;}
async function receive(request,m,id,extra={},key=crypto.randomUUID()){const state=await payments(request,m,id);return request('/api/retail/orders/'+id+'/payments/receive',{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,amount_cents:33,method:'cash',reference:null,received_at:'2025-01-01T10:00:00.000Z',reason:'虚构实际收款登记',...extra}});}
async function voidReceipt(request,m,id,source,extra={},key=crypto.randomUUID()){const s=await payments(request,m,id);return request('/api/retail/orders/'+id+'/payments/void',{...m,method:'POST',key,data:{expected_order_version:s.order_version,expected_revision:s.revision,source_id:source,reason:'虚构未发生金额误登记，纠正记录',...extra}});}
import {parameterRecord,insertParameterVersion,insertParameterEvent,insertParameterReview,parameterReviews} from '../src/parameters.mjs';
import {parameterContext,parameterSequence} from '../src/parameter-ledger.mjs';
import {verifyParameters} from '../src/parameter-recovery.mjs';
import {processingRecord,insertProcessingJob,insertProcessingEvent,verifyProcessing} from '../src/processing.mjs';
import {fulfillmentRecord,insertFulfillmentEvent} from '../src/fulfillment.mjs';
async function setup(t,options={}){const x=await fixture(t,options),m=await x.login('manager'),f=await x.login('front'),pro=await x.login('professional'),p=await product(x.request,m),o=await order(x.request,m,[p]);const j=insertProcessingJob(x.db,o.id,{lines:[{position:1,supply_mode:'purchase',processing_mode:'internal',supplier_name:'明确虚构来源',assignee_id:'professional',due_date:null,instructions:'明确虚构交接安排'}],reason:'虚构安排'},'manager');return {...x,m,f,pro,p,o,j};}
function input(x,extra={}){return {expected_order_version:x.o.version,expected_sequence:parameterSequence(x.db,x.o.id),source:'staff_record',source_note:'明确本次交接来源（虚构）',values:[{position:1,label:'虚构交接项（非专业标准）',value:'示例值 A',unit:null,condition:'虚构条件'}],document_version_ids:[],attachment_ids:[],note:'交接记录（虚构）',reason:'本次明确依据（虚构）',...extra};}
async function save(x,extra={},who=x.f,key){return x.request('/api/retail/orders/'+x.o.id+'/parameters',{...who,method:'POST',data:input(x,extra),key});}
async function event(x,id,action,who=x.pro,extra={},key){const p=parameterRecord(x.db,id);return x.request('/api/parameters/versions/'+id+'/events',{...who,method:'POST',data:{expected_order_version:x.o.version,expected_sequence:parameterSequence(x.db,x.o.id),expected_revision:p.revision,action,note:'交接核对（虚构）',reason:'明确依据（虚构）',...extra},key});}
async function checked(x){const r=await save(x);assert.equal(r.status,201,JSON.stringify(r.body));const id=r.body.parameter.id;assert.equal((await event(x,id,'submit',x.f)).status,201);assert.equal((await event(x,id,'check')).status,201);return id;}
async function process(x,action,extra={},who=x.pro,key){const p=processingRecord(x.db,x.j.id),c=parameterContext(x.db,x.j.id);return x.request('/api/processing/jobs/'+x.j.id+'/events',{...who,method:'POST',key,data:{expected_revision:p.revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action,position:1,quantity:1,reason:'明确执行（虚构）',...extra}});}
async function review(x,outcome='continue_original',extra={},who=x.pro,key){const r=parameterReviews(x.db,x.j.id),c=r.context;return x.request('/api/processing/jobs/'+x.j.id+'/parameter-reviews',{...who,method:'POST',key,data:{expected_order_version:x.o.version,expected_sequence:c.sequence,expected_processing_revision:r.processing_revision,expected_fulfillment_revision:r.fulfillment_revision,expected_review_revision:c.review_revision,fixed_version_id:c.fixed_version_id,current_version_id:c.current_version_id,outcome,note:'明确参数变化影响（虚构）',reason:'独立核对依据（虚构）',...extra}});}
async function qc(x,action='check_pass',extra={},who=x.pro){const f=fulfillmentRecord(x.db,x.j.id),c=parameterContext(x.db,x.j.id);return x.request('/api/processing/jobs/'+x.j.id+'/fulfillment/events',{...who,method:'POST',data:{expected_revision:f.revision,expected_processing_revision:f.processing_revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,position:1,quantity:1,action,source_id:null,reason:'明确质检（虚构）',checks:[{label:'虚构外观项',result:'pass',notes:'本次明确结果'}],...extra}});}
const verify=x=>{verifyParameters(x.db);verifyProcessing(x.db);verifyPayments(x.db);verifyInventory(x.db);};
test('explicit parameter values keep physical order source and unknown units; only technical role checks submitted handover',async t=>{const x=await setup(t),r=await save(x);assert.equal(r.status,201,JSON.stringify(r.body));const p=r.body.parameter;assert.equal(p.order_version,1);assert.equal(p.values[0].unit,null);assert.equal((await event(x,p.id,'check')).status,409);await event(x,p.id,'submit',x.f);assert.equal((await event(x,p.id,'check',x.m)).status,403);assert.equal((await event(x,p.id,'check',x.f)).status,403);assert.equal((await event(x,p.id,'check')).status,201);assert.equal(parameterRecord(x.db,p.id).status,'checked');verify(x);});
test('unchecked handover blocks start in server and native guards, checked first start freezes exact original version',async t=>{const x=await setup(t);await process(x,'receive',{},x.m);const r=await save(x);assert.equal((await process(x,'start')).body.error.code,'PARAMETER_REVIEW_REQUIRED');assert.throws(()=>insertProcessingEvent(x.db,x.j.id,{action:'start',position:1,quantity:1,reason:'虚构'},'professional'),/parameter review required/);await event(x,r.body.parameter.id,'submit',x.f);await event(x,r.body.parameter.id,'check');assert.equal((await process(x,'start')).status,201);assert.equal(parameterContext(x.db,x.j.id).fixed_version_id,r.body.parameter.id);assert.equal((await process(x,'complete')).status,201);assert.equal((await qc(x)).status,201);verify(x);});
test('new parameter version pauses outstanding execution until explicit review; hold and continuation preserve old batch and independent funds/stock',async t=>{const x=await setup(t),first=await checked(x);await process(x,'receive',{},x.m);await process(x,'start');const old=['payment_events','inventory_events','retail_order_versions'].map(n=>x.db.prepare('SELECT * FROM '+n).all()),next=await checked(x);assert.notEqual(first,next);assert.equal((await process(x,'complete')).body.error.code,'PARAMETER_REVIEW_REQUIRED');await review(x,'hold');assert.equal((await process(x,'complete')).status,409);assert.equal((await review(x,'continue_original',{},x.m)).status,403);await review(x);assert.equal((await process(x,'complete')).status,201);assert.equal(parameterContext(x.db,x.j.id).fixed_version_id,first);assert.equal((await qc(x)).status,201);['payment_events','inventory_events','retail_order_versions'].forEach((n,i)=>assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),old[i]));verify(x);});
test('a checked change after processing completion holds quality/signature actions until original-version decision is recorded',async t=>{const x=await setup(t);await checked(x);await process(x,'receive',{},x.m);await process(x,'start');await process(x,'complete');await checked(x);assert.equal((await qc(x)).body.error.code,'PARAMETER_REVIEW_REQUIRED');await review(x);assert.equal((await qc(x)).status,201);await checked(x);const pass=fulfillmentRecord(x.db,x.j.id).history[0];assert.equal((await qc(x,'deliver',{checks:undefined,source_id:pass.id,receiver_name:'虚构领取人',receipt_note:'明确签收',handed_at:new Date().toISOString()},x.f)).body.error.code,'PARAMETER_REVIEW_REQUIRED');await review(x);assert.equal((await qc(x,'deliver',{checks:undefined,source_id:pass.id,receiver_name:'虚构领取人',receipt_note:'明确签收',handed_at:new Date().toISOString()},x.f)).status,201);verify(x);});
test('unregistered earlier start remains unknown when parameters are later entered; continuation never rewrites history',async t=>{const x=await setup(t);await process(x,'receive',{},x.m);await process(x,'start');const before=x.db.prepare('SELECT * FROM parameter_execution_refs').all();await checked(x);assert.equal(parameterContext(x.db,x.j.id).fixed_version_id,null);assert.equal((await process(x,'complete')).status,409);await review(x);assert.equal((await process(x,'complete')).status,201);assert.deepEqual(x.db.prepare('SELECT * FROM parameter_execution_refs WHERE event_id=?').get(before[0].event_id),before[0]);verify(x);});
test('return and resubmit retain immutable values; new saved versions refuse stale technical review',async t=>{const x=await setup(t),p=(await save(x)).body.parameter;await event(x,p.id,'submit',x.f);await event(x,p.id,'return');assert.equal(parameterRecord(x.db,p.id).status,'returned');await event(x,p.id,'submit',x.f);const q=(await save(x)).body.parameter;assert.equal((await event(x,p.id,'check')).body.error.code,'PARAMETER_CONFLICT');assert.equal(q.version,2);assert.deepEqual(parameterRecord(x.db,p.id).values,p.values);verify(x);});
test('strict values and physical row/customer source reject fabricated professional fields and cross-order evidence',async t=>{const x=await setup(t);for(const extra of [{source:'diagnosed'},{values:[]},{values:[{position:1,label:'虚构',value:0,unit:null,condition:null}]},{values:[{position:2,label:'虚构',value:'A',unit:null,condition:null}]},{values:[{position:1,label:'虚构',value:'A',unit:null,condition:null},{position:1,label:'虚构',value:'B',unit:null,condition:null}]},{document_version_ids:['missing']},{attachment_ids:['missing']},{prescription_approved:true}])assert.ok([422,409].includes((await save(x,extra)).status),JSON.stringify(extra));verify(x);});
test('current original-order and parameter leases reject simultaneous different inputs; identical retry adds one version',async t=>{const x=await setup(t),data=input(x),path='/api/retail/orders/'+x.o.id+'/parameters',opts={...x.f,method:'POST',data,key:'parameter-same-intent'};const a=await x.request(path,opts),b=await x.request(path,opts);assert.equal(a.status,201);assert.deepEqual(b.body,a.body);assert.equal((await x.request(path,{...opts,data:{...data,note:'changed'}})).status,409);const current=input(x);const pair=await Promise.all([x.request(path,{...x.f,method:'POST',data:current}),x.request(path,{...x.f,method:'POST',data:{...current,note:'different'}})]);assert.deepEqual(pair.map(x=>x.status).sort(),[201,409]);verify(x);});
test('processing and quality lease includes parameter/review versions rather than silently adopting a later decision',async t=>{const x=await setup(t);await checked(x);await process(x,'receive',{},x.m);const c=parameterContext(x.db,x.j.id);await checked(x);assert.equal((await process(x,'start',{expected_parameter_sequence:c.sequence})).body.error.code,'PARAMETER_CONFLICT');await process(x,'start');await checked(x);await review(x);const before=parameterContext(x.db,x.j.id);await review(x,'hold');assert.equal((await process(x,'complete',{expected_parameter_review_revision:before.review_revision})).body.error.code,'PARAMETER_CONFLICT');verify(x);});
test('audit failure rolls saved source, technical check and review back and same-intent retry preserves source',async t=>{const x=await setup(t);x.db.exec("CREATE TRIGGER bad_parameter_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'parameters.%' BEGIN SELECT RAISE(ABORT,'audit unavailable');END");assert.equal((await save(x)).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM parameter_versions').get().n,0);x.db.exec('DROP TRIGGER bad_parameter_audit');await checked(x);await process(x,'receive',{},x.m);await process(x,'start');await checked(x);x.db.exec("CREATE TRIGGER bad_parameter_audit BEFORE INSERT ON audit_events WHEN NEW.action='parameters.review' BEGIN SELECT RAISE(ABORT,'audit unavailable');END");assert.equal((await review(x)).status,500);assert.equal(parameterContext(x.db,x.j.id).review_revision,0);x.db.exec('DROP TRIGGER bad_parameter_audit');assert.equal((await review(x)).status,201);verify(x);});
test('native append-only and technical role guards protect values, documents, decisions and execution references',async t=>{const x=await setup(t),id=await checked(x);assert.throws(()=>x.db.exec("UPDATE parameter_versions SET source_note='changed'"),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM parameter_events'),/immutable/);await process(x,'receive',{},x.m);await process(x,'start');await checked(x);assert.throws(()=>insertParameterReview(x.db,x.j.id,{outcome:'continue_original',note:'虚构',reason:'虚构'},'manager'),/actor invalid/);assert.throws(()=>x.db.exec('DELETE FROM parameter_execution_refs'),/immutable/);verify(x);});
test('local roles, guardian and pending revoked session never create or expose parameter sources',async t=>{const x=await setup(t),parent=await x.login('parent'),other=await x.login('other');assert.equal((await x.request('/api/parameters',parent)).status,403);assert.equal((await x.request('/api/retail/orders/'+x.o.id+'/parameters',other)).status,404);const data=JSON.stringify(input(x)),u=new URL(x.origin);const r=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path:'/api/retail/orders/'+x.o.id+'/parameters',method:'POST',headers:{Cookie:x.f.cookie,'X-CSRF-Token':x.f.csrf,'Idempotency-Key':'parameter-pending-session','Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{x.db.prepare("DELETE FROM sessions WHERE user_id='front'").run();req.end(data.slice(10));},20);});assert.equal(r,401);assert.equal(parameterSequence(x.db,x.o.id),0);});
test('global and historic parameter paging, total counts and customer timeline preserve original order versions',async t=>{const x=await setup(t);for(let i=0;i<3;i++)await checked(x);const a=(await x.request('/api/retail/orders/'+x.o.id+'/parameters?limit=2',x.pro)).body;assert.equal(a.total,3);assert.equal(a.next_offset,2);const p=(await x.request('/api/parameters/versions/'+a.latest.id+'?limit=1',x.pro)).body.parameter;assert.equal(p.total,3);assert.equal(p.next_offset,1);assert.equal((await x.request('/api/parameters?status=checked',x.pro)).body.total,1);const tl=(await x.request('/api/customers/one/timeline?kind=parameter',x.pro)).body;assert.equal(tl.items.length,9);assert.ok(tl.items.every(e=>e.entity_id===x.o.id&&e.details.order_version===1));for(const q of ['limit=0','limit=101','offset=-1','status=approved'])assert.equal((await x.request('/api/parameters?'+q,x.pro)).status,422);verify(x);});
test('backup and independent restore replay captured execution and review; removed cross-reference fails verification',async t=>{const x=await setup(t,{persist:true});await checked(x);await process(x,'receive',{},x.m);await process(x,'start');await checked(x);await review(x);await process(x,'complete');await qc(x);const b=await createBackup(x.path,join(x.dir,'backup')),r=await restoreBackup(b.backup,join(x.dir,'restored')),copy=openDatabase(r.database);try{for(const n of ['parameter_versions','parameter_events','parameter_reviews','parameter_execution_refs'])assert.deepEqual(copy.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());verifyParameters(copy);}finally{copy.close();}const sql=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='parameter_execution_refs_no_delete'").get().sql;x.db.exec('DROP TRIGGER parameter_execution_refs_no_delete;DELETE FROM parameter_execution_refs');x.db.exec(sql);await assert.rejects(()=>createBackup(x.path,join(x.dir,'bad')),/参数/);});

async function demoFixture(t){const dir=mkdtempSync(join(tmpdir(),'optical-parameter-demo-')),db=openDatabase(join(dir,'source.sqlite'));db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment','seedDemoAftercare','seedDemoAftercareWork','seedDemoReplacements','seedDemoDispositions','seedDemoRefunds'])demo[fn](db);t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});return {db,dir,path:join(dir,'source.sqlite')};}
test('demo adds draft/checked hold/explicit old-source continuation once with every earlier business ledger unchanged',async t=>{const x=await demoFixture(t),names=['processing_events','fulfillment_events','payment_events','refund_events','inventory_events','aftercare_events','aftercare_work_events','aftercare_disposition_events','parameter_execution_refs'],old=names.map(n=>x.db.prepare('SELECT * FROM '+n).all());assert.deepEqual(demo.seedDemoParameters(x.db),{versions:3,events:7,reviews:2});assert.equal(parameterRecord(x.db,'demo-parameter-draft').status,'draft');assert.equal(parameterContext(x.db,'demo-processing-parallel').blocked,true);assert.equal(parameterContext(x.db,'demo-processing-split').blocked,false);assert.equal(parameterContext(x.db,'demo-processing-split').fixed_version_id,null);assert.deepEqual(demo.seedDemoParameters(x.db),{versions:0,events:0,reviews:0});names.forEach((n,i)=>assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),old[i]));verifyParameters(x.db);});
test('nonempty schema22 upgrade preserves all original rows and explicitly marks old processing/quality sources unknown',async()=>{const dir=mkdtempSync(join(tmpdir(),'optical-parameter-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);try{db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&x<'023').sort()){db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(f,new Date().toISOString());}db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment','seedDemoAftercare','seedDemoAftercareWork','seedDemoReplacements','seedDemoDispositions','seedDemoRefunds'])demo[fn](db);const names=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='schema_migrations' ORDER BY name").all().map(x=>x.name),old=names.map(n=>db.prepare('SELECT * FROM '+n).all());db.close();db=openDatabase(path);names.forEach((n,i)=>assert.deepEqual(db.prepare('SELECT * FROM '+n).all(),old[i]));assert.equal(db.prepare('SELECT count(*) n FROM parameter_versions').get().n,0);assert.equal(db.prepare("SELECT count(*) n FROM parameter_execution_refs WHERE basis<>'legacy' OR fixed_version_id IS NOT NULL OR current_version_id IS NOT NULL").get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM parameter_execution_refs').get().n,40);verifyParameters(db);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
test('fixed document and active attachment references survive later edits; revoked evidence prevents technical check',async t=>{const x=await setup(t),upload=await fetch(x.origin+'/api/customers/one/attachments',{method:'POST',headers:{Cookie:x.f.cookie,'X-CSRF-Token':x.f.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'text/plain','X-File-Name':encodeURIComponent('虚构来源.txt')},body:'synthetic source'}),a=(await upload.json()).attachment;assert.ok(a);const r=await x.request('/api/customers/one/documents',{...x.f,method:'POST',data:{title:'虚构来源记录',content:'明确资料',source:'external',attachment_ids:[]}});assert.equal(r.status,201,JSON.stringify(r.body));const id=r.body.document.id,p=(await save(x,{document_version_ids:[id],attachment_ids:[a.id]})).body.parameter;await event(x,p.id,'submit',x.f);assert.equal((await x.request('/api/documents/'+r.body.document.record_id+'/versions',{...x.f,method:'POST',data:{expected_version:1,title:'后续资料 V2（虚构）',content:'后来的资料内容',source:'external',revision_reason:'保留旧引用',attachment_ids:[]}})).status,201);await x.request('/api/attachments/'+a.id+'/revoke',{...x.f,method:'POST',data:{reason:'明确撤销'}});assert.equal((await event(x,p.id,'check')).body.error.code,'PARAMETER_SOURCE');assert.equal(parameterRecord(x.db,p.id).document_version_ids[0],id);verify(x);});
test('execution audit failure rolls new parameter reference and work count back together',async t=>{const x=await setup(t);await checked(x);await process(x,'receive',{},x.m);x.db.exec("CREATE TRIGGER bad_work_audit BEFORE INSERT ON audit_events WHEN NEW.action='processing.start' BEGIN SELECT RAISE(ABORT,'audit unavailable');END");assert.equal((await process(x,'start')).status,500);assert.equal(parameterContext(x.db,x.j.id).has_started,false);assert.equal(x.db.prepare('SELECT count(*) n FROM parameter_execution_refs').get().n,0);x.db.exec('DROP TRIGGER bad_work_audit');assert.equal((await process(x,'start')).status,201);verify(x);});
test('disabled or first-password technical reviewers cannot manufacture a checked handover or change decision',async t=>{const x=await setup(t),id=(await save(x)).body.parameter.id;await event(x,id,'submit',x.f);x.db.prepare('INSERT INTO user_security VALUES (?,1,1)').run('professional');assert.equal((await event(x,id,'check')).status,403);assert.throws(()=>insertParameterEvent(x.db,id,{action:'check',note:'虚构',reason:'虚构'},'professional'),/actor invalid/);x.db.prepare('UPDATE user_security SET must_change_password=0 WHERE user_id=?').run('professional');x.db.prepare('UPDATE users SET active=0 WHERE id=?').run('professional');assert.throws(()=>insertParameterEvent(x.db,id,{action:'check',note:'虚构',reason:'虚构'},'professional'),/actor invalid/);verify(x);});
test('historic checked parameter remains bound to original order version after explicit unexecuted order revision',async t=>{const x=await setup(t),id=await checked(x);const p=processingRecord(x.db,x.j.id);insertProcessingEvent(x.db,x.j.id,{action:'cancel',reason:'明确未执行计划取消'},'manager');const r=await revise(x.request,x.m,x.o,{notes:'原商品新版本（虚构）'});assert.equal(r.status,201,JSON.stringify(r.body));x.o=r.body.order;assert.equal(x.o.version,2);assert.equal(parameterRecord(x.db,id).order_version,1);const next=await checked(x);assert.equal(parameterRecord(x.db,next).order_version,2);verify(x);});
test('recovery refuses an older continuation reference after a newer explicit hold and continuation',async t=>{const x=await setup(t);await checked(x);await process(x,'receive',{},x.m);await process(x,'start');await checked(x);await review(x);const old=parameterContext(x.db,x.j.id).review_id;await review(x,'hold');await review(x);await process(x,'complete');verify(x);const trigger=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='parameter_execution_refs_no_update'").get().sql;x.db.exec('DROP TRIGGER parameter_execution_refs_no_update');x.db.prepare("UPDATE parameter_execution_refs SET review_id=? WHERE processing_event_id=(SELECT id FROM processing_events WHERE job_id=? AND action='complete')").run(old,x.j.id);x.db.exec(trigger);assert.throws(()=>verifyParameters(x.db),/最新引用/);});
test('same-millisecond interleaving replays by captured revisions without retroactively assigning later parameters',async t=>{const x=await setup(t),now=new Date(Date.now()+1000).toISOString();insertProcessingEvent(x.db,x.j.id,{action:'receive',position:1,quantity:1,reason:'同刻明确到货'},'manager',now);insertProcessingEvent(x.db,x.j.id,{action:'start',position:1,quantity:1,reason:'同刻明确开工'},'professional',now);const id=insertParameterVersion(x.db,x.o.id,input(x),'front',now).parameter.id;insertParameterEvent(x.db,id,{action:'submit',note:'同刻提交',reason:'明确来源'},'front',now);insertParameterEvent(x.db,id,{action:'check',note:'同刻核对',reason:'明确交接'},'professional',now);insertParameterReview(x.db,x.j.id,{outcome:'continue_original',note:'同刻原版继续',reason:'保留未知'},'professional',now);insertProcessingEvent(x.db,x.j.id,{action:'complete',position:1,quantity:1,reason:'同刻明确完成'},'professional',now);assert.equal(parameterContext(x.db,x.j.id).fixed_version_id,null);verify(x);});
