import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
import {paymentTables,orderPayments,verifyPayments,insertPayment} from '../src/payments.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
async function product(request,m,extra={}){const r=await request('/api/retail/products',{...m,method:'POST',data:{sku:'SKU-'+crypto.randomUUID().slice(0,8),name:'虚构镜架',category:'frame',brand:null,specification:'虚构型号',unit:'副',list_price_cents:19900,status:'active',reason:'虚构目录',...extra}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.product;}
async function order(request,m,items){const r=await request('/api/customers/one/retail-orders',{...m,method:'POST',data:{title:'库存订单（虚构）',notes:null,items:items.map(x=>({product_id:x.id,product_version:x.version,quantity:x.quantity||1,unit_price_cents:100,note:null})),reason:'虚构开单'}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.order;}
async function stock(request,m,p,action='receive',quantity=10,extra={},key=crypto.randomUUID()){const current=(await request('/api/inventory/products/'+p.id,m)).body;return request('/api/inventory/products/'+p.id+'/events',{...m,method:'POST',key,data:{expected_product_version:current.product?.version||p.version,expected_sequence:current.stock?.sequence||0,action,quantity,reason:'虚构库存操作',...extra}});}
async function inventory(request,m,id){const r=await request('/api/retail/orders/'+id+'/inventory',m);assert.equal(r.status,200);return r.body.inventory;}
function postReservation(request,m,state,action='reserve',extra={},key=crypto.randomUUID()){return request('/api/retail/orders/'+state.order_id+'/inventory/'+action,{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,reason:'虚构'+action,...(action==='reserve'?{stock_versions:state.stock_versions}:{}),...extra}});}
function revise(request,m,o,extra={}){return request('/api/retail/orders/'+o.id+'/versions',{...m,method:'POST',data:{expected_version:o.version,title:o.title,notes:'虚构修订说明',items:o.items.map(({product_id,product_version,quantity,unit_price_cents,note})=>({product_id,product_version,quantity,unit_price_cents,note})),document_version_ids:[],attachment_ids:[],reason:'虚构修订',...extra}});}

async function payments(request,m,id){const r=await request('/api/retail/orders/'+id+'/payments',m);assert.equal(r.status,200,JSON.stringify(r.body));return r.body.payments;}
async function receive(request,m,id,extra={},key=crypto.randomUUID()){const state=await payments(request,m,id);return request('/api/retail/orders/'+id+'/payments/receive',{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,amount_cents:33,method:'cash',reference:null,received_at:'2025-01-01T10:00:00.000Z',reason:'虚构实际收款登记',...extra}});}
async function voidReceipt(request,m,id,source,extra={},key=crypto.randomUUID()){const s=await payments(request,m,id);return request('/api/retail/orders/'+id+'/payments/void',{...m,method:'POST',key,data:{expected_order_version:s.order_version,expected_revision:s.revision,source_id:source,reason:'虚构未发生金额误登记，纠正记录',...extra}});}
test('payments manager/front manual records and manager corrections enforce role/store/family boundaries',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),f=await login('front'),p=await login('professional'),g=await login('parent'),b=await login('other'),item=await product(request,m),o=await order(request,m,[item]);for(const s of [m,f])assert.equal((await request('/api/payments',s)).status,200);for(const s of [p,g]){assert.equal((await request('/api/payments',s)).status,403);assert.equal((await request('/api/retail/orders/'+o.id+'/payments',s)).status,403);}assert.equal((await request('/api/retail/orders/'+o.id+'/payments',b)).status,404);assert.equal((await request('/api/payments',b)).body.total,0);const r=await receive(request,f,o.id);assert.equal(r.status,201);assert.equal((await voidReceipt(request,f,o.id,r.body.event.id)).status,403);assert.equal((await voidReceipt(request,m,o.id,r.body.event.id)).status,201);assert.equal((await request('/api/payments')).status,401);
});
test('installments use exact cents and fixed original basis, with signed comparison instead of an invented receivable',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);for(const amount of [33,34,33,1])assert.equal((await receive(request,m,o.id,{amount_cents:amount})).status,201);const s=await payments(request,m,o.id);assert.deepEqual([s.recorded_cents,s.comparison_cents,s.valid_receipts,s.revision,s.locked],[101,-1,4,4,true]);assert.ok(s.history.every(e=>e.order_version===1&&e.basis_total_cents===100&&e.currency==='CNY'));assert.equal(db.prepare('SELECT subtotal_cents FROM retail_order_versions WHERE order_id=?').get(o.id).subtotal_cents,100);verifyPayments(db);
});
test('valid receipts protect revision/cancellation; append-only false-entry void preserves originals and permits later version',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),r=await receive(request,m,o.id);assert.equal((await revise(request,m,o)).body.error.code,'ORDER_HAS_RECEIPTS');assert.equal((await request('/api/retail/orders/'+o.id+'/cancel',{...m,method:'POST',data:{expected_version:1,reason:'不能取消有实际收款的原单'}})).body.error.code,'ORDER_HAS_RECEIPTS');const v=await voidReceipt(request,m,o.id,r.body.event.id);assert.equal(v.status,201);assert.equal(v.body.event.amount_cents,r.body.event.amount_cents);assert.equal(v.body.event.received_at,r.body.event.received_at);assert.equal(v.body.payments.recorded_cents,0);assert.equal(v.body.payments.history[1].void_id,v.body.event.id);assert.equal((await voidReceipt(request,m,o.id,r.body.event.id)).body.error.code,'RECEIPT_VOIDED');assert.equal((await revise(request,m,o)).status,201);const next=await receive(request,m,o.id,{amount_cents:50});assert.equal(next.body.event.order_version,2);assert.equal(next.body.payments.history[2].order_version,1);verifyPayments(db);
});
test('void cannot target another order or a void event; client cannot fabricate copied amount or accounting fields',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m),a=await order(request,m,[p]),b=await order(request,m,[p]),r=await receive(request,m,a.id);assert.equal((await voidReceipt(request,m,b.id,r.body.event.id)).status,404);assert.equal((await voidReceipt(request,m,a.id,r.body.event.id,{amount_cents:1})).status,422);const v=await voidReceipt(request,m,a.id,r.body.event.id);assert.equal((await voidReceipt(request,m,a.id,v.body.event.id)).status,404);for(const extra of [{paid:true},{discount_cents:10},{balance:2},{refund:true},{basis_total_cents:99}])assert.equal((await receive(request,m,b.id,extra)).status,422);
});
test('validation rejects noninteger, negative, excessive, bad-date/future amounts, unknown channels and CSRF',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);for(const amount_cents of [0,-1,.1,1e12+1,'33'])assert.equal((await receive(request,m,o.id,{amount_cents})).status,422);for(const received_at of ['2025-02-30T10:00:00.000Z','2099-01-01T00:00:00.000Z','2025-01-01','1999-12-31T23:59:59.000Z'])assert.equal((await receive(request,m,o.id,{received_at})).status,422);assert.equal((await receive(request,m,o.id,{method:'wechat_callback'})).status,422);assert.equal((await receive(request,{...m,csrf:'wrong'},o.id)).status,403);assert.equal(db.prepare('SELECT count(*) n FROM payment_events').get().n,0);
});
test('same-key retry replays once, changed intent fails and competing installments require explicit current revision',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),input={expected_order_version:1,expected_revision:0,amount_cents:20,method:'cash',reference:null,received_at:'2025-01-01T00:00:00.000Z',reason:'虚构并发收款'},path='/api/retail/orders/'+o.id+'/payments/receive',key='same-payment-intent';const r=await request(path,{...m,method:'POST',data:input,key}),again=await request(path,{...m,method:'POST',data:input,key});assert.equal(r.status,201);assert.deepEqual(again.body,r.body);assert.equal((await request(path,{...m,method:'POST',data:{...input,amount_cents:21},key})).body.error.code,'IDEMPOTENCY_CONFLICT');input.expected_revision=1;const race=await Promise.all([request(path,{...m,method:'POST',data:input}),request(path,{...m,method:'POST',data:input})]);assert.deepEqual(race.map(x=>x.status).sort(),[201,409]);assert.equal(db.prepare('SELECT count(*) n FROM payment_events').get().n,2);verifyPayments(db);
});
test('external references prevent duplicate active receipts across orders and allow corrected re-entry after void',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m),a=await order(request,m,[p]),b=await order(request,m,[p]),r=await receive(request,m,a.id,{reference:'REF-01',method:'transfer'});assert.equal((await receive(request,m,b.id,{reference:'REF-01',method:'transfer'})).body.error.code,'DUPLICATE_REFERENCE');await voidReceipt(request,m,a.id,r.body.event.id);assert.equal((await receive(request,m,b.id,{reference:'REF-01',method:'transfer'})).status,201);assert.equal((await receive(request,m,a.id,{reference:'REF-01',method:'transfer'})).status,409);assert.equal((await receive(request,m,b.id,{reference:'REF-01',method:'card'})).status,201);
});
test('receipt/revision race yields one winner; cancelled orders reject collection and service orders permit manual records',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),race=await Promise.all([receive(request,m,o.id,{expected_order_version:1}),revise(request,m,o)]);assert.equal(race.filter(x=>x.status===201).length,1);const cancelled=await order(request,m,[p]);await request('/api/retail/orders/'+cancelled.id+'/cancel',{...m,method:'POST',data:{expected_version:1,reason:'虚构取消'}});assert.equal((await receive(request,m,cancelled.id)).body.error.code,'ORDER_CANCELLED');const service=await product(request,m,{category:'service',unit:'次'}),s=await order(request,m,[service]);assert.equal((await receive(request,m,s.id)).status,201);verifyPayments(db);
});
test('audit failure rolls receipt/void and idempotency together back; retry succeeds',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);db.exec("CREATE TRIGGER reject_payment_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'payments.%' BEGIN SELECT RAISE(ABORT,'audit failure'); END");assert.equal((await receive(request,m,o.id,{},'payment-audit-retry')).status,500);assert.equal(db.prepare('SELECT count(*) n FROM payment_events').get().n,0);db.exec('DROP TRIGGER reject_payment_audit');const r=await receive(request,m,o.id,{},'payment-audit-retry');assert.equal(r.status,201);db.exec("CREATE TRIGGER reject_payment_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'payments.%' BEGIN SELECT RAISE(ABORT,'audit failure'); END");assert.equal((await voidReceipt(request,m,o.id,r.body.event.id,{},'void-audit-retry')).status,500);assert.equal(hasValid(db,o.id),true);db.exec('DROP TRIGGER reject_payment_audit');assert.equal((await voidReceipt(request,m,o.id,r.body.event.id,{},'void-audit-retry')).status,201);
});
const hasValid=(db,id)=>orderPayments(db,id).locked;
test('database immutable guards block deletion, overwrite, wrong basis and occupied-order revision',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),r=await receive(request,m,o.id);for(const sql of ['DELETE FROM payment_events',"UPDATE payment_events SET amount_cents=1"])assert.throws(()=>db.exec(sql),/immutable/);assert.throws(()=>insertPayment(db,o.id,'void',{source_id:r.body.event.id,reason:'未授权岗位作废'},'front'),/actor/);const v=db.prepare('SELECT * FROM retail_order_versions WHERE order_id=?').get(o.id),values=Object.values(v);values[1]=2;assert.throws(()=>db.prepare('INSERT INTO retail_order_versions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...values),/receipts lock/);const e=Object.values(r.body.event);e[0]=crypto.randomUUID();e[5]=2;e[9]=101;assert.throws(()=>db.prepare('INSERT INTO payment_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...e),/original order/);
});
test('complete event counts/history paging exceed one hundred without aggregating a financial report',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);for(let i=0;i<105;i++)insertPayment(db,o.id,'receive',{amount_cents:1,method:'cash',reference:null,received_at:'2025-01-01T00:00:00.000Z',reason:'虚构分页'},'manager');const a=(await request('/api/payments?limit=100',m)).body,b=(await request('/api/payments?limit=100&offset='+a.next_offset,m)).body;assert.equal(a.total,105);assert.equal(a.items.length,100);assert.equal(b.items.length,5);assert.equal(new Set([...a.items,...b.items].map(e=>e.id)).size,105);const state=(await request('/api/retail/orders/'+o.id+'/payments?limit=100',m)).body.payments;assert.equal(state.total,105);assert.equal(state.recorded_cents,105);assert.equal(state.history.length,100);assert.equal((await request('/api/payments?q=%25',m)).body.total,0);for(const query of ['limit=0','limit=101','offset=-1','action=refund'])assert.equal((await request('/api/payments?'+query,m)).status,422);
});
test('timeline fixed versions and same-time paging project saved receipts and hide money from unauthorized roles',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),f=await login('professional'),p=await product(request,m),o=await order(request,m,[p]),now=new Date().toISOString();for(let i=0;i<3;i++)insertPayment(db,o.id,'receive',{amount_cents:i+1,method:'cash',reference:null,received_at:now,reason:'虚构同刻事件'},'manager',now);let cursor='',events=[];do{const r=await request('/api/customers/one/timeline?kind=payment&limit=1'+(cursor?'&cursor='+cursor:''),m);assert.equal(r.status,200);events.push(...r.body.items);cursor=r.body.next_cursor;}while(cursor);assert.deepEqual(events.map(e=>e.details.revision),[3,2,1]);assert.ok(events.every(e=>e.entity_id===o.id&&e.details.order_version===1));assert.equal((await request('/api/customers/one/timeline?kind=payment',f)).status,403);assert.ok(!(await request('/api/customers/one/timeline?limit=50',f)).body.items.some(e=>e.kind==='payment'));
});
test('backup/restore retain original receipts and corrections with sessions revoked',async t=>{
 const {request,login,db,path,dir}=await fixture(t,{persist:true}),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),r=await receive(request,m,o.id);await voidReceipt(request,m,o.id,r.body.event.id);await receive(request,m,o.id,{amount_cents:75});const before=orderPayments(db,o.id),backup=await createBackup(path,join(dir,'backup')),restored=await restoreBackup(backup.backup,join(dir,'restore')),copy=openDatabase(restored.database);try{assert.deepEqual(copy.prepare('SELECT * FROM payment_events').all(),db.prepare('SELECT * FROM payment_events').all());assert.deepEqual(orderPayments(copy,o.id),before);assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyPayments(copy);}finally{copy.close();}
});
test('recovery rejects corrupted source amounts after protection triggers are reinstated',async t=>{
 const {request,login,db,path,dir}=await fixture(t,{persist:true}),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),r=await receive(request,m,o.id);await voidReceipt(request,m,o.id,r.body.event.id);const sql=db.prepare("SELECT sql FROM sqlite_schema WHERE name='payment_no_update'").get().sql;db.exec('DROP TRIGGER payment_no_update');db.prepare('UPDATE payment_events SET amount_cents=amount_cents+1 WHERE id=?').run(r.body.event.id);db.exec(sql);assert.throws(()=>verifyPayments(db),/作废来源/);await assert.rejects(()=>createBackup(path,join(dir,'bad-backup')),/核对/);
});
test('nonempty V0.17 upgrade preserves original tables without inventing receipts',()=>{
 const dir=mkdtempSync(join(tmpdir(),'optical-payment-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);try{db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&x<'015').sort()){db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(file,new Date().toISOString());}db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only'),'manager','store-a');demo.seedDemoScenarios(db);demo.seedDemoRetail(db);demo.seedDemoInventory(db);const tables=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations' ORDER BY name").all().map(x=>x.name),before=Object.fromEntries(tables.map(t=>[t,db.prepare('SELECT * FROM '+t).all()]));db.close();db=openDatabase(path);for(const table of tables)assert.deepEqual(db.prepare('SELECT * FROM '+table).all(),before[table]);assert.equal(db.prepare('SELECT count(*) n FROM payment_events').get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,39);}finally{db.close();rmSync(dir,{recursive:true,force:true});}
});
test('synthetic installments and error correction preserve later hand-entered records on repeat seed',()=>{
 const db=openDatabase(':memory:');try{db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only'),role,'store-a');demo.seedDemoScenarios(db);demo.seedDemoRetail(db);demo.seedDemoInventory(db);assert.deepEqual(demo.seedDemoPayments(db),{records:5});assert.deepEqual([orderPayments(db,'demo-order-revised').recorded_cents,orderPayments(db,'demo-order-draft').recorded_cents],[260000,30000]);insertPayment(db,'demo-order-draft','receive',{amount_cents:20,method:'cash',reference:null,received_at:'2025-01-01T00:00:00.000Z',reason:'手工追加虚构记录'},'demo-manager');const before=db.prepare('SELECT * FROM payment_events').all();assert.deepEqual(demo.seedDemoPayments(db),{records:0});assert.deepEqual(db.prepare('SELECT * FROM payment_events').all(),before);verifyPayments(db);}finally{db.close();}
});

test('pending receipt body rechecks session revocation and initial-password gate without writing',async t=>{
 const {request,login,db,origin}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]),data=JSON.stringify({expected_order_version:1,expected_revision:0,amount_cents:10,method:'cash',reference:null,received_at:'2025-01-01T00:00:00.000Z',reason:'虚构等待请求'}),u=new URL(origin),response=new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path:'/api/retail/orders/'+o.id+'/payments/receive',method:'POST',headers:{Cookie:m.cookie,'X-CSRF-Token':m.csrf,'Idempotency-Key':'pending-payment-body','Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{let value='';r.on('data',x=>value+=x);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(value)}));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{db.prepare('DELETE FROM sessions WHERE user_id=?').run('manager');req.end(data.slice(10));},30);});assert.equal((await response).status,401);assert.equal(db.prepare('SELECT count(*) n FROM payment_events').get().n,0);const next=await login('manager');db.prepare('INSERT INTO user_security (user_id,must_change_password) VALUES (?,1)').run('manager');assert.equal((await request('/api/payments',next)).body.error.code,'PASSWORD_CHANGE_REQUIRED');
});
test('stock release never unlocks an order with valid receipts; erroneous void does not release stock',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,[p]);await stock(request,m,p);const reserved=await postReservation(request,m,await inventory(request,m,o.id)),r=await receive(request,m,o.id);await postReservation(request,m,reserved.body.inventory,'release');assert.equal((await revise(request,m,o)).body.error.code,'ORDER_HAS_RECEIPTS');const newReserve=await postReservation(request,m,await inventory(request,m,o.id));assert.equal(newReserve.status,201);await voidReceipt(request,m,o.id,r.body.event.id);assert.equal((await revise(request,m,o)).body.error.code,'ORDER_RESERVED');assert.equal(stockBalance(db,p.id).reserved,1);verifyPayments(db);verifyInventory(db);
});

test('competing different orders cannot record the same external receipt twice',async t=>{const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),a=await order(request,m,[p]),b=await order(request,m,[p]),race=await Promise.all([receive(request,m,a.id,{reference:'RACE-EXTERNAL',method:'transfer'}),receive(request,m,b.id,{reference:'RACE-EXTERNAL',method:'transfer'})]);assert.deepEqual(race.map(r=>r.status).sort(),[201,409]);assert.equal(db.prepare('SELECT count(*) n FROM payment_events').get().n,1);verifyPayments(db);});
