import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import {verifyProcurement} from '../src/procurement-recovery.mjs';
const now=()=>new Date().toISOString(),notes=()=>({note:'仅虚构实际来源',reason:'明确来源核对',next_step:'等待实际下一办理'}),si=(x={})=>({code:'DEMO-'+crypto.randomUUID().slice(0,8),name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构供应范围，真实资质待核验',settlement_note:null,source_note:'人工明确虚构目录来源',source_reference:'DEMO-DIRECTORY',status:'active',reason:'虚构来源',...x});
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-GOODS',name:'虚构采购镜片',category:'lens',brand:null,specification:'实际规格说明，不是处方',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201,JSON.stringify(z.body));x.product=z.body.product;return x;}
const sequence=x=>P.procurementSequence(x.db,'a');
async function supplier(x,i=si(),who=x.m){return x.request('/api/suppliers',{...who,method:'POST',data:{expected_sequence:sequence(x),...i}});}
async function readySupplier(x){const z=await supplier(x);assert.equal(z.status,201,JSON.stringify(z.body));x.supplier=z.body.record;return x.supplier;}
const purchaseInput=(x,e={})=>({supplier_id:x.supplier.id,supplier_version:x.supplier.current_version,title:'明确采购需求（虚构）',purpose_note:'实际采购用途，不推定销售',source_note:'人工明确商品和价格来源',source_reference:'DEMO-ACTUAL-PURCHASE',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:2,unit_price_cents:101,note:null}],...notes(),...e});
async function purchase(x,e={},who=x.f,key){return x.request('/api/purchases',{...who,method:'POST',key,data:{expected_sequence:sequence(x),...purchaseInput(x,e)}});}
async function readyPurchase(x,e={}){if(!x.supplier)await readySupplier(x);const z=await purchase(x,e);assert.equal(z.status,201,JSON.stringify(z.body));x.purchase=z.body.record;return x.purchase;}
async function action(x,a,extra={},who=['approve','reject'].includes(a)?x.m:x.f,key){const r=P.purchaseRecord(x.db,x.purchase.id);return x.request('/api/purchases/'+r.id+'/events',{...who,method:'POST',key,data:{expected_sequence:sequence(x),expected_revision:r.revision,expected_version:r.current_version,action:a,decision_basis:'本次明确原版本决定（虚构）',...notes(),...(a==='order'?{ordered_at:now(),order_reference:'DEMO-ORDER-'+r.id}:{}),...extra}});}
async function revise(x,e={}){const r=P.purchaseRecord(x.db,x.purchase.id);return x.request('/api/purchases/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:sequence(x),expected_revision:r.revision,expected_version:r.current_version,...purchaseInput(x,e)}});}
async function changeSupplier(x,extra={}){const r=P.supplierRecord(x.db,x.supplier.id),i=si({...r,...extra});delete i.code;for(const k of ['id','supplier_id','store_id','version','sequence','created_at','created_by','current_version','history','total','next_offset'])delete i[k];return x.request('/api/suppliers/'+r.id+'/versions',{...x.m,method:'POST',data:{expected_sequence:sequence(x),expected_version:r.current_version,...i}});}
test('supplier sources preserve unknown contacts and only manager maintains immutable directory versions',async t=>{const x=await setup(t);assert.equal((await supplier(x,si(),x.f)).status,403);await readySupplier(x);assert.equal(x.supplier.contact_method,null);assert.equal((await changeSupplier(x,{name:'虚构供应商资料更正'})).status,201);assert.equal(P.supplierRecord(x.db,x.supplier.id,{version:1}).name,'虚构供应商');assert.equal((await x.request('/api/suppliers/'+x.supplier.id,x.o)).status,404);assert.equal((await x.request('/api/suppliers',x.g)).status,403);verifyProcurement(x.db);});
test('explicit purchase quantities and prices use exact cents without creating inventory or finance facts',async t=>{const x=await setup(t);await readyPurchase(x);assert.equal(x.purchase.total_cents,202);assert.equal(x.purchase.currency,'CNY');assert.equal(x.purchase.expected_date,null);for(const n of ['inventory_events','payment_events','refund_events'])assert.equal(x.db.prepare('SELECT count(*) n FROM '+n).get().n,0);assert.equal((await purchase(x,{items:[{product_id:x.product.id,product_version:1,quantity:999,unit_price_cents:1000000000,note:null}]})).status,201);assert.equal((await purchase(x,{items:Array.from({length:2},()=>({product_id:x.product.id,product_version:1,quantity:999,unit_price_cents:1000000000,note:null}))})).status,422);verifyProcurement(x.db);});
test('submission, commercial approval and actual order are separate and require current local roles',async t=>{const x=await setup(t);await readyPurchase(x);assert.equal((await action(x,'approve')).status,409);assert.equal((await action(x,'submit')).status,201);assert.equal((await action(x,'approve',{},x.f)).status,403);assert.equal((await action(x,'approve')).status,201);assert.equal(P.purchaseRecord(x.db,x.purchase.id).current.order_reference,null);assert.equal((await action(x,'order')).status,201);assert.equal(P.purchaseRecord(x.db,x.purchase.id).status,'ordered');assert.equal((await action(x,'cancel')).status,409);assert.equal((await action(x,'reopen')).status,409);verifyProcurement(x.db);});
test('source change holds approval and order until an explicit reopen and new fixed request version',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'approve');await changeSupplier(x,{name:'新明确来源版本'});assert.equal((await action(x,'order')).status,409);assert.equal((await revise(x)).status,409);assert.equal((await action(x,'reopen')).status,201);x.supplier=P.supplierRecord(x.db,x.supplier.id);assert.equal((await revise(x)).status,201);await action(x,'submit');await action(x,'approve');await action(x,'order');assert.equal(P.purchaseRecord(x.db,x.purchase.id,{version:1}).supplier.name,'虚构供应商');verifyProcurement(x.db);});
test('supplier disable blocks a cached actual-order replay while the original order remains historical',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'approve');const r=P.purchaseRecord(x.db,x.purchase.id),path='/api/purchases/'+r.id+'/events',data={expected_sequence:sequence(x),expected_revision:r.revision,expected_version:1,action:'order',decision_basis:'实际订货来源',ordered_at:now(),order_reference:'DEMO-CACHED-ORDER',...notes()},key='actual-order-key';assert.equal((await x.request(path,{...x.f,method:'POST',data,key})).status,201);assert.equal((await x.request(path,{...x.f,method:'POST',data,key})).status,201);await changeSupplier(x,{status:'inactive'});assert.equal((await x.request(path,{...x.f,method:'POST',data,key})).status,409);assert.equal(P.purchaseRecord(x.db,r.id).revision,4);verifyProcurement(x.db);});
test('duplicate supplier order references reject the second actual order and do not record receipt or stock',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'approve');assert.equal((await action(x,'order',{order_reference:'FIXED-ACTUAL-REF'})).status,201);await readyPurchase(x);await action(x,'submit');await action(x,'approve');assert.equal((await action(x,'order',{order_reference:'FIXED-ACTUAL-REF'})).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_events').get().n,0);verifyProcurement(x.db);});
test('native source and actor guards reject commercial approval by reception and future actual order times',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');assert.throws(()=>P.purchaseEvent(x.db,x.purchase.id,{action:'approve',decision_basis:'明确决定',...notes()},'front'),/approver/);await action(x,'approve');assert.throws(()=>P.purchaseEvent(x.db,x.purchase.id,{action:'order',ordered_at:new Date(Date.now()+60000).toISOString(),order_reference:'FUTURE',decision_basis:'实际来源',...notes()},'front'),/time/);verifyProcurement(x.db);});
test('audit and direct root/version failures roll back source, event and sequence together',async t=>{const x=await setup(t);await readySupplier(x);x.db.exec("CREATE TRIGGER procurement_audit_failure BEFORE INSERT ON audit_events WHEN NEW.action='procurement.version' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END");assert.equal((await purchase(x)).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_requests').get().n,0);x.db.exec('DROP TRIGGER procurement_audit_failure');assert.throws(()=>P.createPurchase(x.db,'a',{...purchaseInput(x),note:''},'front'),/source/);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_requests').get().n,0);assert.equal((await purchase(x)).status,201);verifyProcurement(x.db);});
test('all five purchase and supplier tables restore independently after later supplier revisions',async t=>{const x=await setup(t,{persist:true});await readyPurchase(x);await action(x,'submit');await action(x,'approve');await action(x,'order');await changeSupplier(x,{status:'inactive'});verifyProcurement(x.db);const b=await createBackup(x.path,join(x.dir,'backup')),rr=await restoreBackup(b.backup,join(x.dir,'restore')),d=openDatabase(rr.database);for(const n of P.procurementTables)assert.deepEqual(d.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());verifyProcurement(d);d.close();});
import {insertProductVersion} from '../src/retail.mjs';
import {seedDemoProcurement} from '../src/demo-procurement.mjs';
function tamper(db,t,sql,args=[]){const name=t+'_no_update',saved=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(name).sql;db.exec('DROP TRIGGER '+name);db.prepare(sql).run(...args);db.exec(saved);}
test('services and foreign-store goods cannot be purchased through either API or native records',async t=>{const x=await setup(t);await readySupplier(x);const service=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-SERVICE',name:'虚构服务',category:'service',brand:null,specification:'非实物',unit:'次',list_price_cents:100,status:'active',reason:'虚构'}});for(const id of [service.body.product.id,'foreign-missing-product'])assert.equal((await purchase(x,{items:[{product_id:id,product_version:1,quantity:1,unit_price_cents:100,note:null}]})).status,409);assert.throws(()=>P.createPurchase(x.db,'a',purchaseInput(x,{items:[{product_id:service.body.product.id,product_version:1,quantity:1,unit_price_cents:100,note:null}]}),'front'),/product/);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_requests').get().n,0);verifyProcurement(x.db);});
test('unsupported assumptions, incomplete prices and invalid dates do not create partial requests',async t=>{const x=await setup(t);await readySupplier(x);for(const e of [{default_discount:20},{expected_date:'2026-02-30'},{items:[{product_id:x.product.id,product_version:1,quantity:1.5,unit_price_cents:100,note:null}]},{items:[{product_id:x.product.id,product_version:1,quantity:1,unit_price_cents:-1,note:null}]},{items:[{product_id:x.product.id,product_version:1,quantity:1,note:null}]}])assert.equal((await purchase(x,e)).status,422);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_requests').get().n,0);verifyProcurement(x.db);});
test('rejected source stays fixed until explicit reopening; actual ordering cannot predate approval',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'reject');assert.equal((await revise(x,{title:'不能直接改已驳回原需求'})).status,409);await action(x,'reopen');assert.equal((await revise(x,{title:'明确新需求版本'})).status,201);await action(x,'submit');await action(x,'approve');assert.equal((await action(x,'order',{ordered_at:'2020-01-01T00:00:00.000Z'})).status,409);assert.equal((await action(x,'order',{ordered_at:new Date(Date.now()+60000).toISOString()})).status,422);verifyProcurement(x.db);});
test('product source changes hold future positive actions without replacing old quantities, units or commercial opinions',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'approve');const p=x.db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? AND version=1').get(x.product.id);insertProductVersion(x.db,x.product.id,{...p,name:'后来新商品资料',list_price_cents:999,reason:'实际目录更正'},'manager');assert.equal((await action(x,'order')).status,409);assert.equal(P.purchaseRecord(x.db,x.purchase.id).items[0].name,'虚构采购镜片');assert.equal(P.purchaseRecord(x.db,x.purchase.id).items[0].unit_price_cents,101);verifyProcurement(x.db);});
test('bounded supplier and request pages preserve totals and reject changed continuation sequences',async t=>{const x=await setup(t);await readySupplier(x);for(let n=0;n<31;n++)await readyPurchase(x,{title:'明确原采购 '+n});const z=await x.request('/api/purchases?limit=30',x.f);assert.equal(z.body.total,31);assert.equal(z.body.items.length,30);assert.equal((await x.request('/api/purchases?offset=30',x.f)).status,409);assert.equal((await x.request('/api/purchases?offset=30&expected_sequence='+z.body.sequence,x.f)).body.items.length,1);await readyPurchase(x);assert.equal((await x.request('/api/purchases?offset=30&expected_sequence='+z.body.sequence,x.f)).status,409);verifyProcurement(x.db);});
test('all source tables are immutable and nonmanager native supplier maintenance is rejected',async t=>{const x=await setup(t);await readyPurchase(x);for(const n of P.procurementTables){const key=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+key+'='+key),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}assert.throws(()=>P.supplierVersion(x.db,x.supplier.id,si(),'front'),/actor/);verifyProcurement(x.db);});
test('same-millisecond product and supplier changes cannot substitute later sources into past approvals',async t=>{const x=await setup(t);await readyPurchase(x);const at=now();P.purchaseEvent(x.db,x.purchase.id,{action:'submit',decision_basis:'同刻本版原需求',...notes()},'front',at);P.purchaseEvent(x.db,x.purchase.id,{action:'approve',decision_basis:'同刻明确原版本',...notes()},'manager',at);const p=x.db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? AND version=1').get(x.product.id);insertProductVersion(x.db,x.product.id,{...p,name:'同刻后来新增商品来源',reason:'实际更正'},'manager',at);P.supplierVersion(x.db,x.supplier.id,si({status:'inactive'}),'manager',at);verifyProcurement(x.db);const e=x.db.prepare("SELECT * FROM purchase_events WHERE request_id=? AND action='approve'").get(x.purchase.id),basis=x.db.prepare('SELECT basis_json FROM purchase_product_basis WHERE version_id=?').get(e.version_id).basis_json;tamper(x.db,'purchase_events','UPDATE purchase_events SET product_basis_json=? WHERE id=?',[basis,e.id]);assert.throws(()=>verifyProcurement(x.db),/采购/);});
test('a request waiting for its body rechecks supplier changes and cannot record a stale actual order',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'approve');const r=P.purchaseRecord(x.db,x.purchase.id),data={expected_sequence:sequence(x),expected_revision:r.revision,expected_version:1,action:'order',decision_basis:'原窗口实际订货来源',ordered_at:now(),order_reference:'PENDING-BODY',...notes()},raw=JSON.stringify(data);let req;const result=new Promise((resolve,reject)=>{req=httpRequest(x.origin+'/api/purchases/'+r.id+'/events',{method:'POST',headers:{Cookie:x.f.cookie,'X-CSRF-Token':x.f.csrf,'Idempotency-Key':'pending-purchase-body','Content-Type':'application/json','Content-Length':Buffer.byteLength(raw)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);});req.write(raw.slice(0,10));await changeSupplier(x,{status:'inactive'});req.end(raw.slice(10));assert.equal(await result,409);assert.equal(P.purchaseRecord(x.db,r.id).status,'approved');verifyProcurement(x.db);});
test('revoked session and initial-password accounts cannot save procurement sources or business decisions',async t=>{const x=await setup(t);await readyPurchase(x);const r=P.purchaseRecord(x.db,x.purchase.id),data={expected_sequence:sequence(x),expected_revision:r.revision,expected_version:1,action:'submit',decision_basis:'明确提交来源',...notes()};x.db.prepare('DELETE FROM sessions WHERE user_id=?').run('front');assert.equal((await x.request('/api/purchases/'+r.id+'/events',{...x.f,method:'POST',data})).status,401);x.db.prepare('INSERT INTO user_security VALUES(?,?,?)').run('manager',1,1);assert.equal((await supplier(x)).status,403);verifyProcurement(x.db);});
test('nonempty schema35 upgrade preserves all previous records and creates no suppliers, orders or inventory facts',async t=>{const dir=mkdtempSync(join(tmpdir(),'procurement-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,35)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('manager','manager','manager',hashPassword('synthetic-only-password'),'manager','a');d.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('one','a','one',null,null,null,now(),'manager');const tables=d.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations'").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));d.close();const u=openDatabase(path);for(const n of tables)assert.deepEqual(u.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),before[n],n);for(const n of P.procurementTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifyProcurement(u);u.close();});
test('five saved procurement stages append once and never create stock, payments or replace prior business rows',async t=>{const x=await setup(t);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('demo-manager','demo-manager','demo-manager',hashPassword('synthetic-only-password'),'manager','a');x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('demo-front','demo-front','demo-front',hashPassword('synthetic-only-password'),'reception','a');const tables=x.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoProcurement(x.db),{suppliers:2,purchases:5});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);verifyProcurement(x.db);const after=Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoProcurement(x.db),{suppliers:0,purchases:0});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),after[n],n);});

test('recorded actual purchase orders lock original product unit/category while allowing explicit name and price revisions',async t=>{const x=await setup(t);await readyPurchase(x);await action(x,'submit');await action(x,'approve');await action(x,'order');const p=x.db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? AND version=1').get(x.product.id);assert.throws(()=>insertProductVersion(x.db,x.product.id,{...p,unit:'盒',reason:'实际目录变化'},'manager'),/locked/);insertProductVersion(x.db,x.product.id,{...p,name:'明确名称更正',list_price_cents:999,reason:'原单位保留'},'manager');assert.equal(P.purchaseRecord(x.db,x.purchase.id).items[0].unit,'片');verifyProcurement(x.db);});
