import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {insertProductVersion} from '../src/retail.mjs';
import {physicalStock} from '../src/stock-ledger.mjs';
const now=()=>new Date().toISOString(),notes={note:'虚构实际办理',reason:'明确原始来源',next_step:'依实际后续办理'},metadata={lot_status:'unknown',lot_code:null,expiry_status:'unknown',expiry_date:null,location_status:'unknown',location_note:null,manufacturer_note:null,source_note:'虚构原收货资料',source_reference:'DEMO-ONLY',...notes},known={...metadata,lot_status:'recorded',lot_code:'DEMO-LOT',expiry_status:'provided',expiry_date:'2099-01-01',location_status:'recorded',location_note:'虚构隔离柜'},supplier={code:'TEST-SUPPLIER',name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构',settlement_note:null,source_note:'虚构',source_reference:'DEMO',status:'active',reason:'虚构'};
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-RECEIPT',name:'虚构实物',category:'lens',brand:null,specification:'原规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201);x.product=z.body.product;P.createSupplier(x.db,'a',supplier,'manager');x.purchase=P.createPurchase(x.db,'a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'虚构收货原采购',purpose_note:'实际用途',source_note:'虚构实际来源',source_reference:'DEMO',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'虚构明确来源',ordered_at:now(),order_reference:'DEMO-ORDER',...notes},action==='approve'?'manager':'front');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];return x;}
const input=(x,over={})=>({order_event_id:x.order.order_event_id,position:1,received_quantity:2,bound_quantity:2,received_at:now(),receiver_label:'虚构收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'虚构实际到货，不是自动验收',...metadata,...over});
async function receipt(x,over={},who=x.f,key=crypto.randomUUID()){const z=await x.request('/api/purchase-receipts',{...who,method:'POST',key,data:{expected_sequence:R.receivingSequence(x.db,'a'),...input(x,over)}});if(z.status===201)x.receipt=z.body.record;return z;}
const eventInput=(x,action,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,...notes,...(action.startsWith('quality_')?{checked_at:now(),requirement_source:'虚构明确人工验收要求，不是默认标准',require_lot:false,require_expiry:false,require_location:false,checks:[{label:'实际外观项目',result:action==='quality_pass'?'pass':'fail'}]}:{}),...(action==='inbound'?{inbound_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision}:{}),...over};};
async function act(x,action,over={},who=x.m,key=crypto.randomUUID()){return x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...who,method:'POST',key,data:eventInput(x,action,over)});}
async function revise(x,over={}){const r=R.receiptRecord(x.db,x.receipt.id);return x.request('/api/purchase-receipts/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,...metadata,...over}});}
const good=z=>assert.equal(z.status,201,JSON.stringify(z.body));
test('split actual receipts preserve unknown provenance and oversupply without stock or payment',async t=>{const x=await setup(t);good(await receipt(x,{received_quantity:3,bound_quantity:2}));good(await receipt(x,{received_quantity:2,bound_quantity:2}));assert.equal((await receipt(x,{bound_quantity:1})).status,409);const l=R.purchaseReceiptLines(x.db,x.purchase.id)[0];assert.deepEqual([l.claimed,l.extra,l.posted,l.remaining],[4,1,0,0]);assert.equal(physicalStock(x.db,x.product.id).on_hand,0);assert.equal(x.db.prepare('SELECT count(*) n FROM payment_events').get().n,0);verifyReceiving(x.db);});
test('explicit quality and actual stock posting remain separate; a retry posts once',async t=>{const x=await setup(t);good(await receipt(x,known));good(await act(x,'quality_pass',{require_lot:true,require_expiry:true,require_location:true},x.p));assert.equal(physicalStock(x.db,x.product.id).on_hand,0);const data=eventInput(x,'inbound'),key=crypto.randomUUID(),post=()=>x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...x.m,method:'POST',key,data});good(await post());good(await post());assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_inbound_refs').get().n,1);assert.equal(physicalStock(x.db,x.product.id).available,2);assert.equal((await act(x,'inbound')).status,409);verifyReceiving(x.db);});
test('unknown required provenance blocks pass; explicit failure can be recorded and quarantined atomically',async t=>{const x=await setup(t);good(await receipt(x));assert.equal((await act(x,'quality_pass',{require_lot:true})).status,409);good(await act(x,'quality_fail',{require_lot:true},x.p));assert.equal((await act(x,'inbound')).status,409);good(await act(x,'inbound',{inbound_bucket:'quarantined'}));const b=physicalStock(x.db,x.product.id);assert.deepEqual([b.available,b.quarantined,b.on_hand],[0,2,2]);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_inbound_refs').get().n,2);verifyReceiving(x.db);});
test('receipt provenance correction requires new quality before posting and preserves previous facts',async t=>{const x=await setup(t);good(await receipt(x));good(await act(x,'quality_pass'));good(await revise(x,known));assert.equal(R.receiptRecord(x.db,x.receipt.id).status,'pending');assert.equal((await act(x,'inbound')).status,409);assert.equal(R.receiptRecord(x.db,x.receipt.id,{version:1}).lot_code,null);good(await act(x,'quality_pass',{require_lot:true}));good(await act(x,'inbound'));verifyReceiving(x.db);});
test('posted metadata correction never moves inventory or permits a second posting',async t=>{const x=await setup(t);good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound'));const b=physicalStock(x.db,x.product.id);good(await revise(x,{...known,lot_code:'DEMO-FACT-CORRECTION'}));assert.equal(R.receiptRecord(x.db,x.receipt.id).status,'posted');assert.deepEqual(physicalStock(x.db,x.product.id),b);assert.equal((await act(x,'inbound')).status,409);assert.equal((await act(x,'cancel')).status,409);verifyReceiving(x.db);});
test('unmatched oversupply remains explicit held quantity and cannot enter either stock bucket',async t=>{const x=await setup(t);good(await receipt(x,{received_quantity:2,bound_quantity:0}));for(const inbound_bucket of ['available','quarantined'])assert.equal((await act(x,'inbound',{inbound_bucket})).status,409);assert.equal(R.purchaseReceiptLines(x.db,x.purchase.id)[0].extra,2);verifyReceiving(x.db);});
test('manager unposted misrecord cancellation releases matching capacity without supplier return',async t=>{const x=await setup(t);good(await receipt(x,{received_quantity:4,bound_quantity:4}));assert.equal((await act(x,'cancel',{},x.f)).status,403);good(await act(x,'cancel'));good(await receipt(x,{received_quantity:4,bound_quantity:4}));assert.equal(x.db.prepare("SELECT count(*) n FROM purchase_receipt_events WHERE action='cancel'").get().n,1);assert.equal(physicalStock(x.db,x.product.id).on_hand,0);verifyReceiving(x.db);});
test('later supplier disabling and product naming revisions do not erase actual arrival in the original unit',async t=>{const x=await setup(t);P.supplierVersion(x.db,x.order.supplier_id,{...supplier,status:'inactive'},'manager');const p=x.db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? AND version=1').get(x.product.id);insertProductVersion(x.db,x.product.id,{...p,name:'更正后名称',status:'inactive',reason:'保留实际旧订货'},'manager');good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound'));assert.equal(R.receiptRecord(x.db,x.receipt.id).product.name,'虚构实物');verifyReceiving(x.db);});
test('known delivery source line identities reject duplicates; unknown source remains unknown',async t=>{const x=await setup(t);good(await receipt(x,{delivery_reference:'DEMO-NOTE',source_line_reference:'LINE1'}));assert.equal((await receipt(x,{delivery_reference:'DEMO-NOTE',source_line_reference:'LINE1'})).status,409);good(await receipt(x,{bound_quantity:0}));verifyReceiving(x.db);});
test('scope and actor rights distinguish receipt transcription, quality and stock',async t=>{const x=await setup(t);assert.equal((await receipt(x,{},x.p)).status,403);good(await receipt(x));for(const who of [x.g,x.o])assert.ok([403,404].includes((await x.request('/api/purchase-receipts/'+x.receipt.id,who)).status));assert.equal((await act(x,'quality_pass',{},x.f)).status,403);good(await act(x,'quality_pass',{},x.p));assert.equal((await act(x,'inbound',{},x.p)).status,403);verifyReceiving(x.db);});
test('invalid actual dates, incomplete requirements and invented extra fields never append partial facts',async t=>{const x=await setup(t);for(const over of [{received_at:'2000-01-01T00:00:00.000Z'},{received_at:new Date(Date.now()+60000).toISOString()},{bound_quantity:3},{expiry_status:'provided',expiry_date:'2026-02-30'},{delivery_reference:'KNOWN',source_line_reference:null},{default_accept:true}])assert.ok([409,422].includes((await receipt(x,over)).status));assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_receipts').get().n,0);good(await receipt(x));for(const over of [{require_lot:null},{checks:[{label:'结果缺失'}]},{checks:[{label:'实际失败',result:'fail'}]},{checked_at:'2000-01-01T00:00:00.000Z'}])assert.ok([422,409].includes((await act(x,'quality_pass',over)).status));verifyReceiving(x.db);});
test('audit failure rolls back receipt, versions, stock, refs and idempotency together',async t=>{const x=await setup(t);good(await receipt(x,known));good(await act(x,'quality_pass'));x.db.exec("CREATE TRIGGER receiving_test_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test audit'); END");const z=await act(x,'inbound');assert.equal(z.status,500);assert.equal(physicalStock(x.db,x.product.id).on_hand,0);assert.equal(R.receiptRecord(x.db,x.receipt.id).status,'passed');assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_inbound_refs').get().n,0);x.db.exec('DROP TRIGGER receiving_test_audit');good(await act(x,'inbound'));verifyReceiving(x.db);});
test('native immutable source and aggregate quantity guards protect append-only actual records',async t=>{const x=await setup(t);R.createReceipt(x.db,'a',input(x,{received_quantity:4,bound_quantity:4}),'front');assert.throws(()=>R.createReceipt(x.db,'a',input(x,{bound_quantity:1}),'front'),/capacity/);x.receipt=R.receiptRecord(x.db,x.db.prepare('SELECT id FROM purchase_receipts').get().id);good(await act(x,'inbound',{inbound_bucket:'quarantined'}));for(const n of R.receivingTables){const k=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+k+'='+k),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}verifyReceiving(x.db);});
test('independent full backup restores receipt source versions and original stock refs after a correction',async t=>{const x=await setup(t,{persist:true});good(await receipt(x,known));good(await act(x,'quality_fail'));good(await act(x,'inbound',{inbound_bucket:'quarantined'}));good(await revise(x,{...known,lot_code:'CORRECTED'}));const b=await createBackup(x.path,join(x.dir,'backups'));const z=await restoreBackup(b.backup,join(x.dir,'restore')),d=openDatabase(z.database);t.after(()=>d.close());for(const n of R.receivingTables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all());verifyReceiving(d);});
import {seedDemoReceiving} from '../src/demo-purchase-receiving.mjs';
test('synthetic receipt stages append their own purchase/stock sources once and preserve all previous rows',async t=>{const x=await setup(t);for(const[id,role]of [['demo-manager','manager'],['demo-front','reception']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');const tables=x.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoReceiving(x.db),{receipts:4,inbounds:3});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);verifyReceiving(x.db);const after=Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoReceiving(x.db),{receipts:0,inbounds:0});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),after[n],n);});
test('stale source and stock leases reject posting without credits; logout revokes a cached retry',async t=>{const x=await setup(t);good(await receipt(x,known));good(await act(x,'quality_pass'));assert.equal((await act(x,'inbound',{expected_stock_sequence:99})).status,409);const data=eventInput(x,'inbound'),key=crypto.randomUUID(),post=()=>x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...x.m,method:'POST',data,key});good(await post());x.db.prepare('DELETE FROM sessions WHERE user_id=?').run('manager');assert.equal((await post()).status,401);assert.equal(physicalStock(x.db,x.product.id).available,2);verifyReceiving(x.db);});
test('native positive quality cannot invent omitted results and available posting cannot bypass quality',async t=>{const x=await setup(t);good(await receipt(x));assert.throws(()=>R.receivingEvent(x.db,x.receipt.id,{...eventInput(x,'quality_pass'),checks:[{label:'缺少原结果'}]},'manager'),/quality/);assert.throws(()=>R.receivingEvent(x.db,x.receipt.id,{action:'inbound',inbound_bucket:'available',...notes},'manager'),/stock source/);assert.equal(physicalStock(x.db,x.product.id).on_hand,0);verifyReceiving(x.db);});
test('nonempty schema36 upgrade preserves original procurement and creates no actual receipt or stock credits',async t=>{const dir=mkdtempSync(join(tmpdir(),'receiving-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,36)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('manager','manager','manager',hashPassword('synthetic-only-password'),'manager','a');P.createSupplier(d,'a',supplier,'manager');const before=d.prepare('SELECT * FROM supplier_versions').all();d.close();const u=openDatabase(path);assert.deepEqual(u.prepare('SELECT * FROM supplier_versions').all(),before);for(const n of R.receivingTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifyReceiving(u);u.close();});
test('body-waiting inbound rechecks new receipt provenance before returning any cached positive response',async t=>{const x=await setup(t);good(await receipt(x,known));good(await act(x,'quality_pass'));const data=eventInput(x,'inbound'),key='receiving-cached-original',url='/api/purchase-receipts/'+x.receipt.id+'/events';good(await x.request(url,{...x.m,method:'POST',data,key}));const raw=JSON.stringify(data);let req;const result=new Promise((resolve,reject)=>{req=httpRequest(x.origin+url,{method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(raw)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);});req.write(raw.slice(0,10));good(await revise(x,{...known,lot_code:'LATER-FACT'}));req.end(raw.slice(10));assert.equal(await result,409);assert.equal(physicalStock(x.db,x.product.id).on_hand,2);verifyReceiving(x.db);});
test('same-millisecond provenance and original stock references reject later substitution during recovery',async t=>{const x=await setup(t);const at=now();x.receipt=R.createReceipt(x.db,'a',input(x,{...known,received_at:at}),'front',at);R.receivingEvent(x.db,x.receipt.id,{...eventInput(x,'quality_pass'),checked_at:at},'manager',at);R.receivingEvent(x.db,x.receipt.id,{action:'inbound',inbound_bucket:'available',...notes},'manager',at);R.receiptVersion(x.db,x.receipt.id,{...known,lot_code:'SAME-MS-LATER'},'front',at);verifyReceiving(x.db);const name='purchase_receipt_events_no_update',sql=x.db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(name).sql,e=x.db.prepare("SELECT * FROM purchase_receipt_events WHERE action='inbound'").get(),v=x.db.prepare('SELECT id FROM purchase_receipt_versions WHERE version=2').get();x.db.exec('DROP TRIGGER '+name);x.db.prepare('UPDATE purchase_receipt_events SET version_id=? WHERE id=?').run(v.id,e.id);x.db.exec(sql);assert.throws(()=>verifyReceiving(x.db),/采购收货/);});
