import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {insertProductVersion} from '../src/retail.mjs';
import {physicalStock} from '../src/stock-ledger.mjs';
const now=()=>new Date().toISOString(),notes={note:'虚构实际办理',reason:'明确原始来源',next_step:'依实际后续办理'},metadata={lot_status:'unknown',lot_code:null,expiry_status:'unknown',expiry_date:null,location_status:'unknown',location_note:null,manufacturer_note:null,source_note:'虚构原收货资料',source_reference:'DEMO-ONLY',...notes},known={...metadata,lot_status:'recorded',lot_code:'DEMO-LOT',expiry_status:'provided',expiry_date:'2099-01-01',location_status:'recorded',location_note:'虚构隔离柜'},supplier={code:'TEST-SUPPLIER',name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构',settlement_note:null,source_note:'虚构',source_reference:'DEMO',status:'active',reason:'虚构'};
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-RECEIPT',name:'虚构实物',category:'lens',brand:null,specification:'原规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201);x.product=z.body.product;P.createSupplier(x.db,'a',supplier,'manager');x.purchase=P.createPurchase(x.db,'a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'虚构收货原采购',purpose_note:'实际用途',source_note:'虚构实际来源',source_reference:'DEMO',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'虚构明确来源',ordered_at:now(),order_reference:'DEMO-ORDER',...notes},action==='approve'?'manager':'front');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];return x;}
const input=(x,over={})=>({order_event_id:x.order.order_event_id,position:1,received_quantity:2,bound_quantity:2,received_at:now(),receiver_label:'虚构收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'虚构实际到货，不是自动验收',...metadata,...over});
async function receipt(x,over={},who=x.f,key=crypto.randomUUID()){const z=await x.request('/api/purchase-receipts',{...who,method:'POST',key,data:{expected_sequence:R.receivingSequence(x.db,'a'),...input(x,over)}});if(z.status===201)x.receipt=z.body.record;return z;}
const eventInput=(x,action,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,...notes,...(action.startsWith('quality_')?{checked_at:now(),requirement_source:'虚构明确人工验收要求，不是默认标准',require_lot:false,require_expiry:false,require_location:false,checks:[{label:'实际外观项目',result:action==='quality_pass'?'pass':'fail'}]}:{}),...(action==='inbound'?{inbound_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision}:{}),...over};};
async function act(x,action,over={},who=x.m,key=crypto.randomUUID()){return x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...who,method:'POST',key,data:eventInput(x,action,over)});}
async function revise(x,over={}){const r=R.receiptRecord(x.db,x.receipt.id);return x.request('/api/purchase-receipts/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,...metadata,...over}});}
const good=z=>assert.equal(z.status,201,JSON.stringify(z.body));
import * as Q from '../src/purchase-quality.mjs';
import {verifyPurchaseQuality} from '../src/purchase-quality-recovery.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
async function base(t,over={}){const x=await setup(t,over);good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound',{inbound_bucket:over.bucket||'available'}));return x;}
const qi=(x,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),receipt_id:r.id,receipt_version_id:r.version_id,quantity:1,source_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,custody_confirmed_at:now(),custody_source:'实际核对原收货箱与本批在库数量（虚构）',observed_at:now(),observation_note:'实际待复检情况（虚构）',source_reference:'DEMO-ACTUAL-CUSTODY',...notes,...over};};
async function caseCreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-quality',{...who,method:'POST',key,data:qi(x,over)});if(z.status===201)x.q=z.body.record;return z;}
const qe=(x,action,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,action,...notes,...(action==='release'?{expected_stock_sequence:c.stock.sequence,expected_outbound_revision:c.stock.outbound_revision}:{checked_at:now(),requirement_source:'本次实际人工要求（虚构），不是通用标准',require_lot:true,require_expiry:true,require_location:true,checks:[{label:'实际本批复检项目（虚构）',result:action==='quality_pass'?'pass':'fail'}]}),...over};};
async function qact(x,action,over={},who=x.p,key=crypto.randomUUID()){return x.request('/api/purchase-quality/'+x.q.id+'/events',{...who,method:'POST',data:qe(x,action,over),key});}
async function qrevise(x,over={},who=x.p){const r=R.receiptRecord(x.db,x.receipt.id),c=Q.purchaseQualityRecord(x.db,x.q.id);return x.request('/api/purchase-quality/'+c.id+'/versions',{...who,method:'POST',data:{expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,receipt_version_id:r.version_id,observed_at:now(),observation_note:'明确新增实际观察',source_reference:'DEMO-NEW-FACT',...notes,...over}});}
const verify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);};
test('manager isolates actual source-specific in-stock quantity; review and release remain independent',async t=>{const x=await base(t);good(await caseCreate(x));assert.deepEqual([physicalStock(x.db,x.product.id).available,physicalStock(x.db,x.product.id).quarantined],[1,1]);assert.equal(Q.protectedQuarantine(x.db,x.product.id),1);good(await qact(x,'quality_pass'));assert.equal(physicalStock(x.db,x.product.id).quarantined,1);good(await qact(x,'release',{},x.m));assert.deepEqual([physicalStock(x.db,x.product.id).available,physicalStock(x.db,x.product.id).quarantined],[2,0]);assert.equal(Q.protectedQuarantine(x.db,x.product.id),0);verify(x);});
test('actual already-quarantined stock can be claimed once without a duplicate isolation entry',async t=>{const x=await base(t,{bucket:'quarantined'});const before=x.db.prepare('SELECT count(*) n FROM inventory_events').get().n;good(await caseCreate(x,{source_bucket:'quarantined',quantity:2}));assert.equal(x.db.prepare('SELECT count(*) n FROM inventory_events').get().n,before);assert.equal((await caseCreate(x,{source_bucket:'quarantined'})).status,409);verify(x);});
test('generic API and native unquarantine cannot bypass source-specific pending or failed quality',async t=>{const x=await base(t);good(await caseCreate(x,{quantity:2}));good(await qact(x,'quality_fail'));const b=physicalStock(x.db,x.product.id),z=await x.request('/api/inventory/products/'+x.product.id+'/events',{...x.m,method:'POST',data:{expected_sequence:b.sequence,expected_outbound_revision:b.outbound_revision,expected_product_version:1,action:'unquarantine',quantity:1,reason:'不能绕过原复检'}});assert.equal(z.status,409,JSON.stringify(z.body));assert.throws(()=>insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'unquarantine',quantity:1,reason:'原生绕过',created_by:'manager'}),/protected quarantine/);assert.equal((await qact(x,'release',{},x.m)).status,409);verify(x);});
test('fresh observation version resets review; original quality and stock sources remain fixed',async t=>{const x=await base(t);good(await caseCreate(x));good(await qact(x,'quality_fail'));good(await qrevise(x));assert.equal(Q.purchaseQualityRecord(x.db,x.q.id).status,'pending');assert.equal(Q.purchaseQualityRecord(x.db,x.q.id,{version:1}).observation_note,'实际待复检情况（虚构）');good(await qact(x,'quality_pass'));good(await qact(x,'release',{},x.m));assert.equal((await qrevise(x)).status,409);verify(x);});
test('later receipt metadata requires explicit current-source adoption before review or release',async t=>{const x=await base(t);good(await caseCreate(x));good(await qact(x,'quality_pass'));good(await revise(x,{...known,lot_code:'NEW-RECEIPT-FACT'}));assert.equal((await qact(x,'release',{},x.m)).status,409);good(await qrevise(x));good(await qact(x,'quality_pass'));good(await qact(x,'release',{},x.m));const history=Q.purchaseQualityRecord(x.db,x.q.id);assert.equal(history.history.find(e=>e.action==='quality_pass'&&e.version===1).receipt_version,1);verify(x);});
test('exact-source release retries once, while later original receipt correction blocks old cached positive response',async t=>{const x=await base(t);good(await caseCreate(x));good(await qact(x,'quality_pass'));const data=qe(x,'release'),key=crypto.randomUUID(),post=()=>x.request('/api/purchase-quality/'+x.q.id+'/events',{...x.m,method:'POST',data,key});good(await post());good(await post());assert.equal(x.db.prepare("SELECT count(*) n FROM inventory_events WHERE action='unquarantine'").get().n,1);good(await revise(x,{...known,lot_code:'AFTER-RELEASE-CORRECTION'}));assert.equal((await post()).status,409);verify(x);});
test('unprotected quarantine remains available to explicit generic management without consuming claimed quantities',async t=>{const x=await base(t,{bucket:'quarantined'});good(await caseCreate(x,{source_bucket:'quarantined'}));const b=physicalStock(x.db,x.product.id);good(await x.request('/api/inventory/products/'+x.product.id+'/events',{...x.m,method:'POST',data:{expected_sequence:b.sequence,expected_outbound_revision:b.outbound_revision,expected_product_version:1,action:'unquarantine',quantity:1,reason:'明确仅解除尚未占用原库存'}}));assert.equal(physicalStock(x.db,x.product.id).quarantined,1);verify(x);});
test('role, store and guardian boundaries distinguish actual isolation, quality and release',async t=>{const x=await base(t);assert.equal((await caseCreate(x,{},x.p)).status,403);assert.equal((await caseCreate(x,{},x.f)).status,403);good(await caseCreate(x));assert.ok([403,404].includes((await x.request('/api/purchase-quality/'+x.q.id,x.g)).status));assert.equal((await x.request('/api/purchase-quality/'+x.q.id,x.o)).status,404);assert.equal((await qact(x,'quality_pass',{},x.f)).status,403);good(await qact(x,'quality_pass'));assert.equal((await qact(x,'release',{},x.p)).status,403);verify(x);});
test('stale stock and quality leases reject actual custody and release without moving goods',async t=>{const x=await base(t);assert.equal((await caseCreate(x,{expected_stock_sequence:99})).status,409);good(await caseCreate(x));good(await qact(x,'quality_pass'));assert.equal((await qact(x,'release',{expected_stock_sequence:99},x.m)).status,409);assert.equal(physicalStock(x.db,x.product.id).quarantined,1);verify(x);});
test('audit failure rolls isolation, protected quantity, source versions and cache back together',async t=>{const x=await base(t);x.db.exec("CREATE TRIGGER q_test_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test'); END");assert.equal((await caseCreate(x)).status,500);assert.equal(Q.protectedQuarantine(x.db,x.product.id),0);assert.equal(physicalStock(x.db,x.product.id).quarantined,0);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_quality_cases').get().n,0);x.db.exec('DROP TRIGGER q_test_audit');good(await caseCreate(x));verify(x);});
test('independent backup retains protected quantities, exact source versions and original stock contexts',async t=>{const x=await base(t,{persist:true});good(await caseCreate(x));good(await qact(x,'quality_pass'));const b=await createBackup(x.path,join(x.dir,'backup')),z=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(z.database);t.after(()=>d.close());for(const n of Q.purchaseQualityTables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all());verifyPurchaseQuality(d);});
import {seedDemoPurchaseQuality} from '../src/demo-purchase-quality.mjs';
test('five independent synthetic quality stages append attributed sources once and preserve previous business rows',async t=>{const x=await setup(t);for(const[id,role]of [['demo-manager','manager'],['demo-front','reception']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');const tables=x.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoPurchaseQuality(x.db),{cases:5,released:1});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);verify(x);const after=Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoPurchaseQuality(x.db),{cases:0,released:0});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),after[n],n);});
test('native immutability, custody capacity and result requirements reject direct altered facts',async t=>{const x=await base(t);good(await caseCreate(x));assert.throws(()=>Q.createPurchaseQuality(x.db,'a',qi(x,{quantity:2}),'manager'),/custody\/capacity|original receipt remaining quantity/);assert.throws(()=>Q.purchaseQualityEvent(x.db,x.q.id,{...qe(x,'quality_pass'),checks:[{label:'结果缺失'}]},'professional'),/actual checks/);good(await qact(x,'quality_pass'));good(await qact(x,'release',{},x.m));for(const n of Q.purchaseQualityTables){const k=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+k+'='+k),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}verify(x);});
test('same-millisecond source substitution and stock protection prefixes cannot replace original recovery references',async t=>{const x=await base(t),at=now();x.q=Q.createPurchaseQuality(x.db,'a',qi(x,{custody_confirmed_at:at,observed_at:at}),'manager',at);Q.purchaseQualityEvent(x.db,x.q.id,{...qe(x,'quality_pass'),checked_at:at},'professional',at);Q.purchaseQualityEvent(x.db,x.q.id,qe(x,'release'),'manager',at);R.receiptVersion(x.db,x.receipt.id,{...known,lot_code:'SAME-MS-LATER-FACT'},'front',at);verify(x);const stock=x.db.prepare("SELECT id FROM inventory_events WHERE action='unquarantine'").get(),name='purchase_quality_stock_context_no_update',sql=x.db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(name).sql;x.db.exec('DROP TRIGGER '+name);x.db.prepare('UPDATE purchase_quality_stock_context SET quality_sequence=0 WHERE stock_event_id=?').run(stock.id);x.db.exec(sql);assert.throws(()=>verifyPurchaseQuality(x.db),/采购质量/);});
test('request body waiting for release rechecks original receipt revision before cached response',async t=>{const x=await base(t);good(await caseCreate(x));good(await qact(x,'quality_pass'));const data=qe(x,'release'),key='quality-body-cached',url='/api/purchase-quality/'+x.q.id+'/events';good(await x.request(url,{...x.m,method:'POST',data,key}));const raw=JSON.stringify(data);let req;const result=new Promise((resolve,reject)=>{req=httpRequest(x.origin+url,{method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(raw)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);});req.write(raw.slice(0,10));good(await revise(x,{...known,lot_code:'LATER-ORIGINAL-RECEIPT'}));req.end(raw.slice(10));assert.equal(await result,409);verify(x);});
test('actual custody/observation/check times and unsupported policies do not append partial cases',async t=>{const x=await base(t);for(const over of [{custody_confirmed_at:'2000-01-01T00:00:00.000Z'},{observed_at:new Date(Date.now()+60000).toISOString()},{quantity:0},{default_quality_policy:'invented'},{source_bucket:'supplier'},{custody_source:''}])assert.ok([409,422].includes((await caseCreate(x,over)).status));assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_quality_cases').get().n,0);good(await caseCreate(x));for(const over of [{require_lot:null},{checked_at:'2000-01-01T00:00:00.000Z'},{checks:[{label:'原不合格',result:'fail'}]}])assert.ok([409,422].includes((await qact(x,'quality_pass',over)).status));verify(x);});
test('nonempty schema37 upgrade adds no professional checks or isolation, with only technical zero-prefix stock contexts',async t=>{const dir=mkdtempSync(join(tmpdir(),'quality-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,37)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('manager','manager','manager',hashPassword('synthetic-only-password'),'manager','a');P.createSupplier(d,'a',supplier,'manager');const before=d.prepare('SELECT * FROM supplier_versions').all();d.close();const u=openDatabase(path);assert.deepEqual(u.prepare('SELECT * FROM supplier_versions').all(),before);for(const n of Q.purchaseQualityTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifyPurchaseQuality(u);u.close();});
test('bounded quality history retains total counts and rejects changed-source continuation',async t=>{const x=await base(t);good(await caseCreate(x));for(let i=0;i<31;i++)good(await qrevise(x,{observation_note:'明确第 '+i+' 版实际观察'}));const a=await x.request('/api/purchase-quality/'+x.q.id+'?limit=30',x.m);assert.equal(a.body.record.total,32);assert.equal(a.body.record.history.length,30);assert.equal((await x.request('/api/purchase-quality/'+x.q.id+'?offset=30',x.m)).status,409);const b=await x.request('/api/purchase-quality/'+x.q.id+'?offset=30&expected_sequence='+a.body.sequence,x.m);assert.equal(b.body.record.history.length,2);verify(x);});
test('release audit failure rolls back protected status and stock movements; session revocation denies retry',async t=>{const x=await base(t);good(await caseCreate(x));good(await qact(x,'quality_pass'));x.db.exec("CREATE TRIGGER q_release_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test'); END");assert.equal((await qact(x,'release',{},x.m)).status,500);assert.equal(Q.purchaseQualityRecord(x.db,x.q.id).status,'passed');assert.equal(Q.protectedQuarantine(x.db,x.product.id),1);assert.equal(physicalStock(x.db,x.product.id).quarantined,1);x.db.exec('DROP TRIGGER q_release_audit');const data=qe(x,'release'),key=crypto.randomUUID(),post=()=>x.request('/api/purchase-quality/'+x.q.id+'/events',{...x.m,method:'POST',data,key});good(await post());x.db.prepare('DELETE FROM sessions WHERE user_id=?').run('manager');assert.equal((await post()).status,401);verify(x);});
test('actual expired source metadata permits failure preservation while blocking positive recheck and release',async t=>{const x=await base(t);good(await caseCreate(x));good(await revise(x,{...known,expiry_date:'2000-01-01'}));good(await qrevise(x));assert.equal((await qact(x,'quality_pass')).status,409);good(await qact(x,'quality_fail'));assert.equal(Q.protectedQuarantine(x.db,x.product.id),1);assert.equal((await qact(x,'release',{},x.m)).status,409);verify(x);});
