import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as P from '../src/procurement.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {insertProductVersion} from '../src/retail.mjs';
import {physicalStock} from '../src/stock-ledger.mjs';
const now=()=>new Date().toISOString(),notes={note:'虚构实际办理',reason:'明确原始来源',next_step:'依实际后续办理'},metadata={lot_status:'unknown',lot_code:null,expiry_status:'unknown',expiry_date:null,location_status:'unknown',location_note:null,manufacturer_note:null,source_note:'虚构原收货资料',source_reference:'DEMO-ONLY',...notes},known={...metadata,lot_status:'recorded',lot_code:'DEMO-LOT',expiry_status:'provided',expiry_date:'2099-01-01',location_status:'recorded',location_note:'虚构隔离柜'},supplier={code:'TEST-SUPPLIER',name:'虚构供应商',contact_label:null,contact_method:null,address_note:null,scope_note:'仅虚构',settlement_note:null,source_note:'虚构',source_reference:'DEMO',status:'active',reason:'虚构'};
async function setup(t,opts){const x=await fixture(t,opts);Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});const z=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'DEMO-RECEIPT',name:'虚构实物',category:'lens',brand:null,specification:'原规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(z.status,201);x.product=z.body.product;P.createSupplier(x.db,'a',supplier,'manager');x.purchase=P.createPurchase(x.db,'a',{supplier_id:x.db.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'虚构收货原采购',purpose_note:'实际用途',source_note:'虚构实际来源',source_reference:'DEMO',expected_date:null,items:[{product_id:x.product.id,product_version:1,quantity:4,unit_price_cents:100,note:null}],...notes},'front');for(const action of ['submit','approve','order'])P.purchaseEvent(x.db,x.purchase.id,{action,decision_basis:'虚构明确来源',ordered_at:now(),order_reference:'DEMO-ORDER',...notes},action==='approve'?'manager':'front');x.order=R.purchaseReceiptLines(x.db,x.purchase.id)[0];return x;}
const input=(x,over={})=>({order_event_id:x.order.order_event_id,position:1,received_quantity:2,bound_quantity:2,received_at:now(),receiver_label:'虚构收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'虚构实际到货，不是自动验收',...metadata,...over});
async function receipt(x,over={},who=x.f,key=crypto.randomUUID()){const z=await x.request('/api/purchase-receipts',{...who,method:'POST',key,data:{expected_sequence:R.receivingSequence(x.db,'a'),...input(x,over)}});if(z.status===201)x.receipt=z.body.record;return z;}
const eventInput=(x,action,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,...notes,...(action.startsWith('quality_')?{checked_at:now(),requirement_source:'虚构明确人工验收要求，不是默认标准',require_lot:false,require_expiry:false,require_location:false,checks:[{label:'实际外观项目',result:action==='quality_pass'?'pass':'fail'}]}:{}),...(action==='inbound'?{inbound_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision}:{}),...over};};
async function act(x,action,over={},who=x.m,key=crypto.randomUUID()){return x.request('/api/purchase-receipts/'+x.receipt.id+'/events',{...who,method:'POST',key,data:eventInput(x,action,over)});}
async function revise(x,over={}){const r=R.receiptRecord(x.db,x.receipt.id);return x.request('/api/purchase-receipts/'+r.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:R.receivingSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,...metadata,...over}});}
const good=z=>assert.equal(z.status,201,JSON.stringify(z.body));
import * as Q from '../src/purchase-quality.mjs';
import {verifyPurchaseQuality} from '../src/purchase-quality-recovery.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
async function base(t,over={}){const x=await setup(t,over);good(await receipt(x,known));good(await act(x,'quality_pass'));good(await act(x,'inbound',{inbound_bucket:over.bucket||'available'}));return x;}
const qi=(x,over={})=>{const r=R.receiptRecord(x.db,x.receipt.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),receipt_id:r.id,receipt_version_id:r.version_id,quantity:1,source_bucket:'available',expected_stock_sequence:r.stock.sequence,expected_outbound_revision:r.stock.outbound_revision,custody_confirmed_at:now(),custody_source:'实际核对原收货箱与本批在库数量（虚构）',observed_at:now(),observation_note:'实际待复检情况（虚构）',source_reference:'DEMO-ACTUAL-CUSTODY',...notes,...over};};
async function caseCreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-quality',{...who,method:'POST',key,data:qi(x,over)});if(z.status===201)x.q=z.body.record;return z;}
const qe=(x,action,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,action,...notes,...(action==='release'?{expected_stock_sequence:c.stock.sequence,expected_outbound_revision:c.stock.outbound_revision}:{checked_at:now(),requirement_source:'本次实际人工要求（虚构），不是通用标准',require_lot:true,require_expiry:true,require_location:true,checks:[{label:'实际本批复检项目（虚构）',result:action==='quality_pass'?'pass':'fail'}]}),...over};};
async function qact(x,action,over={},who=x.p,key=crypto.randomUUID()){return x.request('/api/purchase-quality/'+x.q.id+'/events',{...who,method:'POST',data:qe(x,action,over),key});}
async function qrevise(x,over={},who=x.p){const r=R.receiptRecord(x.db,x.receipt.id),c=Q.purchaseQualityRecord(x.db,x.q.id);return x.request('/api/purchase-quality/'+c.id+'/versions',{...who,method:'POST',data:{expected_sequence:Q.purchaseQualitySequence(x.db,'a'),expected_revision:c.revision,expected_version:c.current_version,receipt_version_id:r.version_id,observed_at:now(),observation_note:'明确新增实际观察',source_reference:'DEMO-NEW-FACT',...notes,...over}});}
const verify=x=>{verifyReceiving(x.db);verifyPurchaseQuality(x.db);};
import * as S from '../src/supplier-returns.mjs';
import {supplierReturnSequence} from '../src/supplier-return-ledger.mjs';
import {verifySupplierReturns} from '../src/supplier-return-recovery.mjs';
import {seedDemoSupplierReturns} from '../src/demo-supplier-returns.mjs';
const si=(x,over={})=>{const c=Q.purchaseQualityRecord(x.db,x.q.id);return {expected_sequence:supplierReturnSequence(x.db,'a'),case_id:c.id,quantity:2,source_note:'实际原批退供安排（虚构）',quality_version_id:c.version_id,quality_event_id:c.current.id,receipt_version_id:c.receipt_current.id,expected_case_return_revision:c.case_return_revision,return_basis:'人工明确退供依据（虚构），不预设正式政策',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-RETURN',...notes,...over};};
async function sb(t,opts={}){const x=await base(t,{bucket:'quarantined',...opts});good(await caseCreate(x,{quantity:2,source_bucket:'quarantined'}));good(await qact(x,'quality_fail'));return x;}
async function create(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns',{...who,method:'POST',data:si(x,over),key});if(z.status===201)x.s=z.body.record;return z;}
const se=(x,action,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id);return {expected_sequence:supplierReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,action,decision_basis:'本次人工商业依据（虚构）',...notes,...over};};
const sa=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/supplier-returns/'+x.s.id+'/events',{...who,method:'POST',data:se(x,action,over),key});
async function approved(x){good(await create(x));good(await sa(x,'submit'));good(await sa(x,'approve'));return x;}
const hi=(x,over={})=>{const r=S.supplierReturnRecord(x.db,x.s.id),s=r.source;return {expected_sequence:supplierReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,quantity:1,handed_at:now(),collector_label:'虚构实际接收人',destination_note:'虚构实际接收地点',external_reference:null,source_identity:null,source_note:'本次实际交出事实（虚构）',expected_stock_sequence:s.stock.sequence,expected_outbound_revision:s.stock.outbound_revision,expected_product_return_revision:s.stock.return_revision,expected_case_return_revision:s.balance.case_return_revision,expected_handed_quantity:r.balance.handed_quantity,reason:notes.reason,next_step:notes.next_step,...over};};
async function hand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/supplier-returns/'+x.s.id+'/handoffs',{...who,method:'POST',data:hi(x,over),key});if(z.status===201)x.h=z.body.record.handoffs[0];return z;}
const ri=(x,over={})=>({expected_sequence:supplierReturnSequence(x.db,'a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'可核对供应方实际收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const receive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/supplier-return-handoffs/'+x.h.id+'/receipts',{...who,method:'POST',data:ri(x,over),key});
const verified=x=>{verify(x);verifySupplierReturns(x.db);};

import * as E from '../src/purchase-extra-returns.mjs';
import {extraReturnSequence} from '../src/purchase-extra-return-ledger.mjs';
import {verifyExtraReturns} from '../src/purchase-extra-return-recovery.mjs';
async function extraBase(t,opts={}){const x=await setup(t,opts);good(await receipt(x,{received_quantity:4,bound_quantity:1}));return x;}
const ei=(x,over={})=>{const s=E.extraReturnSource(x.db,x.receipt.id);return {expected_sequence:extraReturnSequence(x.db,'a'),receipt_id:x.receipt.id,receipt_version_id:s.receipt_version.id,expected_receipt_sequence:R.receivingSequence(x.db,'a'),expected_receipt_return_revision:s.balance.receipt_return_revision,quantity:2,custody_confirmed_at:now(),custody_source:'人工实际核对超收原件身份数量和位置（虚构）',source_note:'原超收独立未入账来源（虚构）',return_basis:'明确人工退回依据（虚构）',destination_note:'虚构原供应方',contact_note:null,source_reference:'DEMO-EXTRA-RETURN',...notes,...over};};
async function ecreate(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-extra-returns',{...who,method:'POST',data:ei(x,over),key});if(z.status===201)x.e=z.body.record;return z;}
const eevent=(x,action,over={})=>{const e=E.extraReturnRecord(x.db,x.e.id);return {expected_sequence:extraReturnSequence(x.db,'a'),expected_revision:e.revision,expected_version:e.current_version,action,decision_basis:'真实人工商业决定（虚构）',...notes,...over};};
const eact=(x,action,over={},who=x.m,key=crypto.randomUUID())=>x.request('/api/purchase-extra-returns/'+x.e.id+'/events',{...who,method:'POST',data:eevent(x,action,over),key});
async function eapprove(x){good(await ecreate(x));good(await eact(x,'submit'));good(await eact(x,'approve'));}
const ehi=(x,over={})=>{const r=E.extraReturnRecord(x.db,x.e.id);return {expected_sequence:extraReturnSequence(x.db,'a'),expected_revision:r.revision,expected_version:r.current_version,expected_receipt_return_revision:r.source.balance.receipt_return_revision,expected_handed_quantity:r.balance.handed_quantity,quantity:1,handed_at:now(),collector_label:'虚构接收人',destination_note:'虚构实际地点',external_reference:null,source_identity:null,source_note:'可核对超收实际交出（虚构）',reason:notes.reason,next_step:notes.next_step,...over};};
async function ehand(x,over={},who=x.m,key=crypto.randomUUID()){const z=await x.request('/api/purchase-extra-returns/'+x.e.id+'/handoffs',{...who,method:'POST',data:ehi(x,over),key});if(z.status===201)x.eh=z.body.record.handoffs[0];return z;}
const eri=(x,over={})=>({expected_sequence:extraReturnSequence(x.db,'a'),quantity:1,received_at:now(),receiver_label:'虚构供应方收件人',external_reference:null,source_identity:null,source_note:'实际超收退回件的供应方收件（虚构）',reason:notes.reason,next_step:notes.next_step,...over});
const ereceive=(x,over={},who=x.f,key=crypto.randomUUID())=>x.request('/api/purchase-extra-handoffs/'+x.eh.id+'/receipts',{...who,method:'POST',data:eri(x,over),key});
const eVerify=x=>{verifyReceiving(x.db);verifyExtraReturns(x.db);};
test('unmatched actual handover and supplier receipt never debit posted SKU inventory or funds',async t=>{const x=await extraBase(t);good(await act(x,'quality_pass'));good(await act(x,'inbound'));const stock=physicalStock(x.db,x.product.id),before=x.db.prepare('SELECT * FROM inventory_events').all();await eapprove(x);good(await ehand(x));good(await ereceive(x));assert.deepEqual(physicalStock(x.db,x.product.id),stock);assert.deepEqual(x.db.prepare('SELECT * FROM inventory_events').all(),before);assert.equal(E.extraReturnRecord(x.db,x.e.id).source.balance.handed_quantity,1);assert.equal(x.db.prepare('SELECT count(*) n FROM supplier_return_handoffs').get().n,0);eVerify(x);});
test('unposted bound goods and completely unmatched actual arrival retain separate capacity from extra returns',async t=>{const x=await extraBase(t);await eapprove(x);good(await ehand(x,{quantity:2}));assert.equal(physicalStock(x.db,x.product.id).recorded,false);good(await act(x,'quality_pass'));good(await act(x,'inbound'));assert.equal(physicalStock(x.db,x.product.id).on_hand,1);eVerify(x);});
test('commercial claims cannot overbook original excess; stopping remaining arrangement preserves actual handed facts',async t=>{const x=await extraBase(t);await eapprove(x);assert.equal((await ecreate(x,{quantity:2})).status,409);good(await ehand(x));good(await eact(x,'stop_remaining'));assert.equal((await eact(x,'cancel')).status,409);assert.equal((await ehand(x)).status,409);const first=x.e.id;good(await ecreate(x,{quantity:2}));assert.equal(E.extraReturnRecord(x.db,first).balance.handed_quantity,1);eVerify(x);});
test('original receipt cancellation requires unhanded plans cancelled and remains blocked after any actual handover',async t=>{const x=await extraBase(t);await eapprove(x);assert.equal((await act(x,'cancel')).status,409);good(await eact(x,'cancel'));good(await act(x,'cancel'));eVerify(x);const y=await extraBase(t);await eapprove(y);good(await ehand(y));good(await eact(y,'stop_remaining'));assert.equal((await act(y,'cancel')).status,409);eVerify(y);});
test('metadata change blocks cached commercial approval; reopen explicitly adopts current receipt before future submit',async t=>{const x=await extraBase(t);good(await ecreate(x));good(await eact(x,'submit'));const data=eevent(x,'approve'),key='extra-source-cached';const post=()=>x.request('/api/purchase-extra-returns/'+x.e.id+'/events',{...x.m,method:'POST',data,key});good(await post());good(await revise(x,{...known,lot_code:'LATER-ORIGINAL-LOT'}));assert.equal((await post()).status,409);good(await eact(x,'reopen'));const r=E.extraReturnRecord(x.db,x.e.id),i=ei(x);for(const k of ['receipt_id','quantity','custody_confirmed_at','custody_source','source_note'])delete i[k];Object.assign(i,{expected_revision:r.revision,expected_version:r.current_version});good(await x.request('/api/purchase-extra-returns/'+x.e.id+'/versions',{...x.m,method:'POST',data:i}));good(await eact(x,'submit'));good(await eact(x,'approve'));eVerify(x);});
test('actual negative fact keeps original approved version after later receipt metadata change',async t=>{const x=await extraBase(t);await eapprove(x);const original=E.extraReturnRecord(x.db,x.e.id).current.id;good(await revise(x,{...known,lot_code:'AFTER-APPROVAL'}));good(await ehand(x));good(await ereceive(x));assert.equal(x.eh.approval_event_id,original);eVerify(x);});
test('actual quantities, approval time, handover time and supplier receipt capacity are enforced',async t=>{const x=await extraBase(t);await eapprove(x);for(const over of [{quantity:3},{handed_at:'2000-01-01T00:00:00.000Z'},{handed_at:new Date(Date.now()+60000).toISOString()},{expected_receipt_return_revision:3}])assert.ok([409,422].includes((await ehand(x,over)).status));good(await ehand(x));assert.equal((await ereceive(x,{quantity:2})).status,409);assert.equal((await ereceive(x,{received_at:'2000-01-01T00:00:00.000Z'})).status,409);good(await ereceive(x));assert.equal((await ereceive(x)).status,409);eVerify(x);});
test('manager arrangement and actual handover are separate from front supplier transcription; scope and guardian are denied',async t=>{const x=await extraBase(t);for(const who of [x.f,x.p,x.g])assert.equal((await ecreate(x,{},who)).status,403);await eapprove(x);assert.equal((await x.request('/api/purchase-extra-returns/'+x.e.id,x.o)).status,404);assert.equal((await ehand(x,{},x.f)).status,403);good(await ehand(x));assert.equal((await ereceive(x,{},x.p)).status,403);good(await ereceive(x));eVerify(x);});
test('known source identity and exact idempotency preserve a single actual fact; audit failure rolls all extra records and cache back',async t=>{const x=await extraBase(t);await eapprove(x);const data=ehi(x,{source_identity:'EXTRA-ONE'}),key='extra-hand-cache',post=()=>x.request('/api/purchase-extra-returns/'+x.e.id+'/handoffs',{...x.m,method:'POST',data,key});x.db.exec("CREATE TRIGGER extra_test_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test');END");assert.equal((await post()).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_extra_return_handoffs').get().n,0);x.db.exec('DROP TRIGGER extra_test_audit');const z=await post();good(z);x.eh=z.body.record.handoffs[0];good(await post());assert.equal((await ehand(x,{source_identity:'EXTRA-ONE'})).status,409);good(await ereceive(x,{source_identity:'SUPPLIER-ONE'}));eVerify(x);});
test('all six extra tables retain source contexts, independent quantities and originals through verified backup restoration',async t=>{const x=await extraBase(t,{persist:true});await eapprove(x);good(await ehand(x));good(await ereceive(x));const b=await createBackup(x.path,join(x.dir,'backup')),z=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(z.database);t.after(()=>d.close());for(const n of E.extraReturnTables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all());verifyExtraReturns(d);});
import {seedDemoExtraReturns} from '../src/demo-purchase-extra-returns.mjs';
test('native excess capacity and immutable six-table histories prevent bypasses and leave no orphan roots',async t=>{const x=await extraBase(t);assert.throws(()=>E.createExtraReturn(x.db,'a',ei(x,{quantity:4}),'manager'),/extra return/);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_extra_return_plans').get().n,0);await eapprove(x);assert.throws(()=>E.extraReturnHandoff(x.db,x.e.id,ehi(x,{quantity:3}),'manager'),/capacity/);good(await ehand(x));good(await ereceive(x));for(const n of E.extraReturnTables){const key=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+key+'='+key),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}assert.throws(()=>R.receivingEvent(x.db,x.receipt.id,eventInput(x,'cancel'),'manager'),/extra return/);eVerify(x);});
test('seven separately sourced synthetic excess stages preserve old rows, inventory and money and repeat unchanged',async t=>{const x=await setup(t);for(const[id,role]of [['demo-manager','manager'],['demo-front','reception']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');const tables=x.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),snapshot=()=>Object.fromEntries(tables.map(n=>[n,x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()])),before=snapshot();assert.deepEqual(seedDemoExtraReturns(x.db),{plans:7,handed:8,received:3});for(const n of tables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);assert.deepEqual(snapshot().inventory_events,before.inventory_events);eVerify(x);const after=snapshot();assert.deepEqual(seedDemoExtraReturns(x.db),{plans:0,handed:0,received:0});assert.deepEqual(snapshot(),after);});
test('same-millisecond receipt and commercial source captures reject substituted later or earlier prefixes',async t=>{const x=await extraBase(t);await eapprove(x);const at=now();E.extraReturnHandoff(x.db,x.e.id,{...ehi(x),handed_at:at},'manager',at);R.receiptVersion(x.db,x.receipt.id,{...known,lot_code:'SAME-MS'},'front',at);eVerify(x);const r=R.receiptRecord(x.db,x.receipt.id),name='purchase_receipt_extra_return_context_no_update',sql=x.db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(name).sql;x.db.exec('DROP TRIGGER '+name);x.db.prepare('UPDATE purchase_receipt_extra_return_context SET extra_sequence=0 WHERE receipt_event_id=?').run(r.current.id);x.db.exec(sql);assert.throws(()=>verifyExtraReturns(x.db),/前缀|顺序/);});
test('nonempty schema39 upgrades retain actual old receipts and only add empty excess ledgers with technical zero prefixes',async t=>{const dir=mkdtempSync(join(tmpdir(),'extra-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,39)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('manager','manager','manager',hashPassword('synthetic-only-password'),'manager','a');P.createSupplier(d,'a',supplier,'manager');const id='old-extra-product';d.prepare('INSERT INTO retail_products VALUES(?,?,?,?,?)').run(id,'a','OLD-EXTRA',now(),'manager');insertProductVersion(d,id,{name:'虚构旧实物',category:'lens',brand:null,specification:'旧规格',unit:'片',list_price_cents:100,status:'active',reason:'虚构'},'manager');const p=P.createPurchase(d,'a',{supplier_id:d.prepare('SELECT id FROM suppliers').get().id,supplier_version:1,title:'旧原采购',purpose_note:'虚构',source_note:'虚构',source_reference:'OLD',expected_date:null,items:[{product_id:id,product_version:1,quantity:1,unit_price_cents:100,note:null}],...notes},'manager');for(const action of ['submit','approve','order'])P.purchaseEvent(d,p.id,{action,decision_basis:'虚构旧实际来源',ordered_at:now(),order_reference:'OLD',...notes},'manager');const l=R.purchaseReceiptLines(d,p.id)[0];R.createReceipt(d,'a',{order_event_id:l.order_event_id,position:1,received_quantity:4,bound_quantity:1,received_at:now(),receiver_label:'旧实际收货人',delivery_reference:null,source_line_reference:null,receipt_source_note:'旧实际超收，不能补造今天保管',...metadata},'manager');const before=d.prepare('SELECT * FROM purchase_receipt_events').all();d.close();const u=openDatabase(path);t.after(()=>u.close());assert.deepEqual(u.prepare('SELECT * FROM purchase_receipt_events').all(),before);for(const n of E.extraReturnTables.slice(0,5))assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);assert.deepEqual(u.prepare('SELECT extra_sequence FROM purchase_receipt_extra_return_context').all().map(x=>x.extra_sequence),[0]);verifyExtraReturns(u);});
test('two concurrent actual handovers consume one original lease and cannot silently overdraw excess quantity',async t=>{const x=await extraBase(t);await eapprove(x);const data=ehi(x),post=()=>x.request('/api/purchase-extra-returns/'+x.e.id+'/handoffs',{...x.m,method:'POST',data});const z=await Promise.all([post(),post()]);assert.deepEqual(z.map(x=>x.status).sort(),[201,409]);assert.equal(E.extraReturnRecord(x.db,x.e.id).balance.handed_quantity,1);eVerify(x);});
test('unknown external source remains unknown; repeated external labels are not falsely treated as a unique fact',async t=>{const x=await extraBase(t);await eapprove(x);good(await ehand(x,{external_reference:'SAME-LABEL'}));good(await ehand(x,{external_reference:'SAME-LABEL'}));assert.equal(E.extraReturnRecord(x.db,x.e.id).handoff_total,2);assert.equal(x.eh.source_identity,null);const data=eri(x,{source_identity:'ACTUAL-SUPPLIER-ONE'}),key='extra-receipt-retry',post=()=>x.request('/api/purchase-extra-handoffs/'+x.eh.id+'/receipts',{...x.f,method:'POST',data,key});good(await post());good(await post());assert.equal((await x.request('/api/purchase-extra-handoffs/'+x.eh.id+'/receipts',{...x.f,method:'POST',data:{...data,quantity:2},key})).status,409);eVerify(x);});
test('commercial history retains all 37 immutable versions with bounded stable continuation and explicit old metadata',async t=>{const x=await extraBase(t);good(await ecreate(x));for(let j=0;j<36;j++){const r=E.extraReturnRecord(x.db,x.e.id),data=ei(x);for(const k of ['receipt_id','quantity','custody_confirmed_at','custody_source','source_note'])delete data[k];Object.assign(data,{expected_revision:r.revision,expected_version:r.current_version});good(await x.request('/api/purchase-extra-returns/'+r.id+'/versions',{...x.m,method:'POST',data}));}const z=await x.request('/api/purchase-extra-returns/'+x.e.id,x.m);assert.equal(z.body.record.total,37);assert.equal(z.body.record.history.length,30);assert.equal((await x.request('/api/purchase-extra-returns/'+x.e.id+'?offset=30',x.m)).status,409);const p=await x.request('/api/purchase-extra-returns/'+x.e.id+'?offset=30&expected_sequence='+z.body.sequence,x.m);assert.equal(p.body.record.history.length,7);assert.equal((await x.request('/api/purchase-extra-returns/'+x.e.id+'?version=1',x.m)).body.record.version,1);eVerify(x);});
test('completely unmatched arrival is separately returned without a SKU ledger while zero-extra receipt rejects arrangement',async t=>{const x=await setup(t);good(await receipt(x,{received_quantity:3,bound_quantity:0}));await eapprove(x);good(await ehand(x,{quantity:2}));assert.equal(physicalStock(x.db,x.product.id).recorded,false);assert.equal(E.extraReturnRecord(x.db,x.e.id).source.current_extra_custody_quantity,null);eVerify(x);const y=await setup(t);good(await receipt(y,{received_quantity:1,bound_quantity:1}));assert.equal((await ecreate(y)).status,409);});
async function pausedExtra(x,data,change){const payload=JSON.stringify(data),req=httpRequest(x.origin+'/api/purchase-extra-returns',{method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}}),done=new Promise((resolve,reject)=>{req.on('error',reject);req.on('response',r=>{let s='';r.on('data',x=>s+=x);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(s)}));});});req.write(payload.slice(0,12));await new Promise(resolve=>setTimeout(resolve,60));await change();req.end(payload.slice(12));return done;}
test('current staff role and password-reset status are rechecked after a paused request body without saving records',async t=>{const x=await extraBase(t);let z=await pausedExtra(x,ei(x),()=>x.db.exec("UPDATE users SET role='reception' WHERE id='manager'"));assert.equal(z.status,401);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_extra_return_plans').get().n,0);x.db.exec("UPDATE users SET role='manager' WHERE id='manager'");z=await pausedExtra(x,ei(x),()=>x.db.prepare('INSERT INTO user_security(user_id,must_change_password) VALUES(?,1)').run('manager'));assert.equal(z.status,403);assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_extra_return_plans').get().n,0);});
test('original receipt source is checked after a paused create body and invalid dates, quantities or invented fields are rejected',async t=>{const x=await extraBase(t),data=ei(x);const z=await pausedExtra(x,data,()=>revise(x,{...known,lot_code:'DURING-BODY'}));assert.equal(z.status,409);for(const over of [{quantity:0},{quantity:1.5},{custody_confirmed_at:'bad'},{refund_cents:100},{custody_confirmed_at:'2000-01-01T00:00:00.000Z'}])assert.ok([409,422].includes((await ecreate(x,over)).status));assert.equal(x.db.prepare('SELECT count(*) n FROM purchase_extra_return_plans').get().n,0);});
