import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as R from '../src/referrals.mjs';
import {verifyReferrals} from '../src/referral-recovery.mjs';
const now=()=>new Date().toISOString(),later=()=>new Date(Date.now()+86400000).toISOString(),manual=()=>({kind:'manual',id:null,version:null,revision:null}),note=()=>({note:'明确人工登记（虚构）',reason:'验证实际来源'});
const recordInput=()=>({kind:'external_report',title:'外院报告（虚构）',institution:'虚构外院',reported_at:new Date(Date.now()-1000).toISOString(),measured_at:new Date(Date.now()-60000).toISOString(),eye:'both',condition_status:'unknown',condition_note:'单位和测量条件未齐全，保留未知',source_note:'家长提交原文，不是本店测量',record_note:'虚构报告原文，不生成诊断',attachment_ids:[],document_ids:[],...note()});
const caseInput=()=>({title:'外院转介（虚构）',reason_note:'原检查需进一步确认',destination:'待明确外院安排',arrangement_note:'尚待专业确认',due_at:later(),next_action:'由明确责任人继续安排',...note()});
async function setup(t,opts){const x=await fixture(t,opts);return {...x,m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')};}
const sequence=x=>R.referralSequence(x.db,'a');
async function post(x,path,u,data,key){return x.request('/api/referrals/'+path,{...u,method:'POST',data:{expected_sequence:sequence(x),...data},...(key?{key}:{})});}
async function record(x,extra={},u=x.f){const r=await post(x,'records',u,{customer_id:'one',owner_id:'professional',...recordInput(),...extra});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.record;}
async function re(x,r,action,extra={},u=action==='assign'?x.m:x.p){const old=R.externalRecord(x.db,r.id),b={expected_revision:old.revision,expected_version:old.current_version,action,...note(),...(action!=='assign'?{opinion_note:'仅确认原文来源与限制（虚构）',next_step:'按实际业务安排'}:{}),...extra},z=await post(x,'records/'+r.id+'/events',u,b);assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function rv(x,r,extra={},u=x.p){const old=R.externalRecord(x.db,r.id),z=await post(x,'records/'+r.id+'/versions',u,{expected_revision:old.revision,expected_version:old.current_version,...recordInput(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function referral(x,extra={},u=x.f){const z=await post(x,'cases',u,{customer_id:'one',source:manual(),source_note:'明确人工转介意向',professional_owner_id:'professional',contact_owner_id:'front',...caseInput(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function ce(x,c,action,extra={},u=['arrange','complete'].includes(action)?x.p:action==='assign'?x.m:x.f){const old=R.referralCase(x.db,c.id),i={expected_revision:old.revision,action,...note(),...(action==='assign'?{professional_owner_id:old.professional_owner_id,contact_owner_id:old.contact_owner_id}:{due_at:later(),next_action:'明确下一步'}),...(['revise','arrange'].includes(action)?caseInput():{}),...(['arrange','reschedule'].includes(action)?{scheduled_for:later()}:{}),...(['complete','cancel'].includes(action)?{outcome_note:'保留实际结果（虚构）',next_step:'明确后续'}:{}),...(action==='complete'?{outcome_kind:'no_result',result:null}:{}),...extra},z=await post(x,'cases/'+c.id+'/events',u,i);assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
const snapshot=db=>Object.fromEntries(R.referralTables.map(n=>[n,db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
test('outside data, customer report and unable-to-measure remain pending and do not overwrite local observations',async t=>{const x=await setup(t);for(const kind of ['external_report','customer_report','unable_to_measure']){const r=await record(x,{kind,measured_at:kind==='unable_to_measure'?null:recordInput().measured_at});assert.equal(r.status,'pending');assert.equal(r.confirmation,null);}assert.equal(x.db.prepare('SELECT count(*) n FROM longitudinal_observations').get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM document_versions').get().n,0);verifyReferrals(x.db);});
test('only assigned professional confirms; manager and reception cannot supply an opinion',async t=>{const x=await setup(t),r=await record(x);for(const u of [x.f,x.m])assert.equal((await post(x,'records/'+r.id+'/events',u,{expected_revision:r.revision,expected_version:r.version,action:'confirm',opinion_note:'意见',next_step:'后续',...note()})).status,403);const c=await re(x,r,'confirm');assert.equal(c.status,'confirmed');assert.equal(c.confirmation.created_by,'professional');verifyReferrals(x.db);});
test('correcting an outside source adds a version, resets pending and preserves original professional confirmation',async t=>{const x=await setup(t),r=await record(x);await re(x,r,'confirm');const v=await rv(x,r,{record_note:'外院新原文（虚构）'});assert.equal(v.current_version,2);assert.equal(v.status,'pending');assert.equal(v.confirmation,null);const old=R.externalRecord(x.db,r.id,{version:1});assert.equal(old.record_note,'虚构报告原文，不生成诊断');assert.equal(old.version_status,'confirmed');assert.equal(old.confirmation.version,1);await re(x,v,'reject',{opinion_note:'原文条件不足，暂不采纳'});verifyReferrals(x.db);});
test('administrative reassignment preserves actual original confirmer and keeps professional ownership explicit',async t=>{const x=await setup(t);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('pro-two','pro-two','pro-two',hashPassword('synthetic-only-password'),'professional','a');const r=await record(x);await re(x,r,'confirm');const z=await re(x,r,'assign',{owner_id:'pro-two'});assert.equal(z.owner_id,'pro-two');assert.equal(z.confirmation.created_by,'professional');assert.equal(z.status,'confirmed');assert.equal((await post(x,'records/'+r.id+'/events',x.p,{expected_revision:z.revision,expected_version:z.version,action:'reject',opinion_note:'不采纳',next_step:'后续',...note()})).status,403);verifyReferrals(x.db);});
test('attachments and fixed document versions require same customer and live access',async t=>{const x=await setup(t);const b=Buffer.from('synthetic outside report'),id='outside-file';x.db.prepare('INSERT INTO attachment_blobs VALUES(?,?,?)').run('hash',b,b.length);x.db.prepare('INSERT INTO attachments(id,customer_id,filename,content_type,blob_sha256,size,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,'one','outside.txt','text/plain','hash',b.length,now(),'front');const r=await record(x,{attachment_ids:[id]});assert.deepEqual(r.attachment_ids,[id]);assert.equal((await post(x,'records',x.f,{customer_id:'two',owner_id:'professional',...recordInput(),attachment_ids:[id]})).status,409);x.db.prepare('UPDATE attachments SET revoked_at=?,revoked_by=?,revocation_reason=? WHERE id=?').run(now(),'manager','撤回',id);assert.equal((await post(x,'records/'+r.id+'/events',x.p,{expected_revision:r.revision,expected_version:r.version,action:'confirm',opinion_note:'确认',next_step:'后续',...note()})).status,409);verifyReferrals(x.db);});
test('confirmed source keeps exact version and cannot use pending, rejected, another customer or stale source',async t=>{const x=await setup(t),r=await record(x),s={kind:'external',id:r.id,version:1,revision:1};assert.equal((await post(x,'cases',x.f,{customer_id:'one',source:s,source_note:'来源',professional_owner_id:'professional',contact_owner_id:'front',...caseInput()})).status,409);const z=await re(x,r,'confirm');s.revision=z.revision;const c=await referral(x,{source:s});assert.deepEqual(c.source,s);await rv(x,r);assert.equal(R.referralCase(x.db,c.id).source.version,1);assert.equal((await post(x,'cases',x.f,{customer_id:'one',source:s,source_note:'来源',professional_owner_id:'professional',contact_owner_id:'front',...caseInput()})).status,409);verifyReferrals(x.db);});
test('professional arrangement and contact responsibility are separate; rescheduling preserves original content',async t=>{const x=await setup(t),c=await referral(x);assert.equal(c.status,'draft');const bad=await post(x,'cases/'+c.id+'/events',x.m,{expected_revision:c.revision,action:'arrange',scheduled_for:later(),...caseInput()});assert.equal(bad.status,403);const a=await ce(x,c,'arrange',{destination:'虚构外院A',arrangement_note:'明确人工安排'}),b=await ce(x,a,'reschedule',{scheduled_for:new Date(Date.now()+172800000).toISOString()});assert.equal(b.status,'arranged');assert.equal(b.destination,a.destination);assert.equal(b.history[1].scheduled_for,a.scheduled_for);assert.notEqual(b.scheduled_for,a.scheduled_for);verifyReferrals(x.db);});
test('defer and explicit no-result completion retain uncertainty and required next step',async t=>{const x=await setup(t),c=await referral(x);await ce(x,c,'arrange');const d=await ce(x,c,'defer',{next_action:'客户明确延期，责任人继续跟踪'});assert.equal(d.status,'waiting');const end=await ce(x,c,'complete');assert.equal(end.outcome_kind,'no_result');assert.equal(end.result_record_id,null);assert.equal(x.db.prepare('SELECT count(*) n FROM external_records').get().n,0);verifyReferrals(x.db);});
test('result completion requires current confirmed exact version and retains it after a later correction',async t=>{const x=await setup(t),r=await record(x),c=await referral(x);await ce(x,c,'arrange');let old=R.referralCase(x.db,c.id);assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:old.revision,action:'complete',due_at:later(),next_action:'后续',outcome_note:'结果',next_step:'后续',outcome_kind:'result_received',result:{id:r.id,version:1,revision:1},...note()})).status,409);const z=await re(x,r,'confirm');const end=await ce(x,c,'complete',{outcome_kind:'result_received',result:{id:z.id,version:z.version,revision:z.revision}});await rv(x,r);assert.equal(R.referralCase(x.db,end.id).result_version,1);verifyReferrals(x.db);});
test('unable-to-measure completion never produces a result or a local clinical value',async t=>{const x=await setup(t),c=await referral(x);await ce(x,c,'arrange');const z=await ce(x,c,'complete',{outcome_kind:'unable_to_measure',result:null,outcome_note:'无法测，待后续安排'});assert.equal(z.outcome_kind,'unable_to_measure');assert.equal(x.db.prepare('SELECT count(*) n FROM longitudinal_observation_versions').get().n,0);verifyReferrals(x.db);});
test('terminal referral cannot be silently reopened or receive later contact links',async t=>{const x=await setup(t),c=await referral(x);const z=await ce(x,c,'cancel');assert.equal(z.status,'cancelled');assert.equal((await post(x,'cases/'+c.id+'/events',x.f,{expected_revision:z.revision,action:'reschedule',scheduled_for:later(),due_at:later(),next_action:'后续',...note()})).status,409);verifyReferrals(x.db);});
test('reception cannot rewrite professional arrangement destination through a reschedule',async t=>{const x=await setup(t),c=await referral(x);const z=await ce(x,c,'arrange');assert.equal((await post(x,'cases/'+c.id+'/events',x.f,{expected_revision:z.revision,action:'reschedule',scheduled_for:later(),destination:'替换目标',due_at:later(),next_action:'后续',...note()})).status,422);assert.equal(R.referralCase(x.db,c.id).revision,z.revision);});
test('store, guardian and customer scoping blocks records, lists, histories and write options',async t=>{const x=await setup(t),r=await record(x);for(const path of ['records','cases','records/'+r.id,'customers/one/options'])assert.equal((await x.request('/api/referrals/'+path,x.g)).status,403);assert.equal((await x.request('/api/referrals/records/'+r.id,x.o)).status,404);assert.equal((await x.request('/api/referrals/customers/other-child/options',x.f)).status,404);assert.equal((await x.request('/api/referrals/records')).status,401);});
test('strict fields reject invented diagnoses, future actuals, missing source and fake measurement',async t=>{const x=await setup(t),b={customer_id:'one',owner_id:'professional',...recordInput()};for(const patch of [{diagnosis:'自动结论'},{reported_at:later()},{measured_at:later()},{kind:'unable_to_measure',measured_at:b.measured_at},{attachment_ids:['x','x']},{eye:'clinical-default'},{condition_status:'automatic'}])assert.equal((await post(x,'records',x.f,{...b,...patch})).status,422);assert.equal((await post(x,'cases',x.f,{customer_id:'one',source:{kind:'manual',id:'x',version:null,revision:null},source_note:'来源',professional_owner_id:'professional',contact_owner_id:'front',...caseInput()})).status,422);});
test('sequence, record version and referral revision conflicts keep one current fact',async t=>{const x=await setup(t),r=await record(x),seq=sequence(x);await re(x,r,'confirm');assert.equal((await post(x,'records/'+r.id+'/events',x.p,{expected_sequence:seq,expected_revision:r.revision,expected_version:1,action:'reject',opinion_note:'意见',next_step:'后续',...note()})).status,409);assert.equal((await post(x,'records/'+r.id+'/versions',x.p,{expected_revision:r.revision,expected_version:1,...recordInput()})).status,409);assert.equal(R.externalRecord(x.db,r.id).version,1);});
test('audit failure rolls back root, version, paired event, sequence and idempotency',async t=>{const x=await setup(t),b={customer_id:'one',owner_id:'professional',...recordInput()},before=snapshot(x.db);x.db.exec("CREATE TRIGGER fail_referral_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'referral.%' BEGIN SELECT RAISE(ABORT,'forced'); END");assert.equal((await post(x,'records',x.f,b,'rollback')).status,500);assert.deepEqual(snapshot(x.db),before);x.db.exec('DROP TRIGGER fail_referral_audit');assert.equal((await post(x,'records',x.f,b,'rollback')).status,201);verifyReferrals(x.db);});
test('idempotency preserves one version and withdrawal of session blocks cached retry',async t=>{const x=await setup(t),b={expected_sequence:sequence(x),customer_id:'one',owner_id:'professional',...recordInput()},z=await post(x,'records',x.f,b,'referral-same');assert.equal(z.status,201);assert.equal((await post(x,'records',x.f,b,'referral-same')).body.record.id,z.body.record.id);x.db.prepare('DELETE FROM sessions WHERE user_id=?').run('front');assert.equal((await post(x,'records',x.f,b,'referral-same')).status,401);verifyReferrals(x.db);});
test('full bounded paging covers more than thirty records and rejects changed second page',async t=>{const x=await setup(t);x.db.exec('BEGIN');for(let i=0;i<33;i++)R.createExternalRecord(x.db,'a','one',{...recordInput(),owner_id:'professional'},'front');x.db.exec('COMMIT');const a=(await x.request('/api/referrals/records?limit=30',x.f)).body;assert.equal(a.total,33);assert.equal(a.next_offset,30);const b=(await x.request('/api/referrals/records?limit=30&offset=30&expected_sequence='+a.sequence,x.f)).body;assert.equal(b.items.length,3);await record(x);assert.equal((await x.request('/api/referrals/records?offset=30&expected_sequence='+a.sequence,x.f)).status,409);verifyReferrals(x.db);});
test('native guards prevent administrative clinical confirmation and immutable history changes',async t=>{const x=await setup(t),r=await record(x);assert.throws(()=>R.externalRecordEvent(x.db,r.id,{action:'confirm',opinion_note:'意见',next_step:'后续',...note()},'manager'));assert.throws(()=>x.db.prepare('UPDATE external_record_versions SET record_note=? WHERE record_id=?').run('篡改',r.id));assert.throws(()=>x.db.prepare('DELETE FROM external_records WHERE id=?').run(r.id));verifyReferrals(x.db);});
test('recovery rejects replacing original source version or confirmed result with a later same-millisecond revision',async t=>{const x=await setup(t),r=await record(x);await re(x,r,'confirm');const c=await referral(x,{source:{kind:'external',id:r.id,version:1,revision:2}});await rv(x,r);x.db.exec('DROP TRIGGER referral_cases_no_update');x.db.prepare('UPDATE referral_cases SET source_version=2,source_revision=3 WHERE id=?').run(c.id);assert.throws(()=>verifyReferrals(x.db),/来源|确认/);});
test('nonempty schema29 migration preserves previous rows and creates no outside confirmation or referral',t=>{const dir=mkdtempSync(join(tmpdir(),'referral-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,29)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('old','old')");d.close();const u=openDatabase(path);assert.equal(u.prepare('SELECT count(*) n FROM stores').get().n,1);for(const n of R.referralTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifyReferrals(u);u.close();});
test('schema30 independent backup and restore preserve every outside/referral version and clear sessions',async t=>{const x=await setup(t,{persist:true}),r=await record(x);await re(x,r,'confirm');const c=await referral(x);await ce(x,c,'arrange');await ce(x,c,'complete',{outcome_kind:'result_received',result:{id:r.id,version:1,revision:2}});const a=snapshot(x.db),b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,34);const z=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(z.database);assert.deepEqual(snapshot(d),a);assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyReferrals(d);d.close();});
import * as C from '../src/contact.mjs';
import {seedDemoScenarios} from '../src/demo-data.mjs';
import {seedDemoContact} from '../src/demo-contact.mjs';
import {seedDemoReferrals} from '../src/demo-referrals.mjs';
function actualContact(x,customer='one'){const at=now(),grant=C.createContactConsent(x.db,'a',customer,{category:'service',channel:'phone',recipient_label:'虚构接收人',address:'synthetic-contact-only',source_note:'明确演示授权',effective_at:new Date(Date.now()-60000).toISOString(),...note()},'front',at),c=C.createContactCase(x.db,'a',customer,{purpose:'other_service',source:manual(),source_note:'虚构服务联系',owner_id:'front',title:'转介联系（虚构）',purpose_note:'仅明确联系目的',due_at:later(),next_action:'人工跟进',...note()},'front',at),a=C.recordContactAttempt(x.db,c.id,{consent_id:grant.id,consent_revision:grant.revision,occurred_at:new Date(Date.now()-1000).toISOString(),result:'no_answer',source_note:'人工实际登记',content_summary:'虚构联系',result_note:'无人接听',due_at:later(),next_action:'人工接管',reason:'实际依据'},'front',at);return {a,c,at};}
test('failed actual contact, optional receipt and appointment link without finishing clinical referral',async t=>{const x=await setup(t),c=await referral(x),{a}=actualContact(x),receipt=C.recordContactReceipt(x.db,a.id,{status:'unknown',source:'staff_transcript',occurred_at:now(),source_note:'原实际回执',result_note:'状态未知',reason:'保留未知'},'front'),appointment=C.createCustomerAppointment(x.db,a.case_id,{starts_at:later(),ends_at:new Date(Date.now()+90000000).toISOString(),purpose_note:'明确意向',place_note:'虚构地点',source_note:'客户明确意向',owner_id:'front',...note()},'front');const z=await post(x,'cases/'+c.id+'/contacts',x.f,{expected_revision:c.revision,attempt_id:a.id,receipt_id:receipt.receipt.id,appointment:{id:appointment.id,revision:1},source_note:'关联原实际记录',result_note:'未接通，非已读或到店',due_at:later(),next_action:'明确责任人跟进',reason:'实际关联'});assert.equal(z.status,201,JSON.stringify(z.body));assert.equal(R.referralCase(x.db,c.id).status,'draft');assert.equal(R.referralCase(x.db,c.id).revision,1);verifyReferrals(x.db);});
test('contact linking rejects cross-customer or unrelated receipt/appointment and duplicate actuals',async t=>{const x=await setup(t),c=await referral(x),{a}=actualContact(x,'two'),b={expected_revision:c.revision,attempt_id:a.id,receipt_id:null,appointment:null,source_note:'原联系',result_note:'未接通',due_at:later(),next_action:'后续',reason:'关联'};assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,b)).status,409);const own=actualContact(x);b.attempt_id=own.a.id;assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,{...b,receipt_id:'missing'})).status,409);assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,b)).status,201);assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,b)).status,409);verifyReferrals(x.db);});
test('historical recorded contact remains linkable after consent withdrawal without restoring authorization',async t=>{const x=await setup(t),c=await referral(x),{a}=actualContact(x);C.contactConsentEvent(x.db,a.consent_id,{action:'revoke',...note()},'front');assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,{expected_revision:c.revision,attempt_id:a.id,receipt_id:null,appointment:null,source_note:'历史实际联系',result_note:'撤回前实际无应答',due_at:later(),next_action:'不再联系，内部明确后续',reason:'关联实际历史'})).status,201);assert.equal(C.contactConsent(x.db,a.consent_id).status,'revoked');verifyReferrals(x.db);});
test('professional handoff during request body wait rejects old owner confirmation and cached replay',async t=>{const x=await setup(t),r=await record(x);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('pro-two','pro-two','pro-two',hashPassword('synthetic-only-password'),'professional','a');const b={expected_sequence:sequence(x),expected_revision:r.revision,expected_version:r.version,action:'confirm',opinion_note:'实际意见',next_step:'明确安排',...note()},path='/api/referrals/records/'+r.id+'/events',key='pending-referral-replay';assert.equal((await x.request(path,{...x.p,method:'POST',data:b,key})).status,201);const data=JSON.stringify(b),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.p.cookie,'X-CSRF-Token':x.p.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{R.externalRecordEvent(x.db,r.id,{action:'assign',owner_id:'pro-two',...note()},'manager');req.end(data.slice(10));},20);});assert.equal(status,403);assert.equal(R.externalRecord(x.db,r.id).confirmation.created_by,'professional');verifyReferrals(x.db);});
test('timeline exposes separate outside confirmation, referral and actual contact links within internal scope',async t=>{const x=await setup(t),r=await record(x),c=await referral(x);await re(x,r,'confirm');const {a}=actualContact(x);await post(x,'cases/'+c.id+'/contacts',x.f,{expected_revision:c.revision,attempt_id:a.id,receipt_id:null,appointment:null,source_note:'原实际联系',result_note:'未接通',due_at:later(),next_action:'明确后续',reason:'关联'});const z=await x.request('/api/customers/one/timeline',x.f);assert.equal(z.status,200);for(const kind of ['external_record','referral','referral_contact'])assert.ok(z.body.items.some(e=>e.kind===kind));assert.equal((await x.request('/api/customers/one/timeline',x.g)).status,403);});
test('staged synthetic outside/referral cases append once and preserve all previous local business',async t=>{const x=await setup(t),d=x.db;d.exec("INSERT INTO stores VALUES('store-a','演示')");for(const [id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');seedDemoScenarios(d);seedDemoContact(d);const names=['customers','service_cycles','cycle_versions','visits','document_versions','contact_cases','contact_attempts'],before=names.map(n=>d.prepare('SELECT * FROM '+n).all());assert.deepEqual(seedDemoReferrals(d),{records:4,cases:4});assert.deepEqual(names.map(n=>d.prepare('SELECT * FROM '+n).all()),before);const a=snapshot(d);assert.deepEqual(seedDemoReferrals(d),{records:0,cases:0});assert.deepEqual(snapshot(d),a);verifyReferrals(d);});
import {seedDemoRetail,seedDemoInventory,seedDemoPayments,seedDemoProcessing,seedDemoFulfillment,seedDemoAftercare,seedDemoAftercareWork,seedDemoReplacements,seedDemoDispositions,seedDemoRefunds,seedDemoParameters,seedDemoTraining} from '../src/demo-data.mjs';
import {seedDemoEntitlements} from '../src/demo-entitlements.mjs';
import {seedDemoScheduling} from '../src/demo-scheduling.mjs';
import {seedDemoFamilyTraining} from '../src/demo-family-training.mjs';
import {seedDemoLongitudinal} from '../src/demo-longitudinal.mjs';
test('longitudinal, observation, aftercare and actual-course sources retain captured cycle identity and reject substituted versions',async t=>{const x=await setup(t),d=x.db;d.exec("INSERT INTO stores VALUES('store-a','演示')");for(const [id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional'],['demo-practice-parent','guardian']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,role==='guardian'?null:'store-a');for(const fn of [seedDemoScenarios,seedDemoRetail,seedDemoInventory,seedDemoPayments,seedDemoProcessing,seedDemoFulfillment,seedDemoAftercare,seedDemoAftercareWork,seedDemoReplacements,seedDemoDispositions,seedDemoRefunds,seedDemoParameters,seedDemoTraining,seedDemoEntitlements,seedDemoScheduling,seedDemoFamilyTraining,seedDemoLongitudinal])fn(d);for(const kind of ['longitudinal','observation','aftercare','training_session']){const s=d.prepare('SELECT * FROM referral_sources WHERE kind=? ORDER BY id LIMIT 1').get(kind);assert.ok(s,kind);const source={kind,id:s.id,version:s.version,revision:s.revision},r=R.createReferralCase(d,'store-a',s.customer_id,{...caseInput(),source,source_note:'原业务固定来源',professional_owner_id:'demo-professional',contact_owner_id:'demo-front'},'demo-front');assert.equal(r.cycle_id,s.cycle_id);assert.equal(r.cycle_version,s.cycle_version);assert.equal(R.referralSource(d,'store-a',s.customer_id,{...source,...(source.version?{version:source.version+100}:{revision:source.revision+100})}),null);}verifyReferrals(d);});
test('contact-link audit failure leaves no link or sequence and retry commits exactly one actual source',async t=>{const x=await setup(t),c=await referral(x),{a}=actualContact(x),b={expected_sequence:sequence(x),expected_revision:c.revision,attempt_id:a.id,receipt_id:null,appointment:null,source_note:'实际来源',result_note:'未接通',due_at:later(),next_action:'跟踪',reason:'明确关联'},before=snapshot(x.db);x.db.exec("CREATE TRIGGER fail_link BEFORE INSERT ON audit_events WHEN NEW.action='referral.contact.link' BEGIN SELECT RAISE(ABORT,'forced'); END");assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,b,'referral-link-retry')).status,500);assert.deepEqual(snapshot(x.db),before);x.db.exec('DROP TRIGGER fail_link');assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,b,'referral-link-retry')).status,201);assert.equal((await post(x,'cases/'+c.id+'/contacts',x.f,b,'referral-link-retry')).status,201);assert.equal(R.referralCase(x.db,c.id).contact_total,1);verifyReferrals(x.db);});
