import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
import {paymentTables,orderPayments,verifyPayments,insertPayment} from '../src/payments.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
async function product(request,m,extra={}){const r=await request('/api/retail/products',{...m,method:'POST',data:{sku:'SKU-'+crypto.randomUUID().slice(0,8),name:'虚构镜架',category:'frame',brand:null,specification:'虚构型号',unit:'副',list_price_cents:19900,status:'active',reason:'虚构目录',...extra}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.product;}
async function order(request,m,items){const r=await request('/api/customers/one/retail-orders',{...m,method:'POST',data:{title:'库存订单（虚构）',notes:null,items:items.map(x=>({product_id:x.id,product_version:x.version,quantity:x.quantity||1,unit_price_cents:100,note:null})),reason:'虚构开单'}});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.order;}
async function stock(request,m,p,action='receive',quantity=10,extra={},key=crypto.randomUUID()){const current=(await request('/api/inventory/products/'+p.id,m)).body;return request('/api/inventory/products/'+p.id+'/events',{...m,method:'POST',key,data:{expected_product_version:current.product?.version||p.version,expected_sequence:current.stock?.sequence||0,action,quantity,reason:'虚构库存操作',...extra}});}
async function inventory(request,m,id){const r=await request('/api/retail/orders/'+id+'/inventory',m);assert.equal(r.status,200);return r.body.inventory;}
function postReservation(request,m,state,action='reserve',extra={},key=crypto.randomUUID()){return request('/api/retail/orders/'+state.order_id+'/inventory/'+action,{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,reason:'虚构'+action,...(action==='reserve'?{stock_versions:state.stock_versions}:{}),...extra}});}
function revise(request,m,o,extra={}){return request('/api/retail/orders/'+o.id+'/versions',{...m,method:'POST',data:{expected_version:o.version,title:o.title,notes:'虚构修订说明',items:o.items.map(({product_id,product_version,quantity,unit_price_cents,note})=>({product_id,product_version,quantity,unit_price_cents,note})),document_version_ids:[],attachment_ids:[],reason:'虚构修订',...extra}});}

async function payments(request,m,id){const r=await request('/api/retail/orders/'+id+'/payments',m);assert.equal(r.status,200,JSON.stringify(r.body));return r.body.payments;}
async function receive(request,m,id,extra={},key=crypto.randomUUID()){const state=await payments(request,m,id);return request('/api/retail/orders/'+id+'/payments/receive',{...m,method:'POST',key,data:{expected_order_version:state.order_version,expected_revision:state.revision,amount_cents:33,method:'cash',reference:null,received_at:'2025-01-01T10:00:00.000Z',reason:'虚构实际收款登记',...extra}});}
async function voidReceipt(request,m,id,source,extra={},key=crypto.randomUUID()){const s=await payments(request,m,id);return request('/api/retail/orders/'+id+'/payments/void',{...m,method:'POST',key,data:{expected_order_version:s.order_version,expected_revision:s.revision,source_id:source,reason:'虚构未发生金额误登记，纠正记录',...extra}});}
import {refundRecord,refundSources,insertRefundEvent,verifyRefunds} from '../src/refunds.mjs';import {refundSequence} from '../src/refund-ledger.mjs';
async function setup(t,amount=100,options={}){const x=await fixture(t,options),m=await x.login('manager'),p=await product(x.request,m),o=await order(x.request,m,[p]),r=await receive(x.request,m,o.id,{amount_cents:amount});assert.equal(r.status,201);return {...x,m,o,receipt:r.body.event};}
function intent(x,extra={}){const p=orderPayments(x.db,x.o.id);return {expected_order_version:p.order_version,expected_payment_revision:p.revision,expected_sequence:p.refund_sequence,expected_case_revision:null,receipt_id:x.receipt.id,amount_cents:20,case_id:null,decision_basis:'明确本次人工退款依据（虚构）',note:'本次退款记录（虚构）',reason:'本次原实收核对（虚构）',...extra};}
async function propose(x,s=x.m,extra={},key){return x.request('/api/retail/orders/'+x.o.id+'/refunds',{...s,method:'POST',data:intent(x,extra),key});}
async function act(x,id,action,s=x.m,extra={},key){const p=orderPayments(x.db,x.o.id),r=refundRecord(x.db,id),c=r.case_id?x.db.prepare('SELECT max(revision) n FROM aftercare_events WHERE case_id=?').get(r.case_id).n:null;return x.request('/api/refunds/'+id+'/events',{...s,method:'POST',key,data:{expected_order_version:p.order_version,expected_payment_revision:p.revision,expected_sequence:p.refund_sequence,expected_case_revision:c,expected_revision:r.revision,action,note:'明确退款动作（虚构）',reason:'本次审核及凭据（虚构）',...(action==='execute'?{method:'transfer',reference:'SYNTHETIC-PAYOUT-'+crypto.randomUUID(),receiver_name:'实际接收人（虚构）',refunded_at:new Date().toISOString(),receipt_note:'实际退款记录（虚构）'}:{}),...extra}});}
const verify=x=>{verifyPayments(x.db);verifyRefunds(x.db);verifyInventory(x.db);};
test('manual proposal, manager approval and actual refund retain gross receipts and debit only separate refund projection',async t=>{const x=await setup(t),f=await x.login('front'),tables=['payment_events','retail_order_versions','inventory_events','inventory_outbounds','aftercare_events'],old=tables.map(n=>x.db.prepare('SELECT * FROM '+n).all());const p=await propose(x,f);assert.equal(p.status,201,JSON.stringify(p));const id=p.body.refund.id;assert.deepEqual([p.body.payments.recorded_cents,p.body.payments.refunded_cents,p.body.payments.reserved_refund_cents,p.body.payments.retained_cents],[100,0,20,100]);assert.equal((await act(x,id,'approve',f)).status,403);assert.equal((await act(x,id,'execute',f)).status,409);assert.equal((await act(x,id,'approve')).status,201);assert.equal(orderPayments(x.db,x.o.id).refunded_cents,0);assert.equal((await act(x,id,'execute',f)).status,201);const s=orderPayments(x.db,x.o.id);assert.deepEqual([s.recorded_cents,s.refunded_cents,s.reserved_refund_cents,s.retained_cents],[100,20,0,80]);tables.forEach((n,i)=>assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),old[i]));verify(x);});
test('receipt cap includes pending, approved and paid amounts; reject/cancel release reservations without changing net money',async t=>{const x=await setup(t,33);const p=(await propose(x,x.m,{amount_cents:20})).body.refund;assert.equal((await propose(x,x.m,{amount_cents:14})).body.error.code,'REFUND_AMOUNT');await act(x,p.id,'reject');assert.equal(refundSources(x.db,x.o.id)[0].available_refund_cents,33);const q=(await propose(x,x.m,{amount_cents:33})).body.refund;await act(x,q.id,'approve');await act(x,q.id,'cancel');assert.equal(orderPayments(x.db,x.o.id).retained_cents,33);const r=(await propose(x,x.m,{amount_cents:33})).body.refund;await act(x,r.id,'approve');await act(x,r.id,'execute');assert.equal(refundSources(x.db,x.o.id)[0].available_refund_cents,0);assert.equal((await propose(x,x.m,{amount_cents:1})).status,409);assert.equal((await act(x,r.id,'cancel')).status,409);verify(x);});
test('multiple original receipts retain independent caps and exactly split cents',async t=>{const x=await setup(t,33);const second=(await receive(x.request,x.m,x.o.id,{amount_cents:34})).body.event;for(const [receipt,amount] of [[x.receipt,13],[second,34],[x.receipt,20]]){const p=(await propose(x,x.m,{receipt_id:receipt.id,amount_cents:amount})).body.refund;await act(x,p.id,'approve');assert.equal((await act(x,p.id,'execute')).status,201);}const s=orderPayments(x.db,x.o.id);assert.deepEqual([s.recorded_cents,s.refunded_cents,s.retained_cents],[67,67,0]);assert.equal((await revise(x.request,x.m,x.o)).body.error.code,'ORDER_HAS_RECEIPTS');verify(x);});
test('active refunds prevent receipt misentry void in both server and database; cancelled requests restore explicit void path',async t=>{const x=await setup(t),p=(await propose(x)).body.refund;assert.equal((await voidReceipt(x.request,x.m,x.o.id,x.receipt.id)).body.error.code,'RECEIPT_HAS_REFUNDS');assert.throws(()=>insertPayment(x.db,x.o.id,'void',{source_id:x.receipt.id,reason:'虚构'},'manager'),/protects original receipt/);await act(x,p.id,'cancel');assert.equal((await voidReceipt(x.request,x.m,x.o.id,x.receipt.id)).status,201);assert.equal((await propose(x)).status,409);verify(x);});
test('actual refund permanently protects its original receipt from false-entry void',async t=>{const x=await setup(t),p=(await propose(x)).body.refund;await act(x,p.id,'approve');await act(x,p.id,'execute');assert.equal((await voidReceipt(x.request,x.m,x.o.id,x.receipt.id)).status,409);assert.throws(()=>insertPayment(x.db,x.o.id,'void',{source_id:x.receipt.id,reason:'虚构'},'manager'),/protects original receipt/);verify(x);});
test('same-key replay is stable; differing intent and simultaneous proposals require current source versions',async t=>{const x=await setup(t),input=intent(x),path='/api/retail/orders/'+x.o.id+'/refunds',opts={...x.m,method:'POST',data:input,key:'refund-exact-intent'},a=await x.request(path,opts),b=await x.request(path,opts);assert.deepEqual(a.body,b.body);assert.equal((await x.request(path,{...opts,data:{...input,amount_cents:21}})).status,409);await act(x,a.body.refund.id,'cancel');const same=intent(x,{amount_cents:100}),race=await Promise.all([x.request(path,{...x.m,method:'POST',data:same}),x.request(path,{...x.m,method:'POST',data:same})]);assert.deepEqual(race.map(r=>r.status).sort(),[201,409]);verify(x);});
test('receipt void and refund proposal race has only one winner without orphan money references',async t=>{const x=await setup(t),input=intent(x),race=await Promise.all([x.request('/api/retail/orders/'+x.o.id+'/refunds',{...x.m,method:'POST',data:input}),voidReceipt(x.request,x.m,x.o.id,x.receipt.id)]);assert.deepEqual(race.map(r=>r.status).sort(),[201,409]);verify(x);});
test('adding an installment conflicts with stale approval and reread can preserve fixed original receipt',async t=>{const x=await setup(t),r=(await propose(x)).body.refund,p=orderPayments(x.db,x.o.id),input={expected_order_version:1,expected_payment_revision:p.revision,expected_sequence:p.refund_sequence,expected_case_revision:null,expected_revision:1,action:'approve',note:'保留（虚构）',reason:'虚构'};await receive(x.request,x.m,x.o.id,{amount_cents:1});assert.equal((await x.request('/api/refunds/'+r.id+'/events',{...x.m,method:'POST',data:input})).body.error.code,'REFUND_CONFLICT');assert.equal((await act(x,r.id,'approve')).status,201);assert.equal(refundRecord(x.db,r.id).receipt_id,x.receipt.id);verify(x);});
test('refund source must be original effective receipt, never a void, another order or fabricated subtotal',async t=>{const x=await setup(t),other=await order(x.request,x.m,[await product(x.request,x.m)]),r=(await receive(x.request,x.m,other.id)).body.event;assert.equal((await propose(x,x.m,{receipt_id:r.id})).status,409);for(const extra of [{receipt_id:'missing'},{receipt_id:null},{amount_cents:0},{amount_cents:1.1},{amount_cents:'20'},{amount_cents:1e12+1},{decision_basis:''},{case_id:'missing'},{basis_total_cents:100},{currency:'USD'},{free_exchange:true}])assert.ok([409,422].includes((await propose(x,x.m,extra)).status),JSON.stringify(extra));verify(x);});
test('financial reads and writes stay store/role scoped; guardian and professional cannot see refund timeline amounts',async t=>{const x=await setup(t),f=await x.login('front'),p=await x.login('professional'),g=await x.login('parent'),o=await x.login('other'),r=(await propose(x)).body.refund;for(const s of [p,g]){assert.equal((await x.request('/api/refunds',s)).status,403);assert.equal((await x.request('/api/refunds/'+r.id,s)).status,403);assert.equal((await x.request('/api/customers/one/timeline?kind=refund',s)).status,403);}assert.equal((await x.request('/api/refunds/'+r.id,o)).status,404);assert.equal((await x.request('/api/refunds',o)).body.total,0);assert.equal((await x.request('/api/refunds',f)).status,200);assert.equal((await act(x,r.id,'reject',f)).status,403);const tl=(await x.request('/api/customers/one/timeline',p)).body;assert.ok(!tl.items.some(e=>['payment','refund'].includes(e.kind)));});
test('actual refund must follow explicit approval and use past canonical time and full evidence',async t=>{const x=await setup(t),r=(await propose(x)).body.refund;await act(x,r.id,'approve');for(const extra of [{refunded_at:'2001-01-01T00:00:00.000Z'},{refunded_at:new Date(Date.now()+10000).toISOString()},{refunded_at:'2026-02-30T00:00:00.000Z'},{receiver_name:''},{reference:''},{receipt_note:''},{method:'payment_callback'},{amount_cents:1},{refund_fee_cents:1}])assert.equal((await act(x,r.id,'execute',x.m,extra)).status,422,JSON.stringify(extra));assert.equal(orderPayments(x.db,x.o.id).refunded_cents,0);verify(x);});
test('actual refund references prevent duplicate payout across original receipts while repeated idempotent record stays single',async t=>{const x=await setup(t),a=(await propose(x)).body.refund;await act(x,a.id,'approve');assert.equal((await act(x,a.id,'execute',x.m,{reference:'SYNTHETIC-DUPLICATE'},'refund-actual-once')).status,201);const b=(await propose(x)).body.refund;await act(x,b.id,'approve');assert.equal((await act(x,b.id,'execute',x.m,{reference:'SYNTHETIC-DUPLICATE'})).body.error.code,'REFUND_DUPLICATE_REFERENCE');assert.equal(orderPayments(x.db,x.o.id).refunded_cents,20);verify(x);});
test('native append-only, source/cap and role guards remain independent of frontend checks',async t=>{const x=await setup(t),r=(await propose(x)).body.refund;assert.throws(()=>x.db.exec('UPDATE refund_events SET amount_cents=1'),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM refund_events'),/immutable/);assert.throws(()=>x.db.exec('UPDATE payment_refund_refs SET sequence=9'),/immutable/);assert.throws(()=>insertRefundEvent(x.db,x.o.id,{action:'approve',root_id:r.id,note:'虚构',reason:'虚构'},'front'),/actor/);assert.throws(()=>insertRefundEvent(x.db,x.o.id,{action:'create',receipt_id:x.receipt.id,amount_cents:100,decision_basis:'虚构',note:'虚构',reason:'虚构'},'manager'),/amount exceeded/);verify(x);});
test('refund audit failure rolls back reserved cents and actual money; retry uses the unchanged approved intent',async t=>{const x=await setup(t);x.db.exec("CREATE TRIGGER bad_refund_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'refunds.%' BEGIN SELECT RAISE(ABORT,'audit unavailable');END");assert.equal((await propose(x,x.m,{},'refund-audit-retry')).status,500);assert.equal(refundSequence(x.db,x.o.id),0);x.db.exec('DROP TRIGGER bad_refund_audit');const r=(await propose(x,x.m,{},'refund-audit-retry')).body.refund;await act(x,r.id,'approve');x.db.exec("CREATE TRIGGER bad_refund_audit BEFORE INSERT ON audit_events WHEN NEW.action='refunds.execute' BEGIN SELECT RAISE(ABORT,'audit unavailable');END");assert.equal((await act(x,r.id,'execute')).status,500);assert.equal(orderPayments(x.db,x.o.id).refunded_cents,0);assert.equal(refundRecord(x.db,r.id).status,'approved');x.db.exec('DROP TRIGGER bad_refund_audit');assert.equal((await act(x,r.id,'execute')).status,201);verify(x);});
test('payment audit rollback removes its new cross-ref and leaves refund source consistent',async t=>{const x=await setup(t),r=(await propose(x)).body.refund;await act(x,r.id,'cancel');const n=x.db.prepare('SELECT count(*) n FROM payment_refund_refs').get().n;x.db.exec("CREATE TRIGGER bad_payment_audit BEFORE INSERT ON audit_events WHEN NEW.action='payments.receive' BEGIN SELECT RAISE(ABORT,'audit unavailable');END");assert.equal((await receive(x.request,x.m,x.o.id)).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM payment_refund_refs').get().n,n);x.db.exec('DROP TRIGGER bad_payment_audit');assert.equal((await receive(x.request,x.m,x.o.id)).status,201);verify(x);});
test('global/order history paging and same-time timeline retain exact original sources',async t=>{const x=await setup(t);for(let i=0;i<3;i++){const r=(await propose(x)).body.refund;await act(x,r.id,'reject');}const a=(await x.request('/api/refunds?limit=2',x.m)).body;assert.equal(a.total,3);assert.equal(a.items.length,2);assert.equal(a.next_offset,2);const o=(await x.request('/api/retail/orders/'+x.o.id+'/refunds?limit=1',x.m)).body;assert.equal(o.total,3);assert.equal(o.next_offset,1);const tl=(await x.request('/api/customers/one/timeline?kind=refund',x.m)).body;assert.equal(tl.items.length,6);assert.ok(tl.items.every(e=>e.entity_id===x.o.id&&e.details.order_version===1&&e.details.receipt_id===x.receipt.id));for(const q of ['limit=0','limit=101','offset=-1','status=paid'])assert.equal((await x.request('/api/refunds?'+q,x.m)).status,422);verify(x);});
test('pending financial request rechecks session revocation and creates no reservation',async t=>{const x=await setup(t),data=JSON.stringify(intent(x)),u=new URL(x.origin),r=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path:'/api/retail/orders/'+x.o.id+'/refunds',method:'POST',headers:{Cookie:x.m.cookie,'X-CSRF-Token':x.m.csrf,'Idempotency-Key':'refund-pending-session','Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},r=>{let s='';r.on('data',x=>s+=x);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(s)}));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{x.db.prepare("DELETE FROM sessions WHERE user_id='manager'").run();req.end(data.slice(10));},30);});assert.equal(r.status,401);assert.equal(refundSequence(x.db,x.o.id),0);});
test('replaying the exact actual payout returns the same receipt once and changed intent is rejected',async t=>{const x=await setup(t),r=(await propose(x)).body.refund;await act(x,r.id,'approve');const p=orderPayments(x.db,x.o.id),input={expected_order_version:1,expected_payment_revision:p.revision,expected_sequence:p.refund_sequence,expected_case_revision:null,expected_revision:2,action:'execute',method:'cash',reference:'SYNTHETIC-EXACT-PAID',receiver_name:'实际接收人（虚构）',refunded_at:new Date().toISOString(),receipt_note:'实际发生（虚构）',note:'登记（虚构）',reason:'凭据（虚构）'},path='/api/refunds/'+r.id+'/events',opts={...x.m,method:'POST',data:input,key:'refund-exact-paid'};const a=await x.request(path,opts),b=await x.request(path,opts);assert.equal(a.status,201);assert.deepEqual(b.body,a.body);assert.equal((await x.request(path,{...opts,data:{...input,note:'不同记录'}})).status,409);assert.equal(orderPayments(x.db,x.o.id).refunded_cents,20);verify(x);});
async function demoFixture(t,{persist=false}={}){const dir=mkdtempSync(join(tmpdir(),'optical-refund-demo-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment','seedDemoAftercare','seedDemoAftercareWork','seedDemoReplacements','seedDemoDispositions'])demo[fn](db);server.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});return {db,path,dir,server};}
import {aftercareRecord,insertAftercareEvent} from '../src/aftercare.mjs';import {orderVersion,insertOrderVersion} from '../src/retail.mjs';import {insertReplacementEvent,verifyReplacements} from '../src/aftercare-replacements.mjs';
test('same-customer refunds link only original or fixed replacement order and preserve closed-case trace',async t=>{const x=await demoFixture(t),order='demo-order-revised',receipt=refundSources(x.db,order)[0],c=aftercareRecord(x.db,'demo-aftercare-repair');const root=insertRefundEvent(x.db,order,{action:'create',receipt_id:receipt.id,amount_cents:100,case_id:c.id,decision_basis:'明确本次退款（虚构）',note:'虚构',reason:'虚构'},'demo-front').refund;insertAftercareEvent(x.db,c.id,{action:'resolve',note:'沟通结束（虚构）',reason:'独立处理（虚构）'},'demo-manager');insertRefundEvent(x.db,order,{action:'approve',root_id:root.id,note:'虚构',reason:'虚构'},'demo-manager');assert.equal(refundRecord(x.db,root.id).history[0].case_revision,aftercareRecord(x.db,c.id).revision);assert.throws(()=>insertRefundEvent(x.db,'demo-order-draft',{action:'create',receipt_id:refundSources(x.db,'demo-order-draft')[0].id,amount_cents:1,case_id:c.id,decision_basis:'虚构',note:'虚构',reason:'虚构'},'demo-manager'),/aftercare source invalid/);const replacement='demo-order-replacement-approved',payment=insertPayment(x.db,replacement,'receive',{amount_cents:100,method:'cash',received_at:new Date().toISOString(),reference:null,reason:'新单实收（虚构）'},'demo-manager');const next=insertRefundEvent(x.db,replacement,{action:'create',receipt_id:payment.id,amount_cents:20,case_id:'demo-aftercare-exchange',decision_basis:'新单人工退款（虚构）',note:'虚构',reason:'虚构'},'demo-front');assert.equal(next.refund.case_id,'demo-aftercare-exchange');verifyRefunds(x.db);verifyPayments(x.db);insertRefundEvent(x.db,replacement,{action:'cancel',root_id:next.refund.id,note:'撤销未退申请（虚构）',reason:'独立改办（虚构）'},'demo-front');insertPayment(x.db,replacement,'void',{source_id:payment.id,reason:'此原收款为误录，未发生付款（虚构）'},'demo-manager');insertReplacementEvent(x.db,'demo-replacement-approved',{action:'cancel',note:'明确取消新商品安排（虚构）',reason:'来源变更（虚构）'},'demo-manager');const o=orderVersion(x.db,replacement);insertOrderVersion(x.db,replacement,{title:'取消旧安排后独立继续（虚构）',notes:o.notes,items:o.items,document_version_ids:[],attachment_ids:[],reason:'明确新单版本（虚构）'},'demo-manager');assert.equal(orderVersion(x.db,replacement).version,2);assert.equal(refundRecord(x.db,next.refund.id).order_version,1);verifyRefunds(x.db);verifyPayments(x.db);verifyReplacements(x.db);});
test('demo saves pending/approved/paid stages once and does not mutate originals, stock or old custody',async t=>{const x=await demoFixture(t),tables=['payment_events','retail_order_versions','inventory_events','inventory_outbounds','aftercare_events','aftercare_work_events','aftercare_disposition_events'],old=tables.map(n=>x.db.prepare('SELECT * FROM '+n).all());assert.deepEqual(demo.seedDemoRefunds(x.db),{proposals:3,events:6});assert.equal(refundRecord(x.db,'demo-refund-pending').status,'pending');assert.equal(refundRecord(x.db,'demo-refund-approved').status,'approved');assert.equal(refundRecord(x.db,'demo-refund-executed').status,'executed');assert.equal(orderPayments(x.db,'demo-order-draft').retained_cents,20000);assert.equal(orderPayments(x.db,'demo-order-revised').reserved_refund_cents,30000);assert.deepEqual(demo.seedDemoRefunds(x.db),{proposals:0,events:0});tables.forEach((n,i)=>assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),old[i]));verify(x);});
test('backup and independent restore preserve actual refunds; removed cross-reference or altered receipt is rejected',async t=>{const x=await setup(t,100,{persist:true}),r=(await propose(x)).body.refund;await act(x,r.id,'approve');await act(x,r.id,'execute');const b=await createBackup(x.path,join(x.dir,'backup')),restored=await restoreBackup(b.backup,join(x.dir,'restored')),db=openDatabase(restored.database);try{for(const n of ['refund_events','payment_refund_refs'])assert.deepEqual(db.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());verifyRefunds(db);}finally{db.close();}const sql=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='payment_refund_refs_no_delete'").get().sql;x.db.exec('DROP TRIGGER payment_refund_refs_no_delete');x.db.exec('DELETE FROM payment_refund_refs');x.db.exec(sql);await assert.rejects(()=>createBackup(x.path,join(x.dir,'bad')),/退款/);});
test('schema21 nonempty upgrade captures zero refund basis without altering original rows or inventing refunds',()=>{
 const dir=mkdtempSync(join(tmpdir(),'optical-refund-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);
 try{
  db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');
  for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&x<'022').sort()){db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(file,new Date().toISOString());}
  db.exec("INSERT INTO stores VALUES ('store-a','A')");
  for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');
  for(const fn of ['seedDemoScenarios','seedDemoRetail','seedDemoInventory','seedDemoPayments','seedDemoProcessing','seedDemoFulfillment','seedDemoAftercare','seedDemoAftercareWork','seedDemoReplacements','seedDemoDispositions'])demo[fn](db);
  const names=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name!='schema_migrations' ORDER BY name").all().map(x=>x.name),old=names.map(n=>db.prepare('SELECT * FROM '+n).all()),receiptCount=db.prepare('SELECT count(*) n FROM payment_events').get().n;
  db.close();db=openDatabase(path);
  names.forEach((n,i)=>assert.deepEqual(db.prepare('SELECT * FROM '+n).all(),old[i],n));
  assert.equal(db.prepare('SELECT count(*) n FROM refund_events').get().n,0);
  assert.equal(db.prepare('SELECT count(*) n FROM payment_refund_refs WHERE sequence=0').get().n,receiptCount);
  assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,45);verifyRefunds(db);verifyPayments(db);
 }finally{db.close();rmSync(dir,{recursive:true,force:true});}
});
