import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { request as httpRequest } from 'node:http';
import { mkdtempSync,rmSync,readFileSync,readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { createApp } from '../src/server.mjs';
import { hashPassword,openDatabase } from '../src/db.mjs';
import { createBackup,restoreBackup } from '../src/recovery.mjs';
import { retailTables,insertOrderVersion } from '../src/retail.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-retail-')),path=persist?join(dir,'source.sqlite'):':memory:',app=createApp({databasePath:path,mode:'test',logger:()=>{}}),{server,db}=app;db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {...app,request,login,origin,path,dir};
}
function productInput(extra={}){return {sku:'FRAME-'+crypto.randomUUID().slice(0,8),name:'镜架（虚构）',category:'frame',brand:'虚构品牌',specification:'虚构型号 / 蓝色',unit:'副',list_price_cents:19990,status:'active',reason:'虚构目录登记',...extra};}
async function product(request,m,extra={}){const r=await request('/api/retail/products',{...m,method:'POST',data:productInput(extra)});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.product;}
function orderInput(p,extra={}){return {title:'配镜订单（虚构）',notes:'虚构配镜需求，专业确认另行处理',items:[{product_id:p.id,product_version:p.version,quantity:1,unit_price_cents:19990,note:'镜架行说明'}],document_version_ids:[],attachment_ids:[],reason:'虚构录单',...extra};}
async function order(request,m,p,extra={}){const r=await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,extra)});assert.equal(r.status,201,JSON.stringify(r.body));return r.body.order;}
function reviseProduct(request,m,p,extra={}){return request(`/api/retail/products/${p.id}/versions`,{...m,method:'POST',data:{...productInput(),sku:undefined,expected_version:p.version,...Object.fromEntries(['name','category','brand','specification','unit','list_price_cents','status'].map(k=>[k,p[k]])),reason:'虚构目录修订',...extra}});}
function reviseOrder(request,m,o,extra={},key=crypto.randomUUID()){return request(`/api/retail/orders/${o.id}/versions`,{...m,method:'POST',key,data:{expected_version:o.version,title:o.title,notes:o.notes,items:o.items.map(x=>({product_id:x.product_id,product_version:x.product_version,quantity:x.quantity,unit_price_cents:x.unit_price_cents,note:x.note})),document_version_ids:o.documents.map(x=>x.id),attachment_ids:o.attachments.map(x=>x.id),reason:'虚构订单修订',...extra}});}
async function assets(request,m,origin,customer='one'){
 const r=await fetch(`${origin}/api/customers/${customer}/attachments`,{method:'POST',headers:{Cookie:m.cookie,'X-CSRF-Token':m.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'text/plain','X-File-Name':encodeURIComponent('配镜资料（虚构）.txt')},body:'纯虚构资料来源'}),a=(await r.json()).attachment;assert.equal(r.status,201);const d=await request(`/api/customers/${customer}/documents`,{...m,method:'POST',data:{title:'配镜资料来源（虚构）',content:'未确认专业资料，仅作来源记录',source:'external',attachment_ids:[a.id]}});assert.equal(d.status,201,JSON.stringify(d.body));return {attachment:a,document:d.body.document};
}
test('retail catalog and draft orders have employee/store permissions and catalog writes require manager',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),f=await login('front'),p=await login('professional'),other=await login('other'),g=await login('parent'),item=await product(request,m),o=await order(request,f,item);for(const s of [m,f,p]){assert.equal((await request('/api/retail/products',s)).status,200);assert.equal((await request(`/api/retail/orders/${o.id}`,s)).status,200);}for(const s of [f,p,g])assert.equal((await request('/api/retail/products',{...s,method:'POST',data:productInput()})).status,403);assert.equal((await request('/api/customers/one/retail-orders',{...p,method:'POST',data:orderInput(item)})).status,403);assert.equal((await request('/api/retail/orders',g)).status,403);assert.equal((await request(`/api/retail/orders/${o.id}`,other)).status,404);assert.equal((await request(`/api/retail/products/${item.id}`,other)).status,404);assert.equal((await request('/api/retail/orders',other)).body.total,0);assert.equal((await request('/api/retail/products')).status,401);
});
test('retail catalog duplicate codes and optimistic immutable revisions preserve old orders through repricing and deactivation',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m,{sku:'EXAMPLE-1'}),o=await order(request,m,p);assert.equal((await request('/api/retail/products',{...m,method:'POST',data:productInput({sku:'example-1'})})).body.error.code,'SKU_EXISTS');assert.equal((await reviseProduct(request,m,p,{list_price_cents:29990,status:'inactive'})).status,201);assert.equal((await reviseProduct(request,m,p,{name:'陈旧编辑'})).body.error.code,'PRODUCT_CONFLICT');const read=(await request(`/api/retail/orders/${o.id}`,m)).body.order;assert.equal(read.items[0].product_version,1);assert.equal(read.items[0].list_price_cents,19990);assert.equal(read.items[0].catalog_version,2);assert.equal(read.items[0].catalog_status,'inactive');assert.equal(read.subtotal_cents,19990);assert.equal((await reviseOrder(request,m,o,{notes:'目录停用后补充订单说明'})).status,201);assert.throws(()=>db.exec("UPDATE retail_product_versions SET name='覆盖旧版本'"),/immutable/);assert.throws(()=>db.exec('DELETE FROM retail_products'),/immutable/);
});
test('retail order amounts use exact integer cents and explicit per-line unit prices independent of catalog',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m,{list_price_cents:10000}),o=await order(request,m,p,{items:[{product_id:p.id,product_version:1,quantity:3,unit_price_cents:10},{product_id:p.id,product_version:1,quantity:7,unit_price_cents:1},{product_id:p.id,product_version:1,quantity:1,unit_price_cents:0}]});assert.equal(o.subtotal_cents,37);assert.deepEqual(o.items.map(x=>x.line_total_cents),[30,7,0]);assert.equal(o.currency,'CNY');assert.equal(o.status,'draft');for(const n of [-1,0.1,Infinity,'10',1000000001]){const r=await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{items:[{product_id:p.id,product_version:1,quantity:1,unit_price_cents:n}]})});assert.equal(r.status,422);}for(const quantity of [0,0.5,1000,'1'])assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{items:[{product_id:p.id,product_version:1,quantity,unit_price_cents:10}]})})).status,422);
});
test('retail orders fix original visit and retail cycle V1 despite later V3 and reject forged or unknown context',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m),cycle=(await request('/api/customers/one/cycles',{...m,method:'POST',data:{type:'retail',goal:'原配镜需求（虚构）'}})).body.cycle,visit=(await request('/api/customers/one/visits',{...m,method:'POST',data:{purpose:'原到店（虚构）',cycle_ids:[cycle.id]}})).body.visit;for(let v=1;v<=2;v++)assert.equal((await request(`/api/cycles/${cycle.id}/versions`,{...m,method:'POST',data:{expected_version:v,goal:'后来需求'+v,source:'employee',revision_reason:'补充需求'}})).status,201);const o=await order(request,m,p,{cycle_id:cycle.id,cycle_version:1,visit_id:visit.id});assert.equal(o.context_basis,'visit_cycle');assert.equal(o.cycle_goal,'原配镜需求（虚构）');assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{cycle_id:cycle.id,cycle_version:1})})).body.error.code,'CONTEXT_CONFLICT');assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{cycle_id:cycle.id,cycle_version:3,visit_id:visit.id})})).body.error.code,'CONTEXT_CONFLICT');assert.equal((await reviseOrder(request,m,o,{cycle_version:3})).status,422);const training=(await request('/api/customers/one/cycles',{...m,method:'POST',data:{type:'training',goal:'其他业务'}})).body.cycle;assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{cycle_id:training.id,cycle_version:1})})).status,422);const opt=(await request('/api/retail/customers/one/options',m)).body;assert.equal(opt.cycles[0].version,3);assert.equal(opt.visits[0].cycle_refs[0].version,1);
});
test('retail order source references stay at original document version and retain later revoked attachment without authorizing new references',async t=>{
 const {request,login,origin}=await fixture(t),m=await login('manager'),p=await product(request,m),a=await assets(request,m,origin),o=await order(request,m,p,{document_version_ids:[a.document.id],attachment_ids:[a.attachment.id]});await request(`/api/documents/${a.document.record_id}/versions`,{...m,method:'POST',data:{expected_version:1,title:'资料 V2（虚构）',content:'后续修订',source:'external',revision_reason:'修订',attachment_ids:[a.attachment.id]}});await request(`/api/attachments/${a.attachment.id}/revoke`,{...m,method:'POST',data:{reason:'事后撤销'}});const r=(await request(`/api/retail/orders/${o.id}`,m)).body.order;assert.equal(r.documents[0].id,a.document.id);assert.equal(r.documents[0].version,1);assert.ok(r.attachments[0].revoked_at);assert.equal((await reviseOrder(request,m,o,{notes:'保留已引用原资料'})).status,201);assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{attachment_ids:[a.attachment.id]})})).status,422);const other=await assets(request,m,origin,'two');assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,{document_version_ids:[other.document.id]})})).status,422);
});
test('retail order revisions and draft cancellation append full history without changing identity or original lines',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,p),before=db.prepare('SELECT * FROM retail_orders').get(),r=await reviseOrder(request,m,o,{title:'第二版配镜草稿（虚构）',items:[{product_id:p.id,product_version:1,quantity:2,unit_price_cents:18880}]});assert.equal(r.status,201);assert.equal(r.body.order.subtotal_cents,37760);assert.deepEqual(db.prepare('SELECT * FROM retail_orders').get(),before);const old=(await request(`/api/retail/orders/${o.id}/versions/1`,m)).body.order;assert.equal(old.title,o.title);assert.equal(old.items[0].quantity,1);const cancel=await request(`/api/retail/orders/${o.id}/cancel`,{...m,method:'POST',data:{expected_version:2,reason:'虚构草稿取消'}});assert.equal(cancel.status,201);assert.equal(cancel.body.order.version,3);assert.equal(cancel.body.order.status,'cancelled');assert.equal(cancel.body.order.subtotal_cents,37760);assert.equal((await reviseOrder(request,m,cancel.body.order,{notes:'取消后修订'})).body.error.code,'ORDER_CANCELLED');assert.equal((await request(`/api/retail/orders/${o.id}`,m)).body.history.length,3);assert.throws(()=>db.exec('DELETE FROM retail_order_items'),/immutable/);assert.throws(()=>db.exec("UPDATE retail_orders SET customer_id='two'"),/immutable/);
});
test('retail order list search, customer list and overview/timeline use actual saved order versions',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,p);await reviseOrder(request,m,o,{title:'订单新标题（虚构）'});const list=(await request('/api/retail/orders?q='+encodeURIComponent(o.order_number),m)).body;assert.equal(list.total,1);assert.equal(list.items[0].version,2);assert.equal((await request('/api/customers/two/retail-orders',m)).body.total,0);const events=(await request('/api/customers/one/timeline?kind=retail',m)).body.items;assert.deepEqual(events.map(e=>e.details.version).sort(),[1,2]);assert.equal((await request('/api/customers/one/overview',m)).body.retail_orders_draft,1);
});
test('retail catalog and order writes reject CSRF, invented payment/state fields and cross-store goods',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),other=await login('other'),p=await product(request,m),q=await product(request,other);assert.equal((await request('/api/customers/one/retail-orders',{cookie:m.cookie,method:'POST',data:orderInput(p)})).status,403);for(const extra of [{paid:true},{status:'delivered'},{discount_cents:1},{refund:100},{prescription_confirmed:true},{store_id:'b'},{customer_id:'two'}])assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p,extra)})).status,422);assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(q)})).status,404);assert.equal((await request('/api/retail/products',{...m,method:'POST',data:productInput({stock:99})})).status,422);
});
test('new retail order goods require current active catalog version while saved historical references can be retained',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m);await reviseProduct(request,m,p,{name:'新目录 V2（虚构）'});assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',data:orderInput(p)})).body.error.code,'PRODUCT_CHANGED');const fresh=(await request(`/api/retail/products/${p.id}`,m)).body.product,o=await order(request,m,fresh);await reviseProduct(request,m,fresh,{status:'inactive'});assert.equal((await reviseOrder(request,m,o,{notes:'旧版本继续留存'})).status,201);const other=await order(request,m,await product(request,m));assert.equal((await reviseOrder(request,m,other,{items:orderInput(fresh).items})).body.error.code,'PRODUCT_CHANGED');
});
test('retail audit failures roll back header/version/lines/references/serial and idempotent retry creates one order',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m);db.exec("CREATE TRIGGER retail_fault BEFORE INSERT ON audit_events WHEN NEW.action='retail.order.create' BEGIN SELECT RAISE(ABORT,'fault'); END");const input=orderInput(p),r=await request('/api/customers/one/retail-orders',{...m,method:'POST',key:'retail-retry-one',data:input});assert.equal(r.status,500);for(const table of retailTables.filter(t=>!t.startsWith('retail_product')))assert.equal(db.prepare('SELECT count(*) n FROM '+table).get().n,0);assert.equal(db.prepare("SELECT count(*) n FROM idempotency WHERE request_key='retail-retry-one'").get().n,0);db.exec('DROP TRIGGER retail_fault');const replies=await Promise.all([request('/api/customers/one/retail-orders',{...m,method:'POST',key:'retail-retry-one',data:input}),request('/api/customers/one/retail-orders',{...m,method:'POST',key:'retail-retry-one',data:input})]);assert.deepEqual(replies.map(x=>x.status),[201,201]);assert.deepEqual(replies[0].body,replies[1].body);assert.equal(replies[0].body.order.serial,1);assert.equal(db.prepare('SELECT count(*) n FROM retail_orders').get().n,1);assert.equal((await request('/api/customers/one/retail-orders',{...m,method:'POST',key:'retail-retry-one',data:{...input,title:'不同意图'}})).body.error.code,'IDEMPOTENCY_CONFLICT');
});
test('retail order competing revision and cancellation have one winner and stale requests leave no partial history',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),f=await login('front'),p=await product(request,m),o=await order(request,m,p),replies=await Promise.all([reviseOrder(request,m,o,{notes:'竞争修订'}),request(`/api/retail/orders/${o.id}/cancel`,{...f,method:'POST',data:{expected_version:1,reason:'竞争取消'}})]);assert.deepEqual(replies.map(x=>x.status).sort(),[201,409]);assert.equal(db.prepare('SELECT count(*) n FROM retail_order_versions').get().n,2);assert.equal(db.prepare('SELECT count(*) n FROM retail_order_items').get().n,2);assert.equal((await reviseOrder(request,m,o,{notes:'陈旧修订'})).body.error.code,'ORDER_CONFLICT');
});
test('retail catalog optimistic concurrent edits and audit rollback never replace prior versions',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m);db.exec("CREATE TRIGGER catalog_fault BEFORE INSERT ON audit_events WHEN NEW.action='retail.product.revise' BEGIN SELECT RAISE(ABORT,'fault'); END");assert.equal((await reviseProduct(request,m,p,{name:'失败修订'})).status,500);assert.equal(db.prepare('SELECT count(*) n FROM retail_product_versions').get().n,1);db.exec('DROP TRIGGER catalog_fault');const r=await Promise.all([reviseProduct(request,m,p,{name:'并发一'}),reviseProduct(request,m,p,{name:'并发二'})]);assert.deepEqual(r.map(x=>x.status).sort(),[201,409]);assert.equal(db.prepare('SELECT count(*) n FROM retail_product_versions').get().n,2);
});
test('retail lists retain full totals above one hundred and literal search does not treat wildcard input as SQL',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m);for(let i=0;i<105;i++)await order(request,m,p,{title:`虚构订单 ${i}`});let cursor=0,seen=[];do{const r=(await request(`/api/retail/orders?limit=40&offset=${cursor}`,m)).body;assert.equal(r.total,105);assert.equal(r.counts.draft,105);seen.push(...r.items.map(x=>x.id));cursor=r.next_offset;}while(cursor!==null);assert.equal(seen.length,105);assert.equal(new Set(seen).size,105);assert.equal((await request('/api/retail/products?q=%25',m)).body.total,0);for(const q of ['limit=0','limit=101','offset=-1','status=paid'])assert.equal((await request('/api/retail/orders?'+q,m)).status,422);
});
test('retail backup and independent restore preserve catalog versions, original sources, prices and cancelled history',async t=>{
 const {request,login,db,origin,path,dir}=await fixture(t,{persist:true}),m=await login('manager'),p=await product(request,m),a=await assets(request,m,origin),o=await order(request,m,p,{document_version_ids:[a.document.id],attachment_ids:[a.attachment.id]});await reviseProduct(request,m,p,{list_price_cents:99900,status:'inactive'});const revised=(await reviseOrder(request,m,o,{notes:'第二版订单'})).body.order;await request(`/api/retail/orders/${o.id}/cancel`,{...m,method:'POST',data:{expected_version:revised.version,reason:'虚构取消'}});await request(`/api/attachments/${a.attachment.id}/revoke`,{...m,method:'POST',data:{reason:'事后撤销'}});const b=await createBackup(path,join(dir,'backup'));assert.equal(b.checks.migrations.length,43);const restored=await restoreBackup(b.backup,join(dir,'restored')),copy=openDatabase(restored.database);try{for(const table of retailTables)assert.deepEqual(copy.prepare('SELECT * FROM '+table).all(),db.prepare('SELECT * FROM '+table).all());assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n,0);}finally{copy.close();}
});
test('retail recovery detects incorrect header totals even with protection triggers reinstated',async t=>{
 const {request,login,db,path,dir}=await fixture(t,{persist:true}),m=await login('manager'),p=await product(request,m);await order(request,m,p);const sql=db.prepare("SELECT sql FROM sqlite_schema WHERE name='retail_order_versions_no_update'").get().sql;db.exec('DROP TRIGGER retail_order_versions_no_update;UPDATE retail_order_versions SET subtotal_cents=subtotal_cents+1');db.exec(sql);await assert.rejects(createBackup(path,join(dir,'bad-backup')),/订单明细、金额或固定引用/);
});
test('retail pending order body rechecks revoked session before saving anything',async t=>{
 const {request,login,server,origin,db}=await fixture(t),m=await login('manager'),f=await login('front'),p=await product(request,m),accepted=once(server,'request'),pending=httpRequest(origin+'/api/customers/one/retail-orders',{method:'POST',headers:{Cookie:f.cookie,'X-CSRF-Token':f.csrf,'Idempotency-Key':'pending-retail-order','Content-Type':'application/json'}}),response=new Promise((resolve,reject)=>{pending.on('error',reject);pending.on('response',r=>{let bytes='';r.on('data',c=>bytes+=c);r.on('end',()=>resolve({status:r.statusCode,body:JSON.parse(bytes)}));});});pending.flushHeaders();await accepted;assert.equal((await request('/api/organization/staff/front/revoke-sessions',{...m,method:'POST',data:{expected_revision:1,reason:'撤销待保存会话'}})).status,200);pending.end(JSON.stringify(orderInput(p)));assert.equal((await response).status,401);assert.equal(db.prepare('SELECT count(*) n FROM retail_orders').get().n,0);
});

test('retail cancellation audit failure rolls back the complete copied version and same intent can be retried once',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager'),p=await product(request,m),o=await order(request,m,p),key='same-cancel-intent',before=Object.fromEntries(retailTables.map(table=>[table,db.prepare('SELECT * FROM '+table).all()]));db.exec("CREATE TRIGGER reject_cancel_audit BEFORE INSERT ON audit_events WHEN NEW.action='retail.order.cancel' BEGIN SELECT RAISE(ABORT,'audit failure');END");const path=`/api/retail/orders/${o.id}/cancel`,data={expected_version:1,reason:'虚构取消'};assert.equal((await request(path,{...m,method:'POST',key,data})).status,500);for(const table of retailTables)assert.deepEqual(db.prepare('SELECT * FROM '+table).all(),before[table]);db.exec('DROP TRIGGER reject_cancel_audit');const first=await request(path,{...m,method:'POST',key,data}),retry=await request(path,{...m,method:'POST',key,data});assert.equal(first.status,201);assert.deepEqual(retry.body,first.body);assert.equal(db.prepare('SELECT count(*) n FROM retail_order_versions WHERE order_id=?').get(o.id).n,2);
});
test('retail database guards reject extra historical rows, malformed manifests, altered cancellation and overwritten references',async t=>{
 const {request,login,db,origin}=await fixture(t),m=await login('manager'),p=await product(request,m),a=await assets(request,m,origin),o=await order(request,m,p,{document_version_ids:[a.document.id],attachment_ids:[a.attachment.id]}),header=db.prepare('SELECT * FROM retail_order_versions WHERE order_id=?').get(o.id),create=db.prepare('INSERT INTO retail_order_versions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)'),values=Object.values(header);values[1]=2;values[6]='cancelled';values[4]='未经允许改名';assert.throws(()=>create.run(...values),/cancelled order content changed/);values[6]='draft';values[9]='{}';assert.throws(()=>create.run(...values),/manifest invalid/);values[9]=header.manifest_json;values[7]++;assert.throws(()=>create.run(...values),/manifest total invalid/);assert.throws(()=>db.prepare('INSERT INTO retail_order_items VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(o.id,1,2,'one','a',p.id,1,1,19990,19990,null),/outside manifest/);for(const table of retailTables)assert.throws(()=>db.exec('DELETE FROM '+table),/immutable|foreign key/i);
});
test('retail first-password gate blocks catalog and order reads/writes even with an otherwise valid session',async t=>{
 const {request,login,db}=await fixture(t),m=await login('manager');db.prepare('INSERT INTO user_security (user_id,must_change_password) VALUES (?,1)').run('manager');for(const path of ['/api/retail/products','/api/retail/orders','/api/retail/customers/one/options'])assert.equal((await request(path,m)).body.error.code,'PASSWORD_CHANGE_REQUIRED');assert.equal((await request('/api/retail/products',{...m,method:'POST',data:productInput()})).status,403);assert.equal(db.prepare('SELECT count(*) n FROM retail_products').get().n,0);
});
function seedOriginalDemo(db){db.exec("INSERT INTO stores VALUES ('store-a','A')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');for(const name of ['seedDemoScenarios','seedDemoPeople','seedDemoProfiles','seedDemoCycleRevisions','seedDemoTasks','seedDemoTaskExecution','seedDemoTaskExceptions','seedDemoTaskEvidence','seedDemoTaskCompletions','seedDemoTaskAmendments','seedDemoTaskChains'])demo[name](db);}
test('retail synthetic saved stages preserve manual revisions and catalog changes on repeat initialization',()=>{
 const db=openDatabase(':memory:');try{seedOriginalDemo(db);assert.deepEqual(demo.seedDemoRetail(db),{products:5,orders:4,versions:12});const o=db.prepare("SELECT * FROM retail_order_versions WHERE order_id='demo-order-draft'").get(),items=db.prepare("SELECT * FROM retail_order_items WHERE order_id='demo-order-draft'").all();insertOrderVersion(db,'demo-order-draft',{title:o.title,notes:'后来手工补充的虚构说明',items,document_version_ids:['demo-version-retail-1'],attachment_ids:['demo-attachment-retail'],reason:'后来手工修订'},'demo-manager');const tables=[...retailTables,'audit_events'],before=Object.fromEntries(tables.map(table=>[table,db.prepare('SELECT * FROM '+table).all()]));assert.deepEqual(demo.seedDemoRetail(db),{products:0,orders:0,versions:0});for(const table of tables)assert.deepEqual(db.prepare('SELECT * FROM '+table).all(),before[table]);assert.equal(db.prepare('SELECT count(*) n FROM work_tasks').get().n,26);assert.equal(db.prepare('SELECT count(*) n FROM task_events').get().n,74);}finally{db.close();}
});
test('V0.15 nonempty upgrade preserves all prior business tables and creates no invented retail orders',()=>{
 const dir=mkdtempSync(join(tmpdir(),'optical-retail-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);try{db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&x<'013').sort()){db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(file,new Date().toISOString());}seedOriginalDemo(db);const tables=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations' ORDER BY name").all().map(x=>x.name),before=Object.fromEntries(tables.map(table=>[table,db.prepare('SELECT * FROM '+table).all()]));db.close();db=openDatabase(path);assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,43);for(const table of tables)assert.deepEqual(db.prepare('SELECT * FROM '+table).all(),before[table]);for(const table of retailTables)assert.equal(db.prepare('SELECT count(*) n FROM '+table).get().n,0);assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{db.close();rmSync(dir,{recursive:true,force:true});}
});

test('retail full thirty-row Unicode notes remain editable with the same body capacity as creation',async t=>{
 const {request,login}=await fixture(t),m=await login('manager'),p=await product(request,m),items=Array.from({length:30},(_,i)=>({product_id:p.id,product_version:1,quantity:i+1,unit_price_cents:100,note:'虚'.repeat(300)})),o=await order(request,m,p,{items,notes:'长'.repeat(2000)}),revised=await reviseOrder(request,m,o,{notes:'长'.repeat(1999)+'改'});assert.equal(revised.status,201,JSON.stringify(revised.body));assert.equal(revised.body.order.items.length,30);assert.equal(revised.body.order.subtotal_cents,46500);assert.equal(revised.body.order.items[29].note.length,300);
});
