import * as demo from '../src/demo-data.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';
import {inventoryTables,stockBalance,orderInventory,verifyInventory,insertStockEvent} from '../src/inventory.mjs';
import {paymentTables,orderPayments,verifyPayments,insertPayment} from '../src/payments.mjs';
async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import {scheduleSequence,scheduleResource,scheduleSlot,scheduleBooking,schedulingTables,createResource,resourceVersion,createSlot,slotEvent,createBooking,bookingEvent} from '../src/scheduling.mjs';
import {verifyScheduling} from '../src/scheduling-recovery.mjs';
import {createTrainingProject,createTrainingPlan,insertTrainingPlanEvent,trainingPlan,insertTrainingPlanVersion} from '../src/training.mjs';
const resource=(extra={})=>({code:'SYNTHETIC-'+crypto.randomUUID(),kind:'room',user_id:null,name:'明确资源（虚构）',capacity:2,buffer_before:0,buffer_after:0,status:'active',source_note:'明确人工容量与准备收尾来源（虚构）',reason:'明确依据',...extra});
const note={note:'明确本次安排（虚构）',reason:'明确操作依据'};
async function setup(t,{persist=false}={}){const x=await fixture(t,{persist});x.m=await x.login('manager');x.f=await x.login('front');x.pro=await x.login('professional');x.plans={};for(const id of ['one','two']){const c=(await x.request('/api/customers/'+id+'/cycles',{...x.m,method:'POST',data:{type:'training',goal:'虚构计划需求'}})).body.cycle;let pr=x.db.prepare('SELECT id FROM training_projects LIMIT 1').get();if(!pr)pr=createTrainingProject(x.db,'a',{code:'SYNTHETIC-PROJECT',name:'虚构项目',description:'虚构',instructions:'人工明确',status:'active',reason:'虚构依据'},'professional');const p=createTrainingPlan(x.db,'a',id,{cycle_id:c.id,cycle_version:1,visit_id:null,title:'明确个人计划（虚构）',assessment:'人工明确来源',goals:'虚构目标',owner_id:'professional',source:'staff_record',source_note:'虚构依据',items:[{project_id:pr.id,project_version:1,instructions:'明确安排'}],document_version_ids:[],attachment_ids:[],...note},'professional');insertTrainingPlanEvent(x.db,p.plan.id,{action:'confirm',...note},'professional');x.plans[id]=trainingPlan(x.db,p.plan.id);}x.staff=(await write(x,'/api/scheduling/resources',resource({kind:'staff',user_id:'professional',name:'员工资源'}))).body.resource;x.room=(await write(x,'/api/scheduling/resources',resource({name:'房间'}))).body.resource;x.eq=(await write(x,'/api/scheduling/resources',resource({kind:'equipment',name:'设备'}))).body.resource;return x;}
async function write(x,path,data,who=x.m,key){return x.request(path,{...who,method:'POST',key,data:{expected_sequence:scheduleSequence(x.db,'a'),...data}});}
function slotInput(x,extra={}){return {kind:'one',capacity:1,starts_at:'2030-01-01T10:00:00.000Z',ends_at:'2030-01-01T11:00:00.000Z',resources:[x.staff,x.room,x.eq].map(r=>({id:r.id,version:r.version})),...note,...extra};}
async function slot(x,extra={}){const r=await write(x,'/api/scheduling/slots',slotInput(x,extra),x.f);assert.equal(r.status,201,JSON.stringify(r.body));return r.body.slot;}
async function book(x,s,child='one',status='booked',extra={},who=x.f,key){const p=trainingPlan(x.db,x.plans[child].id);return write(x,'/api/customers/'+child+'/scheduling',{plan_id:p.id,plan_version:p.current_version,expected_plan_revision:p.revision,slot_id:s.id,slot_revision:s.revision,status,...note,...extra},who,key);}
async function event(x,b,action,extra={},who=x.f,key){const now=scheduleBooking(x.db,b.id),p=trainingPlan(x.db,now.plan_id);return write(x,'/api/scheduling/bookings/'+b.id+'/events',{action,expected_revision:now.revision,...(!['cancel','leave'].includes(action)?{expected_plan_revision:p.revision}:{}),...note,...extra},who,key);}
const all=db=>Object.fromEntries(schedulingTables.map(t=>[t,db.prepare('SELECT * FROM '+t+' ORDER BY rowid').all()]));
function tamper(db,t,sql){const trig=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(t+'_no_update').sql;db.exec('DROP TRIGGER '+t+'_no_update');db.exec(sql);db.exec(trig);}

test('explicit employee room and equipment reserve time while customer booking remains separate from course and money',async t=>{const x=await setup(t),s=await slot(x),r=await book(x,s);assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.booking.plan_version,1);assert.equal(r.body.booking.slot.resources.length,3);assert.equal(scheduleSlot(x.db,s.id).booked,1);assert.equal(x.db.prepare('SELECT count(*) n FROM training_sessions').get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM entitlement_events').get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM payment_events').get().n,0);verifyScheduling(x.db);});
test('same resources conflict in overlap and exact adjacent intervals are allowed with zero buffers',async t=>{const x=await setup(t);await slot(x);assert.equal((await write(x,'/api/scheduling/slots',slotInput(x,{starts_at:'2030-01-01T10:59:59.999Z',ends_at:'2030-01-01T12:00:00.000Z'}))).status,409);await slot(x,{starts_at:'2030-01-01T11:00:00.000Z',ends_at:'2030-01-01T12:00:00.000Z'});verifyScheduling(x.db);});
test('explicit prepare and cleanup buffers lock per-resource intervals and preserve exact adjacency',async t=>{const x=await setup(t);const i=resource({name:'员工资源',buffer_before:10,buffer_after:5});delete i.code;delete i.kind;delete i.user_id;const r=await write(x,'/api/scheduling/resources/'+x.staff.id+'/versions',{...i,expected_version:1});assert.equal(r.status,201);x.staff=r.body.resource;await slot(x);assert.equal((await write(x,'/api/scheduling/slots',slotInput(x,{starts_at:'2030-01-01T11:14:59.999Z',ends_at:'2030-01-01T12:00:00.000Z'}))).status,409);await slot(x,{starts_at:'2030-01-01T11:15:00.000Z',ends_at:'2030-01-01T12:00:00.000Z'});verifyScheduling(x.db);});
test('maintenance is manager-only resource occupancy and cancelling its empty slot releases the time',async t=>{const x=await setup(t),i=slotInput(x,{kind:'maintenance',capacity:0,resources:[{id:x.eq.id,version:1}]});assert.equal((await write(x,'/api/scheduling/slots',i,x.f)).status,403);const r=await write(x,'/api/scheduling/slots',i);assert.equal(r.status,201);assert.equal((await book(x,r.body.slot)).status,409);assert.equal((await write(x,'/api/scheduling/slots',slotInput(x))).status,409);assert.equal((await write(x,'/api/scheduling/slots/'+r.body.slot.id+'/events',{action:'cancel',expected_revision:1,...note})).status,201);await slot(x);verifyScheduling(x.db);});
test('group capacity and waiting queue are separate; cancellation never auto-promotes and explicit promotion rechecks capacity',async t=>{const x=await setup(t),s=await slot(x,{kind:'group',capacity:1}),first=(await book(x,s)).body.booking;assert.equal((await book(x,s,'two')).status,409);const w=(await book(x,s,'two','waiting')).body.booking;assert.equal(w.queue_position,1);assert.equal((await event(x,w,'promote')).status,409);assert.equal((await event(x,first,'cancel')).status,201);assert.equal(scheduleBooking(x.db,w.id).status,'waiting');assert.equal((await event(x,w,'promote')).status,201);assert.equal(scheduleSlot(x.db,s.id).booked,1);verifyScheduling(x.db);});
test('manual group capacity cannot exceed any explicit resource capacity and same customer cannot join twice',async t=>{const x=await setup(t);assert.equal((await write(x,'/api/scheduling/slots',slotInput(x,{kind:'group',capacity:3}))).status,409);const s=await slot(x,{kind:'group',capacity:2});assert.equal((await book(x,s)).status,201);assert.equal((await book(x,s,'one','waiting')).status,409);assert.equal((await book(x,s,'two')).status,201);verifyScheduling(x.db);});
test('single-customer move retains original event/plan and does not alter group peers or other slots',async t=>{const x=await setup(t),s=await slot(x,{kind:'group',capacity:2}),dest=await slot(x,{starts_at:'2030-01-02T10:00:00.000Z',ends_at:'2030-01-02T11:00:00.000Z'}),a=(await book(x,s)).body.booking,b=(await book(x,s,'two')).body.booking,old=scheduleBooking(x.db,b.id);const r=await event(x,a,'move',{slot_id:dest.id,slot_revision:1});assert.equal(r.status,201);assert.equal(r.body.booking.plan_id,a.plan_id);const peer=scheduleBooking(x.db,b.id);assert.deepEqual(peer.history,old.history);assert.equal(peer.slot_id,old.slot_id);assert.equal(peer.plan_version,old.plan_version);assert.equal(r.body.booking.history[1].slot_id,s.id);assert.equal(scheduleSlot(x.db,s.id).booked,1);verifyScheduling(x.db);});
test('occupied slot cannot be bulk revised or cancelled; waiting moved retains waiting state and receives destination queue order',async t=>{const x=await setup(t),s=await slot(x),dest=await slot(x,{starts_at:'2030-01-02T10:00:00.000Z',ends_at:'2030-01-02T11:00:00.000Z'}),w=(await book(x,s,'one','waiting')).body.booking;assert.equal((await write(x,'/api/scheduling/slots/'+s.id+'/events',{action:'revise',expected_revision:1,...slotInput(x)})).status,409);assert.equal((await write(x,'/api/scheduling/slots/'+s.id+'/events',{action:'cancel',expected_revision:1,...note})).status,409);const r=await event(x,w,'move',{slot_id:dest.id,slot_revision:1});assert.equal(r.status,201);assert.equal(r.body.booking.status,'waiting');assert.equal(r.body.event.queue_sequence,r.body.event.sequence);verifyScheduling(x.db);});
test('leave cancels only booked occurrence; later empty slot revision never rewrites cancelled booking or timeline date',async t=>{const x=await setup(t),s=await slot(x),b=(await book(x,s)).body.booking;assert.equal((await event(x,b,'leave')).status,201);assert.equal((await write(x,'/api/scheduling/slots/'+s.id+'/events',{action:'revise',expected_revision:1,...slotInput(x,{starts_at:'2030-01-02T10:00:00.000Z',ends_at:'2030-01-02T11:00:00.000Z'})})).status,201);assert.equal(scheduleBooking(x.db,b.id).slot.starts_at,s.starts_at);const r=await x.request('/api/customers/one/scheduling?from=2030-01-01T00%3A00%3A00.000Z&to=2030-01-02T00%3A00%3A00.000Z',x.m);assert.equal(r.body.total,1);verifyScheduling(x.db);});
test('resource version drift preserves old slot references but blocks new admissions until explicitly replaced',async t=>{const x=await setup(t),s=await slot(x),r=resource({capacity:1,status:'inactive'});for(const k of ['code','kind','user_id'])delete r[k];assert.equal((await write(x,'/api/scheduling/resources/'+x.room.id+'/versions',{...r,expected_version:1})).status,201);assert.equal(scheduleSlot(x.db,s.id).resources.find(r=>r.id===x.room.id).capacity,2);assert.equal((await book(x,s)).status,409);verifyScheduling(x.db);});
test('later plan pause or revision blocks new registration and promotion while historical cancellation remains possible',async t=>{const x=await setup(t),s=await slot(x),b=(await book(x,s,'one','waiting')).body.booking;insertTrainingPlanEvent(x.db,x.plans.one.id,{action:'pause',...note},'professional');assert.equal((await event(x,b,'promote')).status,409);assert.equal((await event(x,b,'cancel')).status,201);verifyScheduling(x.db);});
test('source scope and roles enforce manager resource/maintenance, front bookings, professional read-only and guardian isolation',async t=>{const x=await setup(t),s=await slot(x);assert.equal((await write(x,'/api/scheduling/resources',resource(),x.f)).status,403);assert.equal((await book(x,s,'one','booked',{},x.pro)).status,403);assert.equal((await x.request('/api/scheduling/slots',x.pro)).status,200);assert.equal((await x.request('/api/scheduling/slots/'+s.id,await x.login('other'))).status,404);assert.equal((await x.request('/api/customers/one/scheduling',await x.login('parent'))).status,403);assert.equal((await write(x,'/api/scheduling/resources',resource({kind:'staff',user_id:'other'}))).status,422);});
test('strict UTC leap dates, resource arrays, capacities and unknown clinical/financial fields reject without writes',async t=>{const x=await setup(t),before=all(x.db);for(const extra of [{starts_at:'2030-02-29T10:00:00.000Z'},{ends_at:'2030-01-01T09:00:00.000Z'},{capacity:2},{resources:[{id:x.room.id,version:1}]},{resources:[{id:x.room.id,version:1},{id:x.room.id,version:1}]},{resources:[{id:x.room.id,version:1,capacity:5}]},{deduction:1}])assert.equal((await write(x,'/api/scheduling/slots',slotInput(x,extra))).status,422);assert.deepEqual(all(x.db),before);assert.equal((await write(x,'/api/scheduling/resources',resource({capacity:1.5}))).status,422);assert.equal((await x.request('/api/scheduling/slots?from=no',x.m)).status,422);});
test('global lease and identical retry prevent duplicate booking and concurrent last-seat contenders produce one winner',async t=>{const x=await setup(t),s=await slot(x),seq=scheduleSequence(x.db,'a'),keys=[crypto.randomUUID(),crypto.randomUUID()],p=x.plans.one,data={expected_sequence:seq,plan_id:p.id,plan_version:1,expected_plan_revision:p.revision,slot_id:s.id,slot_revision:1,status:'booked',...note},paths=['/api/customers/one/scheduling','/api/customers/two/scheduling'],inputs=[data,{...data,plan_id:x.plans.two.id}];const results=await Promise.all(paths.map((path,i)=>write(x,path,inputs[i],x.f,keys[i])));assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);const winner=results.findIndex(r=>r.status===201),retry=await write(x,paths[winner],inputs[winner],x.f,keys[winner]);assert.equal(retry.status,201);assert.equal(scheduleSlot(x.db,s.id).booked,1);assert.equal((await write(x,paths[winner],{...inputs[winner],note:'不同'},x.f,keys[winner])).status,409);verifyScheduling(x.db);});
test('concurrent waitlist promotion with one remaining seat and stale cancel/move each save exactly one valid intent',async t=>{const x=await setup(t),s=await slot(x),a=(await book(x,s,'one','waiting')).body.booking,b=(await book(x,s,'two','waiting')).body.booking,seq=scheduleSequence(x.db,'a');const r=await Promise.all([event(x,a,'promote',{expected_sequence:seq}),event(x,b,'promote',{expected_sequence:seq})]);assert.deepEqual(r.map(x=>x.status).sort(),[201,409]);assert.equal(scheduleSlot(x.db,s.id).booked,1);verifyScheduling(x.db);});
test('audit insert failure atomically rolls resource slot booking roots/events and idempotency back and permits original retry',async t=>{const x=await setup(t),s=await slot(x),before=all(x.db),seq=scheduleSequence(x.db,'a'),key=crypto.randomUUID();x.db.exec("CREATE TRIGGER schedule_test_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'schedule.%' BEGIN SELECT RAISE(ABORT,'forced'); END");const r=await book(x,s,'one','booked',{expected_sequence:seq},x.f,key);assert.equal(r.status,500);assert.deepEqual(all(x.db),before);assert.equal((await write(x,'/api/scheduling/resources',resource())).status,500);assert.deepEqual(all(x.db),before);x.db.exec('DROP TRIGGER schedule_test_audit');assert.equal((await book(x,s,'one','booked',{expected_sequence:seq},x.f,key)).status,201);verifyScheduling(x.db);});
test('native immutable and source/capacity guards reject direct modifications and invalid event admissions',async t=>{const x=await setup(t),s=await slot(x);await book(x,s);for(const table of schedulingTables)assert.throws(()=>x.db.exec('DELETE FROM '+table));assert.throws(()=>createSlot(x.db,'a',{...slotInput(x),resources_json:JSON.stringify([{id:x.room.id,version:1}])},'front'));assert.throws(()=>createBooking(x.db,'a','two',x.plans.two,{status:'booked',slot_id:s.id,...note},'front'));assert.throws(()=>createResource(x.db,'a',resource({capacity:0}),'manager'));assert.throws(()=>slotEvent(x.db,s.id,{action:'cancel',...note},'front'));});
test('customer timeline locates appointment original times and professional reads without funds or purchase proof',async t=>{const x=await setup(t),s=await slot(x),b=(await book(x,s)).body.booking;await event(x,b,'cancel');const r=await x.request('/api/customers/one/timeline?kind=scheduling',x.pro);assert.equal(r.status,200);assert.equal(r.body.items.length,2);assert.equal(r.body.items[0].entity_id,b.id);assert.equal(r.body.items[0].details.starts_at,s.starts_at);assert.equal(JSON.stringify(r.body).includes('basis_reference'),false);});
test('backup and independent restore preserve all six scheduling tables and clear recovered sessions',async t=>{const x=await setup(t,{persist:true}),s=await slot(x);await book(x,s);await book(x,s,'two','waiting');const before=all(x.db),b=await createBackup(x.path,join(x.dir,'backup')),r=await restoreBackup(b.backup,join(x.dir,'restored')),db=openDatabase(r.database);assert.deepEqual(all(db),before);assert.equal(db.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyScheduling(db);db.close();});
test('recovery rejects altered initial event actor with native guards restored',async t=>{const x=await setup(t),s=await slot(x);await book(x,s);tamper(x.db,'schedule_slot_events',"UPDATE schedule_slot_events SET created_by='manager' WHERE slot_id='"+s.id+"'");assert.throws(()=>verifyScheduling(x.db),/核对失败/);});
test('nonempty schema25 upgrade retains all old rows and does not invent resources or appointments',async t=>{const x=await setup(t),path=join(x.dir,'old.sqlite'),d=new DatabaseSync(path),migrations=readdirSync(new URL('../migrations/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort();for(const n of migrations.slice(0,25))d.exec(readFileSync(new URL('../migrations/'+n,import.meta.url),'utf8'));d.exec('CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const n of migrations.slice(0,25))d.prepare('INSERT INTO schema_migrations VALUES (?,?)').run(n,new Date().toISOString());d.exec("INSERT INTO stores VALUES('old','old')");const before=d.prepare('SELECT * FROM stores').all();d.close();const upgraded=openDatabase(path);assert.deepEqual(upgraded.prepare('SELECT * FROM stores').all(),before);for(const t of schedulingTables)assert.equal(upgraded.prepare('SELECT count(*) n FROM '+t).get().n,0);verifyScheduling(upgraded);upgraded.close();});
test('over one hundred resource matches keep complete totals and bounded pages without invented capacity defaults',async t=>{const x=await setup(t);for(let n=0;n<102;n++)createResource(x.db,'a',resource({code:'BULK-'+n,name:'分页 '+n}),'manager');const r=await x.request('/api/scheduling/resources?limit=100',x.m);assert.equal(r.status,200);assert.equal(r.body.total,105);assert.equal(r.body.items.length,100);assert.equal(r.body.next_offset,100);assert.equal((await x.request('/api/scheduling/resources?limit=100&offset=100',x.m)).body.items.length,5);verifyScheduling(x.db);});
test('resource revisions in the same millisecond cannot be substituted into earlier slot references',async t=>{const x=await setup(t),s=await slot(x),time=x.db.prepare('SELECT created_at FROM schedule_slot_events WHERE slot_id=?').get(s.id).created_at,r=resource({name:'后来房间'});resourceVersion(x.db,x.room.id,r,'manager',time);verifyScheduling(x.db);const refs=JSON.parse(s.resources_json).map(r=>({...r,version:r.id===x.room.id?2:r.version}));const guard=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='schedule_slot_events_no_update'").get().sql;x.db.exec('DROP TRIGGER schedule_slot_events_no_update');x.db.prepare('UPDATE schedule_slot_events SET resources_json=? WHERE slot_id=?').run(JSON.stringify(refs),s.id);x.db.exec(guard);assert.throws(()=>verifyScheduling(x.db),/核对失败/);});
test('revoked session and forced password cannot write resource or appointment data',async t=>{const x=await setup(t),s=await slot(x);x.db.prepare('DELETE FROM sessions WHERE user_id=?').run('front');assert.equal((await book(x,s)).status,401);x.db.prepare('INSERT INTO user_security(user_id,must_change_password,revision) VALUES (?,1,1) ON CONFLICT(user_id) DO UPDATE SET must_change_password=1').run('manager');assert.equal((await write(x,'/api/scheduling/resources',resource())).status,403);assert.equal(x.db.prepare('SELECT count(*) n FROM schedule_bookings').get().n,0);});
test('synthetic scheduling extends only its six tables and repeated seeding never replaces human arrangements',async t=>{const x=await fixture(t),d=x.db;d.exec("INSERT INTO stores VALUES ('store-a','示例门店')");for(const [id,role] of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');for(const fn of [demo.seedDemoScenarios,demo.seedDemoRetail,demo.seedDemoInventory,demo.seedDemoPayments,demo.seedDemoProcessing,demo.seedDemoFulfillment,demo.seedDemoAftercare,demo.seedDemoAftercareWork,demo.seedDemoReplacements,demo.seedDemoDispositions,demo.seedDemoRefunds,demo.seedDemoParameters,demo.seedDemoTraining,demo.seedDemoEntitlements])fn(d);const names=['training_plans','training_plan_versions','training_plan_events','training_session_events','entitlement_events','payment_events','inventory_events','task_events'],before=names.map(n=>d.prepare('SELECT * FROM '+n).all());assert.deepEqual(demo.seedDemoScheduling(d),{resources:3,resource_versions:4,slots:4,slot_events:5,bookings:3,booking_events:4});assert.deepEqual(names.map(n=>d.prepare('SELECT * FROM '+n).all()),before);const snapshot=all(d);assert.deepEqual(demo.seedDemoScheduling(d),{resources:0,resource_versions:0,slots:0,slot_events:0,bookings:0,booking_events:0});assert.deepEqual(all(d),snapshot);verifyScheduling(d);});
