import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as S from '../src/specialty.mjs';
import {verifySpecialty} from '../src/specialty-recovery.mjs';
import {createHash} from 'node:crypto';
const now=()=>new Date().toISOString(),note=()=>({note:'明确本地记录（虚构）',reason:'实际来源核对'}),pi=()=>({...Object.fromEntries(S.protocolFields.map(k=>[k,k==='title'?'接触镜条件来源（虚构）':'明确人工来源，未知规则不补造：'+k])),require_assessment_evidence:false,require_consent_evidence:false,...note()}),ci=()=>({title:'专项评估（虚构）',assessment_note:'资料尚待专业明确核对',suitability:'pending',suitability_note:'未知，不推定适用',assessed_at:null,source_note:'仅虚构人工资料',next_step:'由明确专业责任人继续评估',document_ids:[],attachment_ids:[],...note()}),signed=()=>({party:'guardian',party_label:'虚构监护人',relationship_note:'明确虚构身份与关系来源；不从查看授权推定',signed_at:new Date(Date.now()-1000).toISOString(),source_note:'明确记录本版本知情同意来源，非真实签署',document_ids:[],attachment_ids:[],...note()});
async function setup(t,opts){const x=await fixture(t,opts);x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('cycle-one','one','retail','明确配镜需求','draft',now(),'front');return {...x,m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')};}
const seq=x=>S.specialtySequence(x.db,'a');
async function post(x,path,u,data,key){return x.request('/api/specialty/'+path,{...u,method:'POST',data:{expected_sequence:seq(x),...data},...(key?{key}:{})});}
async function protocol(x,extra={},adopt=true){let z=await post(x,'protocols',x.m,{code:'DEMO-'+crypto.randomUUID().slice(0,8),service_type:'contact_lens',...pi(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));let r=z.body.record;if(adopt){z=await post(x,'protocols/'+r.id+'/events',x.m,{expected_revision:r.revision,expected_version:r.version,action:'adopt',...note()});assert.equal(z.status,201,JSON.stringify(z.body));r=z.body.record;}return r;}
async function fitting(x,p,extra={},u=x.f){const z=await post(x,'cases',u,{customer_id:'one',protocol_id:p.id,protocol_version:p.current_version,protocol_revision:p.revision,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function cv(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/versions',x.p,{expected_revision:r.revision,expected_version:r.current_version,...ci(),suitability:'suitable',suitability_note:'由本条专业责任人明确记录的虚构判断',assessed_at:new Date(Date.now()-1000).toISOString(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function consent(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/consents',x.f,{expected_case_revision:r.revision,...signed(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function event(x,c,action,extra={},u=action==='assign'?x.m:x.p){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/events',u,{expected_revision:r.revision,expected_version:r.current_version,action,next_step:'保留明确后续',...note(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
const snapshot=db=>Object.fromEntries(S.specialtyTables.map(n=>[n,db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
function proof(x,customer='one',id=crypto.randomUUID()){const b=Buffer.from('synthetic specialty source; no true signature'),hash=createHash('sha256').update(b).digest('hex');x.db.prepare('INSERT OR IGNORE INTO attachment_blobs VALUES(?,?,?)').run(hash,b,b.length);x.db.prepare('INSERT INTO attachments(id,customer_id,filename,content_type,blob_sha256,size,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,customer,'specialty-source.txt','text/plain',hash,b.length,now(),'front');return id;}

import * as T from '../src/specialty-trace.mjs';
import {verifySpecialtyTrace} from '../src/specialty-trace-recovery.mjs';
import {insertParameterVersion,insertParameterEvent} from '../src/parameters.mjs';
import {insertProcessingJob,insertProcessingEvent,processingRecord} from '../src/processing.mjs';
import {insertFulfillmentEvent,fulfillmentRecord} from '../src/fulfillment.mjs';
import {parameterContext} from '../src/parameter-ledger.mjs';
async function traceSetup(t,opts){const x=await setup(t,opts),pr=await protocol(x);let c=await fitting(x,pr);c=await cv(x,c);const a=await consent(x,c);c=await event(x,c,'adopt',{consent_id:a.id,consent_revision:a.revision});const prod=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'CL-'+crypto.randomUUID().slice(0,8),name:'虚构镜片订片',category:'lens',brand:null,specification:'仅演示来源，非临床参数',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(prod.status,201,JSON.stringify(prod.body));const o=await x.request('/api/customers/one/retail-orders',{...x.f,method:'POST',data:{title:'专项原单（虚构）',notes:null,cycle_id:'cycle-one',cycle_version:1,visit_id:null,items:[{product_id:prod.body.product.id,product_version:1,quantity:2,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构'}});assert.equal(o.status,201,JSON.stringify(o.body));Object.assign(x,{c,a,pr,order:o.body.order,product:prod.body.product});checkParam(x);return x;}
function checkParam(x){const p=insertParameterVersion(x.db,x.order.id,{source:'staff_record',source_note:'虚构来源，不代替正式处方',values:[{position:1,label:'虚构交接项',value:'样例交接值',unit:null,condition:null}],document_version_ids:[],attachment_ids:[],...note()},'front').parameter;insertParameterEvent(x.db,p.id,{action:'submit',...note()},'front');insertParameterEvent(x.db,p.id,{action:'check',...note()},'professional');return p.id;}
function approvalInput(x){const z=T.approvalCandidates(x.db,x.order.id),c=S.specialtyCase(x.db,x.c.id);return {expected_sequence:T.traceSequence(x.db,'a'),case_id:c.id,expected_order_version:1,expected_case_revision:c.revision,expected_specialty_sequence:seq(x),expected_approval_revision:T.specialtyOrderContext(x.db,x.order.id)?.approval_revision||0,parameter_version_id:z.parameter.id,expected_parameter_sequence:z.parameter.sequence,...note()};}
const approve=(x,who=x.p,extra={},key)=>x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/approvals',{...who,method:'POST',data:{...approvalInput(x),...extra},key});
async function approved(x){const z=await approve(x);assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
function job(x){const j=insertProcessingJob(x.db,x.order.id,{lines:[{position:1,supply_mode:'purchase',processing_mode:'internal',supplier_name:'虚构供应方',assignee_id:'professional',due_date:null,instructions:'仅虚构交接'}],reason:'虚构'},'manager');x.job=j;return j;}
function received(x){job(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:2,reason:'虚构实际到货'},'front');return x.db.prepare("SELECT * FROM processing_events WHERE job_id=? AND action='receive'").get(x.job.id);}
const li=(extra={})=>({trace_status:'recorded',lot_number:'DEMO-LOT-ONLY',serial_note:'序列尚未知，明确原来源',manufacturer_note:'虚构生产来源',supplier_note:'虚构供货来源',source_note:'虚构原包装批号，不代表真实产品',document_ids:[],attachment_ids:[],...note(),...extra});
async function lot(x,e,extra={},key){return x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/lots',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),receive_event_id:e.id,quantity:2,...li(extra)},key});}
async function revision(x,l,extra={}){return x.request('/api/specialty-lots/'+l.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),expected_revision:l.revision,...li(extra)}});}
async function revoke(x){return post(x,'consents/'+x.a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});}
async function process(x,action,key){const p=processingRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/events',{...x.p,method:'POST',key,data:{expected_revision:p.revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action,position:1,quantity:2,reason:'虚构实际执行'}});}
function finished(x){insertProcessingEvent(x.db,x.job.id,{action:'start',position:1,quantity:2,reason:'虚构'},'professional');insertProcessingEvent(x.db,x.job.id,{action:'complete',position:1,quantity:2,reason:'虚构'},'professional');}
async function qc(x){const f=fulfillmentRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/fulfillment/events',{...x.p,method:'POST',data:{expected_revision:f.revision,expected_processing_revision:f.processing_revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action:'check_pass',position:1,quantity:2,source_id:null,checks:[{label:'虚构明确检查项',result:'pass',notes:'虚构检查事实'}],reason:'虚构检查'}});}
const verify=x=>{verifySpecialty(x.db);verifySpecialtyTrace(x.db);};

import * as C from '../src/specialty-care.mjs';
import * as R from '../src/specialty-review.mjs';
import {verifySpecialtyReviews} from '../src/specialty-review-recovery.mjs';
import * as L from '../src/longitudinal.mjs';
import * as F from '../src/referrals.mjs';
import * as K from '../src/contact.mjs';
const manifest=()=>({documents:[],attachments:[],observations:[],external_records:[]}),ri=(extra={})=>({title:'原镜片复查（虚构）',participant_label:'虚构实际反馈人',relationship_note:'明确人工身份来源，不推定监护授权',reported_at:now(),measured_at:null,eye:'both',condition_status:'unknown',condition_note:'条件尚未齐全，保留明确未知',source_kind:'customer_report',due_date:null,source_note:'仅虚构反馈原文来源',feedback_note:'虚构佩戴反馈，不生成临床结论',findings_note:'实际检查待核对，不补默认指标',issue_note:'损坏/遗失等实际情况依来源记录',arrangement_note:'下一安排按专业实际来源明确',manifest:manifest(),next_step:'由专业责任人继续核对',...note(),...extra});
async function reviewSetup(t,opts){const x=await traceSetup(t,opts);await approved(x);const e=received(x);await lot(x,e);finished(x);const q=insertFulfillmentEvent(x.db,x.job.id,{action:'check_pass',position:1,quantity:2,checks:[{label:'虚构原检查项',result:'pass',notes:'仅明确虚构来源'}],reason:'虚构'},'professional').event;x.quality=q;if(opts?.careBefore){const i={...Object.fromEntries(C.careFields.map(k=>[k,'仅虚构原护理来源 '+k])),guided_at:now(),outcome:'demonstrated',document_ids:[],attachment_ids:[],require_demonstration:true,requirement_source_note:'明确虚构原要求，非临床规则',timing:'before_handover',delivery_id:null,...note()};x.care=C.createCare(x.db,C.careQuality(x.db,q.id),i,'professional');for(const action of ['review','release'])C.careEvent(x.db,x.care.id,{action,next_step:'明确后续',...note()},'professional');}x.delivery=insertFulfillmentEvent(x.db,x.job.id,{action:'deliver',position:1,quantity:1,source_id:q.id,receiver_name:'虚构实际领取人',receipt_note:'明确原签收',handed_at:now(),reason:'虚构'},'front').event;return x;}
const reviewLease=x=>({expected_sequence:R.reviewSequence(x.db,'a'),expected_specialty_sequence:seq(x)});
async function review(x,extra={},who=x.f,key){return x.request('/api/specialty-reviews',{...who,method:'POST',key,data:{...reviewLease(x),delivery_id:x.delivery.id,category:'routine',root_source_note:'实际原产品后续来源（虚构）',expected_case_revision:S.specialtyCase(x.db,x.c.id).revision,...ri(extra)}});}
async function reviewedRoot(x,extra={}){const z=await review(x,extra);assert.equal(z.status,201,JSON.stringify(z.body));x.review=z.body.record;return x.review;}
async function rv(x,extra={},who=x.f){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/versions',{...who,method:'POST',data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,...ri(extra)}});}
async function re(x,decision='not_assessed',extra={},who=x.p,key){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/events',{...who,method:'POST',key,data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,action:'confirm',decision,evaluated_at:now(),opinion_note:'专业明确原版本处置意见（虚构）',next_step:'明确下一安排，不补默认方法或频率',...note(),...extra}});}
async function end(x,action='close'){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/events',{...x.p,method:'POST',data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,action,next_step:'明确保留后续资料安排',...note()}});}
async function link(x,kind,source,who=x.f,extra={}){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/links',{...who,method:'POST',data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,kind,source,source_note:'明确已有后续原记录关联',next_step:'仍由对应责任人继续办理',...note(),...extra}});}
const verifyReview=x=>{verify(x);verifySpecialtyReviews(x.db);};
function outside(x,customer='one'){const r=F.createExternalRecord(x.db,'a',customer,{kind:'external_report',title:'外院原资料（虚构）',institution:'虚构机构',reported_at:now(),measured_at:null,eye:'both',condition_status:'unknown',condition_note:'实际条件尚未知',source_note:'虚构原报告转录',record_note:'保留原文，不生成诊断',document_ids:[],attachment_ids:[],owner_id:'professional',...note()},'front');return F.externalRecordEvent(x.db,r.id,{action:'confirm',opinion_note:'专业明确原文及限制',next_step:'保留后续',...note()},'professional');}
function long(x){x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('followup-one','one','followup','明确后续需求','draft',now(),'front');const i={title:'长期来源（虚构）',baseline_note:'尚未取得',goal_note:'核对原资料',source_note:'明确人工来源',manifest:L.emptyLongitudinalManifest(),reason:'虚构',cycle_id:'followup-one',cycle_version:1},c=L.createLongitudinalCase(x.db,'a','one',i,'professional');L.longitudinalCaseEvent(x.db,c.id,{action:'activate',...note()},'professional');const o=L.createObservation(x.db,c.id,{measured_at:now(),eye:'both',condition_status:'unknown',condition_note:'条件仍未知',source:'staff_record',source_note:'明确实际记录来源',record_note:'虚构检查原文，不生成指标',manifest:L.emptyLongitudinalManifest(),reason:'虚构'},'professional');const p=L.createReviewPlan(x.db,c.id,{due_date:'2026-10-01',purpose:'明确下一复查',items_note:'实际检查项待核对',owner_id:'professional',source_note:'实际明确日期，不生成默认频率',manifest:L.emptyLongitudinalManifest(),...note()},'professional');return {c,o,p};}
function actualContact(x){const g=K.createContactConsent(x.db,'a','one',{category:'service',channel:'phone',recipient_label:'虚构反馈人',address:'synthetic-only',source_note:'明确人工服务联系授权',effective_at:now(),...note()},'front'),c=K.createContactCase(x.db,'a','one',{purpose:'followup',source:{kind:'manual',id:null,version:null,revision:null},source_note:'实际后续来源',title:'虚构人工联系',purpose_note:'核对复查安排',due_at:now(),next_action:'等待实际回执',owner_id:'front',...note()},'front');return K.recordContactAttempt(x.db,c.id,{consent_id:g.id,consent_revision:1,occurred_at:now(),result:'sent',source_note:'实际发出来源',content_summary:'虚构复查安排',result_note:'已发出，回执未知',due_at:now(),next_action:'等待实际回执',reason:'明确来源'},'front');}
function tamper(db,t,sql,args=[]){const name=t+'_no_update',s=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(name).sql;db.exec('DROP TRIGGER '+name);db.prepare(sql).run(...args);db.exec(s);}
test('actual signed product, original lot/care sources and uncertain feedback stay separate from professional opinion',async t=>{const x=await reviewSetup(t),r=await reviewedRoot(x,{category:'discomfort'});assert.equal(r.status,'pending');assert.equal(r.opinion,null);assert.equal(r.source.quantity,1);assert.equal(r.quantity,1);assert.equal(r.case_version,x.c.version);assert.equal(r.care_basis_json,null);assert.equal(S.specialtyCase(x.db,x.c.id).status,'active');verifyReview(x);});
test('only current professional owner confirms actual continue, adjust, referral or unresolved opinions',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);for(const u of [x.f,x.m])assert.equal((await re(x,'continue',{},u)).status,403);const z=await re(x,'continue');assert.equal(z.status,201,JSON.stringify(z.body));assert.equal(z.body.record.opinion.decision,'continue');assert.equal(z.body.record.opinion.created_by,'professional');assert.equal(S.specialtyCase(x.db,x.c.id).revision,x.c.revision);assert.equal(x.db.prepare('SELECT count(*) n FROM refund_events').get().n,0);verifyReview(x);});
test('a new feedback version returns pending while old professional opinion stays bound to its exact source',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);await re(x,'adjust');assert.equal((await rv(x,{feedback_note:'追加客户新的实际反馈'})).status,201);const r=R.specialtyReview(x.db,x.review.id);assert.equal(r.status,'pending');assert.equal(r.opinion,null);const old=R.specialtyReview(x.db,r.id,{version:1});assert.equal(old.opinion.decision,'adjust');assert.ok(!old.feedback_note.includes('新的'));verifyReview(x);});
test('professional pause records the clinical effect atomically and blocks subsequent signature without changing money',async t=>{const x=await reviewSetup(t);await reviewedRoot(x,{category:'discomfort'});const z=await re(x,'pause');assert.equal(z.status,201,JSON.stringify(z.body));assert.equal(S.specialtyCase(x.db,x.c.id).status,'paused');assert.equal(x.db.prepare('SELECT action FROM specialty_case_events WHERE id=?').get(z.body.record.opinion.effect_case_event_id).action,'pause');assert.throws(()=>insertFulfillmentEvent(x.db,x.job.id,{action:'deliver',position:1,quantity:1,source_id:x.quality.id,receiver_name:'虚构',receipt_note:'虚构',handed_at:now(),reason:'虚构'},'front'),/specialty/);assert.equal(x.db.prepare('SELECT count(*) n FROM refund_events').get().n,0);verifyReview(x);});
test('explicit stop freezes the original specialty but retains original feedback and future archival facts',async t=>{const x=await reviewSetup(t);await reviewedRoot(x,{category:'other_issue'});assert.equal((await re(x,'stop')).status,201);assert.equal(S.specialtyCase(x.db,x.c.id).status,'stopped');assert.equal((await end(x)).status,201);assert.equal((await rv(x)).status,409);assert.equal(x.db.prepare('SELECT status FROM service_cycles WHERE id=?').get('cycle-one').status,'draft');const z=await review(x,{category:'lost',source_kind:'unable_measure',measured_at:null});assert.equal(z.status,201,JSON.stringify(z.body));verifyReview(x);});
test('pending cannot be closed as professionally completed, cancellation is explicit and creates no professional opinion',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);assert.equal((await end(x)).status,409);assert.equal((await end(x,'cancel')).status,201);assert.equal(R.specialtyReview(x.db,x.review.id).opinion,null);assert.equal((await rv(x)).status,409);verifyReview(x);});
test('continuation cannot restore withdrawn consent, paused original source or altered assessment version',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);await revoke(x);assert.equal((await re(x,'continue')).status,409);assert.equal((await re(x,'not_assessed')).status,201);verifyReview(x);});
test('unknown or incomparable and unable-measure are retained without fabricated measurements or intervals',async t=>{const x=await reviewSetup(t),r=await reviewedRoot(x,{source_kind:'unable_measure',measured_at:null,condition_status:'incomparable',due_date:null});assert.equal(r.measured_at,null);assert.equal(r.due_date,null);assert.equal((await re(x,'not_assessed')).status,201);assert.equal((await review(x,{source_kind:'unable_measure',measured_at:now()})).status,422);assert.equal((await review(x,{diopters:1})).status,422);verifyReview(x);});
test('fixed confirmed outside source and actual observations require current versions and retain historical adopted sources',async t=>{const x=await reviewSetup(t),a=outside(x),l=long(x),m={...manifest(),observations:[{id:l.o.id,version:1}],external_records:[{id:a.id,version:a.version,revision:a.revision}]};await reviewedRoot(x,{manifest:m});assert.equal((await re(x,'adjust')).status,201);L.observationVersion(x.db,l.o.id,{...l.o,record_note:'追加真实资料更正',manifest:l.o.manifest},'professional');assert.equal((await review(x,{manifest:m})).status,409);const old=R.specialtyReview(x.db,x.review.id,{version:1});assert.equal(old.manifest.observations[0].version,1);verifyReview(x);});
test('changed outside confirmation or observation version blocks a pending professional adoption',async t=>{const x=await reviewSetup(t),a=outside(x);await reviewedRoot(x,{manifest:{...manifest(),external_records:[{id:a.id,version:1,revision:a.revision}]}});F.externalRecordVersion(x.db,a.id,{...a,attachment_ids:[],document_ids:[],record_note:'明确原报告更正',...note()},'professional');assert.equal((await re(x,'adjust')).status,409);verifyReview(x);});
test('revoked or foreign materials do not permit new adoption while original opinion and closure stay readable',async t=>{const x=await reviewSetup(t),id=proof(x);await reviewedRoot(x,{manifest:{...manifest(),attachments:[id]}});await re(x,'adjust');x.db.prepare('UPDATE attachments SET revoked_at=?,revoked_by=?,revocation_reason=? WHERE id=?').run(now(),'front','明确撤销',id);assert.equal((await end(x)).status,201);assert.equal((await review(x,{manifest:{...manifest(),attachments:[id]}})).status,409);assert.equal((await review(x,{manifest:{...manifest(),attachments:[proof(x,'two')]}})).status,409);verifyReview(x);});
test('existing review, referral and actual service contact link exact versions without marking visits or results complete',async t=>{const x=await reviewSetup(t),l=long(x),a=actualContact(x),f=F.createReferralCase(x.db,'a','one',{source:{kind:'manual',id:null,version:null,revision:null},source_note:'明确后续来源',professional_owner_id:'professional',contact_owner_id:'front',title:'虚构转介安排',reason_note:'专业来源待核对',destination:'待实际来源',arrangement_note:'尚未安排',due_at:now(),next_action:'由专业明确安排',...note()},'front');await reviewedRoot(x);for(const[k,s]of [['review_plan',{id:l.p.id,revision:1}],['referral',{id:f.id,revision:1}],['contact_attempt',{id:a.id,revision:a.case_revision}]])assert.equal((await link(x,k,s)).status,201);assert.equal(R.specialtyReview(x.db,x.review.id).links_total,3);assert.equal(L.reviewPlan(x.db,l.p.id).status,'scheduled');assert.equal(F.referralCase(x.db,f.id).status,'draft');assert.equal(K.contactAttempt(x.db,a.id).receipt,null);assert.equal((await link(x,'contact_attempt',{id:'not-an-actual-contact',revision:1})).status,409);verifyReview(x);});
test('stale existing follow-up revisions reject new linkage while original linked versions survive later revisions',async t=>{const x=await reviewSetup(t),l=long(x);await reviewedRoot(x);assert.equal((await link(x,'review_plan',{id:l.p.id,revision:1})).status,201);L.reviewPlanEvent(x.db,l.p.id,{action:'pause',...note()},'professional');assert.equal((await link(x,'review_plan',{id:l.p.id,revision:1})).status,409);assert.equal(R.specialtyReview(x.db,x.review.id).links[0].source.revision,1);verifyReview(x);});
test('clinical pause/stop and review opinion roll back together on audit or direct review insert failure',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);x.db.exec("CREATE TRIGGER review_audit_failure BEFORE INSERT ON audit_events WHEN NEW.action='specialty.review.confirm' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END");assert.equal((await re(x,'stop')).status,500);assert.equal(S.specialtyCase(x.db,x.c.id).status,'active');assert.equal(R.specialtyReview(x.db,x.review.id).status,'pending');x.db.exec('DROP TRIGGER review_audit_failure');assert.throws(()=>R.specialtyReviewEvent(x.db,x.review.id,{action:'confirm',decision:'stop',evaluated_at:now(),opinion_note:'明确停止',next_step:'明确后续',note:'',reason:'虚构'},'professional'),/review/);assert.equal(S.specialtyCase(x.db,x.c.id).status,'active');assert.equal((await re(x,'stop')).status,201);verifyReview(x);});
test('lease, idempotency and permission checks reject professional replay after source withdrawal or responsibility transfer',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);const r=R.specialtyReview(x.db,x.review.id),data={...reviewLease(x),expected_revision:r.revision,expected_version:r.version,action:'confirm',decision:'continue',evaluated_at:now(),opinion_note:'明确继续',next_step:'保留后续',...note()},key='fixed-review-key',path='/api/specialty-reviews/'+r.id+'/events';const z=await x.request(path,{...x.p,method:'POST',data,key});assert.equal(z.status,201);await revoke(x);assert.equal((await x.request(path,{...x.p,method:'POST',data,key})).status,409);assert.equal(R.specialtyReview(x.db,r.id).revision,2);verifyReview(x);});
test('cross-store, guardian, unsupported fields, invalid time and premature feedback fail without partial roots',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);assert.equal((await x.request('/api/specialty-reviews/'+x.review.id,x.g)).status,403);assert.equal((await x.request('/api/specialty-reviews/'+x.review.id,x.o)).status,404);for(const e of [{reported_at:'2020-01-01T00:00:00.000Z'},{reported_at:new Date(Date.now()+60000).toISOString()},{due_date:'2026-02-30'},{category:'diagnosed'},{manifest:{...manifest(),clinical_values:[]}}])assert.ok([409,422].includes((await review(x,e)).status));assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_reviews').get().n,1);verifyReview(x);});
test('native immutable signed-product identities, professional effects and current material guards reject substitutions',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);assert.throws(()=>x.db.exec('UPDATE specialty_reviews SET quantity=2'),/immutable/);assert.throws(()=>R.specialtyReviewEvent(x.db,x.review.id,{action:'confirm',decision:'continue',evaluated_at:now(),opinion_note:'明确继续',next_step:'明确后续',...note()},'front'),/owner/);verifyReview(x);});
test('all four review tables, adopted opinions and links restore independently after later consent withdrawal',async t=>{const x=await reviewSetup(t,{persist:true}),l=long(x);await reviewedRoot(x);await link(x,'review_plan',{id:l.p.id,revision:1});await re(x,'continue');await revoke(x);const b=await createBackup(x.path,join(x.dir,'backup'));assert.equal(b.checks.migrations.length,44);const rr=await restoreBackup(b.backup,join(x.dir,'restore')),d=openDatabase(rr.database);for(const n of R.specialtyReviewTables)assert.deepEqual(d.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());verifySpecialtyReviews(d);assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);d.close();});
test('same-millisecond adopted version and clinical stop effect reject replacing the source with a later version',async t=>{const x=await reviewSetup(t),at=now();const r=R.createSpecialtyReview(x.db,R.signedReviewSource(x.db,x.delivery.id),{category:'routine',root_source_note:'明确虚构',...ri({reported_at:at})},'front',at);R.specialtyReviewEvent(x.db,r.id,{action:'confirm',decision:'stop',evaluated_at:at,opinion_note:'明确停止并留后续',next_step:'明确后续',...note()},'professional',at);R.saveSpecialtyReviewVersion(x.db,r.id,ri({reported_at:at,feedback_note:'同一毫秒后来追加的原来源'}),'front',at);verifyReview(x);const v=x.db.prepare('SELECT id FROM specialty_review_versions WHERE review_id=? AND version=2').get(r.id);tamper(x.db,'specialty_review_events',"UPDATE specialty_review_events SET version_id=? WHERE review_id=? AND action='confirm'",[v.id,r.id]);assert.throws(()=>verifySpecialtyReviews(x.db),/复查/);});
test('bounded paging keeps complete review totals and refuses a changed source sequence on later pages',async t=>{const x=await reviewSetup(t);for(let n=0;n<31;n++)await reviewedRoot(x,{title:'明确原复查 '+n,due_date:'2026-10-01'});const a=await x.request('/api/specialty-reviews?limit=30&as_of=2026-10-10',x.f);assert.equal(a.body.total,31);assert.equal(a.body.items.length,30);assert.equal(a.body.items[0].overdue,true);assert.equal((await x.request('/api/specialty-reviews?offset=30',x.f)).status,409);assert.equal((await x.request('/api/specialty-reviews?offset=30&expected_sequence='+a.body.sequence,x.f)).body.items.length,1);await rv(x);assert.equal((await x.request('/api/specialty-reviews?offset=30&expected_sequence='+a.body.sequence,x.f)).status,409);verifyReview(x);});
import {seedDemoSpecialtyTrace} from '../src/demo-specialty-trace.mjs';
import {seedDemoSpecialtyCare} from '../src/demo-specialty-care.mjs';
import {seedDemoSpecialtyReviews} from '../src/demo-specialty-review.mjs';
function minimalDemo(d){d.exec("INSERT INTO stores VALUES('a','A')");for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');d.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'demo-front');d.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('demo-retail-cycle','sample-retail','retail','虚构需求','draft',now(),'demo-front');seedDemoSpecialty(d);seedDemoSpecialtyTrace(d);seedDemoSpecialtyCare(d);}
test('schema33 nonempty upgrade preserves every original clinical and commercial row and adds four empty review ledgers',t=>{const dir=mkdtempSync(join(tmpdir(),'review-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,33)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}minimalDemo(d);const tables=d.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations' ORDER BY name").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));d.close();const u=openDatabase(path);for(const n of tables)assert.deepEqual(u.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),before[n]);for(const n of R.specialtyReviewTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifySpecialtyReviews(u);assert.equal(u.prepare('SELECT count(*) n FROM schema_migrations').get().n,44);u.close();});
test('four synthetic feedback/adjustment/lost/stopped stages append only their own sources and repeat without replacing earlier facts',()=>{const d=openDatabase(':memory:');minimalDemo(d);const tables=d.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.equal(seedDemoSpecialtyReviews(d).reviews,4);for(const n of tables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all().slice(0,before[n].length),before[n],n);verifySpecialtyReviews(d);verifySpecialty(d);verifySpecialtyTrace(d);const all=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.equal(seedDemoSpecialtyReviews(d).reviews,0);for(const n of tables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),all[n]);d.close();});
test('original signed care version remains part of the product follow-up after later guidance material revision',async t=>{const x=await reviewSetup(t,{careBefore:true});await reviewedRoot(x);const old=JSON.parse(x.review.care_basis_json);assert.equal(old.care_id,x.care.id);const r=C.careRecord(x.db,x.care.id),i={...r,guidance_note:'后续明确护理材料更正',document_ids:r.document_ids,attachment_ids:r.attachment_ids,...note()};C.saveCareVersion(x.db,r.id,i,'professional');assert.equal(JSON.parse(R.specialtyReview(x.db,x.review.id).care_basis_json).version_id,old.version_id);verifyReview(x);});
test('responsibility changes retain original confirmer, reject old owner and permit explicit new-owner review of a new feedback version',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);await re(x,'adjust');x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('pro-two','pro-two','新专业责任人',hashPassword('synthetic-only-password'),'professional','a');await event(x,x.c,'assign',{owner_id:'pro-two'});assert.equal(R.specialtyReview(x.db,x.review.id).opinion.created_by,'professional');await rv(x);assert.equal((await re(x,'adjust')).status,403);assert.equal((await re(x,'adjust',{},await x.login('pro-two'))).status,201);verifyReview(x);});
test('professional request awaiting its body rechecks current source and cannot stop after administrative owner transfer',async t=>{const x=await reviewSetup(t);await reviewedRoot(x);const r=R.specialtyReview(x.db,x.review.id),data={...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,action:'confirm',decision:'stop',evaluated_at:now(),opinion_note:'原窗口明确停用',next_step:'明确后续',...note()},raw=JSON.stringify(data);let req;const result=new Promise((resolve,reject)=>{req=httpRequest(x.origin+'/api/specialty-reviews/'+r.id+'/events',{method:'POST',headers:{Cookie:x.p.cookie,'X-CSRF-Token':x.p.csrf,'Idempotency-Key':'pending-review-body','Content-Type':'application/json','Content-Length':Buffer.byteLength(raw)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);});req.write(raw.slice(0,10));x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('pro-two','pro-two','新专业责任人',hashPassword('synthetic-only-password'),'professional','a');await event(x,x.c,'assign',{owner_id:'pro-two'});req.end(raw.slice(10));assert.ok([403,409].includes(await result));assert.equal(S.specialtyCase(x.db,x.c.id).status,'active');assert.equal(R.specialtyReview(x.db,x.review.id).status,'pending');verifyReview(x);});
