import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as S from '../src/specialty.mjs';
import {verifySpecialty} from '../src/specialty-recovery.mjs';
import {createHash} from 'node:crypto';
const now=()=>new Date().toISOString(),note=()=>({note:'明确本地记录（虚构）',reason:'实际来源核对'}),pi=()=>({...Object.fromEntries(S.protocolFields.map(k=>[k,k==='title'?'接触镜条件来源（虚构）':'明确人工来源，未知规则不补造：'+k])),require_assessment_evidence:false,require_consent_evidence:false,...note()}),ci=()=>({title:'专项评估（虚构）',assessment_note:'资料尚待专业明确核对',suitability:'pending',suitability_note:'未知，不推定适用',assessed_at:null,source_note:'仅虚构人工资料',next_step:'由明确专业责任人继续评估',document_ids:[],attachment_ids:[],...note()}),signed=()=>({party:'guardian',party_label:'虚构监护人',relationship_note:'明确虚构身份与关系来源；不从查看授权推定',signed_at:new Date(Date.now()-1000).toISOString(),source_note:'明确记录本版本知情同意来源，非真实签署',document_ids:[],attachment_ids:[],...note()});
async function setup(t,opts){const x=await fixture(t,opts);x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('cycle-one','one','retail','明确配镜需求','draft',now(),'front');return {...x,m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')};}
const seq=x=>S.specialtySequence(x.db,'a');
async function post(x,path,u,data,key){return x.request('/api/specialty/'+path,{...u,method:'POST',data:{expected_sequence:seq(x),...data},...(key?{key}:{})});}
async function protocol(x,extra={},adopt=true){let z=await post(x,'protocols',x.m,{code:'DEMO-'+crypto.randomUUID().slice(0,8),service_type:'contact_lens',...pi(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));let r=z.body.record;if(adopt){z=await post(x,'protocols/'+r.id+'/events',x.m,{expected_revision:r.revision,expected_version:r.version,action:'adopt',...note()});assert.equal(z.status,201,JSON.stringify(z.body));r=z.body.record;}return r;}
async function fitting(x,p,extra={},u=x.f){const z=await post(x,'cases',u,{customer_id:'one',protocol_id:p.id,protocol_version:p.current_version,protocol_revision:p.revision,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function cv(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/versions',x.p,{expected_revision:r.revision,expected_version:r.current_version,...ci(),suitability:'suitable',suitability_note:'由本条专业责任人明确记录的虚构判断',assessed_at:new Date(Date.now()-1000).toISOString(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function consent(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/consents',x.f,{expected_case_revision:r.revision,...signed(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function event(x,c,action,extra={},u=action==='assign'?x.m:x.p){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/events',u,{expected_revision:r.revision,expected_version:r.current_version,action,next_step:'保留明确后续',...note(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
const snapshot=db=>Object.fromEntries(S.specialtyTables.map(n=>[n,db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
function proof(x,customer='one',id=crypto.randomUUID()){const b=Buffer.from('synthetic specialty source; no true signature'),hash=createHash('sha256').update(b).digest('hex');x.db.prepare('INSERT OR IGNORE INTO attachment_blobs VALUES(?,?,?)').run(hash,b,b.length);x.db.prepare('INSERT INTO attachments(id,customer_id,filename,content_type,blob_sha256,size,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,customer,'specialty-source.txt','text/plain',hash,b.length,now(),'front');return id;}

import * as T from '../src/specialty-trace.mjs';
import {verifySpecialtyTrace} from '../src/specialty-trace-recovery.mjs';
import {insertParameterVersion,insertParameterEvent} from '../src/parameters.mjs';
import {insertProcessingJob,insertProcessingEvent,processingRecord} from '../src/processing.mjs';
import {insertFulfillmentEvent,fulfillmentRecord} from '../src/fulfillment.mjs';
import {parameterContext} from '../src/parameter-ledger.mjs';
async function traceSetup(t,opts){const x=await setup(t,opts),pr=await protocol(x);let c=await fitting(x,pr);c=await cv(x,c);const a=await consent(x,c);c=await event(x,c,'adopt',{consent_id:a.id,consent_revision:a.revision});const prod=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'CL-'+crypto.randomUUID().slice(0,8),name:'虚构镜片订片',category:'lens',brand:null,specification:'仅演示来源，非临床参数',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(prod.status,201,JSON.stringify(prod.body));const o=await x.request('/api/customers/one/retail-orders',{...x.f,method:'POST',data:{title:'专项原单（虚构）',notes:null,cycle_id:'cycle-one',cycle_version:1,visit_id:null,items:[{product_id:prod.body.product.id,product_version:1,quantity:2,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构'}});assert.equal(o.status,201,JSON.stringify(o.body));Object.assign(x,{c,a,pr,order:o.body.order,product:prod.body.product});checkParam(x);return x;}
function checkParam(x){const p=insertParameterVersion(x.db,x.order.id,{source:'staff_record',source_note:'虚构来源，不代替正式处方',values:[{position:1,label:'虚构交接项',value:'样例交接值',unit:null,condition:null}],document_version_ids:[],attachment_ids:[],...note()},'front').parameter;insertParameterEvent(x.db,p.id,{action:'submit',...note()},'front');insertParameterEvent(x.db,p.id,{action:'check',...note()},'professional');return p.id;}
function approvalInput(x){const z=T.approvalCandidates(x.db,x.order.id),c=S.specialtyCase(x.db,x.c.id);return {expected_sequence:T.traceSequence(x.db,'a'),case_id:c.id,expected_order_version:1,expected_case_revision:c.revision,expected_specialty_sequence:seq(x),expected_approval_revision:T.specialtyOrderContext(x.db,x.order.id)?.approval_revision||0,parameter_version_id:z.parameter.id,expected_parameter_sequence:z.parameter.sequence,...note()};}
const approve=(x,who=x.p,extra={},key)=>x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/approvals',{...who,method:'POST',data:{...approvalInput(x),...extra},key});
async function approved(x){const z=await approve(x);assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
function job(x){const j=insertProcessingJob(x.db,x.order.id,{lines:[{position:1,supply_mode:'purchase',processing_mode:'internal',supplier_name:'虚构供应方',assignee_id:'professional',due_date:null,instructions:'仅虚构交接'}],reason:'虚构'},'manager');x.job=j;return j;}
function received(x){job(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:2,reason:'虚构实际到货'},'front');return x.db.prepare("SELECT * FROM processing_events WHERE job_id=? AND action='receive'").get(x.job.id);}
const li=(extra={})=>({trace_status:'recorded',lot_number:'DEMO-LOT-ONLY',serial_note:'序列尚未知，明确原来源',manufacturer_note:'虚构生产来源',supplier_note:'虚构供货来源',source_note:'虚构原包装批号，不代表真实产品',document_ids:[],attachment_ids:[],...note(),...extra});
async function lot(x,e,extra={},key){return x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/lots',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),receive_event_id:e.id,quantity:2,...li(extra)},key});}
async function revision(x,l,extra={}){return x.request('/api/specialty-lots/'+l.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),expected_revision:l.revision,...li(extra)}});}
async function revoke(x){return post(x,'consents/'+x.a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});}
async function process(x,action,key){const p=processingRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/events',{...x.p,method:'POST',key,data:{expected_revision:p.revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action,position:1,quantity:2,reason:'虚构实际执行'}});}
function finished(x){insertProcessingEvent(x.db,x.job.id,{action:'start',position:1,quantity:2,reason:'虚构'},'professional');insertProcessingEvent(x.db,x.job.id,{action:'complete',position:1,quantity:2,reason:'虚构'},'professional');}
async function qc(x){const f=fulfillmentRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/fulfillment/events',{...x.p,method:'POST',data:{expected_revision:f.revision,expected_processing_revision:f.processing_revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action:'check_pass',position:1,quantity:2,source_id:null,checks:[{label:'虚构明确检查项',result:'pass',notes:'虚构检查事实'}],reason:'虚构检查'}});}
const verify=x=>{verifySpecialty(x.db);verifySpecialtyTrace(x.db);};

import * as C from '../src/specialty-care.mjs';
import {verifySpecialtyCare} from '../src/specialty-care-recovery.mjs';
import {insertDispatch} from '../src/dispatch.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
async function careSetup(t,opts){const x=await traceSetup(t,opts);await approved(x);const e=received(x);await lot(x,e);finished(x);const q=insertFulfillmentEvent(x.db,x.job.id,{action:'check_pass',position:1,quantity:2,checks:[{label:'虚构检查项',result:'pass',notes:'明确实际记录'}],reason:'虚构'},'professional').event;x.quality=q;return x;}
const careInput=(extra={})=>({title:'虚构护理指导',participant_label:'虚构当事人',relationship_note:'实际身份来源，不继承家长查看授权',guided_at:null,outcome:'not_assessed',guidance_note:'指导资料待专业核对，不生成护理方法',material_note:'明确虚构原材料说明',practice_note:'尚未记录实际练习',warning_note:'提示内容待实际专业来源',contact_note:'明确联系渠道待人工记录，不发消息',next_step:'由专业人员明确核对实际掌握情况',document_ids:[],attachment_ids:[],...note(),...extra});
const careLease=x=>({expected_sequence:C.careSequence(x.db,'a'),expected_specialty_sequence:seq(x),expected_trace_sequence:T.traceSequence(x.db,'a')});
async function care(x,extra={},who=x.f,key){return x.request('/api/specialty-care',{...who,method:'POST',key,data:{...careLease(x),quality_id:x.quality.id,delivery_id:null,timing:'before_handover',require_demonstration:true,requirement_source_note:'明确演示规则要求掌握，不代表默认临床标准',expected_case_revision:S.specialtyCase(x.db,x.c.id).revision,...careInput(extra)}});}
async function created(x,extra={},who=x.f){const z=await care(x,extra,who);assert.equal(z.status,201,JSON.stringify(z.body));x.care=z.body.record;return x.care;}
async function careVersion(x,extra={},who=x.p){const r=C.careRecord(x.db,x.care.id);return x.request('/api/specialty-care/'+r.id+'/versions',{...who,method:'POST',data:{...careLease(x),expected_revision:r.revision,expected_version:r.current_version,...careInput({guided_at:new Date(Date.now()-1000).toISOString(),outcome:'demonstrated',practice_note:'仅虚构的实际观察意见，不设默认掌握阈值',...extra})}});}
async function careEvent(x,action,who=x.p,key){const r=C.careRecord(x.db,x.care.id);return x.request('/api/specialty-care/'+r.id+'/events',{...who,method:'POST',key,data:{...careLease(x),expected_revision:r.revision,expected_version:r.current_version,action,next_step:'明确后续安排，不自动排期或退款',...note()}});}
async function readyCare(x){await created(x);assert.equal((await careVersion(x)).status,201);assert.equal((await careEvent(x,'review')).status,201);assert.equal((await careEvent(x,'release')).status,201);}
async function deliver(x,key){const f=fulfillmentRecord(x.db,x.job.id),p=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/fulfillment/events',{...x.f,method:'POST',key,data:{expected_revision:f.revision,expected_processing_revision:f.processing_revision,expected_parameter_sequence:p.sequence,expected_parameter_review_revision:p.review_revision,position:1,quantity:1,action:'deliver',source_id:x.quality.id,receiver_name:'虚构实际领取人',receipt_note:'明确原签收，与护理来源分别保存',handed_at:now(),reason:'虚构实际签收'}});}
const verifyCare=x=>{verify(x);verifySpecialtyCare(x.db);};
test('explicit before-handover care captures quality, product and lot basis but does not sign or claim mastery',async t=>{const x=await careSetup(t),r=await created(x);assert.equal(r.status,'pending');assert.equal(r.outcome,'not_assessed');assert.equal(r.require_demonstration,1);assert.equal(r.lot_basis.length,1);assert.equal((await deliver(x)).body.error.code,'SPECIALTY_CARE_HOLD');assert.equal(x.db.prepare("SELECT count(*) n FROM fulfillment_events WHERE action='deliver'").get().n,0);verifyCare(x);});
test('professional observed mastery, exact version review and explicit release remain three distinct records',async t=>{const x=await careSetup(t);await created(x);const z=await careVersion(x);assert.equal(z.status,201);assert.equal((await careEvent(x,'release')).status,409);assert.equal((await careEvent(x,'review')).status,201);assert.equal(C.careRecord(x.db,x.care.id).can_handover,false);assert.equal((await careEvent(x,'release')).status,201);assert.equal((await deliver(x)).status,201);verifyCare(x);});
test('needs-practice, unknown and declined do not bypass explicit demonstration requirement',async t=>{const x=await careSetup(t);await created(x);assert.equal((await careVersion(x,{outcome:'needs_practice',practice_note:'实际仍需补练'})).status,201);await careEvent(x,'review');assert.equal((await careEvent(x,'release')).body.error.code,'SPECIALTY_CARE_PRACTICE');assert.equal((await careVersion(x,{outcome:'declined',practice_note:'明确拒绝，不推定掌握'})).status,201);await careEvent(x,'review');assert.equal((await careEvent(x,'release')).status,409);verifyCare(x);});
test('actual source may explicitly waive demonstration gate but never replaces professional assessment or release',async t=>{const x=await careSetup(t);await created(x,{require_demonstration:false,requirement_source_note:'明确虚构规则不强制现场演示，仍须专业明确核对'});assert.equal((await careVersion(x,{outcome:'needs_practice'})).status,201);await careEvent(x,'review');assert.equal((await careEvent(x,'release')).status,201);verifyCare(x);});
test('reception or manager cannot record mastery, review or release from contact/viewing permissions',async t=>{const x=await careSetup(t);assert.equal((await care(x,{outcome:'demonstrated',guided_at:now()})).status,403);await created(x);assert.equal((await careEvent(x,'review',x.m)).status,403);assert.equal((await careVersion(x,{},x.f)).status,403);assert.equal((await careVersion(x)).status,201);assert.equal((await careVersion(x,{outcome:'not_assessed',guided_at:null},x.f)).status,403);verifyCare(x);});
test('new material version resets review/release and preserves original signed care basis',async t=>{const x=await careSetup(t);await readyCare(x);const d=await deliver(x);assert.equal(d.status,201);const old=x.db.prepare('SELECT * FROM specialty_care_execution_refs WHERE event_id=?').get(d.body.event.id);assert.equal((await careVersion(x,{guidance_note:'追加明确材料更正'})).status,201);assert.equal((await deliver(x)).status,409);await careEvent(x,'review');await careEvent(x,'release');assert.equal((await deliver(x)).status,201);assert.deepEqual(x.db.prepare('SELECT * FROM specialty_care_execution_refs WHERE event_id=?').get(d.body.event.id),old);verifyCare(x);});
test('pause/resume returns pending and close keeps hold; it never closes the clinical case or refunds money',async t=>{const x=await careSetup(t);await readyCare(x);await careEvent(x,'pause');assert.equal((await deliver(x)).status,409);await careEvent(x,'resume');assert.equal(C.careRecord(x.db,x.care.id).status,'pending');await careEvent(x,'review');await careEvent(x,'release');await careEvent(x,'close');assert.equal((await deliver(x)).status,409);assert.equal(S.specialtyCase(x.db,x.c.id).status,'active');assert.equal(x.db.prepare('SELECT count(*) n FROM refund_events').get().n,0);verifyCare(x);});
test('same information consent withdrawal blocks new handover and preserves exact physical outbound basis while history survives',async t=>{const x=await careSetup(t);await readyCare(x);const d=await deliver(x);assert.equal(d.status,201);insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'receive',quantity:2,reason:'虚构',created_by:'manager'});const out=insertDispatch(x.db,d.body.event.id,{quantity:1,reason:'虚构'},'manager');assert.equal(x.db.prepare('SELECT kind FROM specialty_care_execution_refs WHERE event_id=?').get(out.event.id).kind,'outbound');await revoke(x);assert.equal((await deliver(x)).status,409);verifyCare(x);});
test('revoked guidance material stops new handover without deleting the prior actual care fact',async t=>{const x=await careSetup(t),id=proof(x);await created(x);await careVersion(x,{attachment_ids:[id]});await careEvent(x,'review');await careEvent(x,'release');assert.equal((await deliver(x)).status,201);x.db.prepare('UPDATE attachments SET revoked_at=?,revoked_by=?,revocation_reason=? WHERE id=?').run(now(),'front','明确撤销',id);assert.equal((await deliver(x)).status,409);verifyCare(x);});
test('after-handover guidance fixes an actual receipt and cannot backfill earlier pre-handover permission',async t=>{const x=await careSetup(t),d=await deliver(x);assert.equal(d.status,201);assert.equal((await care(x)).body.error.code,'SPECIALTY_CARE_SOURCE');const r=await created(x,{timing:'after_handover',delivery_id:d.body.event.id});assert.equal(r.quantity,1);assert.equal(r.timing,'after_handover');assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_care_execution_refs').get().n,0);verifyCare(x);});
test('owner changes require new original-source review and preserve the original care release actor',async t=>{const x=await careSetup(t);await readyCare(x);await event(x,x.c,'pause');await event(x,x.c,'resume',{consent_id:x.a.id,consent_revision:1});await approved(x);assert.equal(C.careRecord(x.db,x.care.id).can_handover,false);await careEvent(x,'pause');await careEvent(x,'resume');await careEvent(x,'review');await careEvent(x,'release');assert.equal(C.careRecord(x.db,x.care.id).can_handover,true);verifyCare(x);});
test('strict fields, explicit rule flag, future actual times and cross-customer material fail with no partial root',async t=>{const x=await careSetup(t);assert.equal((await care(x,{require_demonstration:undefined})).status,422);assert.equal((await care(x,{guided_at:new Date(Date.now()+60000).toISOString()})).status,422);assert.equal((await care(x,{attachment_ids:[proof(x,'two')]})).status,409);assert.equal((await care(x,{diagnosis:'not accepted'})).status,422);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_care_records').get().n,0);});
test('care audit failure rolls root, version and event back, then unchanged retry succeeds once',async t=>{const x=await careSetup(t);x.db.exec("CREATE TRIGGER care_audit_failure BEFORE INSERT ON audit_events WHEN NEW.action='specialty.care.version' BEGIN SELECT RAISE(ABORT,'forced care audit'); END");assert.equal((await care(x)).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_care_records').get().n,0);x.db.exec('DROP TRIGGER care_audit_failure');assert.equal((await care(x)).status,201);verifyCare(x);});
test('native handover and immutable source guards protect the same pre-handover requirement',async t=>{const x=await careSetup(t);await created(x);assert.throws(()=>insertFulfillmentEvent(x.db,x.job.id,{action:'deliver',position:1,quantity:1,source_id:x.quality.id,receiver_name:'虚构',receipt_note:'虚构',handed_at:now(),reason:'虚构'},'front'),/care handover hold/);assert.throws(()=>x.db.prepare('UPDATE specialty_care_records SET require_demonstration=0').run(),/immutable/);verifyCare(x);});
test('all four care tables survive independent restore after later withdrawal, with exact signature/outbound versions',async t=>{const x=await careSetup(t,{persist:true});await readyCare(x);await deliver(x);await revoke(x);const b=await createBackup(x.path,join(x.dir,'backup'));assert.equal(b.checks.migrations.length,45);const r=await restoreBackup(b.backup,join(x.dir,'restore')),d=openDatabase(r.database);verifySpecialtyCare(d);for(const n of C.careTables)assert.deepEqual(d.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());d.close();});
test('care history and customer scope reject guardian, other-store and stale revisions',async t=>{const x=await careSetup(t);await created(x);assert.equal((await x.request('/api/specialty-care/'+x.care.id,x.g)).status,403);assert.equal((await x.request('/api/specialty-care/'+x.care.id,x.o)).status,404);const initial=careLease(x);await careVersion(x);assert.equal((await x.request('/api/specialty-care/'+x.care.id+'/events',{...x.p,method:'POST',data:{...initial,expected_revision:1,expected_version:1,action:'review',next_step:'虚构后续',...note()}})).status,409);verifyCare(x);});
test('recovery rejects altered release basis and substituted guidance material version',async t=>{const x=await careSetup(t);await readyCare(x);await deliver(x);x.db.exec('DROP TRIGGER specialty_care_events_no_update');x.db.prepare("UPDATE specialty_care_events SET case_revision=case_revision-1 WHERE action='release'").run();assert.throws(()=>verifySpecialtyCare(x.db),/原责任/);});

import {seedDemoSpecialtyCare} from '../src/demo-specialty-care.mjs';
import {seedDemoSpecialtyTrace} from '../src/demo-specialty-trace.mjs';
test('same-millisecond signatures cannot substitute a later care source revision',async t=>{const x=await careSetup(t),at=now(),i={...careInput({guided_at:at,outcome:'demonstrated',practice_note:'同刻虚构实际观察'}),timing:'before_handover',delivery_id:null,require_demonstration:true,requirement_source_note:'明确虚构演示要求'};x.care=C.createCare(x.db,C.careQuality(x.db,x.quality.id),i,'professional',at);C.careEvent(x.db,x.care.id,{action:'review',...note(),next_step:'同刻后续'},'professional',at);C.careEvent(x.db,x.care.id,{action:'release',...note(),next_step:'同刻后续'},'professional',at);const d=insertFulfillmentEvent(x.db,x.job.id,{action:'deliver',position:1,quantity:1,source_id:x.quality.id,receiver_name:'虚构',receipt_note:'虚构',handed_at:at,reason:'同刻实际签收'},'front',at).event;C.saveCareVersion(x.db,x.care.id,{...i,guidance_note:'同刻追加原材料'},'professional',at);verifySpecialtyCare(x.db);x.db.exec('DROP TRIGGER specialty_care_execution_refs_no_update');x.db.prepare('UPDATE specialty_care_execution_refs SET version_id=? WHERE event_id=?').run(C.careRecord(x.db,x.care.id).version_id,d.id);assert.throws(()=>verifySpecialtyCare(x.db),/快照/);});
test('schema32 nonempty upgrade keeps prior commerce and clinical facts and adds empty care ledgers',t=>{const dir=mkdtempSync(join(tmpdir(),'care-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,32)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');d.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'demo-front');d.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('demo-retail-cycle','sample-retail','retail','虚构需求','draft',now(),'demo-front');seedDemoSpecialty(d);seedDemoSpecialtyTrace(d);const names=d.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations' ORDER BY name").all().map(x=>x.name),old=Object.fromEntries(names.map(n=>[n,d.prepare('SELECT * FROM '+n).all()]));d.close();const u=openDatabase(path);for(const n of names)assert.deepEqual(u.prepare('SELECT * FROM '+n).all(),old[n]);for(const n of C.careTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);assert.equal(u.prepare('SELECT count(*) n FROM schema_migrations').get().n,45);verifySpecialtyCare(u);u.close();});
test('synthetic pending, needs-practice and released nursing stages append once and preserve all prior sources',async t=>{const x=await fixture(t);for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');x.db.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'front');x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('demo-retail-cycle','sample-retail','retail','虚构需求','draft',now(),'front');const {seedDemoSpecialty}=await import('../src/demo-specialty.mjs');seedDemoSpecialty(x.db);seedDemoSpecialtyTrace(x.db);const names=[...S.specialtyTables,...T.specialtyTraceTables],old=Object.fromEntries(names.map(n=>[n,x.db.prepare('SELECT * FROM '+n).all()]));assert.deepEqual(seedDemoSpecialtyCare(x.db),{records:3});for(const n of S.specialtyTables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),old[n]);for(const n of T.specialtyTraceTables){const current=x.db.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(old[n].length);assert.deepEqual(current,old[n]);}assert.deepEqual(seedDemoSpecialtyCare(x.db),{records:0});verifySpecialtyCare(x.db);verifySpecialtyTrace(x.db);});
