import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as S from '../src/specialty.mjs';
import {verifySpecialty} from '../src/specialty-recovery.mjs';
import {createHash} from 'node:crypto';
const now=()=>new Date().toISOString(),note=()=>({note:'明确本地记录（虚构）',reason:'实际来源核对'}),pi=()=>({...Object.fromEntries(S.protocolFields.map(k=>[k,k==='title'?'接触镜条件来源（虚构）':'明确人工来源，未知规则不补造：'+k])),require_assessment_evidence:false,require_consent_evidence:false,...note()}),ci=()=>({title:'专项评估（虚构）',assessment_note:'资料尚待专业明确核对',suitability:'pending',suitability_note:'未知，不推定适用',assessed_at:null,source_note:'仅虚构人工资料',next_step:'由明确专业责任人继续评估',document_ids:[],attachment_ids:[],...note()}),signed=()=>({party:'guardian',party_label:'虚构监护人',relationship_note:'明确虚构身份与关系来源；不从查看授权推定',signed_at:new Date(Date.now()-1000).toISOString(),source_note:'明确记录本版本知情同意来源，非真实签署',document_ids:[],attachment_ids:[],...note()});
async function setup(t,opts){const x=await fixture(t,opts);x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('cycle-one','one','retail','明确配镜需求','draft',now(),'front');return {...x,m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')};}
const seq=x=>S.specialtySequence(x.db,'a');
async function post(x,path,u,data,key){return x.request('/api/specialty/'+path,{...u,method:'POST',data:{expected_sequence:seq(x),...data},...(key?{key}:{})});}
async function protocol(x,extra={},adopt=true){let z=await post(x,'protocols',x.m,{code:'DEMO-'+crypto.randomUUID().slice(0,8),service_type:'contact_lens',...pi(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));let r=z.body.record;if(adopt){z=await post(x,'protocols/'+r.id+'/events',x.m,{expected_revision:r.revision,expected_version:r.version,action:'adopt',...note()});assert.equal(z.status,201,JSON.stringify(z.body));r=z.body.record;}return r;}
async function fitting(x,p,extra={},u=x.f){const z=await post(x,'cases',u,{customer_id:'one',protocol_id:p.id,protocol_version:p.current_version,protocol_revision:p.revision,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function cv(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/versions',x.p,{expected_revision:r.revision,expected_version:r.current_version,...ci(),suitability:'suitable',suitability_note:'由本条专业责任人明确记录的虚构判断',assessed_at:new Date(Date.now()-1000).toISOString(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function consent(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/consents',x.f,{expected_case_revision:r.revision,...signed(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function event(x,c,action,extra={},u=action==='assign'?x.m:x.p){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/events',u,{expected_revision:r.revision,expected_version:r.current_version,action,next_step:'保留明确后续',...note(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
const snapshot=db=>Object.fromEntries(S.specialtyTables.map(n=>[n,db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
function proof(x,customer='one',id=crypto.randomUUID()){const b=Buffer.from('synthetic specialty source; no true signature'),hash=createHash('sha256').update(b).digest('hex');x.db.prepare('INSERT OR IGNORE INTO attachment_blobs VALUES(?,?,?)').run(hash,b,b.length);x.db.prepare('INSERT INTO attachments(id,customer_id,filename,content_type,blob_sha256,size,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,customer,'specialty-source.txt','text/plain',hash,b.length,now(),'front');return id;}
test('explicit conditional protocol is local source configuration, with service type and requirements kept in versions',async t=>{const x=await setup(t),p=await protocol(x);assert.equal(p.status,'adopted');assert.equal(p.service_type,'contact_lens');assert.equal(p.require_assessment_evidence,0);assert.equal(p.require_consent_evidence,0);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_cases').get().n,0);verifySpecialty(x.db);});
test('only manager records or adopts institution/duty conditions and no evidence flags are guessed',async t=>{const x=await setup(t),b={code:'X',service_type:'ok_lens',...pi()};for(const u of [x.f,x.p])assert.equal((await post(x,'protocols',u,b)).status,403);delete b.require_assessment_evidence;assert.equal((await post(x,'protocols',x.m,b)).status,422);});
test('draft protocol cannot enable new cases; condition versions and current identity remain explicit',async t=>{const x=await setup(t),p=await protocol(x,{},false);assert.equal((await post(x,'cases',x.f,{customer_id:'one',protocol_id:p.id,protocol_version:1,protocol_revision:1,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci()})).status,409);verifySpecialty(x.db);});
test('reception captures pending only; professional suitability and actual time remain separate from adopting',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);assert.equal(c.status,'draft');assert.equal(c.suitability,'pending');assert.ok(c.holds.length);const z=await cv(x,c);assert.equal(z.suitability,'suitable');assert.equal(z.status,'draft');assert.equal(z.adoption,null);assert.equal(x.db.prepare('SELECT count(*) n FROM retail_orders').get().n,0);verifySpecialty(x.db);});
test('suitable assessment still needs this exact information version consent before explicit professional adoption',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await cv(x,c);const a=await consent(x,c),z=await event(x,c,'adopt',{consent_id:a.id,consent_revision:a.revision});assert.equal(z.status,'active');assert.equal(z.adoption.created_by,'professional');assert.deepEqual(z.holds,[]);assert.equal(z.consent.case_version,2);verifySpecialty(x.db);});
test('needs-more and not-suitable never become adopted from contact/viewing permissions or a signature alone',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);for(const suitability of ['needs_more','not_suitable']){const r=await cv(x,c,{suitability});const a=await consent(x,c);assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:r.revision,expected_version:r.version,action:'adopt',consent_id:a.id,consent_revision:a.revision,next_step:'后续',...note()})).status,409);}assert.equal(S.specialtyCase(x.db,c.id).status,'draft');verifySpecialty(x.db);});
test('required source evidence follows the explicitly captured protocol; another customer proof is rejected',async t=>{const x=await setup(t),p=await protocol(x,{require_assessment_evidence:true,require_consent_evidence:true}),c=await fitting(x,p),id=proof(x);await cv(x,c);const a=await consent(x,c);assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:2,expected_version:2,action:'adopt',consent_id:a.id,consent_revision:1,next_step:'后续',...note()})).status,409);await cv(x,c,{attachment_ids:[id]});const b=await consent(x,c,{attachment_ids:[id]});assert.equal((await event(x,c,'adopt',{consent_id:b.id,consent_revision:b.revision})).status,'active');const other=proof(x,'two');assert.equal((await post(x,'cases/'+c.id+'/consents',x.f,{expected_case_revision:4,...signed(),attachment_ids:[other]})).status,409);verifySpecialty(x.db);});
test('source revision returns draft, preserves prior evaluation/adoption and invalidates old consent basis',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await cv(x,c);const a=await consent(x,c);await event(x,c,'adopt',{consent_id:a.id,consent_revision:1});const z=await cv(x,c,{assessment_note:'新的明确评估（虚构）'});assert.equal(z.status,'draft');assert.equal(z.consent,null);assert.equal(S.specialtyCase(x.db,c.id,{version:2}).adoption.version,2);assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:z.revision,expected_version:z.version,action:'adopt',consent_id:a.id,consent_revision:1,next_step:'后续',...note()})).status,409);verifySpecialty(x.db);});
test('clinical consent is independent from service/marketing contact and family view authority',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);const a=await consent(x,c);assert.equal(a.party,'guardian');assert.equal(a.case_version,1);assert.equal(x.db.prepare('SELECT count(*) n FROM contact_consents').get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM guardian_links WHERE user_id=? AND customer_id=?').get('parent','one').n,1);verifySpecialty(x.db);});
test('withdrawal derives immediate hold without altering the adopted original, and blocks cached release replay',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);const r=await cv(x,c),a=await consent(x,c),b={expected_sequence:seq(x),expected_revision:r.revision,expected_version:r.version,action:'adopt',consent_id:a.id,consent_revision:1,next_step:'后续',...note()};assert.equal((await post(x,'cases/'+c.id+'/events',x.p,b,'specialty-adopt-replay')).status,201);const revoke=await post(x,'consents/'+a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});assert.equal(revoke.status,201);const z=S.specialtyCase(x.db,c.id);assert.equal(z.status,'active');assert.ok(z.holds.some(s=>s.includes('同意')));assert.equal((await post(x,'cases/'+c.id+'/events',x.p,b,'specialty-adopt-replay')).status,409);await event(x,c,'pause');assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:4,expected_version:2,action:'resume',consent_id:a.id,consent_revision:2,next_step:'后续',...note()})).status,409);verifySpecialty(x.db);});
test('renewed explicit consent has a new root, and pause/resume/stop preserve complete reasons and sources',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await cv(x,c);const a=await consent(x,c);await event(x,c,'adopt',{consent_id:a.id,consent_revision:1});await post(x,'consents/'+a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});await event(x,c,'pause');const b=await consent(x,c);assert.notEqual(b.id,a.id);const z=await event(x,c,'resume',{consent_id:b.id,consent_revision:1});assert.equal(z.status,'active');await event(x,c,'stop');assert.equal((await post(x,'cases/'+c.id+'/versions',x.p,{expected_revision:6,expected_version:2,...ci()})).status,409);assert.equal(S.specialtyCase(x.db,c.id).consent.id,b.id);verifySpecialty(x.db);});
test('condition retirement/change holds future adoption while retaining customer original captured version',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);const r=await cv(x,c),a=await consent(x,c);await event(x,c,'adopt',{consent_id:a.id,consent_revision:1});assert.equal((await post(x,'protocols/'+p.id+'/events',x.m,{expected_revision:p.revision,expected_version:p.version,action:'retire',...note()})).status,201);assert.equal(S.specialtyCase(x.db,c.id).protocol_version,1);assert.ok(S.specialtyCase(x.db,c.id).holds.some(s=>s.includes('条件')));await event(x,c,'pause');assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:4,expected_version:2,action:'resume',consent_id:a.id,consent_revision:1,next_step:'后续',...note()})).status,409);verifySpecialty(x.db);});
test('only current professional adopts/pauses; manager transfers responsibility without rewriting original adopter',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await cv(x,c);const a=await consent(x,c);for(const u of [x.f,x.m])assert.equal((await post(x,'cases/'+c.id+'/events',u,{expected_revision:2,expected_version:2,action:'adopt',consent_id:a.id,consent_revision:1,next_step:'后续',...note()})).status,403);await event(x,c,'adopt',{consent_id:a.id,consent_revision:1});x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('pro-two','pro-two','pro-two',hashPassword('synthetic-only-password'),'professional','a');const z=await event(x,c,'assign',{owner_id:'pro-two'});assert.equal(z.owner_id,'pro-two');assert.equal(z.adoption.created_by,'professional');assert.equal((await post(x,'cases/'+c.id+'/events',x.p,{expected_revision:z.revision,expected_version:z.version,action:'pause',next_step:'后续',...note()})).status,403);verifySpecialty(x.db);});
test('store/customer/guardian scope rejects configuration, histories, options and consent withdrawal',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p),a=await consent(x,c);for(const path of ['protocols','cases','consents/'+a.id,'customers/one/options'])assert.equal((await x.request('/api/specialty/'+path,x.g)).status,403);assert.equal((await x.request('/api/specialty/cases/'+c.id,x.o)).status,404);assert.equal((await x.request('/api/specialty/customers/other-child/options',x.f)).status,404);});
test('strict fields reject invented units/clinical flags, future evaluations and implied guardian consent',async t=>{const x=await setup(t),p=await protocol(x),b={customer_id:'one',protocol_id:p.id,protocol_version:1,protocol_revision:2,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci()};for(const patch of [{diagnosis:'自动临床结论'},{suitability:'default_safe'},{suitability:'suitable',assessed_at:new Date(Date.now()+60000).toISOString()}])assert.equal((await post(x,'cases',x.p,{...b,...patch})).status,422);assert.equal((await post(x,'cases',x.f,{...b,suitability:'suitable',assessed_at:now()})).status,403);});
test('stale sequence/assessment revision rejects duplicate or competing intent',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p),old=seq(x);await cv(x,c);assert.equal((await post(x,'cases/'+c.id+'/versions',x.p,{expected_sequence:old,expected_revision:1,expected_version:1,...ci()})).status,409);assert.equal(S.specialtyCase(x.db,c.id).version,2);});
test('assessment audit failure removes new version/event/idempotency and same-intent retry commits once',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p),before=snapshot(x.db),b={expected_sequence:seq(x),expected_revision:c.revision,expected_version:c.version,...ci()};x.db.exec("CREATE TRIGGER fail_specialty BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'specialty.%' BEGIN SELECT RAISE(ABORT,'forced'); END");assert.equal((await post(x,'cases/'+c.id+'/versions',x.p,b,'specialty-audit-retry')).status,500);assert.deepEqual(snapshot(x.db),before);x.db.exec('DROP TRIGGER fail_specialty');assert.equal((await post(x,'cases/'+c.id+'/versions',x.p,b,'specialty-audit-retry')).status,201);assert.equal((await post(x,'cases/'+c.id+'/versions',x.p,b,'specialty-audit-retry')).status,201);verifySpecialty(x.db);});
test('native state guards reject administrative adoption, revoked consent and mutation of history',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await cv(x,c);const a=await consent(x,c),i={action:'adopt',consent_id:a.id,consent_revision:1,next_step:'后续',...note()};assert.throws(()=>S.specialtyCaseEvent(x.db,c.id,i,'manager'));S.specialtyConsentEvent(x.db,a.id,{action:'revoke',occurred_at:now(),...note()},'front');assert.throws(()=>S.specialtyCaseEvent(x.db,c.id,{...i,consent_revision:2},'professional'));assert.throws(()=>x.db.prepare('UPDATE specialty_cases SET protocol_version=2 WHERE id=?').run(c.id));verifySpecialty(x.db);});
test('recovery rejects same-millisecond consent order substitution and false adopted state',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await cv(x,c);const a=await consent(x,c);await event(x,c,'adopt',{consent_id:a.id,consent_revision:1});await post(x,'consents/'+a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});x.db.exec('DROP TRIGGER specialty_case_events_no_update');x.db.prepare("UPDATE specialty_case_events SET consent_revision=2 WHERE case_id=? AND action='adopt'").run(c.id);assert.throws(()=>verifySpecialty(x.db),/当时/);});
test('schema31 eight-table backup and independent restore preserve fixed versions and clear sessions',async t=>{const x=await setup(t,{persist:true}),p=await protocol(x),c=await fitting(x,p),id=proof(x);await cv(x,c,{attachment_ids:[id]});const a=await consent(x,c,{attachment_ids:[id]});await event(x,c,'adopt',{consent_id:a.id,consent_revision:1});const before=snapshot(x.db),b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,32);const r=await restoreBackup(b.backup,join(x.dir,'restored')),d=openDatabase(r.database);assert.deepEqual(snapshot(d),before);assert.equal(d.prepare('SELECT count(*) n FROM sessions').get().n,0);verifySpecialty(d);d.close();});
test('schema30 upgrade preserves prior rows and adds no clinical approval or customer consent',t=>{const dir=mkdtempSync(join(tmpdir(),'specialty-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,30)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('old','old')");d.close();const u=openDatabase(path);assert.equal(u.prepare('SELECT count(*) n FROM stores').get().n,1);for(const n of S.specialtyTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifySpecialty(u);u.close();});
import {seedDemoScenarios} from '../src/demo-data.mjs';
import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
test('full paging uses one sequence and preserves counts beyond thirty while histories remain bounded',async t=>{const x=await setup(t),p=await protocol(x);x.db.exec('BEGIN');for(let i=0;i<33;i++)S.createSpecialtyCase(x.db,'a','one',{...ci(),protocol_id:p.id,protocol_version:1,protocol_revision:2,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional'},'front');x.db.exec('COMMIT');const a=(await x.request('/api/specialty/cases?limit=30',x.f)).body;assert.equal(a.total,33);assert.equal(a.next_offset,30);assert.equal((await x.request('/api/specialty/cases?offset=30&expected_sequence='+a.sequence,x.f)).body.items.length,3);await fitting(x,p);assert.equal((await x.request('/api/specialty/cases?offset=30&expected_sequence='+a.sequence,x.f)).status,409);verifySpecialty(x.db);});
test('actual consent withdrawal while body is pending blocks a previously cached adoption',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p),r=await cv(x,c),a=await consent(x,c),b={expected_sequence:seq(x),expected_revision:r.revision,expected_version:r.version,action:'adopt',consent_id:a.id,consent_revision:1,next_step:'明确后续',...note()},path='/api/specialty/cases/'+c.id+'/events',key='pending-specialty-replay';assert.equal((await x.request(path,{...x.p,method:'POST',data:b,key})).status,201);const data=JSON.stringify(b),u=new URL(x.origin),status=await new Promise((resolve,reject)=>{const req=httpRequest({hostname:u.hostname,port:u.port,path,method:'POST',headers:{Cookie:x.p.cookie,'X-CSRF-Token':x.p.csrf,'Idempotency-Key':key,'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.write(data.slice(0,10));setTimeout(()=>{S.specialtyConsentEvent(x.db,a.id,{action:'revoke',occurred_at:now(),...note()},'front');req.end(data.slice(10));},20);});assert.equal(status,409);assert.equal(x.db.prepare("SELECT count(*) n FROM specialty_case_events WHERE action='adopt'").get().n,1);verifySpecialty(x.db);});
test('captured old visit demand remains fixed after later revisions and wrong visit/customer sources fail',async t=>{const x=await setup(t),p=await protocol(x),at=now();x.db.prepare('INSERT INTO visits VALUES(?,?,?,?,?,?,?,?)').run('visit-one','one','a','演示到店','registered',at,null,'front');x.db.prepare('INSERT INTO visit_cycles VALUES(?,?,?)').run('visit-one','cycle-one','one');x.db.prepare('INSERT INTO cycle_versions VALUES(?,?,?,?,?,?,?,?,?)').run('cycle-one','one',2,'retail','新需求','employee','明确修订',now(),'front');const c=await fitting(x,p,{visit_id:'visit-one',context_basis:'visit_cycle'});assert.equal(c.cycle_version,1);assert.equal((await post(x,'cases',x.f,{customer_id:'one',protocol_id:p.id,protocol_version:1,protocol_revision:2,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci()})).status,409);verifySpecialty(x.db);});
test('timeline keeps customer case and consent events separate from configuration and denies guardians',async t=>{const x=await setup(t),p=await protocol(x),c=await fitting(x,p);await consent(x,c);const z=await x.request('/api/customers/one/timeline',x.f);assert.equal(z.status,200);assert.ok(z.body.items.some(x=>x.kind==='specialty_case'));assert.ok(z.body.items.some(x=>x.kind==='specialty_consent'));assert.equal((await x.request('/api/customers/one/timeline',x.g)).status,403);});
test('staged specialty examples append once and do not rewrite original customers, orders, visits or authorizations',async t=>{const x=await setup(t),d=x.db;d.exec("INSERT INTO stores VALUES('store-a','演示')");for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'store-a');seedDemoScenarios(d);const names=['customers','service_cycles','cycle_versions','visits','retail_orders','guardian_links','contact_consents'],old=names.map(n=>d.prepare('SELECT * FROM '+n).all());assert.deepEqual(seedDemoSpecialty(d),{protocols:2,cases:5});assert.deepEqual(names.map(n=>d.prepare('SELECT * FROM '+n).all()),old);const a=snapshot(d);assert.deepEqual(seedDemoSpecialty(d),{protocols:0,cases:0});assert.deepEqual(snapshot(d),a);assert.ok(S.specialtyCase(d,'demo-specialty-withdrawn').holds.length);verifySpecialty(d);});
