import {insertOrderVersion} from '../src/retail.mjs';
import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as S from '../src/specialty.mjs';
import {verifySpecialty} from '../src/specialty-recovery.mjs';
import {createHash} from 'node:crypto';
const now=()=>new Date().toISOString(),note=()=>({note:'明确本地记录（虚构）',reason:'实际来源核对'}),pi=()=>({...Object.fromEntries(S.protocolFields.map(k=>[k,k==='title'?'接触镜条件来源（虚构）':'明确人工来源，未知规则不补造：'+k])),require_assessment_evidence:false,require_consent_evidence:false,...note()}),ci=()=>({title:'专项评估（虚构）',assessment_note:'资料尚待专业明确核对',suitability:'pending',suitability_note:'未知，不推定适用',assessed_at:null,source_note:'仅虚构人工资料',next_step:'由明确专业责任人继续评估',document_ids:[],attachment_ids:[],...note()}),signed=()=>({party:'guardian',party_label:'虚构监护人',relationship_note:'明确虚构身份与关系来源；不从查看授权推定',signed_at:new Date(Date.now()-1000).toISOString(),source_note:'明确记录本版本知情同意来源，非真实签署',document_ids:[],attachment_ids:[],...note()});
async function setup(t,opts){const x=await fixture(t,opts);x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('cycle-one','one','retail','明确配镜需求','draft',now(),'front');return {...x,m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')};}
const seq=x=>S.specialtySequence(x.db,'a');
async function post(x,path,u,data,key){return x.request('/api/specialty/'+path,{...u,method:'POST',data:{expected_sequence:seq(x),...data},...(key?{key}:{})});}
async function protocol(x,extra={},adopt=true){let z=await post(x,'protocols',x.m,{code:'DEMO-'+crypto.randomUUID().slice(0,8),service_type:'contact_lens',...pi(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));let r=z.body.record;if(adopt){z=await post(x,'protocols/'+r.id+'/events',x.m,{expected_revision:r.revision,expected_version:r.version,action:'adopt',...note()});assert.equal(z.status,201,JSON.stringify(z.body));r=z.body.record;}return r;}
async function fitting(x,p,extra={},u=x.f){const z=await post(x,'cases',u,{customer_id:'one',protocol_id:p.id,protocol_version:p.current_version,protocol_revision:p.revision,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function cv(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/versions',x.p,{expected_revision:r.revision,expected_version:r.current_version,...ci(),suitability:'suitable',suitability_note:'由本条专业责任人明确记录的虚构判断',assessed_at:new Date(Date.now()-1000).toISOString(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function consent(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/consents',x.f,{expected_case_revision:r.revision,...signed(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function event(x,c,action,extra={},u=action==='assign'?x.m:x.p){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/events',u,{expected_revision:r.revision,expected_version:r.current_version,action,next_step:'保留明确后续',...note(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
const snapshot=db=>Object.fromEntries(S.specialtyTables.map(n=>[n,db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
function proof(x,customer='one',id=crypto.randomUUID()){const b=Buffer.from('synthetic specialty source; no true signature'),hash=createHash('sha256').update(b).digest('hex');x.db.prepare('INSERT OR IGNORE INTO attachment_blobs VALUES(?,?,?)').run(hash,b,b.length);x.db.prepare('INSERT INTO attachments(id,customer_id,filename,content_type,blob_sha256,size,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,customer,'specialty-source.txt','text/plain',hash,b.length,now(),'front');return id;}

import * as T from '../src/specialty-trace.mjs';
import {verifySpecialtyTrace} from '../src/specialty-trace-recovery.mjs';
import {insertParameterVersion,insertParameterEvent} from '../src/parameters.mjs';
import {insertProcessingJob,insertProcessingEvent,processingRecord} from '../src/processing.mjs';
import {insertFulfillmentEvent,fulfillmentRecord} from '../src/fulfillment.mjs';
import {parameterContext} from '../src/parameter-ledger.mjs';
async function traceSetup(t,opts){const x=await setup(t,opts),pr=await protocol(x);let c=await fitting(x,pr);c=await cv(x,c);const a=await consent(x,c);c=await event(x,c,'adopt',{consent_id:a.id,consent_revision:a.revision});const prod=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'CL-'+crypto.randomUUID().slice(0,8),name:'虚构镜片订片',category:'lens',brand:null,specification:'仅演示来源，非临床参数',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(prod.status,201,JSON.stringify(prod.body));const o=await x.request('/api/customers/one/retail-orders',{...x.f,method:'POST',data:{title:'专项原单（虚构）',notes:null,cycle_id:'cycle-one',cycle_version:1,visit_id:null,items:[{product_id:prod.body.product.id,product_version:1,quantity:2,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构'}});assert.equal(o.status,201,JSON.stringify(o.body));Object.assign(x,{c,a,pr,order:o.body.order,product:prod.body.product});checkParam(x);return x;}
function checkParam(x){const p=insertParameterVersion(x.db,x.order.id,{source:'staff_record',source_note:'虚构来源，不代替正式处方',values:[{position:1,label:'虚构交接项',value:'样例交接值',unit:null,condition:null}],document_version_ids:[],attachment_ids:[],...note()},'front').parameter;insertParameterEvent(x.db,p.id,{action:'submit',...note()},'front');insertParameterEvent(x.db,p.id,{action:'check',...note()},'professional');return p.id;}
function approvalInput(x){const z=T.approvalCandidates(x.db,x.order.id),c=S.specialtyCase(x.db,x.c.id);return {expected_sequence:T.traceSequence(x.db,'a'),case_id:c.id,expected_order_version:1,expected_case_revision:c.revision,expected_specialty_sequence:seq(x),expected_approval_revision:T.specialtyOrderContext(x.db,x.order.id)?.approval_revision||0,parameter_version_id:z.parameter.id,expected_parameter_sequence:z.parameter.sequence,...note()};}
const approve=(x,who=x.p,extra={},key)=>x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/approvals',{...who,method:'POST',data:{...approvalInput(x),...extra},key});
async function approved(x){const z=await approve(x);assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
function job(x){const j=insertProcessingJob(x.db,x.order.id,{lines:[{position:1,supply_mode:'purchase',processing_mode:'internal',supplier_name:'虚构供应方',assignee_id:'professional',due_date:null,instructions:'仅虚构交接'}],reason:'虚构'},'manager');x.job=j;return j;}
function received(x){job(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:2,reason:'虚构实际到货'},'front');return x.db.prepare("SELECT * FROM processing_events WHERE job_id=? AND action='receive'").get(x.job.id);}
const li=(extra={})=>({trace_status:'recorded',lot_number:'DEMO-LOT-ONLY',serial_note:'序列尚未知，明确原来源',manufacturer_note:'虚构生产来源',supplier_note:'虚构供货来源',source_note:'虚构原包装批号，不代表真实产品',document_ids:[],attachment_ids:[],...note(),...extra});
async function lot(x,e,extra={},key){return x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/lots',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),receive_event_id:e.id,quantity:2,...li(extra)},key});}
async function revision(x,l,extra={}){return x.request('/api/specialty-lots/'+l.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),expected_revision:l.revision,...li(extra)}});}
async function revoke(x){return post(x,'consents/'+x.a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});}
async function process(x,action,key){const p=processingRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/events',{...x.p,method:'POST',key,data:{expected_revision:p.revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action,position:1,quantity:2,reason:'虚构实际执行'}});}
function finished(x){insertProcessingEvent(x.db,x.job.id,{action:'start',position:1,quantity:2,reason:'虚构'},'professional');insertProcessingEvent(x.db,x.job.id,{action:'complete',position:1,quantity:2,reason:'虚构'},'professional');}
async function qc(x){const f=fulfillmentRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/fulfillment/events',{...x.p,method:'POST',data:{expected_revision:f.revision,expected_processing_revision:f.processing_revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action:'check_pass',position:1,quantity:2,source_id:null,checks:[{label:'虚构明确检查项',result:'pass',notes:'虚构检查事实'}],reason:'虚构检查'}});}
const verify=x=>{verifySpecialty(x.db);verifySpecialtyTrace(x.db);};

import * as C from '../src/specialty-care.mjs';
import * as R from '../src/specialty-review.mjs';
import {verifySpecialtyReviews} from '../src/specialty-review-recovery.mjs';
import * as L from '../src/longitudinal.mjs';
import * as F from '../src/referrals.mjs';
import * as K from '../src/contact.mjs';
const manifest=()=>({documents:[],attachments:[],observations:[],external_records:[]}),ri=(extra={})=>({title:'原镜片复查（虚构）',participant_label:'虚构实际反馈人',relationship_note:'明确人工身份来源，不推定监护授权',reported_at:now(),measured_at:null,eye:'both',condition_status:'unknown',condition_note:'条件尚未齐全，保留明确未知',source_kind:'customer_report',due_date:null,source_note:'仅虚构反馈原文来源',feedback_note:'虚构佩戴反馈，不生成临床结论',findings_note:'实际检查待核对，不补默认指标',issue_note:'损坏/遗失等实际情况依来源记录',arrangement_note:'下一安排按专业实际来源明确',manifest:manifest(),next_step:'由专业责任人继续核对',...note(),...extra});
async function reviewSetup(t,opts){const x=await traceSetup(t,opts);await approved(x);const e=received(x);await lot(x,e);finished(x);const q=insertFulfillmentEvent(x.db,x.job.id,{action:'check_pass',position:1,quantity:2,checks:[{label:'虚构原检查项',result:'pass',notes:'仅明确虚构来源'}],reason:'虚构'},'professional').event;x.quality=q;if(opts?.careBefore){const i={...Object.fromEntries(C.careFields.map(k=>[k,'仅虚构原护理来源 '+k])),guided_at:now(),outcome:'demonstrated',document_ids:[],attachment_ids:[],require_demonstration:true,requirement_source_note:'明确虚构原要求，非临床规则',timing:'before_handover',delivery_id:null,...note()};x.care=C.createCare(x.db,C.careQuality(x.db,q.id),i,'professional');for(const action of ['review','release'])C.careEvent(x.db,x.care.id,{action,next_step:'明确后续',...note()},'professional');}x.delivery=insertFulfillmentEvent(x.db,x.job.id,{action:'deliver',position:1,quantity:1,source_id:q.id,receiver_name:'虚构实际领取人',receipt_note:'明确原签收',handed_at:now(),reason:'虚构'},'front').event;return x;}
const reviewLease=x=>({expected_sequence:R.reviewSequence(x.db,'a'),expected_specialty_sequence:seq(x)});
async function review(x,extra={},who=x.f,key){return x.request('/api/specialty-reviews',{...who,method:'POST',key,data:{...reviewLease(x),delivery_id:x.delivery.id,category:'routine',root_source_note:'实际原产品后续来源（虚构）',expected_case_revision:S.specialtyCase(x.db,x.c.id).revision,...ri(extra)}});}
async function reviewedRoot(x,extra={}){const z=await review(x,extra);assert.equal(z.status,201,JSON.stringify(z.body));x.review=z.body.record;return x.review;}
async function rv(x,extra={},who=x.f){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/versions',{...who,method:'POST',data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,...ri(extra)}});}
async function re(x,decision='not_assessed',extra={},who=x.p,key){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/events',{...who,method:'POST',key,data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,action:'confirm',decision,evaluated_at:now(),opinion_note:'专业明确原版本处置意见（虚构）',next_step:'明确下一安排，不补默认方法或频率',...note(),...extra}});}
async function end(x,action='close'){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/events',{...x.p,method:'POST',data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,action,next_step:'明确保留后续资料安排',...note()}});}
async function link(x,kind,source,who=x.f,extra={}){const r=R.specialtyReview(x.db,x.review.id);return x.request('/api/specialty-reviews/'+r.id+'/links',{...who,method:'POST',data:{...reviewLease(x),expected_revision:r.revision,expected_version:r.current_version,kind,source,source_note:'明确已有后续原记录关联',next_step:'仍由对应责任人继续办理',...note(),...extra}});}
const verifyReview=x=>{verify(x);verifySpecialtyReviews(x.db);};
function outside(x,customer='one'){const r=F.createExternalRecord(x.db,'a',customer,{kind:'external_report',title:'外院原资料（虚构）',institution:'虚构机构',reported_at:now(),measured_at:null,eye:'both',condition_status:'unknown',condition_note:'实际条件尚未知',source_note:'虚构原报告转录',record_note:'保留原文，不生成诊断',document_ids:[],attachment_ids:[],owner_id:'professional',...note()},'front');return F.externalRecordEvent(x.db,r.id,{action:'confirm',opinion_note:'专业明确原文及限制',next_step:'保留后续',...note()},'professional');}
function long(x){x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('followup-one','one','followup','明确后续需求','draft',now(),'front');const i={title:'长期来源（虚构）',baseline_note:'尚未取得',goal_note:'核对原资料',source_note:'明确人工来源',manifest:L.emptyLongitudinalManifest(),reason:'虚构',cycle_id:'followup-one',cycle_version:1},c=L.createLongitudinalCase(x.db,'a','one',i,'professional');L.longitudinalCaseEvent(x.db,c.id,{action:'activate',...note()},'professional');const o=L.createObservation(x.db,c.id,{measured_at:now(),eye:'both',condition_status:'unknown',condition_note:'条件仍未知',source:'staff_record',source_note:'明确实际记录来源',record_note:'虚构检查原文，不生成指标',manifest:L.emptyLongitudinalManifest(),reason:'虚构'},'professional');const p=L.createReviewPlan(x.db,c.id,{due_date:'2026-10-01',purpose:'明确下一复查',items_note:'实际检查项待核对',owner_id:'professional',source_note:'实际明确日期，不生成默认频率',manifest:L.emptyLongitudinalManifest(),...note()},'professional');return {c,o,p};}
function actualContact(x){const g=K.createContactConsent(x.db,'a','one',{category:'service',channel:'phone',recipient_label:'虚构反馈人',address:'synthetic-only',source_note:'明确人工服务联系授权',effective_at:now(),...note()},'front'),c=K.createContactCase(x.db,'a','one',{purpose:'followup',source:{kind:'manual',id:null,version:null,revision:null},source_note:'实际后续来源',title:'虚构人工联系',purpose_note:'核对复查安排',due_at:now(),next_action:'等待实际回执',owner_id:'front',...note()},'front');return K.recordContactAttempt(x.db,c.id,{consent_id:g.id,consent_revision:1,occurred_at:now(),result:'sent',source_note:'实际发出来源',content_summary:'虚构复查安排',result_note:'已发出，回执未知',due_at:now(),next_action:'等待实际回执',reason:'明确来源'},'front');}
function tamper(db,t,sql,args=[]){const name=t+'_no_update',s=db.prepare('SELECT sql FROM sqlite_schema WHERE name=?').get(name).sql;db.exec('DROP TRIGGER '+name);db.prepare(sql).run(...args);db.exec(s);}
import * as X from '../src/specialty-continuity.mjs';
import {verifySpecialtyContinuity} from '../src/specialty-continuity-recovery.mjs';
import {insertAftercareCase,insertAftercareEvent,aftercareRecord} from '../src/aftercare.mjs';
import {insertReplacement,insertReplacementEvent} from '../src/aftercare-replacements.mjs';
async function continuitySetup(t,opts){const x=await reviewSetup(t,opts);await reviewedRoot(x);await re(x,'adjust');x.oldOrder=x.order;x.oldClinical=x.c;const z=await x.request('/api/customers/one/retail-orders',{...x.f,method:'POST',data:{title:'独立专项更换新单（虚构）',notes:null,cycle_id:'cycle-one',cycle_version:1,visit_id:null,items:[{product_id:x.product.id,product_version:1,quantity:1,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构'}});assert.equal(z.status,201,JSON.stringify(z.body));x.order=z.body.order;let c=await fitting(x,x.pr);c=await cv(x,c);x.a=await consent(x,c);x.c=await event(x,c,'adopt',{consent_id:x.a.id,consent_revision:x.a.revision});checkParam(x);x.aftercare=insertAftercareCase(x.db,x.delivery.id,{kind:'remake',quantity:1,title:'专项更换原售后（虚构）',...note()},'front');insertAftercareEvent(x.db,x.aftercare.id,{action:'assign',assignee_id:'front',due_date:null,instructions:'独立新单安排',...note()},'manager');insertAftercareEvent(x.db,x.aftercare.id,{action:'start',...note()},'front');x.plan=insertReplacement(x.db,x.aftercare.id,{kind:'remake',quantity:1,new_order_id:x.order.id,new_order_version:1,instructions:'明确独立新单，不推定费用',...note()},'front').replacement;return x;}
const continuityLease=x=>({expected_sequence:X.continuitySequence(x.db,'a'),expected_specialty_sequence:S.specialtySequence(x.db,'a'),expected_trace_sequence:T.traceSequence(x.db,'a'),expected_review_sequence:R.reviewSequence(x.db,'a')});
async function adopt(x,who=x.p,extra={},key){const r=X.continuityRecord(x.db,x.plan.id);return x.request('/api/specialty-continuity/plans/'+r.plan_id+'/events',{...who,method:'POST',key,data:{...continuityLease(x),expected_revision:r.revision,expected_case_revision:r.new_case?.revision||x.c.revision,expected_parameter_sequence:parameterContext(x.db,null)?.sequence||x.db.prepare('SELECT coalesce(max(sequence),0) n FROM parameter_events WHERE order_id=?').get(x.order.id).n,expected_commercial_revision:r.commercial.revision,action:'approve',review_id:x.review.id,source_note:'实际核对原复查和独立新专项（虚构）',next_step:'依商业与实际加工继续',...note(),...extra}});}
function commerciallyApprove(x){insertReplacementEvent(x.db,x.plan.id,{action:'approve',...note()},'manager');}
function positivePayment(x){return x.request('/api/retail/orders/'+x.order.id+'/payments/receive',{...x.f,method:'POST',data:{expected_order_version:1,expected_revision:0,amount_cents:100,method:'cash',reference:null,received_at:now(),reason:'虚构'}});}
const verifyContinuity=x=>{verifyReview(x);verifySpecialtyContinuity(x.db);};
test('an independently unlinked new order cannot bypass the original specialty replacement gate',async t=>{const x=await continuitySetup(t);commerciallyApprove(x);assert.throws(()=>job(x),/continuity/);assert.equal(x.db.prepare('SELECT count(*) n FROM processing_jobs WHERE order_id=?').get(x.order.id).n,0);const z=await positivePayment(x);assert.equal(z.status,409,JSON.stringify(z.body));assert.equal((await adopt(x,x.m)).status,403);verifyContinuity(x);});
test('commercial approval and professional adoption remain independent before actual new-order execution',async t=>{const x=await continuitySetup(t);await approved(x);assert.equal((await adopt(x)).status,201);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_adopt,1);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_execute,0);assert.throws(()=>job(x),/replacement|continuity/);commerciallyApprove(x);job(x);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_execute,1);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_continuity_execution_refs').get().n,1);verifyContinuity(x);});
test('a stopped original case stays stopped while the separately assessed new case proceeds',async t=>{const x=await continuitySetup(t);S.specialtyCaseEvent(x.db,x.oldClinical.id,{action:'stop',next_step:'独立新专项重新核对',...note()},'professional');await approved(x);commerciallyApprove(x);assert.equal((await adopt(x)).status,201);job(x);assert.equal(S.specialtyCase(x.db,x.oldClinical.id).status,'stopped');assert.equal(S.specialtyCase(x.db,x.c.id).status,'active');verifyContinuity(x);});
test('new feedback invalidates future execution until explicit re-adoption; original execution references survive',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);assert.equal((await adopt(x)).status,201);job(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:1,reason:'实际到货保留'},'front');assert.equal((await rv(x,{feedback_note:'后来明确新的实际反馈'})).status,201);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_execute,0);assert.throws(()=>insertProcessingEvent(x.db,x.job.id,{action:'start',position:1,quantity:1,reason:'虚构'},'professional'),/received|continuity/);assert.equal((await re(x,'adjust')).status,201);assert.equal((await adopt(x)).status,201);verifyContinuity(x);});
test('an immutable archive preserves exact source prefix without completing clinical or aftercare workflows',async t=>{const x=await continuitySetup(t);await approved(x);const before=S.specialtyCase(x.db,x.oldClinical.id).revision,a=X.createSpecialtyArchive(x.db,x.oldClinical.id,{next_step:'护理与售后待继续明确',...note()},'front');assert.equal(JSON.parse(a.snapshot_json).case.status,'active');assert.equal(JSON.parse(a.snapshot_json).replacements[0].professional,null);assert.equal(S.specialtyCase(x.db,x.oldClinical.id).revision,before);assert.equal(aftercareRecord(x.db,x.aftercare.id).status,'running');assert.equal(JSON.parse(a.snapshot_json).next_steps.reviews.length,1);commerciallyApprove(x);assert.equal((await adopt(x)).status,201);const b=X.createSpecialtyArchive(x.db,x.oldClinical.id,{next_step:'新单实际加工尚未开始',...note()},'front');assert.equal(JSON.parse(b.snapshot_json).replacements[0].professional.status,'active');assert.equal(a.snapshot_sha256,X.archiveDigest(a.snapshot_json));assert.equal(JSON.parse(a.snapshot_json).replacements[0].professional,null);verifyContinuity(x);});
test('archive scope, guardian restriction and exact source leases apply on the API',async t=>{const x=await continuitySetup(t);const path='/api/specialty-archives',data={...continuityLease(x),case_id:x.oldClinical.id,expected_case_revision:S.specialtyCase(x.db,x.oldClinical.id).revision,next_step:'保留待续事项',...note()};const z=await x.request(path,{...x.f,method:'POST',data});assert.equal(z.status,201,JSON.stringify(z.body));assert.equal((await x.request(path+'/'+z.body.record.id,x.o)).status,404);assert.equal((await x.request(path+'/'+z.body.record.id,x.g)).status,403);assert.equal((await x.request(path,{...x.f,method:'POST',data})).status,409);verifyContinuity(x);});
test('five new immutable tables and historical sources survive independent backup after later withdrawal',async t=>{const x=await continuitySetup(t,{persist:true});await approved(x);commerciallyApprove(x);assert.equal((await adopt(x)).status,201);job(x);X.createSpecialtyArchive(x.db,x.oldClinical.id,{next_step:'后续实际资料待补',...note()},'front');await revoke(x);verifyContinuity(x);const b=await createBackup(x.path,join(x.dir,'backup')),rr=await restoreBackup(b.backup,join(x.dir,'restore')),d=openDatabase(rr.database);for(const n of X.continuityTables)assert.deepEqual(d.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());verifySpecialtyContinuity(d);d.close();});
function revokeContinuity(x){return X.continuityEvent(x.db,x.plan.id,{action:'revoke',next_step:'后续专业来源重新核对',...note()},'professional');}
function paymentData(){return {expected_order_version:1,expected_revision:0,amount_cents:100,method:'cash',reference:null,received_at:now(),reason:'虚构实际收款'};}
test('current professional revocation prevents a cached positive payment replay before idempotency lookup',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);await adopt(x);const path='/api/retail/orders/'+x.order.id+'/payments/receive',data=paymentData(),key='continuity-payment-key';assert.equal((await x.request(path,{...x.f,method:'POST',data,key})).status,201);revokeContinuity(x);assert.equal((await x.request(path,{...x.f,method:'POST',data,key})).status,409);assert.equal(x.db.prepare('SELECT count(*) n FROM payment_events WHERE order_id=?').get(x.order.id).n,1);verifyContinuity(x);});
test('revoking professional adoption retains actual receiving and permits explicit payment correction',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);await adopt(x);await positivePayment(x);job(x);revokeContinuity(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:1,reason:'已发生实际到货，来源撤销不抹事实'},'front');const p=x.db.prepare('SELECT * FROM payment_events WHERE order_id=?').get(x.order.id),z=await x.request('/api/retail/orders/'+x.order.id+'/payments/void',{...x.m,method:'POST',data:{expected_order_version:1,expected_revision:1,source_id:p.id,reason:'实际误录更正保留原记录'}});assert.equal(z.status,201,JSON.stringify(z.body));assert.equal(x.db.prepare('SELECT count(*) n FROM refund_events').get().n,0);verifyContinuity(x);});
test('new clinical owner requires a fresh new-order approval and separate professional re-adoption',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);await adopt(x);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('successor','successor','successor',hashPassword('synthetic-only-password'),'professional','a');const next=await x.login('successor');await event(x,x.c,'assign',{owner_id:'successor'},x.m);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_execute,0);assert.equal((await adopt(x)).status,403);assert.equal((await approve(x,next)).status,201);assert.equal((await adopt(x,next)).status,201);job(x);verifyContinuity(x);});
test('later revocation of adopted original review material holds execution but preserves old references',async t=>{const x=await continuitySetup(t),id=proof(x);assert.equal((await rv(x,{manifest:{...manifest(),attachments:[id]}})).status,201);await re(x,'adjust');await approved(x);commerciallyApprove(x);await adopt(x);job(x);x.db.prepare('UPDATE attachments SET revoked_at=?,revoked_by=?,revocation_reason=? WHERE id=?').run(now(),'front','实际原资料撤销',id);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_execute,0);assert.equal((await adopt(x)).status,409);verifyContinuity(x);});
test('closing the same professionally confirmed review preserves its adoption; independent new feedback can be selected explicitly',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);await adopt(x);await end(x);assert.equal(X.continuityRecord(x.db,x.plan.id).context.can_execute,1);const prior=x.review.id;await reviewedRoot(x,{feedback_note:'后来独立的新反馈条目'});await re(x,'adjust');assert.equal((await adopt(x)).status,201);assert.equal(X.continuityRecord(x.db,x.plan.id).history[1].review_id,prior);assert.equal(X.continuityRecord(x.db,x.plan.id).event.review_id,x.review.id);verifyContinuity(x);});
test('professional adoption and immutable root roll back together when the audit fails',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);x.db.exec("CREATE TRIGGER continuity_audit_failure BEFORE INSERT ON audit_events WHEN NEW.action='specialty.continuity.approve' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END");assert.equal((await adopt(x)).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_continuity_sources').get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_continuity_events').get().n,0);x.db.exec('DROP TRIGGER continuity_audit_failure');assert.equal((await adopt(x)).status,201);verifyContinuity(x);});
test('direct professional adoption failure cannot leave an orphan fixed source',async t=>{const x=await continuitySetup(t);await approved(x);assert.throws(()=>X.approveContinuity(x.db,x.plan.id,{review_id:x.review.id,source_note:'明确原来源',note:'',reason:'实际来源',next_step:'待继续'},'professional'),/continuity/);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_continuity_sources').get().n,0);verifyContinuity(x);});
test('every new source table and the upgrade boundary reject updates or deletes',async t=>{const x=await continuitySetup(t);await approved(x);commerciallyApprove(x);await adopt(x);job(x);X.createSpecialtyArchive(x.db,x.oldClinical.id,{next_step:'保留实际待办',...note()},'front');for(const n of X.continuityTables){const c=x.db.prepare('PRAGMA table_info('+n+')').all()[0].name;assert.throws(()=>x.db.exec('UPDATE '+n+' SET '+c+'='+c),/immutable/);assert.throws(()=>x.db.exec('DELETE FROM '+n),/immutable/);}verifyContinuity(x);});
test('same-millisecond archive cutoffs preserve the earlier source and reject a substituted later index',async t=>{const x=await continuitySetup(t),at=now(),a=X.createSpecialtyArchive(x.db,x.oldClinical.id,{next_step:'实际当时待办',...note()},'front',at);R.saveSpecialtyReviewVersion(x.db,x.review.id,ri({reported_at:at,feedback_note:'同毫秒后来新增的实际反馈'}),'front',at);verifyContinuity(x);const later=X.archiveCutoffs(x.db),json=JSON.stringify(X.archiveSourceIndex(x.db,x.oldClinical.id,later));tamper(x.db,'specialty_archives','UPDATE specialty_archives SET snapshot_json=?,snapshot_sha256=? WHERE id=?',[json,X.archiveDigest(json),a.id]);assert.throws(()=>verifySpecialtyContinuity(x.db),/归档/);});
test('archive digest and complete source index independently reject corruption',async t=>{const x=await continuitySetup(t),a=X.createSpecialtyArchive(x.db,x.oldClinical.id,{next_step:'实际原来源待续',...note()},'front');tamper(x.db,'specialty_archives','UPDATE specialty_archives SET snapshot_sha256=? WHERE id=?',['0'.repeat(64),a.id]);assert.throws(()=>verifySpecialtyContinuity(x.db),/归档/);});
import {seedDemoSpecialtyTrace} from '../src/demo-specialty-trace.mjs';
import {seedDemoSpecialtyCare} from '../src/demo-specialty-care.mjs';
import {seedDemoSpecialtyReviews} from '../src/demo-specialty-review.mjs';
import {seedDemoSpecialtyContinuity} from '../src/demo-specialty-continuity.mjs';
function continuityDemo(d){d.exec("INSERT INTO stores VALUES('a','A')");for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');d.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'demo-front');d.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('demo-retail-cycle','sample-retail','retail','虚构需求','draft',now(),'demo-front');seedDemoSpecialty(d);seedDemoSpecialtyTrace(d);seedDemoSpecialtyCare(d);seedDemoSpecialtyReviews(d);}
test('three synthetic replacement branches and three archives append once while all previous rows remain unchanged',t=>{const d=openDatabase(':memory:');t.after(()=>d.close());continuityDemo(d);const tables=d.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%'").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoSpecialtyContinuity(d),{plans:3,archives:3});for(const n of tables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid LIMIT ?').all(before[n].length),before[n],n);assert.equal(d.prepare("SELECT status FROM specialty_case_current WHERE case_id='demo-specialty-review-stop-case'").get().status,'stopped');assert.equal(d.prepare("SELECT status FROM aftercare_replacement_events WHERE plan_id='demo-specialty-continuity-delivered-plan' ORDER BY revision DESC LIMIT 1").get().status,'completed');verifySpecialtyContinuity(d);const after=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.deepEqual(seedDemoSpecialtyContinuity(d),{plans:0,archives:0});for(const n of tables)assert.deepEqual(d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),after[n],n);});
test('nonempty schema34 upgrade preserves earlier unrecorded professional replacement history without fabricating adoption',t=>{const dir=mkdtempSync(join(tmpdir(),'continuity-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,34)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}continuityDemo(d);const delivery=d.prepare("SELECT d.id FROM fulfillment_events d JOIN processing_jobs j ON j.id=d.job_id WHERE j.order_id='demo-specialty-order-delivered' AND d.action='deliver'").get().id,at=now();insertAftercareCase(d,delivery,{kind:'remake',quantity:1,title:'升级前明确商业安排',...note()},'demo-front',at,'legacy-aftercare');insertAftercareEvent(d,'legacy-aftercare',{action:'assign',assignee_id:'demo-front',due_date:null,...note()},'demo-manager',at);insertAftercareEvent(d,'legacy-aftercare',{action:'start',...note()},'demo-front',at);const c=S.specialtyCase(d,'demo-specialty-ready');d.prepare('INSERT INTO retail_orders VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('legacy-new','a','sample-retail',d.prepare('SELECT max(serial)+1 n FROM retail_orders').get().n,'OW-LEGACY','demo-retail-cycle',1,null,'cycle',at,'demo-front');insertOrderVersion(d,'legacy-new',{title:'原商业新单',notes:null,items:[{product_id:'demo-specialty-trace-product',product_version:1,quantity:1,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'升级前实际安排'},'demo-front','draft',at);insertReplacement(d,'legacy-aftercare',{kind:'remake',quantity:1,new_order_id:'legacy-new',new_order_version:1,instructions:'旧商业安排，专业历史未记录',...note()},'demo-front',at,'legacy-plan');insertReplacementEvent(d,'legacy-plan',{action:'approve',...note()},'demo-manager',at);insertProcessingJob(d,'legacy-new',{lines:[{position:1,supply_mode:'purchase',processing_mode:'internal',supplier_name:'虚构',assignee_id:'demo-professional',due_date:null,instructions:'旧实际商业安排'}],reason:'升级前'},'demo-manager',at);const tables=d.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'schema_migrations'").all().map(x=>x.name),before=Object.fromEntries(tables.map(n=>[n,d.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));d.close();const u=openDatabase(path);for(const n of tables)assert.deepEqual(u.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),before[n],n);assert.ok(u.prepare('SELECT operation_rowid FROM specialty_continuity_boundary').get().operation_rowid>0);assert.equal(u.prepare('SELECT count(*) n FROM specialty_continuity_execution_refs').get().n,0);assert.equal(u.prepare('SELECT count(*) n FROM specialty_continuity_events').get().n,0);verifySpecialtyContinuity(u);u.close();});
