import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('a','A'),('b','B')");for(const [id,role,store] of [['manager','manager','a'],['front','reception','a'],['professional','professional','a'],['other','manager','b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','a'],['two','a'],['other-child','b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}
import * as S from '../src/specialty.mjs';
import {verifySpecialty} from '../src/specialty-recovery.mjs';
import {createHash} from 'node:crypto';
const now=()=>new Date().toISOString(),note=()=>({note:'明确本地记录（虚构）',reason:'实际来源核对'}),pi=()=>({...Object.fromEntries(S.protocolFields.map(k=>[k,k==='title'?'接触镜条件来源（虚构）':'明确人工来源，未知规则不补造：'+k])),require_assessment_evidence:false,require_consent_evidence:false,...note()}),ci=()=>({title:'专项评估（虚构）',assessment_note:'资料尚待专业明确核对',suitability:'pending',suitability_note:'未知，不推定适用',assessed_at:null,source_note:'仅虚构人工资料',next_step:'由明确专业责任人继续评估',document_ids:[],attachment_ids:[],...note()}),signed=()=>({party:'guardian',party_label:'虚构监护人',relationship_note:'明确虚构身份与关系来源；不从查看授权推定',signed_at:new Date(Date.now()-1000).toISOString(),source_note:'明确记录本版本知情同意来源，非真实签署',document_ids:[],attachment_ids:[],...note()});
async function setup(t,opts){const x=await fixture(t,opts);x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('cycle-one','one','retail','明确配镜需求','draft',now(),'front');return {...x,m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')};}
const seq=x=>S.specialtySequence(x.db,'a');
async function post(x,path,u,data,key){return x.request('/api/specialty/'+path,{...u,method:'POST',data:{expected_sequence:seq(x),...data},...(key?{key}:{})});}
async function protocol(x,extra={},adopt=true){let z=await post(x,'protocols',x.m,{code:'DEMO-'+crypto.randomUUID().slice(0,8),service_type:'contact_lens',...pi(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));let r=z.body.record;if(adopt){z=await post(x,'protocols/'+r.id+'/events',x.m,{expected_revision:r.revision,expected_version:r.version,action:'adopt',...note()});assert.equal(z.status,201,JSON.stringify(z.body));r=z.body.record;}return r;}
async function fitting(x,p,extra={},u=x.f){const z=await post(x,'cases',u,{customer_id:'one',protocol_id:p.id,protocol_version:p.current_version,protocol_revision:p.revision,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function cv(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/versions',x.p,{expected_revision:r.revision,expected_version:r.current_version,...ci(),suitability:'suitable',suitability_note:'由本条专业责任人明确记录的虚构判断',assessed_at:new Date(Date.now()-1000).toISOString(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function consent(x,c,extra={}){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/consents',x.f,{expected_case_revision:r.revision,...signed(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
async function event(x,c,action,extra={},u=action==='assign'?x.m:x.p){const r=S.specialtyCase(x.db,c.id),z=await post(x,'cases/'+c.id+'/events',u,{expected_revision:r.revision,expected_version:r.current_version,action,next_step:'保留明确后续',...note(),...extra});assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
const snapshot=db=>Object.fromEntries(S.specialtyTables.map(n=>[n,db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
function proof(x,customer='one',id=crypto.randomUUID()){const b=Buffer.from('synthetic specialty source; no true signature'),hash=createHash('sha256').update(b).digest('hex');x.db.prepare('INSERT OR IGNORE INTO attachment_blobs VALUES(?,?,?)').run(hash,b,b.length);x.db.prepare('INSERT INTO attachments(id,customer_id,filename,content_type,blob_sha256,size,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(id,customer,'specialty-source.txt','text/plain',hash,b.length,now(),'front');return id;}

import * as T from '../src/specialty-trace.mjs';
import {verifySpecialtyTrace} from '../src/specialty-trace-recovery.mjs';
import {insertParameterVersion,insertParameterEvent} from '../src/parameters.mjs';
import {insertProcessingJob,insertProcessingEvent,processingRecord} from '../src/processing.mjs';
import {insertFulfillmentEvent,fulfillmentRecord} from '../src/fulfillment.mjs';
import {parameterContext} from '../src/parameter-ledger.mjs';
async function traceSetup(t,opts){const x=await setup(t,opts),pr=await protocol(x);let c=await fitting(x,pr);c=await cv(x,c);const a=await consent(x,c);c=await event(x,c,'adopt',{consent_id:a.id,consent_revision:a.revision});const prod=await x.request('/api/retail/products',{...x.m,method:'POST',data:{sku:'CL-'+crypto.randomUUID().slice(0,8),name:'虚构镜片订片',category:'lens',brand:null,specification:'仅演示来源，非临床参数',unit:'片',list_price_cents:100,status:'active',reason:'虚构'}});assert.equal(prod.status,201,JSON.stringify(prod.body));const o=await x.request('/api/customers/one/retail-orders',{...x.f,method:'POST',data:{title:'专项原单（虚构）',notes:null,cycle_id:'cycle-one',cycle_version:1,visit_id:null,items:[{product_id:prod.body.product.id,product_version:1,quantity:2,unit_price_cents:100,note:null}],document_version_ids:[],attachment_ids:[],reason:'虚构'}});assert.equal(o.status,201,JSON.stringify(o.body));Object.assign(x,{c,a,pr,order:o.body.order,product:prod.body.product});checkParam(x);return x;}
function checkParam(x){const p=insertParameterVersion(x.db,x.order.id,{source:'staff_record',source_note:'虚构来源，不代替正式处方',values:[{position:1,label:'虚构交接项',value:'样例交接值',unit:null,condition:null}],document_version_ids:[],attachment_ids:[],...note()},'front').parameter;insertParameterEvent(x.db,p.id,{action:'submit',...note()},'front');insertParameterEvent(x.db,p.id,{action:'check',...note()},'professional');return p.id;}
function approvalInput(x){const z=T.approvalCandidates(x.db,x.order.id),c=S.specialtyCase(x.db,x.c.id);return {expected_sequence:T.traceSequence(x.db,'a'),case_id:c.id,expected_order_version:1,expected_case_revision:c.revision,expected_specialty_sequence:seq(x),expected_approval_revision:T.specialtyOrderContext(x.db,x.order.id)?.approval_revision||0,parameter_version_id:z.parameter.id,expected_parameter_sequence:z.parameter.sequence,...note()};}
const approve=(x,who=x.p,extra={},key)=>x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/approvals',{...who,method:'POST',data:{...approvalInput(x),...extra},key});
async function approved(x){const z=await approve(x);assert.equal(z.status,201,JSON.stringify(z.body));return z.body.record;}
function job(x){const j=insertProcessingJob(x.db,x.order.id,{lines:[{position:1,supply_mode:'purchase',processing_mode:'internal',supplier_name:'虚构供应方',assignee_id:'professional',due_date:null,instructions:'仅虚构交接'}],reason:'虚构'},'manager');x.job=j;return j;}
function received(x){job(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:2,reason:'虚构实际到货'},'front');return x.db.prepare("SELECT * FROM processing_events WHERE job_id=? AND action='receive'").get(x.job.id);}
const li=(extra={})=>({trace_status:'recorded',lot_number:'DEMO-LOT-ONLY',serial_note:'序列尚未知，明确原来源',manufacturer_note:'虚构生产来源',supplier_note:'虚构供货来源',source_note:'虚构原包装批号，不代表真实产品',document_ids:[],attachment_ids:[],...note(),...extra});
async function lot(x,e,extra={},key){return x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/lots',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),receive_event_id:e.id,quantity:2,...li(extra)},key});}
async function revision(x,l,extra={}){return x.request('/api/specialty-lots/'+l.id+'/versions',{...x.f,method:'POST',data:{expected_sequence:T.traceSequence(x.db,'a'),expected_revision:l.revision,...li(extra)}});}
async function revoke(x){return post(x,'consents/'+x.a.id+'/events',x.f,{expected_revision:1,action:'revoke',occurred_at:now(),...note()});}
async function process(x,action,key){const p=processingRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/events',{...x.p,method:'POST',key,data:{expected_revision:p.revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action,position:1,quantity:2,reason:'虚构实际执行'}});}
function finished(x){insertProcessingEvent(x.db,x.job.id,{action:'start',position:1,quantity:2,reason:'虚构'},'professional');insertProcessingEvent(x.db,x.job.id,{action:'complete',position:1,quantity:2,reason:'虚构'},'professional');}
async function qc(x){const f=fulfillmentRecord(x.db,x.job.id),c=parameterContext(x.db,x.job.id);return x.request('/api/processing/jobs/'+x.job.id+'/fulfillment/events',{...x.p,method:'POST',data:{expected_revision:f.revision,expected_processing_revision:f.processing_revision,expected_parameter_sequence:c.sequence,expected_parameter_review_revision:c.review_revision,action:'check_pass',position:1,quantity:2,source_id:null,checks:[{label:'虚构明确检查项',result:'pass',notes:'虚构检查事实'}],reason:'虚构检查'}});}
const verify=x=>{verifySpecialty(x.db);verifySpecialtyTrace(x.db);};
test('professional explicitly fixes assessment, informed consent, checked parameter and untouched same-cycle lens order',async t=>{const x=await traceSetup(t);assert.equal((await approve(x,x.m)).status,403);assert.equal((await approve(x,x.f)).status,403);const r=await approved(x);assert.equal(r.context.can_execute,true);assert.equal(r.parameter.values[0].unit,null);assert.equal(r.approval.case_version,2);assert.equal(x.db.prepare('SELECT count(*) n FROM payment_events').get().n,0);verify(x);});
test('different customer, cycle or physical category cannot become specialty source',async t=>{const x=await traceSetup(t);assert.equal((await approve(x,x.p,{case_id:'missing-other-customer'})).status,404);assert.equal((await approve(x,x.p,{parameter_version_id:'missing'})).status,409);verify(x);});
test('existing processing facts cannot acquire retroactive clinical authority',async t=>{const x=await traceSetup(t);job(x);assert.equal((await approve(x)).body.error.code,'SPECIALTY_ORDER_EXECUTED');assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_order_links').get().n,0);});
test('withdrawal protects new execution, cached start replay and native writes while actual arrival still records',async t=>{const x=await traceSetup(t);await approved(x);received(x);const key=crypto.randomUUID(),z=await process(x,'start',key);assert.equal(z.status,201,JSON.stringify(z.body));assert.equal((await revoke(x)).status,201);assert.equal((await process(x,'complete')).body.error.code,'SPECIALTY_ORDER_HOLD');assert.equal((await process(x,'start',key)).status,409);assert.throws(()=>insertProcessingEvent(x.db,x.job.id,{action:'complete',position:1,quantity:2,reason:'虚构'},'professional'),/specialty current approval/);verify(x);});
test('arrival and batch provenance can be recorded after withdrawal without resuming execution',async t=>{const x=await traceSetup(t);await approved(x);job(x);await revoke(x);insertProcessingEvent(x.db,x.job.id,{action:'receive',position:1,quantity:2,reason:'实际已到货'},'front');const e=x.db.prepare("SELECT * FROM processing_events WHERE job_id=? AND action='receive'").get(x.job.id),z=await lot(x,e);assert.equal(z.status,201,JSON.stringify(z.body));assert.equal(T.specialtyOrderContext(x.db,x.order.id).can_execute,false);verify(x);});
test('unknown batch blocks positive quality; explicit source revision keeps original unknown fact and quantity',async t=>{const x=await traceSetup(t);await approved(x);const e=received(x),z=await lot(x,e,{trace_status:'unknown',lot_number:null});assert.equal(z.status,201);finished(x);assert.equal((await qc(x)).body.error.code,'SPECIALTY_TRACE_REQUIRED');const next=await revision(x,z.body.record);assert.equal(next.status,201,JSON.stringify(next.body));assert.equal(next.body.record.history[1].trace_status,'unknown');assert.equal((await qc(x)).status,201);verify(x);});
test('lot allocation is bounded by each actual receipt and never duplicated by retries or over-allocation',async t=>{const x=await traceSetup(t);await approved(x);const e=received(x),key=crypto.randomUUID(),data={expected_sequence:T.traceSequence(x.db,'a'),receive_event_id:e.id,quantity:2,...li()},send=()=>x.request('/api/retail/orders/'+x.order.id+'/specialty-trace/lots',{...x.f,method:'POST',data,key});assert.equal((await send()).status,201);assert.equal((await send()).status,201);assert.equal((await lot(x,e)).body.error.code,'SPECIALTY_TRACE_CAPACITY');assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_product_lots').get().n,1);verify(x);});
test('parameter change requires new specialty approval as well as existing processing original-version review',async t=>{const x=await traceSetup(t);await approved(x);received(x);checkParam(x);assert.equal((await process(x,'start')).status,409);await approved(x);assert.equal((await process(x,'start')).status,201);verify(x);});
test('changed clinical information after start cannot replace original assessment authorization',async t=>{const x=await traceSetup(t);await approved(x);received(x);await process(x,'start');x.c=await cv(x,x.c);x.a=await consent(x,x.c);x.c=await event(x,x.c,'adopt',{consent_id:x.a.id,consent_revision:1});assert.equal((await approve(x)).body.error.code,'SPECIALTY_ORDER_CHANGED');verify(x);});
test('changed responsibility and pause/resume require explicit specialty reapproval and preserve earlier actor',async t=>{const x=await traceSetup(t);const r=await approved(x);await event(x,x.c,'pause');await event(x,x.c,'resume',{consent_id:x.a.id,consent_revision:1});assert.equal(T.specialtyOrderContext(x.db,x.order.id).can_execute,false);const next=await approved(x);assert.equal(next.approval.revision,2);assert.equal(next.approvals[1].id,r.approval.id);verify(x);});
test('revoked trace attachment blocks quality without erasing previous batch version or successful history',async t=>{const x=await traceSetup(t);await approved(x);const e=received(x),id=proof(x);await lot(x,e,{attachment_ids:[id]});finished(x);assert.equal((await qc(x)).status,201);x.db.prepare('UPDATE attachments SET revoked_at=?,revoked_by=?,revocation_reason=? WHERE id=?').run(now(),'front','明确撤销',id);verify(x);assert.equal(T.lotRecord(x.db,x.db.prepare('SELECT id FROM specialty_product_lots').get().id).source_live,false);});
test('cross-store, guardian and strict fields cannot read or write internal trace',async t=>{const x=await traceSetup(t);await approved(x);const path='/api/retail/orders/'+x.order.id+'/specialty-trace';assert.equal((await x.request(path,x.o)).status,404);assert.equal((await x.request(path,x.g)).status,403);assert.equal((await approve(x,x.p,{diagnosis:'invented'})).status,422);});
test('approval audit failure rolls link, approval and idempotency back; identical retry succeeds once',async t=>{const x=await traceSetup(t);x.db.exec("CREATE TRIGGER trace_audit_failure BEFORE INSERT ON audit_events WHEN NEW.action='specialty.trace.approve' BEGIN SELECT RAISE(ABORT,'forced audit'); END");const key=crypto.randomUUID();assert.equal((await approve(x,x.p,{},key)).status,500);assert.equal(x.db.prepare('SELECT count(*) n FROM specialty_order_links').get().n,0);x.db.exec('DROP TRIGGER trace_audit_failure');assert.equal((await approve(x,x.p,{},key)).status,201);verify(x);});
test('native immutable and received-capacity guards reject direct source replacement',async t=>{const x=await traceSetup(t);await approved(x);const e=received(x),z=await lot(x,e);assert.equal(z.status,201);assert.throws(()=>T.createSpecialtyLot(x.db,x.order.id,{receive_event_id:e.id,quantity:1,...li()},'front'),/capacity/);assert.throws(()=>x.db.prepare("UPDATE specialty_lot_versions SET lot_number='other'").run(),/immutable/);verify(x);});
test('all trace records and captured execution references survive verified independent restore after withdrawal',async t=>{const x=await traceSetup(t,{persist:true});await approved(x);const e=received(x);await lot(x,e);finished(x);await qc(x);await revoke(x);const b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,46);await restoreBackup(b.backup,join(x.dir,'restored'));const r=new DatabaseSync(join(x.dir,'restored','workbench.sqlite'));verifySpecialtyTrace(r);for(const n of T.specialtyTraceTables)assert.deepEqual(r.prepare('SELECT * FROM '+n).all(),x.db.prepare('SELECT * FROM '+n).all());r.close();});
test('recovery rejects substituting a later consent source even when the trace row remains immutable',async t=>{const x=await traceSetup(t);await approved(x);received(x);finished(x);x.db.exec('DROP TRIGGER specialty_order_approvals_no_update');x.db.prepare('UPDATE specialty_order_approvals SET case_revision=case_revision-1').run();assert.throws(()=>verifySpecialtyTrace(x.db),/当时明确/);});

import {seedDemoSpecialtyTrace} from '../src/demo-specialty-trace.mjs';
import {insertStockEvent} from '../src/inventory.mjs';
import {insertDispatch} from '../src/dispatch.mjs';
test('captured product lot versions remain exact through quality, signature and physical outbound',async t=>{const x=await traceSetup(t);await approved(x);const e=received(x);await lot(x,e);finished(x);const pass=insertFulfillmentEvent(x.db,x.job.id,{action:'check_pass',position:1,quantity:2,checks:[{label:'虚构项目',result:'pass',notes:'明确'}],reason:'虚构'},'professional').event;const d=insertFulfillmentEvent(x.db,x.job.id,{action:'deliver',position:1,quantity:2,source_id:pass.id,receiver_name:'虚构领取人',receipt_note:'虚构签收',handed_at:now(),reason:'虚构'},'front').event;insertStockEvent(x.db,{product_id:x.product.id,product_version:1,store_id:'a',action:'receive',quantity:2,reason:'虚构实物',created_by:'manager'});const r=insertDispatch(x.db,d.id,{quantity:1,reason:'虚构出库'},'manager');assert.equal(T.specialtyExecutionRef(x.db,r.event.id).lot_basis.length,1);await revoke(x);assert.throws(()=>insertDispatch(x.db,d.id,{quantity:1,reason:'新的出库'},'manager'),/specialty current approval/);verify(x);});
test('nonempty schema31 upgrade preserves all prior specialty roots and invents no order links or lot facts',t=>{const dir=mkdtempSync(join(tmpdir(),'trace-upgrade-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'old.sqlite'),d=new DatabaseSync(path);d.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const f of readdirSync(new URL('../migrations',import.meta.url)).sort().slice(0,31)){d.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));d.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(f,now());}d.exec("INSERT INTO stores VALUES('a','A')");for(const[id,role]of [['manager','manager'],['front','reception'],['professional','professional']])d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');d.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('one','a','one',null,null,null,now(),'front');d.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('cycle-one','one','retail','虚构需求','draft',now(),'front');const pr=S.createSpecialtyProtocol(d,'a',{code:'CL-OLD',service_type:'contact_lens',...pi()},'manager');S.specialtyProtocolEvent(d,pr.id,{action:'adopt',...note()},'manager');S.createSpecialtyCase(d,'a','one',{protocol_id:pr.id,protocol_version:1,protocol_revision:2,cycle_id:'cycle-one',cycle_version:1,visit_id:null,context_basis:'cycle',owner_id:'professional',...ci()},'front');const old=Object.fromEntries(S.specialtyTables.map(n=>[n,d.prepare('SELECT * FROM '+n).all()]));d.close();const u=openDatabase(path);assert.equal(u.prepare('SELECT count(*) n FROM schema_migrations').get().n,46);for(const n of S.specialtyTables)assert.deepEqual(u.prepare('SELECT * FROM '+n).all(),old[n]);for(const n of T.specialtyTraceTables)assert.equal(u.prepare('SELECT count(*) n FROM '+n).get().n,0);verifySpecialtyTrace(u);u.close();});
test('synthetic trace stages append once and keep original customer, consent and prior commerce',async t=>{const x=await fixture(t);for(const [id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,'a');x.db.prepare('INSERT INTO customers VALUES(?,?,?,?,?,?,?,?)').run('sample-retail','a','小陆（虚构）',null,null,null,now(),'front');x.db.prepare('INSERT INTO service_cycles VALUES(?,?,?,?,?,?,?)').run('demo-retail-cycle','sample-retail','retail','虚构需求','draft',now(),'front');const {seedDemoSpecialty}=await import('../src/demo-specialty.mjs');seedDemoSpecialty(x.db);const previous=Object.fromEntries(S.specialtyTables.map(n=>[n,x.db.prepare('SELECT * FROM '+n).all()]));assert.deepEqual(seedDemoSpecialtyTrace(x.db),{orders:3,lots:2});for(const n of S.specialtyTables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),previous[n]);const initial=Object.fromEntries(T.specialtyTraceTables.map(n=>[n,x.db.prepare('SELECT * FROM '+n).all()]));assert.deepEqual(seedDemoSpecialtyTrace(x.db),{orders:0,lots:0});for(const n of T.specialtyTraceTables)assert.deepEqual(x.db.prepare('SELECT * FROM '+n).all(),initial[n]);verifySpecialtyTrace(x.db);});
