import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('store-a','A'),('store-b','B')");for(const [id,role,store] of [['manager','manager','store-a'],['front','reception','store-a'],['professional','professional','store-a'],['other','manager','store-b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','store-a'],['two','store-a'],['other-child','store-b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='store-a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}

import * as S from '../src/staff-records.mjs';
import {verifyStaffRecords} from '../src/staff-records-recovery.mjs';
import {seedDemoStaffRecords} from '../src/demo-staff-records.mjs';
const qualification=()=>({credential_label:'虚构资质来源',identifier_status:'unknown',identifier:null,issuer_status:'unknown',issuer_note:null,issued_status:'unknown',issued_date:null,expiry_status:'unknown',expiry_date:null,scope_note:'尚待正式人工核验'}),facts=k=>k==='qualification'?qualification():k==='training'?{time_status:'unknown',occurred_at:null,training_label:'虚构员工培训',participation_status:'not_recorded',outcome_note:'来源待核对'}:{starts_at:'2026-10-01T08:00:00.000Z',ends_at:'2026-10-01T12:00:00.000Z',...(k==='shift'?{place_note:'虚构门店',duty_note:'人工安排说明'}:{absence_note:'虚构缺勤安排',coverage_note:'责任沿原流程办理'})};
async function intent(x,kind='qualification',staff='professional',extra={}){return {staff_id:staff,kind,title:'员工原来源（虚构）',data:facts(kind),source_reference:'synthetic:staff-source',source_note:'独立虚构原来源',record_note:'仅手工事实',reason:'开发记录核对',next_step:'正式业务另行验收',expected_employee_source:S.employeeSource(x.db,staff,'store-a')?.source_token||'0'.repeat(64),expected_sequence:S.staffRecordSequence(x.db,'store-a'),...extra};}
async function create(x,m,kind='qualification',staff='professional',extra={},key){return x.request('/api/staff-records',{...m,method:'POST',data:await intent(x,kind,staff,extra),...(key?{key}:{})});}
async function append(x,m,r,extra={},key){const i=await intent(x,r.kind,r.staff_id);delete i.staff_id;delete i.kind;Object.assign(i,extra);return x.request('/api/staff-records/'+r.id+'/versions',{...m,method:'POST',data:{...i,expected_revision:r.revision,expected_version:r.current_version},...(key?{key}:{})});}
async function withdraw(x,m,r,extra={},key){return x.request('/api/staff-records/'+r.id+'/events',{...m,method:'POST',data:{action:'withdraw',expected_employee_source:S.employeeSource(x.db,r.staff_id,'store-a').source_token,expected_sequence:S.staffRecordSequence(x.db,'store-a'),expected_revision:r.revision,expected_version:r.current_version,reason:'人工撤回解释',next_step:'保留原事实',...extra},...(key?{key}:{})});}
const snapshot=db=>Object.fromEntries(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'staff_record_%' AND name NOT IN('schema_migrations','audit_events','idempotency','sessions') ORDER BY name").all().map(x=>[x.name,db.prepare('SELECT * FROM '+x.name+' ORDER BY rowid').all()]));
test('four explicit employee record types keep unknown facts and never grant permission, alter stock or invent customer events',async t=>{const x=await fixture(t),m=await x.login('manager'),before=snapshot(x.db);for(const k of S.staffRecordKinds){const a=await create(x,m,k);assert.equal(a.status,201,JSON.stringify(a.body));assert.equal(a.body.record.kind,k);assert.equal(a.body.record.version,1);assert.equal(a.body.record.professional_qualification_status,'not_verified');assert.deepEqual(a.body.record.data,facts(k));}assert.deepEqual(snapshot(x.db),before);verifyStaffRecords(x.db);});
test('manager employee privacy and fixed store exclude other staff, customers and guardian records',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record;for(const id of ['front','professional','parent']){const u=await x.login(id);for(const path of ['/api/staff-records/employees/professional','/api/staff-records/'+r.id])assert.equal((await x.request(path,u)).status,403);assert.equal((await create(x,u)).status,403);}const other=await x.login('other');assert.equal((await x.request('/api/staff-records/'+r.id,other)).status,404);for(const staff of ['other','parent','one'])assert.equal((await create(x,m,'qualification',staff)).status,404);assert.equal((await x.request('/api/staff-records/employees/other',m)).status,404);});
test('typed validation rejects inferred identifiers, invalid dates, future actual training, wrong periods and unknown fields',async t=>{const x=await fixture(t),m=await x.login('manager');for(const data of [{...qualification(),identifier:'inferred'},{...qualification(),issuer_status:'verified'},{...qualification(),issued_status:'recorded',issued_date:'2026-02-30'},{...qualification(),issued_status:'recorded',issued_date:'2999-01-01'},{...qualification(),expiry_status:'recorded',expiry_date:'x'},{...qualification(),automatic_verified:true}])assert.equal((await create(x,m,'qualification','professional',{data})).status,422);for(const data of [{...facts('training'),time_status:'recorded',occurred_at:'2999-01-01T00:00:00.000Z'},{...facts('training'),participation_status:'qualified'}])assert.equal((await create(x,m,'training','professional',{data})).status,422);assert.equal((await create(x,m,'shift','professional',{data:{...facts('shift'),ends_at:facts('shift').starts_at}})).status,422);for(const extra of [{automatic_approval:true},{source_reference:''},{reason:'\0'},{kind:'license_verified'}])assert.equal((await create(x,m,'qualification','professional',extra)).status,422);assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_roots').get().n,0);});
test('new versions and explicit withdrawal retain fixed old facts; later explicit sources cannot change employee or type',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record,a=await append(x,m,r,{title:'后续原来源',data:{...qualification(),identifier_status:'recorded',identifier:'FICTIONAL-002'}});assert.equal(a.status,201);const b=await withdraw(x,m,a.body.record);assert.equal(b.status,201);assert.equal(b.body.record.status,'withdrawn');assert.equal((await withdraw(x,m,b.body.record)).status,409);const c=await append(x,m,b.body.record,{title:'人工新事实'});assert.equal(c.status,201);assert.equal(c.body.record.version,3);const old=await x.request('/api/staff-records/'+r.id+'?version=1',m);assert.deepEqual(old.body.record.data,qualification());assert.equal(old.body.record.title,r.title);assert.equal(old.body.record.current_version,3);assert.equal(old.body.record.total,4);assert.equal((await append(x,m,c.body.record,{kind:'training'})).status,422);assert.equal((await append(x,m,c.body.record,{staff_id:'front'})).status,422);verifyStaffRecords(x.db);});
test('successful retries replay once after own versions and withdrawal; external employee changes still reject cached adoption',async t=>{const x=await fixture(t),m=await x.login('manager'),i=await intent(x),key=crypto.randomUUID(),a=await x.request('/api/staff-records',{...m,method:'POST',data:i,key}),b=await append(x,m,a.body.record);await withdraw(x,m,b.body.record);const retry=await x.request('/api/staff-records',{...m,method:'POST',data:i,key});assert.equal(retry.status,201);assert.deepEqual(retry.body,a.body);assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_roots').get().n,1);assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:{...i,title:'changed'},key})).status,409);x.db.prepare("UPDATE users SET display_name='员工资料后续变化' WHERE id='professional'").run();assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:i,key})).body.error.code,'STAFF_EMPLOYEE_CHANGED');});
test('inactive employee can retain current manually sourced records while old active status and security leases reject',async t=>{const x=await fixture(t),m=await x.login('manager'),i=await intent(x);x.db.prepare("UPDATE users SET active=0 WHERE id='professional'").run();assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:i})).status,409);assert.equal((await create(x,m)).status,201);const j=await intent(x);x.db.prepare("INSERT INTO user_security VALUES('professional',2,1)").run();assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:j})).status,409);assert.equal((await create(x,m,'absence')).status,201);assert.equal(x.db.prepare("SELECT active FROM users WHERE id='professional'").get().active,0);});
test('store sequence and current original revision give competing writes one winner without adopting stale records',async t=>{const x=await fixture(t),m=await x.login('manager'),i=await intent(x),a=await x.request('/api/staff-records',{...m,method:'POST',data:i});assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:i})).status,409);const b=await append(x,m,a.body.record);assert.equal((await append(x,m,a.body.record)).status,409);assert.equal((await withdraw(x,m,a.body.record)).status,409);assert.equal(b.status,201);});
async function delayed(x,m,i,change){const payload=JSON.stringify(i);return new Promise((resolve,reject)=>{const req=httpRequest(x.origin+'/api/staff-records',{method:'POST',headers:{Cookie:m.cookie,'X-CSRF-Token':m.csrf,'Idempotency-Key':crypto.randomUUID(),'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}},res=>{let data='';res.on('data',c=>data+=c);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(data)}));});req.on('error',reject);req.write(payload.slice(0,1));setTimeout(()=>{change();req.end(payload.slice(1));},25);});}
test('post-body current actor security, store and revoked session checks reject pending writes before cache or ledger',async t=>{for(const change of [db=>db.exec("UPDATE users SET role='reception' WHERE id='manager'"),db=>db.exec("UPDATE users SET store_id='store-b' WHERE id='manager'"),db=>db.exec("UPDATE users SET active=0 WHERE id='manager'"),db=>db.exec("INSERT INTO user_security VALUES('manager',2,0)"),db=>db.exec("INSERT INTO user_security VALUES('manager',2,1)"),db=>db.exec('DELETE FROM sessions')]){const x=await fixture(t),m=await x.login('manager'),r=await delayed(x,m,await intent(x),()=>change(x.db));assert.ok([401,403].includes(r.status),JSON.stringify(r));assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_roots').get().n,0);assert.equal(x.db.prepare('SELECT count(*) n FROM idempotency').get().n,0);}});
test('complete filtered list and old version histories paginate beyond one hundred and reject mixed snapshots',async t=>{const x=await fixture(t),m=await x.login('manager'),i=await intent(x);let r;for(let n=0;n<105;n++){const q=S.createStaffRecord(x.db,'store-a',{...i,title:'条目 '+n,kind:n%2?'training':'qualification',data:facts(n%2?'training':'qualification')},'manager');if(!r)r=q;}const list=await x.request('/api/staff-records/employees/professional?limit=100',m);assert.equal(list.body.total,105);assert.equal(list.body.items.length,100);assert.equal(list.body.next_offset,100);assert.equal((await x.request('/api/staff-records/employees/professional?offset=100',m)).status,409);const last=await x.request('/api/staff-records/employees/professional?offset=100&expected_source='+list.body.source_token,m);assert.equal(last.body.items.length,5);assert.equal((await x.request('/api/staff-records/employees/professional?kind=training',m)).body.total,52);for(let n=0;n<104;n++)r=S.recordStaffVersion(x.db,r.id,{...i,title:'来源版本 '+n},'manager');const detail=await x.request('/api/staff-records/'+r.id+'?version=1&limit=100',m);assert.equal(detail.body.record.total,105);assert.equal(detail.body.record.history.length,100);const end=await x.request('/api/staff-records/'+r.id+'?version=1&offset=100&expected_source='+detail.body.source_token,m);assert.equal(end.body.record.history.length,5);assert.equal(end.body.record.version,1);S.withdrawStaffRecord(x.db,r.id,{reason:'手工撤回',next_step:'保留旧事实'},'manager');assert.equal((await x.request('/api/staff-records/'+r.id+'?offset=100&expected_source='+detail.body.source_token,m)).status,409);verifyStaffRecords(x.db);});
test('strict bounded paging and literal filters reject repeated parameters, invalid fields and unsupported verbs',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record;for(const q of ['limit=101','offset=-1','kind=invalid','status=approved','limit=1&limit=2','extra=x'])assert.equal((await x.request('/api/staff-records/employees/professional?'+q,m)).status,422);for(const q of ['version=0','version=-1','limit=0','q=x'])assert.equal((await x.request('/api/staff-records/'+r.id+'?'+q,m)).status,422);assert.equal((await x.request('/api/staff-records/'+r.id+'?version=999',m)).status,404);assert.equal((await x.request('/api/staff-records',{...m,method:'GET'})).status,405);assert.equal((await x.request('/api/staff-records/'+r.id,{...m,method:'PATCH',data:{}})).status,405);});
test('native immutable roots, typed canonical facts and paired events prevent direct bypass or partial creation',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record;for(const table of S.staffRecordTables){assert.throws(()=>x.db.exec('DELETE FROM '+table),/immutable/);assert.throws(()=>x.db.exec('UPDATE '+table+' SET id=id'),/immutable/);}const count=x.db.prepare('SELECT count(*) n FROM staff_record_versions').get().n;for(const actor of ['front','professional','other'])assert.throws(()=>S.createStaffRecord(x.db,'store-a',awaitlessIntent(r),actor),/actor/);assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_versions').get().n,count);assert.throws(()=>S.recordStaffVersion(x.db,r.id,{...awaitlessIntent(r),data:{...qualification(),identifier:'invented'}},'manager'),/invalid/);verifyStaffRecords(x.db);});
function awaitlessIntent(r){return {staff_id:r.staff_id,kind:r.kind,title:r.title,data:r.data,source_reference:r.source_reference,source_note:r.source_note,record_note:r.record_note,reason:r.reason,next_step:'后续业务人工验收'};}
test('missing first version or missing paired record event cannot commit orphan native sources',async t=>{const x=await fixture(t),at=new Date().toISOString();assert.throws(()=>x.db.prepare('INSERT INTO staff_record_roots VALUES(?,?,?,?,?,?,?,?,?)').run('orphan','professional','store-a','qualification',1,'SR-'+at.slice(0,10).replaceAll('-','')+'-00001','missing',at,'manager'),/FOREIGN KEY/);assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_roots').get().n,0);});
test('audit failure rolls roots, version, event and retry key back together',async t=>{const x=await fixture(t),m=await x.login('manager'),i=await intent(x),key=crypto.randomUUID();x.db.exec("CREATE TRIGGER break_staff_audit BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'staff-record.%' BEGIN SELECT RAISE(ABORT,'forced audit failure'); END;");assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:i,key})).status,500);for(const table of [...S.staffRecordTables,'idempotency'])assert.equal(x.db.prepare('SELECT count(*) n FROM '+table).get().n,0);x.db.exec('DROP TRIGGER break_staff_audit');assert.equal((await x.request('/api/staff-records',{...m,method:'POST',data:i,key})).status,201);});
test('reading directories, current and old personnel sources adds no facts or customer timeline entries',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record,before=x.db.prepare('SELECT total_changes() n').get().n;for(const path of ['/api/staff-records/employees/professional','/api/staff-records/'+r.id+'?version=1','/api/staff-handover/employees','/api/staff-handover/employees/professional/responsibilities'])assert.equal((await x.request(path,m)).status,200);assert.equal(x.db.prepare('SELECT total_changes() n').get().n,before);const counts=(await x.request('/api/staff-handover/employees/professional/responsibilities',m)).body.personnel_records;assert.equal(counts.qualification.recorded,1);assert.equal(x.db.prepare('SELECT count(*) n FROM task_events').get().n,0);});
test('independent verified backup keeps personnel facts through later employee names, inactivity and actor role changes',async t=>{const x=await fixture(t,{persist:true}),m=await x.login('manager'),r=(await create(x,m)).body.record;await append(x,m,r,{title:'后续来源'});x.db.exec("UPDATE users SET display_name='当前后续员工名称',active=0 WHERE id='professional'; UPDATE users SET role='reception' WHERE id='manager';");verifyStaffRecords(x.db);const b=await createBackup(x.path,join(x.dir,'backups'));assert.equal(b.checks.migrations.length,45);assert.equal(Object.keys(b.checks.counts).length,201);const a=await restoreBackup(b.backup,join(x.dir,'restored')),db=openDatabase(a.database);for(const table of S.staffRecordTables)assert.deepEqual(db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),x.db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all());assert.equal(db.prepare('SELECT count(*) n FROM sessions').get().n,0);verifyStaffRecords(db);db.close();});
test('recovery rejects altered typed data and typed data after native guards are reinstated',async t=>{const x=await fixture(t),m=await x.login('manager');await create(x,m);const triggers=x.db.prepare("SELECT name,sql FROM sqlite_schema WHERE type='trigger' AND tbl_name='staff_record_versions'").all();for(const z of triggers)x.db.exec('DROP TRIGGER '+z.name);x.db.exec("UPDATE staff_record_versions SET data_json='{}'");for(const z of triggers)x.db.exec(z.sql);assert.throws(()=>verifyStaffRecords(x.db),/类型事实/);});
test('nonempty schema44 upgrade preserves every original record and creates no qualification, shift or history',()=>{const dir=mkdtempSync(join(tmpdir(),'optical-staff-upgrade-')),path=join(dir,'old.sqlite');let db=new DatabaseSync(path);try{db.exec('PRAGMA foreign_keys=ON;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,applied_at TEXT NOT NULL)');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')&&x<'045').sort()){db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(file,new Date().toISOString());}db.exec("INSERT INTO stores VALUES('s','原门店'); INSERT INTO users VALUES('m','m','旧员工','dummy','manager','s',1)");const before=snapshot(db);db.close();db=openDatabase(path);assert.deepEqual(snapshot(db),before);for(const table of S.staffRecordTables)assert.equal(db.prepare('SELECT count(*) n FROM '+table).get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM schema_migrations').get().n,45);}finally{db.close();rmSync(dir,{force:true,recursive:true});}});
test('seven separately sourced synthetic stages preserve old accounts and every unrelated ledger and seed once',async t=>{const x=await fixture(t);x.db.exec("INSERT INTO users VALUES('demo-manager','demo-manager','示例负责人','dummy','manager','store-a',1),('demo-front','demo-front','示例前台','dummy','reception','store-a',1),('demo-professional','demo-professional','示例专业人员','dummy','professional','store-a',1)");const before=snapshot(x.db),r=seedDemoStaffRecords(x.db);assert.deepEqual(r,{records:7,versions:8,withdrawals:1});assert.deepEqual(snapshot(x.db),before);const rows=x.db.prepare('SELECT * FROM staff_record_versions ORDER BY rowid').all();S.withdrawStaffRecord(x.db,'demo-staff-record-training-actual',{reason:'后续人工变化',next_step:'保留旧培训事实'},'demo-manager');assert.deepEqual(seedDemoStaffRecords(x.db),{records:0,versions:0,withdrawals:0});assert.deepEqual(x.db.prepare('SELECT * FROM staff_record_versions ORDER BY rowid').all(),rows);verifyStaffRecords(x.db);});
test('same-millisecond personnel versions preserve append order and independent store activity keeps the employee lease',async t=>{const x=await fixture(t),m=await x.login('manager'),i=await intent(x),at=new Date().toISOString(),r=S.createStaffRecord(x.db,'store-a',i,'manager',at),a=S.recordStaffVersion(x.db,r.id,i,'manager',at);S.withdrawStaffRecord(x.db,r.id,{reason:'同刻明确撤回',next_step:'保留原版'},'manager',at);verifyStaffRecords(x.db);assert.equal(a.version,2);const first=await x.request('/api/staff-records/employees/professional?limit=1',m);S.createStaffRecord(x.db,'store-b',{...i,staff_id:'other'},'other',at);const second=await x.request('/api/staff-records/employees/professional?expected_source='+first.body.source_token,m);assert.equal(second.status,200);});
test('native canonical source validation rejects impossible timestamps, inferred qualification fields and forged version reasons',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record,v=x.db.prepare('SELECT * FROM staff_record_versions WHERE root_id=?').get(r.id),e=x.db.prepare('SELECT * FROM staff_record_events WHERE root_id=?').get(r.id),insert=(table,row)=>x.db.prepare('INSERT INTO '+table+'('+Object.keys(row).join(',')+') VALUES('+Object.keys(row).map(()=>'?').join(',')+')').run(...Object.values(row));for(const data of [{...qualification(),identifier:'inferred'},{...qualification(),issued_status:'recorded',issued_date:'2026-02-30'},{...qualification(),unexpected:'extra'}]){x.db.exec('SAVEPOINT native_attempt');try{assert.throws(()=>insert('staff_record_versions',{...v,id:crypto.randomUUID(),version:2,base_sequence:1,event_id:crypto.randomUUID(),data_json:JSON.stringify(data)}),/canonical typed/);}finally{x.db.exec('ROLLBACK TO native_attempt;RELEASE native_attempt');}}x.db.exec('SAVEPOINT native_reason');try{const id=crypto.randomUUID(),event=crypto.randomUUID();insert('staff_record_versions',{...v,id,version:2,base_sequence:1,event_id:event});assert.throws(()=>insert('staff_record_events',{...e,id:event,version_id:id,revision:2,sequence:2,reason:'forged other reason'}),/paired event/);}finally{x.db.exec('ROLLBACK TO native_reason;RELEASE native_reason');}assert.throws(()=>S.createStaffRecord(x.db,'store-a',{...awaitlessIntent(r),kind:'shift',data:{...facts('shift'),starts_at:'2026-02-30T08:00:00.000Z'}},'manager'),/invalid/);verifyStaffRecords(x.db);});
test('recovery rejects a paired record reason edited independently of its fixed source version',async t=>{const x=await fixture(t),m=await x.login('manager');await create(x,m);const trigger=x.db.prepare("SELECT sql FROM sqlite_schema WHERE name='staff_record_events_no_update'").get().sql;x.db.exec('DROP TRIGGER staff_record_events_no_update');x.db.exec("UPDATE staff_record_events SET reason='被错误覆盖的来源依据'");x.db.exec(trigger);assert.throws(()=>verifyStaffRecords(x.db),/原配对/);});
test('deferred native pairs cannot substitute another roots later version or an unrelated withdrawal event',async t=>{const x=await fixture(t),m=await x.login('manager'),r=(await create(x,m)).body.record,a=(await append(x,m,r)).body.record,w=(await withdraw(x,m,a)).body.record,root=x.db.prepare('SELECT * FROM staff_record_roots WHERE id=?').get(r.id),v=x.db.prepare('SELECT * FROM staff_record_versions WHERE id=?').get(w.current.version_id),ev=x.db.prepare("SELECT * FROM staff_record_events WHERE root_id=? AND action='withdraw'").get(r.id),at=new Date().toISOString(),put=(t,r)=>x.db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));assert.throws(()=>put('staff_record_roots',{...root,id:crypto.randomUUID(),serial:2,record_number:'SR-'+at.slice(0,10).replaceAll('-','')+'-00002',first_version_id:v.id,created_at:at}),/FOREIGN KEY/);assert.throws(()=>put('staff_record_versions',{...v,id:crypto.randomUUID(),version:3,base_sequence:3,event_id:ev.id,created_at:at}),/FOREIGN KEY/);assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_roots').get().n,1);assert.equal(x.db.prepare('SELECT count(*) n FROM staff_record_versions').get().n,2);verifyStaffRecords(x.db);});
