import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {request as httpRequest} from 'node:http';
import {mkdtempSync,rmSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../src/server.mjs';
import {hashPassword,openDatabase} from '../src/db.mjs';
import {createBackup,restoreBackup} from '../src/recovery.mjs';


async function fixture(t,{persist=false}={}){
 const dir=mkdtempSync(join(tmpdir(),'optical-stock-')),path=persist?join(dir,'source.sqlite'):':memory:',{server,db}=createApp({databasePath:path,mode:'test',logger:()=>{}});db.exec("INSERT INTO stores VALUES ('store-a','A'),('store-b','B')");for(const [id,role,store] of [['manager','manager','store-a'],['front','reception','store-a'],['professional','professional','store-a'],['other','manager','store-b'],['parent','guardian',null]])db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,store);for(const [id,store] of [['one','store-a'],['two','store-a'],['other-child','store-b']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,store,id,null,null,null,new Date().toISOString(),store==='store-a'?'manager':'other');db.prepare('INSERT INTO guardian_links (user_id,customer_id,active) VALUES (?,?,1)').run('parent','one');server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 const request=async(path,{cookie,csrf,method='GET',data,key=crypto.randomUUID(),headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(method!=='GET'?{'Idempotency-Key':key}:{}),...(data?{'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const login=async id=>{const r=await request('/api/auth/login',{method:'POST',data:{username:id,password:'synthetic-only-password'}});assert.equal(r.status,200);const me=await request('/api/me',{cookie:r.cookie});return {cookie:r.cookie,csrf:me.body.csrf};};return {db,request,login,origin,path,dir};
}

import {seedDemoBatches} from '../src/demo-inventory-batches.mjs';
import {verifyBatches} from '../src/inventory-batch-recovery.mjs';
import * as R from '../src/purchase-receiving.mjs';
import {seedDemoCustody} from '../src/demo-inventory-custody.mjs';
import {verifyCustody} from '../src/inventory-custody-recovery.mjs';
import {seedDemoExtraReturns} from '../src/demo-purchase-extra-returns.mjs';
import {verifyExtraReturns} from '../src/purchase-extra-return-recovery.mjs';
import {seedDemoSupplierReturns} from '../src/demo-supplier-returns.mjs';
import {verifySupplierReturns} from '../src/supplier-return-recovery.mjs';
import {seedDemoPurchaseQuality} from '../src/demo-purchase-quality.mjs';
import {verifyPurchaseQuality} from '../src/purchase-quality-recovery.mjs';
import {seedDemoReceiving} from '../src/demo-purchase-receiving.mjs';
import {verifyReceiving} from '../src/purchase-receiving-recovery.mjs';
import {seedDemoProcurement} from '../src/demo-procurement.mjs';
import {seedDemoSpecialtyReviews} from '../src/demo-specialty-review.mjs';
import {seedDemoSpecialtyCare} from '../src/demo-specialty-care.mjs';
import {seedDemoSpecialtyTrace} from '../src/demo-specialty-trace.mjs';
import {seedDemoSpecialty} from '../src/demo-specialty.mjs';
import {seedDemoReferrals} from '../src/demo-referrals.mjs';
import {seedDemoContact} from '../src/demo-contact.mjs';
import {seedDemoLongitudinal} from '../src/demo-longitudinal.mjs';
import {seedDemoFamilyTraining} from '../src/demo-family-training.mjs';
import {seedDemoScheduling} from '../src/demo-scheduling.mjs';
import {seedDemoEntitlements} from '../src/demo-entitlements.mjs';
import {seedDemoScenarios,seedDemoRetail,seedDemoInventory,seedDemoPayments,seedDemoProcessing,seedDemoFulfillment,seedDemoAftercare,seedDemoAftercareWork,seedDemoReplacements,seedDemoDispositions,seedDemoRefunds,seedDemoParameters,seedDemoTraining} from '../src/demo-data.mjs';
import {employeeDirectory,employeeResponsibilities,responsibilityKinds,responsibilitySnapshot} from '../src/staff-handover.mjs';
import {seedDemoStaffHandover} from '../src/demo-staff-handover.mjs';
import {transaction} from '../src/db.mjs';
async function setup(t,{persist=false,seed=true}={}){const x=await fixture(t,{persist});Object.assign(x,{m:await x.login('manager'),f:await x.login('front'),p:await x.login('professional'),g:await x.login('parent'),o:await x.login('other')});if(seed){for(const[id,role]of [['demo-manager','manager'],['demo-front','reception'],['demo-professional','professional'],['demo-parent','guardian']])x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run(id,id,id,hashPassword('synthetic-only-password'),role,role==='guardian'?null:'store-a');seedDemoScenarios(x.db);seedDemoRetail(x.db);seedDemoInventory(x.db);seedDemoPayments(x.db);seedDemoProcessing(x.db);seedDemoFulfillment(x.db);seedDemoAftercare(x.db);seedDemoAftercareWork(x.db);seedDemoReplacements(x.db);seedDemoDispositions(x.db);seedDemoRefunds(x.db);seedDemoParameters(x.db);seedDemoTraining(x.db);seedDemoEntitlements(x.db);seedDemoScheduling(x.db);x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('demo-practice-parent','demo-practice-parent','家庭练习家长（虚构）',hashPassword('synthetic-only-password'),'guardian',null);seedDemoFamilyTraining(x.db);seedDemoLongitudinal(x.db);seedDemoContact(x.db);seedDemoReferrals(x.db);seedDemoSpecialty(x.db);seedDemoSpecialtyTrace(x.db);seedDemoSpecialtyCare(x.db);seedDemoSpecialtyReviews(x.db);seedDemoStaffHandover(x.db);}return x;}
const path='/api/staff-handover/employees',duties=id=>path+'/'+id+'/responsibilities',good=(z,status=200)=>assert.equal(z.status,status,JSON.stringify(z.body));
const snapshot=db=>Object.fromEntries(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(x=>[x.name,db.prepare('SELECT * FROM '+x.name+' ORDER BY rowid').all()]));
async function newTask(x,{owner='front',title='明确原客户资料核对',role=null}={}){const z=await x.request('/api/customers/one/tasks',{...x.m,method:'POST',data:{title,instructions:'仅原客户通用资料核对',assignee_id:owner,...(role?{candidate_role:role}:{}),cycle_id:null,cycle_version:null,visit_id:null,reason:'实际明确原任务'}});good(z,201);return z.body.task||z.body;}
test('manager-only cross-business employee handover remains store-scoped and excludes guardian accounts',async t=>{const x=await setup(t);good(await x.request(path,x.m));for(const who of [x.f,x.p,x.g])assert.equal((await x.request(path,who)).status,403);assert.equal((await x.request(duties('demo-professional'),x.o)).status,404);const z=await x.request(path,x.m);assert.ok(z.body.items.every(u=>u.store_id==='store-a'&&u.role!=='guardian'));});
test('saved cross-business responsibilities preserve original customer, versions, line references and full kind counts without returning clinical or financial bodies',async t=>{const x=await setup(t),z=await x.request(duties('demo-professional')+'?limit=100',x.m);good(z);assert.equal(z.body.counts.task,4);assert.ok(z.body.items.some(r=>r.kind==='processing'&&r.position>0));assert.ok(z.body.items.some(r=>r.kind==='training_plan'));assert.ok(z.body.items.some(r=>r.kind==='specialty'));assert.ok(z.body.items.every(r=>r.store_id==='store-a'&&r.customer_id&&r.revision>0));for(const r of z.body.items)for(const k of ['assessment_note','opinion_note','password_hash','address','source_json','manifest_json','unit_price_cents'])assert.equal(r[k],undefined);assert.equal(z.body.kinds.length,13);assert.equal(Object.values(z.body.counts).reduce((a,b)=>a+b,0),z.body.total);});
test('employee directory counts responsibility items and distinct customers rather than adding duplicate customers or candidate tasks',async t=>{const x=await setup(t),directory=employeeDirectory(x.db,'store-a',{limit:100}),d=employeeResponsibilities(x.db,'store-a','demo-professional',{limit:100}),u=directory.items.find(u=>u.id==='demo-professional');assert.equal(u.responsibility_count,d.total);assert.equal(u.customer_count,new Set(d.items.map(i=>i.customer_id)).size);assert.ok(d.candidate_task_count>=1);assert.ok(d.items.every(r=>r.owner_id==='demo-professional'));assert.ok(directory.unassigned_candidate_tasks>=1);});
test('stopped employee retains saved responsibility while reset-password and local role are separately visible and do not claim qualification',async t=>{const x=await setup(t),id='demo-staff-handover-inactive',z=await x.request(duties(id),x.m);good(z);assert.equal(z.body.employee.active,0);assert.equal(z.body.total,1);assert.equal(z.body.items[0].professional_qualification_status,'not_verified');x.db.prepare('INSERT INTO user_security VALUES(?,2,1)').run('front');const reset=await x.request(duties('front'),x.m);good(reset);assert.equal(reset.body.employee.must_change_password,1);const assignees=await x.request('/api/tasks/assignees',x.m);assert.ok(!assignees.body.items.some(u=>u.id==='front'||u.id===id));});
test('handover overview does not manufacture new events or mutate accounts, responsibilities, stock or funds',async t=>{const x=await setup(t),before=snapshot(x.db);for(const p of [path,duties('demo-professional'),duties('demo-front')])good(await x.request(p,x.m));assert.deepEqual(snapshot(x.db),before);});
test('employee search is literal and full totals remain accurate beyond a hundred employees',async t=>{const x=await setup(t,{seed:false}),hash=x.db.prepare("SELECT password_hash FROM users WHERE id='front'").get().password_hash;for(let i=0;i<115;i++)x.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,1)').run('large-'+i,'large-'+i,'人员_'+i+'%组',hash,'reception','store-a');const z=await x.request(path+'?q='+encodeURIComponent('人员_')+'&limit=100',x.m);good(z);assert.equal(z.body.total,115);assert.equal(z.body.items.length,100);assert.equal(z.body.next_offset,100);const next=await x.request(path+'?q='+encodeURIComponent('人员_')+'&limit=100&offset=100&expected_source='+z.body.source_token,x.m);good(next);assert.equal(next.body.items.length,15);assert.equal((await x.request(path+'?q='+encodeURIComponent('%组'),x.m)).body.total,115);assert.equal((await x.request(path+'?q='+encodeURIComponent('人员%'),x.m)).body.total,0);});
test('responsibility paging retains complete current items and source leases beyond one hundred original tasks',async t=>{const x=await setup(t,{seed:false});for(let i=0;i<105;i++)await newTask(x,{title:'批次原任务 '+i});const first=await x.request(duties('front')+'?limit=100',x.m);good(first);assert.equal(first.body.total,105);assert.equal(first.body.items.length,100);assert.equal((await x.request(duties('front')+'?limit=100&offset=100',x.m)).status,409);const last=await x.request(duties('front')+'?limit=100&offset=100&expected_source='+first.body.source_token,x.m);good(last);assert.equal(last.body.items.length,5);assert.equal(new Set([...first.body.items,...last.body.items].map(r=>r.key)).size,105);});
test('explicit original task transfer moves actual employee responsibility to awaiting acceptance and pauses running work without advancing any other business',async t=>{const x=await setup(t),id='demo-staff-handover-running',old=await x.request(duties('demo-professional'),x.m),row=x.db.prepare('SELECT * FROM work_tasks WHERE id=?').get(id),beforeStock=x.db.prepare('SELECT * FROM inventory_events').all(),z=await x.request('/api/tasks/'+id+'/transfer',{...x.m,method:'POST',data:{expected_revision:row.revision,assignee_id:'front',reason:'明确原员工交接'}});good(z);const after=x.db.prepare('SELECT * FROM work_tasks WHERE id=?').get(id);assert.equal(after.assignee_id,'front');assert.equal(after.assignment_status,'awaiting');assert.equal(after.execution_status,'paused');assert.equal((await x.request(duties('demo-professional')+'?offset=1&expected_source='+old.body.source_token,x.m)).status,409);assert.ok((await x.request(duties('front'),x.m)).body.items.some(r=>r.id===id));assert.ok(!(await x.request(duties('demo-professional'),x.m)).body.items.some(r=>r.id===id));assert.deepEqual(x.db.prepare('SELECT * FROM inventory_events').all(),beforeStock);const timeline=await x.request('/api/customers/sample-retail/timeline?kind=task',x.m);assert.equal(timeline.status,200);});
test('blocked original task remains blocked after employee transfer and does not become active execution',async t=>{const x=await setup(t),id='demo-staff-handover-blocked',row=x.db.prepare('SELECT * FROM work_tasks WHERE id=?').get(id);good(await x.request('/api/tasks/'+id+'/transfer',{...x.m,method:'POST',data:{expected_revision:row.revision,assignee_id:'front',reason:'明确阻塞原因随原任务交接'}}));const next=x.db.prepare('SELECT * FROM work_tasks WHERE id=?').get(id);assert.equal(next.lifecycle_status,'blocked');assert.equal(next.exception_reason,row.exception_reason);assert.equal(next.execution_status,'paused');});
test('source leases reject employee deactivation and original customer name changes without mixing a continuation page',async t=>{const x=await setup(t),old=await x.request(duties('demo-professional'),x.m);x.db.prepare("UPDATE users SET active=0 WHERE id='demo-professional'").run();assert.equal((await x.request(duties('demo-professional')+'?offset=1&expected_source='+old.body.source_token,x.m)).status,409);const changed=(await x.request(duties('demo-professional'),x.m)).body;x.db.prepare("UPDATE customers SET name='后来更正姓名' WHERE id='sample-retail'").run();assert.equal((await x.request(duties('demo-professional')+'?offset=1&expected_source='+changed.source_token,x.m)).status,409);});
test('source leases reject current plan or followup responsibility change rather than substituting later owner',async t=>{const x=await setup(t),old=(await x.request(duties('demo-professional'),x.m)).body;const id='demo-staff-handover-pending',r=x.db.prepare('SELECT * FROM work_tasks WHERE id=?').get(id);good(await x.request('/api/tasks/'+id+'/transfer',{...x.m,method:'POST',data:{expected_revision:r.revision,assignee_id:'front',reason:'实际转交原任务'}}));assert.equal((await x.request(path+'?offset=1&expected_source='+old.source_token,x.m)).status,409);});
test('filters use explicit kind, role, account and responsibility status while malformed and unknown options are refused',async t=>{const x=await setup(t);const z=await x.request(path+'?active=inactive&duties=yes&role=professional',x.m);good(z);assert.equal(z.body.total,1);const task=await x.request(duties('demo-professional')+'?kind=task',x.m);good(task);assert.equal(task.body.total,4);for(const q of ['limit=0','limit=101','offset=-1','active=paused','role=guardian','duties=maybe','automatic_transfer=true'])assert.equal((await x.request(path+'?'+q,x.m)).status,422);assert.equal((await x.request(duties('demo-professional')+'?kind=finance',x.m)).status,422);assert.equal((await x.request(path,{...x.m,method:'POST',data:{}})).status,405);});
test('explicit dates remain absent when not recorded and never manufacture overdue tasks from an unknown date',async t=>{const x=await setup(t),z=employeeResponsibilities(x.db,'store-a','demo-professional',{limit:100});for(const r of z.items){if(r.due===null)assert.equal(r.deadline_status,'not_recorded');else assert.ok(['recorded','past_date'].includes(r.deadline_status));}});
test('seven separately sourced task handover stages preserve original rows and accounts, repeat exactly and recover independently',async t=>{const x=await setup(t,{persist:true}),before=snapshot(x.db);assert.deepEqual(seedDemoStaffHandover(x.db),{employees:0,tasks:0,events:0});assert.deepEqual(snapshot(x.db),before);const b=await createBackup(x.path,join(x.dir,'backup')),z=await restoreBackup(b.backup,join(x.dir,'restored')),db=openDatabase(z.database);t.after(()=>db.close());assert.deepEqual(employeeResponsibilities(db,'store-a','demo-professional',{limit:100}).items,employeeResponsibilities(x.db,'store-a','demo-professional',{limit:100}).items);assert.equal(db.prepare('SELECT count(*) n FROM sessions').get().n,0);});
test('another store task activity cannot change this stores responsibility source lease',async t=>{const x=await setup(t,{seed:false}),before=responsibilitySnapshot(x.db,'store-a').source_token,z=await x.request('/api/customers/other-child/tasks',{...x.o,method:'POST',data:{title:'另一门店原任务',instructions:'仅另一门店',assignee_id:'other',cycle_id:null,cycle_version:null,visit_id:null,reason:'明确另一门店来源'}});good(z,201);assert.equal(responsibilitySnapshot(x.db,'store-a').source_token,before);const next=await x.request(path+'?offset=1&expected_source='+before,x.m);good(next);});
test('cancelled work stays in original history but is excluded from current employee duties',async t=>{const x=await setup(t),id='demo-staff-handover-pending',old=x.db.prepare('SELECT * FROM work_tasks WHERE id=?').get(id);good(await x.request('/api/tasks/'+id+'/cancel',{...x.m,method:'POST',data:{expected_revision:old.revision,reason:'明确原任务无需继续'}}));const dutiesNow=employeeResponsibilities(x.db,'store-a','demo-professional',{limit:100});assert.ok(!dutiesNow.items.some(r=>r.id===id));assert.ok(x.db.prepare("SELECT 1 FROM task_events WHERE task_id=? AND action='cancel'").get(id));});
