CREATE TABLE processing_jobs (
 id TEXT PRIMARY KEY, order_id TEXT NOT NULL, order_version INTEGER NOT NULL, customer_id TEXT NOT NULL, store_id TEXT NOT NULL,
 serial INTEGER NOT NULL CHECK(typeof(serial)='integer' AND serial>=1), created_at TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(order_id,serial), FOREIGN KEY(order_id,order_version,customer_id,store_id) REFERENCES retail_order_versions(order_id,version,customer_id,store_id)
);
CREATE TABLE processing_events (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES processing_jobs(id), revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),
 action TEXT NOT NULL CHECK(action IN('create','plan','receive','start','complete','delay','clear_delay','cancel')), position INTEGER, quantity INTEGER,
 snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)), reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300), created_at TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(job_id,revision), CHECK((action IN('create','cancel') AND position IS NULL AND quantity IS NULL) OR (action IN('plan','delay','clear_delay') AND typeof(position)='integer' AND position>=1 AND quantity IS NULL) OR (action IN('receive','start','complete') AND typeof(position)='integer' AND position>=1 AND typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999))
);
CREATE INDEX processing_store_jobs ON processing_jobs(store_id,created_at,id);
CREATE INDEX processing_customer_jobs ON processing_jobs(customer_id,created_at,id);
CREATE TRIGGER processing_job_ready BEFORE INSERT ON processing_jobs BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception') AND u.active=1 AND COALESCE(s.must_change_password,0)=0) THEN RAISE(ABORT,'processing creation actor not allowed') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM retail_order_versions v WHERE v.order_id=NEW.order_id AND v.version=NEW.order_version AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=NEW.order_id) AND v.status='draft' AND NEW.created_at>=v.created_at) THEN RAISE(ABORT,'processing original order invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM retail_order_items i JOIN retail_product_versions p ON p.product_id=i.product_id AND p.version=i.product_version WHERE i.order_id=NEW.order_id AND i.version=NEW.order_version AND p.category<>'service') THEN RAISE(ABORT,'processing requires physical items') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM processing_jobs j WHERE j.order_id=NEW.order_id AND (SELECT action FROM processing_events WHERE job_id=j.id ORDER BY revision DESC LIMIT 1) IS NOT 'cancel') THEN RAISE(ABORT,'processing order already has active job') END;
 SELECT CASE WHEN NEW.serial<>COALESCE((SELECT max(serial)+1 FROM processing_jobs WHERE order_id=NEW.order_id),1) THEN RAISE(ABORT,'processing serial invalid') END;
END;
CREATE TRIGGER processing_event_ready BEFORE INSERT ON processing_events BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM processing_jobs j JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE j.id=NEW.job_id AND u.store_id=j.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND NEW.created_at>=j.created_at) THEN RAISE(ABORT,'processing actor not allowed') END;
 SELECT CASE WHEN NEW.revision<>COALESCE((SELECT max(revision)+1 FROM processing_events WHERE job_id=NEW.job_id),1) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM processing_events WHERE job_id=NEW.job_id),'') OR (NEW.revision=1 AND NEW.action<>'create') OR (NEW.revision>1 AND NEW.action='create') THEN RAISE(ABORT,'processing revision invalid') END;
 SELECT CASE WHEN NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM processing_jobs j WHERE j.id=NEW.job_id AND j.created_by=NEW.created_by AND j.created_at=NEW.created_at) THEN RAISE(ABORT,'processing first event invalid') END;
 SELECT CASE WHEN NEW.revision>1 AND (SELECT action FROM processing_events WHERE job_id=NEW.job_id ORDER BY revision DESC LIMIT 1)='cancel' THEN RAISE(ABORT,'processing cancelled job immutable') END;
 SELECT CASE WHEN NEW.revision>1 AND NOT EXISTS(SELECT 1 FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.completed')<json_extract(l.value,'$.quantity')) THEN RAISE(ABORT,'processing awaits quality review') END;
 SELECT CASE WHEN NEW.action IN('create','plan','receive') AND (SELECT role FROM users WHERE id=NEW.created_by) NOT IN('manager','reception') OR NEW.action='cancel' AND (SELECT role FROM users WHERE id=NEW.created_by)<>'manager' THEN RAISE(ABORT,'processing action actor not allowed') END;
 SELECT CASE WHEN NEW.action IN('start','complete','delay','clear_delay') AND (SELECT role FROM users WHERE id=NEW.created_by)<>'manager' AND NOT (NEW.action IN('delay','clear_delay') AND (SELECT role FROM users WHERE id=NEW.created_by)='reception') AND NOT EXISTS(SELECT 1 FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position AND json_extract(l.value,'$.assignee_id')=NEW.created_by) THEN RAISE(ABORT,'processing current assignee required') END;
 SELECT CASE WHEN json_type(NEW.snapshot_json) IS NOT 'array' OR json_array_length(NEW.snapshot_json) NOT BETWEEN 1 AND 30 OR json_array_length(NEW.snapshot_json)<>(SELECT count(*) FROM processing_jobs j JOIN retail_order_items i ON i.order_id=j.order_id AND i.version=j.order_version JOIN retail_product_versions p ON p.product_id=i.product_id AND p.version=i.product_version WHERE j.id=NEW.job_id AND p.category<>'service') OR (SELECT count(DISTINCT json_extract(value,'$.position')) FROM json_each(NEW.snapshot_json))<>json_array_length(NEW.snapshot_json) THEN RAISE(ABORT,'processing original line set invalid') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM json_each(NEW.snapshot_json) l WHERE json_type(l.value) IS NOT 'object' OR (SELECT count(*) FROM json_each(l.value))<>14 OR NOT EXISTS(SELECT 1 FROM processing_jobs j JOIN retail_order_items i ON i.order_id=j.order_id AND i.version=j.order_version JOIN retail_product_versions p ON p.product_id=i.product_id AND p.version=i.product_version WHERE j.id=NEW.job_id AND p.category<>'service' AND json_extract(l.value,'$.position')=i.position AND json_extract(l.value,'$.product_id')=i.product_id AND json_extract(l.value,'$.product_version')=i.product_version AND json_extract(l.value,'$.quantity')=i.quantity)) THEN RAISE(ABORT,'processing line is not original item') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM json_each(NEW.snapshot_json) l WHERE json_type(l.value,'$.position') IS NOT 'integer' OR json_type(l.value,'$.product_id') IS NOT 'text' OR json_type(l.value,'$.product_version') IS NOT 'integer' OR json_type(l.value,'$.quantity') IS NOT 'integer' OR json_type(l.value,'$.supply_mode') IS NOT 'text' OR json_type(l.value,'$.processing_mode') IS NOT 'text' OR json_type(l.value,'$.received') IS NOT 'integer' OR json_type(l.value,'$.started') IS NOT 'integer' OR json_type(l.value,'$.completed') IS NOT 'integer' OR json_extract(l.value,'$.completed')<0 OR json_extract(l.value,'$.completed')>json_extract(l.value,'$.started') OR json_extract(l.value,'$.started')>json_extract(l.value,'$.received') OR json_extract(l.value,'$.received')>json_extract(l.value,'$.quantity') OR json_extract(l.value,'$.supply_mode') NOT IN('stock','purchase') OR json_extract(l.value,'$.processing_mode') NOT IN('internal','external','none') OR json_type(l.value,'$.instructions') IS NOT 'text' OR length(json_extract(l.value,'$.instructions'))>1000 OR json_type(l.value,'$.assignee_id') IS NOT 'text' OR NOT EXISTS(SELECT 1 FROM users u JOIN processing_jobs j ON j.id=NEW.job_id WHERE u.id=json_extract(l.value,'$.assignee_id') AND u.store_id=j.store_id) OR json_type(l.value,'$.supplier_name') NOT IN('null','text') OR length(json_extract(l.value,'$.supplier_name'))>120 OR ((json_extract(l.value,'$.supply_mode')='purchase' OR json_extract(l.value,'$.processing_mode')='external') AND COALESCE(length(trim(json_extract(l.value,'$.supplier_name'))),0)=0) OR json_type(l.value,'$.delay_reason') NOT IN('null','text') OR json_type(l.value,'$.delay_reason')='text' AND length(trim(json_extract(l.value,'$.delay_reason'))) NOT BETWEEN 1 AND 300 OR json_type(l.value,'$.due_date') NOT IN('null','text') OR json_type(l.value,'$.due_date')='text' AND (length(json_extract(l.value,'$.due_date'))<>10 OR json_extract(l.value,'$.due_date')<'2000-01-01' OR json_extract(l.value,'$.due_date')>'2099-12-31' OR date(json_extract(l.value,'$.due_date')) IS NOT json_extract(l.value,'$.due_date'))) THEN RAISE(ABORT,'processing plan or quantities invalid') END;
 SELECT CASE WHEN NEW.action='create' AND EXISTS(SELECT 1 FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.received')<>0 OR json_extract(l.value,'$.started')<>0 OR json_extract(l.value,'$.completed')<>0 OR json_type(l.value,'$.delay_reason') IS NOT 'null') THEN RAISE(ABORT,'processing initial counts invalid') END;
 SELECT CASE WHEN NEW.action IN('create','plan') AND EXISTS(SELECT 1 FROM json_each(NEW.snapshot_json) l WHERE (NEW.action='create' OR json_extract(l.value,'$.position')=NEW.position) AND NOT EXISTS(SELECT 1 FROM users u JOIN processing_jobs j ON j.id=NEW.job_id WHERE u.id=json_extract(l.value,'$.assignee_id') AND u.store_id=j.store_id AND u.role IN('manager','reception','professional') AND u.active=1)) THEN RAISE(ABORT,'processing assignee unavailable') END;
 SELECT CASE WHEN NEW.position IS NOT NULL AND NOT EXISTS(SELECT 1 FROM json_each(NEW.snapshot_json) WHERE json_extract(value,'$.position')=NEW.position) THEN RAISE(ABORT,'processing target line missing') END;
 SELECT CASE WHEN NEW.position IS NOT NULL AND EXISTS(SELECT 1 FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position AND json_extract(l.value,'$.completed')=json_extract(l.value,'$.quantity')) THEN RAISE(ABORT,'processing finished line immutable') END;
 SELECT CASE WHEN NEW.action='receive' AND NEW.snapshot_json IS NOT json_set((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].received',(SELECT json_extract(l.value,'$.received') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)+NEW.quantity) THEN RAISE(ABORT,'processing quantity transition invalid') END;
 SELECT CASE WHEN NEW.action='start' AND NEW.snapshot_json IS NOT json_set((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].started',(SELECT json_extract(l.value,'$.started') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)+NEW.quantity) THEN RAISE(ABORT,'processing quantity transition invalid') END;
 SELECT CASE WHEN NEW.action='complete' AND NEW.snapshot_json IS NOT json_set((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].completed',(SELECT json_extract(l.value,'$.completed') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)+NEW.quantity) THEN RAISE(ABORT,'processing quantity transition invalid') END;
 SELECT CASE WHEN NEW.action='plan' AND (NEW.snapshot_json IS NOT json_set((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].supply_mode',(SELECT json_extract(l.value,'$.supply_mode') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].processing_mode',(SELECT json_extract(l.value,'$.processing_mode') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].supplier_name',(SELECT json_extract(l.value,'$.supplier_name') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].assignee_id',(SELECT json_extract(l.value,'$.assignee_id') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].due_date',(SELECT json_extract(l.value,'$.due_date') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].instructions',(SELECT json_extract(l.value,'$.instructions') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position)) OR NEW.snapshot_json=(SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1)) THEN RAISE(ABORT,'processing plan transition invalid') END;
 SELECT CASE WHEN NEW.action='plan' AND (SELECT json_extract(l.value,'$.received') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)>0 AND ((SELECT json_extract(l.value,'$.supply_mode') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position) IS NOT (SELECT json_extract(l.value,'$.supply_mode') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position) OR (SELECT json_extract(l.value,'$.supplier_name') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position) IS NOT (SELECT json_extract(l.value,'$.supplier_name') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)) THEN RAISE(ABORT,'processing executed plan locked') END;
 SELECT CASE WHEN NEW.action='plan' AND (SELECT json_extract(l.value,'$.started') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)>0 AND ((SELECT json_extract(l.value,'$.processing_mode') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position) IS NOT (SELECT json_extract(l.value,'$.processing_mode') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position) OR (SELECT json_extract(l.value,'$.instructions') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position) IS NOT (SELECT json_extract(l.value,'$.instructions') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)) THEN RAISE(ABORT,'processing executed plan locked') END;
 SELECT CASE WHEN NEW.action='delay' AND NEW.snapshot_json IS NOT json_set((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].delay_reason',NEW.reason,'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].due_date',(SELECT json_extract(l.value,'$.due_date') FROM json_each(NEW.snapshot_json) l WHERE json_extract(l.value,'$.position')=NEW.position)) THEN RAISE(ABORT,'processing delay transition invalid') END;
 SELECT CASE WHEN NEW.action='clear_delay' AND ((SELECT json_extract(l.value,'$.delay_reason') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position) IS NULL OR NEW.snapshot_json IS NOT json_set((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1),'$['||(SELECT l.key FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)||'].delay_reason',NULL)) THEN RAISE(ABORT,'processing delay clear invalid') END;
 SELECT CASE WHEN NEW.action='cancel' AND (NEW.snapshot_json IS NOT (SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1) OR EXISTS(SELECT 1 FROM json_each((SELECT snapshot_json FROM processing_events WHERE job_id=NEW.job_id AND revision=NEW.revision-1)) l WHERE json_extract(l.value,'$.received')>0)) THEN RAISE(ABORT,'processing cancellation requires untouched plan') END;
 SELECT CASE WHEN NEW.action='receive' AND (SELECT json_extract(l.value,'$.supply_mode') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.revision-1 AND json_extract(l.value,'$.position')=NEW.position)='stock' AND NOT EXISTS(SELECT 1 FROM processing_jobs j JOIN inventory_order_events e ON e.order_id=j.order_id AND e.order_version=j.order_version WHERE j.id=NEW.job_id AND e.action='reserve' AND e.revision=(SELECT max(revision) FROM inventory_order_events WHERE order_id=j.order_id)) THEN RAISE(ABORT,'processing stock preparation requires reservation') END;
END;
CREATE TRIGGER processing_order_lock BEFORE INSERT ON retail_order_versions WHEN EXISTS(SELECT 1 FROM processing_jobs j WHERE j.order_id=NEW.order_id AND (SELECT action FROM processing_events WHERE job_id=j.id ORDER BY revision DESC LIMIT 1) IS NOT 'cancel') BEGIN SELECT RAISE(ABORT,'active processing job locks original order'); END;
CREATE TRIGGER processing_stock_lock BEFORE INSERT ON inventory_order_events WHEN NEW.action='release' AND EXISTS(SELECT 1 FROM processing_jobs j JOIN processing_events e ON e.job_id=j.id AND e.revision=(SELECT max(revision) FROM processing_events WHERE job_id=j.id),json_each(e.snapshot_json) l WHERE j.order_id=NEW.order_id AND e.action<>'cancel' AND json_extract(l.value,'$.supply_mode')='stock' AND json_extract(l.value,'$.received')>0) BEGIN SELECT RAISE(ABORT,'processing stock already prepared'); END;
CREATE TRIGGER processing_jobs_no_update BEFORE UPDATE ON processing_jobs BEGIN SELECT RAISE(ABORT,'processing identity immutable'); END;
CREATE TRIGGER processing_jobs_no_delete BEFORE DELETE ON processing_jobs BEGIN SELECT RAISE(ABORT,'processing identity immutable'); END;
CREATE TRIGGER processing_events_no_update BEFORE UPDATE ON processing_events BEGIN SELECT RAISE(ABORT,'processing history immutable'); END;
CREATE TRIGGER processing_events_no_delete BEFORE DELETE ON processing_events BEGIN SELECT RAISE(ABORT,'processing history immutable'); END;
