CREATE TABLE fulfillment_events (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES processing_jobs(id), revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),
 processing_revision INTEGER NOT NULL, position INTEGER NOT NULL CHECK(typeof(position)='integer' AND position BETWEEN 1 AND 30),
 action TEXT NOT NULL CHECK(action IN('check_pass','check_fail','rework_assign','rework_start','rework_complete','deliver')),
 quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999), source_id TEXT REFERENCES fulfillment_events(id),
 assignee_id TEXT REFERENCES users(id), instructions TEXT, checks_json TEXT NOT NULL CHECK(json_valid(checks_json)),
 receiver_name TEXT, receipt_note TEXT, handed_at TEXT,
 reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300), created_at TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(job_id,revision), FOREIGN KEY(job_id,processing_revision) REFERENCES processing_events(job_id,revision),
 CHECK((action IN('check_pass','check_fail')) OR source_id IS NOT NULL),
 CHECK((action='rework_assign' AND assignee_id IS NOT NULL AND length(trim(instructions)) BETWEEN 1 AND 1000) OR (action<>'rework_assign' AND assignee_id IS NULL AND instructions IS NULL)),
 CHECK((action='deliver' AND length(trim(receiver_name)) BETWEEN 1 AND 120 AND length(trim(receipt_note)) BETWEEN 1 AND 1000 AND handed_at IS NOT NULL) OR (action<>'deliver' AND receiver_name IS NULL AND receipt_note IS NULL AND handed_at IS NULL))
);
CREATE INDEX fulfillment_store_source ON fulfillment_events(job_id,revision);
CREATE INDEX fulfillment_source ON fulfillment_events(source_id);
CREATE TRIGGER fulfillment_event_ready BEFORE INSERT ON fulfillment_events BEGIN
 SELECT CASE WHEN NEW.revision<>COALESCE((SELECT max(revision)+1 FROM fulfillment_events WHERE job_id=NEW.job_id),1) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM fulfillment_events WHERE job_id=NEW.job_id),'') THEN RAISE(ABORT,'fulfillment revision invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM processing_jobs j JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE j.id=NEW.job_id AND u.store_id=j.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='professional' AND NEW.action IN('check_pass','check_fail','rework_start','rework_complete') OR u.role='reception' AND NEW.action IN('rework_assign','rework_start','rework_complete','deliver'))) THEN RAISE(ABORT,'fulfillment actor not allowed') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.processing_revision AND p.revision=(SELECT max(revision) FROM processing_events WHERE job_id=NEW.job_id) AND p.action<>'cancel' AND p.created_at<=NEW.created_at AND json_extract(l.value,'$.position')=NEW.position AND json_extract(l.value,'$.completed')>0) THEN RAISE(ABORT,'fulfillment processing source invalid') END;
 SELECT CASE WHEN NEW.source_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM fulfillment_events e WHERE e.id=NEW.source_id AND e.job_id=NEW.job_id AND e.position=NEW.position AND e.revision<NEW.revision AND e.created_at<=NEW.created_at AND e.action=CASE NEW.action WHEN 'check_pass' THEN 'rework_complete' WHEN 'check_fail' THEN 'rework_complete' WHEN 'rework_assign' THEN 'check_fail' WHEN 'rework_start' THEN 'rework_assign' WHEN 'rework_complete' THEN 'rework_start' WHEN 'deliver' THEN 'check_pass' END) THEN RAISE(ABORT,'fulfillment parent source invalid') END;
 SELECT CASE WHEN NEW.source_id IS NOT NULL AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM fulfillment_events WHERE source_id=NEW.source_id),0)>(SELECT quantity FROM fulfillment_events WHERE id=NEW.source_id) THEN RAISE(ABORT,'fulfillment source quantity exceeded') END;
 SELECT CASE WHEN NEW.source_id IS NULL AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM fulfillment_events WHERE job_id=NEW.job_id AND position=NEW.position AND source_id IS NULL),0)>(SELECT json_extract(l.value,'$.completed') FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.processing_revision AND json_extract(l.value,'$.position')=NEW.position) THEN RAISE(ABORT,'fulfillment initial quantity exceeded') END;
 SELECT CASE WHEN NEW.action='rework_assign' AND NOT EXISTS(SELECT 1 FROM users u JOIN processing_jobs j ON j.id=NEW.job_id WHERE u.id=NEW.assignee_id AND u.active=1 AND u.store_id=j.store_id AND u.role IN('manager','reception','professional')) THEN RAISE(ABORT,'fulfillment assignee unavailable') END;
 SELECT CASE WHEN NEW.action IN('rework_start','rework_complete') AND (SELECT role FROM users WHERE id=NEW.created_by)<>'manager' AND NEW.created_by IS NOT (SELECT a.assignee_id FROM fulfillment_events s JOIN fulfillment_events a ON a.id=CASE WHEN NEW.action='rework_start' THEN s.id ELSE s.source_id END WHERE s.id=NEW.source_id) THEN RAISE(ABORT,'fulfillment assigned worker required') END;
 SELECT CASE WHEN json_type(NEW.checks_json) IS NOT 'array' OR (NEW.action NOT IN('check_pass','check_fail') AND NEW.checks_json<>'[]') OR (NEW.action IN('check_pass','check_fail') AND (json_array_length(NEW.checks_json) NOT BETWEEN 1 AND 20 OR EXISTS(SELECT 1 FROM json_each(NEW.checks_json) c WHERE json_type(c.value) IS NOT 'object' OR (SELECT count(*) FROM json_each(c.value))<>3 OR json_type(c.value,'$.label') IS NOT 'text' OR length(trim(json_extract(c.value,'$.label'))) NOT BETWEEN 1 AND 120 OR json_extract(c.value,'$.result') NOT IN('pass','fail') OR json_type(c.value,'$.result') IS NOT 'text' OR json_type(c.value,'$.notes') IS NOT 'text' OR length(json_extract(c.value,'$.notes'))>1000))) THEN RAISE(ABORT,'fulfillment checks invalid') END;
 SELECT CASE WHEN NEW.action='check_pass' AND EXISTS(SELECT 1 FROM json_each(NEW.checks_json) WHERE json_extract(value,'$.result')='fail') OR NEW.action='check_fail' AND NOT EXISTS(SELECT 1 FROM json_each(NEW.checks_json) WHERE json_extract(value,'$.result')='fail') THEN RAISE(ABORT,'fulfillment check result invalid') END;
 SELECT CASE WHEN NEW.action='deliver' AND (NEW.handed_at<'2000-01-01T00:00:00.000Z' OR NEW.handed_at>NEW.created_at OR length(NEW.handed_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.handed_at) IS NOT NEW.handed_at) THEN RAISE(ABORT,'fulfillment handover time invalid') END;
 SELECT CASE WHEN NEW.action='deliver' AND EXISTS(SELECT 1 FROM processing_events p,json_each(p.snapshot_json) l WHERE p.job_id=NEW.job_id AND p.revision=NEW.processing_revision AND json_extract(l.value,'$.position')=NEW.position AND json_extract(l.value,'$.supply_mode')='stock') AND NOT EXISTS(SELECT 1 FROM inventory_order_events i JOIN processing_jobs j ON j.id=NEW.job_id WHERE i.order_id=j.order_id AND i.order_version=j.order_version AND i.action='reserve' AND i.revision=(SELECT max(revision) FROM inventory_order_events WHERE order_id=i.order_id)) THEN RAISE(ABORT,'fulfillment original stock reservation missing') END;
END;
CREATE TRIGGER fulfillment_no_update BEFORE UPDATE ON fulfillment_events BEGIN SELECT RAISE(ABORT,'fulfillment history immutable'); END;
CREATE TRIGGER fulfillment_no_delete BEFORE DELETE ON fulfillment_events BEGIN SELECT RAISE(ABORT,'fulfillment history immutable'); END;
