CREATE TABLE inventory_outbounds (
 id TEXT PRIMARY KEY, product_id TEXT NOT NULL, product_version INTEGER NOT NULL, store_id TEXT NOT NULL,
 outbound_revision INTEGER NOT NULL CHECK(typeof(outbound_revision)='integer' AND outbound_revision>=1), basis_sequence INTEGER NOT NULL,
 delivery_id TEXT NOT NULL REFERENCES fulfillment_events(id), order_id TEXT NOT NULL, order_version INTEGER NOT NULL, position INTEGER NOT NULL,
 source_mode TEXT NOT NULL CHECK(source_mode IN('available','reserved')), reservation_id TEXT REFERENCES inventory_order_events(id),
 quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999),
 available_after INTEGER NOT NULL CHECK(typeof(available_after)='integer' AND available_after>=0),reserved_after INTEGER NOT NULL CHECK(typeof(reserved_after)='integer' AND reserved_after>=0),quarantined_after INTEGER NOT NULL CHECK(typeof(quarantined_after)='integer' AND quarantined_after>=0),
 reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(product_id,outbound_revision),FOREIGN KEY(product_id,product_version,store_id) REFERENCES retail_product_versions(product_id,version,store_id),FOREIGN KEY(order_id,order_version,position) REFERENCES retail_order_items(order_id,version,position),
 CHECK((source_mode='available' AND reservation_id IS NULL) OR (source_mode='reserved' AND reservation_id IS NOT NULL))
);
CREATE INDEX outbound_delivery ON inventory_outbounds(delivery_id,outbound_revision);
CREATE INDEX outbound_reservation ON inventory_outbounds(reservation_id,position);
CREATE VIEW inventory_balances AS SELECT e.*,e.available-COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE product_id=e.product_id AND source_mode='available'),0) effective_available,e.reserved-COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE product_id=e.product_id AND source_mode='reserved'),0) effective_reserved,COALESCE((SELECT max(outbound_revision) FROM inventory_outbounds WHERE product_id=e.product_id),0) outbound_revision FROM inventory_events e WHERE e.sequence=(SELECT max(sequence) FROM inventory_events WHERE product_id=e.product_id);
CREATE TRIGGER outbound_ready BEFORE INSERT ON inventory_outbounds BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND u.role IN('manager','reception') AND COALESCE(s.must_change_password,0)=0) THEN RAISE(ABORT,'outbound actor not allowed') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM fulfillment_events d JOIN processing_jobs j ON j.id=d.job_id JOIN retail_order_items i ON i.order_id=j.order_id AND i.version=j.order_version AND i.position=d.position WHERE d.id=NEW.delivery_id AND d.action='deliver' AND j.store_id=NEW.store_id AND j.order_id=NEW.order_id AND j.order_version=NEW.order_version AND d.position=NEW.position AND i.product_id=NEW.product_id AND i.product_version=NEW.product_version AND NEW.created_at>=d.created_at) THEN RAISE(ABORT,'outbound original delivery invalid') END;
 SELECT CASE WHEN NEW.outbound_revision<>COALESCE((SELECT max(outbound_revision)+1 FROM inventory_outbounds WHERE product_id=NEW.product_id),1) OR NEW.basis_sequence IS NOT (SELECT max(sequence) FROM inventory_events WHERE product_id=NEW.product_id) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM inventory_outbounds WHERE product_id=NEW.product_id),'') OR NEW.created_at<(SELECT created_at FROM inventory_balances WHERE product_id=NEW.product_id) THEN RAISE(ABORT,'outbound stock version invalid') END;
 SELECT CASE WHEN NEW.quantity+COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE delivery_id=NEW.delivery_id),0)>(SELECT quantity FROM fulfillment_events WHERE id=NEW.delivery_id) THEN RAISE(ABORT,'outbound delivery quantity exceeded') END;
 SELECT CASE WHEN NEW.source_mode='reserved' AND NOT EXISTS(SELECT 1 FROM inventory_order_events e JOIN inventory_order_lines l ON l.event_id=e.id WHERE e.id=NEW.reservation_id AND e.order_id=NEW.order_id AND e.order_version=NEW.order_version AND e.action='reserve' AND e.revision=(SELECT max(revision) FROM inventory_order_events WHERE order_id=e.order_id) AND l.position=NEW.position AND l.product_id=NEW.product_id AND l.product_version=NEW.product_version AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE reservation_id=e.id AND position=NEW.position),0)<=l.quantity) THEN RAISE(ABORT,'outbound reservation source invalid') END;
 SELECT CASE WHEN NEW.source_mode='available' AND (SELECT action FROM inventory_order_events WHERE order_id=NEW.order_id ORDER BY revision DESC LIMIT 1)='reserve' THEN RAISE(ABORT,'outbound must consume original reservation') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM inventory_events first JOIN retail_product_versions p ON p.product_id=first.product_id AND p.version=first.product_version JOIN retail_product_versions o ON o.product_id=NEW.product_id AND o.version=NEW.product_version WHERE first.product_id=NEW.product_id AND first.sequence=1 AND p.unit=o.unit AND p.category=o.category AND o.category<>'service') THEN RAISE(ABORT,'outbound original stock unit invalid') END;
 SELECT CASE WHEN NEW.available_after IS NOT (SELECT effective_available-CASE WHEN NEW.source_mode='available' THEN NEW.quantity ELSE 0 END FROM inventory_balances WHERE product_id=NEW.product_id) OR NEW.reserved_after IS NOT (SELECT effective_reserved-CASE WHEN NEW.source_mode='reserved' THEN NEW.quantity ELSE 0 END FROM inventory_balances WHERE product_id=NEW.product_id) OR NEW.quarantined_after IS NOT (SELECT quarantined FROM inventory_balances WHERE product_id=NEW.product_id) THEN RAISE(ABORT,'outbound physical balance invalid') END;
END;
CREATE TRIGGER outbound_no_update BEFORE UPDATE ON inventory_outbounds BEGIN SELECT RAISE(ABORT,'outbound history immutable'); END;
CREATE TRIGGER outbound_no_delete BEFORE DELETE ON inventory_outbounds BEGIN SELECT RAISE(ABORT,'outbound history immutable'); END;
CREATE TRIGGER inventory_physical_guard BEFORE INSERT ON inventory_events BEGIN
 SELECT CASE WHEN NEW.available<COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE product_id=NEW.product_id AND source_mode='available'),0) OR NEW.reserved<COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE product_id=NEW.product_id AND source_mode='reserved'),0) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM inventory_outbounds WHERE product_id=NEW.product_id),'') THEN RAISE(ABORT,'inventory dispatched physical stock insufficient') END;
END;
CREATE TRIGGER inventory_dispatched_release_lock BEFORE INSERT ON inventory_order_events WHEN NEW.action='release' AND EXISTS(SELECT 1 FROM inventory_outbounds WHERE reservation_id=NEW.source_id) BEGIN SELECT RAISE(ABORT,'partially dispatched reservation cannot be fully released'); END;
CREATE TRIGGER inventory_dispatched_reserve_lock BEFORE INSERT ON inventory_order_events WHEN NEW.action='reserve' AND EXISTS(SELECT 1 FROM inventory_outbounds WHERE order_id=NEW.order_id) BEGIN SELECT RAISE(ABORT,'dispatched order cannot create new reservation'); END;
CREATE TABLE aftercare_cases (
 id TEXT PRIMARY KEY,delivery_id TEXT NOT NULL REFERENCES fulfillment_events(id),store_id TEXT NOT NULL,customer_id TEXT NOT NULL,serial INTEGER NOT NULL CHECK(typeof(serial)='integer' AND serial>=1),kind TEXT NOT NULL CHECK(kind IN('repair','remake','complaint','return')),quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999),title TEXT NOT NULL CHECK(length(trim(title)) BETWEEN 1 AND 120),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(store_id,serial)
);
CREATE TABLE aftercare_events (
 id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES aftercare_cases(id),revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),action TEXT NOT NULL CHECK(action IN('create','assign','start','note','pause','resume','resolve','cancel','reopen','receive_return')),
 snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)),note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),dispatch_id TEXT REFERENCES inventory_outbounds(id),return_quantity INTEGER,returner_name TEXT,
 reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),
 CHECK((action='receive_return' AND dispatch_id IS NOT NULL AND typeof(return_quantity)='integer' AND return_quantity BETWEEN 1 AND 999 AND returner_name IS NOT NULL AND length(trim(returner_name)) BETWEEN 1 AND 120) OR (action<>'receive_return' AND dispatch_id IS NULL AND return_quantity IS NULL AND returner_name IS NULL))
);
CREATE INDEX aftercare_store ON aftercare_cases(store_id,created_at,id);
CREATE INDEX aftercare_return_dispatch ON aftercare_events(dispatch_id);
CREATE TRIGGER aftercare_case_ready BEFORE INSERT ON aftercare_cases BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND u.role IN('manager','reception') AND COALESCE(s.must_change_password,0)=0) THEN RAISE(ABORT,'aftercare creator not allowed') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM fulfillment_events d JOIN processing_jobs j ON j.id=d.job_id WHERE d.id=NEW.delivery_id AND d.action='deliver' AND j.store_id=NEW.store_id AND j.customer_id=NEW.customer_id AND NEW.quantity<=d.quantity AND NEW.created_at>=d.created_at) THEN RAISE(ABORT,'aftercare original delivery invalid') END;
 SELECT CASE WHEN NEW.serial<>COALESCE((SELECT max(serial)+1 FROM aftercare_cases WHERE store_id=NEW.store_id),1) THEN RAISE(ABORT,'aftercare serial invalid') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_cases c LEFT JOIN aftercare_events e ON e.case_id=c.id AND e.revision=(SELECT max(revision) FROM aftercare_events WHERE case_id=c.id) WHERE c.delivery_id=NEW.delivery_id AND COALESCE(json_extract(e.snapshot_json,'$.status'),'open') NOT IN('resolved','cancelled')) THEN RAISE(ABORT,'aftercare source already active') END;
END;
CREATE TRIGGER aftercare_event_ready BEFORE INSERT ON aftercare_events BEGIN
 SELECT CASE WHEN NEW.revision<>COALESCE((SELECT max(revision)+1 FROM aftercare_events WHERE case_id=NEW.case_id),1) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM aftercare_events WHERE case_id=NEW.case_id),(SELECT created_at FROM aftercare_cases WHERE id=NEW.case_id)) OR (NEW.revision=1 AND NEW.action<>'create') OR (NEW.revision>1 AND NEW.action='create') THEN RAISE(ABORT,'aftercare event revision invalid') END;
 SELECT CASE WHEN json_type(NEW.snapshot_json) IS NOT 'object' OR (SELECT count(*) FROM json_each(NEW.snapshot_json))<>3 OR json_type(NEW.snapshot_json,'$.status') IS NOT 'text' OR json_extract(NEW.snapshot_json,'$.status') NOT IN('open','assigned','running','paused','resolved','cancelled') OR json_type(NEW.snapshot_json,'$.assignee_id') IS NULL OR json_type(NEW.snapshot_json,'$.due_date') IS NULL THEN RAISE(ABORT,'aftercare snapshot invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_cases c JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE c.id=NEW.case_id AND u.store_id=c.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='reception' AND NEW.action IN('create','assign','note','cancel','reopen','receive_return') OR u.role IN('reception','professional') AND NEW.action IN('start','pause','resume','resolve','note') AND u.id=(SELECT json_extract(snapshot_json,'$.assignee_id') FROM aftercare_events WHERE case_id=c.id ORDER BY revision DESC LIMIT 1))) THEN RAISE(ABORT,'aftercare actor not allowed') END;
 SELECT CASE WHEN NEW.revision=1 AND (NEW.snapshot_json<>'{"status":"open","assignee_id":null,"due_date":null}' OR NOT EXISTS(SELECT 1 FROM aftercare_cases c WHERE c.id=NEW.case_id AND c.created_by=NEW.created_by AND c.created_at=NEW.created_at)) THEN RAISE(ABORT,'aftercare first record invalid') END;
 SELECT CASE WHEN NEW.snapshot_json<>json_object('status',json_extract(NEW.snapshot_json,'$.status'),'assignee_id',json_extract(NEW.snapshot_json,'$.assignee_id'),'due_date',json_extract(NEW.snapshot_json,'$.due_date')) OR json_type(NEW.snapshot_json,'$.assignee_id') NOT IN('text','null') OR json_type(NEW.snapshot_json,'$.due_date') NOT IN('text','null') OR (json_type(NEW.snapshot_json,'$.due_date')='text' AND (length(json_extract(NEW.snapshot_json,'$.due_date'))<>10 OR json_extract(NEW.snapshot_json,'$.due_date')<'2000-01-01' OR json_extract(NEW.snapshot_json,'$.due_date')>'2099-12-31' OR date(json_extract(NEW.snapshot_json,'$.due_date'),'+0 days') IS NOT json_extract(NEW.snapshot_json,'$.due_date'))) THEN RAISE(ABORT,'aftercare canonical date invalid') END;
 SELECT CASE WHEN NEW.action='assign' AND (NOT EXISTS(SELECT 1 FROM users u JOIN aftercare_cases c ON c.id=NEW.case_id WHERE u.id=json_extract(NEW.snapshot_json,'$.assignee_id') AND u.store_id=c.store_id AND u.active=1 AND u.role IN('manager','reception','professional')) OR (SELECT role FROM users WHERE id=NEW.created_by) NOT IN('manager','reception')) THEN RAISE(ABORT,'aftercare assignment invalid') END;
 SELECT CASE WHEN NEW.revision>1 AND NEW.action<>'reopen' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled') THEN RAISE(ABORT,'aftercare closed case locked') END;
 SELECT CASE WHEN NEW.action='start' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'assigned' OR NEW.action='pause' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' OR NEW.action='resume' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'paused' OR NEW.action='resolve' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' OR NEW.action='reopen' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) NOT IN('resolved','cancelled') THEN RAISE(ABORT,'aftercare transition invalid') END;
 SELECT CASE WHEN NEW.revision>1 AND NEW.snapshot_json IS NOT (SELECT CASE NEW.action WHEN 'assign' THEN json_set(snapshot_json,'$.status','assigned','$.assignee_id',json_extract(NEW.snapshot_json,'$.assignee_id'),'$.due_date',json_extract(NEW.snapshot_json,'$.due_date')) WHEN 'start' THEN json_set(snapshot_json,'$.status','running') WHEN 'pause' THEN json_set(snapshot_json,'$.status','paused') WHEN 'resume' THEN json_set(snapshot_json,'$.status','running') WHEN 'resolve' THEN json_set(snapshot_json,'$.status','resolved') WHEN 'cancel' THEN json_set(snapshot_json,'$.status','cancelled') WHEN 'reopen' THEN '{"status":"open","assignee_id":null,"due_date":null}' ELSE snapshot_json END FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) THEN RAISE(ABORT,'aftercare snapshot transition invalid') END;
 SELECT CASE WHEN NEW.action IN('create','reopen') AND EXISTS(SELECT 1 FROM aftercare_cases c JOIN aftercare_cases current ON current.id=NEW.case_id LEFT JOIN aftercare_events e ON e.case_id=c.id AND e.revision=(SELECT max(revision) FROM aftercare_events WHERE case_id=c.id) WHERE c.id<>current.id AND c.delivery_id=current.delivery_id AND COALESCE(json_extract(e.snapshot_json,'$.status'),'open') NOT IN('resolved','cancelled')) THEN RAISE(ABORT,'aftercare source already active') END;
 SELECT CASE WHEN NEW.action='receive_return' AND (NOT EXISTS(SELECT 1 FROM inventory_outbounds o JOIN aftercare_cases c ON c.id=NEW.case_id WHERE o.id=NEW.dispatch_id AND o.delivery_id=c.delivery_id AND NEW.created_at>=o.created_at AND NEW.return_quantity+COALESCE((SELECT sum(return_quantity) FROM aftercare_events WHERE dispatch_id=o.id),0)<=o.quantity) OR NEW.return_quantity+COALESCE((SELECT sum(return_quantity) FROM aftercare_events WHERE case_id=NEW.case_id),0)>(SELECT quantity FROM aftercare_cases WHERE id=NEW.case_id)) THEN RAISE(ABORT,'aftercare return source quantity invalid') END;
END;
CREATE TRIGGER aftercare_cases_no_update BEFORE UPDATE ON aftercare_cases BEGIN SELECT RAISE(ABORT,'aftercare source immutable'); END;
CREATE TRIGGER aftercare_cases_no_delete BEFORE DELETE ON aftercare_cases BEGIN SELECT RAISE(ABORT,'aftercare source immutable'); END;
CREATE TRIGGER aftercare_events_no_update BEFORE UPDATE ON aftercare_events BEGIN SELECT RAISE(ABORT,'aftercare history immutable'); END;
CREATE TRIGGER aftercare_events_no_delete BEFORE DELETE ON aftercare_events BEGIN SELECT RAISE(ABORT,'aftercare history immutable'); END;
