CREATE TABLE aftercare_work_events (
 id TEXT PRIMARY KEY,case_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),case_revision INTEGER NOT NULL,
 action TEXT NOT NULL CHECK(action IN('plan','start','complete','check_pass','check_fail','rework_plan','rework_start','rework_complete','return','cancel_plan')),
 return_id TEXT NOT NULL REFERENCES aftercare_events(id),source_id TEXT REFERENCES aftercare_work_events(id),quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999),
 assignee_id TEXT REFERENCES users(id),instructions TEXT,checks_json TEXT NOT NULL CHECK(json_valid(checks_json)),receiver_name TEXT,returned_at TEXT,receipt_note TEXT,
 note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(case_id,revision),FOREIGN KEY(case_id,case_revision) REFERENCES aftercare_events(case_id,revision),
 CHECK((action='plan' AND source_id IS NULL) OR (action<>'plan' AND source_id IS NOT NULL)),
 CHECK((action IN('plan','rework_plan') AND assignee_id IS NOT NULL AND instructions IS NOT NULL AND length(trim(instructions)) BETWEEN 1 AND 1000) OR (action NOT IN('plan','rework_plan') AND assignee_id IS NULL AND instructions IS NULL)),
 CHECK((action='return' AND receiver_name IS NOT NULL AND length(trim(receiver_name)) BETWEEN 1 AND 120 AND returned_at IS NOT NULL AND receipt_note IS NOT NULL AND length(trim(receipt_note)) BETWEEN 1 AND 1000) OR (action<>'return' AND receiver_name IS NULL AND returned_at IS NULL AND receipt_note IS NULL))
);
CREATE INDEX aftercare_work_return ON aftercare_work_events(return_id,action);
CREATE INDEX aftercare_work_source ON aftercare_work_events(source_id);
CREATE TRIGGER aftercare_work_ready BEFORE INSERT ON aftercare_work_events BEGIN
 SELECT CASE WHEN NEW.revision<>COALESCE((SELECT max(revision)+1 FROM aftercare_work_events WHERE case_id=NEW.case_id),1) OR NEW.case_revision IS NOT (SELECT max(revision) FROM aftercare_events WHERE case_id=NEW.case_id) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM aftercare_work_events WHERE case_id=NEW.case_id),'') OR NEW.created_at<(SELECT created_at FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) THEN RAISE(ABORT,'aftercare work version invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_events e WHERE e.id=NEW.return_id AND e.case_id=NEW.case_id AND e.action='receive_return' AND NEW.created_at>=e.created_at) THEN RAISE(ABORT,'aftercare work received source invalid') END;
 SELECT CASE WHEN (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled') OR NEW.action NOT IN('plan','rework_plan','cancel_plan') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' THEN RAISE(ABORT,'aftercare work case inactive') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_cases c JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE c.id=NEW.case_id AND u.store_id=c.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='reception' AND NEW.action IN('plan','rework_plan','cancel_plan','return') OR u.role='professional' AND NEW.action IN('check_pass','check_fail') OR u.role IN('reception','professional') AND NEW.action IN('start','complete','rework_start','rework_complete') AND u.id=(SELECT a.assignee_id FROM aftercare_work_events a WHERE a.id=CASE WHEN NEW.action IN('start','rework_start') THEN NEW.source_id ELSE (SELECT source_id FROM aftercare_work_events WHERE id=NEW.source_id) END))) THEN RAISE(ABORT,'aftercare work actor not allowed') END;
 SELECT CASE WHEN NEW.action IN('plan','rework_plan') AND NOT EXISTS(SELECT 1 FROM users u JOIN aftercare_cases c ON c.id=NEW.case_id WHERE u.id=NEW.assignee_id AND u.store_id=c.store_id AND u.active=1 AND u.role IN('manager','reception','professional')) THEN RAISE(ABORT,'aftercare work assignee invalid') END;
 SELECT CASE WHEN NEW.action<>'plan' AND NOT EXISTS(SELECT 1 FROM aftercare_work_events e WHERE e.id=NEW.source_id AND e.case_id=NEW.case_id AND e.return_id=NEW.return_id AND e.created_at<=NEW.created_at AND (NEW.action IN('start','cancel_plan') AND e.action='plan' OR NEW.action='complete' AND e.action='start' OR NEW.action IN('check_pass','check_fail') AND e.action IN('complete','rework_complete') OR NEW.action='rework_plan' AND e.action='check_fail' OR NEW.action='rework_start' AND e.action='rework_plan' OR NEW.action='rework_complete' AND e.action='rework_start' OR NEW.action='return' AND e.action='check_pass')) THEN RAISE(ABORT,'aftercare work parent source invalid') END;
 SELECT CASE WHEN NEW.action='plan' AND NEW.quantity+COALESCE((SELECT sum(e.quantity) FROM aftercare_work_events e WHERE e.return_id=NEW.return_id AND e.action='plan' AND NOT EXISTS(SELECT 1 FROM aftercare_work_events cancelled WHERE cancelled.source_id=e.id AND cancelled.action='cancel_plan')),0)>(SELECT return_quantity FROM aftercare_events WHERE id=NEW.return_id) THEN RAISE(ABORT,'aftercare work received quantity exceeded') END;
 SELECT CASE WHEN NEW.source_id IS NOT NULL AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM aftercare_work_events WHERE source_id=NEW.source_id),0)>(SELECT quantity FROM aftercare_work_events WHERE id=NEW.source_id) THEN RAISE(ABORT,'aftercare work source quantity exceeded') END;
 SELECT CASE WHEN NEW.action='cancel_plan' AND (NEW.quantity IS NOT (SELECT quantity FROM aftercare_work_events WHERE id=NEW.source_id) OR EXISTS(SELECT 1 FROM aftercare_work_events WHERE source_id=NEW.source_id)) THEN RAISE(ABORT,'aftercare work cancellation executed source') END;
 SELECT CASE WHEN json_type(NEW.checks_json) IS NOT 'array' OR NEW.action NOT IN('check_pass','check_fail') AND NEW.checks_json<>'[]' OR NEW.action IN('check_pass','check_fail') AND (json_array_length(NEW.checks_json) NOT BETWEEN 1 AND 20 OR EXISTS(SELECT 1 FROM json_each(NEW.checks_json) c WHERE c.type<>'object' OR (SELECT count(*) FROM json_each(c.value))<>3 OR json_type(c.value,'$.label') IS NOT 'text' OR length(trim(json_extract(c.value,'$.label'))) NOT BETWEEN 1 AND 120 OR json_type(c.value,'$.result') IS NOT 'text' OR json_extract(c.value,'$.result') NOT IN('pass','fail') OR json_type(c.value,'$.notes') IS NOT 'text' OR length(json_extract(c.value,'$.notes'))>1000)) THEN RAISE(ABORT,'aftercare work checklist invalid') END;
 SELECT CASE WHEN NEW.action='check_pass' AND EXISTS(SELECT 1 FROM json_each(NEW.checks_json) WHERE json_extract(value,'$.result')='fail') OR NEW.action='check_fail' AND NOT EXISTS(SELECT 1 FROM json_each(NEW.checks_json) WHERE json_extract(value,'$.result')='fail') THEN RAISE(ABORT,'aftercare work check result invalid') END;
 SELECT CASE WHEN NEW.action='return' AND (NEW.returned_at<'2000-01-01T00:00:00.000Z' OR NEW.returned_at>NEW.created_at OR length(NEW.returned_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.returned_at,'+0 days') IS NOT NEW.returned_at OR NEW.quantity+COALESCE((SELECT sum(quantity) FROM aftercare_work_events WHERE return_id=NEW.return_id AND action='return'),0)>(SELECT return_quantity FROM aftercare_events WHERE id=NEW.return_id)) THEN RAISE(ABORT,'aftercare work return receipt invalid') END;
END;
CREATE TRIGGER aftercare_work_no_update BEFORE UPDATE ON aftercare_work_events BEGIN SELECT RAISE(ABORT,'aftercare work immutable');END;
CREATE TRIGGER aftercare_work_no_delete BEFORE DELETE ON aftercare_work_events BEGIN SELECT RAISE(ABORT,'aftercare work immutable');END;

DROP TRIGGER aftercare_event_ready;
CREATE TRIGGER aftercare_event_ready BEFORE INSERT ON aftercare_events BEGIN
 SELECT CASE WHEN NEW.revision<>COALESCE((SELECT max(revision)+1 FROM aftercare_events WHERE case_id=NEW.case_id),1) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM aftercare_events WHERE case_id=NEW.case_id),(SELECT created_at FROM aftercare_cases WHERE id=NEW.case_id)) OR (NEW.revision=1 AND NEW.action<>'create') OR (NEW.revision>1 AND NEW.action='create') THEN RAISE(ABORT,'aftercare event revision invalid') END;
 SELECT CASE WHEN json_type(NEW.snapshot_json) IS NOT 'object' OR (SELECT count(*) FROM json_each(NEW.snapshot_json))<>3 OR json_type(NEW.snapshot_json,'$.status') IS NOT 'text' OR json_extract(NEW.snapshot_json,'$.status') NOT IN('open','assigned','running','paused','resolved','cancelled') OR json_type(NEW.snapshot_json,'$.assignee_id') IS NULL OR json_type(NEW.snapshot_json,'$.due_date') IS NULL THEN RAISE(ABORT,'aftercare snapshot invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_cases c JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE c.id=NEW.case_id AND u.store_id=c.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='reception' AND NEW.action IN('create','assign','note','cancel','reopen','receive_return') OR u.role IN('reception','professional') AND NEW.action IN('start','pause','resume','resolve','note') AND u.id=(SELECT json_extract(snapshot_json,'$.assignee_id') FROM aftercare_events WHERE case_id=c.id ORDER BY revision DESC LIMIT 1))) THEN RAISE(ABORT,'aftercare actor not allowed') END;
 SELECT CASE WHEN NEW.revision=1 AND (NEW.snapshot_json<>'{"status":"open","assignee_id":null,"due_date":null}' OR NOT EXISTS(SELECT 1 FROM aftercare_cases c WHERE c.id=NEW.case_id AND c.created_by=NEW.created_by AND c.created_at=NEW.created_at)) THEN RAISE(ABORT,'aftercare first record invalid') END;
 SELECT CASE WHEN NEW.snapshot_json<>json_object('status',json_extract(NEW.snapshot_json,'$.status'),'assignee_id',json_extract(NEW.snapshot_json,'$.assignee_id'),'due_date',json_extract(NEW.snapshot_json,'$.due_date')) OR json_type(NEW.snapshot_json,'$.assignee_id') NOT IN('text','null') OR json_type(NEW.snapshot_json,'$.due_date') NOT IN('text','null') OR (json_type(NEW.snapshot_json,'$.due_date')='text' AND (length(json_extract(NEW.snapshot_json,'$.due_date'))<>10 OR json_extract(NEW.snapshot_json,'$.due_date')<'2000-01-01' OR json_extract(NEW.snapshot_json,'$.due_date')>'2099-12-31' OR date(json_extract(NEW.snapshot_json,'$.due_date'),'+0 days') IS NOT json_extract(NEW.snapshot_json,'$.due_date'))) THEN RAISE(ABORT,'aftercare canonical date invalid') END;
 SELECT CASE WHEN NEW.action='assign' AND (NOT EXISTS(SELECT 1 FROM users u JOIN aftercare_cases c ON c.id=NEW.case_id WHERE u.id=json_extract(NEW.snapshot_json,'$.assignee_id') AND u.store_id=c.store_id AND u.active=1 AND u.role IN('manager','reception','professional')) OR (SELECT role FROM users WHERE id=NEW.created_by) NOT IN('manager','reception')) THEN RAISE(ABORT,'aftercare assignment invalid') END;
 SELECT CASE WHEN NEW.revision>1 AND NEW.action<>'reopen' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled') THEN RAISE(ABORT,'aftercare closed case locked') END;
 SELECT CASE WHEN NEW.action='start' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'assigned' OR NEW.action='pause' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' OR NEW.action='resume' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'paused' OR NEW.action='resolve' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' OR NEW.action='reopen' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) NOT IN('resolved','cancelled') THEN RAISE(ABORT,'aftercare transition invalid') END;
 SELECT CASE WHEN NEW.revision>1 AND NEW.snapshot_json IS NOT (SELECT CASE NEW.action WHEN 'assign' THEN json_set(snapshot_json,'$.status','assigned','$.assignee_id',json_extract(NEW.snapshot_json,'$.assignee_id'),'$.due_date',json_extract(NEW.snapshot_json,'$.due_date')) WHEN 'start' THEN json_set(snapshot_json,'$.status','running') WHEN 'pause' THEN json_set(snapshot_json,'$.status','paused') WHEN 'resume' THEN json_set(snapshot_json,'$.status','running') WHEN 'resolve' THEN json_set(snapshot_json,'$.status','resolved') WHEN 'cancel' THEN json_set(snapshot_json,'$.status','cancelled') WHEN 'reopen' THEN '{"status":"open","assignee_id":null,"due_date":null}' ELSE snapshot_json END FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) THEN RAISE(ABORT,'aftercare snapshot transition invalid') END;
 SELECT CASE WHEN NEW.action IN('create','reopen') AND EXISTS(SELECT 1 FROM aftercare_cases c JOIN aftercare_cases current ON current.id=NEW.case_id LEFT JOIN aftercare_events e ON e.case_id=c.id AND e.revision=(SELECT max(revision) FROM aftercare_events WHERE case_id=c.id) WHERE c.id<>current.id AND c.delivery_id=current.delivery_id AND COALESCE(json_extract(e.snapshot_json,'$.status'),'open') NOT IN('resolved','cancelled')) THEN RAISE(ABORT,'aftercare source already active') END;
 SELECT CASE WHEN NEW.action='receive_return' AND (NOT EXISTS(SELECT 1 FROM inventory_outbounds o JOIN aftercare_cases c ON c.id=NEW.case_id WHERE o.id=NEW.dispatch_id AND o.delivery_id=c.delivery_id AND NEW.created_at>=o.created_at AND NEW.return_quantity+COALESCE((SELECT sum(return_quantity) FROM aftercare_events WHERE dispatch_id=o.id),0)<=o.quantity+COALESCE((SELECT sum(w.quantity) FROM aftercare_work_events w JOIN aftercare_events r ON r.id=w.return_id WHERE w.action='return' AND r.dispatch_id=o.id AND w.created_at<=NEW.created_at),0)) OR NEW.return_quantity+COALESCE((SELECT sum(return_quantity) FROM aftercare_events WHERE case_id=NEW.case_id),0)>(SELECT quantity FROM aftercare_cases WHERE id=NEW.case_id)) THEN RAISE(ABORT,'aftercare return source quantity invalid') END;
END;
