CREATE TABLE aftercare_replacements (
 id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES aftercare_cases(id),serial INTEGER NOT NULL CHECK(typeof(serial)='integer' AND serial>=1),kind TEXT NOT NULL CHECK(kind IN('remake','exchange')),quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999),new_order_id TEXT NOT NULL UNIQUE,new_order_version INTEGER NOT NULL,instructions TEXT NOT NULL CHECK(length(trim(instructions)) BETWEEN 1 AND 1000),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,serial),FOREIGN KEY(new_order_id,new_order_version) REFERENCES retail_order_versions(order_id,version)
);
CREATE TABLE aftercare_replacement_events (
 id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES aftercare_replacements(id),revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),case_id TEXT NOT NULL,case_revision INTEGER NOT NULL,case_sequence INTEGER NOT NULL CHECK(typeof(case_sequence)='integer' AND case_sequence>=1),action TEXT NOT NULL CHECK(action IN('create','approve','cancel','complete')),status TEXT NOT NULL CHECK(status IN('pending','approved','cancelled','completed')),note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(plan_id,revision),UNIQUE(case_id,case_sequence),FOREIGN KEY(case_id,case_revision) REFERENCES aftercare_events(case_id,revision),CHECK(status=CASE action WHEN 'create' THEN 'pending' WHEN 'approve' THEN 'approved' WHEN 'cancel' THEN 'cancelled' WHEN 'complete' THEN 'completed' END)
);
CREATE TABLE aftercare_replacement_operations (
 id TEXT PRIMARY KEY,plan_id TEXT NOT NULL,case_id TEXT NOT NULL,case_revision INTEGER NOT NULL,plan_revision INTEGER NOT NULL,record_type TEXT NOT NULL CHECK(record_type IN('reservation','payment','processing_job','processing','fulfillment','outbound')),record_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(record_type,record_id),FOREIGN KEY(case_id,case_revision) REFERENCES aftercare_events(case_id,revision),FOREIGN KEY(plan_id,plan_revision) REFERENCES aftercare_replacement_events(plan_id,revision)
);
CREATE TRIGGER replacement_ready BEFORE INSERT ON aftercare_replacements BEGIN
 SELECT CASE WHEN NEW.serial<>COALESCE((SELECT max(serial)+1 FROM aftercare_replacements WHERE case_id=NEW.case_id),1) THEN RAISE(ABORT,'replacement serial invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_cases c JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE c.id=NEW.case_id AND c.created_at<=NEW.created_at AND u.store_id=c.store_id AND u.active=1 AND u.role IN('manager','reception') AND COALESCE(s.must_change_password,0)=0 AND (SELECT status FROM retail_order_versions WHERE order_id=NEW.new_order_id ORDER BY version DESC LIMIT 1)='draft' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=c.id ORDER BY revision DESC LIMIT 1) NOT IN('resolved','cancelled')) THEN RAISE(ABORT,'replacement case or actor invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM retail_orders o JOIN aftercare_cases c ON c.id=NEW.case_id JOIN fulfillment_events f ON f.id=c.delivery_id JOIN processing_jobs j ON j.id=f.job_id JOIN retail_order_versions v ON v.order_id=o.id AND v.version=NEW.new_order_version WHERE o.id=NEW.new_order_id AND o.id<>j.order_id AND o.customer_id=c.customer_id AND o.store_id=c.store_id AND v.created_at<=NEW.created_at AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=o.id)) THEN RAISE(ABORT,'replacement new order source invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM retail_order_items WHERE order_id=NEW.new_order_id AND version=NEW.new_order_version) OR EXISTS(SELECT 1 FROM retail_order_items i JOIN retail_product_versions p ON p.product_id=i.product_id AND p.version=i.product_version WHERE i.order_id=NEW.new_order_id AND i.version=NEW.new_order_version AND p.category='service') OR EXISTS(SELECT 1 FROM inventory_order_events WHERE order_id=NEW.new_order_id) OR EXISTS(SELECT 1 FROM payment_events WHERE order_id=NEW.new_order_id) OR EXISTS(SELECT 1 FROM processing_jobs WHERE order_id=NEW.new_order_id) THEN RAISE(ABORT,'replacement new order is not untouched goods draft') END;
 SELECT CASE WHEN NEW.quantity+COALESCE((SELECT sum(p.quantity) FROM aftercare_replacements p WHERE p.case_id=NEW.case_id AND COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'cancelled'),0)>(SELECT quantity FROM aftercare_cases WHERE id=NEW.case_id) THEN RAISE(ABORT,'replacement case quantity exceeded') END;
END;
CREATE TRIGGER replacement_event_ready BEFORE INSERT ON aftercare_replacement_events BEGIN
 SELECT CASE WHEN NEW.case_sequence<>COALESCE((SELECT max(case_sequence)+1 FROM aftercare_replacement_events WHERE case_id=NEW.case_id),1) OR NEW.revision<>COALESCE((SELECT max(revision)+1 FROM aftercare_replacement_events WHERE plan_id=NEW.plan_id),1) OR NEW.case_id IS NOT (SELECT case_id FROM aftercare_replacements WHERE id=NEW.plan_id) OR NEW.case_revision IS NOT (SELECT max(revision) FROM aftercare_events WHERE case_id=NEW.case_id) OR NEW.created_at<(SELECT created_at FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) OR NEW.created_at<COALESCE((SELECT created_at FROM aftercare_replacement_events WHERE case_id=NEW.case_id ORDER BY case_sequence DESC LIMIT 1),(SELECT created_at FROM aftercare_replacements WHERE id=NEW.plan_id)) THEN RAISE(ABORT,'replacement event source or revision invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u JOIN aftercare_cases c ON c.id=NEW.case_id LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=c.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='reception' AND NEW.action<>'approve')) OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled') THEN RAISE(ABORT,'replacement event case or actor invalid') END;
 SELECT CASE WHEN NEW.action='create' AND (NEW.revision<>1 OR NEW.created_by IS NOT (SELECT created_by FROM aftercare_replacements WHERE id=NEW.plan_id) OR NEW.created_at IS NOT (SELECT created_at FROM aftercare_replacements WHERE id=NEW.plan_id)) OR NEW.action='approve' AND (SELECT status FROM aftercare_replacement_events WHERE plan_id=NEW.plan_id ORDER BY revision DESC LIMIT 1) IS NOT 'pending' OR NEW.action='cancel' AND COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=NEW.plan_id ORDER BY revision DESC LIMIT 1),'missing') NOT IN('pending','approved') OR NEW.action='complete' AND (SELECT status FROM aftercare_replacement_events WHERE plan_id=NEW.plan_id ORDER BY revision DESC LIMIT 1) IS NOT 'approved' THEN RAISE(ABORT,'replacement transition invalid') END;
 SELECT CASE WHEN NEW.action='cancel' AND (EXISTS(SELECT 1 FROM inventory_order_events e JOIN aftercare_replacements p ON p.new_order_id=e.order_id WHERE p.id=NEW.plan_id AND e.action='reserve' AND e.revision=(SELECT max(revision) FROM inventory_order_events WHERE order_id=e.order_id)) OR EXISTS(SELECT 1 FROM payment_events e JOIN aftercare_replacements p ON p.new_order_id=e.order_id WHERE p.id=NEW.plan_id AND e.action='receive' AND NOT EXISTS(SELECT 1 FROM payment_events v WHERE v.source_id=e.id)) OR EXISTS(SELECT 1 FROM processing_jobs j JOIN aftercare_replacements p ON p.new_order_id=j.order_id WHERE p.id=NEW.plan_id AND (SELECT action FROM processing_events WHERE job_id=j.id ORDER BY revision DESC LIMIT 1)<>'cancel') OR EXISTS(SELECT 1 FROM inventory_outbounds o JOIN aftercare_replacements p ON p.new_order_id=o.order_id WHERE p.id=NEW.plan_id)) THEN RAISE(ABORT,'replacement new order has protected activity') END;
 SELECT CASE WHEN NEW.action='complete' AND ((SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' OR EXISTS(SELECT 1 FROM retail_order_items i JOIN aftercare_replacements p ON p.new_order_id=i.order_id AND p.new_order_version=i.version WHERE p.id=NEW.plan_id AND COALESCE((SELECT sum(quantity) FROM inventory_outbounds WHERE order_id=i.order_id AND order_version=i.version AND position=i.position),0)<>i.quantity)) THEN RAISE(ABORT,'replacement new goods not fully dispatched') END;
END;
CREATE TRIGGER replacement_order_lock BEFORE INSERT ON retail_order_versions WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'cancelled') BEGIN SELECT RAISE(ABORT,'replacement locks new order version');END;
CREATE TRIGGER replacement_reservation_gate BEFORE INSERT ON inventory_order_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending') NOT IN('approved','completed') OR ('reservation' IN('processing_job','processing') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled')) OR (0) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'approved' OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1)<>'running'))) THEN RAISE(ABORT,'replacement approval or case execution required') END;
END;
CREATE TRIGGER replacement_reservation_capture AFTER INSERT ON inventory_order_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 INSERT INTO aftercare_replacement_operations SELECT lower(hex(randomblob(16))),p.id,p.case_id,(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id),(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id),'reservation',NEW.id,NEW.created_at FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version;
END;
CREATE TRIGGER replacement_payment_gate BEFORE INSERT ON payment_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending') NOT IN('approved','completed') OR ('payment' IN('processing_job','processing') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled')) OR (0) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'approved' OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1)<>'running'))) THEN RAISE(ABORT,'replacement approval or case execution required') END;
END;
CREATE TRIGGER replacement_payment_capture AFTER INSERT ON payment_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 INSERT INTO aftercare_replacement_operations SELECT lower(hex(randomblob(16))),p.id,p.case_id,(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id),(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id),'payment',NEW.id,NEW.created_at FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version;
END;
CREATE TRIGGER replacement_processing_job_gate BEFORE INSERT ON processing_jobs WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending') NOT IN('approved','completed') OR ('processing_job' IN('processing_job','processing') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled')) OR (0) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'approved' OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1)<>'running'))) THEN RAISE(ABORT,'replacement approval or case execution required') END;
END;
CREATE TRIGGER replacement_processing_job_capture AFTER INSERT ON processing_jobs WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 INSERT INTO aftercare_replacement_operations SELECT lower(hex(randomblob(16))),p.id,p.case_id,(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id),(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id),'processing_job',NEW.id,NEW.created_at FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version;
END;
CREATE TRIGGER replacement_processing_gate BEFORE INSERT ON processing_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id)) BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending') NOT IN('approved','completed') OR ('processing' IN('processing_job','processing') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled')) OR (NEW.action IN('receive','start','complete')) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'approved' OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1)<>'running'))) THEN RAISE(ABORT,'replacement approval or case execution required') END;
END;
CREATE TRIGGER replacement_processing_capture AFTER INSERT ON processing_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id)) BEGIN
 INSERT INTO aftercare_replacement_operations SELECT lower(hex(randomblob(16))),p.id,p.case_id,(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id),(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id),'processing',NEW.id,NEW.created_at FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id);
END;
CREATE TRIGGER replacement_fulfillment_gate BEFORE INSERT ON fulfillment_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id)) BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending') NOT IN('approved','completed') OR ('fulfillment' IN('processing_job','processing') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled')) OR (1) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'approved' OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1)<>'running'))) THEN RAISE(ABORT,'replacement approval or case execution required') END;
END;
CREATE TRIGGER replacement_fulfillment_capture AFTER INSERT ON fulfillment_events WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id)) BEGIN
 INSERT INTO aftercare_replacement_operations SELECT lower(hex(randomblob(16))),p.id,p.case_id,(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id),(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id),'fulfillment',NEW.id,NEW.created_at FROM aftercare_replacements p WHERE p.new_order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id) AND p.new_order_version=(SELECT order_version FROM processing_jobs WHERE id=NEW.job_id);
END;
CREATE TRIGGER replacement_outbound_gate BEFORE INSERT ON inventory_outbounds WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending') NOT IN('approved','completed') OR ('outbound' IN('processing_job','processing') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled')) OR (1) AND (COALESCE((SELECT status FROM aftercare_replacement_events WHERE plan_id=p.id ORDER BY revision DESC LIMIT 1),'pending')<>'approved' OR (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=p.case_id ORDER BY revision DESC LIMIT 1)<>'running'))) THEN RAISE(ABORT,'replacement approval or case execution required') END;
END;
CREATE TRIGGER replacement_outbound_capture AFTER INSERT ON inventory_outbounds WHEN EXISTS(SELECT 1 FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version) BEGIN
 INSERT INTO aftercare_replacement_operations SELECT lower(hex(randomblob(16))),p.id,p.case_id,(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id),(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id),'outbound',NEW.id,NEW.created_at FROM aftercare_replacements p WHERE p.new_order_id=NEW.order_id AND p.new_order_version=NEW.order_version;
END;
CREATE VIEW replacement_business_records AS SELECT b.id record_id,'reservation' record_type,b.created_at,b.order_id order_id,b.order_version order_version,(0) actual FROM inventory_order_events b UNION ALL SELECT b.id record_id,'payment' record_type,b.created_at,b.order_id order_id,b.order_version order_version,(0) actual FROM payment_events b UNION ALL SELECT b.id record_id,'processing_job' record_type,b.created_at,b.order_id order_id,b.order_version order_version,(0) actual FROM processing_jobs b UNION ALL SELECT b.id record_id,'processing' record_type,b.created_at,(SELECT order_id FROM processing_jobs WHERE id=b.job_id) order_id,(SELECT order_version FROM processing_jobs WHERE id=b.job_id) order_version,(b.action IN('receive','start','complete')) actual FROM processing_events b UNION ALL SELECT b.id record_id,'fulfillment' record_type,b.created_at,(SELECT order_id FROM processing_jobs WHERE id=b.job_id) order_id,(SELECT order_version FROM processing_jobs WHERE id=b.job_id) order_version,(1) actual FROM fulfillment_events b UNION ALL SELECT b.id record_id,'outbound' record_type,b.created_at,b.order_id order_id,b.order_version order_version,(1) actual FROM inventory_outbounds b;
CREATE TRIGGER replacement_operation_ready BEFORE INSERT ON aftercare_replacement_operations BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_replacements p JOIN aftercare_replacement_events e ON e.plan_id=p.id AND e.revision=NEW.plan_revision JOIN aftercare_events c ON c.case_id=p.case_id AND c.revision=NEW.case_revision JOIN replacement_business_records b ON b.record_type=NEW.record_type AND b.record_id=NEW.record_id WHERE p.id=NEW.plan_id AND p.case_id=NEW.case_id AND e.status IN('approved','completed') AND e.revision=(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id) AND c.revision=(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id) AND b.order_id=p.new_order_id AND b.order_version=p.new_order_version AND b.created_at=NEW.created_at AND NEW.created_at>=e.created_at AND NEW.created_at>=c.created_at AND (b.record_type NOT IN('processing_job','processing') OR json_extract(c.snapshot_json,'$.status') NOT IN('resolved','cancelled')) AND (b.actual=0 OR e.status='approved' AND json_extract(c.snapshot_json,'$.status')='running')) THEN RAISE(ABORT,'replacement operation fixed source invalid') END;
END;
CREATE TRIGGER aftercare_replacements_no_update BEFORE UPDATE ON aftercare_replacements BEGIN SELECT RAISE(ABORT,'replacement history immutable');END;
CREATE TRIGGER aftercare_replacements_no_delete BEFORE DELETE ON aftercare_replacements BEGIN SELECT RAISE(ABORT,'replacement history immutable');END;
CREATE TRIGGER aftercare_replacement_events_no_update BEFORE UPDATE ON aftercare_replacement_events BEGIN SELECT RAISE(ABORT,'replacement history immutable');END;
CREATE TRIGGER aftercare_replacement_events_no_delete BEFORE DELETE ON aftercare_replacement_events BEGIN SELECT RAISE(ABORT,'replacement history immutable');END;
CREATE TRIGGER aftercare_replacement_operations_no_update BEFORE UPDATE ON aftercare_replacement_operations BEGIN SELECT RAISE(ABORT,'replacement history immutable');END;
CREATE TRIGGER aftercare_replacement_operations_no_delete BEFORE DELETE ON aftercare_replacement_operations BEGIN SELECT RAISE(ABORT,'replacement history immutable');END;
