CREATE TABLE aftercare_disposition_events (
 id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES aftercare_cases(id),sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>=1),case_revision INTEGER NOT NULL,work_revision INTEGER NOT NULL CHECK(typeof(work_revision)='integer' AND work_revision>=0),
 root_id TEXT NOT NULL REFERENCES aftercare_disposition_events(id),revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),action TEXT NOT NULL CHECK(action IN('create','approve','reject','cancel','execute')),status TEXT NOT NULL CHECK(status IN('pending','approved','rejected','cancelled','executed')),
 return_id TEXT NOT NULL REFERENCES aftercare_events(id),work_source_id TEXT REFERENCES aftercare_work_events(id),quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 999),kind TEXT NOT NULL CHECK(kind IN('scrap','supplier_return')),
 destination TEXT NOT NULL CHECK(length(trim(destination)) BETWEEN 1 AND 200),basis TEXT NOT NULL CHECK(length(trim(basis)) BETWEEN 1 AND 1000),
 receiver_name TEXT,occurred_at TEXT,reference TEXT,receipt_note TEXT,note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(case_id,sequence),UNIQUE(root_id,revision),FOREIGN KEY(case_id,case_revision) REFERENCES aftercare_events(case_id,revision),
 CHECK(status=CASE action WHEN 'create' THEN 'pending' WHEN 'approve' THEN 'approved' WHEN 'reject' THEN 'rejected' WHEN 'cancel' THEN 'cancelled' ELSE 'executed' END),
 CHECK((action='create' AND root_id=id AND revision=1) OR (action<>'create' AND root_id<>id AND revision>1)),
 CHECK((action='execute' AND receiver_name IS NOT NULL AND length(trim(receiver_name)) BETWEEN 1 AND 120 AND occurred_at IS NOT NULL AND reference IS NOT NULL AND length(trim(reference)) BETWEEN 1 AND 160 AND receipt_note IS NOT NULL AND length(trim(receipt_note)) BETWEEN 1 AND 1000) OR (action<>'execute' AND receiver_name IS NULL AND occurred_at IS NULL AND reference IS NULL AND receipt_note IS NULL))
);
CREATE INDEX aftercare_disposition_source ON aftercare_disposition_events(return_id,work_source_id);
CREATE VIEW aftercare_disposition_latest AS SELECT e.* FROM aftercare_disposition_events e WHERE e.revision=(SELECT max(revision) FROM aftercare_disposition_events WHERE root_id=e.root_id);
CREATE TABLE aftercare_work_disposition_refs(work_event_id TEXT PRIMARY KEY REFERENCES aftercare_work_events(id),case_id TEXT NOT NULL REFERENCES aftercare_cases(id),sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>=0));
INSERT INTO aftercare_work_disposition_refs SELECT id,case_id,0 FROM aftercare_work_events;
CREATE TRIGGER aftercare_disposition_ready BEFORE INSERT ON aftercare_disposition_events BEGIN
 SELECT CASE WHEN NEW.sequence<>COALESCE((SELECT max(sequence)+1 FROM aftercare_disposition_events WHERE case_id=NEW.case_id),1) OR NEW.revision<>COALESCE((SELECT max(revision)+1 FROM aftercare_disposition_events WHERE root_id=NEW.root_id),1) OR NEW.case_revision IS NOT (SELECT max(revision) FROM aftercare_events WHERE case_id=NEW.case_id) OR NEW.work_revision<>COALESCE((SELECT max(revision) FROM aftercare_work_events WHERE case_id=NEW.case_id),0) OR NEW.created_at<(SELECT max(created_at) FROM aftercare_events WHERE case_id=NEW.case_id) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM aftercare_work_events WHERE case_id=NEW.case_id),'') OR NEW.created_at<COALESCE((SELECT max(created_at) FROM aftercare_disposition_events WHERE case_id=NEW.case_id),'') THEN RAISE(ABORT,'aftercare disposition versions invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u JOIN aftercare_cases c ON c.id=NEW.case_id LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=c.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='reception' AND NEW.action IN('create','cancel','execute'))) THEN RAISE(ABORT,'aftercare disposition actor not allowed') END;
 SELECT CASE WHEN NEW.action IN('create','approve','execute') AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1) IN('resolved','cancelled') OR NEW.action='execute' AND (SELECT json_extract(snapshot_json,'$.status') FROM aftercare_events WHERE case_id=NEW.case_id ORDER BY revision DESC LIMIT 1)<>'running' THEN RAISE(ABORT,'aftercare disposition case inactive') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_events r WHERE r.id=NEW.return_id AND r.case_id=NEW.case_id AND r.action='receive_return' AND r.created_at<=NEW.created_at) OR NEW.work_source_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM aftercare_work_events w WHERE w.id=NEW.work_source_id AND w.case_id=NEW.case_id AND w.return_id=NEW.return_id AND w.action IN('check_pass','check_fail') AND w.created_at<=NEW.created_at) THEN RAISE(ABORT,'aftercare disposition source invalid') END;
 SELECT CASE WHEN NEW.action<>'create' AND NOT EXISTS(SELECT 1 FROM aftercare_disposition_events r JOIN aftercare_disposition_latest l ON l.root_id=r.id WHERE r.id=NEW.root_id AND r.action='create' AND r.case_id=NEW.case_id AND r.return_id=NEW.return_id AND r.work_source_id IS NEW.work_source_id AND r.quantity=NEW.quantity AND r.kind=NEW.kind AND r.destination=NEW.destination AND r.basis=NEW.basis AND (NEW.action IN('approve','reject') AND l.status='pending' OR NEW.action='cancel' AND l.status IN('pending','approved') OR NEW.action='execute' AND l.status='approved')) THEN RAISE(ABORT,'aftercare disposition source or transition invalid') END;
 SELECT CASE WHEN NEW.action='create' AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM aftercare_disposition_latest WHERE return_id=NEW.return_id AND work_source_id IS NEW.work_source_id AND status NOT IN('cancelled','rejected')),0)+CASE WHEN NEW.work_source_id IS NULL THEN COALESCE((SELECT sum(w.quantity) FROM aftercare_work_events w WHERE w.return_id=NEW.return_id AND w.action='plan' AND NOT EXISTS(SELECT 1 FROM aftercare_work_events x WHERE x.source_id=w.id AND x.action='cancel_plan')),0) ELSE COALESCE((SELECT sum(quantity) FROM aftercare_work_events WHERE source_id=NEW.work_source_id),0) END>CASE WHEN NEW.work_source_id IS NULL THEN (SELECT return_quantity FROM aftercare_events WHERE id=NEW.return_id) ELSE (SELECT quantity FROM aftercare_work_events WHERE id=NEW.work_source_id) END THEN RAISE(ABORT,'aftercare disposition source quantity exceeded') END;
 SELECT CASE WHEN NEW.action='execute' AND (NEW.occurred_at<'2000-01-01T00:00:00.000Z' OR NEW.occurred_at>NEW.created_at OR NEW.occurred_at<(SELECT created_at FROM aftercare_disposition_events WHERE root_id=NEW.root_id AND action='approve') OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.occurred_at) IS NOT NEW.occurred_at) THEN RAISE(ABORT,'aftercare disposition receipt invalid') END;
END;
CREATE TRIGGER aftercare_work_disposition_gate BEFORE INSERT ON aftercare_work_events BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_events r WHERE r.id=NEW.return_id AND r.case_id=NEW.case_id AND r.action='receive_return') OR NEW.source_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM aftercare_work_events w WHERE w.id=NEW.source_id AND w.case_id=NEW.case_id AND w.return_id=NEW.return_id) THEN RAISE(ABORT,'aftercare work received source invalid') END;
 SELECT CASE WHEN NEW.created_at<COALESCE((SELECT max(created_at) FROM aftercare_disposition_events WHERE case_id=NEW.case_id),'') THEN RAISE(ABORT,'aftercare work disposition time invalid') END;
 SELECT CASE WHEN NEW.action='plan' AND NEW.quantity+COALESCE((SELECT sum(w.quantity) FROM aftercare_work_events w WHERE w.return_id=NEW.return_id AND w.action='plan' AND NOT EXISTS(SELECT 1 FROM aftercare_work_events x WHERE x.source_id=w.id AND x.action='cancel_plan')),0)+COALESCE((SELECT sum(quantity) FROM aftercare_disposition_latest WHERE return_id=NEW.return_id AND work_source_id IS NULL AND status NOT IN('cancelled','rejected')),0)>(SELECT return_quantity FROM aftercare_events WHERE id=NEW.return_id) THEN RAISE(ABORT,'aftercare work disposition quantity exceeded') END;
 SELECT CASE WHEN NEW.action='rework_plan' AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM aftercare_work_events WHERE source_id=NEW.source_id),0)+COALESCE((SELECT sum(quantity) FROM aftercare_disposition_latest WHERE return_id=NEW.return_id AND work_source_id IS NEW.source_id AND status NOT IN('cancelled','rejected')),0)>(SELECT quantity FROM aftercare_work_events WHERE id=NEW.source_id) THEN RAISE(ABORT,'aftercare work disposition quantity exceeded') END;
 SELECT CASE WHEN NEW.action='return' AND NEW.quantity+COALESCE((SELECT sum(quantity) FROM aftercare_work_events WHERE source_id=NEW.source_id),0)+COALESCE((SELECT sum(quantity) FROM aftercare_disposition_latest WHERE return_id=NEW.return_id AND work_source_id IS NEW.source_id AND status NOT IN('cancelled','rejected')),0)>(SELECT quantity FROM aftercare_work_events WHERE id=NEW.source_id) THEN RAISE(ABORT,'aftercare work disposition quantity exceeded') END;
END;
CREATE TRIGGER aftercare_work_disposition_capture AFTER INSERT ON aftercare_work_events BEGIN INSERT INTO aftercare_work_disposition_refs VALUES(NEW.id,NEW.case_id,COALESCE((SELECT max(sequence) FROM aftercare_disposition_events WHERE case_id=NEW.case_id),0));END;
CREATE TRIGGER aftercare_work_disposition_ref_ready BEFORE INSERT ON aftercare_work_disposition_refs BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM aftercare_work_events w WHERE w.id=NEW.work_event_id AND w.case_id=NEW.case_id) OR NEW.sequence<>COALESCE((SELECT max(sequence) FROM aftercare_disposition_events WHERE case_id=NEW.case_id),0) THEN RAISE(ABORT,'aftercare work disposition reference invalid') END;END;
CREATE TRIGGER aftercare_disposition_events_no_update BEFORE UPDATE ON aftercare_disposition_events BEGIN SELECT RAISE(ABORT,'aftercare disposition immutable');END;
CREATE TRIGGER aftercare_disposition_events_no_delete BEFORE DELETE ON aftercare_disposition_events BEGIN SELECT RAISE(ABORT,'aftercare disposition immutable');END;
CREATE TRIGGER aftercare_work_disposition_refs_no_update BEFORE UPDATE ON aftercare_work_disposition_refs BEGIN SELECT RAISE(ABORT,'aftercare disposition immutable');END;
CREATE TRIGGER aftercare_work_disposition_refs_no_delete BEFORE DELETE ON aftercare_work_disposition_refs BEGIN SELECT RAISE(ABORT,'aftercare disposition immutable');END;
