CREATE TABLE refund_events (
 id TEXT PRIMARY KEY,order_id TEXT NOT NULL,order_version INTEGER NOT NULL,customer_id TEXT NOT NULL,store_id TEXT NOT NULL,
 sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>=1),payment_revision INTEGER NOT NULL CHECK(typeof(payment_revision)='integer' AND payment_revision>=1),
 root_id TEXT NOT NULL REFERENCES refund_events(id),revision INTEGER NOT NULL CHECK(typeof(revision)='integer' AND revision>=1),action TEXT NOT NULL CHECK(action IN('create','approve','reject','cancel','execute')),status TEXT NOT NULL CHECK(status IN('pending','approved','rejected','cancelled','executed')),
 receipt_id TEXT NOT NULL REFERENCES payment_events(id),amount_cents INTEGER NOT NULL CHECK(typeof(amount_cents)='integer' AND amount_cents BETWEEN 1 AND 1000000000000),currency TEXT NOT NULL CHECK(currency='CNY'),
 case_id TEXT REFERENCES aftercare_cases(id),case_revision INTEGER,decision_basis TEXT NOT NULL CHECK(length(trim(decision_basis)) BETWEEN 1 AND 1000),
 method TEXT,reference TEXT,receiver_name TEXT,refunded_at TEXT,receipt_note TEXT,
 note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL CHECK(length(created_at)=24 AND strftime('%Y-%m-%dT%H:%M:%fZ',created_at) IS created_at),created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(order_id,sequence),UNIQUE(root_id,revision),FOREIGN KEY(order_id,order_version,customer_id,store_id) REFERENCES retail_order_versions(order_id,version,customer_id,store_id),FOREIGN KEY(case_id,case_revision) REFERENCES aftercare_events(case_id,revision),
 CHECK((case_id IS NULL AND case_revision IS NULL) OR (case_id IS NOT NULL AND case_revision IS NOT NULL)),
 CHECK(status=CASE action WHEN 'create' THEN 'pending' WHEN 'approve' THEN 'approved' WHEN 'reject' THEN 'rejected' WHEN 'cancel' THEN 'cancelled' ELSE 'executed' END),
 CHECK((action='create' AND root_id=id AND revision=1) OR (action<>'create' AND root_id<>id AND revision>1)),
 CHECK((action='execute' AND method IS NOT NULL AND method IN('cash','card','transfer','other') AND reference IS NOT NULL AND length(trim(reference)) BETWEEN 1 AND 120 AND receiver_name IS NOT NULL AND length(trim(receiver_name)) BETWEEN 1 AND 120 AND refunded_at IS NOT NULL AND receipt_note IS NOT NULL AND length(trim(receipt_note)) BETWEEN 1 AND 1000) OR (action<>'execute' AND method IS NULL AND reference IS NULL AND receiver_name IS NULL AND refunded_at IS NULL AND receipt_note IS NULL))
);
CREATE INDEX refund_source ON refund_events(receipt_id,sequence);
CREATE UNIQUE INDEX refund_actual_reference ON refund_events(store_id,method,reference) WHERE action='execute';
CREATE VIEW refund_latest AS SELECT e.* FROM refund_events e WHERE e.revision=(SELECT max(revision) FROM refund_events WHERE root_id=e.root_id);
CREATE TABLE payment_refund_refs(payment_event_id TEXT PRIMARY KEY REFERENCES payment_events(id),order_id TEXT NOT NULL REFERENCES retail_orders(id),sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>=0));
INSERT INTO payment_refund_refs SELECT id,order_id,0 FROM payment_events;
CREATE TRIGGER refund_ready BEFORE INSERT ON refund_events BEGIN
 SELECT CASE WHEN NEW.sequence<>COALESCE((SELECT max(sequence)+1 FROM refund_events WHERE order_id=NEW.order_id),1) OR NEW.revision<>COALESCE((SELECT max(revision)+1 FROM refund_events WHERE root_id=NEW.root_id),1) OR NEW.payment_revision IS NOT (SELECT max(revision) FROM payment_events WHERE order_id=NEW.order_id) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM refund_events WHERE order_id=NEW.order_id),'') OR NEW.created_at<(SELECT max(created_at) FROM payment_events WHERE order_id=NEW.order_id) THEN RAISE(ABORT,'refund versions invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND COALESCE(s.must_change_password,0)=0 AND (u.role='manager' OR u.role='reception' AND NEW.action IN('create','cancel','execute'))) THEN RAISE(ABORT,'refund actor not allowed') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM retail_order_versions v JOIN payment_events p ON p.id=NEW.receipt_id WHERE v.order_id=NEW.order_id AND v.version=NEW.order_version AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=v.order_id) AND v.status='draft' AND p.order_id=v.order_id AND p.order_version=v.version AND p.customer_id=NEW.customer_id AND p.store_id=NEW.store_id AND p.action='receive' AND p.currency=NEW.currency AND NOT EXISTS(SELECT 1 FROM payment_events x WHERE x.source_id=p.id) AND NEW.created_at>=p.created_at) THEN RAISE(ABORT,'refund original receipt invalid') END;
 SELECT CASE WHEN NEW.case_id IS NOT NULL AND (NEW.case_revision IS NOT (SELECT max(revision) FROM aftercare_events WHERE case_id=NEW.case_id) OR NOT EXISTS(SELECT 1 FROM aftercare_cases c JOIN fulfillment_events d ON d.id=c.delivery_id JOIN processing_jobs j ON j.id=d.job_id JOIN aftercare_events e ON e.case_id=c.id AND e.revision=NEW.case_revision WHERE c.id=NEW.case_id AND c.customer_id=NEW.customer_id AND c.store_id=NEW.store_id AND NEW.created_at>=e.created_at AND (j.order_id=NEW.order_id OR EXISTS(SELECT 1 FROM aftercare_replacements r WHERE r.case_id=c.id AND r.new_order_id=NEW.order_id AND r.new_order_version=NEW.order_version)))) THEN RAISE(ABORT,'refund aftercare source invalid') END;
 SELECT CASE WHEN NEW.action='create' AND NEW.amount_cents+COALESCE((SELECT sum(amount_cents) FROM refund_latest WHERE receipt_id=NEW.receipt_id AND status NOT IN('cancelled','rejected')),0)>(SELECT amount_cents FROM payment_events WHERE id=NEW.receipt_id) THEN RAISE(ABORT,'refund original receipt amount exceeded') END;
 SELECT CASE WHEN NEW.action<>'create' AND NOT EXISTS(SELECT 1 FROM refund_events r JOIN refund_latest l ON l.root_id=r.id WHERE r.id=NEW.root_id AND r.action='create' AND r.order_id=NEW.order_id AND r.order_version=NEW.order_version AND r.customer_id=NEW.customer_id AND r.store_id=NEW.store_id AND r.receipt_id=NEW.receipt_id AND r.amount_cents=NEW.amount_cents AND r.currency=NEW.currency AND r.case_id IS NEW.case_id AND r.decision_basis=NEW.decision_basis AND (NEW.action IN('approve','reject') AND l.status='pending' OR NEW.action='cancel' AND l.status IN('pending','approved') OR NEW.action='execute' AND l.status='approved')) THEN RAISE(ABORT,'refund immutable source or transition invalid') END;
 SELECT CASE WHEN NEW.action='execute' AND (NEW.refunded_at<'2000-01-01T00:00:00.000Z' OR NEW.refunded_at>NEW.created_at OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.refunded_at) IS NOT NEW.refunded_at OR NEW.refunded_at<(SELECT received_at FROM payment_events WHERE id=NEW.receipt_id) OR NEW.refunded_at<(SELECT created_at FROM refund_events WHERE root_id=NEW.root_id AND action='approve')) THEN RAISE(ABORT,'refund actual receipt invalid') END;
END;
CREATE TRIGGER payment_refund_gate BEFORE INSERT ON payment_events BEGIN
 SELECT CASE WHEN NEW.created_at<COALESCE((SELECT max(created_at) FROM refund_events WHERE order_id=NEW.order_id),'') THEN RAISE(ABORT,'payment refund time invalid') END;
 SELECT CASE WHEN NEW.action='void' AND EXISTS(SELECT 1 FROM refund_latest WHERE receipt_id=NEW.source_id AND status NOT IN('cancelled','rejected')) THEN RAISE(ABORT,'refund protects original receipt') END;
END;
CREATE TRIGGER payment_refund_capture AFTER INSERT ON payment_events BEGIN INSERT INTO payment_refund_refs VALUES(NEW.id,NEW.order_id,COALESCE((SELECT max(sequence) FROM refund_events WHERE order_id=NEW.order_id),0));END;
CREATE TRIGGER payment_refund_ref_ready BEFORE INSERT ON payment_refund_refs BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM payment_events p WHERE p.id=NEW.payment_event_id AND p.order_id=NEW.order_id) OR NEW.sequence<>COALESCE((SELECT max(sequence) FROM refund_events WHERE order_id=NEW.order_id),0) THEN RAISE(ABORT,'payment refund reference invalid') END;END;
CREATE TRIGGER refund_no_update BEFORE UPDATE ON refund_events BEGIN SELECT RAISE(ABORT,'refund immutable');END;
CREATE TRIGGER refund_no_delete BEFORE DELETE ON refund_events BEGIN SELECT RAISE(ABORT,'refund immutable');END;
CREATE TRIGGER payment_refund_refs_no_update BEFORE UPDATE ON payment_refund_refs BEGIN SELECT RAISE(ABORT,'refund references immutable');END;
CREATE TRIGGER payment_refund_refs_no_delete BEFORE DELETE ON payment_refund_refs BEGIN SELECT RAISE(ABORT,'refund references immutable');END;
