CREATE TABLE parameter_versions(
 id TEXT PRIMARY KEY,order_id TEXT NOT NULL,order_version INTEGER NOT NULL,customer_id TEXT NOT NULL,store_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1),source TEXT NOT NULL CHECK(source IN('staff_record','external_transcript','customer_transcript')),source_note TEXT NOT NULL CHECK(length(trim(source_note)) BETWEEN 1 AND 1000),manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),
 UNIQUE(order_id,version),FOREIGN KEY(order_id,order_version,customer_id,store_id) REFERENCES retail_order_versions(order_id,version,customer_id,store_id));
CREATE TABLE parameter_documents(version_id TEXT NOT NULL REFERENCES parameter_versions(id),document_version_id TEXT NOT NULL REFERENCES document_versions(id),PRIMARY KEY(version_id,document_version_id));
CREATE TABLE parameter_attachments(version_id TEXT NOT NULL REFERENCES parameter_versions(id),attachment_id TEXT NOT NULL REFERENCES attachments(id),PRIMARY KEY(version_id,attachment_id));
CREATE TABLE parameter_events(id TEXT PRIMARY KEY,version_id TEXT NOT NULL REFERENCES parameter_versions(id),order_id TEXT NOT NULL REFERENCES retail_orders(id),sequence INTEGER NOT NULL CHECK(sequence>=1),revision INTEGER NOT NULL CHECK(revision>=1),action TEXT NOT NULL CHECK(action IN('create','submit','check','return')),status TEXT NOT NULL CHECK(status IN('draft','submitted','checked','returned')),execution_basis_json TEXT NOT NULL CHECK(json_valid(execution_basis_json)),note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(order_id,sequence),UNIQUE(version_id,revision));
CREATE VIEW parameter_current AS SELECT v.*,e.status,e.sequence,e.revision,e.created_at event_created_at FROM parameter_versions v JOIN parameter_events e ON e.version_id=v.id AND e.revision=(SELECT max(revision) FROM parameter_events WHERE version_id=v.id) WHERE v.version=(SELECT max(version) FROM parameter_versions WHERE order_id=v.order_id AND order_version=v.order_version);
CREATE VIEW parameter_execution_basis AS SELECT o.id order_id,COALESCE((SELECT json_group_array(json_object('job_id',x.id,'processing_revision',x.p,'fulfillment_revision',x.f)) FROM (SELECT j.id,COALESCE((SELECT max(revision) FROM processing_events WHERE job_id=j.id),0) p,COALESCE((SELECT max(revision) FROM fulfillment_events WHERE job_id=j.id),0) f FROM processing_jobs j WHERE j.order_id=o.id ORDER BY j.serial) x),'[]') basis_json FROM retail_orders o;
CREATE TABLE parameter_reviews(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES processing_jobs(id),revision INTEGER NOT NULL CHECK(revision>=1),fixed_version_id TEXT REFERENCES parameter_versions(id),current_version_id TEXT NOT NULL REFERENCES parameter_versions(id),parameter_sequence INTEGER NOT NULL CHECK(parameter_sequence>=1),processing_revision INTEGER NOT NULL,fulfillment_revision INTEGER NOT NULL,outcome TEXT NOT NULL CHECK(outcome IN('continue_original','hold')),note TEXT NOT NULL CHECK(length(trim(note)) BETWEEN 1 AND 1000),reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 300),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(job_id,revision));
CREATE TABLE parameter_execution_refs(event_id TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN('processing','fulfillment')),job_id TEXT NOT NULL REFERENCES processing_jobs(id),processing_event_id TEXT UNIQUE REFERENCES processing_events(id),fulfillment_event_id TEXT UNIQUE REFERENCES fulfillment_events(id),parameter_sequence INTEGER NOT NULL CHECK(parameter_sequence>=0),current_version_id TEXT REFERENCES parameter_versions(id),fixed_version_id TEXT REFERENCES parameter_versions(id),review_id TEXT REFERENCES parameter_reviews(id),basis TEXT NOT NULL CHECK(basis IN('legacy','not_recorded','captured')),recorded_at TEXT NOT NULL,CHECK((kind='processing' AND event_id=processing_event_id AND fulfillment_event_id IS NULL) OR (kind='fulfillment' AND event_id=fulfillment_event_id AND processing_event_id IS NULL)));
INSERT INTO parameter_execution_refs SELECT id,'processing',job_id,id,NULL,0,NULL,NULL,NULL,'legacy',created_at FROM processing_events WHERE action IN('start','complete');
INSERT INTO parameter_execution_refs SELECT id,'fulfillment',job_id,NULL,id,0,NULL,NULL,NULL,'legacy',created_at FROM fulfillment_events;
CREATE VIEW parameter_job_context AS SELECT j.id job_id,j.order_id,j.order_version,c.id current_version_id,c.status current_status,COALESCE((SELECT max(sequence) FROM parameter_events WHERE order_id=j.order_id),0) sequence,
 (SELECT r.fixed_version_id FROM parameter_execution_refs r JOIN processing_events p ON p.id=r.processing_event_id WHERE p.job_id=j.id AND p.action='start' ORDER BY p.revision LIMIT 1) fixed_version_id,
 EXISTS(SELECT 1 FROM processing_events WHERE job_id=j.id AND action='start') has_started,
 COALESCE((SELECT r.basis FROM parameter_execution_refs r JOIN processing_events p ON p.id=r.processing_event_id WHERE p.job_id=j.id AND p.action='start' ORDER BY p.revision LIMIT 1),'not_recorded') basis,
 COALESCE((SELECT max(revision) FROM parameter_reviews WHERE job_id=j.id),0) review_revision,
 (SELECT id FROM parameter_reviews WHERE job_id=j.id ORDER BY revision DESC LIMIT 1) review_id,
 CASE WHEN c.id IS NULL THEN 1 WHEN c.status<>'checked' OR EXISTS(SELECT 1 FROM parameter_attachments a JOIN attachments x ON x.id=a.attachment_id WHERE a.version_id=c.id AND x.revoked_at IS NOT NULL) THEN 0
 WHEN NOT EXISTS(SELECT 1 FROM processing_events WHERE job_id=j.id AND action='start') THEN 1
 WHEN EXISTS(SELECT 1 FROM parameter_reviews r WHERE r.job_id=j.id AND r.revision=(SELECT max(revision) FROM parameter_reviews WHERE job_id=j.id) AND r.current_version_id=c.id AND r.parameter_sequence=(SELECT max(sequence) FROM parameter_events WHERE order_id=j.order_id) AND r.outcome='hold') THEN 0
 WHEN c.id IS (SELECT r.fixed_version_id FROM parameter_execution_refs r JOIN processing_events p ON p.id=r.processing_event_id WHERE p.job_id=j.id AND p.action='start' ORDER BY p.revision LIMIT 1) THEN 1
 WHEN EXISTS(SELECT 1 FROM parameter_reviews r WHERE r.job_id=j.id AND r.revision=(SELECT max(revision) FROM parameter_reviews WHERE job_id=j.id) AND r.current_version_id=c.id AND r.fixed_version_id IS (SELECT x.fixed_version_id FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=j.id AND p.action='start' ORDER BY p.revision LIMIT 1) AND r.parameter_sequence=(SELECT max(sequence) FROM parameter_events WHERE order_id=j.order_id) AND r.outcome='continue_original') THEN 1 ELSE 0 END can_execute
 FROM processing_jobs j LEFT JOIN parameter_current c ON c.order_id=j.order_id AND c.order_version=j.order_version;
CREATE TRIGGER parameter_version_ready BEFORE INSERT ON parameter_versions BEGIN
 SELECT CASE WHEN NEW.version<>COALESCE((SELECT max(version)+1 FROM parameter_versions WHERE order_id=NEW.order_id),1) OR NOT EXISTS(SELECT 1 FROM retail_order_versions v JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE v.order_id=NEW.order_id AND v.version=NEW.order_version AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=v.order_id) AND v.status='draft' AND v.customer_id=NEW.customer_id AND v.store_id=NEW.store_id AND u.active=1 AND u.store_id=v.store_id AND u.role IN('manager','reception','professional') AND COALESCE(s.must_change_password,0)=0 AND NEW.created_at>=v.created_at) OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR length(NEW.created_at)<>24 THEN RAISE(ABORT,'parameter original version invalid') END;
 SELECT CASE WHEN NEW.created_at<COALESCE((SELECT max(created_at) FROM parameter_events WHERE order_id=NEW.order_id),'') OR EXISTS(SELECT 1 FROM parameter_versions v WHERE v.order_id=NEW.order_id AND NOT EXISTS(SELECT 1 FROM parameter_events e WHERE e.version_id=v.id)) THEN RAISE(ABORT,'parameter history incomplete') END;
 SELECT CASE WHEN json_type(NEW.manifest_json,'$.values') IS NOT 'array' OR json_type(NEW.manifest_json,'$.document_version_ids') IS NOT 'array' OR json_type(NEW.manifest_json,'$.attachment_ids') IS NOT 'array' OR (SELECT count(*) FROM json_each(NEW.manifest_json))<>3 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.values') x WHERE (SELECT count(*) FROM json_each(x.value))<>5 OR json_type(x.value,'$.label') IS NOT 'text' OR json_type(x.value,'$.value') IS NOT 'text' OR json_type(x.value,'$.unit') NOT IN('text','null') OR json_type(x.value,'$.condition') NOT IN('text','null') OR length(json_extract(x.value,'$.unit'))>32 OR length(json_extract(x.value,'$.condition'))>120) OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.values') x GROUP BY json_extract(x.value,'$.position'),lower(json_extract(x.value,'$.label')) HAVING count(*)>1) THEN RAISE(ABORT,'parameter manifest invalid') END;
 SELECT CASE WHEN json_array_length(NEW.manifest_json,'$.values') NOT BETWEEN 1 AND 100 OR json_array_length(NEW.manifest_json,'$.document_version_ids')>10 OR json_array_length(NEW.manifest_json,'$.attachment_ids')>10 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.values') x WHERE json_type(x.value,'$.position') IS NOT 'integer' OR length(trim(json_extract(x.value,'$.label'))) NOT BETWEEN 1 AND 80 OR length(trim(json_extract(x.value,'$.value'))) NOT BETWEEN 1 AND 160 OR NOT EXISTS(SELECT 1 FROM retail_order_items i JOIN retail_product_versions p ON p.product_id=i.product_id AND p.version=i.product_version WHERE i.order_id=NEW.order_id AND i.version=NEW.order_version AND i.position=json_extract(x.value,'$.position') AND p.category<>'service')) THEN RAISE(ABORT,'parameter fields invalid') END;
END;
CREATE TRIGGER parameter_document_ready BEFORE INSERT ON parameter_documents BEGIN SELECT CASE WHEN EXISTS(SELECT 1 FROM parameter_events WHERE version_id=NEW.version_id) OR NOT EXISTS(SELECT 1 FROM parameter_versions v JOIN document_versions d ON d.id=NEW.document_version_id JOIN json_each(v.manifest_json,'$.document_version_ids') x ON x.value=d.id WHERE v.id=NEW.version_id AND d.customer_id=v.customer_id) THEN RAISE(ABORT,'parameter document invalid') END;END;
CREATE TRIGGER parameter_attachment_ready BEFORE INSERT ON parameter_attachments BEGIN SELECT CASE WHEN EXISTS(SELECT 1 FROM parameter_events WHERE version_id=NEW.version_id) OR NOT EXISTS(SELECT 1 FROM parameter_versions v JOIN attachments a ON a.id=NEW.attachment_id JOIN json_each(v.manifest_json,'$.attachment_ids') x ON x.value=a.id WHERE v.id=NEW.version_id AND a.customer_id=v.customer_id AND a.revoked_at IS NULL) THEN RAISE(ABORT,'parameter attachment invalid') END;END;
CREATE TRIGGER parameter_event_ready BEFORE INSERT ON parameter_events BEGIN
 SELECT CASE WHEN NEW.sequence<>COALESCE((SELECT max(sequence)+1 FROM parameter_events WHERE order_id=NEW.order_id),1) OR NEW.revision<>COALESCE((SELECT max(revision)+1 FROM parameter_events WHERE version_id=NEW.version_id),1) OR EXISTS(SELECT 1 FROM processing_jobs j WHERE j.order_id=NEW.order_id AND (NEW.created_at<(SELECT max(created_at) FROM processing_events WHERE job_id=j.id) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM fulfillment_events WHERE job_id=j.id),''))) OR NEW.execution_basis_json IS NOT (SELECT basis_json FROM parameter_execution_basis WHERE order_id=NEW.order_id) OR NOT EXISTS(SELECT 1 FROM parameter_versions v WHERE v.id=NEW.version_id AND v.order_id=NEW.order_id AND v.version=(SELECT max(version) FROM parameter_versions WHERE order_id=v.order_id) AND v.order_version=(SELECT max(version) FROM retail_order_versions WHERE order_id=v.order_id) AND NEW.created_at>=v.created_at) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM parameter_events WHERE order_id=NEW.order_id),'') OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR length(NEW.created_at)<>24 THEN RAISE(ABORT,'parameter event versions invalid') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM users u JOIN parameter_versions v ON v.id=NEW.version_id LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=v.store_id AND COALESCE(s.must_change_password,0)=0 AND (NEW.action IN('check','return') AND u.role='professional' OR NEW.action IN('create','submit') AND u.role IN('manager','reception','professional'))) THEN RAISE(ABORT,'parameter actor invalid') END;
 SELECT CASE WHEN NOT(NEW.action='create' AND NEW.revision=1 AND NEW.status='draft' AND (SELECT count(*) FROM parameter_documents WHERE version_id=NEW.version_id)=json_array_length((SELECT manifest_json FROM parameter_versions WHERE id=NEW.version_id),'$.document_version_ids') AND (SELECT count(*) FROM parameter_attachments WHERE version_id=NEW.version_id)=json_array_length((SELECT manifest_json FROM parameter_versions WHERE id=NEW.version_id),'$.attachment_ids') OR NEW.action='submit' AND NEW.status='submitted' AND (SELECT status FROM parameter_events WHERE version_id=NEW.version_id ORDER BY revision DESC LIMIT 1) IN('draft','returned') OR NEW.action IN('check','return') AND NEW.status=CASE NEW.action WHEN 'check' THEN 'checked' ELSE 'returned' END AND (SELECT status FROM parameter_events WHERE version_id=NEW.version_id ORDER BY revision DESC LIMIT 1)='submitted') THEN RAISE(ABORT,'parameter transition invalid') END;
 SELECT CASE WHEN NEW.action IN('submit','check') AND EXISTS(SELECT 1 FROM parameter_attachments a JOIN attachments x ON x.id=a.attachment_id WHERE a.version_id=NEW.version_id AND x.revoked_at IS NOT NULL) THEN RAISE(ABORT,'parameter source revoked') END;
END;
CREATE TRIGGER parameter_review_ready BEFORE INSERT ON parameter_reviews BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM parameter_job_context c JOIN parameter_versions v ON v.id=c.current_version_id JOIN users u ON u.id=NEW.created_by LEFT JOIN user_security s ON s.user_id=u.id WHERE c.job_id=NEW.job_id AND c.has_started=1 AND c.current_version_id=NEW.current_version_id AND c.current_status='checked' AND c.fixed_version_id IS NEW.fixed_version_id AND c.sequence=NEW.parameter_sequence AND u.active=1 AND u.role='professional' AND u.store_id=v.store_id AND COALESCE(s.must_change_password,0)=0) OR NEW.revision<>COALESCE((SELECT max(revision)+1 FROM parameter_reviews WHERE job_id=NEW.job_id),1) OR NEW.processing_revision IS NOT (SELECT max(revision) FROM processing_events WHERE job_id=NEW.job_id) OR NEW.fulfillment_revision<>COALESCE((SELECT max(revision) FROM fulfillment_events WHERE job_id=NEW.job_id),0) OR NEW.created_at<(SELECT max(created_at) FROM processing_events WHERE job_id=NEW.job_id) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM fulfillment_events WHERE job_id=NEW.job_id),'') OR NEW.created_at<(SELECT max(created_at) FROM parameter_events WHERE order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id)) OR NEW.created_at<COALESCE((SELECT max(created_at) FROM parameter_reviews WHERE job_id=NEW.job_id),'') OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR length(NEW.created_at)<>24 THEN RAISE(ABORT,'parameter review source or actor invalid') END;
END;
CREATE TRIGGER processing_parameter_gate BEFORE INSERT ON processing_events WHEN NEW.action IN('start','complete') BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM parameter_job_context WHERE job_id=NEW.job_id AND can_execute=1) THEN RAISE(ABORT,'parameter review required') END;END;
CREATE TRIGGER fulfillment_parameter_gate BEFORE INSERT ON fulfillment_events BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM parameter_job_context WHERE job_id=NEW.job_id AND can_execute=1) THEN RAISE(ABORT,'parameter review required') END;END;
CREATE TRIGGER processing_parameter_capture AFTER INSERT ON processing_events WHEN NEW.action IN('start','complete') BEGIN INSERT INTO parameter_execution_refs SELECT NEW.id,'processing',NEW.job_id,NEW.id,NULL,c.sequence,c.current_version_id,CASE WHEN c.has_started=1 AND EXISTS(SELECT 1 FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=NEW.job_id AND p.action='start') THEN c.fixed_version_id ELSE c.current_version_id END,CASE WHEN c.has_started=1 THEN c.review_id ELSE NULL END,CASE WHEN EXISTS(SELECT 1 FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=NEW.job_id AND p.action='start') THEN c.basis WHEN c.current_version_id IS NOT NULL THEN 'captured' ELSE 'not_recorded' END,NEW.created_at FROM parameter_job_context c WHERE c.job_id=NEW.job_id;END;
CREATE TRIGGER fulfillment_parameter_capture AFTER INSERT ON fulfillment_events  BEGIN INSERT INTO parameter_execution_refs SELECT NEW.id,'fulfillment',NEW.job_id,NULL,NEW.id,c.sequence,c.current_version_id,CASE WHEN c.has_started=1 AND EXISTS(SELECT 1 FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=NEW.job_id AND p.action='start') THEN c.fixed_version_id ELSE c.current_version_id END,CASE WHEN c.has_started=1 THEN c.review_id ELSE NULL END,CASE WHEN EXISTS(SELECT 1 FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=NEW.job_id AND p.action='start') THEN c.basis WHEN c.current_version_id IS NOT NULL THEN 'captured' ELSE 'not_recorded' END,NEW.created_at FROM parameter_job_context c WHERE c.job_id=NEW.job_id;END;
CREATE TRIGGER parameter_versions_no_update BEFORE UPDATE ON parameter_versions BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_versions_no_delete BEFORE DELETE ON parameter_versions BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_documents_no_update BEFORE UPDATE ON parameter_documents BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_documents_no_delete BEFORE DELETE ON parameter_documents BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_attachments_no_update BEFORE UPDATE ON parameter_attachments BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_attachments_no_delete BEFORE DELETE ON parameter_attachments BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_events_no_update BEFORE UPDATE ON parameter_events BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_events_no_delete BEFORE DELETE ON parameter_events BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_reviews_no_update BEFORE UPDATE ON parameter_reviews BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_reviews_no_delete BEFORE DELETE ON parameter_reviews BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_execution_refs_no_update BEFORE UPDATE ON parameter_execution_refs BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_execution_refs_no_delete BEFORE DELETE ON parameter_execution_refs BEGIN SELECT RAISE(ABORT,'parameter immutable');END;
CREATE TRIGGER parameter_execution_ref_ready BEFORE INSERT ON parameter_execution_refs BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM parameter_job_context c WHERE c.job_id=NEW.job_id AND c.sequence=NEW.parameter_sequence AND c.current_version_id IS NEW.current_version_id AND NEW.fixed_version_id IS CASE WHEN EXISTS(SELECT 1 FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=NEW.job_id AND p.action='start') THEN c.fixed_version_id ELSE c.current_version_id END AND NEW.basis=CASE WHEN EXISTS(SELECT 1 FROM parameter_execution_refs x JOIN processing_events p ON p.id=x.processing_event_id WHERE p.job_id=NEW.job_id AND p.action='start') THEN c.basis WHEN c.current_version_id IS NOT NULL THEN 'captured' ELSE 'not_recorded' END AND NEW.review_id IS c.review_id)
 OR NOT(NEW.kind='processing' AND EXISTS(SELECT 1 FROM processing_events p WHERE p.id=NEW.event_id AND p.id=NEW.processing_event_id AND p.job_id=NEW.job_id AND p.action IN('start','complete') AND p.created_at=NEW.recorded_at) OR NEW.kind='fulfillment' AND EXISTS(SELECT 1 FROM fulfillment_events f WHERE f.id=NEW.event_id AND f.id=NEW.fulfillment_event_id AND f.job_id=NEW.job_id AND f.created_at=NEW.recorded_at)) THEN RAISE(ABORT,'parameter execution reference invalid') END;
 SELECT CASE WHEN NEW.recorded_at<COALESCE((SELECT max(created_at) FROM parameter_events WHERE order_id=(SELECT order_id FROM processing_jobs WHERE id=NEW.job_id)),'') OR NEW.recorded_at<COALESCE((SELECT created_at FROM parameter_reviews WHERE id=NEW.review_id),'') THEN RAISE(ABORT,'parameter execution time invalid') END;
END;
