CREATE TABLE contact_consents(id TEXT PRIMARY KEY,store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL,category TEXT NOT NULL CHECK(category IN('service','marketing')),channel TEXT NOT NULL CHECK(channel IN('phone','sms','wechat','email','in_person')),recipient_label TEXT NOT NULL,address TEXT NOT NULL,source_note TEXT NOT NULL,effective_at TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,store_id,customer_id),FOREIGN KEY(customer_id,store_id) REFERENCES customers(id,store_id));

CREATE TABLE contact_consent_events(id TEXT PRIMARY KEY,consent_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL,sequence INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('grant','revoke')),status TEXT NOT NULL CHECK(status IN('active','revoked')),note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(consent_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(consent_id,store_id,customer_id) REFERENCES contact_consents(id,store_id,customer_id),UNIQUE(consent_id,revision,store_id,customer_id));

CREATE TABLE contact_cases(id TEXT PRIMARY KEY,store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL,purpose TEXT NOT NULL CHECK(purpose IN('followup','pickup','training','other_service','marketing')),category TEXT NOT NULL CHECK(category IN('service','marketing')),source_json TEXT NOT NULL CHECK(json_valid(source_json)),cycle_id TEXT,cycle_version INTEGER,source_note TEXT NOT NULL,serial INTEGER NOT NULL,case_number TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,store_id,customer_id),UNIQUE(store_id,serial),FOREIGN KEY(customer_id,store_id) REFERENCES customers(id,store_id),FOREIGN KEY(cycle_id,cycle_version) REFERENCES cycle_versions(cycle_id,version),CHECK((cycle_id IS NULL AND cycle_version IS NULL) OR(cycle_id IS NOT NULL AND cycle_version IS NOT NULL)));

CREATE TABLE contact_case_events(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL,sequence INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('create','revise','assign','retry','defer','attempt','failed','resolve','cancel')),status TEXT NOT NULL CHECK(status IN('open','waiting','handoff','resolved','cancelled')),owner_id TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,purpose_note TEXT NOT NULL,due_at TEXT NOT NULL,next_action TEXT NOT NULL,attempt_id TEXT REFERENCES contact_attempts(id),resolution_reason TEXT,next_step TEXT,followup_task_id TEXT REFERENCES work_tasks(id),followup_revision INTEGER,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES contact_cases(id,store_id,customer_id),CHECK((followup_task_id IS NULL AND followup_revision IS NULL) OR(followup_task_id IS NOT NULL AND followup_revision IS NOT NULL)),CHECK((status IN('resolved','cancelled') AND resolution_reason IS NOT NULL AND next_step IS NOT NULL) OR(status NOT IN('resolved','cancelled') AND resolution_reason IS NULL AND next_step IS NULL AND followup_task_id IS NULL AND followup_revision IS NULL)));

CREATE TABLE contact_attempts(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,case_revision INTEGER NOT NULL,sequence INTEGER NOT NULL,consent_id TEXT NOT NULL,consent_revision INTEGER NOT NULL,occurred_at TEXT NOT NULL,result TEXT NOT NULL CHECK(result IN('attempted','sent','failed','no_answer','invalid_address','refused','connected')),source_note TEXT NOT NULL,content_summary TEXT NOT NULL,result_note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,case_id,store_id,customer_id),UNIQUE(store_id,sequence),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES contact_cases(id,store_id,customer_id),FOREIGN KEY(case_id,case_revision) REFERENCES contact_case_events(case_id,revision),FOREIGN KEY(consent_id,consent_revision,store_id,customer_id) REFERENCES contact_consent_events(consent_id,revision,store_id,customer_id));

CREATE TABLE contact_receipts(id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,case_revision INTEGER NOT NULL,revision INTEGER NOT NULL,sequence INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN('delivered','read','not_read','unknown','channel_failed')),source TEXT NOT NULL CHECK(source IN('staff_transcript','provider_transcript')),occurred_at TEXT NOT NULL,source_note TEXT NOT NULL,result_note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(attempt_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(attempt_id,case_id,store_id,customer_id) REFERENCES contact_attempts(id,case_id,store_id,customer_id),FOREIGN KEY(case_id,case_revision) REFERENCES contact_case_events(case_id,revision));

CREATE TABLE customer_appointments(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,cycle_id TEXT,cycle_version INTEGER,serial INTEGER NOT NULL,appointment_number TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,case_id,store_id,customer_id),UNIQUE(store_id,serial),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES contact_cases(id,store_id,customer_id),FOREIGN KEY(cycle_id,cycle_version) REFERENCES cycle_versions(cycle_id,version),CHECK((cycle_id IS NULL AND cycle_version IS NULL) OR(cycle_id IS NOT NULL AND cycle_version IS NOT NULL)));

CREATE TABLE customer_appointment_events(id TEXT PRIMARY KEY,appointment_id TEXT NOT NULL,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL,sequence INTEGER NOT NULL,case_revision INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('create','reschedule','assign','cancel','no_show','arrive')),status TEXT NOT NULL CHECK(status IN('planned','cancelled','missed','arrived')),owner_id TEXT NOT NULL REFERENCES users(id),starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,purpose_note TEXT NOT NULL,place_note TEXT NOT NULL,source_note TEXT NOT NULL,visit_id TEXT REFERENCES visits(id),arrived_at TEXT,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(appointment_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(appointment_id,case_id,store_id,customer_id) REFERENCES customer_appointments(id,case_id,store_id,customer_id),FOREIGN KEY(case_id,case_revision) REFERENCES contact_case_events(case_id,revision),CHECK((status='arrived' AND visit_id IS NOT NULL AND arrived_at IS NOT NULL) OR(status!='arrived' AND visit_id IS NULL AND arrived_at IS NULL)));

CREATE VIEW contact_journal AS SELECT store_id,sequence,created_at,'consent' kind,consent_id root_id,id FROM contact_consent_events UNION ALL SELECT store_id,sequence,created_at,'case',case_id,id FROM contact_case_events UNION ALL SELECT store_id,sequence,created_at,'attempt',case_id,id FROM contact_attempts UNION ALL SELECT store_id,sequence,created_at,'receipt',attempt_id,id FROM contact_receipts UNION ALL SELECT store_id,sequence,created_at,'appointment',appointment_id,id FROM customer_appointment_events;

CREATE VIEW contact_consent_current AS SELECT * FROM contact_consent_events e WHERE revision=(SELECT max(revision) FROM contact_consent_events WHERE consent_id=e.consent_id);

CREATE VIEW contact_case_current AS SELECT * FROM contact_case_events e WHERE revision=(SELECT max(revision) FROM contact_case_events WHERE case_id=e.case_id);

CREATE VIEW customer_appointment_current AS SELECT * FROM customer_appointment_events e WHERE revision=(SELECT max(revision) FROM customer_appointment_events WHERE appointment_id=e.appointment_id);

CREATE TRIGGER contact_consents_no_update BEFORE UPDATE ON contact_consents BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_consents_no_delete BEFORE DELETE ON contact_consents BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_consents_actor BEFORE INSERT ON contact_consents WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER contact_consent_events_no_update BEFORE UPDATE ON contact_consent_events BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_consent_events_no_delete BEFORE DELETE ON contact_consent_events BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_consent_events_actor BEFORE INSERT ON contact_consent_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER contact_consent_events_sequence BEFORE INSERT ON contact_consent_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM contact_journal WHERE store_id=NEW.store_id) OR NEW.created_at<coalesce((SELECT max(created_at) FROM contact_journal WHERE store_id=NEW.store_id),NEW.created_at) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) BEGIN SELECT RAISE(ABORT,'contact journal mismatch'); END;

CREATE TRIGGER contact_cases_no_update BEFORE UPDATE ON contact_cases BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_cases_no_delete BEFORE DELETE ON contact_cases BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_cases_actor BEFORE INSERT ON contact_cases WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER contact_case_events_no_update BEFORE UPDATE ON contact_case_events BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_case_events_no_delete BEFORE DELETE ON contact_case_events BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_case_events_actor BEFORE INSERT ON contact_case_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER contact_case_events_sequence BEFORE INSERT ON contact_case_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM contact_journal WHERE store_id=NEW.store_id) OR NEW.created_at<coalesce((SELECT max(created_at) FROM contact_journal WHERE store_id=NEW.store_id),NEW.created_at) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) BEGIN SELECT RAISE(ABORT,'contact journal mismatch'); END;

CREATE TRIGGER contact_attempts_no_update BEFORE UPDATE ON contact_attempts BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_attempts_no_delete BEFORE DELETE ON contact_attempts BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_attempts_actor BEFORE INSERT ON contact_attempts WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER contact_attempts_sequence BEFORE INSERT ON contact_attempts WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM contact_journal WHERE store_id=NEW.store_id) OR NEW.created_at<coalesce((SELECT max(created_at) FROM contact_journal WHERE store_id=NEW.store_id),NEW.created_at) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) BEGIN SELECT RAISE(ABORT,'contact journal mismatch'); END;

CREATE TRIGGER contact_receipts_no_update BEFORE UPDATE ON contact_receipts BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_receipts_no_delete BEFORE DELETE ON contact_receipts BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER contact_receipts_actor BEFORE INSERT ON contact_receipts WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER contact_receipts_sequence BEFORE INSERT ON contact_receipts WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM contact_journal WHERE store_id=NEW.store_id) OR NEW.created_at<coalesce((SELECT max(created_at) FROM contact_journal WHERE store_id=NEW.store_id),NEW.created_at) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) BEGIN SELECT RAISE(ABORT,'contact journal mismatch'); END;

CREATE TRIGGER customer_appointments_no_update BEFORE UPDATE ON customer_appointments BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER customer_appointments_no_delete BEFORE DELETE ON customer_appointments BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER customer_appointments_actor BEFORE INSERT ON customer_appointments WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER customer_appointment_events_no_update BEFORE UPDATE ON customer_appointment_events BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER customer_appointment_events_no_delete BEFORE DELETE ON customer_appointment_events BEGIN SELECT RAISE(ABORT,'contact immutable history'); END;

CREATE TRIGGER customer_appointment_events_actor BEFORE INSERT ON customer_appointment_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR (length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact actor/time mismatch'); END;

CREATE TRIGGER customer_appointment_events_sequence BEFORE INSERT ON customer_appointment_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM contact_journal WHERE store_id=NEW.store_id) OR NEW.created_at<coalesce((SELECT max(created_at) FROM contact_journal WHERE store_id=NEW.store_id),NEW.created_at) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) BEGIN SELECT RAISE(ABORT,'contact journal mismatch'); END;

CREATE TRIGGER contact_cases_number BEFORE INSERT ON contact_cases WHEN NEW.serial!=(SELECT coalesce(max(serial),0)+1 FROM contact_cases WHERE store_id=NEW.store_id) OR NEW.case_number!='CT-'||replace(substr(NEW.created_at,1,10),'-','')||'-'||printf('%05d',NEW.serial) BEGIN SELECT RAISE(ABORT,'contact number mismatch'); END;

CREATE TRIGGER customer_appointments_number BEFORE INSERT ON customer_appointments WHEN NEW.serial!=(SELECT coalesce(max(serial),0)+1 FROM customer_appointments WHERE store_id=NEW.store_id) OR NEW.appointment_number!='AP-'||replace(substr(NEW.created_at,1,10),'-','')||'-'||printf('%05d',NEW.serial) BEGIN SELECT RAISE(ABORT,'contact number mismatch'); END;

CREATE TRIGGER contact_consent_fields BEFORE INSERT ON contact_consents WHEN (length(trim(NEW.recipient_label)) NOT BETWEEN 1 AND 120 OR length(NEW.recipient_label)>120) OR (length(trim(NEW.address)) NOT BETWEEN 1 AND 300 OR length(NEW.address)>300) OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000) OR (length(NEW.effective_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.effective_at) IS NOT NEW.effective_at) OR NEW.effective_at>NEW.created_at BEGIN SELECT RAISE(ABORT,'contact consent source mismatch'); END;

CREATE TRIGGER contact_consent_transition BEFORE INSERT ON contact_consent_events WHEN (length(trim(NEW.note)) NOT BETWEEN 1 AND 1000 OR length(NEW.note)>1000) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM contact_consent_events WHERE consent_id=NEW.consent_id) OR(NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM contact_consents r WHERE r.id=NEW.consent_id AND NEW.action='grant' AND NEW.status='active' AND r.created_at=NEW.created_at AND r.created_by=NEW.created_by)) OR(NEW.revision>1 AND NOT EXISTS(SELECT 1 FROM contact_consent_current e WHERE e.consent_id=NEW.consent_id AND e.status='active' AND NEW.action='revoke' AND NEW.status='revoked')) BEGIN SELECT RAISE(ABORT,'contact consent transition mismatch'); END;

CREATE TRIGGER contact_case_source_shape BEFORE INSERT ON contact_cases WHEN json_type(NEW.source_json) IS NOT 'object' OR (SELECT count(*) FROM json_each(NEW.source_json))!=4 OR EXISTS(SELECT 1 FROM json_each(NEW.source_json) WHERE key NOT IN('kind','id','version','revision')) OR json_extract(NEW.source_json,'$.kind') NOT IN('manual','review','order','training') OR json_type(NEW.source_json,'$.kind') IS NOT 'text' OR json_type(NEW.source_json,'$.id') IS NULL OR json_type(NEW.source_json,'$.version') IS NULL OR json_type(NEW.source_json,'$.revision') IS NULL OR(json_extract(NEW.source_json,'$.kind')='manual' AND (json_type(NEW.source_json,'$.id')!='null' OR json_type(NEW.source_json,'$.version')!='null' OR json_type(NEW.source_json,'$.revision')!='null')) OR(json_extract(NEW.source_json,'$.kind')!='manual' AND (json_type(NEW.source_json,'$.id')!='text' OR length(json_extract(NEW.source_json,'$.id')) NOT BETWEEN 1 AND 100)) OR(json_extract(NEW.source_json,'$.kind')='review' AND (json_type(NEW.source_json,'$.revision')!='integer' OR json_extract(NEW.source_json,'$.revision')<1 OR json_type(NEW.source_json,'$.version')!='null')) OR(json_extract(NEW.source_json,'$.kind')='order' AND (json_type(NEW.source_json,'$.version')!='integer' OR json_extract(NEW.source_json,'$.version')<1 OR json_type(NEW.source_json,'$.revision')!='null')) OR(json_extract(NEW.source_json,'$.kind')='training' AND (json_type(NEW.source_json,'$.version')!='integer' OR json_extract(NEW.source_json,'$.version')<1 OR json_type(NEW.source_json,'$.revision')!='integer' OR json_extract(NEW.source_json,'$.revision')<1)) OR NEW.category!=CASE WHEN NEW.purpose='marketing' THEN 'marketing' ELSE 'service' END OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000) OR NOT(json_extract(NEW.source_json,'$.kind')='manual' OR NEW.purpose='followup' AND json_extract(NEW.source_json,'$.kind')='review' OR NEW.purpose='pickup' AND json_extract(NEW.source_json,'$.kind')='order' OR NEW.purpose='training' AND json_extract(NEW.source_json,'$.kind')='training') BEGIN SELECT RAISE(ABORT,'contact case source shape mismatch'); END;

CREATE TRIGGER contact_case_fixed_source BEFORE INSERT ON contact_cases WHEN (json_extract(NEW.source_json,'$.kind')='manual' AND NEW.cycle_id IS NOT NULL) OR(json_extract(NEW.source_json,'$.kind')='review' AND NOT EXISTS(SELECT 1 FROM review_plans p JOIN review_plan_current e ON e.plan_id=p.id JOIN longitudinal_cases c ON c.id=p.case_id WHERE p.id=json_extract(NEW.source_json,'$.id') AND e.revision=json_extract(NEW.source_json,'$.revision') AND e.status='scheduled' AND p.customer_id=NEW.customer_id AND p.store_id=NEW.store_id AND NEW.cycle_id IS c.cycle_id AND NEW.cycle_version IS c.cycle_version AND e.created_at<=NEW.created_at)) OR(json_extract(NEW.source_json,'$.kind')='order' AND NOT EXISTS(SELECT 1 FROM retail_orders p JOIN retail_order_versions v ON v.order_id=p.id WHERE p.id=json_extract(NEW.source_json,'$.id') AND v.version=json_extract(NEW.source_json,'$.version') AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=p.id) AND v.status!='cancelled' AND p.customer_id=NEW.customer_id AND p.store_id=NEW.store_id AND NEW.cycle_id IS p.cycle_id AND NEW.cycle_version IS p.cycle_version AND v.created_at<=NEW.created_at)) OR(json_extract(NEW.source_json,'$.kind')='training' AND NOT EXISTS(SELECT 1 FROM training_plans p JOIN training_plan_events e ON e.plan_id=p.id WHERE p.id=json_extract(NEW.source_json,'$.id') AND e.revision=json_extract(NEW.source_json,'$.revision') AND e.revision=(SELECT max(revision) FROM training_plan_events WHERE plan_id=p.id) AND e.plan_version=json_extract(NEW.source_json,'$.version') AND e.status='active' AND p.customer_id=NEW.customer_id AND p.store_id=NEW.store_id AND NEW.cycle_id IS p.cycle_id AND NEW.cycle_version IS p.cycle_version AND e.created_at<=NEW.created_at)) BEGIN SELECT RAISE(ABORT,'contact fixed business source mismatch'); END;

CREATE TRIGGER contact_case_transition BEFORE INSERT ON contact_case_events WHEN (length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120) OR (length(trim(NEW.purpose_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.purpose_note)>1000) OR (length(trim(NEW.next_action)) NOT BETWEEN 1 AND 1000 OR length(NEW.next_action)>1000) OR (length(trim(NEW.note)) NOT BETWEEN 1 AND 1000 OR length(NEW.note)>1000) OR (length(NEW.due_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.due_at) IS NOT NEW.due_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM contact_case_events WHERE case_id=NEW.case_id) OR(NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM contact_cases c WHERE c.id=NEW.case_id AND NEW.action='create' AND NEW.status='open' AND c.created_at=NEW.created_at AND c.created_by=NEW.created_by)) OR(NEW.revision>1 AND NOT EXISTS(SELECT 1 FROM contact_case_current p WHERE p.case_id=NEW.case_id AND p.status IN('open','waiting','handoff') AND (NEW.created_by=p.owner_id OR (SELECT role FROM users WHERE id=NEW.created_by)='manager') AND (NEW.action='revise' AND NEW.status=p.status OR NEW.action='assign' AND NEW.status=p.status AND NEW.owner_id!=p.owner_id OR NEW.action='retry' AND NEW.status='open' OR NEW.action='defer' AND NEW.status='waiting' OR NEW.action='attempt' AND NEW.status='waiting' OR NEW.action='failed' AND NEW.status='handoff' OR NEW.action='resolve' AND NEW.status='resolved' OR NEW.action='cancel' AND NEW.status='cancelled') AND (NEW.action='assign' OR NEW.owner_id=p.owner_id))) OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.owner_id AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR(NEW.action IN('assign','resolve','cancel') AND EXISTS(SELECT 1 FROM contact_case_current p WHERE p.case_id=NEW.case_id AND (NEW.title!=p.title OR NEW.purpose_note!=p.purpose_note OR NEW.due_at!=p.due_at OR NEW.next_action!=p.next_action))) OR(NEW.action NOT IN('attempt','failed') AND NEW.attempt_id IS NOT NULL) OR(NEW.action IN('attempt','failed') AND NOT EXISTS(SELECT 1 FROM contact_attempts a WHERE a.id=NEW.attempt_id AND a.case_id=NEW.case_id AND a.case_revision=NEW.revision-1 AND a.sequence=NEW.sequence-1 AND a.created_at=NEW.created_at AND a.created_by=NEW.created_by AND NEW.action=CASE WHEN a.result IN('failed','no_answer','invalid_address','refused') THEN 'failed' ELSE 'attempt' END)) OR(NEW.status IN('resolved','cancelled') AND ((length(trim(NEW.resolution_reason)) NOT BETWEEN 1 AND 1000 OR length(NEW.resolution_reason)>1000) OR (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 1000 OR length(NEW.next_step)>1000))) OR(NEW.action='cancel' AND EXISTS(SELECT 1 FROM customer_appointment_current a WHERE a.case_id=NEW.case_id AND a.status='planned')) BEGIN SELECT RAISE(ABORT,'contact case transition mismatch'); END;

CREATE TRIGGER contact_case_next_task BEFORE INSERT ON contact_case_events WHEN NEW.followup_task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM work_tasks t JOIN task_events e ON e.task_id=t.id AND e.revision=t.revision JOIN contact_cases c ON c.id=NEW.case_id WHERE t.id=NEW.followup_task_id AND e.revision=NEW.followup_revision AND t.customer_id=NEW.customer_id AND t.store_id=NEW.store_id AND t.cycle_id IS c.cycle_id AND t.lifecycle_status='active' AND NOT EXISTS(SELECT 1 FROM task_completions WHERE task_id=t.id) AND e.created_at<=NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact next task mismatch'); END;

CREATE TRIGGER contact_attempt_guard BEFORE INSERT ON contact_attempts WHEN (length(NEW.occurred_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.occurred_at) IS NOT NEW.occurred_at) OR NEW.occurred_at>NEW.created_at OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000) OR (length(trim(NEW.content_summary)) NOT BETWEEN 1 AND 1000 OR length(NEW.content_summary)>1000) OR (length(trim(NEW.result_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.result_note)>1000) OR NOT EXISTS(SELECT 1 FROM contact_case_current c WHERE c.case_id=NEW.case_id AND c.revision=NEW.case_revision AND c.status IN('open','waiting','handoff') AND (c.owner_id=NEW.created_by OR (SELECT role FROM users WHERE id=NEW.created_by)='manager')) OR NOT EXISTS(SELECT 1 FROM contact_consents r JOIN contact_consent_current e ON e.consent_id=r.id JOIN contact_cases c ON c.id=NEW.case_id WHERE r.id=NEW.consent_id AND r.customer_id=NEW.customer_id AND r.store_id=NEW.store_id AND r.category=c.category AND e.revision=NEW.consent_revision AND e.status='active' AND r.effective_at<=NEW.occurred_at AND e.created_at<=NEW.created_at) BEGIN SELECT RAISE(ABORT,'contact current consent or actual mismatch'); END;

CREATE TRIGGER contact_receipt_guard BEFORE INSERT ON contact_receipts WHEN NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM contact_receipts WHERE attempt_id=NEW.attempt_id) OR (length(NEW.occurred_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.occurred_at) IS NOT NEW.occurred_at) OR NEW.occurred_at>NEW.created_at OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000) OR (length(trim(NEW.result_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.result_note)>1000) OR NOT EXISTS(SELECT 1 FROM contact_attempts a JOIN contact_case_current c ON c.case_id=a.case_id WHERE a.id=NEW.attempt_id AND a.occurred_at<=NEW.occurred_at AND a.created_at<=NEW.created_at AND c.revision=NEW.case_revision AND (c.owner_id=NEW.created_by OR (SELECT role FROM users WHERE id=NEW.created_by)='manager')) BEGIN SELECT RAISE(ABORT,'contact explicit receipt mismatch'); END;

CREATE TRIGGER customer_appointment_root BEFORE INSERT ON customer_appointments WHEN NOT EXISTS(SELECT 1 FROM contact_cases r JOIN contact_case_current e ON e.case_id=r.id WHERE r.id=NEW.case_id AND r.category='service' AND r.cycle_id IS NEW.cycle_id AND r.cycle_version IS NEW.cycle_version AND e.status IN('open','waiting','handoff') AND (e.owner_id=NEW.created_by OR(SELECT role FROM users WHERE id=NEW.created_by)='manager')) BEGIN SELECT RAISE(ABORT,'appointment fixed contact mismatch'); END;

CREATE TRIGGER customer_appointment_guard BEFORE INSERT ON customer_appointment_events WHEN (length(trim(NEW.purpose_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.purpose_note)>1000) OR (length(trim(NEW.place_note)) NOT BETWEEN 1 AND 300 OR length(NEW.place_note)>300) OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000) OR (length(trim(NEW.note)) NOT BETWEEN 1 AND 1000 OR length(NEW.note)>1000) OR (length(NEW.starts_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.starts_at) IS NOT NEW.starts_at) OR (length(NEW.ends_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.ends_at) IS NOT NEW.ends_at) OR NEW.ends_at<=NEW.starts_at OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM customer_appointment_events WHERE appointment_id=NEW.appointment_id) OR NOT EXISTS(SELECT 1 FROM contact_case_current c WHERE c.case_id=NEW.case_id AND c.revision=NEW.case_revision) OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security x ON x.user_id=u.id WHERE u.id=NEW.owner_id AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(x.must_change_password,0)=0) OR(NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM customer_appointments r WHERE r.id=NEW.appointment_id AND r.created_at=NEW.created_at AND r.created_by=NEW.created_by AND NEW.action='create' AND NEW.status='planned')) OR(NEW.revision>1 AND NOT EXISTS(SELECT 1 FROM customer_appointment_current p JOIN contact_case_current c ON c.case_id=p.case_id WHERE p.appointment_id=NEW.appointment_id AND p.status='planned' AND (NEW.created_by=p.owner_id OR NEW.created_by=c.owner_id OR (SELECT role FROM users WHERE id=NEW.created_by)='manager') AND (NEW.action IN('reschedule','assign') AND NEW.status='planned' OR NEW.action='cancel' AND NEW.status='cancelled' OR NEW.action='no_show' AND NEW.status='missed' OR NEW.action='arrive' AND NEW.status='arrived') AND (NEW.action='assign' AND NEW.owner_id!=p.owner_id OR NEW.action!='assign' AND NEW.owner_id=p.owner_id))) OR(NEW.action NOT IN('create','reschedule') AND EXISTS(SELECT 1 FROM customer_appointment_current p WHERE p.appointment_id=NEW.appointment_id AND (NEW.starts_at!=p.starts_at OR NEW.ends_at!=p.ends_at OR NEW.purpose_note!=p.purpose_note OR NEW.place_note!=p.place_note OR NEW.source_note!=p.source_note))) OR(NEW.action='arrive' AND ((length(NEW.arrived_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.arrived_at) IS NOT NEW.arrived_at) OR NEW.arrived_at>NEW.created_at OR NOT EXISTS(SELECT 1 FROM visits v JOIN customer_appointments p ON p.id=NEW.appointment_id WHERE v.id=NEW.visit_id AND v.store_id=NEW.store_id AND v.customer_id=NEW.customer_id AND v.created_at<=NEW.created_at AND (p.cycle_id IS NULL OR EXISTS(SELECT 1 FROM visit_cycle_versions x WHERE x.visit_id=v.id AND x.cycle_id=p.cycle_id AND x.version=p.cycle_version AND x.basis='captured'))))) BEGIN SELECT RAISE(ABORT,'appointment transition or arrival mismatch'); END;

CREATE INDEX contact_cases_lookup ON contact_cases(customer_id,serial);

CREATE INDEX contact_attempts_lookup ON contact_attempts(case_id,sequence);

CREATE INDEX contact_consents_lookup ON contact_consents(customer_id,category);

CREATE INDEX customer_appointments_lookup ON customer_appointments(customer_id,serial);

CREATE TRIGGER contact_attempt_current_source BEFORE INSERT ON contact_attempts WHEN NOT EXISTS(SELECT 1 FROM contact_cases c WHERE c.id=NEW.case_id AND (json_extract(c.source_json,'$.kind')='manual' OR json_extract(c.source_json,'$.kind')='review' AND EXISTS(SELECT 1 FROM review_plan_current e WHERE e.plan_id=json_extract(c.source_json,'$.id') AND e.revision=json_extract(c.source_json,'$.revision') AND e.status='scheduled' AND e.created_at<=NEW.created_at) OR json_extract(c.source_json,'$.kind')='order' AND EXISTS(SELECT 1 FROM retail_order_versions v WHERE v.order_id=json_extract(c.source_json,'$.id') AND v.version=json_extract(c.source_json,'$.version') AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=v.order_id) AND v.status!='cancelled' AND v.created_at<=NEW.created_at) OR json_extract(c.source_json,'$.kind')='training' AND EXISTS(SELECT 1 FROM training_plan_events e WHERE e.plan_id=json_extract(c.source_json,'$.id') AND e.revision=json_extract(c.source_json,'$.revision') AND e.revision=(SELECT max(revision) FROM training_plan_events WHERE plan_id=e.plan_id) AND e.plan_version=json_extract(c.source_json,'$.version') AND e.status='active' AND e.created_at<=NEW.created_at))) BEGIN SELECT RAISE(ABORT,'contact business source changed'); END;
CREATE TRIGGER appointment_current_source BEFORE INSERT ON customer_appointment_events WHEN NEW.action IN('create','reschedule') AND NOT EXISTS(SELECT 1 FROM contact_cases c WHERE c.id=NEW.case_id AND (json_extract(c.source_json,'$.kind')='manual' OR json_extract(c.source_json,'$.kind')='review' AND EXISTS(SELECT 1 FROM review_plan_current e WHERE e.plan_id=json_extract(c.source_json,'$.id') AND e.revision=json_extract(c.source_json,'$.revision') AND e.status='scheduled' AND e.created_at<=NEW.created_at) OR json_extract(c.source_json,'$.kind')='order' AND EXISTS(SELECT 1 FROM retail_order_versions v WHERE v.order_id=json_extract(c.source_json,'$.id') AND v.version=json_extract(c.source_json,'$.version') AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=v.order_id) AND v.status!='cancelled' AND v.created_at<=NEW.created_at) OR json_extract(c.source_json,'$.kind')='training' AND EXISTS(SELECT 1 FROM training_plan_events e WHERE e.plan_id=json_extract(c.source_json,'$.id') AND e.revision=json_extract(c.source_json,'$.revision') AND e.revision=(SELECT max(revision) FROM training_plan_events WHERE plan_id=e.plan_id) AND e.plan_version=json_extract(c.source_json,'$.version') AND e.status='active' AND e.created_at<=NEW.created_at))) BEGIN SELECT RAISE(ABORT,'appointment business source changed'); END;
CREATE TRIGGER contact_attempt_fixed_purpose BEFORE INSERT ON contact_case_events WHEN NEW.action IN('attempt','failed') AND EXISTS(SELECT 1 FROM contact_case_current p WHERE p.case_id=NEW.case_id AND (NEW.title!=p.title OR NEW.purpose_note!=p.purpose_note)) BEGIN SELECT RAISE(ABORT,'contact attempt fixed purpose mismatch'); END;
CREATE TRIGGER appointment_absence_time BEFORE INSERT ON customer_appointment_events WHEN NEW.action='no_show' AND NEW.ends_at>NEW.created_at BEGIN SELECT RAISE(ABORT,'appointment absence before end'); END;
