CREATE TABLE external_records(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,serial INTEGER NOT NULL CHECK(serial>=1),record_number TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,store_id,customer_id),UNIQUE(store_id,serial),FOREIGN KEY(customer_id,store_id) REFERENCES customers(id,store_id));

CREATE TABLE external_record_versions(record_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),kind TEXT NOT NULL CHECK(kind IN('external_report','customer_report','unable_to_measure')),title TEXT NOT NULL,institution TEXT NOT NULL,reported_at TEXT NOT NULL,measured_at TEXT,eye TEXT NOT NULL CHECK(eye IN('right','left','both','not_specified')),condition_status TEXT NOT NULL CHECK(condition_status IN('recorded','unknown','incomparable')),condition_note TEXT NOT NULL,source_note TEXT NOT NULL,record_note TEXT NOT NULL,attachment_ids_json TEXT NOT NULL CHECK(json_valid(attachment_ids_json)),document_ids_json TEXT NOT NULL CHECK(json_valid(document_ids_json)),reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(record_id,version),UNIQUE(record_id,version,store_id,customer_id),FOREIGN KEY(record_id,store_id,customer_id) REFERENCES external_records(id,store_id,customer_id),CHECK(kind!='unable_to_measure' OR measured_at IS NULL));

CREATE TABLE external_record_events(id TEXT PRIMARY KEY,record_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),version INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('create','revise','assign','confirm','reject')),status TEXT NOT NULL CHECK(status IN('pending','confirmed','rejected')),owner_id TEXT NOT NULL REFERENCES users(id),opinion_note TEXT,next_step TEXT,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(record_id,revision),UNIQUE(store_id,sequence),UNIQUE(record_id,version,revision,store_id,customer_id),FOREIGN KEY(record_id,store_id,customer_id) REFERENCES external_records(id,store_id,customer_id),FOREIGN KEY(record_id,version) REFERENCES external_record_versions(record_id,version),CHECK((status='pending' AND opinion_note IS NULL AND next_step IS NULL) OR(status!='pending' AND opinion_note IS NOT NULL AND next_step IS NOT NULL)));

CREATE TABLE referral_cases(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,source_kind TEXT NOT NULL CHECK(source_kind IN('manual','longitudinal','observation','aftercare','training_session','external')),source_id TEXT,source_version INTEGER,source_revision INTEGER,cycle_id TEXT,cycle_version INTEGER,source_note TEXT NOT NULL,serial INTEGER NOT NULL CHECK(serial>=1),case_number TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,store_id,customer_id),UNIQUE(store_id,serial),FOREIGN KEY(customer_id,store_id) REFERENCES customers(id,store_id),FOREIGN KEY(cycle_id,cycle_version) REFERENCES cycle_versions(cycle_id,version),CHECK((cycle_id IS NULL AND cycle_version IS NULL) OR(cycle_id IS NOT NULL AND cycle_version IS NOT NULL)),CHECK((source_kind='manual' AND source_id IS NULL AND source_version IS NULL AND source_revision IS NULL) OR(source_kind!='manual' AND source_id IS NOT NULL)));

CREATE TABLE referral_events(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),action TEXT NOT NULL CHECK(action IN('create','revise','assign','arrange','reschedule','defer','complete','cancel')),status TEXT NOT NULL CHECK(status IN('draft','arranged','waiting','completed','cancelled')),professional_owner_id TEXT NOT NULL REFERENCES users(id),contact_owner_id TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,reason_note TEXT NOT NULL,destination TEXT NOT NULL,scheduled_for TEXT,arrangement_note TEXT NOT NULL,due_at TEXT NOT NULL,next_action TEXT NOT NULL,outcome_kind TEXT CHECK(outcome_kind IN('result_received','no_result','unable_to_measure')),outcome_note TEXT,next_step TEXT,result_record_id TEXT,result_version INTEGER,result_revision INTEGER,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES referral_cases(id,store_id,customer_id),FOREIGN KEY(result_record_id,result_version,result_revision,store_id,customer_id) REFERENCES external_record_events(record_id,version,revision,store_id,customer_id),CHECK((status='completed' AND outcome_kind IS NOT NULL AND outcome_note IS NOT NULL AND next_step IS NOT NULL) OR(status='cancelled' AND outcome_kind IS NULL AND outcome_note IS NOT NULL AND next_step IS NOT NULL) OR(status NOT IN('completed','cancelled') AND outcome_kind IS NULL AND outcome_note IS NULL AND next_step IS NULL)),CHECK((outcome_kind='result_received' AND result_record_id IS NOT NULL AND result_version IS NOT NULL AND result_revision IS NOT NULL) OR(coalesce(outcome_kind,'')!='result_received' AND result_record_id IS NULL AND result_version IS NULL AND result_revision IS NULL)));

CREATE TABLE referral_contact_links(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),case_revision INTEGER NOT NULL,contact_owner_id TEXT NOT NULL REFERENCES users(id),attempt_id TEXT NOT NULL REFERENCES contact_attempts(id),receipt_id TEXT REFERENCES contact_receipts(id),appointment_id TEXT,appointment_revision INTEGER,source_note TEXT NOT NULL,result_note TEXT NOT NULL,due_at TEXT NOT NULL,next_action TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),UNIQUE(case_id,attempt_id),UNIQUE(store_id,sequence),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES referral_cases(id,store_id,customer_id),FOREIGN KEY(case_id,case_revision) REFERENCES referral_events(case_id,revision),FOREIGN KEY(appointment_id,appointment_revision) REFERENCES customer_appointment_events(appointment_id,revision),CHECK((appointment_id IS NULL AND appointment_revision IS NULL) OR(appointment_id IS NOT NULL AND appointment_revision IS NOT NULL)));

CREATE VIEW external_record_current AS SELECT e.* FROM external_record_events e WHERE e.revision=(SELECT max(revision) FROM external_record_events WHERE record_id=e.record_id);

CREATE VIEW referral_current AS SELECT e.* FROM referral_events e WHERE e.revision=(SELECT max(revision) FROM referral_events WHERE case_id=e.case_id);

CREATE VIEW referral_journal AS SELECT store_id,sequence,created_at,'record' kind,record_id root_id,id FROM external_record_events UNION ALL SELECT store_id,sequence,created_at,'case',case_id,id FROM referral_events UNION ALL SELECT store_id,sequence,created_at,'contact',case_id,id FROM referral_contact_links;

CREATE VIEW referral_sources AS SELECT 'longitudinal' kind,c.id,c.store_id,c.customer_id,e.version,e.revision,c.cycle_id,c.cycle_version FROM longitudinal_cases c JOIN longitudinal_case_current e ON e.case_id=c.id UNION ALL SELECT 'observation',c.id,c.store_id,c.customer_id,v.version,NULL,l.cycle_id,l.cycle_version FROM longitudinal_observations c JOIN longitudinal_observation_versions v ON v.observation_id=c.id AND v.version=(SELECT max(version) FROM longitudinal_observation_versions WHERE observation_id=c.id) JOIN longitudinal_cases l ON l.id=c.case_id UNION ALL SELECT 'aftercare',c.id,c.store_id,c.customer_id,NULL,e.revision,o.cycle_id,o.cycle_version FROM aftercare_cases c JOIN aftercare_events e ON e.case_id=c.id AND e.revision=(SELECT max(revision) FROM aftercare_events WHERE case_id=c.id) JOIN fulfillment_events f ON f.id=c.delivery_id JOIN processing_jobs j ON j.id=f.job_id JOIN retail_orders o ON o.id=j.order_id UNION ALL SELECT 'training_session',c.id,c.store_id,c.customer_id,NULL,e.revision,c.cycle_id,c.visit_cycle_version FROM training_sessions c JOIN training_session_events e ON e.session_id=c.id AND e.revision=(SELECT max(revision) FROM training_session_events WHERE session_id=c.id) JOIN training_plans p ON p.id=c.plan_id UNION ALL SELECT 'external',c.id,c.store_id,c.customer_id,e.version,e.revision,NULL,NULL FROM external_records c JOIN external_record_current e ON e.record_id=c.id WHERE e.status='confirmed';

CREATE TRIGGER external_records_no_update BEFORE UPDATE ON external_records BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER external_records_no_delete BEFORE DELETE ON external_records BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER external_records_actor BEFORE INSERT ON external_records WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_record_versions_no_update BEFORE UPDATE ON external_record_versions BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER external_record_versions_no_delete BEFORE DELETE ON external_record_versions BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER external_record_versions_actor BEFORE INSERT ON external_record_versions WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_record_events_no_update BEFORE UPDATE ON external_record_events BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER external_record_events_no_delete BEFORE DELETE ON external_record_events BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER external_record_events_actor BEFORE INSERT ON external_record_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_cases_no_update BEFORE UPDATE ON referral_cases BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER referral_cases_no_delete BEFORE DELETE ON referral_cases BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER referral_cases_actor BEFORE INSERT ON referral_cases WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_events_no_update BEFORE UPDATE ON referral_events BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER referral_events_no_delete BEFORE DELETE ON referral_events BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER referral_events_actor BEFORE INSERT ON referral_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_contact_links_no_update BEFORE UPDATE ON referral_contact_links BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER referral_contact_links_no_delete BEFORE DELETE ON referral_contact_links BEGIN SELECT RAISE(ABORT,'referral immutable history'); END;

CREATE TRIGGER referral_contact_links_actor BEFORE INSERT ON referral_contact_links WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.role IN('manager','reception','professional') AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_record_events_clock BEFORE INSERT ON external_record_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM referral_journal WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM referral_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM external_record_events WHERE record_id=NEW.record_id) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_events_clock BEFORE INSERT ON referral_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM referral_journal WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM referral_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM referral_events WHERE case_id=NEW.case_id) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_contact_links_clock BEFORE INSERT ON referral_contact_links WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM referral_journal WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM referral_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM referral_contact_links WHERE case_id=NEW.case_id) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_records_serial BEFORE INSERT ON external_records WHEN NEW.serial!=(SELECT coalesce(max(serial),0)+1 FROM external_records WHERE store_id=NEW.store_id) OR NEW.record_number IS NOT 'ER-'||replace(substr(NEW.created_at,1,10),'-','')||'-'||printf('%05d',NEW.serial) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_cases_serial BEFORE INSERT ON referral_cases WHEN NEW.serial!=(SELECT coalesce(max(serial),0)+1 FROM referral_cases WHERE store_id=NEW.store_id) OR NEW.case_number IS NOT 'RF-'||replace(substr(NEW.created_at,1,10),'-','')||'-'||printf('%05d',NEW.serial) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_record_versions_text BEFORE INSERT ON external_record_versions WHEN (NEW.title IS NOT NULL AND (length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120)) OR (NEW.institution IS NOT NULL AND (length(trim(NEW.institution)) NOT BETWEEN 1 AND 300 OR length(NEW.institution)>300)) OR (NEW.condition_note IS NOT NULL AND (length(trim(NEW.condition_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.condition_note)>1000)) OR (NEW.source_note IS NOT NULL AND (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000)) OR (NEW.record_note IS NOT NULL AND (length(trim(NEW.record_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.record_note)>3000)) OR (NEW.reason IS NOT NULL AND (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_record_events_text BEFORE INSERT ON external_record_events WHEN (NEW.note IS NOT NULL AND (length(trim(NEW.note)) NOT BETWEEN 1 AND 1000 OR length(NEW.note)>1000)) OR (NEW.reason IS NOT NULL AND (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300)) OR (NEW.opinion_note IS NOT NULL AND (length(trim(NEW.opinion_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.opinion_note)>3000)) OR (NEW.next_step IS NOT NULL AND (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 1000 OR length(NEW.next_step)>1000)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_cases_text BEFORE INSERT ON referral_cases WHEN (NEW.source_note IS NOT NULL AND (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_events_text BEFORE INSERT ON referral_events WHEN (NEW.title IS NOT NULL AND (length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120)) OR (NEW.reason_note IS NOT NULL AND (length(trim(NEW.reason_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.reason_note)>2000)) OR (NEW.destination IS NOT NULL AND (length(trim(NEW.destination)) NOT BETWEEN 1 AND 300 OR length(NEW.destination)>300)) OR (NEW.arrangement_note IS NOT NULL AND (length(trim(NEW.arrangement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.arrangement_note)>2000)) OR (NEW.next_action IS NOT NULL AND (length(trim(NEW.next_action)) NOT BETWEEN 1 AND 1000 OR length(NEW.next_action)>1000)) OR (NEW.outcome_note IS NOT NULL AND (length(trim(NEW.outcome_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.outcome_note)>3000)) OR (NEW.next_step IS NOT NULL AND (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 1000 OR length(NEW.next_step)>1000)) OR (NEW.note IS NOT NULL AND (length(trim(NEW.note)) NOT BETWEEN 1 AND 1000 OR length(NEW.note)>1000)) OR (NEW.reason IS NOT NULL AND (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_contact_links_text BEFORE INSERT ON referral_contact_links WHEN (NEW.source_note IS NOT NULL AND (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_note)>1000)) OR (NEW.result_note IS NOT NULL AND (length(trim(NEW.result_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.result_note)>2000)) OR (NEW.next_action IS NOT NULL AND (length(trim(NEW.next_action)) NOT BETWEEN 1 AND 1000 OR length(NEW.next_action)>1000)) OR (NEW.reason IS NOT NULL AND (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_version BEFORE INSERT ON external_record_versions WHEN NEW.version!=(SELECT coalesce(max(version),0)+1 FROM external_record_versions WHERE record_id=NEW.record_id) OR NEW.base_sequence!=(SELECT coalesce(max(sequence),0) FROM referral_journal WHERE store_id=NEW.store_id) OR length(NEW.reported_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.reported_at) IS NOT NEW.reported_at OR NEW.reported_at>NEW.created_at OR (NEW.measured_at IS NOT NULL AND (length(NEW.measured_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.measured_at) IS NOT NEW.measured_at OR NEW.measured_at>NEW.reported_at)) OR json_type(NEW.attachment_ids_json)!='array' OR json_array_length(NEW.attachment_ids_json)>30 OR (SELECT count(*) FROM json_each(NEW.attachment_ids_json))!=(SELECT count(DISTINCT value) FROM json_each(NEW.attachment_ids_json)) OR EXISTS(SELECT 1 FROM json_each(NEW.attachment_ids_json) j WHERE j.type!='text' OR NOT EXISTS(SELECT 1 FROM attachments a WHERE a.id=j.value AND a.customer_id=NEW.customer_id AND a.revoked_at IS NULL)) OR json_type(NEW.document_ids_json)!='array' OR json_array_length(NEW.document_ids_json)>30 OR (SELECT count(*) FROM json_each(NEW.document_ids_json))!=(SELECT count(DISTINCT value) FROM json_each(NEW.document_ids_json)) OR EXISTS(SELECT 1 FROM json_each(NEW.document_ids_json) j WHERE j.type!='text' OR NOT EXISTS(SELECT 1 FROM document_versions v WHERE v.id=j.value AND v.customer_id=NEW.customer_id)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_events_owner BEFORE INSERT ON external_record_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.owner_id AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role='professional') OR (NEW.action IN('confirm','reject') AND (NEW.created_by!=NEW.owner_id OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional'))) OR (NEW.action='assign' AND NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='manager')) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_events_state BEFORE INSERT ON external_record_events WHEN NEW.version!=(SELECT max(version) FROM external_record_versions WHERE record_id=NEW.record_id) OR NOT ((NEW.revision=1 AND NEW.action='create' AND NEW.version=1 AND NEW.status='pending') OR (NEW.revision>1 AND EXISTS(SELECT 1 FROM external_record_current e WHERE e.record_id=NEW.record_id AND ((NEW.action='revise' AND NEW.version=e.version+1 AND NEW.status='pending' AND NEW.owner_id=e.owner_id) OR (NEW.action='assign' AND NEW.version=e.version AND NEW.status=e.status AND NEW.owner_id!=e.owner_id AND NEW.opinion_note IS e.opinion_note AND NEW.next_step IS e.next_step) OR (NEW.action IN('confirm','reject') AND NEW.version=e.version AND NEW.owner_id=e.owner_id AND NEW.status=CASE NEW.action WHEN 'confirm' THEN 'confirmed' ELSE 'rejected' END))))) OR (NEW.action IN('create','revise') AND NOT EXISTS(SELECT 1 FROM external_record_versions v WHERE v.record_id=NEW.record_id AND v.version=NEW.version AND v.base_sequence+1=NEW.sequence AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_source BEFORE INSERT ON referral_cases WHEN NOT ((NEW.source_kind='manual' AND NEW.cycle_id IS NULL) OR EXISTS(SELECT 1 FROM referral_sources s WHERE s.kind=NEW.source_kind AND s.id=NEW.source_id AND s.store_id=NEW.store_id AND s.customer_id=NEW.customer_id AND s.version IS NEW.source_version AND s.revision IS NEW.source_revision AND s.cycle_id IS NEW.cycle_id AND s.cycle_version IS NEW.cycle_version)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_owners BEFORE INSERT ON referral_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.professional_owner_id AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role='professional') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.contact_owner_id AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR (NEW.action IN('arrange','complete') AND (NEW.created_by!=NEW.professional_owner_id OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional'))) OR (NEW.action='assign' AND NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='manager')) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_times BEFORE INSERT ON referral_events WHEN length(NEW.due_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.due_at) IS NOT NEW.due_at OR (NEW.scheduled_for IS NOT NULL AND (length(NEW.scheduled_for)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.scheduled_for) IS NOT NEW.scheduled_for)) OR (NEW.status='arranged' AND NEW.scheduled_for IS NULL) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_transition BEFORE INSERT ON referral_events WHEN NOT ((NEW.revision=1 AND NEW.action='create' AND NEW.status='draft' AND NEW.scheduled_for IS NULL) OR (NEW.revision>1 AND EXISTS(SELECT 1 FROM referral_current e WHERE e.case_id=NEW.case_id AND e.status NOT IN('completed','cancelled') AND ((NEW.action='revise' AND e.status='draft' AND NEW.status='draft') OR (NEW.action='assign' AND NEW.status=e.status) OR (NEW.action='arrange' AND e.status='draft' AND NEW.status='arranged' AND NEW.scheduled_for IS NOT NULL) OR (NEW.action='reschedule' AND e.status IN('arranged','waiting') AND NEW.status='arranged' AND NEW.scheduled_for IS NOT NULL) OR (NEW.action='defer' AND e.status IN('arranged','waiting') AND NEW.status='waiting') OR (NEW.action='complete' AND e.status IN('arranged','waiting') AND NEW.status='completed') OR (NEW.action='cancel' AND NEW.status='cancelled'))))) OR (NEW.revision>1 AND NEW.action!='assign' AND EXISTS(SELECT 1 FROM referral_current e WHERE e.case_id=NEW.case_id AND (NEW.professional_owner_id!=e.professional_owner_id OR NEW.contact_owner_id!=e.contact_owner_id))) OR (NEW.revision>1 AND NEW.action NOT IN('revise','arrange') AND EXISTS(SELECT 1 FROM referral_current e WHERE e.case_id=NEW.case_id AND (NEW.title!=e.title OR NEW.reason_note!=e.reason_note OR NEW.destination!=e.destination OR NEW.arrangement_note!=e.arrangement_note))) OR (NEW.revision>1 AND NEW.action NOT IN('arrange','reschedule') AND EXISTS(SELECT 1 FROM referral_current e WHERE e.case_id=NEW.case_id AND NEW.scheduled_for IS NOT e.scheduled_for)) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_confirmed_result BEFORE INSERT ON referral_events WHEN NEW.outcome_kind='result_received' AND NOT EXISTS(SELECT 1 FROM external_record_current e WHERE e.record_id=NEW.result_record_id AND e.version=NEW.result_version AND e.revision=NEW.result_revision AND e.customer_id=NEW.customer_id AND e.store_id=NEW.store_id AND e.status='confirmed') BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_contact_scope BEFORE INSERT ON referral_contact_links WHEN NOT EXISTS(SELECT 1 FROM referral_current e WHERE e.case_id=NEW.case_id AND e.revision=NEW.case_revision AND e.status NOT IN('completed','cancelled') AND e.contact_owner_id=NEW.contact_owner_id) OR NOT EXISTS(SELECT 1 FROM contact_attempts a JOIN contact_cases c ON c.id=a.case_id WHERE a.id=NEW.attempt_id AND a.customer_id=NEW.customer_id AND a.store_id=NEW.store_id AND c.category='service' AND a.created_at<=NEW.created_at) OR (NEW.receipt_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM contact_receipts r WHERE r.id=NEW.receipt_id AND r.attempt_id=NEW.attempt_id AND r.created_at<=NEW.created_at)) OR (NEW.appointment_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM customer_appointment_events e JOIN contact_attempts a ON a.case_id=e.case_id WHERE a.id=NEW.attempt_id AND e.appointment_id=NEW.appointment_id AND e.revision=NEW.appointment_revision AND e.created_at<=NEW.created_at)) OR length(NEW.due_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.due_at) IS NOT NEW.due_at BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER external_actor_owner BEFORE INSERT ON external_record_events WHEN NEW.revision>1 AND NEW.action!='assign' AND NOT EXISTS(SELECT 1 FROM external_record_current e JOIN users u ON u.id=NEW.created_by WHERE e.record_id=NEW.record_id AND (e.owner_id=NEW.created_by OR u.role='manager' AND NEW.action='revise')) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_actor_owner BEFORE INSERT ON referral_events WHEN NEW.revision>1 AND NEW.action!='assign' AND NOT EXISTS(SELECT 1 FROM referral_current e JOIN users u ON u.id=NEW.created_by WHERE e.case_id=NEW.case_id AND (NEW.created_by IN(e.professional_owner_id,e.contact_owner_id) OR u.role='manager')) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE TRIGGER referral_link_actor BEFORE INSERT ON referral_contact_links WHEN NOT EXISTS(SELECT 1 FROM referral_current e JOIN users u ON u.id=NEW.created_by WHERE e.case_id=NEW.case_id AND (NEW.created_by IN(e.professional_owner_id,e.contact_owner_id) OR u.role='manager')) BEGIN SELECT RAISE(ABORT,'referral source/state mismatch'); END;

CREATE INDEX external_record_events_customer ON external_record_events(customer_id,sequence);

CREATE INDEX referral_events_customer ON referral_events(customer_id,sequence);

CREATE INDEX referral_contact_links_customer ON referral_contact_links(customer_id,sequence);

CREATE TRIGGER external_version_owner BEFORE INSERT ON external_record_versions WHEN NEW.version>1 AND NOT EXISTS(SELECT 1 FROM external_record_current e JOIN users u ON u.id=NEW.created_by WHERE e.record_id=NEW.record_id AND (NEW.created_by=e.owner_id OR u.role='manager')) BEGIN SELECT RAISE(ABORT,'referral current source owner mismatch'); END;
CREATE TRIGGER external_initial_identity BEFORE INSERT ON external_record_events WHEN NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM external_records r WHERE r.id=NEW.record_id AND r.created_at=NEW.created_at AND r.created_by=NEW.created_by) BEGIN SELECT RAISE(ABORT,'referral initial identity mismatch'); END;
CREATE TRIGGER referral_initial_identity BEFORE INSERT ON referral_events WHEN NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM referral_cases r WHERE r.id=NEW.case_id AND r.created_at=NEW.created_at AND r.created_by=NEW.created_by) BEGIN SELECT RAISE(ABORT,'referral initial identity mismatch'); END;
CREATE TRIGGER external_confirmation_access BEFORE INSERT ON external_record_events WHEN NEW.action IN('confirm','reject') AND EXISTS(SELECT 1 FROM external_record_versions v,json_each(v.attachment_ids_json) j WHERE v.record_id=NEW.record_id AND v.version=NEW.version AND NOT EXISTS(SELECT 1 FROM attachments a WHERE a.id=j.value AND a.customer_id=NEW.customer_id AND a.revoked_at IS NULL)) BEGIN SELECT RAISE(ABORT,'referral original attachment unavailable'); END;
CREATE TRIGGER referral_contact_owner_available BEFORE INSERT ON referral_contact_links WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.contact_owner_id AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0) BEGIN SELECT RAISE(ABORT,'referral current contact owner unavailable'); END;
