CREATE TABLE specialty_protocols(id TEXT PRIMARY KEY,store_id TEXT NOT NULL REFERENCES stores(id),code TEXT NOT NULL,service_type TEXT NOT NULL CHECK(service_type IN('contact_lens','ok_lens')),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(store_id,code),UNIQUE(id,store_id));

CREATE TABLE specialty_protocol_versions(protocol_id TEXT NOT NULL,store_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),title TEXT NOT NULL,institution_scope_note TEXT NOT NULL,professional_duties_note TEXT NOT NULL,assessment_requirement_note TEXT NOT NULL,consent_requirement_note TEXT NOT NULL,parameter_requirement_note TEXT NOT NULL,product_trace_note TEXT NOT NULL,care_requirement_note TEXT NOT NULL,review_requirement_note TEXT NOT NULL,source_note TEXT NOT NULL,source_reference TEXT NOT NULL,require_assessment_evidence INTEGER NOT NULL CHECK(require_assessment_evidence IN(0,1)),require_consent_evidence INTEGER NOT NULL CHECK(require_consent_evidence IN(0,1)),reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(protocol_id,version),UNIQUE(protocol_id,version,store_id),FOREIGN KEY(protocol_id,store_id) REFERENCES specialty_protocols(id,store_id));

CREATE TABLE specialty_protocol_events(id TEXT PRIMARY KEY,protocol_id TEXT NOT NULL,store_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),version INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('create','revise','adopt','retire')),status TEXT NOT NULL CHECK(status IN('draft','adopted','retired')),note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(protocol_id,revision),UNIQUE(store_id,sequence),UNIQUE(protocol_id,version,revision,store_id),FOREIGN KEY(protocol_id,version,store_id) REFERENCES specialty_protocol_versions(protocol_id,version,store_id));

CREATE TABLE specialty_cases(id TEXT PRIMARY KEY,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,protocol_id TEXT NOT NULL,protocol_version INTEGER NOT NULL,protocol_revision INTEGER NOT NULL,cycle_id TEXT NOT NULL,cycle_version INTEGER NOT NULL,visit_id TEXT REFERENCES visits(id),context_basis TEXT NOT NULL CHECK(context_basis IN('cycle','visit_cycle')),serial INTEGER NOT NULL CHECK(serial>=1),case_number TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,store_id,customer_id),UNIQUE(store_id,serial),FOREIGN KEY(customer_id,store_id) REFERENCES customers(id,store_id),FOREIGN KEY(protocol_id,protocol_version,protocol_revision,store_id) REFERENCES specialty_protocol_events(protocol_id,version,revision,store_id),FOREIGN KEY(cycle_id,cycle_version,customer_id) REFERENCES cycle_versions(cycle_id,version,customer_id),CHECK((context_basis='cycle' AND visit_id IS NULL) OR(context_basis='visit_cycle' AND visit_id IS NOT NULL)));

CREATE TABLE specialty_case_versions(case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>=1),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),title TEXT NOT NULL,assessment_note TEXT NOT NULL,suitability_note TEXT NOT NULL,source_note TEXT NOT NULL,next_step TEXT NOT NULL,suitability TEXT NOT NULL CHECK(suitability IN('pending','needs_more','not_suitable','suitable')),assessed_at TEXT,document_ids_json TEXT NOT NULL CHECK(json_valid(document_ids_json)),attachment_ids_json TEXT NOT NULL CHECK(json_valid(attachment_ids_json)),reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(case_id,version),UNIQUE(case_id,version,store_id,customer_id),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES specialty_cases(id,store_id,customer_id),CHECK((suitability='pending' AND assessed_at IS NULL) OR(suitability!='pending' AND assessed_at IS NOT NULL)));

CREATE TABLE specialty_case_events(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),version INTEGER NOT NULL,action TEXT NOT NULL CHECK(action IN('create','revise','assign','adopt','pause','resume','stop')),status TEXT NOT NULL CHECK(status IN('draft','active','paused','stopped')),owner_id TEXT NOT NULL REFERENCES users(id),consent_id TEXT REFERENCES specialty_consents(id),consent_revision INTEGER,next_step TEXT NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES specialty_cases(id,store_id,customer_id),FOREIGN KEY(case_id,version) REFERENCES specialty_case_versions(case_id,version),FOREIGN KEY(consent_id,consent_revision,case_id,store_id,customer_id) REFERENCES specialty_consent_events(consent_id,revision,case_id,store_id,customer_id),CHECK((consent_id IS NULL AND consent_revision IS NULL) OR(consent_id IS NOT NULL AND consent_revision IS NOT NULL)));

CREATE TABLE specialty_consents(id TEXT PRIMARY KEY,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,case_version INTEGER NOT NULL,initial_case_revision INTEGER NOT NULL,party TEXT NOT NULL CHECK(party IN('patient','guardian')),party_label TEXT NOT NULL,relationship_note TEXT NOT NULL,signed_at TEXT NOT NULL,source_note TEXT NOT NULL,document_ids_json TEXT NOT NULL CHECK(json_valid(document_ids_json)),attachment_ids_json TEXT NOT NULL CHECK(json_valid(attachment_ids_json)),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(id,case_id,store_id,customer_id),FOREIGN KEY(case_id,store_id,customer_id) REFERENCES specialty_cases(id,store_id,customer_id),FOREIGN KEY(case_id,case_version) REFERENCES specialty_case_versions(case_id,version),FOREIGN KEY(case_id,initial_case_revision) REFERENCES specialty_case_events(case_id,revision));

CREATE TABLE specialty_consent_events(id TEXT PRIMARY KEY,consent_id TEXT NOT NULL,case_id TEXT NOT NULL,store_id TEXT NOT NULL,customer_id TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),action TEXT NOT NULL CHECK(action IN('grant','revoke')),status TEXT NOT NULL CHECK(status IN('active','revoked')),occurred_at TEXT NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(consent_id,revision),UNIQUE(store_id,sequence),UNIQUE(consent_id,revision,case_id,store_id,customer_id),FOREIGN KEY(consent_id,case_id,store_id,customer_id) REFERENCES specialty_consents(id,case_id,store_id,customer_id));

CREATE VIEW specialty_protocol_current AS SELECT e.* FROM specialty_protocol_events e WHERE e.revision=(SELECT max(revision) FROM specialty_protocol_events WHERE protocol_id=e.protocol_id);

CREATE VIEW specialty_case_current AS SELECT e.* FROM specialty_case_events e WHERE e.revision=(SELECT max(revision) FROM specialty_case_events WHERE case_id=e.case_id);

CREATE VIEW specialty_consent_current AS SELECT e.* FROM specialty_consent_events e WHERE e.revision=(SELECT max(revision) FROM specialty_consent_events WHERE consent_id=e.consent_id);

CREATE VIEW specialty_journal AS SELECT store_id,sequence,created_at,'protocol' kind,protocol_id root_id,id FROM specialty_protocol_events UNION ALL SELECT store_id,sequence,created_at,'case',case_id,id FROM specialty_case_events UNION ALL SELECT store_id,sequence,created_at,'consent',consent_id,id FROM specialty_consent_events;

CREATE TRIGGER specialty_protocols_no_update BEFORE UPDATE ON specialty_protocols BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_protocols_no_delete BEFORE DELETE ON specialty_protocols BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_protocols_actor BEFORE INSERT ON specialty_protocols WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='manager') BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_versions_no_update BEFORE UPDATE ON specialty_protocol_versions BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_protocol_versions_no_delete BEFORE DELETE ON specialty_protocol_versions BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_protocol_versions_actor BEFORE INSERT ON specialty_protocol_versions WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='manager') BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_events_no_update BEFORE UPDATE ON specialty_protocol_events BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_protocol_events_no_delete BEFORE DELETE ON specialty_protocol_events BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_protocol_events_actor BEFORE INSERT ON specialty_protocol_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='manager') BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_cases_no_update BEFORE UPDATE ON specialty_cases BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_cases_no_delete BEFORE DELETE ON specialty_cases BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_cases_actor BEFORE INSERT ON specialty_cases WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_versions_no_update BEFORE UPDATE ON specialty_case_versions BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_case_versions_no_delete BEFORE DELETE ON specialty_case_versions BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_case_versions_actor BEFORE INSERT ON specialty_case_versions WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_events_no_update BEFORE UPDATE ON specialty_case_events BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_case_events_no_delete BEFORE DELETE ON specialty_case_events BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_case_events_actor BEFORE INSERT ON specialty_case_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consents_no_update BEFORE UPDATE ON specialty_consents BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_consents_no_delete BEFORE DELETE ON specialty_consents BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_consents_actor BEFORE INSERT ON specialty_consents WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consent_events_no_update BEFORE UPDATE ON specialty_consent_events BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_consent_events_no_delete BEFORE DELETE ON specialty_consent_events BEGIN SELECT RAISE(ABORT,'specialty immutable history'); END;

CREATE TRIGGER specialty_consent_events_actor BEFORE INSERT ON specialty_consent_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) OR length(NEW.created_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_events_clock BEFORE INSERT ON specialty_protocol_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM specialty_journal WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM specialty_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM specialty_protocol_events WHERE protocol_id=NEW.protocol_id) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_events_clock BEFORE INSERT ON specialty_case_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM specialty_journal WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM specialty_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM specialty_case_events WHERE case_id=NEW.case_id) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consent_events_clock BEFORE INSERT ON specialty_consent_events WHEN NEW.sequence!=(SELECT coalesce(max(sequence),0)+1 FROM specialty_journal WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM specialty_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.revision!=(SELECT coalesce(max(revision),0)+1 FROM specialty_consent_events WHERE consent_id=NEW.consent_id) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_versions_clock BEFORE INSERT ON specialty_protocol_versions WHEN NEW.version!=(SELECT coalesce(max(version),0)+1 FROM specialty_protocol_versions WHERE protocol_id=NEW.protocol_id) OR NEW.base_sequence!=(SELECT coalesce(max(sequence),0) FROM specialty_journal WHERE store_id=NEW.store_id) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_versions_clock BEFORE INSERT ON specialty_case_versions WHEN NEW.version!=(SELECT coalesce(max(version),0)+1 FROM specialty_case_versions WHERE case_id=NEW.case_id) OR NEW.base_sequence!=(SELECT coalesce(max(sequence),0) FROM specialty_journal WHERE store_id=NEW.store_id) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_versions_text BEFORE INSERT ON specialty_protocol_versions WHEN length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120 OR length(trim(NEW.institution_scope_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.institution_scope_note)>2000 OR length(trim(NEW.professional_duties_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.professional_duties_note)>2000 OR length(trim(NEW.assessment_requirement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.assessment_requirement_note)>2000 OR length(trim(NEW.consent_requirement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.consent_requirement_note)>2000 OR length(trim(NEW.parameter_requirement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.parameter_requirement_note)>2000 OR length(trim(NEW.product_trace_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.product_trace_note)>2000 OR length(trim(NEW.care_requirement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.care_requirement_note)>2000 OR length(trim(NEW.review_requirement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.review_requirement_note)>2000 OR length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 OR length(trim(NEW.source_reference)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_reference)>1000 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_versions_text BEFORE INSERT ON specialty_case_versions WHEN length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120 OR length(trim(NEW.assessment_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.assessment_note)>3000 OR length(trim(NEW.suitability_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.suitability_note)>2000 OR length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_events_text BEFORE INSERT ON specialty_protocol_events WHEN length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_events_text BEFORE INSERT ON specialty_case_events WHEN length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 OR length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consents_text BEFORE INSERT ON specialty_consents WHEN length(trim(NEW.party_label)) NOT BETWEEN 1 AND 120 OR length(NEW.party_label)>120 OR length(trim(NEW.relationship_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.relationship_note)>1000 OR length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consent_events_text BEFORE INSERT ON specialty_consent_events WHEN length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_versions_reason BEFORE INSERT ON specialty_protocol_versions WHEN length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_versions_reason BEFORE INSERT ON specialty_case_versions WHEN length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_code BEFORE INSERT ON specialty_protocols WHEN length(trim(NEW.code)) NOT BETWEEN 1 AND 40 OR length(NEW.code)>40 BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_protocol_state BEFORE INSERT ON specialty_protocol_events WHEN NEW.version!=(SELECT max(version) FROM specialty_protocol_versions WHERE protocol_id=NEW.protocol_id) OR NOT ((NEW.revision=1 AND NEW.action='create' AND NEW.version=1 AND NEW.status='draft') OR (NEW.revision>1 AND EXISTS(SELECT 1 FROM specialty_protocol_current e WHERE e.protocol_id=NEW.protocol_id AND ((NEW.action='revise' AND NEW.version=e.version+1 AND NEW.status='draft') OR (NEW.action='adopt' AND NEW.version=e.version AND e.status='draft' AND NEW.status='adopted') OR (NEW.action='retire' AND NEW.version=e.version AND e.status='adopted' AND NEW.status='retired'))))) OR (NEW.action IN('create','revise') AND NOT EXISTS(SELECT 1 FROM specialty_protocol_versions v WHERE v.protocol_id=NEW.protocol_id AND v.version=NEW.version AND v.base_sequence+1=NEW.sequence AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by)) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_source BEFORE INSERT ON specialty_cases WHEN NOT EXISTS(SELECT 1 FROM specialty_protocol_current p WHERE p.protocol_id=NEW.protocol_id AND p.store_id=NEW.store_id AND p.version=NEW.protocol_version AND p.revision=NEW.protocol_revision AND p.status='adopted') OR NOT EXISTS(SELECT 1 FROM cycle_versions v JOIN customers c ON c.id=v.customer_id WHERE v.cycle_id=NEW.cycle_id AND v.version=NEW.cycle_version AND v.customer_id=NEW.customer_id AND c.store_id=NEW.store_id AND v.type IN('retail','followup')) OR (NEW.context_basis='cycle' AND NEW.cycle_version!=(SELECT max(version) FROM cycle_versions WHERE cycle_id=NEW.cycle_id)) OR (NEW.context_basis='visit_cycle' AND NOT EXISTS(SELECT 1 FROM visits v JOIN visit_cycle_versions c ON c.visit_id=v.id WHERE v.id=NEW.visit_id AND v.customer_id=NEW.customer_id AND v.store_id=NEW.store_id AND c.cycle_id=NEW.cycle_id AND c.version=NEW.cycle_version AND c.basis='captured')) OR NEW.serial!=(SELECT coalesce(max(serial),0)+1 FROM specialty_cases WHERE store_id=NEW.store_id) OR NEW.case_number IS NOT 'SP-'||replace(substr(NEW.created_at,1,10),'-','')||'-'||printf('%05d',NEW.serial) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_state BEFORE INSERT ON specialty_case_events WHEN NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.owner_id AND u.store_id=NEW.store_id AND u.role='professional' AND u.active=1 AND coalesce(s.must_change_password,0)=0) OR NEW.version!=(SELECT max(version) FROM specialty_case_versions WHERE case_id=NEW.case_id) OR NOT ((NEW.revision=1 AND NEW.action='create' AND NEW.version=1 AND NEW.status='draft' AND NEW.consent_id IS NULL) OR (NEW.revision>1 AND EXISTS(SELECT 1 FROM specialty_case_current e WHERE e.case_id=NEW.case_id AND e.status!='stopped' AND ((NEW.action='revise' AND NEW.version=e.version+1 AND NEW.status='draft' AND NEW.owner_id=e.owner_id AND NEW.consent_id IS NULL) OR (NEW.action='assign' AND NEW.version=e.version AND NEW.status=e.status AND NEW.owner_id!=e.owner_id AND NEW.consent_id IS e.consent_id AND NEW.consent_revision IS e.consent_revision) OR (NEW.action='adopt' AND NEW.version=e.version AND e.status='draft' AND NEW.status='active') OR (NEW.action='pause' AND NEW.version=e.version AND e.status='active' AND NEW.status='paused' AND NEW.consent_id IS e.consent_id AND NEW.consent_revision IS e.consent_revision) OR (NEW.action='resume' AND NEW.version=e.version AND e.status='paused' AND NEW.status='active') OR (NEW.action='stop' AND NEW.version=e.version AND NEW.status='stopped' AND NEW.consent_id IS e.consent_id AND NEW.consent_revision IS e.consent_revision))))) OR (NEW.action IN('create','revise') AND NOT EXISTS(SELECT 1 FROM specialty_case_versions v WHERE v.case_id=NEW.case_id AND v.version=NEW.version AND v.base_sequence+1=NEW.sequence AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by)) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_actor BEFORE INSERT ON specialty_case_events WHEN NEW.revision>1 AND NOT ((NEW.action='assign' AND EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='manager')) OR (NEW.action!='assign' AND NEW.created_by=NEW.owner_id AND EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional')))  BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_assessment_actor BEFORE INSERT ON specialty_case_versions WHEN (NEW.suitability!='pending' AND (NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional') OR NEW.assessed_at IS NULL OR length(NEW.assessed_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.assessed_at) IS NOT NEW.assessed_at OR NEW.assessed_at>NEW.created_at)) OR (NEW.version>1 AND NOT EXISTS(SELECT 1 FROM specialty_case_current e WHERE e.case_id=NEW.case_id AND e.owner_id=NEW.created_by AND e.status!='stopped')) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_case_versions_refs BEFORE INSERT ON specialty_case_versions WHEN json_type(NEW.document_ids_json)!='array' OR json_array_length(NEW.document_ids_json)>30 OR (SELECT count(*) FROM json_each(NEW.document_ids_json))!=(SELECT count(DISTINCT value) FROM json_each(NEW.document_ids_json)) OR EXISTS(SELECT 1 FROM json_each(NEW.document_ids_json) j WHERE j.type!='text' OR NOT EXISTS(SELECT 1 FROM document_versions a WHERE a.id=j.value AND a.customer_id=NEW.customer_id)) OR json_type(NEW.attachment_ids_json)!='array' OR json_array_length(NEW.attachment_ids_json)>30 OR (SELECT count(*) FROM json_each(NEW.attachment_ids_json))!=(SELECT count(DISTINCT value) FROM json_each(NEW.attachment_ids_json)) OR EXISTS(SELECT 1 FROM json_each(NEW.attachment_ids_json) j WHERE j.type!='text' OR NOT EXISTS(SELECT 1 FROM attachments a WHERE a.id=j.value AND a.customer_id=NEW.customer_id AND a.revoked_at IS NULL)) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consents_refs BEFORE INSERT ON specialty_consents WHEN json_type(NEW.document_ids_json)!='array' OR json_array_length(NEW.document_ids_json)>30 OR (SELECT count(*) FROM json_each(NEW.document_ids_json))!=(SELECT count(DISTINCT value) FROM json_each(NEW.document_ids_json)) OR EXISTS(SELECT 1 FROM json_each(NEW.document_ids_json) j WHERE j.type!='text' OR NOT EXISTS(SELECT 1 FROM document_versions a WHERE a.id=j.value AND a.customer_id=NEW.customer_id)) OR json_type(NEW.attachment_ids_json)!='array' OR json_array_length(NEW.attachment_ids_json)>30 OR (SELECT count(*) FROM json_each(NEW.attachment_ids_json))!=(SELECT count(DISTINCT value) FROM json_each(NEW.attachment_ids_json)) OR EXISTS(SELECT 1 FROM json_each(NEW.attachment_ids_json) j WHERE j.type!='text' OR NOT EXISTS(SELECT 1 FROM attachments a WHERE a.id=j.value AND a.customer_id=NEW.customer_id AND a.revoked_at IS NULL)) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consent_source BEFORE INSERT ON specialty_consents WHEN NOT EXISTS(SELECT 1 FROM specialty_case_current e WHERE e.case_id=NEW.case_id AND e.revision=NEW.initial_case_revision AND e.version=NEW.case_version AND e.status!='stopped') OR length(NEW.signed_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.signed_at) IS NOT NEW.signed_at OR NEW.signed_at>NEW.created_at BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_consent_state BEFORE INSERT ON specialty_consent_events WHEN length(NEW.occurred_at)!=24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.occurred_at) IS NOT NEW.occurred_at OR NEW.occurred_at>NEW.created_at OR NOT ((NEW.revision=1 AND NEW.action='grant' AND NEW.status='active' AND EXISTS(SELECT 1 FROM specialty_consents c WHERE c.id=NEW.consent_id AND c.created_at=NEW.created_at AND c.created_by=NEW.created_by AND c.signed_at=NEW.occurred_at)) OR (NEW.revision>1 AND NEW.action='revoke' AND NEW.status='revoked' AND EXISTS(SELECT 1 FROM specialty_consent_current e WHERE e.consent_id=NEW.consent_id AND e.status='active' AND e.occurred_at<=NEW.occurred_at))) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_adopt_sources BEFORE INSERT ON specialty_case_events WHEN NEW.action IN('adopt','resume') AND (NEW.created_by!=NEW.owner_id OR NOT EXISTS(SELECT 1 FROM specialty_cases c JOIN specialty_protocol_current p ON p.protocol_id=c.protocol_id WHERE c.id=NEW.case_id AND p.version=c.protocol_version AND p.revision=c.protocol_revision AND p.status='adopted') OR NOT EXISTS(SELECT 1 FROM specialty_case_versions v WHERE v.case_id=NEW.case_id AND v.version=NEW.version AND v.suitability='suitable') OR NOT EXISTS(SELECT 1 FROM specialty_consents c JOIN specialty_consent_current e ON e.consent_id=c.id WHERE c.id=NEW.consent_id AND c.case_id=NEW.case_id AND c.case_version=NEW.version AND e.revision=NEW.consent_revision AND e.status='active')) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE TRIGGER specialty_adopt_evidence BEFORE INSERT ON specialty_case_events WHEN NEW.action IN('adopt','resume') AND EXISTS(SELECT 1 FROM specialty_cases c JOIN specialty_protocol_versions p ON p.protocol_id=c.protocol_id AND p.version=c.protocol_version JOIN specialty_case_versions v ON v.case_id=c.id AND v.version=NEW.version JOIN specialty_consents a ON a.id=NEW.consent_id WHERE c.id=NEW.case_id AND ((p.require_assessment_evidence=1 AND json_array_length(v.document_ids_json)+json_array_length(v.attachment_ids_json)=0) OR (p.require_consent_evidence=1 AND json_array_length(a.document_ids_json)+json_array_length(a.attachment_ids_json)=0) OR EXISTS(SELECT 1 FROM json_each(v.attachment_ids_json) j JOIN attachments z ON z.id=j.value WHERE z.revoked_at IS NOT NULL) OR EXISTS(SELECT 1 FROM json_each(a.attachment_ids_json) j JOIN attachments z ON z.id=j.value WHERE z.revoked_at IS NOT NULL))) BEGIN SELECT RAISE(ABORT,'specialty source/state mismatch'); END;

CREATE INDEX specialty_case_events_customer ON specialty_case_events(customer_id,sequence);

CREATE INDEX specialty_consent_events_customer ON specialty_consent_events(customer_id,sequence);

CREATE TRIGGER specialty_protocol_initial BEFORE INSERT ON specialty_protocol_events WHEN NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM specialty_protocols p WHERE p.id=NEW.protocol_id AND p.created_at=NEW.created_at AND p.created_by=NEW.created_by) BEGIN SELECT RAISE(ABORT,'specialty initial protocol mismatch'); END;
CREATE TRIGGER specialty_case_initial BEFORE INSERT ON specialty_case_events WHEN NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM specialty_cases p WHERE p.id=NEW.case_id AND p.created_at=NEW.created_at AND p.created_by=NEW.created_by) BEGIN SELECT RAISE(ABORT,'specialty initial case mismatch'); END;
