CREATE TABLE specialty_care_records(id TEXT PRIMARY KEY,quality_id TEXT NOT NULL REFERENCES fulfillment_events(id),delivery_id TEXT REFERENCES fulfillment_events(id),timing TEXT NOT NULL CHECK(timing IN('before_handover','after_handover')),serial INTEGER NOT NULL CHECK(serial>=1),link_id TEXT NOT NULL REFERENCES specialty_order_links(id),order_id TEXT NOT NULL REFERENCES retail_orders(id),case_id TEXT NOT NULL REFERENCES specialty_cases(id),case_version INTEGER NOT NULL,original_approval_id TEXT NOT NULL REFERENCES specialty_order_approvals(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),position INTEGER NOT NULL,quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 999),require_demonstration INTEGER NOT NULL CHECK(require_demonstration IN(0,1)),requirement_source_note TEXT NOT NULL,lot_basis_json TEXT NOT NULL CHECK(json_valid(lot_basis_json)),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(quality_id,timing,serial),CHECK((timing='before_handover' AND delivery_id IS NULL) OR(timing='after_handover' AND delivery_id IS NOT NULL)));

CREATE TABLE specialty_care_versions(id TEXT PRIMARY KEY,care_id TEXT NOT NULL REFERENCES specialty_care_records(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),version INTEGER NOT NULL CHECK(version>=1),base_sequence INTEGER NOT NULL,title TEXT NOT NULL,participant_label TEXT NOT NULL,relationship_note TEXT NOT NULL,guided_at TEXT,outcome TEXT NOT NULL CHECK(outcome IN('not_assessed','needs_practice','demonstrated','declined')),guidance_note TEXT NOT NULL,material_note TEXT NOT NULL,practice_note TEXT NOT NULL,warning_note TEXT NOT NULL,contact_note TEXT NOT NULL,next_step TEXT NOT NULL,document_ids_json TEXT NOT NULL CHECK(json_valid(document_ids_json)),attachment_ids_json TEXT NOT NULL CHECK(json_valid(attachment_ids_json)),reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(care_id,version),CHECK((outcome='not_assessed') OR(guided_at IS NOT NULL)));

CREATE TABLE specialty_care_events(id TEXT PRIMARY KEY,care_id TEXT NOT NULL REFERENCES specialty_care_records(id),version_id TEXT NOT NULL REFERENCES specialty_care_versions(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),action TEXT NOT NULL CHECK(action IN('create','revise','review','release','pause','resume','close')),status TEXT NOT NULL CHECK(status IN('pending','reviewed','released','paused','closed')),specialty_sequence INTEGER NOT NULL,case_revision INTEGER NOT NULL,trace_sequence INTEGER NOT NULL,parameter_sequence INTEGER NOT NULL,approval_id TEXT REFERENCES specialty_order_approvals(id),next_step TEXT NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(care_id,revision),UNIQUE(store_id,sequence));

CREATE TABLE specialty_care_execution_refs(event_id TEXT PRIMARY KEY,kind TEXT NOT NULL CHECK(kind IN('deliver','outbound')),care_id TEXT NOT NULL REFERENCES specialty_care_records(id),version_id TEXT NOT NULL REFERENCES specialty_care_versions(id),care_revision INTEGER NOT NULL,care_sequence INTEGER NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(care_id,care_revision) REFERENCES specialty_care_events(care_id,revision));

CREATE VIEW specialty_care_current AS SELECT e.* FROM specialty_care_events e WHERE e.revision=(SELECT max(revision) FROM specialty_care_events WHERE care_id=e.care_id);

CREATE VIEW specialty_care_context AS SELECT r.*,e.revision,e.version_id,e.sequence,e.status,e.approval_id,e.specialty_sequence,e.case_revision,e.trace_sequence,v.version,v.outcome,
 CASE WHEN e.status='released' AND c.can_execute=1 AND c.case_version=r.case_version AND c.approval_id=e.approval_id AND NOT EXISTS(SELECT 1 FROM json_each(v.attachment_ids_json) x JOIN attachments a ON a.id=x.value WHERE a.revoked_at IS NOT NULL) THEN 1 ELSE 0 END can_handover
 FROM specialty_care_records r JOIN specialty_care_current e ON e.care_id=r.id JOIN specialty_care_versions v ON v.id=e.version_id JOIN specialty_trace_context c ON c.id=r.link_id;

CREATE TRIGGER specialty_care_records_no_update BEFORE UPDATE ON specialty_care_records BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_records_no_delete BEFORE DELETE ON specialty_care_records BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_records_actor BEFORE INSERT ON specialty_care_records WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty care actor/time'); END;

CREATE TRIGGER specialty_care_versions_no_update BEFORE UPDATE ON specialty_care_versions BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_versions_no_delete BEFORE DELETE ON specialty_care_versions BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_versions_actor BEFORE INSERT ON specialty_care_versions WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty care actor/time'); END;

CREATE TRIGGER specialty_care_events_no_update BEFORE UPDATE ON specialty_care_events BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_events_no_delete BEFORE DELETE ON specialty_care_events BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_events_actor BEFORE INSERT ON specialty_care_events WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty care actor/time'); END;

CREATE TRIGGER specialty_care_execution_refs_no_update BEFORE UPDATE ON specialty_care_execution_refs BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_execution_refs_no_delete BEFORE DELETE ON specialty_care_execution_refs BEGIN SELECT RAISE(ABORT,'specialty care immutable'); END;

CREATE TRIGGER specialty_care_root_ready BEFORE INSERT ON specialty_care_records BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM fulfillment_events q JOIN processing_jobs j ON j.id=q.job_id JOIN specialty_order_links l ON l.order_id=j.order_id AND l.order_version=j.order_version JOIN specialty_execution_refs ref ON ref.event_id=q.id AND ref.kind='fulfillment' JOIN specialty_order_approvals a ON a.id=ref.approval_id WHERE q.id=NEW.quality_id AND q.action='check_pass' AND q.position=NEW.position AND l.id=NEW.link_id AND l.order_id=NEW.order_id AND l.case_id=NEW.case_id AND l.customer_id=NEW.customer_id AND l.store_id=NEW.store_id AND a.id=NEW.original_approval_id AND a.case_version=NEW.case_version AND ref.lot_basis_json=NEW.lot_basis_json AND NEW.created_at>=q.created_at AND (NEW.timing='before_handover' AND NEW.quantity=q.quantity AND NOT EXISTS(SELECT 1 FROM fulfillment_events d WHERE d.source_id=q.id AND d.action='deliver') OR NEW.timing='after_handover' AND EXISTS(SELECT 1 FROM fulfillment_events d WHERE d.id=NEW.delivery_id AND d.action='deliver' AND d.source_id=q.id AND d.quantity=NEW.quantity AND d.created_at<=NEW.created_at))) OR NEW.serial<>coalesce((SELECT max(serial)+1 FROM specialty_care_records WHERE quality_id=NEW.quality_id AND timing=NEW.timing),1) OR EXISTS(SELECT 1 FROM specialty_care_records r LEFT JOIN specialty_care_current e ON e.care_id=r.id WHERE r.quality_id=NEW.quality_id AND r.timing=NEW.timing AND e.status IS NOT 'closed') OR length(trim(NEW.requirement_source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.requirement_source_note)>2000 THEN RAISE(ABORT,'specialty care original source or requirement mismatch') END; END;

CREATE TRIGGER specialty_care_version_ready BEFORE INSERT ON specialty_care_versions BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM specialty_care_records r WHERE r.id=NEW.care_id AND r.customer_id=NEW.customer_id AND r.store_id=NEW.store_id AND NEW.created_at>=r.created_at) OR NEW.version<>coalesce((SELECT max(version)+1 FROM specialty_care_versions WHERE care_id=NEW.care_id),1) OR NEW.base_sequence<>(SELECT coalesce(max(sequence),0) FROM specialty_care_events WHERE store_id=NEW.store_id) OR EXISTS(SELECT 1 FROM specialty_care_current e WHERE e.care_id=NEW.care_id AND e.status='closed') OR EXISTS(SELECT 1 FROM specialty_care_events e WHERE e.store_id=NEW.store_id AND e.created_at>NEW.created_at) OR NEW.guided_at IS NOT NULL AND (length(NEW.guided_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.guided_at) IS NOT NEW.guided_at OR NEW.guided_at>NEW.created_at) OR NEW.outcome<>'not_assessed' AND NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional') THEN RAISE(ABORT,'specialty care version or actual observation mismatch') END; END;

CREATE TRIGGER specialty_care_version_text BEFORE INSERT ON specialty_care_versions WHEN length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120 OR length(trim(NEW.participant_label)) NOT BETWEEN 1 AND 120 OR length(NEW.participant_label)>120 OR length(trim(NEW.relationship_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.relationship_note)>1000 OR length(trim(NEW.guidance_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.guidance_note)>3000 OR length(trim(NEW.material_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.material_note)>2000 OR length(trim(NEW.practice_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.practice_note)>2000 OR length(trim(NEW.warning_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.warning_note)>2000 OR length(trim(NEW.contact_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.contact_note)>2000 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty care actual source fields'); END;

CREATE TRIGGER specialty_care_version_document_ids_json BEFORE INSERT ON specialty_care_versions WHEN json_type(NEW.document_ids_json) IS NOT 'array' OR json_array_length(NEW.document_ids_json)>30 OR EXISTS(SELECT 1 FROM json_each(NEW.document_ids_json) x WHERE x.type<>'text' OR length(x.value) NOT BETWEEN 1 AND 100 OR NOT EXISTS(SELECT 1 FROM document_versions a WHERE a.id=x.value AND a.customer_id=NEW.customer_id AND a.created_at<=NEW.created_at )) OR EXISTS(SELECT 1 FROM json_each(NEW.document_ids_json) GROUP BY value HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'specialty care fixed material source'); END;

CREATE TRIGGER specialty_care_version_attachment_ids_json BEFORE INSERT ON specialty_care_versions WHEN json_type(NEW.attachment_ids_json) IS NOT 'array' OR json_array_length(NEW.attachment_ids_json)>30 OR EXISTS(SELECT 1 FROM json_each(NEW.attachment_ids_json) x WHERE x.type<>'text' OR length(x.value) NOT BETWEEN 1 AND 100 OR NOT EXISTS(SELECT 1 FROM attachments a WHERE a.id=x.value AND a.customer_id=NEW.customer_id AND a.created_at<=NEW.created_at AND a.revoked_at IS NULL)) OR EXISTS(SELECT 1 FROM json_each(NEW.attachment_ids_json) GROUP BY value HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'specialty care fixed material source'); END;

CREATE TRIGGER specialty_care_event_ready BEFORE INSERT ON specialty_care_events BEGIN
 SELECT CASE WHEN NEW.revision<>coalesce((SELECT max(revision)+1 FROM specialty_care_events WHERE care_id=NEW.care_id),1) OR NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM specialty_care_events WHERE store_id=NEW.store_id),1) OR EXISTS(SELECT 1 FROM specialty_care_events WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.specialty_sequence<>(SELECT coalesce(max(sequence),0) FROM specialty_journal WHERE store_id=NEW.store_id) OR NEW.trace_sequence<>(SELECT coalesce(max(sequence),0) FROM specialty_trace_journal WHERE store_id=NEW.store_id) OR NEW.parameter_sequence<>(SELECT coalesce(max(sequence),0) FROM parameter_events WHERE order_id=(SELECT order_id FROM specialty_care_records WHERE id=NEW.care_id)) OR NOT EXISTS(SELECT 1 FROM specialty_care_records r JOIN specialty_care_versions v ON v.care_id=r.id JOIN specialty_case_current c ON c.case_id=r.case_id WHERE r.id=NEW.care_id AND r.store_id=NEW.store_id AND r.customer_id=NEW.customer_id AND v.id=NEW.version_id AND v.version=(SELECT max(version) FROM specialty_care_versions WHERE care_id=r.id) AND NEW.case_revision=c.revision AND NEW.created_at>=v.created_at AND (NEW.action IN('create','revise') OR c.owner_id=NEW.created_by AND EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional'))) OR length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 THEN RAISE(ABORT,'specialty care history/source/owner mismatch') END;
 SELECT CASE WHEN NOT(NEW.action='create' AND NEW.revision=1 AND NEW.status='pending' AND EXISTS(SELECT 1 FROM specialty_care_records r JOIN specialty_care_versions v ON v.care_id=r.id WHERE r.id=NEW.care_id AND v.id=NEW.version_id AND v.version=1 AND r.created_at=NEW.created_at AND r.created_by=NEW.created_by AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by AND v.base_sequence+1=NEW.sequence) OR NEW.action='revise' AND NEW.status='pending' AND EXISTS(SELECT 1 FROM specialty_care_current e JOIN specialty_care_versions old ON old.id=e.version_id JOIN specialty_care_versions v ON v.id=NEW.version_id WHERE e.care_id=NEW.care_id AND e.status<>'closed' AND v.version=old.version+1 AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by AND v.base_sequence+1=NEW.sequence) OR NEW.action NOT IN('create','revise') AND EXISTS(SELECT 1 FROM specialty_care_current e WHERE e.care_id=NEW.care_id AND e.version_id=NEW.version_id AND (NEW.action='review' AND e.status='pending' AND NEW.status='reviewed' OR NEW.action='release' AND e.status='reviewed' AND NEW.status='released' OR NEW.action='pause' AND e.status IN('pending','reviewed','released') AND NEW.status='paused' OR NEW.action='resume' AND e.status='paused' AND NEW.status='pending' OR NEW.action='close' AND e.status<>'closed' AND NEW.status='closed'))) THEN RAISE(ABORT,'specialty care transition mismatch') END;
 SELECT CASE WHEN NEW.action IN('create','revise') AND EXISTS(SELECT 1 FROM specialty_care_versions v WHERE v.id=NEW.version_id AND (v.outcome<>'not_assessed' OR EXISTS(SELECT 1 FROM specialty_care_current old JOIN specialty_care_versions pv ON pv.id=old.version_id WHERE old.care_id=NEW.care_id AND pv.outcome<>'not_assessed'))) AND NOT EXISTS(SELECT 1 FROM specialty_care_records r JOIN specialty_case_current c ON c.case_id=r.case_id JOIN users u ON u.id=NEW.created_by WHERE r.id=NEW.care_id AND c.owner_id=u.id AND u.role='professional') THEN RAISE(ABORT,'specialty care professional observation owner') END;
 SELECT CASE WHEN NEW.action='release' AND NOT EXISTS(SELECT 1 FROM specialty_care_records r JOIN specialty_care_versions v ON v.id=NEW.version_id JOIN specialty_trace_context c ON c.id=r.link_id WHERE r.id=NEW.care_id AND c.can_execute=1 AND c.case_version=r.case_version AND c.approval_id=NEW.approval_id AND v.guided_at IS NOT NULL AND v.outcome IN('demonstrated','needs_practice') AND (r.require_demonstration=0 OR v.outcome='demonstrated') AND NOT EXISTS(SELECT 1 FROM json_each(v.attachment_ids_json) x JOIN attachments a ON a.id=x.value WHERE a.revoked_at IS NOT NULL)) OR NEW.action<>'release' AND NEW.approval_id IS NOT NULL THEN RAISE(ABORT,'specialty care explicit release required') END; END;

CREATE TRIGGER fulfillment_care_gate BEFORE INSERT ON fulfillment_events WHEN NEW.action='deliver' BEGIN SELECT CASE WHEN EXISTS(SELECT 1 FROM specialty_care_records r WHERE r.quality_id=NEW.source_id AND r.timing='before_handover') AND NOT EXISTS(SELECT 1 FROM specialty_care_context c WHERE c.quality_id=NEW.source_id AND c.timing='before_handover' AND c.serial=(SELECT max(serial) FROM specialty_care_records WHERE quality_id=NEW.source_id AND timing='before_handover') AND c.can_handover=1) THEN RAISE(ABORT,'specialty care handover hold') END; END;

CREATE TRIGGER fulfillment_care_capture AFTER INSERT ON fulfillment_events WHEN NEW.action='deliver' BEGIN INSERT INTO specialty_care_execution_refs SELECT NEW.id,'deliver',c.id,c.version_id,c.revision,(SELECT max(sequence) FROM specialty_care_events WHERE store_id=c.store_id),NEW.created_at FROM specialty_care_context c WHERE c.quality_id=NEW.source_id AND c.timing='before_handover' AND c.serial=(SELECT max(serial) FROM specialty_care_records WHERE quality_id=NEW.source_id AND timing='before_handover'); END;

CREATE TRIGGER outbound_care_gate BEFORE INSERT ON inventory_outbounds BEGIN SELECT CASE WHEN EXISTS(SELECT 1 FROM specialty_care_execution_refs r WHERE r.event_id=NEW.delivery_id AND r.kind='deliver') AND NOT EXISTS(SELECT 1 FROM specialty_care_execution_refs ref JOIN specialty_care_context c ON c.id=ref.care_id WHERE ref.event_id=NEW.delivery_id AND ref.kind='deliver' AND c.can_handover=1) THEN RAISE(ABORT,'specialty care outbound hold') END; END;

CREATE TRIGGER outbound_care_capture AFTER INSERT ON inventory_outbounds BEGIN INSERT INTO specialty_care_execution_refs SELECT NEW.id,'outbound',c.id,c.version_id,c.revision,(SELECT max(sequence) FROM specialty_care_events WHERE store_id=c.store_id),NEW.created_at FROM specialty_care_execution_refs ref JOIN specialty_care_context c ON c.id=ref.care_id WHERE ref.event_id=NEW.delivery_id AND ref.kind='deliver'; END;

CREATE TRIGGER specialty_care_execution_ready BEFORE INSERT ON specialty_care_execution_refs BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM specialty_care_context c WHERE c.id=NEW.care_id AND c.can_handover=1 AND c.version_id=NEW.version_id AND c.revision=NEW.care_revision AND NEW.care_sequence=(SELECT max(sequence) FROM specialty_care_events WHERE store_id=c.store_id) AND (NEW.kind='deliver' AND EXISTS(SELECT 1 FROM fulfillment_events e WHERE e.id=NEW.event_id AND e.action='deliver' AND e.source_id=c.quality_id AND e.created_at=NEW.created_at) OR NEW.kind='outbound' AND EXISTS(SELECT 1 FROM inventory_outbounds e JOIN specialty_care_execution_refs ref ON ref.event_id=e.delivery_id AND ref.kind='deliver' WHERE e.id=NEW.event_id AND ref.care_id=c.id AND e.created_at=NEW.created_at))) THEN RAISE(ABORT,'specialty care actual execution source') END; END;
