CREATE TABLE specialty_reviews(id TEXT PRIMARY KEY,delivery_id TEXT NOT NULL REFERENCES fulfillment_events(id),link_id TEXT NOT NULL REFERENCES specialty_order_links(id),order_id TEXT NOT NULL REFERENCES retail_orders(id),case_id TEXT NOT NULL REFERENCES specialty_cases(id),case_version INTEGER NOT NULL,original_approval_id TEXT NOT NULL REFERENCES specialty_order_approvals(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),position INTEGER NOT NULL,quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 999),category TEXT NOT NULL CHECK(category IN('routine','discomfort','damaged','lost','other_issue')),source_note TEXT NOT NULL,lot_basis_json TEXT NOT NULL CHECK(json_valid(lot_basis_json)),care_basis_json TEXT CHECK(care_basis_json IS NULL OR json_valid(care_basis_json)),created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id));

CREATE TABLE specialty_review_versions(id TEXT PRIMARY KEY,review_id TEXT NOT NULL REFERENCES specialty_reviews(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),version INTEGER NOT NULL CHECK(version>=1),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),reported_at TEXT NOT NULL,measured_at TEXT,eye TEXT NOT NULL CHECK(eye IN('right','left','both','not_specified')),condition_status TEXT NOT NULL CHECK(condition_status IN('recorded','unknown','incomparable')),source_kind TEXT NOT NULL CHECK(source_kind IN('staff_record','customer_report','external_report','unable_measure')),due_date TEXT,title TEXT NOT NULL,participant_label TEXT NOT NULL,relationship_note TEXT NOT NULL,condition_note TEXT NOT NULL,source_note TEXT NOT NULL,feedback_note TEXT NOT NULL,findings_note TEXT NOT NULL,issue_note TEXT NOT NULL,arrangement_note TEXT NOT NULL,manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)),reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(review_id,version),CHECK(source_kind<>'unable_measure' OR measured_at IS NULL));

CREATE TABLE specialty_review_events(id TEXT PRIMARY KEY,review_id TEXT NOT NULL REFERENCES specialty_reviews(id),version_id TEXT NOT NULL REFERENCES specialty_review_versions(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),action TEXT NOT NULL CHECK(action IN('create','revise','confirm','close','cancel')),status TEXT NOT NULL CHECK(status IN('pending','confirmed','closed','cancelled')),specialty_sequence INTEGER NOT NULL,case_revision INTEGER NOT NULL,trace_sequence INTEGER NOT NULL,parameter_sequence INTEGER NOT NULL,approval_id TEXT REFERENCES specialty_order_approvals(id),longitudinal_sequence INTEGER NOT NULL,referral_sequence INTEGER NOT NULL,decision TEXT CHECK(decision IN('continue','adjust','pause','stop','refer','not_assessed')),evaluated_at TEXT,opinion_note TEXT,effect_case_event_id TEXT UNIQUE REFERENCES specialty_case_events(id),next_step TEXT NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(review_id,revision),UNIQUE(store_id,sequence),CHECK((action='confirm' AND decision IS NOT NULL AND evaluated_at IS NOT NULL AND opinion_note IS NOT NULL) OR(action<>'confirm' AND decision IS NULL AND evaluated_at IS NULL AND opinion_note IS NULL AND effect_case_event_id IS NULL)));

CREATE TABLE specialty_review_links(id TEXT PRIMARY KEY,review_id TEXT NOT NULL REFERENCES specialty_reviews(id),version_id TEXT NOT NULL REFERENCES specialty_review_versions(id),review_revision INTEGER NOT NULL,store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),kind TEXT NOT NULL CHECK(kind IN('review_plan','referral','contact_attempt')),source_json TEXT NOT NULL CHECK(json_valid(source_json)),longitudinal_sequence INTEGER NOT NULL,referral_sequence INTEGER NOT NULL,contact_sequence INTEGER NOT NULL,source_note TEXT NOT NULL,next_step TEXT NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(review_id,revision),UNIQUE(store_id,sequence),FOREIGN KEY(review_id,review_revision) REFERENCES specialty_review_events(review_id,revision));

CREATE VIEW specialty_review_journal AS SELECT id,store_id,sequence,created_at,'event' kind FROM specialty_review_events UNION ALL SELECT id,store_id,sequence,created_at,'link' FROM specialty_review_links;

CREATE VIEW specialty_review_current AS SELECT e.* FROM specialty_review_events e WHERE e.revision=(SELECT max(revision) FROM specialty_review_events WHERE review_id=e.review_id);

CREATE VIEW specialty_review_deliveries AS SELECT d.id delivery_id,d.source_id quality_id,d.position,d.quantity,d.handed_at,d.created_at,d.receiver_name,j.id job_id,j.order_id,j.order_version,j.customer_id,j.store_id,o.order_number,l.id link_id,l.case_id,a.case_version,ref.approval_id,ref.lot_basis_json,i.product_id,i.product_version,v.name product_name,v.unit,(SELECT json_object('care_id',care_id,'version_id',version_id,'care_revision',care_revision,'care_sequence',care_sequence) FROM specialty_care_execution_refs WHERE event_id=d.id AND kind='deliver') care_basis_json FROM fulfillment_events d JOIN processing_jobs j ON j.id=d.job_id JOIN retail_orders o ON o.id=j.order_id JOIN specialty_order_links l ON l.order_id=j.order_id JOIN specialty_execution_refs ref ON ref.event_id=d.id AND ref.kind='fulfillment' JOIN specialty_order_approvals a ON a.id=ref.approval_id JOIN retail_order_items i ON i.order_id=j.order_id AND i.version=j.order_version AND i.position=d.position JOIN retail_product_versions v ON v.product_id=i.product_id AND v.version=i.product_version WHERE d.action='deliver';

CREATE TRIGGER specialty_reviews_no_update BEFORE UPDATE ON specialty_reviews BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_reviews_no_delete BEFORE DELETE ON specialty_reviews BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_reviews_actor BEFORE INSERT ON specialty_reviews WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty review actor/time'); END;

CREATE TRIGGER specialty_review_versions_no_update BEFORE UPDATE ON specialty_review_versions BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_review_versions_no_delete BEFORE DELETE ON specialty_review_versions BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_review_versions_actor BEFORE INSERT ON specialty_review_versions WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty review actor/time'); END;

CREATE TRIGGER specialty_review_events_no_update BEFORE UPDATE ON specialty_review_events BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_review_events_no_delete BEFORE DELETE ON specialty_review_events BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_review_events_actor BEFORE INSERT ON specialty_review_events WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty review actor/time'); END;

CREATE TRIGGER specialty_review_links_no_update BEFORE UPDATE ON specialty_review_links BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_review_links_no_delete BEFORE DELETE ON specialty_review_links BEGIN SELECT RAISE(ABORT,'specialty review immutable'); END;

CREATE TRIGGER specialty_review_links_actor BEFORE INSERT ON specialty_review_links WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty review actor/time'); END;

CREATE TRIGGER specialty_review_root_source BEFORE INSERT ON specialty_reviews WHEN NOT EXISTS(SELECT 1 FROM specialty_review_deliveries d WHERE d.delivery_id=NEW.delivery_id AND d.link_id=NEW.link_id AND d.order_id=NEW.order_id AND d.case_id=NEW.case_id AND d.case_version=NEW.case_version AND d.approval_id=NEW.original_approval_id AND d.store_id=NEW.store_id AND d.customer_id=NEW.customer_id AND d.position=NEW.position AND d.quantity=NEW.quantity AND d.lot_basis_json=NEW.lot_basis_json AND d.care_basis_json IS NEW.care_basis_json AND d.created_at<=NEW.created_at) OR length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 BEGIN SELECT RAISE(ABORT,'specialty review fixed signed product source'); END;

CREATE TRIGGER specialty_review_version_ready BEFORE INSERT ON specialty_review_versions WHEN NOT EXISTS(SELECT 1 FROM specialty_reviews r WHERE r.id=NEW.review_id AND r.store_id=NEW.store_id AND r.customer_id=NEW.customer_id AND r.created_at<=NEW.created_at) OR NEW.version<>coalesce((SELECT max(version)+1 FROM specialty_review_versions WHERE review_id=NEW.review_id),1) OR NEW.base_sequence<>coalesce((SELECT max(sequence) FROM specialty_review_journal WHERE store_id=NEW.store_id),0) OR EXISTS(SELECT 1 FROM specialty_review_current e WHERE e.review_id=NEW.review_id AND e.status IN('closed','cancelled')) OR EXISTS(SELECT 1 FROM specialty_review_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR length(NEW.reported_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.reported_at) IS NOT NEW.reported_at OR NEW.reported_at>NEW.created_at OR NEW.reported_at<(SELECT handed_at FROM specialty_review_deliveries d JOIN specialty_reviews r ON r.delivery_id=d.delivery_id WHERE r.id=NEW.review_id) OR NEW.measured_at IS NOT NULL AND (length(NEW.measured_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.measured_at) IS NOT NEW.measured_at OR NEW.measured_at>NEW.reported_at) OR NEW.due_date IS NOT NULL AND (length(NEW.due_date)<>10 OR strftime('%Y-%m-%d',NEW.due_date) IS NOT NEW.due_date OR date(NEW.due_date,'+0 days') IS NOT NEW.due_date) BEGIN SELECT RAISE(ABORT,'specialty review version/time/arrangement'); END;

CREATE TRIGGER specialty_review_version_text BEFORE INSERT ON specialty_review_versions WHEN length(trim(NEW.title)) NOT BETWEEN 1 AND 120 OR length(NEW.title)>120 OR length(trim(NEW.participant_label)) NOT BETWEEN 1 AND 120 OR length(NEW.participant_label)>120 OR length(trim(NEW.relationship_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.relationship_note)>1000 OR length(trim(NEW.condition_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.condition_note)>1000 OR length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 OR length(trim(NEW.feedback_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.feedback_note)>3000 OR length(trim(NEW.findings_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.findings_note)>3000 OR length(trim(NEW.issue_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.issue_note)>2000 OR length(trim(NEW.arrangement_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.arrangement_note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty review actual source fields'); END;

CREATE TRIGGER specialty_review_manifest_shape BEFORE INSERT ON specialty_review_versions WHEN json_type(NEW.manifest_json) IS NOT 'object' OR (SELECT count(*) FROM json_each(NEW.manifest_json))<>4 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json) WHERE key NOT IN('documents','attachments','observations','external_records') OR type<>'array') BEGIN SELECT RAISE(ABORT,'specialty review manifest shape'); END;

CREATE TRIGGER specialty_review_manifest_documents BEFORE INSERT ON specialty_review_versions WHEN json_array_length(NEW.manifest_json,'$.documents')>30 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.documents') x WHERE x.type<>'text' OR length(x.value) NOT BETWEEN 1 AND 100 OR NOT EXISTS(SELECT 1 FROM document_versions a WHERE a.id=x.value AND a.customer_id=NEW.customer_id AND a.created_at<=NEW.created_at )) OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.documents') GROUP BY value HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'specialty review fixed documents'); END;

CREATE TRIGGER specialty_review_manifest_attachments BEFORE INSERT ON specialty_review_versions WHEN json_array_length(NEW.manifest_json,'$.attachments')>30 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.attachments') x WHERE x.type<>'text' OR length(x.value) NOT BETWEEN 1 AND 100 OR NOT EXISTS(SELECT 1 FROM attachments a WHERE a.id=x.value AND a.customer_id=NEW.customer_id AND a.created_at<=NEW.created_at AND a.revoked_at IS NULL)) OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.attachments') GROUP BY value HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'specialty review fixed attachments'); END;

CREATE TRIGGER specialty_review_manifest_observations BEFORE INSERT ON specialty_review_versions WHEN json_array_length(NEW.manifest_json,'$.observations')>30 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.observations') x WHERE x.type<>'object' OR (SELECT count(*) FROM json_each(x.value))<>2 OR json_type(x.value,'$.id') IS NOT 'text' OR length(json_extract(x.value,'$.id')) NOT BETWEEN 1 AND 100 OR json_type(x.value,'$.version') IS NOT 'integer' OR json_extract(x.value,'$.version') NOT BETWEEN 1 AND 1000000000 OR NOT EXISTS(SELECT 1 FROM longitudinal_observation_versions a WHERE a.observation_id=json_extract(x.value,'$.id') AND a.version=json_extract(x.value,'$.version') AND a.store_id=NEW.store_id AND a.customer_id=NEW.customer_id AND a.created_at<=NEW.created_at)) OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.observations') GROUP BY json_extract(value,'$.id') HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'specialty review fixed observations'); END;

CREATE TRIGGER specialty_review_manifest_external_records BEFORE INSERT ON specialty_review_versions WHEN json_array_length(NEW.manifest_json,'$.external_records')>30 OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.external_records') x WHERE x.type<>'object' OR (SELECT count(*) FROM json_each(x.value))<>3 OR json_type(x.value,'$.id') IS NOT 'text' OR length(json_extract(x.value,'$.id')) NOT BETWEEN 1 AND 100 OR json_type(x.value,'$.version') IS NOT 'integer' OR json_extract(x.value,'$.version') NOT BETWEEN 1 AND 1000000000 OR json_type(x.value,'$.revision') IS NOT 'integer' OR json_extract(x.value,'$.revision') NOT BETWEEN 1 AND 1000000000 OR NOT EXISTS(SELECT 1 FROM external_record_events a WHERE a.record_id=json_extract(x.value,'$.id') AND a.version=json_extract(x.value,'$.version') AND a.revision=json_extract(x.value,'$.revision') AND a.store_id=NEW.store_id AND a.customer_id=NEW.customer_id AND a.created_at<=NEW.created_at)) OR EXISTS(SELECT 1 FROM json_each(NEW.manifest_json,'$.external_records') GROUP BY json_extract(value,'$.id') HAVING count(*)>1) BEGIN SELECT RAISE(ABORT,'specialty review fixed external_records'); END;

CREATE TRIGGER specialty_review_event_ready BEFORE INSERT ON specialty_review_events BEGIN
 SELECT CASE WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM specialty_review_journal WHERE store_id=NEW.store_id),1) OR NEW.revision<>coalesce((SELECT max(revision)+1 FROM specialty_review_events WHERE review_id=NEW.review_id),1) OR EXISTS(SELECT 1 FROM specialty_review_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.trace_sequence<>coalesce((SELECT max(sequence) FROM specialty_trace_journal WHERE store_id=NEW.store_id),0) OR NEW.parameter_sequence<>coalesce((SELECT max(sequence) FROM parameter_events WHERE order_id=(SELECT order_id FROM specialty_reviews WHERE id=NEW.review_id)),0) OR NEW.longitudinal_sequence<>coalesce((SELECT max(sequence) FROM longitudinal_journal WHERE store_id=NEW.store_id),0) OR NEW.referral_sequence<>coalesce((SELECT max(sequence) FROM referral_journal WHERE store_id=NEW.store_id),0) OR NOT EXISTS(SELECT 1 FROM specialty_reviews r JOIN specialty_review_versions v ON v.review_id=r.id JOIN specialty_case_events c ON c.case_id=r.case_id AND c.revision=NEW.case_revision WHERE r.id=NEW.review_id AND r.store_id=NEW.store_id AND r.customer_id=NEW.customer_id AND v.id=NEW.version_id AND v.version=(SELECT max(version) FROM specialty_review_versions WHERE review_id=r.id) AND v.created_at<=NEW.created_at AND c.sequence<=NEW.specialty_sequence AND c.revision=(SELECT max(revision) FROM specialty_case_events WHERE case_id=r.case_id AND sequence<=NEW.specialty_sequence) AND c.created_at<=NEW.created_at AND (NEW.action IN('create','revise') OR c.owner_id=NEW.created_by AND EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional'))) OR length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 THEN RAISE(ABORT,'specialty review current source/owner/journal') END;
 SELECT CASE WHEN NOT(NEW.action='create' AND NEW.revision=1 AND NEW.status='pending' AND EXISTS(SELECT 1 FROM specialty_reviews r JOIN specialty_review_versions v ON v.review_id=r.id WHERE r.id=NEW.review_id AND v.id=NEW.version_id AND v.version=1 AND r.created_at=NEW.created_at AND r.created_by=NEW.created_by AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by AND v.base_sequence+1=NEW.sequence) OR NEW.action='revise' AND NEW.status='pending' AND EXISTS(SELECT 1 FROM specialty_review_current e JOIN specialty_review_versions ov ON ov.id=e.version_id JOIN specialty_review_versions v ON v.id=NEW.version_id WHERE e.review_id=NEW.review_id AND e.status IN('pending','confirmed') AND v.version=ov.version+1 AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by AND v.base_sequence+1=NEW.sequence) OR NEW.action NOT IN('create','revise') AND EXISTS(SELECT 1 FROM specialty_review_current e WHERE e.review_id=NEW.review_id AND e.version_id=NEW.version_id AND (NEW.action='confirm' AND e.status='pending' AND NEW.status='confirmed' OR NEW.action='close' AND e.status='confirmed' AND NEW.status='closed' OR NEW.action='cancel' AND e.status='pending' AND NEW.status='cancelled'))) THEN RAISE(ABORT,'specialty review transition') END;
 SELECT CASE WHEN NEW.effect_case_event_id IS NULL AND NEW.specialty_sequence<>coalesce((SELECT max(sequence) FROM specialty_journal WHERE store_id=NEW.store_id),0) OR NEW.effect_case_event_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM specialty_reviews r JOIN specialty_case_events c ON c.case_id=r.case_id WHERE r.id=NEW.review_id AND NEW.action='confirm' AND NEW.decision IN('pause','stop') AND c.id=NEW.effect_case_event_id AND c.action=NEW.decision AND c.revision=NEW.case_revision+1 AND c.sequence=NEW.specialty_sequence+1 AND c.sequence=(SELECT max(sequence) FROM specialty_journal WHERE store_id=NEW.store_id) AND c.created_at=NEW.created_at AND c.created_by=NEW.created_by AND c.note=NEW.opinion_note AND c.next_step=NEW.next_step AND c.reason=NEW.reason) OR NEW.action='confirm' AND NEW.decision IN('pause','stop') AND NEW.effect_case_event_id IS NULL THEN RAISE(ABORT,'specialty review explicit clinical effect') END;
 SELECT CASE WHEN NEW.action='confirm' AND (length(NEW.evaluated_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.evaluated_at) IS NOT NEW.evaluated_at OR NEW.evaluated_at>NEW.created_at OR NEW.evaluated_at<(SELECT reported_at FROM specialty_review_versions WHERE id=NEW.version_id) OR length(trim(NEW.opinion_note)) NOT BETWEEN 1 AND 3000 OR length(NEW.opinion_note)>3000) THEN RAISE(ABORT,'specialty review actual professional opinion') END;
 SELECT CASE WHEN NEW.action='confirm' AND NEW.decision='continue' AND NOT EXISTS(SELECT 1 FROM specialty_reviews r JOIN specialty_trace_context c ON c.id=r.link_id WHERE r.id=NEW.review_id AND c.can_execute=1 AND c.case_version=r.case_version AND c.approval_id=NEW.approval_id) OR (NEW.action<>'confirm' OR NEW.decision<>'continue') AND NEW.approval_id IS NOT NULL THEN RAISE(ABORT,'specialty review continued use source held') END;
 END;

CREATE TRIGGER specialty_review_confirm_observations BEFORE INSERT ON specialty_review_events WHEN NEW.action IN('create','revise','confirm') AND EXISTS(SELECT 1 FROM specialty_review_versions v,json_each(v.manifest_json,'$.observations') x WHERE v.id=NEW.version_id AND NOT EXISTS(SELECT 1 FROM longitudinal_observation_versions a WHERE a.observation_id=json_extract(x.value,'$.id') AND a.version=json_extract(x.value,'$.version') AND a.sequence<=NEW.longitudinal_sequence AND a.version=(SELECT max(version) FROM longitudinal_observation_versions WHERE observation_id=a.observation_id AND sequence<=NEW.longitudinal_sequence))) BEGIN SELECT RAISE(ABORT,'specialty review latest observations'); END;

CREATE TRIGGER specialty_review_confirm_external_records BEFORE INSERT ON specialty_review_events WHEN NEW.action IN('create','revise','confirm') AND EXISTS(SELECT 1 FROM specialty_review_versions v,json_each(v.manifest_json,'$.external_records') x WHERE v.id=NEW.version_id AND NOT EXISTS(SELECT 1 FROM external_record_events a WHERE a.record_id=json_extract(x.value,'$.id') AND a.revision=json_extract(x.value,'$.revision') AND a.sequence<=NEW.referral_sequence AND a.revision=(SELECT max(revision) FROM external_record_events WHERE record_id=a.record_id AND sequence<=NEW.referral_sequence) AND a.status='confirmed' AND a.version=json_extract(x.value,'$.version'))) BEGIN SELECT RAISE(ABORT,'specialty review latest external_records'); END;

CREATE TRIGGER specialty_review_confirm_materials BEFORE INSERT ON specialty_review_events WHEN NEW.action IN('create','revise','confirm') AND EXISTS(SELECT 1 FROM specialty_review_versions v,json_each(v.manifest_json,'$.attachments') x JOIN attachments a ON a.id=x.value WHERE v.id=NEW.version_id AND a.revoked_at IS NOT NULL) BEGIN SELECT RAISE(ABORT,'specialty review material unavailable'); END;

CREATE TRIGGER specialty_review_link_ready BEFORE INSERT ON specialty_review_links WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM specialty_review_journal WHERE store_id=NEW.store_id),1) OR NEW.revision<>coalesce((SELECT max(revision)+1 FROM specialty_review_links WHERE review_id=NEW.review_id),1) OR NOT EXISTS(SELECT 1 FROM specialty_reviews r JOIN specialty_review_current e ON e.review_id=r.id WHERE r.id=NEW.review_id AND r.store_id=NEW.store_id AND r.customer_id=NEW.customer_id AND e.revision=NEW.review_revision AND e.version_id=NEW.version_id AND e.status NOT IN('closed','cancelled') AND e.created_at<=NEW.created_at) OR EXISTS(SELECT 1 FROM specialty_review_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.longitudinal_sequence<>coalesce((SELECT max(sequence) FROM longitudinal_journal WHERE store_id=NEW.store_id),0) OR NEW.referral_sequence<>coalesce((SELECT max(sequence) FROM referral_journal WHERE store_id=NEW.store_id),0) OR NEW.contact_sequence<>coalesce((SELECT max(sequence) FROM contact_journal WHERE store_id=NEW.store_id),0) OR json_type(NEW.source_json) IS NOT 'object' OR (SELECT count(*) FROM json_each(NEW.source_json))<>2 OR json_type(NEW.source_json,'$.id') IS NOT 'text' OR length(json_extract(NEW.source_json,'$.id')) NOT BETWEEN 1 AND 100 OR json_type(NEW.source_json,'$.revision') IS NOT 'integer' OR json_extract(NEW.source_json,'$.revision') NOT BETWEEN 1 AND 1000000000 OR length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 OR length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 BEGIN SELECT RAISE(ABORT,'specialty review followup link source/journal'); END;

CREATE TRIGGER specialty_review_link_review_plan BEFORE INSERT ON specialty_review_links WHEN NEW.kind='review_plan' AND NOT EXISTS(SELECT 1 FROM review_plan_events a WHERE a.plan_id=json_extract(NEW.source_json,'$.id') AND a.revision=json_extract(NEW.source_json,'$.revision') AND a.sequence<=NEW.longitudinal_sequence AND a.customer_id=NEW.customer_id AND a.store_id=NEW.store_id AND a.created_at<=NEW.created_at AND a.revision=(SELECT max(revision) FROM review_plan_events WHERE plan_id=a.plan_id AND sequence<=NEW.longitudinal_sequence)) BEGIN SELECT RAISE(ABORT,'specialty review real review_plan source'); END;

CREATE TRIGGER specialty_review_link_referral BEFORE INSERT ON specialty_review_links WHEN NEW.kind='referral' AND NOT EXISTS(SELECT 1 FROM referral_events a WHERE a.case_id=json_extract(NEW.source_json,'$.id') AND a.revision=json_extract(NEW.source_json,'$.revision') AND a.sequence<=NEW.referral_sequence AND a.customer_id=NEW.customer_id AND a.store_id=NEW.store_id AND a.created_at<=NEW.created_at AND a.revision=(SELECT max(revision) FROM referral_events WHERE case_id=a.case_id AND sequence<=NEW.referral_sequence)) BEGIN SELECT RAISE(ABORT,'specialty review real referral source'); END;

CREATE TRIGGER specialty_review_link_contact_attempt BEFORE INSERT ON specialty_review_links WHEN NEW.kind='contact_attempt' AND NOT EXISTS(SELECT 1 FROM contact_attempts a WHERE a.id=json_extract(NEW.source_json,'$.id') AND a.case_revision=json_extract(NEW.source_json,'$.revision') AND a.sequence<=NEW.contact_sequence AND a.customer_id=NEW.customer_id AND a.store_id=NEW.store_id AND a.created_at<=NEW.created_at AND EXISTS(SELECT 1 FROM contact_cases c WHERE c.id=a.case_id AND c.category='service')) BEGIN SELECT RAISE(ABORT,'specialty review real contact_attempt source'); END;
