CREATE TABLE specialty_continuity_boundary(id INTEGER PRIMARY KEY CHECK(id=1),operation_rowid INTEGER NOT NULL CHECK(operation_rowid>=0));
INSERT INTO specialty_continuity_boundary SELECT 1,coalesce(max(rowid),0) FROM aftercare_replacement_operations;
CREATE TABLE specialty_continuity_sources(plan_id TEXT PRIMARY KEY REFERENCES aftercare_replacements(id),aftercare_id TEXT NOT NULL REFERENCES aftercare_cases(id),delivery_id TEXT NOT NULL REFERENCES fulfillment_events(id),original_link_id TEXT NOT NULL REFERENCES specialty_order_links(id),original_case_id TEXT NOT NULL REFERENCES specialty_cases(id),new_link_id TEXT NOT NULL UNIQUE REFERENCES specialty_order_links(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),source_note TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id));
CREATE TABLE specialty_continuity_events(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES specialty_continuity_sources(plan_id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),action TEXT NOT NULL CHECK(action IN('approve','revoke')),status TEXT NOT NULL CHECK(status=CASE action WHEN 'approve' THEN 'active' ELSE 'revoked' END),review_id TEXT NOT NULL REFERENCES specialty_reviews(id),review_version_id TEXT NOT NULL REFERENCES specialty_review_versions(id),review_revision INTEGER NOT NULL,opinion_event_id TEXT NOT NULL REFERENCES specialty_review_events(id),new_approval_id TEXT NOT NULL REFERENCES specialty_order_approvals(id),specialty_sequence INTEGER NOT NULL,trace_sequence INTEGER NOT NULL,review_sequence INTEGER NOT NULL,longitudinal_sequence INTEGER NOT NULL,referral_sequence INTEGER NOT NULL,parameter_sequence INTEGER NOT NULL,case_revision INTEGER NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(plan_id,revision),UNIQUE(store_id,sequence));
CREATE TABLE specialty_continuity_execution_refs(operation_id TEXT PRIMARY KEY REFERENCES aftercare_replacement_operations(id),approval_event_id TEXT NOT NULL REFERENCES specialty_continuity_events(id),continuity_sequence INTEGER NOT NULL,review_sequence INTEGER NOT NULL,longitudinal_sequence INTEGER NOT NULL,referral_sequence INTEGER NOT NULL,specialty_sequence INTEGER NOT NULL,trace_sequence INTEGER NOT NULL,parameter_sequence INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE specialty_archives(id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES specialty_cases(id),store_id TEXT NOT NULL REFERENCES stores(id),customer_id TEXT NOT NULL REFERENCES customers(id),revision INTEGER NOT NULL CHECK(revision>=1),sequence INTEGER NOT NULL CHECK(sequence>=1),case_revision INTEGER NOT NULL,specialty_sequence INTEGER NOT NULL,trace_sequence INTEGER NOT NULL,care_sequence INTEGER NOT NULL,review_sequence INTEGER NOT NULL,cutoffs_json TEXT NOT NULL CHECK(json_valid(cutoffs_json)),snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)),snapshot_sha256 TEXT NOT NULL CHECK(length(snapshot_sha256)=64 AND snapshot_sha256 NOT GLOB '*[^0-9a-f]*'),note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),UNIQUE(store_id,sequence));
CREATE VIEW specialty_continuity_journal AS SELECT id,store_id,sequence,created_at,'event' kind FROM specialty_continuity_events UNION ALL SELECT id,store_id,sequence,created_at,'archive' FROM specialty_archives;
CREATE VIEW specialty_continuity_current AS SELECT e.* FROM specialty_continuity_events e WHERE revision=(SELECT max(revision) FROM specialty_continuity_events WHERE plan_id=e.plan_id);
CREATE VIEW specialty_continuity_review_context AS SELECT r.id,r.delivery_id,r.customer_id,r.store_id,e.revision,e.version_id,e.status,o.id opinion_event_id,
CASE WHEN e.status IN('confirmed','closed') AND o.decision IN('continue','adjust') AND NOT EXISTS(SELECT 1 FROM json_each(v.manifest_json,'$.attachments') x JOIN attachments a ON a.id=x.value WHERE a.revoked_at IS NOT NULL) AND NOT EXISTS(SELECT 1 FROM json_each(v.manifest_json,'$.observations') x WHERE json_extract(x.value,'$.version') IS NOT (SELECT max(version) FROM longitudinal_observation_versions WHERE observation_id=json_extract(x.value,'$.id'))) AND NOT EXISTS(SELECT 1 FROM json_each(v.manifest_json,'$.external_records') x WHERE NOT EXISTS(SELECT 1 FROM external_record_current a WHERE a.record_id=json_extract(x.value,'$.id') AND a.version=json_extract(x.value,'$.version') AND a.revision=json_extract(x.value,'$.revision') AND a.status='confirmed')) THEN 1 ELSE 0 END can_adopt
FROM specialty_reviews r JOIN specialty_review_current e ON e.review_id=r.id JOIN specialty_review_versions v ON v.id=e.version_id LEFT JOIN specialty_review_events o ON o.review_id=r.id AND o.version_id=e.version_id AND o.action='confirm';
CREATE VIEW specialty_continuity_context AS SELECT s.*,p.new_order_id,e.id approval_event_id,e.revision,e.status,e.review_id,e.review_version_id,e.opinion_event_id,e.new_approval_id,c.case_id new_case_id,
CASE WHEN e.status='active' AND r.can_adopt=1 AND r.delivery_id=s.delivery_id AND r.version_id=e.review_version_id AND r.opinion_event_id=e.opinion_event_id AND c.can_execute=1 AND c.approval_id=e.new_approval_id AND c.case_revision=e.case_revision AND ce.owner_id=e.created_by AND pe.status IN('pending','approved') THEN 1 ELSE 0 END can_adopt,
CASE WHEN e.status='active' AND r.can_adopt=1 AND r.delivery_id=s.delivery_id AND r.version_id=e.review_version_id AND r.opinion_event_id=e.opinion_event_id AND c.can_execute=1 AND c.approval_id=e.new_approval_id AND c.case_revision=e.case_revision AND ce.owner_id=e.created_by AND pe.status='approved' AND json_extract(a.snapshot_json,'$.status')='running' THEN 1 ELSE 0 END can_execute
FROM specialty_continuity_sources s JOIN aftercare_replacements p ON p.id=s.plan_id LEFT JOIN specialty_continuity_current e ON e.plan_id=s.plan_id LEFT JOIN specialty_continuity_review_context r ON r.id=e.review_id JOIN specialty_trace_context c ON c.id=s.new_link_id JOIN specialty_case_current ce ON ce.case_id=c.case_id JOIN aftercare_replacement_events pe ON pe.plan_id=p.id AND pe.revision=(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=p.id) JOIN aftercare_events a ON a.case_id=p.case_id AND a.revision=(SELECT max(revision) FROM aftercare_events WHERE case_id=p.case_id);
CREATE VIEW specialty_continuity_positive_operations AS SELECT op.* FROM aftercare_replacement_operations op WHERE op.record_type='processing_job' OR op.record_type='outbound' OR op.record_type='reservation' AND EXISTS(SELECT 1 FROM inventory_order_events WHERE id=op.record_id AND action='reserve') OR op.record_type='payment' AND EXISTS(SELECT 1 FROM payment_events WHERE id=op.record_id AND action='receive') OR op.record_type='processing' AND EXISTS(SELECT 1 FROM processing_events WHERE id=op.record_id AND action IN('plan','start','complete')) OR op.record_type='fulfillment' AND EXISTS(SELECT 1 FROM fulfillment_events WHERE id=op.record_id AND action IN('check_pass','rework_start','rework_complete','deliver'));
CREATE TRIGGER specialty_continuity_boundary_no_update BEFORE UPDATE ON specialty_continuity_boundary BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_boundary_no_delete BEFORE DELETE ON specialty_continuity_boundary BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_sources_no_update BEFORE UPDATE ON specialty_continuity_sources BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_sources_no_delete BEFORE DELETE ON specialty_continuity_sources BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_events_no_update BEFORE UPDATE ON specialty_continuity_events BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_events_no_delete BEFORE DELETE ON specialty_continuity_events BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_execution_refs_no_update BEFORE UPDATE ON specialty_continuity_execution_refs BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_execution_refs_no_delete BEFORE DELETE ON specialty_continuity_execution_refs BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_archives_no_update BEFORE UPDATE ON specialty_archives BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_archives_no_delete BEFORE DELETE ON specialty_archives BEGIN SELECT RAISE(ABORT,'specialty continuity immutable'); END;
CREATE TRIGGER specialty_continuity_boundary_no_insert BEFORE INSERT ON specialty_continuity_boundary BEGIN SELECT RAISE(ABORT,'specialty continuity immutable boundary'); END;
CREATE TRIGGER specialty_continuity_sources_actor BEFORE INSERT ON specialty_continuity_sources WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty continuity actor/time'); END;
CREATE TRIGGER specialty_continuity_events_actor BEFORE INSERT ON specialty_continuity_events WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty continuity actor/time'); END;
CREATE TRIGGER specialty_archives_actor BEFORE INSERT ON specialty_archives WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=NEW.created_by AND u.active=1 AND u.store_id=NEW.store_id AND coalesce(s.must_change_password,0)=0 AND u.role IN('manager','reception','professional')) BEGIN SELECT RAISE(ABORT,'specialty continuity actor/time'); END;
CREATE TRIGGER specialty_continuity_events_notes BEFORE INSERT ON specialty_continuity_events WHEN length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 BEGIN SELECT RAISE(ABORT,'specialty continuity actual next step'); END;
CREATE TRIGGER specialty_archives_notes BEFORE INSERT ON specialty_archives WHEN length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000 OR length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300 OR length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000 BEGIN SELECT RAISE(ABORT,'specialty continuity actual next step'); END;
CREATE TRIGGER specialty_continuity_source_ready BEFORE INSERT ON specialty_continuity_sources WHEN length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000 OR NOT EXISTS(SELECT 1 FROM aftercare_replacements p JOIN aftercare_cases a ON a.id=p.case_id JOIN specialty_execution_refs r ON r.event_id=a.delivery_id AND r.kind='fulfillment' JOIN specialty_order_approvals ap ON ap.id=r.approval_id JOIN specialty_order_links old ON old.id=ap.link_id JOIN specialty_trace_context n ON n.order_id=p.new_order_id JOIN specialty_case_current c ON c.case_id=n.case_id WHERE p.id=NEW.plan_id AND p.case_id=NEW.aftercare_id AND a.delivery_id=NEW.delivery_id AND old.id=NEW.original_link_id AND old.case_id=NEW.original_case_id AND n.id=NEW.new_link_id AND n.store_id=a.store_id AND n.customer_id=a.customer_id AND NEW.store_id=a.store_id AND NEW.customer_id=a.customer_id AND n.can_execute=1 AND c.owner_id=NEW.created_by AND NEW.created_at>=p.created_at AND EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role='professional')) BEGIN SELECT RAISE(ABORT,'specialty continuity independent new professional source'); END;
CREATE TRIGGER specialty_continuity_event_ready BEFORE INSERT ON specialty_continuity_events BEGIN
SELECT CASE WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM specialty_continuity_journal WHERE store_id=NEW.store_id),1) OR NEW.revision<>coalesce((SELECT max(revision)+1 FROM specialty_continuity_events WHERE plan_id=NEW.plan_id),1) OR EXISTS(SELECT 1 FROM specialty_continuity_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NEW.specialty_sequence<>coalesce((SELECT max(sequence) FROM specialty_journal WHERE store_id=NEW.store_id),0) OR NEW.trace_sequence<>coalesce((SELECT max(sequence) FROM specialty_trace_journal WHERE store_id=NEW.store_id),0) OR NEW.review_sequence<>coalesce((SELECT max(sequence) FROM specialty_review_journal WHERE store_id=NEW.store_id),0) OR NEW.longitudinal_sequence<>coalesce((SELECT max(sequence) FROM longitudinal_journal WHERE store_id=NEW.store_id),0) OR NEW.referral_sequence<>coalesce((SELECT max(sequence) FROM referral_journal WHERE store_id=NEW.store_id),0) OR NOT EXISTS(SELECT 1 FROM specialty_continuity_sources s JOIN specialty_order_links l ON l.id=s.new_link_id JOIN specialty_case_current c ON c.case_id=l.case_id JOIN users u ON u.id=NEW.created_by WHERE s.plan_id=NEW.plan_id AND s.store_id=NEW.store_id AND s.customer_id=NEW.customer_id AND s.created_at<=NEW.created_at AND c.owner_id=NEW.created_by AND u.role='professional' AND c.revision=NEW.case_revision AND c.created_at<=NEW.created_at AND NEW.parameter_sequence=coalesce((SELECT max(sequence) FROM parameter_events WHERE order_id=l.order_id),0)) THEN RAISE(ABORT,'specialty continuity current owner/sequence') END;
SELECT CASE WHEN NEW.revision=1 AND NOT EXISTS(SELECT 1 FROM specialty_continuity_sources s WHERE s.plan_id=NEW.plan_id AND s.created_at=NEW.created_at AND s.created_by=NEW.created_by AND NEW.action='approve') THEN RAISE(ABORT,'specialty continuity first source pairing') END;
SELECT CASE WHEN NEW.action='approve' AND NOT EXISTS(SELECT 1 FROM specialty_continuity_sources s JOIN specialty_continuity_review_context r ON r.id=NEW.review_id JOIN specialty_trace_context n ON n.id=s.new_link_id JOIN aftercare_replacement_events p ON p.plan_id=s.plan_id AND p.revision=(SELECT max(revision) FROM aftercare_replacement_events WHERE plan_id=s.plan_id) WHERE s.plan_id=NEW.plan_id AND r.can_adopt=1 AND r.delivery_id=s.delivery_id AND r.customer_id=s.customer_id AND r.store_id=s.store_id AND r.revision=NEW.review_revision AND r.version_id=NEW.review_version_id AND r.opinion_event_id=NEW.opinion_event_id AND n.can_execute=1 AND n.approval_id=NEW.new_approval_id AND p.status IN('pending','approved') AND p.created_at<=NEW.created_at) OR NEW.action='revoke' AND NOT EXISTS(SELECT 1 FROM specialty_continuity_current e WHERE e.plan_id=NEW.plan_id AND e.status='active' AND e.review_id=NEW.review_id AND e.review_version_id=NEW.review_version_id AND e.review_revision=NEW.review_revision AND e.opinion_event_id=NEW.opinion_event_id AND e.new_approval_id=NEW.new_approval_id) THEN RAISE(ABORT,'specialty continuity actual professional adoption/withdrawal') END;
END;
CREATE TRIGGER specialty_continuity_operation_gate BEFORE INSERT ON aftercare_replacement_operations WHEN EXISTS(SELECT 1 FROM aftercare_cases c JOIN specialty_execution_refs r ON r.event_id=c.delivery_id AND r.kind='fulfillment' WHERE c.id=NEW.case_id) AND (NEW.record_type IN('processing_job','outbound') OR NEW.record_type='reservation' AND EXISTS(SELECT 1 FROM inventory_order_events WHERE id=NEW.record_id AND action='reserve') OR NEW.record_type='payment' AND EXISTS(SELECT 1 FROM payment_events WHERE id=NEW.record_id AND action='receive') OR NEW.record_type='processing' AND EXISTS(SELECT 1 FROM processing_events WHERE id=NEW.record_id AND action IN('plan','start','complete')) OR NEW.record_type='fulfillment' AND EXISTS(SELECT 1 FROM fulfillment_events WHERE id=NEW.record_id AND action IN('check_pass','rework_start','rework_complete','deliver'))) AND NOT EXISTS(SELECT 1 FROM specialty_continuity_context c WHERE c.plan_id=NEW.plan_id AND c.can_execute=1 AND (SELECT created_at FROM specialty_continuity_events WHERE id=c.approval_event_id)<=NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty continuity replacement source held'); END;
CREATE TRIGGER specialty_continuity_operation_capture AFTER INSERT ON aftercare_replacement_operations WHEN EXISTS(SELECT 1 FROM specialty_continuity_positive_operations WHERE id=NEW.id) AND EXISTS(SELECT 1 FROM aftercare_cases c JOIN specialty_execution_refs r ON r.event_id=c.delivery_id AND r.kind='fulfillment' WHERE c.id=NEW.case_id) BEGIN
INSERT INTO specialty_continuity_execution_refs SELECT NEW.id,c.approval_event_id,coalesce((SELECT max(sequence) FROM specialty_continuity_journal WHERE store_id=c.store_id),0),coalesce((SELECT max(sequence) FROM specialty_review_journal WHERE store_id=c.store_id),0),coalesce((SELECT max(sequence) FROM longitudinal_journal WHERE store_id=c.store_id),0),coalesce((SELECT max(sequence) FROM referral_journal WHERE store_id=c.store_id),0),coalesce((SELECT max(sequence) FROM specialty_journal WHERE store_id=c.store_id),0),coalesce((SELECT max(sequence) FROM specialty_trace_journal WHERE store_id=c.store_id),0),coalesce((SELECT max(sequence) FROM parameter_events WHERE order_id=c.new_order_id),0),NEW.created_at FROM specialty_continuity_context c WHERE c.plan_id=NEW.plan_id AND c.can_execute=1;
END;
CREATE TRIGGER specialty_continuity_execution_ready BEFORE INSERT ON specialty_continuity_execution_refs WHEN NOT EXISTS(SELECT 1 FROM specialty_continuity_positive_operations WHERE id=NEW.operation_id) OR NOT EXISTS(SELECT 1 FROM aftercare_replacement_operations op JOIN specialty_continuity_context c ON c.plan_id=op.plan_id JOIN specialty_continuity_events e ON e.id=NEW.approval_event_id WHERE op.id=NEW.operation_id AND c.approval_event_id=e.id AND c.can_execute=1 AND op.created_at=NEW.created_at AND e.created_at<=NEW.created_at AND NEW.continuity_sequence=coalesce((SELECT max(sequence) FROM specialty_continuity_journal WHERE store_id=c.store_id),0) AND NEW.review_sequence=coalesce((SELECT max(sequence) FROM specialty_review_journal WHERE store_id=c.store_id),0) AND NEW.longitudinal_sequence=coalesce((SELECT max(sequence) FROM longitudinal_journal WHERE store_id=c.store_id),0) AND NEW.referral_sequence=coalesce((SELECT max(sequence) FROM referral_journal WHERE store_id=c.store_id),0) AND NEW.specialty_sequence=coalesce((SELECT max(sequence) FROM specialty_journal WHERE store_id=c.store_id),0) AND NEW.trace_sequence=coalesce((SELECT max(sequence) FROM specialty_trace_journal WHERE store_id=c.store_id),0) AND NEW.parameter_sequence=coalesce((SELECT max(sequence) FROM parameter_events WHERE order_id=c.new_order_id),0)) BEGIN SELECT RAISE(ABORT,'specialty continuity captured execution'); END;
CREATE TRIGGER specialty_archive_ready BEFORE INSERT ON specialty_archives WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM specialty_continuity_journal WHERE store_id=NEW.store_id),1) OR NEW.revision<>coalesce((SELECT max(revision)+1 FROM specialty_archives WHERE case_id=NEW.case_id),1) OR EXISTS(SELECT 1 FROM specialty_continuity_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NOT EXISTS(SELECT 1 FROM specialty_cases c JOIN specialty_case_current e ON e.case_id=c.id WHERE c.id=NEW.case_id AND c.store_id=NEW.store_id AND c.customer_id=NEW.customer_id AND e.revision=NEW.case_revision AND e.created_at<=NEW.created_at) OR NEW.specialty_sequence<>coalesce((SELECT max(sequence) FROM specialty_journal WHERE store_id=NEW.store_id),0) OR NEW.trace_sequence<>coalesce((SELECT max(sequence) FROM specialty_trace_journal WHERE store_id=NEW.store_id),0) OR NEW.care_sequence<>coalesce((SELECT max(sequence) FROM specialty_care_events WHERE store_id=NEW.store_id),0) OR NEW.review_sequence<>coalesce((SELECT max(sequence) FROM specialty_review_journal WHERE store_id=NEW.store_id),0) OR json_type(NEW.snapshot_json) IS NOT 'object' OR json_extract(NEW.snapshot_json,'$.case.id') IS NOT NEW.case_id OR json_extract(NEW.snapshot_json,'$.case.revision') IS NOT NEW.case_revision OR length(NEW.snapshot_json)>1048576 BEGIN SELECT RAISE(ABORT,'specialty archive source index'); END;
CREATE TRIGGER specialty_archive_cutoff_shape BEFORE INSERT ON specialty_archives WHEN json_type(NEW.cutoffs_json) IS NOT 'object' OR (SELECT count(*) FROM json_each(NEW.cutoffs_json))<>30 OR EXISTS(SELECT 1 FROM json_each(NEW.cutoffs_json) WHERE key NOT IN('specialty_protocols','specialty_protocol_versions','specialty_protocol_events','specialty_cases','specialty_case_versions','specialty_case_events','specialty_consents','specialty_consent_events','specialty_order_links','specialty_order_approvals','specialty_product_lots','specialty_lot_versions','specialty_care_records','specialty_care_versions','specialty_care_events','specialty_reviews','specialty_review_versions','specialty_review_events','specialty_review_links','specialty_continuity_sources','specialty_continuity_events','aftercare_cases','aftercare_events','aftercare_replacements','aftercare_replacement_events','aftercare_work_events','aftercare_disposition_events','refund_events','fulfillment_events','inventory_outbounds') OR type<>'integer' OR value<0) BEGIN SELECT RAISE(ABORT,'specialty archive cutoff shape'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_protocols BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_protocols') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_protocols) OR EXISTS(SELECT 1 FROM specialty_protocols WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_protocols') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_protocol_versions BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_protocol_versions') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_protocol_versions) OR EXISTS(SELECT 1 FROM specialty_protocol_versions WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_protocol_versions') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_protocol_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_protocol_events') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_protocol_events) OR EXISTS(SELECT 1 FROM specialty_protocol_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_protocol_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_cases BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_cases') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_cases) OR EXISTS(SELECT 1 FROM specialty_cases WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_cases') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_case_versions BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_case_versions') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_case_versions) OR EXISTS(SELECT 1 FROM specialty_case_versions WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_case_versions') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_case_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_case_events') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_case_events) OR EXISTS(SELECT 1 FROM specialty_case_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_case_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_consents BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_consents') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_consents) OR EXISTS(SELECT 1 FROM specialty_consents WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_consents') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_consent_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_consent_events') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_consent_events) OR EXISTS(SELECT 1 FROM specialty_consent_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_consent_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_order_links BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_order_links') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_order_links) OR EXISTS(SELECT 1 FROM specialty_order_links WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_order_links') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_order_approvals BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_order_approvals') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_order_approvals) OR EXISTS(SELECT 1 FROM specialty_order_approvals WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_order_approvals') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_product_lots BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_product_lots') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_product_lots) OR EXISTS(SELECT 1 FROM specialty_product_lots WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_product_lots') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_lot_versions BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_lot_versions') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_lot_versions) OR EXISTS(SELECT 1 FROM specialty_lot_versions WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_lot_versions') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_care_records BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_care_records') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_care_records) OR EXISTS(SELECT 1 FROM specialty_care_records WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_care_records') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_care_versions BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_care_versions') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_care_versions) OR EXISTS(SELECT 1 FROM specialty_care_versions WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_care_versions') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_care_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_care_events') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_care_events) OR EXISTS(SELECT 1 FROM specialty_care_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_care_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_reviews BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_reviews') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_reviews) OR EXISTS(SELECT 1 FROM specialty_reviews WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_reviews') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_review_versions BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_review_versions') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_review_versions) OR EXISTS(SELECT 1 FROM specialty_review_versions WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_review_versions') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_review_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_review_events') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_review_events) OR EXISTS(SELECT 1 FROM specialty_review_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_review_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_review_links BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_review_links') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_review_links) OR EXISTS(SELECT 1 FROM specialty_review_links WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_review_links') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_continuity_sources BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_continuity_sources') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_continuity_sources) OR EXISTS(SELECT 1 FROM specialty_continuity_sources WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_continuity_sources') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_specialty_continuity_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.specialty_continuity_events') IS NOT (SELECT coalesce(max(rowid),0) FROM specialty_continuity_events) OR EXISTS(SELECT 1 FROM specialty_continuity_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.specialty_continuity_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_aftercare_cases BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.aftercare_cases') IS NOT (SELECT coalesce(max(rowid),0) FROM aftercare_cases) OR EXISTS(SELECT 1 FROM aftercare_cases WHERE rowid<=json_extract(NEW.cutoffs_json,'$.aftercare_cases') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_aftercare_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.aftercare_events') IS NOT (SELECT coalesce(max(rowid),0) FROM aftercare_events) OR EXISTS(SELECT 1 FROM aftercare_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.aftercare_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_aftercare_replacements BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.aftercare_replacements') IS NOT (SELECT coalesce(max(rowid),0) FROM aftercare_replacements) OR EXISTS(SELECT 1 FROM aftercare_replacements WHERE rowid<=json_extract(NEW.cutoffs_json,'$.aftercare_replacements') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_aftercare_replacement_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.aftercare_replacement_events') IS NOT (SELECT coalesce(max(rowid),0) FROM aftercare_replacement_events) OR EXISTS(SELECT 1 FROM aftercare_replacement_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.aftercare_replacement_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_aftercare_work_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.aftercare_work_events') IS NOT (SELECT coalesce(max(rowid),0) FROM aftercare_work_events) OR EXISTS(SELECT 1 FROM aftercare_work_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.aftercare_work_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_aftercare_disposition_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.aftercare_disposition_events') IS NOT (SELECT coalesce(max(rowid),0) FROM aftercare_disposition_events) OR EXISTS(SELECT 1 FROM aftercare_disposition_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.aftercare_disposition_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_refund_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.refund_events') IS NOT (SELECT coalesce(max(rowid),0) FROM refund_events) OR EXISTS(SELECT 1 FROM refund_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.refund_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_fulfillment_events BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.fulfillment_events') IS NOT (SELECT coalesce(max(rowid),0) FROM fulfillment_events) OR EXISTS(SELECT 1 FROM fulfillment_events WHERE rowid<=json_extract(NEW.cutoffs_json,'$.fulfillment_events') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
CREATE TRIGGER specialty_archive_cutoff_inventory_outbounds BEFORE INSERT ON specialty_archives WHEN json_extract(NEW.cutoffs_json,'$.inventory_outbounds') IS NOT (SELECT coalesce(max(rowid),0) FROM inventory_outbounds) OR EXISTS(SELECT 1 FROM inventory_outbounds WHERE rowid<=json_extract(NEW.cutoffs_json,'$.inventory_outbounds') AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'specialty archive exact source prefix'); END;
