-- Actual purchase receipts, explicit quality and references to the existing stock ledger.
CREATE TABLE purchase_receipts(id TEXT PRIMARY KEY,store_id TEXT NOT NULL REFERENCES stores(id),serial INTEGER NOT NULL CHECK(serial>0),receipt_number TEXT NOT NULL,order_event_id TEXT NOT NULL REFERENCES purchase_events(id),request_id TEXT NOT NULL REFERENCES purchase_requests(id),purchase_version_id TEXT NOT NULL REFERENCES purchase_versions(id),position INTEGER NOT NULL CHECK(position BETWEEN 1 AND 50),supplier_id TEXT NOT NULL REFERENCES suppliers(id),product_id TEXT NOT NULL REFERENCES retail_products(id),product_version INTEGER NOT NULL,received_quantity INTEGER NOT NULL CHECK(typeof(received_quantity)='integer' AND received_quantity BETWEEN 1 AND 1000000),bound_quantity INTEGER NOT NULL CHECK(typeof(bound_quantity)='integer' AND bound_quantity BETWEEN 0 AND received_quantity),received_at TEXT NOT NULL,receiver_label TEXT NOT NULL,delivery_reference TEXT,source_line_reference TEXT,source_note TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(store_id,serial),UNIQUE(store_id,receipt_number),FOREIGN KEY(product_id,product_version) REFERENCES retail_product_versions(product_id,version),CHECK((delivery_reference IS NULL)=(source_line_reference IS NULL)));
CREATE UNIQUE INDEX purchase_receipt_delivery_identity ON purchase_receipts(store_id,supplier_id,delivery_reference,source_line_reference) WHERE delivery_reference IS NOT NULL;
CREATE TABLE purchase_receipt_versions(id TEXT PRIMARY KEY,receipt_id TEXT NOT NULL REFERENCES purchase_receipts(id),store_id TEXT NOT NULL REFERENCES stores(id),version INTEGER NOT NULL CHECK(version>0),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),lot_status TEXT NOT NULL CHECK(lot_status IN('recorded','unknown')),lot_code TEXT,expiry_status TEXT NOT NULL CHECK(expiry_status IN('provided','unknown','not_applicable')),expiry_date TEXT,location_status TEXT NOT NULL CHECK(location_status IN('recorded','unknown')),location_note TEXT,manufacturer_note TEXT,source_note TEXT NOT NULL,source_reference TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(receipt_id,version),CHECK((lot_status='recorded')=(lot_code IS NOT NULL)),CHECK((expiry_status='provided')=(expiry_date IS NOT NULL)),CHECK((location_status='recorded')=(location_note IS NOT NULL)));
CREATE TABLE purchase_receipt_events(id TEXT PRIMARY KEY,receipt_id TEXT NOT NULL REFERENCES purchase_receipts(id),version_id TEXT NOT NULL REFERENCES purchase_receipt_versions(id),store_id TEXT NOT NULL REFERENCES stores(id),revision INTEGER NOT NULL CHECK(revision>0),sequence INTEGER NOT NULL CHECK(sequence>0),action TEXT NOT NULL CHECK(action IN('create','revise','quality_pass','quality_fail','inbound','cancel')),status TEXT NOT NULL CHECK(status IN('pending','passed','failed','posted','cancelled')),checked_at TEXT,requirement_source TEXT,require_lot INTEGER,require_expiry INTEGER,require_location INTEGER,checks_json TEXT,quality_event_id TEXT REFERENCES purchase_receipt_events(id),inbound_bucket TEXT CHECK(inbound_bucket IN('available','quarantined')),stock_sequence INTEGER,outbound_revision INTEGER,note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(receipt_id,revision),UNIQUE(store_id,sequence));
CREATE TABLE purchase_inbound_refs(event_id TEXT NOT NULL REFERENCES purchase_receipt_events(id),kind TEXT NOT NULL CHECK(kind IN('receive','isolate')),stock_event_id TEXT NOT NULL UNIQUE REFERENCES inventory_events(id),PRIMARY KEY(event_id,kind));
CREATE VIEW purchase_receiving_journal AS SELECT store_id,sequence,created_at,id FROM purchase_receipt_events;
CREATE VIEW purchase_receipt_current AS SELECT e.* FROM purchase_receipt_events e WHERE revision=(SELECT max(revision) FROM purchase_receipt_events WHERE receipt_id=e.receipt_id);
CREATE VIEW purchase_order_lines AS SELECT e.id order_event_id,e.request_id,e.version_id purchase_version_id,e.store_id,e.ordered_at,v.supplier_id,CAST(json_extract(j.value,'$.position') AS INTEGER) position,json_extract(j.value,'$.product_id') product_id,CAST(json_extract(j.value,'$.product_version') AS INTEGER) product_version,CAST(json_extract(j.value,'$.quantity') AS INTEGER) ordered_quantity FROM purchase_events e JOIN purchase_versions v ON v.id=e.version_id,json_each(v.items_json) j WHERE e.action='order';
CREATE TRIGGER purchase_receipt_source BEFORE INSERT ON purchase_receipts BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_order_lines l WHERE l.order_event_id=NEW.order_event_id AND l.request_id=NEW.request_id AND l.purchase_version_id=NEW.purchase_version_id AND l.position=NEW.position AND l.store_id=NEW.store_id AND l.supplier_id=NEW.supplier_id AND l.product_id=NEW.product_id AND l.product_version=NEW.product_version AND l.ordered_at<=NEW.received_at AND NEW.bound_quantity+coalesce((SELECT sum(r.bound_quantity) FROM purchase_receipts r LEFT JOIN purchase_receipt_current c ON c.receipt_id=r.id WHERE r.order_event_id=l.order_event_id AND r.position=l.position AND coalesce(c.status,'pending')<>'cancelled'),0)<=l.ordered_quantity) THEN RAISE(ABORT,'receiving original order/time/capacity') END;
 SELECT CASE WHEN NEW.serial<>coalesce((SELECT max(serial)+1 FROM purchase_receipts WHERE store_id=NEW.store_id),1) OR NEW.received_at>NEW.created_at OR length(NEW.received_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.received_at) IS NOT NEW.received_at THEN RAISE(ABORT,'receiving actual receipt time/serial') END;
END;
CREATE TRIGGER purchase_receipt_version_source BEFORE INSERT ON purchase_receipt_versions BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_receipts r WHERE r.id=NEW.receipt_id AND r.store_id=NEW.store_id AND r.created_at<=NEW.created_at) OR NEW.version<>coalesce((SELECT max(version)+1 FROM purchase_receipt_versions WHERE receipt_id=NEW.receipt_id),1) OR NEW.base_sequence<>coalesce((SELECT max(sequence) FROM purchase_receiving_journal WHERE store_id=NEW.store_id),0) OR EXISTS(SELECT 1 FROM purchase_receipt_current WHERE receipt_id=NEW.receipt_id AND status='cancelled') THEN RAISE(ABORT,'receiving original version/sequence') END;
 SELECT CASE WHEN NEW.expiry_date IS NOT NULL AND(length(NEW.expiry_date)<>10 OR date(NEW.expiry_date,'+0 days') IS NOT NEW.expiry_date) THEN RAISE(ABORT,'receiving actual expiry date') END;
END;
CREATE TRIGGER purchase_receipt_event_source BEFORE INSERT ON purchase_receipt_events BEGIN
 SELECT CASE WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM purchase_receiving_journal WHERE store_id=NEW.store_id),1) OR NEW.revision<>coalesce((SELECT max(revision)+1 FROM purchase_receipt_events WHERE receipt_id=NEW.receipt_id),1) OR EXISTS(SELECT 1 FROM purchase_receiving_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NOT EXISTS(SELECT 1 FROM purchase_receipt_versions v WHERE v.id=NEW.version_id AND v.receipt_id=NEW.receipt_id AND v.store_id=NEW.store_id AND v.version=(SELECT max(version) FROM purchase_receipt_versions WHERE receipt_id=NEW.receipt_id) AND v.created_at<=NEW.created_at) THEN RAISE(ABORT,'receiving current journal/version') END;
 SELECT CASE WHEN NOT(NEW.action='create' AND NEW.revision=1 AND NEW.status='pending' AND EXISTS(SELECT 1 FROM purchase_receipts r JOIN purchase_receipt_versions v ON v.receipt_id=r.id WHERE r.id=NEW.receipt_id AND v.id=NEW.version_id AND v.version=1 AND r.created_at=NEW.created_at AND v.created_at=NEW.created_at AND r.created_by=NEW.created_by AND v.created_by=NEW.created_by AND v.base_sequence+1=NEW.sequence) OR NEW.action='revise' AND EXISTS(SELECT 1 FROM purchase_receipt_current c JOIN purchase_receipt_versions o ON o.id=c.version_id JOIN purchase_receipt_versions v ON v.id=NEW.version_id WHERE c.receipt_id=NEW.receipt_id AND c.status<>'cancelled' AND v.version=o.version+1 AND v.base_sequence+1=NEW.sequence AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by AND NEW.status=CASE WHEN c.status='posted' THEN 'posted' ELSE 'pending' END) OR EXISTS(SELECT 1 FROM purchase_receipt_current c WHERE c.receipt_id=NEW.receipt_id AND c.version_id=NEW.version_id AND(NEW.action='quality_pass' AND c.status='pending' AND NEW.status='passed' OR NEW.action='quality_fail' AND c.status='pending' AND NEW.status='failed' OR NEW.action='inbound' AND c.status IN('pending','passed','failed') AND NEW.status='posted' OR NEW.action='cancel' AND c.status IN('pending','passed','failed') AND NEW.status='cancelled'))) THEN RAISE(ABORT,'receiving explicit transition') END;
 SELECT CASE WHEN NEW.action IN('quality_pass','quality_fail','inbound','cancel') AND NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role IN('manager','professional') AND (NEW.action IN('quality_pass','quality_fail') OR role='manager')) THEN RAISE(ABORT,'receiving quality/stock actor') END;
 SELECT CASE WHEN NEW.action IN('quality_pass','quality_fail') AND(NEW.checked_at IS NULL OR length(NEW.checked_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.checked_at) IS NOT NEW.checked_at OR NEW.checked_at>NEW.created_at OR NEW.checked_at<(SELECT received_at FROM purchase_receipts WHERE id=NEW.receipt_id) OR NEW.requirement_source IS NULL OR length(trim(NEW.requirement_source)) NOT BETWEEN 1 AND 2000 OR NEW.require_lot NOT IN(0,1) OR NEW.require_expiry NOT IN(0,1) OR NEW.require_location NOT IN(0,1) OR NEW.require_lot IS NULL OR NEW.require_expiry IS NULL OR NEW.require_location IS NULL OR NEW.checks_json IS NULL OR json_valid(NEW.checks_json)=0 OR json_type(NEW.checks_json)<>'array' OR json_array_length(NEW.checks_json) NOT BETWEEN 1 AND 30 OR EXISTS(SELECT 1 FROM json_each(NEW.checks_json) j WHERE json_type(j.value)<>'object' OR (SELECT count(*) FROM json_each(j.value))<>2 OR json_type(j.value,'$.label') IS NOT 'text' OR length(trim(json_extract(j.value,'$.label'))) NOT BETWEEN 1 AND 300 OR json_type(j.value,'$.result') IS NOT 'text' OR json_extract(j.value,'$.result') NOT IN('pass','fail')) OR (NEW.action='quality_pass' AND EXISTS(SELECT 1 FROM json_each(NEW.checks_json) j WHERE json_extract(j.value,'$.result')<>'pass')) OR (NEW.action='quality_fail' AND NOT EXISTS(SELECT 1 FROM json_each(NEW.checks_json) j WHERE json_extract(j.value,'$.result')='fail'))) THEN RAISE(ABORT,'receiving actual quality facts') END;
 SELECT CASE WHEN NEW.action='quality_pass' AND NOT EXISTS(SELECT 1 FROM purchase_receipt_versions v WHERE v.id=NEW.version_id AND(NEW.require_lot=0 OR v.lot_status='recorded') AND(NEW.require_expiry=0 OR v.expiry_status='provided') AND(NEW.require_location=0 OR v.location_status='recorded') AND(v.expiry_date IS NULL OR v.expiry_date>=substr(NEW.checked_at,1,10))) THEN RAISE(ABORT,'receiving required provenance/expiry') END;
 SELECT CASE WHEN NEW.action='inbound' AND(NEW.inbound_bucket IS NULL OR NEW.stock_sequence IS NULL OR NEW.outbound_revision IS NULL OR NOT EXISTS(SELECT 1 FROM purchase_receipts r WHERE r.id=NEW.receipt_id AND r.bound_quantity>0 AND NEW.stock_sequence=coalesce((SELECT max(sequence) FROM inventory_events WHERE product_id=r.product_id),0) AND NEW.outbound_revision=coalesce((SELECT max(outbound_revision) FROM inventory_outbounds WHERE product_id=r.product_id),0)) OR NEW.inbound_bucket='available' AND NOT EXISTS(SELECT 1 FROM purchase_receipt_current c JOIN purchase_receipt_versions v ON v.id=c.version_id WHERE c.receipt_id=NEW.receipt_id AND c.status='passed' AND c.id=NEW.quality_event_id AND c.version_id=NEW.version_id AND(v.expiry_date IS NULL OR v.expiry_date>=substr(NEW.created_at,1,10))) OR NEW.inbound_bucket='quarantined' AND NEW.quality_event_id IS NOT (SELECT id FROM purchase_receipt_current WHERE receipt_id=NEW.receipt_id AND action IN('quality_pass','quality_fail'))) THEN RAISE(ABORT,'receiving once-only explicit stock source') END;
 SELECT CASE WHEN NEW.action NOT IN('quality_pass','quality_fail') AND(NEW.checked_at IS NOT NULL OR NEW.requirement_source IS NOT NULL OR NEW.require_lot IS NOT NULL OR NEW.require_expiry IS NOT NULL OR NEW.require_location IS NOT NULL OR NEW.checks_json IS NOT NULL) OR NEW.action<>'inbound' AND(NEW.quality_event_id IS NOT NULL OR NEW.inbound_bucket IS NOT NULL OR NEW.stock_sequence IS NOT NULL OR NEW.outbound_revision IS NOT NULL) THEN RAISE(ABORT,'receiving unrelated assumed facts') END;
END;
CREATE TRIGGER purchase_inbound_ref_source BEFORE INSERT ON purchase_inbound_refs BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_receipt_events e JOIN purchase_receipts r ON r.id=e.receipt_id JOIN inventory_events s ON s.id=NEW.stock_event_id WHERE e.id=NEW.event_id AND e.action='inbound' AND s.product_id=r.product_id AND s.product_version=r.product_version AND s.store_id=r.store_id AND s.quantity=r.bound_quantity AND s.order_event_id IS NULL AND s.action=NEW.kind AND s.created_at=e.created_at AND s.created_by=e.created_by AND s.reason=e.reason AND s.sequence=e.stock_sequence+CASE WHEN NEW.kind='receive' THEN 1 ELSE 2 END AND(NEW.kind='receive' OR e.inbound_bucket='quarantined' AND EXISTS(SELECT 1 FROM purchase_inbound_refs WHERE event_id=e.id AND kind='receive'))) THEN RAISE(ABORT,'receiving original inventory reference') END;
END;
CREATE TRIGGER purchase_receipts_actor BEFORE INSERT ON purchase_receipts WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND u.role IN('manager','reception','professional') AND coalesce(q.must_change_password,0)=0) BEGIN SELECT RAISE(ABORT,'receiving actor/time'); END;
CREATE TRIGGER purchase_receipts_text BEFORE INSERT ON purchase_receipts WHEN (length(trim(NEW.receipt_number)) NOT BETWEEN 1 AND 60 OR length(NEW.receipt_number)>60) OR (length(trim(NEW.receiver_label)) NOT BETWEEN 1 AND 120 OR length(NEW.receiver_label)>120) OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000) OR (NEW.delivery_reference IS NOT NULL AND(length(trim(NEW.delivery_reference)) NOT BETWEEN 1 AND 120 OR length(NEW.delivery_reference)>120)) OR (NEW.source_line_reference IS NOT NULL AND(length(trim(NEW.source_line_reference)) NOT BETWEEN 1 AND 120 OR length(NEW.source_line_reference)>120)) BEGIN SELECT RAISE(ABORT,'receiving actual source text'); END;
CREATE TRIGGER purchase_receipt_versions_actor BEFORE INSERT ON purchase_receipt_versions WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND u.role IN('manager','reception','professional') AND coalesce(q.must_change_password,0)=0) BEGIN SELECT RAISE(ABORT,'receiving actor/time'); END;
CREATE TRIGGER purchase_receipt_versions_text BEFORE INSERT ON purchase_receipt_versions WHEN (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000) OR (length(trim(NEW.source_reference)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_reference)>1000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (NEW.lot_code IS NOT NULL AND(length(trim(NEW.lot_code)) NOT BETWEEN 1 AND 120 OR length(NEW.lot_code)>120)) OR (NEW.location_note IS NOT NULL AND(length(trim(NEW.location_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.location_note)>1000)) OR (NEW.manufacturer_note IS NOT NULL AND(length(trim(NEW.manufacturer_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.manufacturer_note)>1000)) BEGIN SELECT RAISE(ABORT,'receiving actual source text'); END;
CREATE TRIGGER purchase_receipt_events_actor BEFORE INSERT ON purchase_receipt_events WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND u.role IN('manager','reception','professional') AND coalesce(q.must_change_password,0)=0) BEGIN SELECT RAISE(ABORT,'receiving actor/time'); END;
CREATE TRIGGER purchase_receipt_events_text BEFORE INSERT ON purchase_receipt_events WHEN (length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000) BEGIN SELECT RAISE(ABORT,'receiving actual source text'); END;
CREATE TRIGGER purchase_receipts_no_update BEFORE UPDATE ON purchase_receipts BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_receipts_no_delete BEFORE DELETE ON purchase_receipts BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_receipt_versions_no_update BEFORE UPDATE ON purchase_receipt_versions BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_receipt_versions_no_delete BEFORE DELETE ON purchase_receipt_versions BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_receipt_events_no_update BEFORE UPDATE ON purchase_receipt_events BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_receipt_events_no_delete BEFORE DELETE ON purchase_receipt_events BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_inbound_refs_no_update BEFORE UPDATE ON purchase_inbound_refs BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER purchase_inbound_refs_no_delete BEFORE DELETE ON purchase_inbound_refs BEGIN SELECT RAISE(ABORT,'receiving immutable'); END;
CREATE TRIGGER receiving_write_actor BEFORE INSERT ON purchase_receipt_events WHEN NEW.action IN('create','revise') AND NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role IN('manager','reception')) BEGIN SELECT RAISE(ABORT,'receiving write actor'); END;
CREATE TRIGGER purchase_receipts_writer BEFORE INSERT ON purchase_receipts WHEN NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role IN('manager','reception')) BEGIN SELECT RAISE(ABORT,'receiving writer'); END;
CREATE TRIGGER purchase_receipt_versions_writer BEFORE INSERT ON purchase_receipt_versions WHEN NOT EXISTS(SELECT 1 FROM users WHERE id=NEW.created_by AND role IN('manager','reception')) BEGIN SELECT RAISE(ABORT,'receiving writer'); END;
