CREATE TABLE purchase_quality_cases(id TEXT PRIMARY KEY,receipt_id TEXT NOT NULL REFERENCES purchase_receipts(id),inbound_event_id TEXT NOT NULL REFERENCES purchase_receipt_events(id),store_id TEXT NOT NULL REFERENCES stores(id),quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 1000000),source_bucket TEXT NOT NULL CHECK(source_bucket IN('available','quarantined')),stock_sequence INTEGER NOT NULL CHECK(stock_sequence>=0),outbound_revision INTEGER NOT NULL CHECK(outbound_revision>=0),custody_confirmed_at TEXT NOT NULL,custody_source TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id));
CREATE TABLE purchase_quality_versions(id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES purchase_quality_cases(id),store_id TEXT NOT NULL REFERENCES stores(id),version INTEGER NOT NULL CHECK(version>0),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),receipt_version_id TEXT NOT NULL REFERENCES purchase_receipt_versions(id),receipt_sequence INTEGER NOT NULL CHECK(receipt_sequence>=0),observed_at TEXT NOT NULL,observation_note TEXT NOT NULL,source_reference TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,version));
CREATE TABLE purchase_quality_events(id TEXT PRIMARY KEY,case_id TEXT NOT NULL REFERENCES purchase_quality_cases(id),version_id TEXT NOT NULL REFERENCES purchase_quality_versions(id),store_id TEXT NOT NULL REFERENCES stores(id),revision INTEGER NOT NULL CHECK(revision>0),sequence INTEGER NOT NULL CHECK(sequence>0),receipt_sequence INTEGER NOT NULL CHECK(receipt_sequence>=0),action TEXT NOT NULL CHECK(action IN('create','revise','quality_pass','quality_fail','release')),status TEXT NOT NULL CHECK(status IN('pending','passed','failed','released')),checked_at TEXT,requirement_source TEXT,require_lot INTEGER,require_expiry INTEGER,require_location INTEGER,checks_json TEXT,quality_event_id TEXT REFERENCES purchase_quality_events(id),stock_sequence INTEGER,outbound_revision INTEGER,note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(case_id,revision),UNIQUE(store_id,sequence));
CREATE TABLE purchase_quality_stock_refs(event_id TEXT PRIMARY KEY REFERENCES purchase_quality_events(id),stock_event_id TEXT NOT NULL UNIQUE REFERENCES inventory_events(id));
CREATE VIEW purchase_quality_current AS SELECT * FROM purchase_quality_events e WHERE revision=(SELECT max(revision) FROM purchase_quality_events WHERE case_id=e.case_id);
CREATE VIEW purchase_quality_journal AS SELECT store_id,sequence,id,created_at FROM purchase_quality_events;
CREATE VIEW purchase_quality_holds AS SELECT r.product_id,c.receipt_id,c.id case_id,c.quantity FROM purchase_quality_cases c JOIN purchase_receipts r ON r.id=c.receipt_id JOIN purchase_quality_current e ON e.case_id=c.id WHERE e.status<>'released';
CREATE TRIGGER purchase_quality_root_source BEFORE INSERT ON purchase_quality_cases BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_receipts r JOIN purchase_receipt_events e ON e.receipt_id=r.id WHERE r.id=NEW.receipt_id AND e.id=NEW.inbound_event_id AND e.action='inbound' AND r.store_id=NEW.store_id AND e.created_at<=NEW.custody_confirmed_at AND NEW.quantity+coalesce((SELECT sum(quantity) FROM purchase_quality_holds WHERE receipt_id=r.id),0)<=r.bound_quantity AND NEW.stock_sequence=coalesce((SELECT max(sequence) FROM inventory_events WHERE product_id=r.product_id),0) AND NEW.outbound_revision=coalesce((SELECT max(outbound_revision) FROM inventory_outbounds WHERE product_id=r.product_id),0) AND NOT EXISTS(SELECT 1 FROM inventory_events WHERE product_id=r.product_id AND created_at>NEW.created_at) AND NOT EXISTS(SELECT 1 FROM inventory_outbounds WHERE product_id=r.product_id AND created_at>NEW.created_at) AND(NEW.source_bucket='available' AND NEW.quantity<=(SELECT effective_available FROM inventory_balances WHERE product_id=r.product_id) OR NEW.source_bucket='quarantined' AND NEW.quantity<=(SELECT quarantined FROM inventory_balances WHERE product_id=r.product_id)-coalesce((SELECT sum(quantity) FROM purchase_quality_holds WHERE product_id=r.product_id),0))) THEN RAISE(ABORT,'purchase quality actual custody/capacity') END;
 SELECT CASE WHEN length(NEW.custody_confirmed_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.custody_confirmed_at) IS NOT NEW.custody_confirmed_at OR NEW.custody_confirmed_at>NEW.created_at THEN RAISE(ABORT,'purchase quality custody time') END;
END;
CREATE TRIGGER purchase_quality_version_source BEFORE INSERT ON purchase_quality_versions BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_quality_cases c JOIN purchase_receipts r ON r.id=c.receipt_id JOIN purchase_receipt_versions v ON v.receipt_id=r.id WHERE c.id=NEW.case_id AND c.store_id=NEW.store_id AND v.id=NEW.receipt_version_id AND v.version=(SELECT max(version) FROM purchase_receipt_versions WHERE receipt_id=r.id) AND v.created_at<=NEW.created_at AND NEW.observed_at>=c.custody_confirmed_at) OR NEW.version<>coalesce((SELECT max(version)+1 FROM purchase_quality_versions WHERE case_id=NEW.case_id),1) OR NEW.receipt_sequence<>coalesce((SELECT max(sequence) FROM purchase_receiving_journal WHERE store_id=NEW.store_id),0) OR NEW.base_sequence<>coalesce((SELECT max(sequence) FROM purchase_quality_journal WHERE store_id=NEW.store_id),0) OR EXISTS(SELECT 1 FROM purchase_quality_current WHERE case_id=NEW.case_id AND status='released') OR length(NEW.observed_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.observed_at) IS NOT NEW.observed_at OR NEW.observed_at>NEW.created_at THEN RAISE(ABORT,'purchase quality actual observation version') END;
END;
CREATE TRIGGER purchase_quality_event_source BEFORE INSERT ON purchase_quality_events BEGIN
 SELECT CASE WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM purchase_quality_journal WHERE store_id=NEW.store_id),1) OR NEW.receipt_sequence<>coalesce((SELECT max(sequence) FROM purchase_receiving_journal WHERE store_id=NEW.store_id),0) OR NEW.revision<>coalesce((SELECT max(revision)+1 FROM purchase_quality_events WHERE case_id=NEW.case_id),1) OR EXISTS(SELECT 1 FROM purchase_quality_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) OR NOT EXISTS(SELECT 1 FROM purchase_quality_versions v WHERE v.id=NEW.version_id AND v.case_id=NEW.case_id AND v.store_id=NEW.store_id AND v.version=(SELECT max(version) FROM purchase_quality_versions WHERE case_id=NEW.case_id) AND v.created_at<=NEW.created_at) THEN RAISE(ABORT,'purchase quality journal/version') END;
 SELECT CASE WHEN NOT(NEW.action='create' AND NEW.revision=1 AND NEW.status='pending' AND EXISTS(SELECT 1 FROM purchase_quality_cases c JOIN purchase_quality_versions v ON v.case_id=c.id WHERE c.id=NEW.case_id AND v.id=NEW.version_id AND v.version=1 AND c.created_at=NEW.created_at AND c.created_by=NEW.created_by AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by AND v.base_sequence+1=NEW.sequence) OR NEW.action='revise' AND NEW.status='pending' AND EXISTS(SELECT 1 FROM purchase_quality_current e JOIN purchase_quality_versions old ON old.id=e.version_id JOIN purchase_quality_versions v ON v.id=NEW.version_id WHERE e.case_id=NEW.case_id AND e.status<>'released' AND v.version=old.version+1 AND v.base_sequence+1=NEW.sequence AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by) OR EXISTS(SELECT 1 FROM purchase_quality_current e WHERE e.case_id=NEW.case_id AND e.version_id=NEW.version_id AND(NEW.action='quality_pass' AND e.status='pending' AND NEW.status='passed' OR NEW.action='quality_fail' AND e.status='pending' AND NEW.status='failed' OR NEW.action='release' AND e.status='passed' AND NEW.status='released'))) THEN RAISE(ABORT,'purchase quality explicit transition') END;
 SELECT CASE WHEN NEW.action IN('quality_pass','release') AND NOT EXISTS(SELECT 1 FROM purchase_quality_versions v JOIN purchase_quality_cases c ON c.id=v.case_id JOIN purchase_receipt_versions r ON r.id=v.receipt_version_id WHERE v.id=NEW.version_id AND r.version=(SELECT max(version) FROM purchase_receipt_versions WHERE receipt_id=c.receipt_id) AND(r.expiry_date IS NULL OR r.expiry_date>=substr(CASE WHEN NEW.action='quality_pass' THEN NEW.checked_at ELSE NEW.created_at END,1,10))) THEN RAISE(ABORT,'purchase quality current receipt source/expiry') END;
 SELECT CASE WHEN NEW.action='quality_pass' AND NOT EXISTS(SELECT 1 FROM purchase_quality_versions v JOIN purchase_receipt_versions r ON r.id=v.receipt_version_id WHERE v.id=NEW.version_id AND(NEW.require_lot=0 OR r.lot_status='recorded') AND(NEW.require_expiry=0 OR r.expiry_status='provided') AND(NEW.require_location=0 OR r.location_status='recorded')) THEN RAISE(ABORT,'purchase quality required actual provenance') END;
 SELECT CASE WHEN NEW.action IN('quality_pass','quality_fail') AND(NEW.checked_at IS NULL OR length(NEW.checked_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.checked_at) IS NOT NEW.checked_at OR NEW.checked_at>NEW.created_at OR NEW.checked_at<(SELECT observed_at FROM purchase_quality_versions WHERE id=NEW.version_id) OR NEW.requirement_source IS NULL OR length(trim(NEW.requirement_source)) NOT BETWEEN 1 AND 2000 OR length(NEW.requirement_source)>2000 OR NEW.require_lot IS NULL OR NEW.require_lot NOT IN(0,1) OR NEW.require_expiry IS NULL OR NEW.require_expiry NOT IN(0,1) OR NEW.require_location IS NULL OR NEW.require_location NOT IN(0,1) OR NEW.checks_json IS NULL OR json_valid(NEW.checks_json)=0 OR json_type(NEW.checks_json)<>'array' OR json_array_length(NEW.checks_json) NOT BETWEEN 1 AND 30 OR EXISTS(SELECT 1 FROM json_each(NEW.checks_json) j WHERE json_type(j.value)<>'object' OR(SELECT count(*) FROM json_each(j.value))<>2 OR json_type(j.value,'$.label') IS NOT 'text' OR length(trim(json_extract(j.value,'$.label'))) NOT BETWEEN 1 AND 300 OR length(json_extract(j.value,'$.label'))>300 OR json_type(j.value,'$.result') IS NOT 'text' OR json_extract(j.value,'$.result') NOT IN('pass','fail')) OR NEW.action='quality_pass' AND EXISTS(SELECT 1 FROM json_each(NEW.checks_json) j WHERE json_extract(j.value,'$.result')<>'pass') OR NEW.action='quality_fail' AND NOT EXISTS(SELECT 1 FROM json_each(NEW.checks_json) j WHERE json_extract(j.value,'$.result')='fail')) THEN RAISE(ABORT,'purchase quality actual checks') END;
 SELECT CASE WHEN NEW.action='release' AND(NEW.quality_event_id IS NOT(SELECT id FROM purchase_quality_current WHERE case_id=NEW.case_id AND action='quality_pass') OR NEW.stock_sequence IS NULL OR NEW.outbound_revision IS NULL OR NOT EXISTS(SELECT 1 FROM purchase_quality_cases c JOIN purchase_receipts r ON r.id=c.receipt_id WHERE c.id=NEW.case_id AND NEW.stock_sequence=(SELECT max(sequence) FROM inventory_events WHERE product_id=r.product_id) AND NEW.outbound_revision=coalesce((SELECT max(outbound_revision) FROM inventory_outbounds WHERE product_id=r.product_id),0) AND c.quantity<=(SELECT quarantined FROM inventory_balances WHERE product_id=r.product_id))) THEN RAISE(ABORT,'purchase quality release stock source') END;
 SELECT CASE WHEN NEW.action NOT IN('quality_pass','quality_fail') AND(NEW.checked_at IS NOT NULL OR NEW.requirement_source IS NOT NULL OR NEW.require_lot IS NOT NULL OR NEW.require_expiry IS NOT NULL OR NEW.require_location IS NOT NULL OR NEW.checks_json IS NOT NULL) OR NEW.action<>'release' AND(NEW.quality_event_id IS NOT NULL OR NEW.stock_sequence IS NOT NULL OR NEW.outbound_revision IS NOT NULL) THEN RAISE(ABORT,'purchase quality unrelated facts') END;
END;
CREATE TRIGGER purchase_quality_stock_ref_source BEFORE INSERT ON purchase_quality_stock_refs BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_quality_events e JOIN purchase_quality_cases c ON c.id=e.case_id JOIN purchase_receipts r ON r.id=c.receipt_id JOIN inventory_events s ON s.id=NEW.stock_event_id WHERE e.id=NEW.event_id AND(e.action='release' AND s.action='unquarantine' AND s.sequence=e.stock_sequence+1 OR e.action='create' AND c.source_bucket='available' AND s.action='isolate' AND s.sequence=c.stock_sequence+1) AND s.product_id=r.product_id AND s.product_version=r.product_version AND s.store_id=c.store_id AND s.quantity=c.quantity AND s.order_event_id IS NULL AND s.created_at=e.created_at AND s.created_by=e.created_by AND s.reason=e.reason) THEN RAISE(ABORT,'purchase quality original stock reference') END;
END;
CREATE TRIGGER purchase_quality_held_stock BEFORE INSERT ON inventory_events WHEN NEW.action='unquarantine' AND NEW.quantity>(SELECT quarantined FROM inventory_balances WHERE product_id=NEW.product_id)-coalesce((SELECT sum(quantity) FROM purchase_quality_holds WHERE product_id=NEW.product_id),0) BEGIN SELECT RAISE(ABORT,'purchase quality protected quarantine'); END;
CREATE TABLE purchase_quality_stock_context(stock_event_id TEXT PRIMARY KEY REFERENCES inventory_events(id),store_id TEXT NOT NULL REFERENCES stores(id),quality_sequence INTEGER NOT NULL CHECK(quality_sequence>=0));
INSERT INTO purchase_quality_stock_context SELECT id,store_id,0 FROM inventory_events;
CREATE TRIGGER purchase_quality_stock_context_source BEFORE INSERT ON purchase_quality_stock_context WHEN NOT EXISTS(SELECT 1 FROM inventory_events e WHERE e.id=NEW.stock_event_id AND e.store_id=NEW.store_id) OR NEW.quality_sequence<>coalesce((SELECT max(sequence) FROM purchase_quality_journal WHERE store_id=NEW.store_id),0) BEGIN SELECT RAISE(ABORT,'purchase quality original stock context'); END;
CREATE TRIGGER purchase_quality_stock_capture AFTER INSERT ON inventory_events BEGIN INSERT INTO purchase_quality_stock_context VALUES(NEW.id,NEW.store_id,coalesce((SELECT max(sequence) FROM purchase_quality_journal WHERE store_id=NEW.store_id),0)); END;
CREATE TRIGGER purchase_quality_stock_context_no_update BEFORE UPDATE ON purchase_quality_stock_context BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_stock_context_no_delete BEFORE DELETE ON purchase_quality_stock_context BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_cases_actor BEFORE INSERT ON purchase_quality_cases WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND (u.role='manager')) BEGIN SELECT RAISE(ABORT,'purchase quality actor/time'); END;
CREATE TRIGGER purchase_quality_cases_text BEFORE INSERT ON purchase_quality_cases WHEN (length(trim(NEW.custody_source)) NOT BETWEEN 1 AND 2000 OR length(NEW.custody_source)>2000) BEGIN SELECT RAISE(ABORT,'purchase quality actual source text'); END;
CREATE TRIGGER purchase_quality_versions_actor BEFORE INSERT ON purchase_quality_versions WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND (u.role IN('manager','professional'))) BEGIN SELECT RAISE(ABORT,'purchase quality actor/time'); END;
CREATE TRIGGER purchase_quality_versions_text BEFORE INSERT ON purchase_quality_versions WHEN (length(trim(NEW.observation_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.observation_note)>2000) OR (length(trim(NEW.source_reference)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_reference)>1000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) BEGIN SELECT RAISE(ABORT,'purchase quality actual source text'); END;
CREATE TRIGGER purchase_quality_events_actor BEFORE INSERT ON purchase_quality_events WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND (u.role IN('manager','professional') AND (u.role='manager' OR NEW.action IN('quality_pass','quality_fail','revise')))) BEGIN SELECT RAISE(ABORT,'purchase quality actor/time'); END;
CREATE TRIGGER purchase_quality_events_text BEFORE INSERT ON purchase_quality_events WHEN (length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000) BEGIN SELECT RAISE(ABORT,'purchase quality actual source text'); END;
CREATE TRIGGER purchase_quality_cases_no_update BEFORE UPDATE ON purchase_quality_cases BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_cases_no_delete BEFORE DELETE ON purchase_quality_cases BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_versions_no_update BEFORE UPDATE ON purchase_quality_versions BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_versions_no_delete BEFORE DELETE ON purchase_quality_versions BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_events_no_update BEFORE UPDATE ON purchase_quality_events BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_events_no_delete BEFORE DELETE ON purchase_quality_events BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_stock_refs_no_update BEFORE UPDATE ON purchase_quality_stock_refs BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
CREATE TRIGGER purchase_quality_stock_refs_no_delete BEFORE DELETE ON purchase_quality_stock_refs BEGIN SELECT RAISE(ABORT,'purchase quality immutable'); END;
