-- Unmatched excess-goods arrangements and actual handover; never SKU inventory movements.
CREATE TABLE purchase_extra_return_plans(id TEXT PRIMARY KEY,receipt_id TEXT NOT NULL REFERENCES purchase_receipts(id),supplier_id TEXT NOT NULL REFERENCES suppliers(id),store_id TEXT NOT NULL REFERENCES stores(id),serial INTEGER NOT NULL CHECK(serial>0),return_number TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 1000000),custody_confirmed_at TEXT NOT NULL,custody_source TEXT NOT NULL,source_note TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(store_id,serial),UNIQUE(store_id,return_number));
CREATE TABLE purchase_extra_return_versions(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES purchase_extra_return_plans(id),store_id TEXT NOT NULL REFERENCES stores(id),version INTEGER NOT NULL CHECK(version>0),base_sequence INTEGER NOT NULL CHECK(base_sequence>=0),receipt_sequence INTEGER NOT NULL CHECK(receipt_sequence>=0),receipt_version_id TEXT NOT NULL REFERENCES purchase_receipt_versions(id),return_basis TEXT NOT NULL,destination_note TEXT NOT NULL,contact_note TEXT,source_reference TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(plan_id,version));
CREATE TABLE purchase_extra_return_events(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES purchase_extra_return_plans(id),version_id TEXT NOT NULL REFERENCES purchase_extra_return_versions(id),store_id TEXT NOT NULL REFERENCES stores(id),revision INTEGER NOT NULL CHECK(revision>0),sequence INTEGER NOT NULL CHECK(sequence>0),receipt_sequence INTEGER NOT NULL CHECK(receipt_sequence>=0),action TEXT NOT NULL CHECK(action IN('create','revise','submit','approve','reject','reopen','cancel','stop_remaining')),status TEXT NOT NULL CHECK(status IN('draft','submitted','approved','rejected','cancelled','closed_partial')),decision_basis TEXT NOT NULL,note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(plan_id,revision),UNIQUE(store_id,sequence));
CREATE TABLE purchase_extra_return_handoffs(id TEXT PRIMARY KEY,plan_id TEXT NOT NULL REFERENCES purchase_extra_return_plans(id),version_id TEXT NOT NULL REFERENCES purchase_extra_return_versions(id),approval_event_id TEXT NOT NULL REFERENCES purchase_extra_return_events(id),receipt_id TEXT NOT NULL REFERENCES purchase_receipts(id),supplier_id TEXT NOT NULL REFERENCES suppliers(id),store_id TEXT NOT NULL REFERENCES stores(id),product_id TEXT NOT NULL REFERENCES retail_products(id),product_version INTEGER NOT NULL,quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 1000000),receipt_revision INTEGER NOT NULL CHECK(receipt_revision>0),sequence INTEGER NOT NULL CHECK(sequence>0),handed_at TEXT NOT NULL,collector_label TEXT NOT NULL,destination_note TEXT NOT NULL,external_reference TEXT,source_identity TEXT,source_note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(receipt_id,receipt_revision),UNIQUE(store_id,sequence),FOREIGN KEY(product_id,product_version) REFERENCES retail_product_versions(product_id,version));
CREATE UNIQUE INDEX purchase_extra_handoff_identity ON purchase_extra_return_handoffs(plan_id,source_identity) WHERE source_identity IS NOT NULL;
CREATE TABLE purchase_extra_return_receipts(id TEXT PRIMARY KEY,handoff_id TEXT NOT NULL REFERENCES purchase_extra_return_handoffs(id),store_id TEXT NOT NULL REFERENCES stores(id),quantity INTEGER NOT NULL CHECK(typeof(quantity)='integer' AND quantity BETWEEN 1 AND 1000000),sequence INTEGER NOT NULL CHECK(sequence>0),received_at TEXT NOT NULL,receiver_label TEXT NOT NULL,external_reference TEXT,source_identity TEXT,source_note TEXT NOT NULL,reason TEXT NOT NULL,next_step TEXT NOT NULL,created_at TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),UNIQUE(store_id,sequence));
CREATE UNIQUE INDEX purchase_extra_receipt_identity ON purchase_extra_return_receipts(handoff_id,source_identity) WHERE source_identity IS NOT NULL;
CREATE TABLE purchase_receipt_extra_return_context(receipt_event_id TEXT PRIMARY KEY REFERENCES purchase_receipt_events(id),extra_sequence INTEGER NOT NULL CHECK(extra_sequence>=0));
INSERT INTO purchase_receipt_extra_return_context SELECT id,0 FROM purchase_receipt_events;
CREATE VIEW purchase_extra_return_current AS SELECT * FROM purchase_extra_return_events e WHERE revision=(SELECT max(revision) FROM purchase_extra_return_events WHERE plan_id=e.plan_id);
CREATE VIEW purchase_extra_return_journal AS SELECT store_id,sequence,id,created_at FROM purchase_extra_return_events UNION ALL SELECT store_id,sequence,id,created_at FROM purchase_extra_return_handoffs UNION ALL SELECT store_id,sequence,id,created_at FROM purchase_extra_return_receipts;
CREATE VIEW purchase_extra_return_plan_balance AS SELECT p.id,p.receipt_id,p.store_id,p.quantity,coalesce((SELECT sum(quantity) FROM purchase_extra_return_handoffs WHERE plan_id=p.id),0) handed_quantity,coalesce((SELECT sum(r.quantity) FROM purchase_extra_return_receipts r JOIN purchase_extra_return_handoffs h ON h.id=r.handoff_id WHERE h.plan_id=p.id),0) received_quantity,coalesce(c.status,'draft') status,CASE WHEN coalesce(c.status,'draft') IN('draft','submitted','approved') THEN p.quantity-coalesce((SELECT sum(quantity) FROM purchase_extra_return_handoffs WHERE plan_id=p.id),0) ELSE 0 END pending_quantity FROM purchase_extra_return_plans p LEFT JOIN purchase_extra_return_current c ON c.plan_id=p.id;
CREATE VIEW purchase_extra_return_receipt_balance AS SELECT r.id receipt_id,r.received_quantity-r.bound_quantity original_extra_quantity,coalesce((SELECT sum(quantity) FROM purchase_extra_return_handoffs WHERE receipt_id=r.id),0) handed_quantity,r.received_quantity-r.bound_quantity-coalesce((SELECT sum(quantity) FROM purchase_extra_return_handoffs WHERE receipt_id=r.id),0) unmatched_not_returned_quantity,coalesce((SELECT max(receipt_revision) FROM purchase_extra_return_handoffs WHERE receipt_id=r.id),0) receipt_return_revision,coalesce((SELECT sum(pending_quantity) FROM purchase_extra_return_plan_balance WHERE receipt_id=r.id),0) pending_quantity,coalesce((SELECT sum(s.quantity) FROM purchase_extra_return_receipts s JOIN purchase_extra_return_handoffs h ON h.id=s.handoff_id WHERE h.receipt_id=r.id),0) received_quantity FROM purchase_receipts r;

CREATE TRIGGER purchase_extra_return_plan_source BEFORE INSERT ON purchase_extra_return_plans BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_receipts r JOIN purchase_receipt_current e ON e.receipt_id=r.id JOIN purchase_extra_return_receipt_balance b ON b.receipt_id=r.id WHERE r.id=NEW.receipt_id AND r.supplier_id=NEW.supplier_id AND r.store_id=NEW.store_id AND e.status<>'cancelled' AND NEW.quantity<=b.unmatched_not_returned_quantity-b.pending_quantity AND r.created_at<=NEW.created_at AND NEW.custody_confirmed_at>=r.received_at AND NEW.custody_confirmed_at<=NEW.created_at) OR NEW.serial<>coalesce((SELECT max(serial)+1 FROM purchase_extra_return_plans WHERE store_id=NEW.store_id),1) OR NEW.return_number IS NOT 'EXR-'||replace(substr(NEW.created_at,1,10),'-','')||'-'||printf('%05d',NEW.serial) OR length(NEW.custody_confirmed_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.custody_confirmed_at) IS NOT NEW.custody_confirmed_at THEN RAISE(ABORT,'extra return original arrival/custody/capacity') END;
END;
CREATE TRIGGER purchase_extra_return_version_source BEFORE INSERT ON purchase_extra_return_versions BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_extra_return_plans p JOIN purchase_receipt_current e ON e.receipt_id=p.receipt_id JOIN purchase_receipt_versions r ON r.id=NEW.receipt_version_id WHERE p.id=NEW.plan_id AND p.store_id=NEW.store_id AND e.status<>'cancelled' AND e.version_id=r.id AND r.receipt_id=p.receipt_id AND r.created_at<=NEW.created_at) OR NEW.version<>coalesce((SELECT max(version)+1 FROM purchase_extra_return_versions WHERE plan_id=NEW.plan_id),1) OR NEW.base_sequence<>coalesce((SELECT max(sequence) FROM purchase_extra_return_journal WHERE store_id=NEW.store_id),0) OR NEW.receipt_sequence<>coalesce((SELECT max(sequence) FROM purchase_receiving_journal WHERE store_id=NEW.store_id),0) OR EXISTS(SELECT 1 FROM purchase_extra_return_current WHERE plan_id=NEW.plan_id AND status<>'draft') OR EXISTS(SELECT 1 FROM purchase_extra_return_handoffs WHERE plan_id=NEW.plan_id) THEN RAISE(ABORT,'extra return current arrangement version') END;
END;
CREATE TRIGGER purchase_extra_return_event_source BEFORE INSERT ON purchase_extra_return_events BEGIN
 SELECT CASE WHEN NEW.revision<>coalesce((SELECT max(revision)+1 FROM purchase_extra_return_events WHERE plan_id=NEW.plan_id),1) OR NEW.receipt_sequence<>coalesce((SELECT max(sequence) FROM purchase_receiving_journal WHERE store_id=NEW.store_id),0) OR NOT EXISTS(SELECT 1 FROM purchase_extra_return_versions v WHERE v.id=NEW.version_id AND v.plan_id=NEW.plan_id AND v.store_id=NEW.store_id AND v.version=(SELECT max(version) FROM purchase_extra_return_versions WHERE plan_id=NEW.plan_id) AND v.created_at<=NEW.created_at) THEN RAISE(ABORT,'extra return original version/revision') END;
 SELECT CASE WHEN NOT(NEW.action='create' AND NEW.revision=1 AND NEW.status='draft' AND EXISTS(SELECT 1 FROM purchase_extra_return_plans p JOIN purchase_extra_return_versions v ON v.plan_id=p.id WHERE p.id=NEW.plan_id AND v.id=NEW.version_id AND v.version=1 AND v.base_sequence+1=NEW.sequence AND v.receipt_sequence=NEW.receipt_sequence AND p.created_at=NEW.created_at AND p.created_by=NEW.created_by AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by) OR NEW.action='revise' AND NEW.status='draft' AND EXISTS(SELECT 1 FROM purchase_extra_return_current c JOIN purchase_extra_return_versions old ON old.id=c.version_id JOIN purchase_extra_return_versions v ON v.id=NEW.version_id WHERE c.plan_id=NEW.plan_id AND c.status='draft' AND v.version=old.version+1 AND v.base_sequence+1=NEW.sequence AND v.receipt_sequence=NEW.receipt_sequence AND v.created_at=NEW.created_at AND v.created_by=NEW.created_by) OR EXISTS(SELECT 1 FROM purchase_extra_return_current c JOIN purchase_extra_return_plan_balance b ON b.id=c.plan_id WHERE c.plan_id=NEW.plan_id AND c.version_id=NEW.version_id AND(NEW.action='submit' AND c.status='draft' AND NEW.status='submitted' OR NEW.action='approve' AND c.status='submitted' AND NEW.status='approved' OR NEW.action='reject' AND c.status='submitted' AND NEW.status='rejected' OR NEW.action='reopen' AND c.status IN('approved','rejected') AND b.handed_quantity=0 AND NEW.status='draft' OR NEW.action='cancel' AND c.status IN('draft','submitted','approved','rejected') AND b.handed_quantity=0 AND NEW.status='cancelled' OR NEW.action='stop_remaining' AND c.status='approved' AND b.handed_quantity>0 AND b.handed_quantity<b.quantity AND NEW.status='closed_partial'))) THEN RAISE(ABORT,'extra return explicit commercial transition') END;
 SELECT CASE WHEN NEW.action IN('submit','approve','reopen') AND NOT EXISTS(SELECT 1 FROM purchase_extra_return_plans p JOIN purchase_extra_return_versions v ON v.id=NEW.version_id JOIN purchase_receipt_current e ON e.receipt_id=p.receipt_id JOIN purchase_extra_return_receipt_balance b ON b.receipt_id=p.receipt_id WHERE p.id=NEW.plan_id AND e.status<>'cancelled' AND(NEW.action='reopen' OR e.version_id=v.receipt_version_id) AND p.quantity<=b.unmatched_not_returned_quantity-coalesce((SELECT sum(pending_quantity) FROM purchase_extra_return_plan_balance WHERE receipt_id=p.receipt_id AND id<>p.id),0)) THEN RAISE(ABORT,'extra return current source/remaining arrangement') END;
END;
CREATE TRIGGER purchase_extra_return_handoff_source BEFORE INSERT ON purchase_extra_return_handoffs BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_extra_return_plans p JOIN purchase_extra_return_current e ON e.plan_id=p.id JOIN purchase_extra_return_plan_balance b ON b.id=p.id JOIN purchase_receipts r ON r.id=p.receipt_id JOIN purchase_receipt_current c ON c.receipt_id=r.id JOIN purchase_extra_return_receipt_balance rb ON rb.receipt_id=r.id WHERE p.id=NEW.plan_id AND e.id=NEW.approval_event_id AND e.action='approve' AND e.status='approved' AND e.version_id=NEW.version_id AND p.receipt_id=NEW.receipt_id AND p.supplier_id=NEW.supplier_id AND p.store_id=NEW.store_id AND r.product_id=NEW.product_id AND r.product_version=NEW.product_version AND c.status<>'cancelled' AND NEW.quantity<=p.quantity-b.handed_quantity AND NEW.quantity<=rb.unmatched_not_returned_quantity AND NEW.handed_at>=e.created_at) OR NEW.receipt_revision<>coalesce((SELECT max(receipt_revision)+1 FROM purchase_extra_return_handoffs WHERE receipt_id=NEW.receipt_id),1) OR length(NEW.handed_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.handed_at) IS NOT NEW.handed_at OR NEW.handed_at>NEW.created_at THEN RAISE(ABORT,'extra return actual handover approved source/time/capacity') END;
END;
CREATE TRIGGER purchase_extra_return_receipt_source BEFORE INSERT ON purchase_extra_return_receipts BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_extra_return_handoffs h WHERE h.id=NEW.handoff_id AND h.store_id=NEW.store_id AND NEW.quantity+coalesce((SELECT sum(quantity) FROM purchase_extra_return_receipts WHERE handoff_id=h.id),0)<=h.quantity AND NEW.received_at>=h.handed_at) OR length(NEW.received_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.received_at) IS NOT NEW.received_at OR NEW.received_at>NEW.created_at THEN RAISE(ABORT,'extra return supplier receipt actual source/time/capacity') END;
END;
CREATE TRIGGER purchase_extra_return_original_cancel BEFORE INSERT ON purchase_receipt_events WHEN NEW.action='cancel' AND(EXISTS(SELECT 1 FROM purchase_extra_return_handoffs WHERE receipt_id=NEW.receipt_id) OR EXISTS(SELECT 1 FROM purchase_extra_return_plan_balance WHERE receipt_id=NEW.receipt_id AND pending_quantity>0)) BEGIN SELECT RAISE(ABORT,'extra return protects actual original receipt'); END;
CREATE TRIGGER purchase_receipt_extra_return_capture AFTER INSERT ON purchase_receipt_events BEGIN INSERT INTO purchase_receipt_extra_return_context VALUES(NEW.id,coalesce((SELECT max(sequence) FROM purchase_extra_return_journal WHERE store_id=NEW.store_id),0)); END;
CREATE TRIGGER purchase_receipt_extra_return_source BEFORE INSERT ON purchase_receipt_extra_return_context WHEN NOT EXISTS(SELECT 1 FROM purchase_receipt_events e WHERE e.id=NEW.receipt_event_id AND NEW.extra_sequence=coalesce((SELECT max(sequence) FROM purchase_extra_return_journal WHERE store_id=e.store_id),0)) BEGIN SELECT RAISE(ABORT,'extra return original receipt context'); END;

CREATE TRIGGER purchase_extra_return_plans_actor BEFORE INSERT ON purchase_extra_return_plans WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND(u.role='manager')) BEGIN SELECT RAISE(ABORT,'extra return actor/time'); END;
CREATE TRIGGER purchase_extra_return_plans_text BEFORE INSERT ON purchase_extra_return_plans WHEN (length(trim(NEW.custody_source)) NOT BETWEEN 1 AND 2000 OR length(NEW.custody_source)>2000) OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000) BEGIN SELECT RAISE(ABORT,'extra return actual source text'); END;
CREATE TRIGGER purchase_extra_return_versions_actor BEFORE INSERT ON purchase_extra_return_versions WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND(u.role='manager')) BEGIN SELECT RAISE(ABORT,'extra return actor/time'); END;
CREATE TRIGGER purchase_extra_return_versions_text BEFORE INSERT ON purchase_extra_return_versions WHEN (length(trim(NEW.return_basis)) NOT BETWEEN 1 AND 2000 OR length(NEW.return_basis)>2000) OR (length(trim(NEW.destination_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.destination_note)>2000) OR (length(trim(NEW.source_reference)) NOT BETWEEN 1 AND 1000 OR length(NEW.source_reference)>1000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (NEW.contact_note IS NOT NULL AND(length(trim(NEW.contact_note)) NOT BETWEEN 1 AND 1000 OR length(NEW.contact_note)>1000)) BEGIN SELECT RAISE(ABORT,'extra return actual source text'); END;
CREATE TRIGGER purchase_extra_return_events_actor BEFORE INSERT ON purchase_extra_return_events WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND(u.role='manager')) BEGIN SELECT RAISE(ABORT,'extra return actor/time'); END;
CREATE TRIGGER purchase_extra_return_events_text BEFORE INSERT ON purchase_extra_return_events WHEN (length(trim(NEW.decision_basis)) NOT BETWEEN 1 AND 2000 OR length(NEW.decision_basis)>2000) OR (length(trim(NEW.note)) NOT BETWEEN 1 AND 2000 OR length(NEW.note)>2000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000) BEGIN SELECT RAISE(ABORT,'extra return actual source text'); END;
CREATE TRIGGER purchase_extra_return_events_journal BEFORE INSERT ON purchase_extra_return_events WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id),1) OR EXISTS(SELECT 1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'extra return journal'); END;
CREATE TRIGGER purchase_extra_return_handoffs_actor BEFORE INSERT ON purchase_extra_return_handoffs WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND(u.role='manager')) BEGIN SELECT RAISE(ABORT,'extra return actor/time'); END;
CREATE TRIGGER purchase_extra_return_handoffs_text BEFORE INSERT ON purchase_extra_return_handoffs WHEN (length(trim(NEW.collector_label)) NOT BETWEEN 1 AND 120 OR length(NEW.collector_label)>120) OR (length(trim(NEW.destination_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.destination_note)>2000) OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000) OR (NEW.external_reference IS NOT NULL AND(length(trim(NEW.external_reference)) NOT BETWEEN 1 AND 120 OR length(NEW.external_reference)>120)) OR (NEW.source_identity IS NOT NULL AND(length(trim(NEW.source_identity)) NOT BETWEEN 1 AND 120 OR length(NEW.source_identity)>120)) BEGIN SELECT RAISE(ABORT,'extra return actual source text'); END;
CREATE TRIGGER purchase_extra_return_handoffs_journal BEFORE INSERT ON purchase_extra_return_handoffs WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id),1) OR EXISTS(SELECT 1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'extra return journal'); END;
CREATE TRIGGER purchase_extra_return_receipts_actor BEFORE INSERT ON purchase_extra_return_receipts WHEN length(NEW.created_at)<>24 OR strftime('%Y-%m-%dT%H:%M:%fZ',NEW.created_at) IS NOT NEW.created_at OR NEW.created_at>strftime('%Y-%m-%dT%H:%M:%fZ','now') OR NOT EXISTS(SELECT 1 FROM users u LEFT JOIN user_security q ON q.user_id=u.id WHERE u.id=NEW.created_by AND u.store_id=NEW.store_id AND u.active=1 AND coalesce(q.must_change_password,0)=0 AND(u.role IN('manager','reception'))) BEGIN SELECT RAISE(ABORT,'extra return actor/time'); END;
CREATE TRIGGER purchase_extra_return_receipts_text BEFORE INSERT ON purchase_extra_return_receipts WHEN (length(trim(NEW.receiver_label)) NOT BETWEEN 1 AND 120 OR length(NEW.receiver_label)>120) OR (length(trim(NEW.source_note)) NOT BETWEEN 1 AND 2000 OR length(NEW.source_note)>2000) OR (length(trim(NEW.reason)) NOT BETWEEN 1 AND 300 OR length(NEW.reason)>300) OR (length(trim(NEW.next_step)) NOT BETWEEN 1 AND 2000 OR length(NEW.next_step)>2000) OR (NEW.external_reference IS NOT NULL AND(length(trim(NEW.external_reference)) NOT BETWEEN 1 AND 120 OR length(NEW.external_reference)>120)) OR (NEW.source_identity IS NOT NULL AND(length(trim(NEW.source_identity)) NOT BETWEEN 1 AND 120 OR length(NEW.source_identity)>120)) BEGIN SELECT RAISE(ABORT,'extra return actual source text'); END;
CREATE TRIGGER purchase_extra_return_receipts_journal BEFORE INSERT ON purchase_extra_return_receipts WHEN NEW.sequence<>coalesce((SELECT max(sequence)+1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id),1) OR EXISTS(SELECT 1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'extra return journal'); END;
CREATE TRIGGER purchase_extra_return_plans_no_update BEFORE UPDATE ON purchase_extra_return_plans BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_plans_no_delete BEFORE DELETE ON purchase_extra_return_plans BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_versions_no_update BEFORE UPDATE ON purchase_extra_return_versions BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_versions_no_delete BEFORE DELETE ON purchase_extra_return_versions BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_events_no_update BEFORE UPDATE ON purchase_extra_return_events BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_events_no_delete BEFORE DELETE ON purchase_extra_return_events BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_handoffs_no_update BEFORE UPDATE ON purchase_extra_return_handoffs BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_handoffs_no_delete BEFORE DELETE ON purchase_extra_return_handoffs BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_receipts_no_update BEFORE UPDATE ON purchase_extra_return_receipts BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_receipts_no_delete BEFORE DELETE ON purchase_extra_return_receipts BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_receipt_extra_return_context_no_update BEFORE UPDATE ON purchase_receipt_extra_return_context BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_receipt_extra_return_context_no_delete BEFORE DELETE ON purchase_receipt_extra_return_context BEGIN SELECT RAISE(ABORT,'extra return immutable'); END;
CREATE TRIGGER purchase_extra_return_receipt_time BEFORE INSERT ON purchase_receipt_events WHEN EXISTS(SELECT 1 FROM purchase_extra_return_journal WHERE store_id=NEW.store_id AND created_at>NEW.created_at) BEGIN SELECT RAISE(ABORT,'extra return original receipt chronology'); END;
