import { pathToFileURL } from 'node:url';
import { mkdirSync } from 'node:fs';
if(!process.env.PLAYWRIGHT_MODULE_PATH)throw Error('Set PLAYWRIGHT_MODULE_PATH to an installed Playwright index.mjs');
const { chromium }=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href);
mkdirSync('data/browser-check',{recursive:true});
import { createApp } from '../src/server.mjs';
import { hashPassword } from '../src/db.mjs';
import { seedDemoScenarios, seedDemoPeople } from '../src/demo-data.mjs';
import assert from 'node:assert/strict';
import { once } from 'node:events';
const {server,db}=createApp({databasePath:':memory:',mode:'test',logger:()=>{}});
db.prepare('INSERT INTO stores VALUES (?,?)').run('store-a','示例视光门店 · A');
db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('demo-manager','demo-manager','负责人样例',hashPassword('local-browser-test-only'),'manager','store-a');
for(const [id,name,birth] of [['one','小林（虚构）','2017-06-12'],['two','小林弟弟（虚构）','2020-03-08']])db.prepare('INSERT INTO customers VALUES (?,?,?,?,?,?,?,?)').run(id,'store-a',name,birth,'林家长（虚构）',null,new Date().toISOString(),'demo-manager');
db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?,1)').run('demo-parent','demo-parent','家长样例',hashPassword('local-browser-test-only'),'guardian','store-a');
seedDemoScenarios(db);seedDemoPeople(db);
server.listen(0,'127.0.0.1');await once(server,'listening');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.locator('#login-view').waitFor({state:'visible'});
 await page.locator('#login-form input[name=username]').fill('demo-manager');
 await page.locator('#login-form input[name=password]').fill('local-browser-test-only');
 await page.locator('#login-form button[type=submit]').click();
 await page.locator('#customers-view').waitFor({state:'visible'});
 await page.locator('.customer-row').first().click();
 await page.locator('.detail-top').waitFor();
 await page.locator('#new-customer').click();
 await page.locator('#customer-form input[name=name]').fill('小叶（虚构）');
 await page.locator('#customer-form input[name=birth_date]').fill('2019-02-03');
 await page.locator('#customer-form input[name=contact_name]').fill('叶家长（虚构）');
 await page.locator('#customer-form button[type=submit]').click();
 await page.getByRole('heading',{name:'小叶（虚构）',exact:true}).waitFor();
 for(const [type,goal] of [['followup','建立长期复查档案，按约定日期继续跟进'],['training','训练服务需求登记，等待专业评估与计划确认']]){
  await page.locator('.cycle-heading button').click();
  await page.locator('#cycle-form select').selectOption(type);
  await page.locator('#cycle-form textarea').fill(goal);
  await page.locator('#cycle-form button[type=submit]').click();
  await page.getByText(goal,{exact:true}).waitFor();
 }
 assert.equal(await page.locator('.cycle-card').count(),2);
 await page.getByRole('button',{name:'＋ 登记到店',exact:true}).click();
 await page.locator('#visit-form textarea').fill('复查与训练需求登记（虚构）');
 for(const checkbox of await page.locator('#visit-form input[type=checkbox]').all())await checkbox.check();
 await page.locator('#visit-form button[type=submit]').click();
 await page.locator('.visit-card').waitFor();
 assert.ok((await page.locator('.visit-card').textContent()).includes('关联 2 个周期'));
 await page.getByRole('button',{name:'结束本次到店',exact:true}).click();
 await page.locator('#close-visit-form textarea').fill('本次到店结束，长期周期继续（虚构）');
 await page.locator('#close-visit-form button[type=submit]').click();
 await page.getByText('本次已结束',{exact:true}).waitFor();
 assert.equal(await page.locator('.cycle-card').count(),2);
 for(const active of ['true','false']){
  await page.getByRole('button',{name:'管理关联',exact:true}).click();
  await page.locator('#guardian-form input[name=relationship]').fill('监护人（演示）');
  await page.locator('#guardian-form select[name=active]').selectOption(active);
  await page.locator('#guardian-form textarea').fill('纯虚构资料演示授权或撤销');
  await page.locator('#guardian-form button[type=submit]').click();
  await page.locator('.family-row .badge').filter({hasText:active==='true'?'已授权':'已撤销'}).waitFor();
 }

 await page.getByRole('button',{name:'＋ 上传附件',exact:true}).click();
 await page.locator('#attachment-form input[type=file]').setInputFiles({name:'资料清单（虚构）.txt',mimeType:'text/plain',buffer:Buffer.from('虚构资料；仅用于开发展示')});
 await page.locator('#attachment-form button[type=submit]').click();
 await page.locator('.attachment-row .file-download').filter({hasText:'资料清单（虚构）.txt'}).waitFor();
 await page.getByRole('button',{name:'＋ 新建资料',exact:true}).click();
 await page.locator('#document-form input[name=title]').fill('接待资料备忘（虚构）');
 await page.locator('#document-form select[name=source]').selectOption('guardian_report');
 await page.locator('#document-form textarea[name=content]').fill('家长描述到店目的，等待进一步核对。');
 await page.locator('#document-file-options input[type=checkbox]').check();
 await page.locator('#document-form button[type=submit]').click();
 await page.locator('.document-card .badge').filter({hasText:'V1'}).waitFor();
 await page.getByRole('button',{name:'新增修订版本',exact:true}).click();
 await page.locator('#document-form select[name=source]').selectOption('employee');
 await page.locator('#document-form textarea[name=content]').fill('补充接待记录与后续安排（虚构），原始需求记录保留。');
 await page.locator('#document-form textarea[name=revision_reason]').fill('补充现场沟通内容（虚构）');
 await page.locator('#document-form button[type=submit]').click();
 await page.locator('.document-card .badge').filter({hasText:'V2'}).waitFor();
 await page.getByRole('button',{name:'查看历史版本',exact:true}).click();
 await page.locator('.version-card').first().waitFor();
 assert.equal(await page.locator('.version-card').count(),2);
 const downloadPromise=page.waitForEvent('download');
 await page.locator('.version-card').first().getByRole('button',{name:'资料清单（虚构）.txt',exact:true}).click();
 const download=await downloadPromise;assert.equal(download.suggestedFilename(),'资料清单（虚构）.txt');
 await page.screenshot({path:'data/browser-check/versions-desktop.png',fullPage:true});
 await page.locator('#history-dialog [data-close]').click();
 await page.locator('.attachment-row').getByRole('button',{name:'撤销访问',exact:true}).click();
 await page.locator('#revoke-file-form textarea').fill('演示资料访问撤销，历史引用保留');
 await page.locator('#revoke-file-form button[type=submit]').click();
 await page.locator('.attachment-row .file-download:disabled').waitFor();
 await page.screenshot({path:'data/browser-check/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'操作审计',exact:false}).click();
 await page.locator('#audit-items tr').filter({hasText:'创建服务周期草稿'}).first().waitFor();
 assert.ok((await page.locator('#audit-items').textContent()).includes('demo-manager'));
 await page.locator('[data-view=organization]').click();
 await page.locator('.staff-card').filter({hasText:'入职人员（虚构）'}).waitFor();
 await page.locator('#new-staff').click();
 for(const [name,value] of [['display_name','新同事（虚构）'],['username','browser-new-staff'],['initial_password','initial-browser-password'],['reason','虚构入职演示']])await page.locator(`#staff-create-form [name=${name}]`).fill(value);
 await page.locator('#staff-create-form button[type=submit]').click();
 const newStaff=page.locator('.staff-card').filter({hasText:'新同事（虚构）'});await newStaff.waitFor();
 assert.ok((await newStaff.textContent()).includes('待修改密码'));
 await newStaff.getByRole('button',{name:'编辑人员',exact:true}).click();
 await page.locator('#staff-edit-form select[name=role]').selectOption('professional');
 await page.locator('#staff-edit-form textarea').fill('虚构岗位调整');
 await page.locator('#staff-edit-form button[type=submit]').click();
 await newStaff.getByText('专业人员',{exact:true}).waitFor();
 await newStaff.getByRole('button',{name:'重置密码',exact:true}).click();
 await page.locator('#staff-security-form input[name=initial_password]').fill('reset-browser-password');
 await page.locator('#staff-security-form textarea').fill('虚构密码重置');
 await page.locator('#staff-security-form button[type=submit]').click();
 await page.locator('#staff-security-dialog').waitFor({state:'hidden'});
 await page.locator('.staff-card[data-revision="3"]').filter({hasText:'新同事（虚构）'}).waitFor();
 await newStaff.getByRole('button',{name:'撤销会话',exact:true}).click();
 await page.locator('#staff-security-form textarea').fill('虚构会话撤销');
 await page.locator('#staff-security-form button[type=submit]').click();
 await page.locator('#staff-security-dialog').waitFor({state:'hidden'});
 await page.locator('.staff-card[data-revision="4"]').filter({hasText:'新同事（虚构）'}).waitFor();
 await page.screenshot({path:'data/browser-check/organization-desktop.png',fullPage:true});
 const employeePage=await browser.newPage({viewport:{width:390,height:844}});employeePage.on('pageerror',e=>errors.push(e.message));
 await employeePage.goto(`http://127.0.0.1:${server.address().port}`);
 await employeePage.locator('#login-form input[name=username]').fill('browser-new-staff');
 await employeePage.locator('#login-form input[name=password]').fill('reset-browser-password');
 await employeePage.locator('#login-form button[type=submit]').click();
 await employeePage.locator('#password-dialog').waitFor({state:'visible'});
 await employeePage.keyboard.press('Escape');assert.equal(await employeePage.locator('#password-dialog').evaluate(d=>d.open),true);
 await employeePage.screenshot({path:'data/browser-check/password-mobile.png',fullPage:true});
 await employeePage.locator('#password-form input[name=current_password]').fill('reset-browser-password');
 for(const name of ['new_password','confirm_password'])await employeePage.locator(`#password-form input[name=${name}]`).fill('employee-personal-password');
 await employeePage.locator('#password-form button[type=submit]').click();
 await employeePage.locator('#password-dialog').waitFor({state:'hidden'});
 await employeePage.locator('.customer-row').first().waitFor();assert.equal(await employeePage.locator('#organization-nav').isVisible(),false);assert.equal(await employeePage.locator('#operations-nav').isVisible(),false);
 await page.locator('#refresh-organization').click();
 await page.locator('.staff-card[data-revision="5"]').filter({hasText:'新同事（虚构）'}).waitFor();
 await newStaff.getByRole('button',{name:'编辑人员',exact:true}).click();
 await page.locator('#staff-edit-form select[name=active]').selectOption('false');
 await page.locator('#staff-edit-form textarea').fill('虚构停用演示');
 await page.locator('#staff-edit-form button[type=submit]').click();
 await newStaff.getByText('已停用',{exact:true}).waitFor();
 await employeePage.reload();await employeePage.locator('#login-view').waitFor({state:'visible'});await employeePage.close();
 await page.locator('#account-security').click();
 await page.locator('#password-form input[name=current_password]').fill('local-browser-test-only');
 for(const name of ['new_password','confirm_password'])await page.locator(`#password-form input[name=${name}]`).fill('manager-personal-password');
 await page.locator('#password-form button[type=submit]').click();await page.locator('#password-dialog').waitFor({state:'hidden'});
 db.exec("CREATE TRIGGER browser_fault BEFORE INSERT ON audit_events WHEN NEW.action='customer.create' BEGIN SELECT RAISE(ABORT,'synthetic internal failure'); END;");
 await page.locator('#new-customer').click();await page.locator('#customer-form input[name=name]').fill('故障重试样例（虚构）');
 await page.locator('#customer-form button[type=submit]').click();
 await page.locator('#customer-error').filter({hasText:'故障编号'}).waitFor();
 const faultId=(await page.locator('#customer-error').textContent()).match(/[a-f0-9-]{36}/)?.[0];assert.ok(faultId);
 db.exec('DROP TRIGGER browser_fault');await page.locator('#customer-form button[type=submit]').click();
 await page.getByRole('heading',{name:'故障重试样例（虚构）',exact:true}).waitFor();
 assert.equal(db.prepare("SELECT count(*) n FROM customers WHERE name='故障重试样例（虚构）'").get().n,1);
 await page.locator('[data-view=operations]').click();await page.locator('#operations-errors code').filter({hasText:faultId}).waitFor();
 assert.ok((await page.locator('#operations-summary').textContent()).includes('服务错误1'));
 await page.locator('#refresh-operations').click();await page.locator('#operations-errors code').filter({hasText:faultId}).waitFor();
 await page.screenshot({path:'data/browser-check/operations-desktop.png',fullPage:true});
 await page.locator('[data-view=demo]').click();
 await page.locator('.scenario-card').first().waitFor();
 assert.equal(await page.locator('.scenario-card').count(),6);
 await page.screenshot({path:'data/browser-check/demo-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile demo page must not overflow');
 await page.screenshot({path:'data/browser-check/demo-mobile.png',fullPage:true});
 await page.locator('[data-view=operations]').click();
 await page.locator('#operations-errors code').filter({hasText:faultId}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile operations page must not overflow');
 await page.screenshot({path:'data/browser-check/operations-mobile.png',fullPage:true});
 await page.locator('[data-view=organization]').click();
 await page.locator('.staff-card').first().waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile organization page must not overflow');
 await page.screenshot({path:'data/browser-check/organization-mobile.png',fullPage:true});
 await page.locator('[data-view=demo]').click();
 await page.locator('.scenario-card').first().getByRole('button',{name:'查看关联档案 →'}).click();
 await page.locator('.detail-top').waitFor();

 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile page must not overflow');
 await page.locator('#new-customer').click();
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#customer-dialog').evaluate(d=>d.open),false);
 await page.screenshot({path:'data/browser-check/mobile.png',fullPage:true});
 await page.locator('#logout-mobile').click();
 await page.locator('#login-view').waitFor({state:'visible'});
 assert.equal(await page.locator('#customer-items').textContent(),'');assert.equal(await page.locator('#operations-errors').textContent(),'');
 assert.deepEqual(errors,[]);
 console.log('Browser checks passed: correlated failures/retry, store operations/status, staff onboarding/edit/reset/revoke/disable, forced and personal password changes, attachments upload/download/revoke, immutable revisions/history, six scenarios, family/visits, desktop/mobile, Escape and session logout.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
