import {randomUUID} from 'node:crypto';
import {transaction} from './db.mjs';
import * as C from './contact.mjs';
export function seedDemoContact(db){const empty={consents:0,cases:0,attempts:0,receipts:0,appointments:0};if(db.prepare('SELECT 1 FROM contact_consents UNION ALL SELECT 1 FROM contact_cases LIMIT 1').get())return empty;for(const [id,role]of [['demo-front','reception'],['demo-manager','manager']])if(!db.prepare('SELECT 1 FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=? AND u.role=? AND u.store_id=? AND u.active=1 AND coalesce(s.must_change_password,0)=0').get(id,role,'store-a'))return empty;if(!db.prepare("SELECT 1 FROM customers WHERE id='sample-intake' AND store_id='store-a'").get())return empty;
 return transaction(db,()=>{const now=new Date().toISOString(),future=new Date(Date.now()+86400000).toISOString(),past=new Date(Date.now()-86400000).toISOString(),reason='联系与预约流程虚构演示；未向任何人发送消息',note={note:'人工明确办理（虚构）',reason},grant=(customer,id,category='service')=>C.createContactConsent(db,'store-a',customer,{category,channel:'phone',recipient_label:'明确演示接收人（虚构）',address:'synthetic-contact-only',effective_at:past,source_note:'人工明确记录演示授权（虚构）；不代表真实授权',...note},'demo-front',now,id),g=grant('sample-intake','demo-contact-service-consent'),marketing=grant('sample-intake','demo-contact-marketing-consent','marketing');C.contactConsentEvent(db,marketing.id,{action:'revoke',...note},'demo-front',now);
 const manual={kind:'manual',id:null,version:null,revision:null},base={source:manual,source_note:'人工明确服务来源（虚构）',title:'失联待人工跟进（虚构）',purpose_note:'明确服务目的，发送与读到分开（虚构）',owner_id:'demo-front',due_at:future,next_action:'责任前台继续核对联系方式（虚构）',...note},p=db.prepare("SELECT p.id,e.revision FROM review_plans p JOIN review_plan_current e ON e.plan_id=p.id WHERE p.id='demo-review-scheduled' AND e.status='scheduled'").get(),c=C.createContactCase(db,'store-a','sample-intake',{...base,purpose:'followup',source:p?{kind:'review',id:p.id,version:null,revision:p.revision}:manual},'demo-front',now,'demo-contact-handoff'),actual={consent_id:g.id,consent_revision:1,occurred_at:now,result:'no_answer',source_note:'前台人工联系记录（虚构）',content_summary:'明确复查联系摘要（虚构）',result_note:'无人接听，转人工责任跟进（虚构）',due_at:future,next_action:'再次联系并核对明确意向（虚构）',reason};C.recordContactAttempt(db,c.id,actual,'demo-front',now,'demo-contact-no-answer');
 const sent=C.createContactCase(db,'store-a','sample-intake',{...base,title:'发出未读待回执（虚构）',purpose:'other_service'},'demo-front',now,'demo-contact-sent');const a=C.recordContactAttempt(db,sent.id,{...actual,result:'sent',result_note:'仅人工记录发出，尚无已读（虚构）'},'demo-front',now,'demo-contact-sent-attempt');C.recordContactReceipt(db,a.id,{status:'unknown',source:'staff_transcript',occurred_at:now,source_note:'回执状态未取得（虚构）',result_note:'不从发送成功推断已读（虚构）',reason},'demo-front',now);
 const delayed=C.createContactCase(db,'store-a','sample-intake',{...base,title:'延期后再次联系（虚构）',purpose:'other_service'},'demo-front',now,'demo-contact-deferred');C.contactCaseEvent(db,delayed.id,{...base,action:'defer',next_action:'按客户明确延期日期再次联系（虚构）'},'demo-front',now);
 const arrived=C.createContactCase(db,'store-a','sample-intake',{...base,title:'预约后已关联到店（虚构）',purpose:'other_service'},'demo-front',now,'demo-contact-arrived');const ap=C.createCustomerAppointment(db,arrived.id,{starts_at:past,ends_at:new Date(Date.now()-82800000).toISOString(),purpose_note:'客户明确服务预约（虚构）',place_note:'演示门店（虚构）',source_note:'人工记录客户意向（虚构）',owner_id:'demo-front',...note},'demo-front',now,'demo-contact-appointment-arrived'),v=db.prepare("SELECT id FROM visits WHERE id='demo-visit-intake' AND customer_id='sample-intake'").get();if(v)C.customerAppointmentEvent(db,ap.id,{action:'arrive',visit_id:v.id,arrived_at:now,...note},'demo-front',now);C.createCustomerAppointment(db,delayed.id,{starts_at:future,ends_at:new Date(Date.now()+90000000).toISOString(),purpose_note:'明确延期后的预约（虚构）',place_note:'演示门店（虚构）',source_note:'明确客户延期意向（虚构）',owner_id:'demo-front',...note},'demo-front',now,'demo-contact-appointment-planned');
 let cases=4,consents=2;const order=db.prepare("SELECT p.id,p.customer_id,v.version FROM retail_orders p JOIN retail_order_versions v ON v.order_id=p.id WHERE p.id='demo-order-draft' AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=p.id) AND v.status!='cancelled'").get();if(order){grant(order.customer_id,'demo-contact-pickup-consent');C.createContactCase(db,'store-a',order.customer_id,{...base,title:'取镜时间待核对（虚构）',purpose:'pickup',source:{kind:'order',id:order.id,version:order.version,revision:null},source_note:'关联原单人工核对取镜意向（虚构）；未自动确认商品就绪'},'demo-front',now,'demo-contact-pickup');cases++;consents++;}const tp=db.prepare("SELECT p.id,p.customer_id,e.plan_version version,e.revision FROM training_plans p JOIN training_plan_events e ON e.plan_id=p.id WHERE p.id='demo-training-plan-ready' AND e.revision=(SELECT max(revision) FROM training_plan_events WHERE plan_id=p.id) AND e.status='active'").get();if(tp){grant(tp.customer_id,'demo-contact-training-consent');C.createContactCase(db,'store-a',tp.customer_id,{...base,title:'训练服务联系（虚构）',purpose:'training',source:{kind:'training',id:tp.id,version:tp.version,revision:tp.revision}},'demo-front',now,'demo-contact-training');cases++;consents++;}
 for(const id of [c.id,sent.id,delayed.id,arrived.id])db.prepare('INSERT INTO audit_events VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),'store-a','demo-front','contacts.demo.seed',id,null,JSON.stringify({source:'synthetic',reason}),now);return {consents,cases,attempts:2,receipts:1,appointments:2};});}
