import {randomUUID} from 'node:crypto';
import {canonicalTime} from './training.mjs';
export const entitlementTables=['entitlement_packages','entitlement_package_versions','entitlement_accounts','entitlement_events'];
export const entitlementRuleFields=['paid_note','gift_note','validity_note','deduction_note','freeze_note','reversal_note','refund_note'];
export const validDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00.000Z'))&&new Date(v+'T00:00:00.000Z').toISOString().slice(0,10)===v;
export const validRange=(a,b)=>a===null&&b===null||validDate(a)&&validDate(b)&&a<=b;
const insert=(db,t,o)=>db.prepare('INSERT INTO '+t+' ('+Object.keys(o).join(',')+') VALUES ('+Object.keys(o).map(()=>'?').join(',')+')').run(...Object.values(o));
export function entitlementPackage(db,id,version=null){const p=db.prepare('SELECT * FROM entitlement_packages WHERE id=?').get(id);if(!p)return null;const v=db.prepare('SELECT * FROM entitlement_package_versions WHERE package_id=? '+(version?'AND version=?':'ORDER BY version DESC LIMIT 1')).get(...(version?[id,version]:[id]));return v?{...p,...v,id:p.id,created_at:p.created_at,created_by:p.created_by,version_created_at:v.created_at,version_created_by:v.created_by}:null;}
export function insertEntitlementPackageVersion(db,id,input,actor,now=new Date().toISOString()){const p=entitlementPackage(db,id),v={package_id:id,store_id:db.prepare('SELECT store_id FROM entitlement_packages WHERE id=?').get(id).store_id,version:(p?.version||0)+1,name:input.name,kind:input.kind,status:input.status,service_scope:input.service_scope,source_note:input.source_note,...Object.fromEntries(entitlementRuleFields.map(k=>[k,input[k]??null])),account_sequence:db.prepare('SELECT COALESCE(max(serial),0) n FROM entitlement_accounts WHERE store_id=?').get(db.prepare('SELECT store_id FROM entitlement_packages WHERE id=?').get(id).store_id).n,reason:input.reason,created_at:now,created_by:actor};insert(db,'entitlement_package_versions',v);return entitlementPackage(db,id);}
export function createEntitlementPackage(db,store,input,actor,now=new Date().toISOString(),id=randomUUID()){insert(db,'entitlement_packages',{id,store_id:store,code:input.code,created_at:now,created_by:actor});return insertEntitlementPackageVersion(db,id,input,actor,now);}
export function entitlementEvent(db,id){const e=db.prepare('SELECT e.*,u.display_name author_name FROM entitlement_events e JOIN users u ON u.id=e.created_by WHERE e.id=?').get(id);if(!e)return null;const n=db.prepare('SELECT count(*) n,COALESCE(sum(quantity),0) units FROM entitlement_events WHERE source_event_id=?').get(id);return {...e,reversed_quantity:e.quantity===null?null:n.units,remaining_quantity:e.action==='grant'&&e.quantity!==null?e.quantity-n.units:null,fully_reversed:e.action==='grant'&&(e.quantity===null?n.n>0:e.quantity===n.units),reversal_count:n.n};}
export const entitlementCustomerSequence=(db,id)=>db.prepare('SELECT COALESCE(max(sequence),0) n FROM entitlement_events WHERE customer_id=?').get(id).n;
export function entitlementBalances(db,id){const kind=db.prepare('SELECT p.kind FROM entitlement_accounts a JOIN entitlement_package_versions p ON p.package_id=a.package_id AND p.version=a.package_version WHERE a.id=?').get(id).kind;const rows=db.prepare("SELECT origin,action,count(*) n,COALESCE(sum(quantity),0) units FROM entitlement_events WHERE account_id=? GROUP BY origin,action").all(id),r={};for(const origin of ['paid','gift']){const g=rows.find(r=>r.origin===origin&&r.action==='grant'),v=rows.find(r=>r.origin===origin&&r.action==='reverse');r[origin]={recorded:kind==='count'?g?.units||0:null,reversed:kind==='count'?v?.units||0:null,remaining:kind==='count'?(g?.units||0)-(v?.units||0):null,periods_recorded:kind==='period'?g?.n||0:null,periods_reversed:kind==='period'?v?.n||0:null,periods_retained:kind==='period'?(g?.n||0)-(v?.n||0):null};}return r;}
export function entitlementAccount(db,id,{limit=50,offset=0}={}){const a=db.prepare('SELECT a.*,c.name customer_name FROM entitlement_accounts a JOIN customers c ON c.id=a.customer_id WHERE a.id=?').get(id);if(!a)return null;const p=entitlementPackage(db,a.package_id,a.package_version),current=entitlementPackage(db,a.package_id),revision=db.prepare('SELECT COALESCE(max(revision),0) n FROM entitlement_events WHERE account_id=?').get(id).n,total=db.prepare('SELECT count(*) n FROM entitlement_events WHERE account_id=?').get(id).n;return {...a,package:p,current_package_version:current.version,kind:p.kind,revision,customer_sequence:entitlementCustomerSequence(db,a.customer_id),created_customer_sequence:a.customer_sequence,balances:entitlementBalances(db,id),history:db.prepare('SELECT id FROM entitlement_events WHERE account_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset).map(x=>entitlementEvent(db,x.id)),total,next_offset:offset+limit<total?offset+limit:null};}
export function insertEntitlementEvent(db,id,input,actor,now=new Date().toISOString(),eid=randomUUID()){const a=db.prepare('SELECT customer_id,store_id FROM entitlement_accounts WHERE id=?').get(id);let e={id:eid,account_id:id,...a,sequence:entitlementCustomerSequence(db,a.customer_id)+1,revision:db.prepare('SELECT COALESCE(max(revision),0)+1 n FROM entitlement_events WHERE account_id=?').get(id).n,action:input.action,origin:input.origin,quantity:input.quantity??null,source_event_id:input.source_event_id??null,valid_start:input.valid_start??null,valid_end:input.valid_end??null,basis_reference:input.basis_reference,basis_note:input.basis_note,document_version_id:input.document_version_id??null,attachment_id:input.attachment_id??null,occurred_at:input.occurred_at,note:input.note,reason:input.reason,created_at:now,created_by:actor};if(input.action==='reverse'){const s=entitlementEvent(db,input.source_event_id);for(const k of ['origin','valid_start','valid_end','basis_reference','basis_note','document_version_id','attachment_id','occurred_at'])e[k]=s[k];}insert(db,'entitlement_events',e);return {event:entitlementEvent(db,e.id),account:entitlementAccount(db,id)};}
export function createEntitlementAccount(db,store,customer,input,actor,now=new Date().toISOString(),id=randomUUID()){const serial=db.prepare('SELECT COALESCE(max(serial),0)+1 n FROM entitlement_accounts WHERE store_id=?').get(store).n;insert(db,'entitlement_accounts',{id,store_id:store,customer_id:customer,package_id:input.package_id,package_version:input.package_version,cycle_id:input.cycle_id,cycle_version:input.cycle_version,plan_id:input.plan_id??null,plan_version:input.plan_version??null,customer_sequence:entitlementCustomerSequence(db,customer),context_basis:input.plan_id?'plan':'cycle',serial,account_number:'EA-'+now.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),created_at:now,created_by:actor});return insertEntitlementEvent(db,id,{...input.grant,action:'grant'},actor,now);}
export function entitlementSummary(db,customer){const rows=db.prepare('SELECT a.id,p.name,p.kind,a.package_version,a.account_number FROM entitlement_accounts a JOIN entitlement_package_versions p ON p.package_id=a.package_id AND p.version=a.package_version WHERE a.customer_id=? ORDER BY a.serial DESC LIMIT 101').all(customer),total=db.prepare('SELECT count(*) n FROM entitlement_accounts WHERE customer_id=?').get(customer).n;const counts=db.prepare("SELECT p.kind,e.origin,e.action,count(*) n,COALESCE(sum(e.quantity),0) units FROM entitlement_events e JOIN entitlement_accounts a ON a.id=e.account_id JOIN entitlement_package_versions p ON p.package_id=a.package_id AND p.version=a.package_version WHERE a.customer_id=? GROUP BY p.kind,e.origin,e.action").all(customer);return {total,truncated:rows.length>100,accounts:rows.slice(0,100).map(a=>({...a,balances:entitlementBalances(db,a.id)})),totals:['count','period'].map(kind=>({kind,...Object.fromEntries(['paid','gift'].map(origin=>{const g=counts.find(x=>x.kind===kind&&x.origin===origin&&x.action==='grant'),v=counts.find(x=>x.kind===kind&&x.origin===origin&&x.action==='reverse');return [origin,{recorded:kind==='count'?g?.units||0:g?.n||0,reversed:kind==='count'?v?.units||0:v?.n||0,retained:kind==='count'?(g?.units||0)-(v?.units||0):(g?.n||0)-(v?.n||0)}];}))})),eligibility:'not_evaluated',deduction:'not_connected',expiry:'not_evaluated'};}
export {canonicalTime};
