import {parameterContext,guardParameters,executionParameterRef} from './parameter-ledger.mjs';
import {randomUUID} from 'node:crypto';
import {processingRecord} from './processing.mjs';
export const fulfillmentTables=['fulfillment_events'];
export const fulfillmentActions=['check_pass','check_fail','rework_assign','rework_start','rework_complete','deliver'];
const parentAction={check_pass:'rework_complete',check_fail:'rework_complete',rework_assign:'check_fail',rework_start:'rework_assign',rework_complete:'rework_start',deliver:'check_pass'};
const isCheck=a=>a==='check_pass'||a==='check_fail';
function worker(e,all){const assign=e.action==='rework_assign'?e:e.action==='rework_start'?all.find(x=>x.id===e.source_id):e.action==='rework_complete'?all.find(x=>x.id===all.find(y=>y.id===e.source_id)?.source_id):null;return assign?.assignee_id||null;}
function withChecks(e){const {checks_json,...rest}=e;return {...rest,checks:JSON.parse(checks_json)};}
export function fulfillmentState(lines){return lines.every(l=>l.delivered===l.quantity)?'delivered':lines.some(l=>l.delivered>0)?'partial':lines.some(l=>l.failed+l.assigned+l.reworking>0)?'rework':lines.some(l=>l.approved>0)?'ready':'pending_review';}
export function fulfillmentRecord(db,id,{limit=50,offset=0}={}){
 const job=processingRecord(db,id);if(!job)return null;const events=db.prepare('SELECT e.*,u.display_name author_name FROM fulfillment_events e JOIN users u ON u.id=e.created_by WHERE job_id=? ORDER BY revision').all(id),lines=job.lines.map(l=>({...l,uninspected:l.completed,approved:0,failed:0,assigned:0,reworking:0,recheck:0,delivered:0}));
 for(const e of events){const l=lines.find(x=>x.position===e.position),q=e.quantity;if(isCheck(e.action)){l[e.source_id?'recheck':'uninspected']-=q;l[e.action==='check_pass'?'approved':'failed']+=q;}else if(e.action==='rework_assign'){l.failed-=q;l.assigned+=q;}else if(e.action==='rework_start'){l.assigned-=q;l.reworking+=q;}else if(e.action==='rework_complete'){l.reworking-=q;l.recheck+=q;}else{l.approved-=q;l.delivered+=q;}}
 const batches=events.map(e=>{const assignee_id=worker(e,events),u=assignee_id?db.prepare('SELECT display_name,active,store_id FROM users WHERE id=?').get(assignee_id):null;return {...withChecks(e),parameter_reference:executionParameterRef(db,e.id),source_revision:events.find(p=>p.id===e.source_id)?.revision||null,remaining:e.quantity-events.filter(x=>x.source_id===e.id).reduce((n,x)=>n+x.quantity,0),assignee_id:assignee_id||e.assignee_id,assignee_name:u?.display_name||null,assignee_available:Boolean(u?.active&&u.store_id===job.store_id)};});
 return {parameter_context:parameterContext(db,id),id:job.id,job_number:job.job_number,order_id:job.order_id,order_version:job.order_version,customer_id:job.customer_id,customer_name:job.customer_name,store_id:job.store_id,title:job.title,cycle_version:job.cycle_version,visit_id:job.visit_id,processing_revision:job.current_revision,processing_state:job.state,revision:events.at(-1)?.revision||0,state:fulfillmentState(lines),lines,batches:batches.filter(e=>e.remaining>0),history:batches.slice().reverse().slice(offset,offset+limit),total:events.length,next_offset:offset+limit<events.length?offset+limit:null};
}
function validateEvent(e,prior,processing){
 const line=processing.lines.find(l=>l.position===e.position),source=prior.find(x=>x.id===e.source_id),checks=JSON.parse(e.checks_json);if(!line||processing.action==='cancel'||e.created_at<processing.event_created_at||line.completed<1)throw Error('质检交付加工来源核对失败');
 if(e.source_id){if(!source||source.position!==e.position||source.action!==parentAction[e.action]||source.created_at>e.created_at||e.quantity+prior.filter(x=>x.source_id===source.id).reduce((n,x)=>n+x.quantity,0)>source.quantity)throw Error('质检返工来源或数量核对失败');}else if(!isCheck(e.action)||e.quantity+prior.filter(x=>x.position===e.position&&!x.source_id).reduce((n,x)=>n+x.quantity,0)>line.completed)throw Error('初次质检数量核对失败');
 if(!Array.isArray(checks)||isCheck(e.action)&&(!checks.length||checks.length>20)||!isCheck(e.action)&&e.checks_json!=='[]'||checks.some(c=>!c||Object.keys(c).sort().join(',')!=='label,notes,result'||typeof c.label!=='string'||!c.label.trim()||c.label.length>120||!['pass','fail'].includes(c.result)||typeof c.notes!=='string'||c.notes.length>1000)||e.action==='check_pass'&&checks.some(c=>c.result==='fail')||e.action==='check_fail'&&!checks.some(c=>c.result==='fail'))throw Error('质检项目/结论核对失败');
 if(e.action==='rework_assign'&&(!e.assignee_id||typeof e.instructions!=='string'||!e.instructions.trim()||e.instructions.length>1000)||e.action!=='rework_assign'&&(e.assignee_id!==undefined&&e.assignee_id!==null||e.instructions!==undefined&&e.instructions!==null))throw Error('返工安排核对失败');
 if(e.action==='deliver'&&(typeof e.handed_at!=='string'||!Number.isFinite(Date.parse(e.handed_at))||new Date(e.handed_at).toISOString()!==e.handed_at||e.handed_at<'2000-01-01T00:00:00.000Z'||e.handed_at>e.created_at||!e.receiver_name?.trim()||!e.receipt_note?.trim()))throw Error('交付签收核对失败');
}
export function verifyFulfillment(db){for(const {id} of db.prepare('SELECT DISTINCT job_id id FROM fulfillment_events').iterate()){const all=db.prepare('SELECT * FROM fulfillment_events WHERE job_id=? ORDER BY revision').all(id),prior=[];for(const e of all){if(e.revision!==prior.length+1||e.created_at<(prior.at(-1)?.created_at||'')||!Number.isSafeInteger(e.quantity)||e.quantity<1||e.quantity>999)throw Error('质检交付连续历史核对失败');const p=processingRecord(db,id,e.processing_revision);if(!p||db.prepare('SELECT 1 FROM processing_events WHERE job_id=? AND revision>? AND created_at<?').get(id,e.processing_revision,e.created_at))throw Error('质检交付加工版本核对失败');validateEvent(e,prior,p);prior.push(e);}const record=fulfillmentRecord(db,id);if(record.lines.some(l=>['uninspected','approved','failed','assigned','reworking','recheck','delivered'].some(k=>l[k]<0)||l.uninspected+l.approved+l.failed+l.assigned+l.reworking+l.recheck+l.delivered!==l.completed))throw Error('质检交付当前分项数量核对失败');}}
export function insertFulfillmentEvent(db,id,input,actor,now=new Date().toISOString(),eventId=randomUUID()){
 const before=fulfillmentRecord(db,id),e={id:eventId,job_id:id,revision:before.revision+1,processing_revision:before.processing_revision,position:input.position,action:input.action,quantity:input.quantity,source_id:input.source_id||null,assignee_id:input.action==='rework_assign'?input.assignee_id:null,instructions:input.action==='rework_assign'?input.instructions:null,checks_json:JSON.stringify(input.checks||[]),receiver_name:input.action==='deliver'?input.receiver_name:null,receipt_note:input.action==='deliver'?input.receipt_note:null,handed_at:input.action==='deliver'?input.handed_at:null,reason:input.reason,created_at:now,created_by:actor};db.prepare('INSERT INTO fulfillment_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...Object.values(e));return {event:withChecks(e),fulfillment:fulfillmentRecord(db,id)};
}
export function createFulfillmentHandler(db,{need,customer,field,fail,body,mutation,audit}){
 const integer=(v,name,min=0,max=1e9)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail(422,'VALIDATION',name+'须为范围内整数');return v;},keys=(v,allowed)=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k)))fail(422,'VALIDATION','请仅提交本次质检交付字段');},local=(u,id)=>{const j=db.prepare('SELECT * FROM processing_jobs WHERE id=? AND store_id=?').get(id,u.store_id);if(!j)fail(404,'NOT_FOUND','加工工单不存在或不在本店');customer(u,j.customer_id);return j;},paging=url=>{const l=url.searchParams.get('limit')||'50',o=url.searchParams.get('offset')||'0';if(!/^\d{1,3}$/.test(l)||+l<1||+l>100||!/^\d{1,6}$/.test(o))fail(422,'VALIDATION','分页范围不正确');return {limit:+l,offset:+o};};
 return async(req,path,url,user,json)=>{
  const list=path==='/api/fulfillment/jobs',match=/^\/api\/processing\/jobs\/([\w-]+)\/fulfillment(\/events)?$/.exec(path);if(!list&&!match)return false;need(user,'fulfillment:read');
  if(list){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const q=field(url.searchParams.get('q'),'搜索',120)||'',state=url.searchParams.get('state')||'all',{limit,offset}=paging(url);if(!['all','pending_review','rework','ready','partial','delivered'].includes(state))fail(422,'VALIDATION','质检交付筛选不正确');const records=db.prepare("SELECT j.id FROM processing_jobs j JOIN processing_events e ON e.job_id=j.id AND e.revision=(SELECT max(revision) FROM processing_events WHERE job_id=j.id) WHERE j.store_id=? AND e.action<>'cancel' AND EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.completed')>0) ORDER BY j.created_at DESC,j.id").all(user.store_id).map(j=>fulfillmentRecord(db,j.id,{limit:1})).filter(j=>(state==='all'||j.state===state)&&(!q||[j.job_number,j.customer_name,j.title].join(' ').toLowerCase().includes(q.toLowerCase()))),counts=Object.fromEntries(['pending_review','rework','ready','partial','delivered'].map(s=>[s,records.filter(j=>j.state===s).length]));json(200,{items:records.slice(offset,offset+limit).map(({batches,history,...r})=>r),total:records.length,counts,limit,offset,next_offset:offset+limit<records.length?offset+limit:null});return true;}
  const j=local(user,match[1]);if(req.method==='GET'&&!match[2]){json(200,{fulfillment:fulfillmentRecord(db,j.id,paging(url))});return true;}if(req.method!=='POST'||!match[2])fail(405,'METHOD','不支持此请求');const b=await body(req,65536),action=b.action;if(!fulfillmentActions.includes(action))fail(422,'VALIDATION','质检交付操作不正确');need(user,isCheck(action)?'fulfillment:check':action==='deliver'?'fulfillment:deliver':action==='rework_assign'?'fulfillment:assign':'fulfillment:execute');keys(b,['expected_parameter_sequence','expected_parameter_review_revision','expected_revision','expected_processing_revision','position','quantity','action','source_id','reason',...(isCheck(action)?['checks']:action==='rework_assign'?['assignee_id','instructions']:action==='deliver'?['receiver_name','receipt_note','handed_at']:[])]);const input={expected_parameter_sequence:integer(b.expected_parameter_sequence??0,'参数流水'),expected_parameter_review_revision:integer(b.expected_parameter_review_revision??0,'变更核对版本'),expected_revision:integer(b.expected_revision,'质检交付版本'),expected_processing_revision:integer(b.expected_processing_revision,'加工来源版本',1),position:integer(b.position,'原单行',1,30),quantity:integer(b.quantity,'本次数量',1,999),action,source_id:b.source_id===null||b.source_id===undefined?null:field(b.source_id,'原事件来源',100,true),reason:field(b.reason,'操作依据',300,true)};
  if(isCheck(action)){if(!Array.isArray(b.checks)||!b.checks.length||b.checks.length>20)fail(422,'VALIDATION','请明确本次1–20个质检项目和结果');input.checks=b.checks.map(c=>{keys(c,['label','result','notes']);if(!['pass','fail'].includes(c.result))fail(422,'VALIDATION','项目结论须为合格或不合格');return {label:field(c.label,'质检项目',120,true),result:c.result,notes:field(c.notes,'质检记录',1000)||''};});if(action==='check_pass'&&input.checks.some(c=>c.result==='fail')||action==='check_fail'&&!input.checks.some(c=>c.result==='fail'))fail(422,'CHECK_RESULT','项目结果与本次结论不一致');}
  if(action==='rework_assign'){input.assignee_id=field(b.assignee_id,'返工责任人',100,true);input.instructions=field(b.instructions,'返工说明',1000,true);}
  if(action==='deliver'){input.receiver_name=field(b.receiver_name,'实际领取人',120,true);input.receipt_note=field(b.receipt_note,'签收与调整记录',1000,true);input.handed_at=field(b.handed_at,'实际交付时间',30,true);if(!Number.isFinite(Date.parse(input.handed_at))||new Date(input.handed_at).toISOString()!==input.handed_at||input.handed_at<'2000-01-01T00:00:00.000Z'||input.handed_at>new Date().toISOString())fail(422,'VALIDATION','请记录2000年之后且不晚于当前的规范UTC交付时间');}
  json(201,mutation(req,user,'fulfillment.'+action+':'+j.id,input,()=>{local(user,j.id);guardParameters(db,j.id,input,fail);const before=fulfillmentRecord(db,j.id);if(before.revision!==input.expected_revision||before.processing_revision!==input.expected_processing_revision)fail(409,'FULFILLMENT_CONFLICT','加工或质检交付已有变化，请读取最新记录');const p=processingRecord(db,j.id),prior=db.prepare('SELECT * FROM fulfillment_events WHERE job_id=? ORDER BY revision').all(j.id),source=prior.find(e=>e.id===input.source_id);try{validateEvent({...input,checks_json:JSON.stringify(input.checks||[]),created_at:new Date().toISOString()},prior,p);}catch(err){fail(409,'FULFILLMENT_STATE',err.message);}
   if(action==='rework_assign'){const a=db.prepare('SELECT * FROM users WHERE id=?').get(input.assignee_id);if(!a?.active||a.store_id!==user.store_id||!['manager','reception','professional'].includes(a.role))fail(409,'ASSIGNEE_UNAVAILABLE','返工责任人已不可用，请重新安排');}
   if(['rework_start','rework_complete'].includes(action)&&user.role!=='manager'&&worker(source,prior)!==user.id)fail(403,'NOT_ASSIGNEE','仅本次返工责任人或负责人可执行');const result=insertFulfillmentEvent(db,j.id,input,user.id);audit(user,'fulfillment.'+action,result.event.id,result,before);return result;}));return true;
 };
}
