import {productReturnCustody} from './return-custody.mjs';
import {physicalStock,hasOutbounds} from './stock-ledger.mjs';
import {stockInProcessing} from './processing.mjs';
import { randomUUID } from 'node:crypto';
export const inventoryTables=['inventory_events','inventory_order_events','inventory_order_lines'];
const catalog=(db,id)=>db.prepare('SELECT p.id,p.store_id,p.sku,v.* FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id WHERE p.id=? ORDER BY v.version DESC LIMIT 1').get(id);
export function stockBalance(db,id){return physicalStock(db,id);}
export function activeReservation(db,id){const last=db.prepare('SELECT * FROM inventory_order_events WHERE order_id=? ORDER BY revision DESC LIMIT 1').get(id);return last?.action==='reserve'?last:null;}
function reservationLines(db,eventId){return db.prepare('SELECT l.*,p.sku,v.name,v.unit FROM inventory_order_lines l JOIN retail_products p ON p.id=l.product_id JOIN retail_product_versions v ON v.product_id=l.product_id AND v.version=l.product_version WHERE l.event_id=? ORDER BY l.position').all(eventId);}
export function orderInventory(db,id){
 const o=db.prepare('SELECT o.*,v.version,v.title,v.status FROM retail_orders o JOIN retail_order_versions v ON v.order_id=o.id WHERE o.id=? ORDER BY v.version DESC LIMIT 1').get(id);if(!o)return null;
 const items=db.prepare('SELECT i.*,p.sku,v.name,v.unit,v.category FROM retail_order_items i JOIN retail_products p ON p.id=i.product_id JOIN retail_product_versions v ON v.product_id=i.product_id AND v.version=i.product_version WHERE i.order_id=? AND i.version=? ORDER BY i.position').all(id,o.version),tracked=items.filter(x=>x.category!=='service'),groups=new Map();
 for(const row of tracked){let g=groups.get(row.product_id);if(!g){const current=catalog(db,row.product_id),balance=stockBalance(db,row.product_id);g={product_id:row.product_id,sku:row.sku,name:row.name,unit:row.unit,required:0,...balance,catalog_version:current.version,catalog_status:current.status,eligible:current.status==='active'&&current.category===row.category&&current.unit===row.unit};groups.set(row.product_id,g);}g.required+=row.quantity;if(row.unit!==g.unit||catalog(db,row.product_id).category!==row.category)g.eligible=false;}
 const latest=db.prepare('SELECT * FROM inventory_order_events WHERE order_id=? ORDER BY revision DESC LIMIT 1').get(id),active=latest?.action==='reserve'?latest:null,history=db.prepare('SELECT id,revision,action,source_id,order_version,reason,created_at,created_by FROM inventory_order_events WHERE order_id=? ORDER BY revision DESC LIMIT 100').all(id).map(e=>({...e,lines:reservationLines(db,e.id)})),requirements=[...groups.values()].map(g=>({...g,shortage:Math.max(0,g.required-g.available)}));
 const dispatched=hasOutbounds(db)?db.prepare('SELECT COALESCE(sum(quantity),0) n FROM inventory_outbounds WHERE order_id=?').get(id).n:0;
 return {dispatch_locked:dispatched>0,processing_stock_locked:stockInProcessing(db,id),order_id:id,order_version:o.version,order_number:o.order_number,title:o.title,customer_id:o.customer_id,status:o.status,revision:latest?.revision||0,active:active?{id:active.id,order_version:active.order_version,reason:active.reason,created_at:active.created_at,lines:reservationLines(db,active.id)}:null,requirements,service_lines:items.length-tracked.length,stock_versions:requirements.map(x=>({product_id:x.product_id,sequence:x.sequence,outbound_revision:x.outbound_revision})).sort((a,b)=>a.product_id.localeCompare(b.product_id)),can_reserve:o.status==='draft'&&!active&&!dispatched&&tracked.length>0&&requirements.every(x=>x.eligible&&!x.shortage),history,history_truncated:(latest?.revision||0)>100};
}
export function insertStockEvent(db,{id=randomUUID(),product_id,product_version,store_id,action,quantity,order_event_id=null,order_position=null,reason,created_at=new Date().toISOString(),created_by}){
 const before=db.prepare('SELECT sequence,available,reserved,quarantined FROM inventory_events WHERE product_id=? ORDER BY sequence DESC LIMIT 1').get(product_id)||{sequence:0,available:0,reserved:0,quarantined:0},available=before.available+(['receive','unquarantine','release'].includes(action)?quantity:-quantity),reserved=before.reserved+(action==='reserve'?quantity:action==='release'?-quantity:0),quarantined=before.quarantined+(action==='isolate'?quantity:action==='unquarantine'?-quantity:0);
 db.prepare('INSERT INTO inventory_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,product_id,product_version,store_id,before.sequence+1,action,quantity,available,reserved,quarantined,order_event_id,order_position,reason,created_at,created_by);return db.prepare('SELECT * FROM inventory_events WHERE id=?').get(id);
}
export function insertReservation(db,id,action,reason,actor,now=new Date().toISOString(),eventId=randomUUID()){
 const state=orderInventory(db,id),o=db.prepare('SELECT * FROM retail_orders WHERE id=?').get(id),source=state.active,items=action==='release'?source.lines:db.prepare("SELECT i.* FROM retail_order_items i JOIN retail_product_versions v ON v.product_id=i.product_id AND v.version=i.product_version WHERE i.order_id=? AND i.version=? AND v.category<>'service' ORDER BY i.position").all(id,state.order_version),lines=items.map(x=>({position:x.position,product_id:x.product_id,product_version:x.product_version,quantity:x.quantity,stock_event_id:randomUUID()})),version=action==='release'?source.order_version:state.order_version;
 db.prepare('INSERT INTO inventory_order_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(eventId,id,version,o.customer_id,o.store_id,state.revision+1,action,action==='release'?source.id:null,JSON.stringify(lines),reason,now,actor);
 for(const line of lines){db.prepare('INSERT INTO inventory_order_lines VALUES (?,?,?,?,?,?,?,?,?,?)').run(eventId,id,version,line.position,o.customer_id,o.store_id,line.product_id,line.product_version,line.quantity,line.stock_event_id);insertStockEvent(db,{id:line.stock_event_id,product_id:line.product_id,product_version:line.product_version,store_id:o.store_id,action,quantity:line.quantity,order_event_id:eventId,order_position:line.position,reason,created_at:now,created_by:actor});}
 return orderInventory(db,id);
}
export function verifyInventory(db){
 const states=new Map();for(const e of db.prepare('SELECT * FROM inventory_events ORDER BY product_id,sequence').iterate()){
  const b=states.get(e.product_id)||{sequence:0,available:0,reserved:0,quarantined:0,created_at:''},p=db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? AND version=?').get(e.product_id,e.product_version),first=states.get(e.product_id)?.basis||p;
  if(![e.sequence,e.quantity,e.available,e.reserved,e.quarantined].every(Number.isSafeInteger)||e.sequence!==b.sequence+1||e.created_at<b.created_at||e.created_at<p.created_at||p.category==='service'||first.unit!==p.unit||first.category!==p.category)throw Error('库存连续版本、时间或单位核对失败');
  if(e.available!==b.available+(['receive','unquarantine','release'].includes(e.action)?e.quantity:-e.quantity)||e.reserved!==b.reserved+(e.action==='reserve'?e.quantity:e.action==='release'?-e.quantity:0)||e.quarantined!==b.quarantined+(e.action==='isolate'?e.quantity:e.action==='unquarantine'?-e.quantity:0))throw Error('库存数量流水核对失败');states.set(e.product_id,{...e,basis:first});
  if(e.order_event_id){const l=db.prepare('SELECT * FROM inventory_order_lines WHERE event_id=? AND position=?').get(e.order_event_id,e.order_position),h=db.prepare('SELECT * FROM inventory_order_events WHERE id=?').get(e.order_event_id);if(!l||l.stock_event_id!==e.id||l.product_id!==e.product_id||l.product_version!==e.product_version||l.quantity!==e.quantity||h.action!==e.action||h.reason!==e.reason||h.created_by!==e.created_by||h.created_at!==e.created_at)throw Error('库存与订单预留流水核对失败');}
 }
 for(const [id,s] of states){const p=catalog(db,id);if(p.unit!==s.basis.unit||p.category!==s.basis.category)throw Error('商品与库存计量单位核对失败');const active=db.prepare("SELECT COALESCE(sum(l.quantity),0) n FROM inventory_order_lines l JOIN inventory_order_events e ON e.id=l.event_id WHERE l.product_id=? AND e.action='reserve' AND e.revision=(SELECT max(revision) FROM inventory_order_events WHERE order_id=e.order_id)").get(id).n;if(s.reserved!==active)throw Error('库存与当前订单预留数量核对失败');}
 const orders=new Map();for(const e of db.prepare('SELECT * FROM inventory_order_events ORDER BY order_id,revision').iterate()){
  const b=orders.get(e.order_id),lines=reservationLines(db,e.id),expected=db.prepare("SELECT i.* FROM retail_order_items i JOIN retail_product_versions p ON p.product_id=i.product_id AND p.version=i.product_version WHERE i.order_id=? AND i.version=? AND p.category<>'service' ORDER BY i.position").all(e.order_id,e.order_version),manifest=lines.map(l=>({position:l.position,product_id:l.product_id,product_version:l.product_version,quantity:l.quantity,stock_event_id:l.stock_event_id})),v=db.prepare('SELECT status,created_at FROM retail_order_versions WHERE order_id=? AND version=?').get(e.order_id,e.order_version);
  if(e.revision!==(b?.revision||0)+1||e.created_at<(b?.created_at||v.created_at)||v.status!=='draft'||!lines.length||lines.length!==expected.length||lines.some((l,i)=>l.position!==expected[i].position||l.product_id!==expected[i].product_id||l.product_version!==expected[i].product_version||l.quantity!==expected[i].quantity)||e.manifest_json!==JSON.stringify(manifest)||e.action==='reserve'&&b?.action==='reserve'||e.action==='release'&&(!b||b.action!=='reserve'||e.source_id!==b.id||e.order_version!==b.order_version))throw Error('订单预留历史、固定明细或释放来源核对失败');
  for(const l of lines)if(!db.prepare('SELECT 1 FROM inventory_events WHERE id=? AND order_event_id=? AND order_position=?').get(l.stock_event_id,e.id,l.position))throw Error('订单库存流水缺失');if(db.prepare('SELECT 1 FROM retail_order_versions WHERE order_id=? AND version>? AND created_at<? LIMIT 1').get(e.order_id,e.order_version,e.created_at))throw Error('订单预留时的版本核对失败');orders.set(e.order_id,e);
 }
 for(const [id,last] of orders)if(last.action==='reserve'&&db.prepare('SELECT max(version) v FROM retail_order_versions WHERE order_id=?').get(id).v!==last.order_version)throw Error('订单预留未释放就修订');
}
export function createInventoryHandler(db,{need,customer,field,fail,body,mutation,audit}){
 const integer=(v,name,min,max)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail(422,'VALIDATION',name+'须为范围内整数');return v;},keys=(b,allowed)=>{if(Object.keys(b).some(k=>!allowed.includes(k)))fail(422,'VALIDATION','请仅提交本次库存操作字段');};
 const product=(user,id)=>{const p=catalog(db,id);if(!p||p.store_id!==user.store_id)fail(404,'NOT_FOUND','商品不存在或不在本店');if(p.category==='service')fail(422,'SERVICE_NOT_STOCKED','服务类商品不记实物库存');return p;};
 const order=(user,id)=>{const o=db.prepare('SELECT * FROM retail_orders WHERE id=? AND store_id=?').get(id,user.store_id);if(!o)fail(404,'NOT_FOUND','订单不存在或不在本店');customer(user,o.customer_id);return o;};
 function paging(url){const a=url.searchParams.get('limit')||'50',b=url.searchParams.get('offset')||'0';if(!/^\d{1,3}$/.test(a)||+a<1||+a>100||!/^\d{1,6}$/.test(b))fail(422,'VALIDATION','分页范围不正确');return {limit:+a,offset:+b};}
 return async(req,path,url,user,json)=>{
  const list=path==='/api/inventory/products',p=/^\/api\/inventory\/products\/([\w-]+)(\/events)?$/.exec(path),o=/^\/api\/retail\/orders\/([\w-]+)\/inventory(?:\/(reserve|release))?$/.exec(path);if(!list&&!p&&!o)return false;need(user,'inventory:read');
  if(list){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const q=field(url.searchParams.get('q'),'搜索',120)||'',state=url.searchParams.get('state')||'all',{limit,offset}=paging(url);if(!['all','unrecorded','available','reserved','quarantined'].includes(state))fail(422,'VALIDATION','库存筛选不正确');
   const where="p.store_id=:store AND v.version=(SELECT max(version) FROM retail_product_versions WHERE product_id=p.id) AND v.category<>'service' AND (:q='' OR instr(lower(p.sku||' '||v.name||' '||v.specification),lower(:q))>0) AND (:state='all' OR :state='unrecorded' AND e.id IS NULL OR :state='available' AND e.effective_available>0 OR :state='reserved' AND e.effective_reserved>0 OR :state='quarantined' AND e.quarantined>0)",params={store:user.store_id,q,state},from=' FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id LEFT JOIN inventory_balances e ON e.product_id=p.id WHERE '+where,counts=db.prepare("SELECT count(*) total,COALESCE(sum(e.id IS NULL),0) unrecorded,COALESCE(sum(e.effective_available>0),0) available,COALESCE(sum(e.effective_reserved>0),0) reserved,COALESCE(sum(e.quarantined>0),0) quarantined"+from).get(params),items=db.prepare('SELECT p.id'+from+' ORDER BY p.sku,p.id LIMIT :limit OFFSET :offset').all({...params,limit,offset}).map(x=>({...catalog(db,x.id),stock:stockBalance(db,x.id)}));json(200,{items,counts,total:counts.total,limit,offset,next_offset:offset+items.length<counts.total?offset+items.length:null});return true;
  }
  if(p){const current=product(user,p[1]);if(req.method==='GET'){const {limit,offset}=paging(url),total=db.prepare('SELECT count(*) n FROM inventory_events WHERE product_id=?').get(current.id).n,history=db.prepare('SELECT e.*,u.display_name author_name,o.order_id,o.order_version,r.order_number FROM inventory_events e JOIN users u ON u.id=e.created_by LEFT JOIN inventory_order_events o ON o.id=e.order_event_id LEFT JOIN retail_orders r ON r.id=o.order_id WHERE e.product_id=? ORDER BY e.sequence DESC LIMIT ? OFFSET ?').all(current.id,limit,offset);for(const e of history){const debit=db.prepare("SELECT COALESCE(sum(CASE WHEN source_mode='available' THEN quantity ELSE 0 END),0) a,COALESCE(sum(CASE WHEN source_mode='reserved' THEN quantity ELSE 0 END),0) r FROM inventory_outbounds WHERE product_id=? AND basis_sequence<?").get(current.id,e.sequence);e.effective_available=e.available-debit.a;e.effective_reserved=e.reserved-debit.r;}const holding=productReturnCustody(db,current.id),held=holding.hold_quantity;json(200,{product:current,return_hold_quantity:held,return_received_quantity:holding.received_quantity,returned_to_customer_quantity:holding.returned_quantity,stock:stockBalance(db,current.id),history,total,next_offset:offset+history.length<total?offset+history.length:null});return true;}
   if(req.method!=='POST'||!p[2])fail(405,'METHOD','不支持此请求');need(user,'inventory:manage');const b=await body(req);keys(b,['expected_sequence','expected_outbound_revision','expected_product_version','action','quantity','reason']);const input={expected_outbound_revision:integer(b.expected_outbound_revision??0,'出库版本',0,1000000000),expected_sequence:integer(b.expected_sequence,'库存版本',0,1000000000),expected_product_version:integer(b.expected_product_version,'商品版本',1,1000000000),action:b.action,quantity:integer(b.quantity,'数量',1,1000000),reason:field(b.reason,'库存操作依据',300,true)};if(!['receive','isolate','unquarantine'].includes(input.action))fail(422,'VALIDATION','请选择入库、隔离或解除隔离');
   json(201,mutation(req,user,'inventory.stock:'+current.id,input,()=>{const latest=product(user,current.id),before=stockBalance(db,current.id);if(latest.version!==input.expected_product_version||before.sequence!==input.expected_sequence||before.outbound_revision!==input.expected_outbound_revision)fail(409,'STOCK_CONFLICT','商品或库存已有变化，请读取最新数量');if(input.action==='isolate'&&input.quantity>before.available||input.action==='unquarantine'&&input.quantity>before.quarantined)fail(409,'INSUFFICIENT_STOCK','相应状态的库存数量不足');if(input.action==='receive'&&Object.values(db.prepare('SELECT available+reserved+quarantined n FROM inventory_events WHERE product_id=? ORDER BY sequence DESC LIMIT 1').get(latest.id)||{n:0})[0]+input.quantity>1000000000)fail(422,'STOCK_LIMIT','库存数量超出当前范围');const event=insertStockEvent(db,{product_id:latest.id,product_version:latest.version,store_id:user.store_id,action:input.action,quantity:input.quantity,reason:input.reason,created_by:user.id}),after=stockBalance(db,latest.id);audit(user,'inventory.'+input.action,latest.id,{event,stock:after},before);return {event,stock:after};}));return true;
  }
  const current=order(user,o[1]);if(req.method==='GET'&&!o[2]){json(200,{inventory:orderInventory(db,current.id)});return true;}if(req.method!=='POST'||!o[2])fail(405,'METHOD','不支持此请求');need(user,'inventory:reserve');const b=await body(req,65536),action=o[2];keys(b,['expected_order_version','expected_revision','reason',...(action==='reserve'?['stock_versions']:[])]);const input={expected_order_version:integer(b.expected_order_version,'订单版本',1,1000000000),expected_revision:integer(b.expected_revision,'预留记录版本',0,1000000000),reason:field(b.reason,'操作依据',300,true)};
  if(action==='reserve'){if(!Array.isArray(b.stock_versions)||!b.stock_versions.length||b.stock_versions.length>30)fail(422,'VALIDATION','请读取商品库存版本');input.stock_versions=b.stock_versions.map(x=>{if(!x||typeof x!=='object'||Array.isArray(x))fail(422,'VALIDATION','库存版本格式不正确');keys(x,['product_id','sequence','outbound_revision']);return {product_id:field(x.product_id,'商品',100,true),sequence:integer(x.sequence,'库存版本',0,1000000000),outbound_revision:integer(x.outbound_revision??0,'出库版本',0,1000000000)};}).sort((a,b)=>a.product_id.localeCompare(b.product_id));if(new Set(input.stock_versions.map(x=>x.product_id)).size!==input.stock_versions.length)fail(422,'VALIDATION','库存版本不能重复');}
  json(201,mutation(req,user,'inventory.order.'+action+':'+current.id,input,()=>{order(user,current.id);const before=orderInventory(db,current.id);if(before.order_version!==input.expected_order_version||before.revision!==input.expected_revision)fail(409,'RESERVATION_CONFLICT','订单或预留记录已有变化，请读取最新状态');if(before.dispatch_locked)fail(409,'ORDER_DISPATCHED','原单已有实际出库，不能新增整单预留或整单释放');if(before.status!=='draft')fail(409,'ORDER_CANCELLED','订单草稿已取消');if(action==='reserve'){if(before.active)fail(409,'ALREADY_RESERVED','订单已有预留，请先释放');if(!before.requirements.length)fail(422,'NO_STOCK_ITEMS','当前订单仅含服务项目，无需预留实物库存');if(JSON.stringify(input.stock_versions)!==JSON.stringify(before.stock_versions))fail(409,'STOCK_CONFLICT','库存已有变化，请读取最新数量');if(before.requirements.some(x=>!x.eligible))fail(409,'STOCK_PRODUCT_CHANGED','商品已停用或计量单位变化，请核对商品与原单');if(before.requirements.some(x=>x.shortage))fail(409,'INSUFFICIENT_STOCK','可用库存不足，请补充库存后再预留');}else {if(!before.active)fail(409,'NOT_RESERVED','当前订单没有有效预留');if(stockInProcessing(db,current.id))fail(409,'STOCK_IN_PROCESSING','原单商品已有加工备料记录，占用保留至后续出库或异常处理');}const after=insertReservation(db,current.id,action,input.reason,user.id);audit(user,'inventory.order.'+action,current.id,after,before);return {inventory:after};}));return true;
 };
}
