import {custodySequence as reservedSequence} from './inventory-reserved.mjs';
import {reservedBatchSequence} from './inventory-reserved-batch-ledger.mjs';
import {batchSequence,receiptBatchSold} from './inventory-batch-ledger.mjs';
import {custodySequence} from './inventory-custody.mjs';
import {extraReceiptBalance,extraReturnSequence} from './purchase-extra-return-ledger.mjs';
import {createHash} from 'node:crypto';
import {physicalStock} from './stock-ledger.mjs';
import {qualityProtectedStock} from './purchase-quality-ledger.mjs';
export const inventorySourceKinds=['receipt','quality','supplier_return','reservation','dispatch','stock'];
const reservedCount=(db,where,...args)=>db.prepare("SELECT 1 FROM sqlite_schema WHERE name='inventory_reserved_roots'").get()?db.prepare('SELECT count(*) n FROM inventory_reserved_roots WHERE '+where).get(...args).n:0;
const sourceRows=`
 SELECT 'receipt' kind,r.id,r.product_id,r.store_id,r.created_at FROM purchase_receipts r
 UNION ALL SELECT 'quality',c.id,r.product_id,c.store_id,c.created_at FROM purchase_quality_cases c JOIN purchase_receipts r ON r.id=c.receipt_id
 UNION ALL SELECT 'supplier_return',p.id,r.product_id,p.store_id,p.created_at FROM supplier_return_plans p JOIN purchase_receipts r ON r.id=p.receipt_id
 UNION ALL SELECT 'reservation',e.id,l.product_id,e.store_id,e.created_at FROM inventory_order_events e JOIN inventory_order_lines l ON l.event_id=e.id GROUP BY e.id,l.product_id
 UNION ALL SELECT 'dispatch',e.id,e.product_id,e.store_id,e.created_at FROM inventory_outbounds e
 UNION ALL SELECT 'stock',e.id,e.product_id,e.store_id,e.created_at FROM inventory_events e`;
const max=(db,table,where,params,column='sequence')=>db.prepare('SELECT coalesce(max('+column+'),0) n FROM '+table+' WHERE '+where).get(...params).n;
export function inventorySourceSnapshot(db,product){
 const stock=physicalStock(db,product.id),prefix={reserved_batches:reservedBatchSequence(db,product.store_id),reserved_custody:reservedSequence(db,product.store_id),batches:batchSequence(db,product.store_id),custody:custodySequence(db,product.store_id),product_version:product.version,stock:stock.sequence,outbound:stock.outbound_revision,returns:stock.return_revision,procurement:max(db,'procurement_journal','store_id=?',[product.store_id]),receiving:max(db,'purchase_receiving_journal','store_id=?',[product.store_id]),quality:max(db,'purchase_quality_journal','store_id=?',[product.store_id]),extra_returns:extraReturnSequence(db,product.store_id),supplier_returns:max(db,'supplier_return_journal','store_id=?',[product.store_id]),reservations:max(db,'inventory_order_events','store_id=?',[product.store_id],'rowid')};return {stock,prefix,source_token:createHash('sha256').update(JSON.stringify({product_id:product.id,store_id:product.store_id,...prefix})).digest('hex')};
}
function sourceDetail(db,x){
 const r={kind:x.kind,id:x.id,created_at:x.created_at};
 if(x.kind==='receipt'){const receipt=db.prepare('SELECT r.*,v.version metadata_version,v.lot_status,v.lot_code,v.expiry_status,v.expiry_date,v.location_status,v.location_note,v.source_note,v.source_reference,p.purchase_number,pv.supplier_version,s.name supplier_name,pc.status FROM purchase_receipts r JOIN purchase_receipt_current pc ON pc.receipt_id=r.id JOIN purchase_receipt_versions v ON v.id=pc.version_id JOIN purchase_requests p ON p.id=r.request_id JOIN purchase_versions pv ON pv.id=r.purchase_version_id JOIN supplier_versions s ON s.supplier_id=r.supplier_id AND s.version=pv.supplier_version WHERE r.id=?').get(x.id),returned=db.prepare('SELECT coalesce(sum(quantity),0) n FROM supplier_return_handoffs WHERE receipt_id=?').get(x.id).n,protectedQuantity=db.prepare('SELECT coalesce(sum(quantity),0) n FROM purchase_quality_holds WHERE receipt_id=?').get(x.id).n;return {...r,receipt,explicit_batch_sales_quantity:receiptBatchSold(db,x.id),reserved_custody_record_count:reservedCount(db,'receipt_id=?',x.id),unrecorded_prior_sales_batch_source:'unknown',custody_record_count:db.prepare('SELECT count(*) n FROM inventory_custody_roots WHERE receipt_id=?').get(x.id).n,extra_return_balance:extraReceiptBalance(db,x.id),returned_quantity:returned,protected_quantity:protectedQuantity,posted_quantity:receipt.status==='posted'?receipt.bound_quantity:0,unmatched_received_quantity:receipt.received_quantity-receipt.bound_quantity,current_batch_custody_quantity:null};}
 if(x.kind==='quality'){const q=db.prepare('SELECT c.*,e.status,e.revision,e.id current_event_id,v.version observation_version,v.receipt_version_id,v.observed_at,v.observation_note,v.source_reference,r.product_version,r.receipt_number FROM purchase_quality_cases c JOIN purchase_quality_current e ON e.case_id=c.id JOIN purchase_quality_versions v ON v.id=e.version_id JOIN purchase_receipts r ON r.id=c.receipt_id WHERE c.id=?').get(x.id),balance=db.prepare('SELECT * FROM supplier_return_case_balance WHERE case_id=?').get(x.id);return {...r,quality:q,balance,protected_quantity:q.status==='released'?0:balance.remaining_quantity};}
 if(x.kind==='supplier_return'){const p=db.prepare('SELECT p.*,e.status,e.revision,v.version arrangement_version,v.return_basis,v.destination_note,r.product_version,r.receipt_number FROM supplier_return_plans p JOIN supplier_return_current e ON e.plan_id=p.id JOIN supplier_return_versions v ON v.id=e.version_id JOIN purchase_receipts r ON r.id=p.receipt_id WHERE p.id=?').get(x.id),balance=db.prepare('SELECT * FROM supplier_return_plan_balance WHERE id=?').get(x.id);return {...r,plan:p,balance,not_yet_received_quantity:balance.handed_quantity-balance.received_quantity};}
 if(x.kind==='reservation'){const e=db.prepare('SELECT e.*,o.order_number FROM inventory_order_events e JOIN retail_orders o ON o.id=e.order_id WHERE e.id=?').get(x.id),lines=db.prepare('SELECT l.* FROM inventory_order_lines l WHERE l.event_id=? AND l.product_id=? ORDER BY position').all(x.id,x.product_id),current=db.prepare('SELECT * FROM inventory_order_events WHERE order_id=? ORDER BY revision DESC LIMIT 1').get(e.order_id);const shipped=db.prepare('SELECT coalesce(sum(quantity),0) n FROM inventory_outbounds WHERE reservation_id=? AND product_id=?').get(e.id,x.product_id).n;return {...r,event:e,lines,reserved_custody_record_count:reservedCount(db,'reservation_id=? AND receipt_id IN(SELECT id FROM purchase_receipts WHERE product_id=?)',e.id,x.product_id),current_reserved_batch_quantity:null,original_quantity:lines.reduce((n,l)=>n+l.quantity,0),actual_dispatched_quantity:shipped,active_quantity:current.id===e.id&&e.action==='reserve'?lines.reduce((n,l)=>n+l.quantity,0)-shipped:0};}
 if(x.kind==='dispatch'){const e=db.prepare('SELECT e.*,o.order_number,c.product_return_revision FROM inventory_outbounds e JOIN retail_orders o ON o.id=e.order_id JOIN inventory_dispatch_return_context c ON c.outbound_id=e.id WHERE e.id=?').get(x.id);return {...r,event:e};}
 const event=db.prepare('SELECT e.*,c.product_return_revision,q.quality_sequence FROM inventory_events e JOIN inventory_event_return_context c ON c.stock_event_id=e.id JOIN purchase_quality_stock_context q ON q.stock_event_id=e.id WHERE e.id=?').get(x.id),receipts=db.prepare('SELECT e.receipt_id,r.event_id,r.kind FROM purchase_inbound_refs r JOIN purchase_receipt_events e ON e.id=r.event_id WHERE r.stock_event_id=?').all(x.id),quality=db.prepare('SELECT e.case_id,r.event_id FROM purchase_quality_stock_refs r JOIN purchase_quality_events e ON e.id=r.event_id WHERE r.stock_event_id=?').all(x.id);return {...r,event,receipt_refs:receipts,quality_refs:quality};
}
export function inventorySources(db,product,{kind='all',limit=30,offset=0}={}){
 const snapshot=inventorySourceSnapshot(db,product),where=' WHERE product_id=? AND store_id=?',scope=[product.id,product.store_id],counts=Object.fromEntries(inventorySourceKinds.map(k=>[k,0]));for(const c of db.prepare('SELECT kind,count(*) n FROM ('+sourceRows+')'+where+' GROUP BY kind').all(...scope))counts[c.kind]=c.n;const filtered=where+(kind==='all'?'':' AND kind=?'),params=kind==='all'?scope:[...scope,kind],total=kind==='all'?Object.values(counts).reduce((a,b)=>a+b,0):counts[kind],rows=db.prepare('SELECT * FROM ('+sourceRows+')'+filtered+' ORDER BY created_at DESC,kind,id LIMIT ? OFFSET ?').all(...params,limit,offset),raw=db.prepare('SELECT available,reserved,quarantined FROM inventory_events WHERE product_id=? ORDER BY sequence DESC LIMIT 1').get(product.id)||{available:0,reserved:0,quarantined:0},sales=db.prepare("SELECT coalesce(sum(CASE WHEN source_mode='available' THEN quantity ELSE 0 END),0) available,coalesce(sum(CASE WHEN source_mode='reserved' THEN quantity ELSE 0 END),0) reserved FROM inventory_outbounds WHERE product_id=? AND store_id=?").get(...scope),supplier=db.prepare('SELECT coalesce(sum(quantity),0) quantity FROM supplier_return_handoffs WHERE product_id=? AND store_id=?').get(...scope).quantity;
 return {product,...snapshot,counts,total,next_offset:offset+limit<total?offset+limit:null,items:rows.map(x=>sourceDetail(db,x)),reconciliation:{raw_bookkeeping:raw,sales_outbound:sales,supplier_handed_quantity:supplier,physical:snapshot.stock,protected_quarantine:qualityProtectedStock(db,product.id),unprotected_quarantine:snapshot.stock.quarantined-qualityProtectedStock(db,product.id),batch_allocation_status:'not_implemented',unrecorded_prior_batch_history:'unknown'}};
}
export function createInventorySourcesHandler(db,{need,fail}){return async(req,path,url,u,json)=>{const m=/^\/api\/inventory\/products\/([\w-]+)\/sources$/.exec(path);if(!m)return false;need(u,'inventory:read');need(u,'receiving:read');if(req.method!=='GET')fail(405,'METHOD','来源总览只读取已保存的业务事实');const p=db.prepare('SELECT p.id,p.store_id,p.sku,v.* FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id WHERE p.id=? AND p.store_id=? ORDER BY version DESC LIMIT 1').get(m[1],u.store_id);if(!p)fail(404,'NOT_FOUND','商品来源不在本店');if(p.category==='service')fail(422,'SERVICE_NOT_STOCKED','服务不记实物库存来源');for(const k of url.searchParams.keys())if(!['kind','limit','offset','expected_source'].includes(k))fail(422,'VALIDATION','仅使用明确来源筛选和分页');const kind=url.searchParams.get('kind')||'all';if(kind!=='all'&&!inventorySourceKinds.includes(kind))fail(422,'VALIDATION','来源分类无效');const page=(k,d,min,max)=>{const v=url.searchParams.get(k)??String(d);if(!/^\d+$/.test(v)||+v<min||+v>max)fail(422,'VALIDATION','来源分页无效');return +v;},limit=page('limit',30,1,100),offset=page('offset',0,0,1e6),result=inventorySources(db,p,{kind,limit,offset});if(url.searchParams.has('expected_source')&&url.searchParams.get('expected_source')!==result.source_token||offset&&!url.searchParams.has('expected_source'))fail(409,'INVENTORY_SOURCE_STALE','采购、质量、退供或库存来源已有变化，请从首页重新核对');json(200,result);return true;};}
