import {reservedBatchSequence,reservedSalesPrefix,receiptReservedSold} from './inventory-reserved-batch-ledger.mjs';
import {batchSequence,receiptBatchSold} from './inventory-batch-ledger.mjs';
import {randomUUID,createHash} from 'node:crypto';
import {physicalStock} from './stock-ledger.mjs';
export const custodyTables=['inventory_custody_roots','inventory_custody_versions','inventory_custody_events','inventory_custody_stock_context','inventory_custody_dispatch_context','inventory_custody_receipt_context','inventory_custody_return_context','inventory_custody_quality_context'];
export const custodySequence=(db,store)=>db.prepare("SELECT 1 FROM sqlite_schema WHERE name='inventory_custody_events'").get()?db.prepare('SELECT coalesce(max(sequence),0) n FROM inventory_custody_events WHERE store_id=?').get(store).n:0;
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r)),atomic=(db,f)=>{db.exec('SAVEPOINT inventory_custody_apply');try{const r=f();db.exec('RELEASE inventory_custody_apply');return r;}catch(e){db.exec('ROLLBACK TO inventory_custody_apply;RELEASE inventory_custody_apply');throw e;}};
export function custodySource(db,id){const receipt=db.prepare('SELECT r.*,p.name,p.unit,p.specification FROM purchase_receipts r JOIN retail_product_versions p ON p.product_id=r.product_id AND p.version=r.product_version WHERE r.id=?').get(id),current=db.prepare('SELECT * FROM purchase_receipt_current WHERE receipt_id=?').get(id);if(!receipt||!current)return null;const stock=physicalStock(db,receipt.product_id),prefix={quality_sequence:db.prepare('SELECT coalesce(max(sequence),0) n FROM purchase_quality_journal WHERE store_id=?').get(receipt.store_id).n,receipt_version_id:current.version_id,receipt_sequence:db.prepare('SELECT coalesce(max(sequence),0) n FROM purchase_receiving_journal WHERE store_id=?').get(receipt.store_id).n,stock_sequence:stock.sequence,outbound_revision:stock.outbound_revision,product_return_revision:stock.return_revision},returned=db.prepare('SELECT coalesce(sum(quantity),0) n FROM supplier_return_handoffs WHERE receipt_id=?').get(id).n;return {receipt,current,stock,prefix,receipt_version:db.prepare('SELECT * FROM purchase_receipt_versions WHERE id=?').get(current.version_id),original_bound_quantity:receipt.bound_quantity,original_returned_quantity:returned,original_attributed_sales_quantity:receiptBatchSold(db,id),original_bound_not_returned_capacity:receipt.bound_quantity-returned-receiptBatchSold(db,id),original_protected_quantity:db.prepare('SELECT coalesce(sum(quantity),0) n FROM purchase_quality_holds WHERE receipt_id=?').get(id).n,current_batch_custody_quantity:null,allocation_status:'not_implemented',source_token:createHash('sha256').update(JSON.stringify({id,store:receipt.store_id,batch_sequence:batchSequence(db,receipt.store_id),reserved_batch_sequence:reservedBatchSequence(db,receipt.store_id),...prefix})).digest('hex')};}
export function custodyRecord(db,id,{version=null,limit=30,offset=0}={}){const root=db.prepare('SELECT * FROM inventory_custody_roots WHERE id=?').get(id),current=db.prepare('SELECT * FROM inventory_custody_current WHERE root_id=?').get(id);if(!root||!current)return null;const latest=db.prepare('SELECT * FROM inventory_custody_versions WHERE id=?').get(current.version_id),v=version?db.prepare('SELECT * FROM inventory_custody_versions WHERE root_id=? AND version=?').get(id,version):latest;if(!v)return null;const source=custodySource(db,root.receipt_id),same=w=>Object.entries(source.prefix).filter(([k])=>k!=='receipt_sequence').every(([k,n])=>w[k]===n)&&receiptReservedSold(db,root.receipt_id,reservedSalesPrefix(db,'inventory_custody_reserved_sales_context','version_id',w.id))===receiptReservedSold(db,root.receipt_id);return {...root,...v,id:root.id,root_created_at:root.created_at,root_created_by:root.created_by,version_id:v.id,current_version:latest.version,revision:current.revision,status:current.status,current,source,source_current:same(latest),display_source_current:same(v),current_batch_custody_quantity:null,original_receipt_version:db.prepare('SELECT * FROM purchase_receipt_versions WHERE id=?').get(v.receipt_version_id),history:db.prepare('SELECT e.*,v.version FROM inventory_custody_events e JOIN inventory_custody_versions v ON v.id=e.version_id WHERE e.root_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:current.revision,next_offset:offset+limit<current.revision?offset+limit:null};}
export function custodyEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM inventory_custody_roots WHERE id=?').get(id),v=db.prepare('SELECT * FROM inventory_custody_versions WHERE root_id=? ORDER BY version DESC LIMIT 1').get(id);put(db,'inventory_custody_events',{id:randomUUID(),root_id:id,version_id:v.id,store_id:r.store_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM inventory_custody_events WHERE root_id=?').get(id).n,sequence:custodySequence(db,r.store_id)+1,action:i.action,status:i.action==='observe'?'recorded':'withdrawn',reason:i.reason,next_step:i.next_step,created_at:at,created_by:actor});return custodyRecord(db,id);}
export function custodyObservation(db,id,i,actor,at=new Date().toISOString()){return atomic(db,()=>{const r=db.prepare('SELECT * FROM inventory_custody_roots WHERE id=?').get(id),s=custodySource(db,r.receipt_id),v={id:randomUUID(),root_id:id,store_id:r.store_id,version:db.prepare('SELECT coalesce(max(version),0)+1 n FROM inventory_custody_versions WHERE root_id=?').get(id).n,base_sequence:custodySequence(db,r.store_id),...s.prefix};for(const k of ['observed_at','quantity','bucket','identity_source','location_label','location_source','source_reference','note','reason'])v[k]=i[k];put(db,'inventory_custody_versions',{...v,created_at:at,created_by:actor});return custodyEvent(db,id,{...i,action:'observe'},actor,at);});}
export function createCustody(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){return atomic(db,()=>{const serial=db.prepare('SELECT coalesce(max(serial),0)+1 n FROM inventory_custody_roots WHERE store_id=?').get(store).n;put(db,'inventory_custody_roots',{id,receipt_id:i.receipt_id,store_id:store,serial,custody_number:'CUS-'+at.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),created_at:at,created_by:actor});return custodyObservation(db,id,i,actor,at);});}
