import {createHash} from 'node:crypto';
import {validDate} from './staff-records.mjs';
export const moneyKinds=['receive','void','refund'],moneyStates=['receive_valid','receive_voided','void_reference','refund_executed'];
const sql=`WITH money AS (
 SELECT 'payment:'||e.id entry_key,e.id,e.action kind,e.order_id,e.order_version,e.customer_id,e.store_id,e.amount_cents,e.currency,e.method,e.reference,e.received_at occurred_at,e.created_at recorded_at,e.created_by author_id,CASE WHEN e.action='void' THEN 'void_reference' WHEN v.id IS NOT NULL THEN 'receive_voided' ELSE 'receive_valid' END state,CASE WHEN e.action='receive' AND v.id IS NULL THEN e.amount_cents ELSE 0 END signed_recorded_cents,CASE WHEN e.action='receive' THEN e.id ELSE e.source_id END receipt_id,NULL refund_id,CASE WHEN e.action='receive' THEN v.id ELSE e.id END void_id,e.revision source_revision,CASE WHEN e.action='void' THEN 'original_receipt_reference' ELSE 'actual_collection' END actual_date_kind,e.basis_total_cents fixed_order_total_cents FROM payment_events e LEFT JOIN payment_events v ON v.source_id=e.id
 UNION ALL
 SELECT 'refund:'||e.id,e.id,'refund',e.order_id,e.order_version,e.customer_id,e.store_id,e.amount_cents,e.currency,e.method,e.reference,e.refunded_at,e.created_at,e.created_by,'refund_executed',-e.amount_cents,e.receipt_id,e.root_id,NULL,e.revision,'actual_refund',v.subtotal_cents FROM refund_events e JOIN retail_order_versions v ON v.order_id=e.order_id AND v.version=e.order_version WHERE e.action='execute'
 ),scoped AS (SELECT m.*,o.order_number,v.title order_title,c.name customer_name,u.display_name author_name,'not_recorded' external_verification FROM money m JOIN retail_orders o ON o.id=m.order_id AND o.store_id=m.store_id JOIN retail_order_versions v ON v.order_id=m.order_id AND v.version=m.order_version JOIN customers c ON c.id=m.customer_id AND c.store_id=m.store_id JOIN users u ON u.id=m.author_id WHERE m.store_id=:store) `;
const where=" WHERE (:kind='all' OR kind=:kind) AND (:state='all' OR state=:state) AND (:method='all' OR method=:method) AND (instr(lower(order_number||' '||order_title||' '||customer_name||' '||coalesce(reference,'')||' '||id),lower(:q))>0) AND (:from='' OR substr(CASE WHEN :basis='actual' THEN occurred_at ELSE recorded_at END,1,10)>=:from) AND (:to='' OR substr(CASE WHEN :basis='actual' THEN occurred_at ELSE recorded_at END,1,10)<=:to)";
export function moneySnapshot(db,store){const prefix=Object.fromEntries(['payment_events','refund_events'].map(t=>[t,db.prepare('SELECT coalesce(max(rowid),0) n FROM '+t+' WHERE store_id=?').get(store).n])),customers=db.prepare('SELECT DISTINCT c.id,c.name FROM customers c JOIN payment_events e ON e.customer_id=c.id WHERE e.store_id=? ORDER BY c.id').all(store),actors=db.prepare("SELECT DISTINCT u.id,u.display_name FROM users u JOIN (SELECT created_by FROM payment_events WHERE store_id=? UNION SELECT created_by FROM refund_events WHERE store_id=?) a ON a.created_by=u.id ORDER BY u.id").all(store,store);return {source_token:createHash('sha256').update(JSON.stringify({store,prefix,customers,actors})).digest('hex'),currency:'CNY'};}
export function moneyReview(db,store,{q='',kind='all',state='all',method='all',basis='actual',from='',to='',limit=30,offset=0}={}){const filters={q,kind,state,method,basis,from,to},args={store,...filters},snap=moneySnapshot(db,store),source_token=createHash('sha256').update(JSON.stringify({source:snap.source_token,filters})).digest('hex'),counts=Object.fromEntries(moneyStates.map(k=>[k,0]));let received=0n,refunded=0n,total=0,excluded=0n;const excludedReceipts=new Set();for(const x of db.prepare(sql+'SELECT kind,state,amount_cents,signed_recorded_cents,receipt_id FROM scoped'+where).iterate(args)){total++;counts[x.state]++;if(x.state==='receive_valid')received+=BigInt(x.amount_cents);if(x.kind==='refund')refunded+=BigInt(x.amount_cents);if(['receive_voided','void_reference'].includes(x.state)&&!excludedReceipts.has(x.receipt_id)){excluded+=BigInt(x.amount_cents);excludedReceipts.add(x.receipt_id);}}return {filters,source_token,snapshot_token:snap.source_token,currency:'CNY',total,counts,summary:{valid_collection_cents:String(received),executed_refund_cents:String(refunded),matched_recorded_difference_cents:String(received-refunded),excluded_false_receipt_cents:String(excluded)},items:db.prepare(sql+'SELECT * FROM scoped'+where+' ORDER BY recorded_at DESC,entry_key DESC LIMIT :limit OFFSET :offset').all({...args,limit,offset}),next_offset:offset+limit<total?offset+limit:null,external_verification:'not_recorded',accounting_status:'not_defined'};}
export function moneyEntry(db,store,kind,id){return db.prepare(sql+'SELECT * FROM scoped WHERE kind=:kind AND id=:id').get({store,kind,id})||null;}
export function createMoneyReviewHandler(db,{need,fail}){return async(req,path,url,u,json)=>{const list=path==='/api/money-review',m=/^\/api\/money-review\/(receive|void|refund)\/([\w-]+)$/.exec(path);if(!list&&!m)return false;need(u,'payments:read');need(u,'organization:manage');if(req.method!=='GET')fail(405,'METHOD','只核对已保存实际业务事实，新增/作废/退款沿原流程办理');const allowed=list?['q','kind','state','method','basis','from','to','limit','offset','expected_source']:['expected_source'];for(const k of url.searchParams.keys())if(!allowed.includes(k)||url.searchParams.getAll(k).length!==1)fail(422,'VALIDATION','仅明确筛选与原来源分页');if(m){const snap=moneySnapshot(db,u.store_id),entry=moneyEntry(db,u.store_id,m[1],m[2]);if(!entry)fail(404,'NOT_FOUND','原收退款记录不在本店');if(url.searchParams.has('expected_source')&&url.searchParams.get('expected_source')!==snap.source_token)fail(409,'MONEY_REVIEW_CHANGED','原业务事实或当前名称已有变化，请重新核对');json(200,{entry,...snap,external_verification:'not_recorded',accounting_status:'not_defined'});return true;}const p={};for(const[k,values]of [['kind',['all',...moneyKinds]],['state',['all',...moneyStates]],['method',['all','cash','card','transfer','other']],['basis',['actual','recorded']]]){p[k]=url.searchParams.get(k)??(k==='basis'?'actual':'all');if(!values.includes(p[k]))fail(422,'VALIDATION','筛选无效');}p.q=url.searchParams.get('q')||'';if(p.q.length>120)fail(422,'VALIDATION','搜索最多120字符');for(const k of ['from','to']){p[k]=url.searchParams.get(k)||'';if(p[k]&&!validDate(p[k]))fail(422,'VALIDATION','日期须真实 UTC 日期');}if(p.from&&p.to&&p.from>p.to)fail(422,'VALIDATION','开始日期不能晚于结束日期');for(const[k,d,min,max]of [['limit',30,1,100],['offset',0,0,1e6]]){const v=url.searchParams.get(k)??String(d);if(!/^\d+$/.test(v)||+v<min||+v>max)fail(422,'VALIDATION','分页无效');p[k]=+v;}const z=moneyReview(db,u.store_id,p);if(p.offset&&!url.searchParams.has('expected_source')||url.searchParams.has('expected_source')&&url.searchParams.get('expected_source')!==z.source_token)fail(409,'MONEY_REVIEW_CHANGED','筛选或原业务事实已有变化，请从第一页重新核对');json(200,z);return true;};}
