import {specialtyOrderContext,guardSpecialtyOrder,specialtyExecutionRef} from './specialty-order-ledger.mjs';
import {receiptRefunds,orderRefundBalance} from './refund-ledger.mjs';
import {randomUUID} from 'node:crypto';
export const paymentTables=['payment_events'];
const activeSQL="SELECT e.* FROM payment_events e WHERE e.order_id=? AND e.action='receive' AND NOT EXISTS(SELECT 1 FROM payment_events v WHERE v.source_id=e.id)";
export function hasReceipts(db,id){return Boolean(db.prepare(activeSQL+' LIMIT 1').get(id));}
const currentOrder=(db,id)=>db.prepare('SELECT o.*,v.version,v.title,v.status,v.subtotal_cents FROM retail_orders o JOIN retail_order_versions v ON v.order_id=o.id WHERE o.id=? ORDER BY v.version DESC LIMIT 1').get(id);
const projection=`SELECT e.*,o.order_number,c.name customer_name,u.display_name author_name,s.revision source_revision,v.id void_id,v.revision void_revision FROM payment_events e JOIN retail_orders o ON o.id=e.order_id JOIN customers c ON c.id=e.customer_id JOIN users u ON u.id=e.created_by LEFT JOIN payment_events s ON s.id=e.source_id LEFT JOIN payment_events v ON v.source_id=e.id`;
export function orderPayments(db,id,{limit=50,offset=0}={}){const o=currentOrder(db,id);if(!o)return null;const active=db.prepare(activeSQL).all(id),amount=active.reduce((sum,e)=>sum+e.amount_cents,0),total=db.prepare('SELECT count(*) n FROM payment_events WHERE order_id=?').get(id).n,history=db.prepare(projection+' WHERE e.order_id=? ORDER BY e.revision DESC LIMIT ? OFFSET ?').all(id,limit,offset);const refunds=orderRefundBalance(db,id);for(const e of history)Object.assign(e,receiptRefunds(db,e.action==='receive'?e.id:e.source_id));return {...refunds,retained_cents:amount-refunds.refunded_cents,order_id:id,order_number:o.order_number,customer_id:o.customer_id,title:o.title,order_version:o.version,status:o.status,basis_total_cents:o.subtotal_cents,currency:'CNY',revision:total,valid_receipts:active.length,recorded_cents:amount,comparison_cents:o.subtotal_cents-amount,locked:active.length>0,history,total,next_offset:offset+history.length<total?offset+history.length:null};}
export function insertPayment(db,id,action,input,actor,now=new Date().toISOString()){
 const o=currentOrder(db,id),revision=db.prepare('SELECT COALESCE(max(revision),0)+1 n FROM payment_events WHERE order_id=?').get(id).n,source=action==='void'?db.prepare('SELECT * FROM payment_events WHERE id=?').get(input.source_id):null,event={id:randomUUID(),order_id:id,order_version:o.version,customer_id:o.customer_id,store_id:o.store_id,revision,action,source_id:source?.id||null,amount_cents:source?.amount_cents??input.amount_cents,basis_total_cents:o.subtotal_cents,currency:'CNY',method:source?.method??input.method,reference:source?source.reference:input.reference??null,received_at:source?.received_at??input.received_at,reason:input.reason,created_at:now,created_by:actor};
 db.prepare('INSERT INTO payment_events VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...Object.values(event));return event;
}
const canonicalTime=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
export function verifyPayments(db){
 const states=new Map(),events=new Map(),voided=new Set();for(const e of db.prepare('SELECT * FROM payment_events ORDER BY order_id,revision').iterate()){
  const prior=states.get(e.order_id),v=db.prepare('SELECT * FROM retail_order_versions WHERE order_id=? AND version=?').get(e.order_id,e.order_version);
  if(!v||v.status!=='draft'||v.subtotal_cents!==e.basis_total_cents||e.currency!=='CNY'||e.revision!==(prior?.revision||0)+1||!Number.isSafeInteger(e.amount_cents)||e.amount_cents<1||e.amount_cents>1e12||!canonicalTime(e.created_at)||!canonicalTime(e.received_at)||e.received_at>e.created_at||e.received_at<'2000-01-01T00:00:00.000Z'||e.created_at<(prior?.created_at||v.created_at)||e.created_at<v.created_at)throw Error('收款原单金额、连续记录或时间核对失败');
  if(e.action==='void'){const s=events.get(e.source_id);if(!s||s.action!=='receive'||s.order_id!==e.order_id||voided.has(s.id)||['order_version','customer_id','store_id','amount_cents','basis_total_cents','currency','method','reference','received_at'].some(k=>e[k]!==s[k]))throw Error('收款误录作废来源核对失败');voided.add(s.id);}else if(e.action!=='receive'||e.source_id!==null)throw Error('收款记录类型核对失败');
  if(db.prepare('SELECT 1 FROM retail_order_versions WHERE order_id=? AND version>? AND created_at<?').get(e.order_id,e.order_version,e.created_at))throw Error('收款时订单版本核对失败');events.set(e.id,e);states.set(e.order_id,e);
 }
 if(db.prepare("SELECT 1 FROM payment_events e WHERE e.action='receive' AND e.reference IS NOT NULL AND NOT EXISTS(SELECT 1 FROM payment_events v WHERE v.source_id=e.id) GROUP BY e.store_id,e.method,e.reference HAVING count(*)>1").get())throw Error('收款有效外部编号重复');
 for(const [id] of states){const p=orderPayments(db,id),active=db.prepare(activeSQL).all(id);if(!Number.isSafeInteger(p.recorded_cents)||p.recorded_cents>1e14||active.some(e=>e.order_version!==p.order_version)||active.length&&p.status!=='draft')throw Error('收款与当前订单保护核对失败');}
}
export function createPaymentsHandler(db,{need,customer,field,fail,body,mutation,audit}){
 const integer=(v,label,min=0,max=1e9)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail(422,'VALIDATION',label+'须为范围内整数');return v;},keys=(b,allowed)=>{if(Object.keys(b).some(k=>!allowed.includes(k)))fail(422,'VALIDATION','请仅提交本次收款登记字段');};
 const localOrder=(user,id)=>{const o=currentOrder(db,id);if(!o||o.store_id!==user.store_id)fail(404,'NOT_FOUND','订单不存在或不在本店');customer(user,o.customer_id);return o;};
 const paging=url=>{const a=url.searchParams.get('limit')||'50',b=url.searchParams.get('offset')||'0';if(!/^\d{1,3}$/.test(a)||+a<1||+a>100||!/^\d{1,6}$/.test(b))fail(422,'VALIDATION','分页范围不正确');return {limit:+a,offset:+b};};
 return async(req,path,url,user,json)=>{
  const list=path==='/api/payments',match=/^\/api\/retail\/orders\/([\w-]+)\/payments(?:\/(receive|void))?$/.exec(path);if(!list&&!match)return false;need(user,'payments:read');
  if(list){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const {limit,offset}=paging(url),q=field(url.searchParams.get('q'),'搜索',120)||'',action=url.searchParams.get('action')||'all';if(!['all','receive','void'].includes(action))fail(422,'VALIDATION','收款记录筛选不正确');const where=" WHERE e.store_id=:store AND (:action='all' OR e.action=:action) AND (:q='' OR instr(lower(o.order_number||' '||c.name||' '||COALESCE(e.reference,'')),lower(:q))>0)",params={store:user.store_id,action,q},total=db.prepare('SELECT count(*) n FROM ('+projection+where+')').get(params).n,items=db.prepare(projection+where+' ORDER BY e.created_at DESC,e.order_id,e.revision DESC LIMIT :limit OFFSET :offset').all({...params,limit,offset});for(const e of items)Object.assign(e,receiptRefunds(db,e.action==='receive'?e.id:e.source_id));json(200,{items,total,limit,offset,next_offset:offset+items.length<total?offset+items.length:null});return true;}
  const o=localOrder(user,match[1]);if(req.method==='GET'&&!match[2]){json(200,{payments:orderPayments(db,o.id,paging(url))});return true;}if(req.method!=='POST'||!match[2])fail(405,'METHOD','不支持此请求');const action=match[2];need(user,action==='void'?'payments:void':'payments:write');const b=await body(req);keys(b,['expected_order_version','expected_revision','reason',...(action==='receive'?['amount_cents','method','reference','received_at']:['source_id'])]);const input={expected_order_version:integer(b.expected_order_version,'订单版本',1),expected_revision:integer(b.expected_revision,'收款记录版本'),reason:field(b.reason,'登记依据',300,true)};
  if(action==='receive'){input.amount_cents=integer(b.amount_cents,'本次登记金额（分）',1,1e12);input.method=b.method;if(!['cash','card','transfer','other'].includes(input.method))fail(422,'VALIDATION','请选择手工记录的收款方式');input.reference=field(b.reference,'外部记录编号',120);input.received_at=b.received_at;if(!canonicalTime(input.received_at)||input.received_at<'2000-01-01T00:00:00.000Z'||input.received_at>new Date().toISOString())fail(422,'VALIDATION','实际收款时间须为有效的过去时间');}else input.source_id=field(b.source_id,'误录原记录',100,true);
  const specialtyGuard=()=>{if(action==='receive')guardSpecialtyOrder(db,o.id,fail);};specialtyGuard();json(201,mutation(req,user,'payments.'+action+':'+o.id,input,()=>{specialtyGuard();const latest=localOrder(user,o.id),before=orderPayments(db,o.id);if(latest.version!==input.expected_order_version||before.revision!==input.expected_revision)fail(409,'PAYMENT_CONFLICT','订单或收款记录已有变化，请读取最新记录');if(latest.status!=='draft')fail(409,'ORDER_CANCELLED','订单草稿已取消，不能登记收款');if(action==='void'){const s=db.prepare("SELECT * FROM payment_events WHERE id=? AND order_id=? AND action='receive'").get(input.source_id,o.id);if(!s)fail(404,'NOT_FOUND','误录原记录不存在');if(receiptRefunds(db,s.id).refund_locked)fail(409,'RECEIPT_HAS_REFUNDS','原实收已有退款申请或实际退款，不能作为误录作废');if(db.prepare('SELECT 1 FROM payment_events WHERE source_id=?').get(s.id))fail(409,'RECEIPT_VOIDED','原记录已经追加误录作废');}else {if(input.reference&&db.prepare("SELECT 1 FROM payment_events e WHERE store_id=? AND method=? AND reference=? AND action='receive' AND NOT EXISTS(SELECT 1 FROM payment_events v WHERE v.source_id=e.id)").get(user.store_id,input.method,input.reference))fail(409,'DUPLICATE_REFERENCE','本店该方式和外部编号已有有效收款记录，请核对原记录');if(before.recorded_cents+input.amount_cents>1e14)fail(422,'AMOUNT_LIMIT','记录金额超出当前范围');}
   const event=insertPayment(db,o.id,action,input,user.id),after=orderPayments(db,o.id);audit(user,'payments.'+action,o.id,{event,payments:after},before);return {event,payments:after};}));return true;
 };
}
