import {parameterContext,guardParameters,executionParameterRef} from './parameter-ledger.mjs';
import {randomUUID} from 'node:crypto';
export const processingTables=['processing_jobs','processing_events'];
const plans=['supply_mode','processing_mode','supplier_name','assignee_id','due_date','instructions'];
const latest=(db,id)=>db.prepare('SELECT * FROM processing_events WHERE job_id=? ORDER BY revision DESC LIMIT 1').get(id);
const order=(db,id)=>db.prepare('SELECT o.*,v.version,v.status,v.title,v.subtotal_cents FROM retail_orders o JOIN retail_order_versions v ON v.order_id=o.id WHERE o.id=? ORDER BY v.version DESC LIMIT 1').get(id);
const originalLines=(db,id,version)=>db.prepare("SELECT i.*,p.sku,v.name,v.unit,v.category,v.specification FROM retail_order_items i JOIN retail_products p ON p.id=i.product_id JOIN retail_product_versions v ON v.product_id=i.product_id AND v.version=i.product_version WHERE i.order_id=? AND i.version=? AND v.category<>'service' ORDER BY i.position").all(id,version);
export const canonicalLine=l=>({position:l.position,product_id:l.product_id,product_version:l.product_version,quantity:l.quantity,supply_mode:l.supply_mode,processing_mode:l.processing_mode,supplier_name:l.supplier_name,assignee_id:l.assignee_id,due_date:l.due_date,instructions:l.instructions,received:l.received,started:l.started,completed:l.completed,delay_reason:l.delay_reason});
export function activeProcessing(db,id){return db.prepare("SELECT j.* FROM processing_jobs j WHERE j.order_id=? AND (SELECT action FROM processing_events WHERE job_id=j.id ORDER BY revision DESC LIMIT 1) IS NOT 'cancel' ORDER BY j.serial DESC LIMIT 1").get(id)||null;}
export function stockInProcessing(db,id){if(!db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name='processing_jobs'").get())return false;return Boolean(db.prepare("SELECT 1 FROM processing_jobs j JOIN processing_events e ON e.job_id=j.id AND e.revision=(SELECT max(revision) FROM processing_events WHERE job_id=j.id),json_each(e.snapshot_json) l WHERE j.order_id=? AND e.action<>'cancel' AND json_extract(l.value,'$.supply_mode')='stock' AND json_extract(l.value,'$.received')>0 LIMIT 1").get(id));}
function reservation(db,id,version){const e=db.prepare("SELECT id,order_version,action FROM inventory_order_events WHERE order_id=? ORDER BY revision DESC LIMIT 1").get(id);return e?.order_version===version&&e.action==='reserve';}
export function processingState(snapshot,action,today=new Date().toISOString().slice(0,10)){
 const cancelled=action==='cancel',finished=snapshot.filter(l=>l.completed===l.quantity).length,state=cancelled?'cancelled':finished===snapshot.length?'awaiting_qc':snapshot.some(l=>l.started>0)?'running':snapshot.some(l=>l.received>0)?'partial':'planned';
 return {state,lines_total:snapshot.length,lines_completed:finished,delayed:!cancelled&&snapshot.some(l=>l.completed<l.quantity&&l.delay_reason!==null),overdue:!cancelled&&snapshot.some(l=>l.completed<l.quantity&&l.due_date!==null&&l.due_date<today)};
}
function enrich(db,job,snapshot){const originals=originalLines(db,job.order_id,job.order_version);return snapshot.map(l=>{const p=originals.find(x=>x.position===l.position),u=db.prepare('SELECT display_name,role,active,store_id FROM users WHERE id=?').get(l.assignee_id);return {...l,sku:p.sku,name:p.name,unit:p.unit,category:p.category,specification:p.specification,assignee_name:u?.display_name||'原责任人',assignee_available:Boolean(u?.active&&u.store_id===job.store_id&&['manager','reception','professional'].includes(u.role)),ready_to_prepare:l.supply_mode==='purchase'||reservation(db,job.order_id,job.order_version)};});}
export function processingRecord(db,id,revision=null,{limit=50,offset=0}={}){
 const j=db.prepare('SELECT j.*,o.order_number,v.title,c.name customer_name,o.cycle_id,o.cycle_version,o.visit_id FROM processing_jobs j JOIN retail_orders o ON o.id=j.order_id JOIN retail_order_versions v ON v.order_id=j.order_id AND v.version=j.order_version JOIN customers c ON c.id=j.customer_id WHERE j.id=?').get(id);if(!j)return null;const current=latest(db,id),e=revision?db.prepare('SELECT * FROM processing_events WHERE job_id=? AND revision=?').get(id,revision):current;if(!e)return null;
 const snapshot=JSON.parse(e.snapshot_json),history=db.prepare('SELECT e.id,e.revision,e.action,e.position,e.quantity,e.reason,e.created_at,e.created_by,u.display_name author_name FROM processing_events e JOIN users u ON u.id=e.created_by WHERE e.job_id=? ORDER BY e.revision DESC LIMIT ? OFFSET ?').all(id,limit,offset).map(e=>({...e,parameter_reference:executionParameterRef(db,e.id)})),author=db.prepare('SELECT display_name FROM users WHERE id=?').get(e.created_by)?.display_name;
 return {...j,parameter_context:parameterContext(db,id),selected_parameter_reference:executionParameterRef(db,e.id),job_number:j.order_number+'-J'+String(j.serial).padStart(2,'0'),revision:e.revision,current_revision:current.revision,action:e.action,reason:e.reason,event_created_at:e.created_at,event_created_by:e.created_by,author_name:author,...processingState(snapshot,e.action),lines:enrich(db,j,snapshot),stock_prepared:stockInProcessing(db,j.order_id),history,total:current.revision,next_offset:offset+history.length<current.revision?offset+history.length:null};
}
export function orderProcessing(db,id){const o=order(db,id);if(!o)return null;const active=activeProcessing(db,id),jobs=db.prepare('SELECT id FROM processing_jobs WHERE order_id=? ORDER BY serial DESC LIMIT 50').all(id).map(j=>{const value=processingRecord(db,j.id);return {id:value.id,job_number:value.job_number,order_version:value.order_version,revision:value.revision,state:value.state,delayed:value.delayed,overdue:value.overdue,lines_total:value.lines_total,lines_completed:value.lines_completed};}),total=db.prepare('SELECT count(*) n FROM processing_jobs WHERE order_id=?').get(id).n;return {order_id:id,order_number:o.order_number,order_version:o.version,customer_id:o.customer_id,title:o.title,status:o.status,job_count:total,active:active?processingRecord(db,active.id):null,lines:originalLines(db,id,o.version),jobs,jobs_truncated:total>50};}
export function insertProcessingJob(db,id,input,actor,now=new Date().toISOString(),jobId=randomUUID()){
 const o=order(db,id),serial=db.prepare('SELECT COALESCE(max(serial),0)+1 n FROM processing_jobs WHERE order_id=?').get(id).n,snapshot=originalLines(db,id,o.version).map(l=>canonicalLine({...l,...input.lines.find(x=>x.position===l.position),received:0,started:0,completed:0,delay_reason:null}));
 db.prepare('INSERT INTO processing_jobs VALUES (?,?,?,?,?,?,?,?)').run(jobId,id,o.version,o.customer_id,o.store_id,serial,now,actor);db.prepare('INSERT INTO processing_events VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),jobId,1,'create',null,null,JSON.stringify(snapshot),input.reason,now,actor);return processingRecord(db,jobId);
}
export function processingTransition(snapshot,action,input){const next=snapshot.map(canonicalLine),line=next.find(l=>l.position===input.position);if(action==='plan')Object.assign(line,input.plan);else if(['receive','start','complete'].includes(action))line[{receive:'received',start:'started',complete:'completed'}[action]]+=input.quantity;else if(action==='delay'){line.delay_reason=input.reason;line.due_date=input.due_date;}else if(action==='clear_delay')line.delay_reason=null;return next.map(canonicalLine);}
export function insertProcessingEvent(db,id,input,actor,now=new Date().toISOString()){
 const e=latest(db,id),snapshot=processingTransition(JSON.parse(e.snapshot_json),input.action,input);db.prepare('INSERT INTO processing_events VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),id,e.revision+1,input.action,input.position??null,input.quantity??null,JSON.stringify(snapshot),input.reason,now,actor);return processingRecord(db,id);
}
const dateOK=v=>v===null||typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v>='2000-01-01'&&v<='2099-12-31';
function transitionError(before,next,action,input){
 if(processingState(before,'update').state==='awaiting_qc')return '加工备货记录已完成，下一步进入质检';const l=before.find(x=>x.position===input.position),n=next.find(x=>x.position===input.position);
 if(action==='cancel')return before.some(x=>x.received>0)?'已有到货或备料记录，不能取消为未执行工单':null;if(!l)return '原单分项不存在';if(l.completed===l.quantity)return '本项加工备货记录已完成';
 if(action==='plan'){if(l.received>0&&['supply_mode','supplier_name'].some(k=>l[k]!==n[k])||l.started>0&&['processing_mode','instructions'].some(k=>l[k]!==n[k]))return '已执行的供货或加工说明保持原版本，请走后续变更流程';if(JSON.stringify(l)===JSON.stringify(n))return '安排没有变化';}
 if(action==='clear_delay'&&l.delay_reason===null)return '本项没有待处理延期说明';if(next.some(x=>x.received>x.quantity||x.started>x.received||x.completed>x.started))return '本次数量超过原单待到货、待开工或待完成数量';return null;
}
export function verifyProcessing(db){
 const perOrder=new Map();for(const j of db.prepare('SELECT * FROM processing_jobs ORDER BY order_id,serial').iterate()){
  const prior=perOrder.get(j.order_id),events=db.prepare('SELECT * FROM processing_events WHERE job_id=? ORDER BY revision').all(j.id),originals=originalLines(db,j.order_id,j.order_version),v=db.prepare('SELECT * FROM retail_order_versions WHERE order_id=? AND version=?').get(j.order_id,j.order_version);
  if(j.serial!==(prior?.serial||0)+1||!events.length||!originals.length||v?.status!=='draft'||j.created_at<v.created_at||prior&&(latest(db,prior.id).action!=='cancel'||j.created_at<latest(db,prior.id).created_at))throw Error('加工工单原单、连续编号或重复活动核对失败');if(db.prepare('SELECT 1 FROM retail_order_versions WHERE order_id=? AND version>? AND created_at<?').get(j.order_id,j.order_version,j.created_at))throw Error('加工创建时原单版本核对失败');let previous=null;
  for(const e of events){const s=JSON.parse(e.snapshot_json);if(!Array.isArray(s)||s.length!==originals.length||e.revision!==(previous?.revision||0)+1||e.created_at<(previous?.created_at||j.created_at)||e.snapshot_json!==JSON.stringify(s.map(canonicalLine))||s.some((l,i)=>['position','product_id','product_version','quantity'].some(k=>l[k]!==originals[i][k])||![l.received,l.started,l.completed].every(Number.isSafeInteger)||l.completed<0||l.completed>l.started||l.started>l.received||l.received>l.quantity||!dateOK(l.due_date)||!['stock','purchase'].includes(l.supply_mode)||!['internal','external','none'].includes(l.processing_mode)||typeof l.instructions!=='string'||l.instructions.length>1000||typeof l.assignee_id!=='string'||!db.prepare('SELECT 1 FROM users WHERE id=?').get(l.assignee_id)||!(l.supplier_name===null||typeof l.supplier_name==='string'&&l.supplier_name.length<=120)||(l.supply_mode==='purchase'||l.processing_mode==='external')&&!l.supplier_name?.trim()||!(l.delay_reason===null||typeof l.delay_reason==='string'&&l.delay_reason.trim()&&l.delay_reason.length<=300)))throw Error('加工分项、数量、连续记录或快照核对失败');
   if(!previous){if(e.action!=='create'||e.position!==null||e.quantity!==null||e.created_at!==j.created_at||e.created_by!==j.created_by||s.some(l=>l.received||l.started||l.completed||l.delay_reason!==null))throw Error('加工初始安排核对失败');}else {if(previous.action==='cancel'||e.action==='create')throw Error('加工终态历史核对失败');const p=JSON.parse(previous.snapshot_json),line=s.find(l=>l.position===e.position),input={position:e.position,quantity:e.quantity,reason:e.reason,plan:line?Object.fromEntries(plans.map(k=>[k,line[k]])):null,due_date:line?.due_date};if(transitionError(p,s,e.action,input)||JSON.stringify(processingTransition(p,e.action,input))!==e.snapshot_json)throw Error('加工数量、计划锁或历史转换核对失败');}previous=e;
  }
  if(previous.action!=='cancel'){const current=order(db,j.order_id);if(current.version!==j.order_version||current.status!=='draft')throw Error('活动加工原单保护核对失败');if(JSON.parse(previous.snapshot_json).some(l=>l.supply_mode==='stock'&&l.received>0)&&!reservation(db,j.order_id,j.order_version))throw Error('加工备料与原库存占用核对失败');}perOrder.set(j.order_id,j);
 }
}
export function createProcessingHandler(db,{need,customer,field,fail,body,mutation,audit}){
 const integer=(v,name,min=0,max=1e9)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail(422,'VALIDATION',name+'须为范围内整数');return v;},keys=(b,allowed)=>{if(!b||typeof b!=='object'||Array.isArray(b)||Object.keys(b).some(k=>!allowed.includes(k)))fail(422,'VALIDATION','请仅提交本次加工操作字段');};
 const localOrder=(user,id)=>{const o=order(db,id);if(!o||o.store_id!==user.store_id)fail(404,'NOT_FOUND','订单不存在或不在本店');customer(user,o.customer_id);return o;},localJob=(user,id)=>{const j=db.prepare('SELECT * FROM processing_jobs WHERE id=? AND store_id=?').get(id,user.store_id);if(!j)fail(404,'NOT_FOUND','加工工单不存在或不在本店');customer(user,j.customer_id);return j;};
 const paging=url=>{const a=url.searchParams.get('limit')||'50',b=url.searchParams.get('offset')||'0';if(!/^\d{1,3}$/.test(a)||+a<1||+a>100||!/^\d{1,6}$/.test(b))fail(422,'VALIDATION','分页范围不正确');return {limit:+a,offset:+b};};
 const due=v=>{const value=field(v,'预计日期',10);if(!dateOK(value))fail(422,'VALIDATION','预计日期须为有效年月日，未约定可留空');return value;};
 const planInput=b=>{keys(b,plans);const p={supply_mode:b.supply_mode,processing_mode:b.processing_mode,supplier_name:field(b.supplier_name,'供应/加工方',120),assignee_id:field(b.assignee_id,'本项责任人',100,true),due_date:due(b.due_date),instructions:field(b.instructions,'加工安排说明',1000)||''};if(!['stock','purchase'].includes(p.supply_mode)||!['internal','external','none'].includes(p.processing_mode))fail(422,'VALIDATION','供货或加工安排不正确');if((p.supply_mode==='purchase'||p.processing_mode==='external')&&!p.supplier_name)fail(422,'VALIDATION','订货或外加工须记录供应/加工方');return p;};
 const readyAssignee=(user,p)=>{if(!db.prepare("SELECT 1 FROM users WHERE id=? AND store_id=? AND active=1 AND role IN('manager','reception','professional')").get(p.assignee_id,user.store_id))fail(409,'ASSIGNEE_UNAVAILABLE','本项责任人已停用、改岗或不在本店，请重新选择');};
 return async(req,path,url,user,json)=>{
  const list=path==='/api/processing/jobs',assignees=path==='/api/processing/assignees',o=/^\/api\/retail\/orders\/([\w-]+)\/processing$/.exec(path),j=/^\/api\/processing\/jobs\/([\w-]+)(\/events)?$/.exec(path);if(!list&&!assignees&&!o&&!j)return false;need(user,'processing:read');
  if(assignees){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const items=db.prepare("SELECT u.id,u.display_name,u.role,COALESCE(s.must_change_password,0) must_change_password FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.store_id=? AND u.active=1 AND u.role IN('manager','reception','professional') ORDER BY u.display_name,u.id LIMIT 500").all(user.store_id);json(200,{items,truncated:db.prepare("SELECT count(*) n FROM users WHERE store_id=? AND active=1 AND role IN('manager','reception','professional')").get(user.store_id).n>500});return true;}
  if(list){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const {limit,offset}=paging(url),q=field(url.searchParams.get('q'),'搜索',120)||'',state=url.searchParams.get('state')||'all',mine=url.searchParams.get('mine')||'all';if(!['all','planned','partial','running','awaiting_qc','cancelled','delayed','overdue'].includes(state)||!['all','assigned'].includes(mine))fail(422,'VALIDATION','加工筛选不正确');
   const cte=`WITH queue AS (SELECT j.id,j.store_id,j.created_at,j.serial,j.order_id,o.order_number,v.title,c.name customer_name,e.revision,e.snapshot_json,CASE WHEN e.action='cancel' THEN 'cancelled' WHEN NOT EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.completed')<json_extract(l.value,'$.quantity')) THEN 'awaiting_qc' WHEN EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.started')>0) THEN 'running' WHEN EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.received')>0) THEN 'partial' ELSE 'planned' END state,e.action<>'cancel' AND EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.delay_reason') IS NOT NULL AND json_extract(l.value,'$.completed')<json_extract(l.value,'$.quantity')) delayed,e.action<>'cancel' AND EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.due_date')<:today AND json_extract(l.value,'$.completed')<json_extract(l.value,'$.quantity')) overdue,e.action<>'cancel' AND EXISTS(SELECT 1 FROM json_each(e.snapshot_json) l WHERE json_extract(l.value,'$.assignee_id')=:user AND json_extract(l.value,'$.completed')<json_extract(l.value,'$.quantity')) mine FROM processing_jobs j JOIN processing_events e ON e.job_id=j.id AND e.revision=(SELECT max(revision) FROM processing_events WHERE job_id=j.id) JOIN retail_orders o ON o.id=j.order_id JOIN retail_order_versions v ON v.order_id=j.order_id AND v.version=j.order_version JOIN customers c ON c.id=j.customer_id)`,where=" FROM queue WHERE store_id=:store AND (:q='' OR instr(lower(order_number||' '||title||' '||customer_name||' '||order_number||'-J'||printf('%02d',serial)),lower(:q))>0) AND (:mine='all' OR mine=1) AND (:state='all' OR state=:state OR :state='delayed' AND delayed=1 OR :state='overdue' AND overdue=1)",params={store:user.store_id,user:user.id,q,state,mine,today:new Date().toISOString().slice(0,10)},counts=db.prepare(cte+" SELECT count(*) total,COALESCE(sum(state='planned'),0) planned,COALESCE(sum(state='partial'),0) partial,COALESCE(sum(state='running'),0) running,COALESCE(sum(state='awaiting_qc'),0) awaiting_qc,COALESCE(sum(state='cancelled'),0) cancelled,COALESCE(sum(delayed),0) delayed,COALESCE(sum(overdue),0) overdue"+where).get(params),items=db.prepare(cte+' SELECT id'+where+' ORDER BY created_at DESC,order_id,serial DESC LIMIT :limit OFFSET :offset').all({...params,limit,offset}).map(x=>{const value=processingRecord(db,x.id);const {history,...safe}=value;return safe;});json(200,{items,counts,total:counts.total,limit,offset,next_offset:offset+items.length<counts.total?offset+items.length:null});return true;
  }
  if(o){const current=localOrder(user,o[1]);if(req.method==='GET'){json(200,{processing:orderProcessing(db,current.id)});return true;}if(req.method!=='POST')fail(405,'METHOD','不支持此请求');need(user,'processing:manage');const b=await body(req,65536);keys(b,['expected_order_version','expected_job_count','lines','reason']);const input={expected_order_version:integer(b.expected_order_version,'订单版本',1),expected_job_count:integer(b.expected_job_count,'已建工单数量'),reason:field(b.reason,'建立依据',300,true),lines:[]};if(!Array.isArray(b.lines)||!b.lines.length||b.lines.length>30)fail(422,'VALIDATION','请安排原单全部实物行');input.lines=b.lines.map(l=>{keys(l,['position',...plans]);return {position:integer(l.position,'原单行',1,30),...planInput(Object.fromEntries(plans.map(k=>[k,l[k]])))};}).sort((a,b)=>a.position-b.position);if(new Set(input.lines.map(l=>l.position)).size!==input.lines.length)fail(422,'VALIDATION','原单行不能重复');
   json(201,mutation(req,user,'processing.create:'+current.id,input,()=>{const before=orderProcessing(db,current.id);localOrder(user,current.id);if(before.order_version!==input.expected_order_version||before.job_count!==input.expected_job_count)fail(409,'PROCESSING_CONFLICT','订单或工单记录已有变化，请读取最新安排');if(before.status!=='draft')fail(409,'ORDER_CANCELLED','原订单已取消');if(before.active)fail(409,'ACTIVE_PROCESSING','原单已有活动加工工单');if(!before.lines.length)fail(422,'NO_PROCESSING_ITEMS','仅服务订单没有实物加工备货项');if(JSON.stringify(before.lines.map(l=>l.position))!==JSON.stringify(input.lines.map(l=>l.position)))fail(422,'ORIGINAL_LINES_REQUIRED','须逐行安排原单全部实物明细；数量和商品版本由原单固定');for(const p of input.lines)readyAssignee(user,p);const job=insertProcessingJob(db,current.id,input,user.id);audit(user,'processing.create',job.id,job,before);return {job};}));return true;
  }
  const current=localJob(user,j[1]);if(req.method==='GET'&&!j[2]){const raw=url.searchParams.get('revision');if(raw!==null&&(!/^\d{1,9}$/.test(raw)||+raw<1))fail(422,'VALIDATION','加工历史版本不正确');const job=processingRecord(db,current.id,raw===null?null:+raw,paging(url));if(!job)fail(404,'NOT_FOUND','加工历史版本不存在');json(200,{job});return true;}if(req.method!=='POST'||!j[2])fail(405,'METHOD','不支持此请求');const b=await body(req),action=b.action;if(!['plan','receive','start','complete','delay','clear_delay','cancel'].includes(action))fail(422,'VALIDATION','加工操作不正确');need(user,['plan','receive'].includes(action)?'processing:manage':action==='cancel'?'processing:cancel':'processing:execute');keys(b,['expected_revision','action','reason','expected_parameter_sequence','expected_parameter_review_revision',...(action==='cancel'?[]:['position']),...(['receive','start','complete'].includes(action)?['quantity']:action==='plan'?['plan']:action==='delay'?['due_date']:[])]);const input={expected_parameter_sequence:integer(b.expected_parameter_sequence??0,'参数流水'),expected_parameter_review_revision:integer(b.expected_parameter_review_revision??0,'变更核对版本'),expected_revision:integer(b.expected_revision,'加工记录版本',1),action,reason:field(b.reason,'操作依据',300,true)};if(action!=='cancel')input.position=integer(b.position,'原单行',1,30);if(['receive','start','complete'].includes(action))input.quantity=integer(b.quantity,'本次数量',1,999);if(action==='plan')input.plan=planInput(b.plan);if(action==='delay')input.due_date=due(b.due_date);
  json(201,mutation(req,user,'processing.'+action+':'+current.id,input,()=>{localJob(user,current.id);if(['start','complete'].includes(action))guardParameters(db,current.id,input,fail);const before=processingRecord(db,current.id),e=latest(db,current.id),snapshot=JSON.parse(e.snapshot_json),line=snapshot.find(l=>l.position===input.position);if(before.revision!==input.expected_revision)fail(409,'PROCESSING_CONFLICT','加工记录已有变化，请读取最新进度');if(before.state==='cancelled')fail(409,'PROCESSING_CANCELLED','加工计划已取消，原历史保留');if(action!=='cancel'&&!line)fail(404,'NOT_FOUND','原单分项不存在');if(['start','complete','delay','clear_delay'].includes(action)&&user.role!=='manager'&&!(user.role==='reception'&&['delay','clear_delay'].includes(action))&&line.assignee_id!==user.id)fail(403,'NOT_ASSIGNEE','仅当前本项责任人或负责人可登记执行进度');if(action==='plan')readyAssignee(user,input.plan);const next=processingTransition(snapshot,action,input),error=transitionError(snapshot,next,action,input);if(error)fail(409,'PROCESSING_STATE',error);if(action==='receive'&&line.supply_mode==='stock'&&!reservation(db,current.order_id,current.order_version))fail(409,'PROCESSING_STOCK_REQUIRED','库存备料须先在原单预留全部商品；到货记录独立于库存入库');const job=insertProcessingEvent(db,current.id,input,user.id);audit(user,'processing.'+action,current.id,job,before);return {job};}));return true;
 };
}
