import {randomUUID} from 'node:crypto';
export const procurementTables=['suppliers','supplier_versions','purchase_requests','purchase_versions','purchase_events'];
export const supplierFields={name:120,scope_note:2000,source_note:2000,source_reference:1000};
export const supplierOptionalFields={contact_label:120,contact_method:200,address_note:1000,settlement_note:2000};
export const procurementSequence=(db,s)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM procurement_journal WHERE store_id=?').get(s).n;
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));
const atomic=(db,fn)=>{db.exec('SAVEPOINT procurement_apply');try{const r=fn();db.exec('RELEASE procurement_apply');return r;}catch(e){db.exec('ROLLBACK TO procurement_apply;RELEASE procurement_apply');throw e;}};
export function canonicalPurchaseItems(raw){if(!Array.isArray(raw)||!raw.length||raw.length>50)return null;const items=[];for(const [index,i]of raw.entries()){if(!i||typeof i!=='object'||Array.isArray(i)||Object.keys(i).some(k=>!['position','product_id','product_version','quantity','unit_price_cents','note'].includes(k))||typeof i.product_id!=='string'||!i.product_id.length||i.product_id.length>100||!Number.isSafeInteger(i.product_version)||i.product_version<1||i.product_version>1e9||!Number.isSafeInteger(i.quantity)||i.quantity<1||i.quantity>999||!Number.isSafeInteger(i.unit_price_cents)||i.unit_price_cents<0||i.unit_price_cents>1e9||i.position!==undefined&&i.position!==index+1||i.note!==null&&(typeof i.note!=='string'||!i.note.trim().length||i.note.length>1000))return null;items.push({position:index+1,product_id:i.product_id,product_version:i.product_version,quantity:i.quantity,unit_price_cents:i.unit_price_cents,note:i.note});}return items;}
export function supplierRecord(db,id,{version=null,limit=30,offset=0}={}){const root=db.prepare('SELECT * FROM suppliers WHERE id=?').get(id);if(!root)return null;const n=db.prepare('SELECT max(version) n FROM supplier_versions WHERE supplier_id=?').get(id).n,v=db.prepare('SELECT * FROM supplier_versions WHERE supplier_id=? AND version=?').get(id,version||n);if(!v)return null;return {...root,...v,id:root.id,current_version:n,history:db.prepare('SELECT * FROM supplier_versions WHERE supplier_id=? ORDER BY version DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:n,next_offset:offset+limit<n?offset+limit:null};}
export function supplierVersion(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM suppliers WHERE id=?').get(id),v={supplier_id:id,store_id:r.store_id,version:db.prepare('SELECT coalesce(max(version),0)+1 n FROM supplier_versions WHERE supplier_id=?').get(id).n,sequence:procurementSequence(db,r.store_id)+1};for(const k of [...Object.keys(supplierFields),...Object.keys(supplierOptionalFields),'status','reason'])v[k]=i[k];put(db,'supplier_versions',{...v,created_at:at,created_by:actor});return supplierRecord(db,id);}
export function createSupplier(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){return atomic(db,()=>{put(db,'suppliers',{id,store_id:store,code:i.code,created_at:at,created_by:actor});return supplierVersion(db,id,i,actor,at);});}
export function purchaseRecord(db,id,{version=null,limit=30,offset=0}={}){const r=db.prepare('SELECT * FROM purchase_requests WHERE id=?').get(id),e=db.prepare('SELECT * FROM purchase_current WHERE request_id=?').get(id);if(!r||!e)return null;const current=db.prepare('SELECT * FROM purchase_versions WHERE id=?').get(e.version_id),v=version?db.prepare('SELECT * FROM purchase_versions WHERE request_id=? AND version=?').get(id,version):current;if(!v)return null;const items=JSON.parse(v.items_json).map(i=>({...i,...db.prepare('SELECT name,category,unit,specification FROM retail_product_versions WHERE product_id=? AND version=?').get(i.product_id,i.product_version)}));return {...r,...v,id:r.id,version_id:v.id,current_version:current.version,revision:e.revision,status:e.status,current:e,items,supplier:supplierRecord(db,v.supplier_id,{version:v.supplier_version,limit:1}),context:db.prepare('SELECT * FROM purchase_context WHERE id=?').get(id),history:db.prepare('SELECT e.*,v.version FROM purchase_events e JOIN purchase_versions v ON v.id=e.version_id WHERE e.request_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function purchaseEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM purchase_requests WHERE id=?').get(id),v=db.prepare('SELECT * FROM purchase_versions WHERE request_id=? ORDER BY version DESC LIMIT 1').get(id);put(db,'purchase_events',{id:randomUUID(),request_id:id,version_id:v.id,store_id:r.store_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM purchase_events WHERE request_id=?').get(id).n,sequence:procurementSequence(db,r.store_id)+1,action:i.action,status:{create:'draft',revise:'draft',submit:'submitted',approve:'approved',reject:'rejected',reopen:'draft',order:'ordered',cancel:'cancelled'}[i.action],product_basis_json:db.prepare('SELECT basis_json FROM purchase_product_basis WHERE version_id=?').get(v.id).basis_json,decision_basis:i.decision_basis,ordered_at:i.action==='order'?i.ordered_at:null,order_reference:i.action==='order'?i.order_reference:null,note:i.note,reason:i.reason,next_step:i.next_step,created_at:at,created_by:actor});return purchaseRecord(db,id);}
export function purchaseVersion(db,id,i,actor,at=new Date().toISOString()){return atomic(db,()=>{const r=db.prepare('SELECT * FROM purchase_requests WHERE id=?').get(id),n=db.prepare('SELECT coalesce(max(version),0)+1 n FROM purchase_versions WHERE request_id=?').get(id).n,items=canonicalPurchaseItems(i.items);if(!items)throw Error('采购实际明细不完整');const v={id:randomUUID(),request_id:id,store_id:r.store_id,version:n,base_sequence:procurementSequence(db,r.store_id),supplier_id:i.supplier_id,supplier_version:i.supplier_version};for(const k of ['title','purpose_note','source_note','source_reference','expected_date','reason'])v[k]=i[k];put(db,'purchase_versions',{...v,items_json:JSON.stringify(items),total_cents:items.reduce((n,i)=>n+i.quantity*i.unit_price_cents,0),currency:'CNY',created_at:at,created_by:actor});return purchaseEvent(db,id,{...i,action:n===1?'create':'revise',decision_basis:i.source_note},actor,at);});}
export function createPurchase(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){return atomic(db,()=>{const serial=db.prepare('SELECT coalesce(max(serial),0)+1 n FROM purchase_requests WHERE store_id=?').get(store).n;put(db,'purchase_requests',{id,store_id:store,serial,purchase_number:'PO-'+at.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),created_at:at,created_by:actor});return purchaseVersion(db,id,i,actor,at);});}
export function purchaseSourceProblem(db,store,i,{current=true,at=null,productBasis=null,supplierSequence=null}={}){const s=db.prepare('SELECT * FROM supplier_versions WHERE supplier_id=? AND version=? AND store_id=?').get(i.supplier_id,i.supplier_version,store);if(!s||s.status!=='active'||current&&s.version!==db.prepare('SELECT max(version) n FROM supplier_versions WHERE supplier_id=?').get(i.supplier_id).n||at&&s.created_at>at||supplierSequence!==null&&s.version!==db.prepare('SELECT max(version) n FROM supplier_versions WHERE supplier_id=? AND sequence<=?').get(i.supplier_id,supplierSequence).n)return '请明确核对此供应商的有效原资料版本';for(const item of i.items){const p=db.prepare('SELECT rowid source_rowid,* FROM retail_product_versions WHERE product_id=? AND version=? AND store_id=?').get(item.product_id,item.product_version,store),basis=productBasis?.find(x=>x.product_id===item.product_id);if(!p||p.category==='service'||p.status!=='active'||current&&p.version!==db.prepare('SELECT max(version) n FROM retail_product_versions WHERE product_id=?').get(item.product_id).n||at&&p.created_at>at||productBasis&&(!basis||basis.version!==item.product_version||basis.rowid!==p.source_rowid))return '采购须明确本店当前有效实物商品、原规格和单位，不能静默替换商品来源';}return null;}
