import {randomUUID} from 'node:crypto';
import {physicalStock} from './stock-ledger.mjs';
import {insertStockEvent} from './inventory.mjs';
export const purchaseQualityTables=['purchase_quality_cases','purchase_quality_versions','purchase_quality_events','purchase_quality_stock_refs','purchase_quality_stock_context'];
export const purchaseQualitySequence=(db,s)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM purchase_quality_journal WHERE store_id=?').get(s).n;
export const protectedQuarantine=(db,p)=>db.prepare('SELECT coalesce(sum(quantity),0) n FROM purchase_quality_holds WHERE product_id=?').get(p).n;
const receiptSequence=(db,s)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM purchase_receiving_journal WHERE store_id=?').get(s).n;
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));
const atomic=(db,f)=>{db.exec('SAVEPOINT purchase_quality_apply');try{const x=f();db.exec('RELEASE purchase_quality_apply');return x;}catch(e){db.exec('ROLLBACK TO purchase_quality_apply;RELEASE purchase_quality_apply');throw e;}};
export function purchaseQualityRecord(db,id,{version=null,limit=30,offset=0}={}){const c=db.prepare('SELECT * FROM purchase_quality_cases WHERE id=?').get(id),e=db.prepare('SELECT * FROM purchase_quality_current WHERE case_id=?').get(id);if(!c||!e)return null;const latest=db.prepare('SELECT * FROM purchase_quality_versions WHERE id=?').get(e.version_id),v=version?db.prepare('SELECT * FROM purchase_quality_versions WHERE case_id=? AND version=?').get(id,version):latest;if(!v)return null;const receipt=db.prepare('SELECT r.*,p.name,p.unit FROM purchase_receipts r JOIN retail_product_versions p ON p.product_id=r.product_id AND p.version=r.product_version WHERE r.id=?').get(c.receipt_id),source=db.prepare('SELECT * FROM purchase_receipt_versions WHERE id=?').get(v.receipt_version_id),receiptCurrent=db.prepare('SELECT * FROM purchase_receipt_versions WHERE receipt_id=? ORDER BY version DESC LIMIT 1').get(c.receipt_id);return {...c,...v,id:c.id,version_id:v.id,current_version:latest.version,revision:e.revision,status:e.status,current:e,receipt,source,receipt_current:receiptCurrent,stock:physicalStock(db,receipt.product_id),protected_quantity:protectedQuarantine(db,receipt.product_id),source_current:latest.receipt_version_id===receiptCurrent.id,history:db.prepare('SELECT e.*,v.version,r.version receipt_version FROM purchase_quality_events e JOIN purchase_quality_versions v ON v.id=e.version_id JOIN purchase_receipt_versions r ON r.id=v.receipt_version_id WHERE e.case_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),refs:db.prepare('SELECT e.action,e.version_id,e.revision,r.stock_event_id FROM purchase_quality_events e JOIN purchase_quality_stock_refs r ON r.event_id=e.id WHERE e.case_id=? ORDER BY revision').all(id),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function purchaseQualityEvent(db,id,i,actor,at=new Date().toISOString()){return atomic(db,()=>{const c=purchaseQualityRecord(db,id),q=i.action.startsWith('quality_'),release=i.action==='release',e={id:randomUUID(),case_id:id,version_id:c.version_id,store_id:c.store_id,revision:c.revision+1,sequence:purchaseQualitySequence(db,c.store_id)+1,receipt_sequence:receiptSequence(db,c.store_id),action:i.action,status:{quality_pass:'passed',quality_fail:'failed',release:'released'}[i.action],checked_at:q?i.checked_at:null,requirement_source:q?i.requirement_source:null,require_lot:q?Number(i.require_lot):null,require_expiry:q?Number(i.require_expiry):null,require_location:q?Number(i.require_location):null,checks_json:q?JSON.stringify(i.checks):null,quality_event_id:release?c.current.id:null,stock_sequence:release?c.stock.sequence:null,outbound_revision:release?c.stock.outbound_revision:null,note:i.note,reason:i.reason,next_step:i.next_step,created_at:at,created_by:actor};put(db,'purchase_quality_events',e);if(release){const s=insertStockEvent(db,{product_id:c.receipt.product_id,product_version:c.receipt.product_version,store_id:c.store_id,action:'unquarantine',quantity:c.quantity,reason:i.reason,created_at:at,created_by:actor});put(db,'purchase_quality_stock_refs',{event_id:e.id,stock_event_id:s.id});}return purchaseQualityRecord(db,id);});}
export function purchaseQualityVersion(db,id,i,actor,at=new Date().toISOString()){return atomic(db,()=>{const c=db.prepare('SELECT * FROM purchase_quality_cases WHERE id=?').get(id),old=db.prepare('SELECT * FROM purchase_quality_current WHERE case_id=?').get(id),n=db.prepare('SELECT coalesce(max(version),0)+1 n FROM purchase_quality_versions WHERE case_id=?').get(id).n,v={id:randomUUID(),case_id:id,store_id:c.store_id,version:n,base_sequence:purchaseQualitySequence(db,c.store_id),receipt_version_id:i.receipt_version_id,receipt_sequence:receiptSequence(db,c.store_id),observed_at:i.observed_at,observation_note:i.observation_note,source_reference:i.source_reference,reason:i.reason,created_at:at,created_by:actor};put(db,'purchase_quality_versions',v);const e={id:randomUUID(),case_id:id,version_id:v.id,store_id:c.store_id,revision:(old?.revision||0)+1,sequence:v.base_sequence+1,receipt_sequence:receiptSequence(db,c.store_id),action:n===1?'create':'revise',status:'pending',checked_at:null,requirement_source:null,require_lot:null,require_expiry:null,require_location:null,checks_json:null,quality_event_id:null,stock_sequence:null,outbound_revision:null,note:i.note,reason:i.reason,next_step:i.next_step,created_at:at,created_by:actor};put(db,'purchase_quality_events',e);if(n===1&&c.source_bucket==='available'){const r=db.prepare('SELECT * FROM purchase_receipts WHERE id=?').get(c.receipt_id),s=insertStockEvent(db,{product_id:r.product_id,product_version:r.product_version,store_id:c.store_id,action:'isolate',quantity:c.quantity,reason:i.reason,created_at:at,created_by:actor});put(db,'purchase_quality_stock_refs',{event_id:e.id,stock_event_id:s.id});}return purchaseQualityRecord(db,id);});}
export function createPurchaseQuality(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){return atomic(db,()=>{const r=db.prepare('SELECT * FROM purchase_receipts WHERE id=?').get(i.receipt_id),inbound=db.prepare("SELECT * FROM purchase_receipt_events WHERE receipt_id=? AND action='inbound'").get(i.receipt_id);if(!r||r.store_id!==store||!inbound)throw Error('purchase quality original posted source absent');const stock=physicalStock(db,r.product_id);put(db,'purchase_quality_cases',{id,receipt_id:r.id,inbound_event_id:inbound.id,store_id:store,quantity:i.quantity,source_bucket:i.source_bucket,stock_sequence:stock.sequence,outbound_revision:stock.outbound_revision,custody_confirmed_at:i.custody_confirmed_at,custody_source:i.custody_source,created_at:at,created_by:actor});return purchaseQualityVersion(db,id,i,actor,at);});}
