import {randomUUID} from 'node:crypto';
import {canonicalTime} from './training.mjs';
export {canonicalTime};
export const referralTables=['external_records','external_record_versions','external_record_events','referral_cases','referral_events','referral_contact_links'];
export const referralSequence=(db,store)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM referral_journal WHERE store_id=?').get(store).n;
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));
const serial=(db,t,store)=>db.prepare('SELECT coalesce(max(serial),0)+1 n FROM '+t+' WHERE store_id=?').get(store).n;
const number=(prefix,at,n)=>prefix+at.slice(0,10).replaceAll('-','')+'-'+String(n).padStart(5,'0');
export function externalRecord(db,id,{limit=30,offset=0,version=null}={}){const r=db.prepare('SELECT * FROM external_records WHERE id=?').get(id),e=db.prepare('SELECT * FROM external_record_current WHERE record_id=?').get(id);if(!r||!e)return null;const v=db.prepare('SELECT * FROM external_record_versions WHERE record_id=? AND version=?').get(id,version??e.version);if(!v)return null;const state=db.prepare('SELECT * FROM external_record_events WHERE record_id=? AND version=? ORDER BY revision DESC LIMIT 1').get(id,v.version),confirmation=db.prepare("SELECT * FROM external_record_events WHERE record_id=? AND version=? AND action IN('confirm','reject') ORDER BY revision DESC LIMIT 1").get(id,v.version);return {...r,...v,...e,id,root_created_at:r.created_at,root_created_by:r.created_by,current_version:e.version,version:v.version,version_status:state?.status??'pending',confirmation:confirmation||null,attachment_ids:JSON.parse(v.attachment_ids_json),document_ids:JSON.parse(v.document_ids_json),customer_name:db.prepare('SELECT name FROM customers WHERE id=?').get(r.customer_id).name,owner_name:db.prepare('SELECT display_name FROM users WHERE id=?').get(e.owner_id).display_name,history:db.prepare('SELECT * FROM external_record_events WHERE record_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function createExternalRecord(db,store,customer,i,actor,at=new Date().toISOString(),id=randomUUID()){const n=serial(db,'external_records',store);put(db,'external_records',{id,store_id:store,customer_id:customer,serial:n,record_number:number('ER-',at,n),created_at:at,created_by:actor});return externalRecordVersion(db,id,i,actor,at);}
export function externalRecordVersion(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM external_records WHERE id=?').get(id),version=db.prepare('SELECT coalesce(max(version),0)+1 n FROM external_record_versions WHERE record_id=?').get(id).n;const v={record_id:id,store_id:r.store_id,customer_id:r.customer_id,version,base_sequence:referralSequence(db,r.store_id)};for(const k of ['kind','title','institution','reported_at','measured_at','eye','condition_status','condition_note','source_note','record_note','reason'])v[k]=i[k];v.attachment_ids_json=JSON.stringify(i.attachment_ids);v.document_ids_json=JSON.stringify(i.document_ids);Object.assign(v,{created_at:at,created_by:actor});put(db,'external_record_versions',v);return externalRecordEvent(db,id,{...i,action:version===1?'create':'revise'},actor,at);}
export function externalRecordEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM external_records WHERE id=?').get(id),e=db.prepare('SELECT * FROM external_record_current WHERE record_id=?').get(id);put(db,'external_record_events',{id:randomUUID(),record_id:id,store_id:r.store_id,customer_id:r.customer_id,revision:(e?.revision||0)+1,sequence:referralSequence(db,r.store_id)+1,version:db.prepare('SELECT max(version) n FROM external_record_versions WHERE record_id=?').get(id).n,action:i.action,status:{create:'pending',revise:'pending',confirm:'confirmed',reject:'rejected'}[i.action]||e.status,owner_id:i.action==='assign'||!e?i.owner_id:e.owner_id,opinion_note:['confirm','reject'].includes(i.action)?i.opinion_note:i.action==='assign'?e.opinion_note:null,next_step:['confirm','reject'].includes(i.action)?i.next_step:i.action==='assign'?e.next_step:null,note:i.note,reason:i.reason,created_at:at,created_by:actor});return externalRecord(db,id);}
export function canonicalReferralSource(x){if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).sort().join(',')!=='id,kind,revision,version'||!['manual','longitudinal','observation','aftercare','training_session','external'].includes(x.kind))return null;const int=v=>Number.isSafeInteger(v)&&v>0&&v<=1000000000;if(x.kind==='manual')return x.id===null&&x.version===null&&x.revision===null?{kind:x.kind,id:null,version:null,revision:null}:null;if(typeof x.id!=='string'||!x.id||x.id.length>100)return null;if(['longitudinal','external'].includes(x.kind)&&!(int(x.version)&&int(x.revision))||x.kind==='observation'&&!(int(x.version)&&x.revision===null)||['aftercare','training_session'].includes(x.kind)&&!(x.version===null&&int(x.revision)))return null;return {kind:x.kind,id:x.id,version:x.version,revision:x.revision};}
export const sourceFromRoot=r=>({kind:r.source_kind,id:r.source_id,version:r.source_version,revision:r.source_revision});
export function referralSource(db,store,customer,s,{current=true,at=null}={}){if(!canonicalReferralSource(s))return null;if(s.kind==='manual')return {cycle_id:null,cycle_version:null};if(current){return db.prepare('SELECT * FROM referral_sources WHERE kind=? AND id=? AND store_id=? AND customer_id=? AND version IS ? AND revision IS ?').get(s.kind,s.id,store,customer,s.version,s.revision)||null;}
 let r,events,key,revision;if(s.kind==='longitudinal'){r=db.prepare('SELECT c.*,e.created_at captured_at FROM longitudinal_cases c JOIN longitudinal_case_events e ON e.case_id=c.id AND e.revision=? AND e.version=? WHERE c.id=?').get(s.revision,s.version,s.id);events='longitudinal_case_events';key='case_id';revision=s.revision;}
 else if(s.kind==='observation'){r=db.prepare('SELECT o.*,c.cycle_id,c.cycle_version,v.created_at captured_at FROM longitudinal_observations o JOIN longitudinal_cases c ON c.id=o.case_id JOIN longitudinal_observation_versions v ON v.observation_id=o.id AND v.version=? WHERE o.id=?').get(s.version,s.id);events='longitudinal_observation_versions';key='observation_id';revision=s.version;}
 else if(s.kind==='aftercare'){r=db.prepare('SELECT c.*,o.cycle_id,o.cycle_version,e.created_at captured_at FROM aftercare_cases c JOIN aftercare_events e ON e.case_id=c.id AND e.revision=? JOIN fulfillment_events f ON f.id=c.delivery_id JOIN processing_jobs j ON j.id=f.job_id JOIN retail_orders o ON o.id=j.order_id WHERE c.id=?').get(s.revision,s.id);events='aftercare_events';key='case_id';revision=s.revision;}
 else if(s.kind==='training_session'){r=db.prepare('SELECT c.*,c.visit_cycle_version cycle_version,e.created_at captured_at FROM training_sessions c JOIN training_plans p ON p.id=c.plan_id JOIN training_session_events e ON e.session_id=c.id AND e.revision=? WHERE c.id=?').get(s.revision,s.id);events='training_session_events';key='session_id';revision=s.revision;}
 else{r=db.prepare("SELECT c.*,NULL cycle_id,NULL cycle_version,e.created_at captured_at FROM external_records c JOIN external_record_events e ON e.record_id=c.id AND e.revision=? AND e.version=? AND e.status='confirmed' WHERE c.id=?").get(s.revision,s.version,s.id);events='external_record_events';key='record_id';revision=s.revision;}
 if(!r||r.store_id!==store||r.customer_id!==customer||at&&r.captured_at>at||at&&db.prepare('SELECT 1 FROM '+events+' WHERE '+key+'=? AND '+(s.kind==='observation'?'version':'revision')+'>? AND created_at<?').get(s.id,revision,at))return null;return {cycle_id:r.cycle_id??null,cycle_version:r.cycle_version??null};}
export function referralCase(db,id,{limit=30,offset=0}={}){const r=db.prepare('SELECT * FROM referral_cases WHERE id=?').get(id),e=db.prepare('SELECT * FROM referral_current WHERE case_id=?').get(id);if(!r||!e)return null;return {...r,...e,id,root_created_at:r.created_at,root_created_by:r.created_by,source:sourceFromRoot(r),customer_name:db.prepare('SELECT name FROM customers WHERE id=?').get(r.customer_id).name,professional_name:db.prepare('SELECT display_name FROM users WHERE id=?').get(e.professional_owner_id).display_name,contact_name:db.prepare('SELECT display_name FROM users WHERE id=?').get(e.contact_owner_id).display_name,history:db.prepare('SELECT * FROM referral_events WHERE case_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null,contact_total:db.prepare('SELECT count(*) n FROM referral_contact_links WHERE case_id=?').get(id).n};}
export function createReferralCase(db,store,customer,i,actor,at=new Date().toISOString(),id=randomUUID()){const source=referralSource(db,store,customer,i.source);if(!source)throw Error('referral original source changed');const n=serial(db,'referral_cases',store);put(db,'referral_cases',{id,store_id:store,customer_id:customer,source_kind:i.source.kind,source_id:i.source.id,source_version:i.source.version,source_revision:i.source.revision,cycle_id:source.cycle_id,cycle_version:source.cycle_version,source_note:i.source_note,serial:n,case_number:number('RF-',at,n),created_at:at,created_by:actor});return referralEvent(db,id,{...i,action:'create'},actor,at);}
export function referralEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM referral_cases WHERE id=?').get(id),e=db.prepare('SELECT * FROM referral_current WHERE case_id=?').get(id),full=['create','revise','arrange'].includes(i.action),v=full?i:e;const row={id:randomUUID(),case_id:id,store_id:r.store_id,customer_id:r.customer_id,revision:(e?.revision||0)+1,sequence:referralSequence(db,r.store_id)+1,action:i.action,status:{create:'draft',revise:'draft',arrange:'arranged',reschedule:'arranged',defer:'waiting',complete:'completed',cancel:'cancelled'}[i.action]||e.status};for(const k of ['professional_owner_id','contact_owner_id'])row[k]=!e||i.action==='assign'?i[k]:e[k];for(const k of ['title','reason_note','destination','arrangement_note'])row[k]=v[k];row.scheduled_for=i.action==='create'||i.action==='revise'?null:['arrange','reschedule'].includes(i.action)?i.scheduled_for:e.scheduled_for;row.due_at=['assign'].includes(i.action)?e.due_at:i.due_at;row.next_action=['assign'].includes(i.action)?e.next_action:i.next_action;row.outcome_kind=i.action==='complete'?i.outcome_kind:null;row.outcome_note=['complete','cancel'].includes(i.action)?i.outcome_note:null;row.next_step=['complete','cancel'].includes(i.action)?i.next_step:null;row.result_record_id=i.result?.id??null;row.result_version=i.result?.version??null;row.result_revision=i.result?.revision??null;Object.assign(row,{note:i.note,reason:i.reason,created_at:at,created_by:actor});put(db,'referral_events',row);return referralCase(db,id);}
export function linkReferralContact(db,id,i,actor,at=new Date().toISOString()){const c=referralCase(db,id),row={id:randomUUID(),case_id:id,store_id:c.store_id,customer_id:c.customer_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM referral_contact_links WHERE case_id=?').get(id).n,sequence:referralSequence(db,c.store_id)+1,case_revision:c.revision,contact_owner_id:c.contact_owner_id,attempt_id:i.attempt_id,receipt_id:i.receipt_id,appointment_id:i.appointment?.id??null,appointment_revision:i.appointment?.revision??null,source_note:i.source_note,result_note:i.result_note,due_at:i.due_at,next_action:i.next_action,reason:i.reason,created_at:at,created_by:actor};put(db,'referral_contact_links',row);return row;}
