import {randomUUID} from 'node:crypto';import {orderPayments} from './payments.mjs';import {orderVersion} from './retail.mjs';import {aftercareRecord} from './aftercare.mjs';import {receiptRefunds,refundSequence} from './refund-ledger.mjs';
export const refundTables=['refund_events','payment_refund_refs'];
const statuses={create:'pending',approve:'approved',reject:'rejected',cancel:'cancelled',execute:'executed'};
const time=v=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
export function refundRecord(db,id,{limit=50,offset=0}={}){const r=db.prepare("SELECT e.*,o.order_number,c.name customer_name,p.revision receipt_revision,p.amount_cents receipt_amount_cents,p.received_at FROM refund_events e JOIN retail_orders o ON o.id=e.order_id JOIN customers c ON c.id=e.customer_id JOIN payment_events p ON p.id=e.receipt_id WHERE e.id=? AND e.action='create'").get(id);if(!r)return null;const all=db.prepare('SELECT e.*,u.display_name author_name FROM refund_events e JOIN users u ON u.id=e.created_by WHERE root_id=? ORDER BY revision DESC').all(id),latest=all[0];return {...r,status:latest.status,revision:latest.revision,sequence:refundSequence(db,r.order_id),history:all.slice(offset,offset+limit),total:all.length,next_offset:offset+limit<all.length?offset+limit:null};}
export function refundSources(db,id){return db.prepare("SELECT e.* FROM payment_events e WHERE e.order_id=? AND e.action='receive' AND NOT EXISTS(SELECT 1 FROM payment_events v WHERE v.source_id=e.id) ORDER BY revision DESC").all(id).map(e=>{const r=receiptRefunds(db,e.id);return {...e,...r,available_refund_cents:e.amount_cents-r.refunded_cents-r.reserved_refund_cents};});}
export function refundCases(db,id){return db.prepare("SELECT DISTINCT c.id FROM aftercare_cases c JOIN fulfillment_events d ON d.id=c.delivery_id JOIN processing_jobs j ON j.id=d.job_id WHERE j.order_id=? OR EXISTS(SELECT 1 FROM aftercare_replacements r WHERE r.case_id=c.id AND r.new_order_id=? AND r.new_order_version=(SELECT max(version) FROM retail_order_versions WHERE order_id=r.new_order_id)) ORDER BY c.serial DESC").all(id,id).map(x=>{const c=aftercareRecord(db,x.id);return {id:c.id,case_number:c.case_number,title:c.title,revision:c.revision,status:c.status};});}
export function insertRefundEvent(db,id,input,actor,now=new Date().toISOString(),eventId=randomUUID()){const root=input.action==='create'?null:db.prepare("SELECT * FROM refund_events WHERE id=? AND action='create'").get(input.root_id),o=orderVersion(db,id),payment=orderPayments(db,id),case_id=root?root.case_id:input.case_id??null,e={id:eventId,order_id:id,order_version:root?.order_version||o.version,customer_id:o.customer_id,store_id:o.store_id,sequence:refundSequence(db,id)+1,payment_revision:payment.revision,root_id:root?.id||eventId,revision:root?refundRecord(db,root.id).revision+1:1,action:input.action,status:statuses[input.action],receipt_id:root?.receipt_id||input.receipt_id,amount_cents:root?.amount_cents||input.amount_cents,currency:'CNY',case_id,case_revision:case_id?aftercareRecord(db,case_id)?.revision:null,decision_basis:root?.decision_basis||input.decision_basis,method:input.action==='execute'?input.method:null,reference:input.action==='execute'?input.reference:null,receiver_name:input.action==='execute'?input.receiver_name:null,refunded_at:input.action==='execute'?input.refunded_at:null,receipt_note:input.action==='execute'?input.receipt_note:null,note:input.note,reason:input.reason,created_at:now,created_by:actor};db.prepare('INSERT INTO refund_events VALUES ('+Object.keys(e).map(()=>'?').join(',')+')').run(...Object.values(e));return {event:e,refund:refundRecord(db,e.root_id),payments:orderPayments(db,id)};}
export function verifyRefunds(db){const events=db.prepare('SELECT * FROM refund_events ORDER BY order_id,sequence').all(),payments=db.prepare('SELECT * FROM payment_events ORDER BY order_id,revision').all(),refs=db.prepare('SELECT * FROM payment_refund_refs').all(),latest=new Map(),seq=new Map(),times=new Map(),actualReferences=new Set();
 for(const e of events){const prior=latest.get(e.root_id),p=payments.find(p=>p.id===e.receipt_id),v=db.prepare('SELECT * FROM retail_order_versions WHERE order_id=? AND version=?').get(e.order_id,e.order_version),past=payments.filter(p=>p.order_id===e.order_id&&p.revision<=e.payment_revision);if(!p||!v||v.status!=='draft'||p.action!=='receive'||['order_id','order_version','customer_id','store_id','currency'].some(k=>e[k]!==p[k])||e.sequence!==(seq.get(e.order_id)||0)+1||e.payment_revision!==past.length||e.payment_revision<p.revision||past.some(x=>x.source_id===p.id)||e.status!==statuses[e.action]||!Number.isSafeInteger(e.amount_cents)||e.amount_cents<1||e.amount_cents>1e12||e.currency!=='CNY'||!time(e.created_at)||e.created_at<(times.get(e.order_id)||p.created_at)||e.created_at<(past.at(-1)?.created_at||p.created_at)||!e.decision_basis.trim())throw Error('退款原实收、金额或连续版本核对失败');
  for(const x of payments.filter(p=>p.order_id===e.order_id)){const ref=refs.find(r=>r.payment_event_id===x.id);if(!ref||(x.revision<=e.payment_revision)!==(ref.sequence<e.sequence)||x.revision>e.payment_revision&&x.created_at<e.created_at)throw Error('退款与原收款顺序核对失败');}
  if(e.case_id){const c=aftercareRecord(db,e.case_id),s=db.prepare('SELECT * FROM aftercare_events WHERE case_id=? AND revision=?').get(e.case_id,e.case_revision);if(!c||!s||c.customer_id!==e.customer_id||c.store_id!==e.store_id||!db.prepare('SELECT 1 FROM aftercare_cases c JOIN fulfillment_events d ON d.id=c.delivery_id JOIN processing_jobs j ON j.id=d.job_id WHERE c.id=? AND (j.order_id=? OR EXISTS(SELECT 1 FROM aftercare_replacements r WHERE r.case_id=c.id AND r.new_order_id=? AND r.new_order_version=? AND r.created_at<=?))').get(e.case_id,e.order_id,e.order_id,e.order_version,e.created_at)||e.created_at<s.created_at||db.prepare('SELECT 1 FROM aftercare_events WHERE case_id=? AND revision>? AND created_at<?').get(e.case_id,e.case_revision,e.created_at))throw Error('退款固定售后来源核对失败');}else if(e.case_revision!==null)throw Error('退款售后版本核对失败');
  if(e.action==='create'){const occupied=[...latest.values()].filter(x=>x.receipt_id===e.receipt_id&&!['cancelled','rejected'].includes(x.status)).reduce((n,x)=>n+x.amount_cents,0);if(prior||e.root_id!==e.id||e.revision!==1||occupied+e.amount_cents>p.amount_cents)throw Error('退款来源金额占用核对失败');}else if(!prior||e.revision!==prior.revision+1||['order_id','order_version','customer_id','store_id','receipt_id','amount_cents','currency','case_id','decision_basis'].some(k=>e[k]!==prior[k])||!(['approve','reject'].includes(e.action)&&prior.status==='pending'||e.action==='cancel'&&['pending','approved'].includes(prior.status)||e.action==='execute'&&prior.status==='approved'))throw Error('退款批准或固定申请核对失败');
  if(e.action==='execute'){const key=JSON.stringify([e.store_id,e.method,e.reference]);if(!['cash','card','transfer','other'].includes(e.method)||!e.reference?.trim()||!e.receiver_name?.trim()||!e.receipt_note?.trim()||!time(e.refunded_at)||e.refunded_at<'2000-01-01T00:00:00.000Z'||e.refunded_at<p.received_at||e.refunded_at<prior.created_at||e.refunded_at>e.created_at||actualReferences.has(key))throw Error('实际退款时间或凭据核对失败');actualReferences.add(key);}else if(['method','reference','receiver_name','refunded_at','receipt_note'].some(k=>e[k]!==null))throw Error('退款申请包含伪造实际资金记录');
  latest.set(e.root_id,e);seq.set(e.order_id,e.sequence);times.set(e.order_id,e.created_at);
 }
 if(refs.length!==payments.length)throw Error('收款退款引用覆盖核对失败');for(const p of payments){const r=refs.find(r=>r.payment_event_id===p.id);if(!r||r.order_id!==p.order_id||!Number.isSafeInteger(r.sequence)||r.sequence<0||r.sequence>(seq.get(p.order_id)||0)||events.some(e=>e.order_id===p.order_id&&(e.sequence<=r.sequence?e.created_at>p.created_at:e.created_at<p.created_at)))throw Error('收款固定退款版本核对失败');if(p.action==='void'){const active=new Map();for(const e of events.filter(e=>e.order_id===p.order_id&&e.sequence<=r.sequence))active.set(e.root_id,e);if([...active.values()].some(e=>e.receipt_id===p.source_id&&!['cancelled','rejected'].includes(e.status)))throw Error('退款来源被误录作废核对失败');}}
 for(const id of new Set(events.map(e=>e.order_id))){const s=orderPayments(db,id);if(s.refunded_cents>s.recorded_cents||s.retained_cents<0||refundSources(db,id).some(s=>s.available_refund_cents<0))throw Error('原实收与实际退款金额核对失败');}
}
export function createRefundsHandler(db,{need,customer,field,fail,body,mutation,audit}){
 const local=(u,id)=>{const o=orderVersion(db,id);if(!o||o.store_id!==u.store_id)fail(404,'NOT_FOUND','原订单不存在或不在本店');customer(u,o.customer_id);return o;},integer=(v,n,min=0,max=1e9)=>{if(!Number.isSafeInteger(v)||v<min||v>max)fail(422,'VALIDATION',n+'须为范围内整数');return v;},paging=url=>{const a=url.searchParams.get('limit')||'50',b=url.searchParams.get('offset')||'0';if(!/^\d{1,3}$/.test(a)||+a<1||+a>100||!/^\d{1,6}$/.test(b))fail(422,'VALIDATION','分页不正确');return {limit:+a,offset:+b};};
 return async(req,path,url,user,json)=>{const global=path==='/api/refunds',list=/^\/api\/retail\/orders\/([\w-]+)\/refunds$/.exec(path),one=/^\/api\/refunds\/([\w-]+)(\/events)?$/.exec(path);if(!global&&!list&&!one)return false;need(user,'payments:read');
 if(global){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const {limit,offset}=paging(url),q=field(url.searchParams.get('q'),'搜索',120)||'',status=url.searchParams.get('status')||'all';if(!['all',...Object.values(statuses)].includes(status))fail(422,'VALIDATION','退款筛选不正确');const where=" FROM refund_latest e JOIN retail_orders o ON o.id=e.order_id JOIN customers c ON c.id=e.customer_id WHERE e.store_id=:store AND (:status='all' OR e.status=:status) AND (:q='' OR instr(lower(o.order_number||' '||c.name||' '||e.decision_basis),lower(:q))>0)",params={store:user.store_id,status,q},total=db.prepare('SELECT count(*) n'+where).get(params).n,ids=db.prepare('SELECT e.root_id'+where+' ORDER BY e.created_at DESC,e.order_id,e.sequence DESC LIMIT :limit OFFSET :offset').all({...params,limit,offset});json(200,{items:ids.map(x=>refundRecord(db,x.root_id,{limit:1})),total,next_offset:offset+limit<total?offset+limit:null});return true;}
 const r=one?refundRecord(db,one[1]):null;if(one&&!r)fail(404,'NOT_FOUND','退款申请不存在');const o=local(user,list?.[1]||r.order_id);
 if(req.method==='GET'){if(one?.[2])fail(405,'METHOD','不支持此读取');const {limit,offset}=paging(url),payments=orderPayments(db,o.id);if(one)json(200,{refund:refundRecord(db,r.id,{limit,offset}),payments,case:r.case_id?aftercareRecord(db,r.case_id):null});else {const all=db.prepare("SELECT id FROM refund_events WHERE order_id=? AND action='create' ORDER BY sequence DESC").all(o.id);json(200,{payments,sources:refundSources(db,o.id),cases:refundCases(db,o.id),items:all.slice(offset,offset+limit).map(x=>refundRecord(db,x.id,{limit:5})),total:all.length,next_offset:offset+limit<all.length?offset+limit:null});}return true;}
 if(req.method!=='POST'||one&&!one[2])fail(405,'METHOD','不支持此请求');need(user,'payments:write');const b=await body(req,65536),action=list?'create':b.action;if(!statuses[action]||one&&action==='create')fail(422,'VALIDATION','退款操作不正确');if(['approve','reject'].includes(action))need(user,'refunds:approve');const keys=['expected_order_version','expected_payment_revision','expected_sequence','expected_case_revision','note','reason',...(list?['receipt_id','amount_cents','case_id','decision_basis']:['action','expected_revision']),...(action==='execute'?['method','reference','receiver_name','refunded_at','receipt_note']:[])];if(Object.keys(b).some(k=>!keys.includes(k)))fail(422,'VALIDATION','请仅提交本次退款字段');const input={action,expected_order_version:integer(b.expected_order_version,'原订单版本',1),expected_payment_revision:integer(b.expected_payment_revision,'原收款版本',1),expected_sequence:integer(b.expected_sequence,'退款版本'),expected_case_revision:b.expected_case_revision===null?null:integer(b.expected_case_revision,'售后案例版本',1),note:field(b.note,'本次记录',1000,true),reason:field(b.reason,'操作依据',300,true)};
 if(list)Object.assign(input,{receipt_id:field(b.receipt_id,'固定原实收记录',100,true),amount_cents:integer(b.amount_cents,'退款金额（分）',1,1e12),case_id:b.case_id===null?null:field(b.case_id,'原售后案例',100,true),decision_basis:field(b.decision_basis,'本次退款决定依据',1000,true)});else Object.assign(input,{root_id:r.id,expected_revision:integer(b.expected_revision,'申请版本',1)});
 if(action==='execute'){if(!['cash','card','transfer','other'].includes(b.method))fail(422,'VALIDATION','请选择本次实际退款方式');input.method=b.method;for(const [k,n,max] of [['reference','实际退款凭据编号',120],['receiver_name','实际退款接收人',120],['receipt_note','实际退款说明',1000]])input[k]=field(b[k],n,max,true);if(!time(b.refunded_at)||b.refunded_at<'2000-01-01T00:00:00.000Z'||b.refunded_at>new Date().toISOString())fail(422,'VALIDATION','退款时间须为已发生的规范UTC时间');input.refunded_at=b.refunded_at;}
 json(201,mutation(req,user,'refunds.'+action+':'+(r?.id||o.id),input,()=>{const current=local(user,o.id),payments=orderPayments(db,o.id),case_id=r?r.case_id:input.case_id,caseRecord=case_id?aftercareRecord(db,case_id):null;if(case_id&&!refundCases(db,o.id).some(c=>c.id===case_id))fail(409,'REFUND_CASE_SOURCE','请选择本订单同一客户的原售后来源');if(current.version!==input.expected_order_version||payments.revision!==input.expected_payment_revision||refundSequence(db,o.id)!==input.expected_sequence||(caseRecord?.revision??null)!==input.expected_case_revision||r&&refundRecord(db,r.id).revision!==input.expected_revision)fail(409,'REFUND_CONFLICT','原订单、实收、售后或退款记录已有变化，请读取最新来源');if(current.status!=='draft')fail(409,'REFUND_ORDER_STATE','原订单当前不能提交退款记录');if(list){const source=refundSources(db,o.id).find(s=>s.id===input.receipt_id);if(!source||source.order_version!==current.version)fail(409,'REFUND_SOURCE','原实收来源已经作废或变化');if(source.available_refund_cents<input.amount_cents)fail(409,'REFUND_AMOUNT','退款金额超过该笔实收扣除已退及待处理申请后的余量');}else {const p=refundRecord(db,r.id);if(!(['approve','reject'].includes(action)&&p.status==='pending'||action==='cancel'&&['pending','approved'].includes(p.status)||action==='execute'&&p.status==='approved'))fail(409,'REFUND_STATE','当前申请状态不能执行此操作');if(action==='execute'&&input.refunded_at<p.history[0].created_at)fail(422,'VALIDATION','实际退款时间不能早于本次批准');}
 if(action==='execute'&&db.prepare("SELECT 1 FROM refund_events WHERE store_id=? AND method=? AND reference=? AND action='execute'").get(user.store_id,input.method,input.reference))fail(409,'REFUND_DUPLICATE_REFERENCE','本店该方式和凭据已有实际退款记录，请核对原记录');const result=insertRefundEvent(db,o.id,input,user.id);audit(user,'refunds.'+action,result.event.id,result,r||payments);return result;}));return true;
 };
}
