import { randomUUID } from 'node:crypto';

export const retailTables=['retail_products','retail_product_versions','retail_orders','retail_order_versions','retail_order_items','retail_order_documents','retail_order_attachments'];
export const productCategories=['frame','lens','accessory','service'];
export function productRecord(db,id,version=null){
 const p=db.prepare('SELECT * FROM retail_products WHERE id=?').get(id);if(!p)return null;
 const v=version?db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? AND version=?').get(id,version):db.prepare('SELECT * FROM retail_product_versions WHERE product_id=? ORDER BY version DESC LIMIT 1').get(id);
 return v?{...p,...v,id:p.id,created_at:p.created_at,version_created_at:v.created_at,author_name:db.prepare('SELECT display_name FROM users WHERE id=?').get(v.created_by)?.display_name}:null;
}
export function insertProductVersion(db,id,input,actor,now=new Date().toISOString()){
 const p=db.prepare('SELECT * FROM retail_products WHERE id=?').get(id),version=(db.prepare('SELECT max(version) v FROM retail_product_versions WHERE product_id=?').get(id).v||0)+1;
 db.prepare('INSERT INTO retail_product_versions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,p.store_id,version,input.name,input.category,input.brand,input.specification,input.unit,input.list_price_cents,input.status,input.reason,now,actor);
 return productRecord(db,id);
}
export function orderVersion(db,id,version=null){
 const o=db.prepare('SELECT * FROM retail_orders WHERE id=?').get(id);if(!o)return null;
 const v=version?db.prepare('SELECT * FROM retail_order_versions WHERE order_id=? AND version=?').get(id,version):db.prepare('SELECT * FROM retail_order_versions WHERE order_id=? ORDER BY version DESC LIMIT 1').get(id);if(!v)return null;
 const items=db.prepare('SELECT * FROM retail_order_items WHERE order_id=? AND version=? ORDER BY position').all(id,v.version).map(r=>{const p=productRecord(db,r.product_id,r.product_version),current=productRecord(db,r.product_id);return {...r,sku:p.sku,name:p.name,category:p.category,brand:p.brand,specification:p.specification,unit:p.unit,list_price_cents:p.list_price_cents,catalog_version:current.version,catalog_status:current.status};});
 const documents=db.prepare('SELECT d.* FROM retail_order_documents r JOIN document_versions d ON d.id=r.document_version_id WHERE r.order_id=? AND r.version=? ORDER BY d.id').all(id,v.version);
 const attachments=db.prepare('SELECT a.id,a.filename,a.content_type,a.size,a.blob_sha256,a.created_at,a.created_by,a.revoked_at,a.revocation_reason FROM retail_order_attachments r JOIN attachments a ON a.id=r.attachment_id WHERE r.order_id=? AND r.version=? ORDER BY a.id').all(id,v.version);
 const {manifest_json,...safe}=v;return {...o,...safe,id:o.id,created_at:o.created_at,version_created_at:v.created_at,customer_name:db.prepare('SELECT name FROM customers WHERE id=?').get(o.customer_id).name,cycle_goal:o.cycle_id?db.prepare('SELECT goal FROM cycle_versions WHERE cycle_id=? AND version=?').get(o.cycle_id,o.cycle_version).goal:null,visit_purpose:o.visit_id?db.prepare('SELECT purpose FROM visits WHERE id=?').get(o.visit_id).purpose:null,author_name:db.prepare('SELECT display_name FROM users WHERE id=?').get(v.created_by)?.display_name,items,documents,attachments};
}
export function orderManifest(input){return {items:input.items.map(x=>({product_id:x.product_id,product_version:x.product_version,quantity:x.quantity,unit_price_cents:x.unit_price_cents,note:x.note??null})),document_version_ids:[...input.document_version_ids].sort(),attachment_ids:[...input.attachment_ids].sort()};}
export function insertOrderVersion(db,id,input,actor,status='draft',now=new Date().toISOString()){
 const o=db.prepare('SELECT * FROM retail_orders WHERE id=?').get(id),version=(db.prepare('SELECT max(version) v FROM retail_order_versions WHERE order_id=?').get(id).v||0)+1,manifest=orderManifest(input),subtotal=manifest.items.reduce((n,x)=>n+x.quantity*x.unit_price_cents,0);
 db.prepare('INSERT INTO retail_order_versions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,version,o.customer_id,o.store_id,input.title,input.notes??null,status,subtotal,'CNY',JSON.stringify(manifest),input.reason,now,actor);
 for(const [position,item] of manifest.items.entries())db.prepare('INSERT INTO retail_order_items VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,version,position+1,o.customer_id,o.store_id,item.product_id,item.product_version,item.quantity,item.unit_price_cents,item.quantity*item.unit_price_cents,item.note);
 for(const doc of manifest.document_version_ids)db.prepare('INSERT INTO retail_order_documents VALUES (?,?,?,?,?)').run(id,version,o.customer_id,o.store_id,doc);
 for(const a of manifest.attachment_ids)db.prepare('INSERT INTO retail_order_attachments VALUES (?,?,?,?,?)').run(id,version,o.customer_id,o.store_id,a);
 return orderVersion(db,id);
}
export function verifyRetail(db){
 for(const [table,key,parent] of [['retail_product_versions','product_id','retail_products'],['retail_order_versions','order_id','retail_orders']]){
  if(db.prepare(`SELECT 1 FROM ${parent} p WHERE NOT EXISTS(SELECT 1 FROM ${table} v WHERE v.${key}=p.id) LIMIT 1`).get()||db.prepare(`SELECT 1 FROM ${table} GROUP BY ${key} HAVING min(version)<>1 OR count(*)<>max(version) LIMIT 1`).get())throw Error('商品或订单版本缺失/不连续');
 }
 for(const v of db.prepare('SELECT * FROM retail_product_versions ORDER BY product_id,version').iterate()){const p=db.prepare('SELECT created_at FROM retail_products WHERE id=?').get(v.product_id),prior=v.version>1?db.prepare('SELECT created_at FROM retail_product_versions WHERE product_id=? AND version=?').get(v.product_id,v.version-1):null;if(v.created_at<(prior?.created_at||p.created_at))throw Error('商品版本时间核对失败');}
 if(db.prepare("SELECT 1 FROM retail_orders o JOIN cycle_versions c ON c.cycle_id=o.cycle_id AND c.version=o.cycle_version WHERE c.type<>'retail' LIMIT 1").get())throw Error('订单配镜需求类型核对失败');
 for(const v of db.prepare('SELECT * FROM retail_order_versions ORDER BY order_id,version').iterate()){
  const items=db.prepare('SELECT * FROM retail_order_items WHERE order_id=? AND version=? ORDER BY position').all(v.order_id,v.version),documents=db.prepare('SELECT document_version_id FROM retail_order_documents WHERE order_id=? AND version=? ORDER BY document_version_id').all(v.order_id,v.version).map(r=>r.document_version_id),attachments=db.prepare('SELECT attachment_id FROM retail_order_attachments WHERE order_id=? AND version=? ORDER BY attachment_id').all(v.order_id,v.version).map(r=>r.attachment_id);
  if(!items.length||items.length>30||items.some((r,i)=>r.position!==i+1||r.line_total_cents!==r.quantity*r.unit_price_cents)||documents.length>10||attachments.length>10||v.subtotal_cents!==items.reduce((n,x)=>n+x.line_total_cents,0)||v.manifest_json!==JSON.stringify(orderManifest({items,document_version_ids:documents,attachment_ids:attachments})))throw Error('订单明细、金额或固定引用核对失败');
  const prior=v.version>1?db.prepare('SELECT * FROM retail_order_versions WHERE order_id=? AND version=?').get(v.order_id,v.version-1):null,o=db.prepare('SELECT * FROM retail_orders WHERE id=?').get(v.order_id);
  if(v.version===1&&v.status!=='draft'||prior?.status==='cancelled'||v.created_at<(prior?.created_at||o.created_at)||v.status==='cancelled'&&(!prior||v.title!==prior.title||v.notes!==prior.notes||v.manifest_json!==prior.manifest_json||v.subtotal_cents!==prior.subtotal_cents))throw Error('订单修订或取消历史核对失败');
 }
 if(db.prepare("SELECT 1 FROM retail_orders o LEFT JOIN visit_cycle_versions v ON v.visit_id=o.visit_id AND v.cycle_id=o.cycle_id WHERE o.context_basis='visit_cycle' AND (v.basis IS NOT 'captured' OR o.cycle_version IS NOT v.version) LIMIT 1").get())throw Error('订单与到店固定需求核对失败');
}

export function createRetailHandler(db,{need,customer,field,fail,body,mutation,audit}){
 function keys(b,allowed){if(Object.keys(b).some(k=>!allowed.includes(k)))fail(422,'VALIDATION','请仅提交本次商品或订单资料');}
 function integer(value,label,min,max){if(!Number.isSafeInteger(value)||value<min||value>max)fail(422,'VALIDATION',label+'须为范围内整数');return value;}
 function localProduct(user,id){const p=productRecord(db,id);if(!p||p.store_id!==user.store_id)fail(404,'NOT_FOUND','商品不存在或不在本店');return p;}
 function localOrder(user,id){const o=db.prepare('SELECT * FROM retail_orders WHERE id=? AND store_id=?').get(id,user.store_id);if(!o)fail(404,'NOT_FOUND','订单不存在或不在本店');customer(user,o.customer_id);return o;}
 function productInput(b){return {name:field(b.name,'商品名称',120,true),category:b.category,brand:field(b.brand,'品牌',80),specification:field(b.specification,'规格说明',1000,true),unit:field(b.unit,'计价单位',20,true),list_price_cents:integer(b.list_price_cents,'目录参考价（分）',0,1000000000),status:b.status,reason:field(b.reason,'保存依据',300,true)};}
 function ids(value){if(!Array.isArray(value)||value.length>10||value.some(x=>typeof x!=='string'||!/^[-\w]{1,100}$/.test(x))||new Set(value).size!==value.length)fail(422,'VALIDATION','每类最多引用10项同一客户资料');return [...value].sort();}
 function orderInput(b){
  if(!Array.isArray(b.items)||!b.items.length||b.items.length>30)fail(422,'VALIDATION','订单需要1至30行商品');
  const items=b.items.map(x=>{if(!x||typeof x!=='object'||Array.isArray(x))fail(422,'VALIDATION','商品明细格式不正确');keys(x,['product_id','product_version','quantity','unit_price_cents','note']);return {product_id:field(x.product_id,'商品',100,true),product_version:integer(x.product_version,'商品版本',1,1000000000),quantity:integer(x.quantity,'数量',1,999),unit_price_cents:integer(x.unit_price_cents,'本单单价（分）',0,1000000000),note:field(x.note,'商品行说明',300)};});
  return {title:field(b.title,'订单名称',120,true),notes:field(b.notes,'订单说明',2000),items,document_version_ids:ids(b.document_version_ids??[]),attachment_ids:ids(b.attachment_ids??[]),reason:field(b.reason,'保存依据',300,true)};
 }
 function validateReferences(user,c,input,prior=null){
  for(const item of input.items){const p=localProduct(user,item.product_id),retained=prior?.items.some(x=>x.product_id===item.product_id&&x.product_version===item.product_version);if(!retained&&(p.version!==item.product_version||p.status!=='active'))fail(409,'PRODUCT_CHANGED','商品版本或启用状态已变化，请更新目录并核对本单单价');if(!db.prepare('SELECT 1 FROM retail_product_versions WHERE product_id=? AND version=? AND store_id=?').get(item.product_id,item.product_version,c.store_id))fail(422,'INVALID_PRODUCT','商品版本不符');}
  for(const id of input.document_version_ids)if(!db.prepare('SELECT 1 FROM document_versions WHERE id=? AND customer_id=?').get(id,c.id))fail(422,'INVALID_REFERENCE','资料版本必须属于当前客户');
  for(const id of input.attachment_ids){const a=db.prepare('SELECT revoked_at FROM attachments WHERE id=? AND customer_id=?').get(id,c.id);if(!a||a.revoked_at&&!prior?.attachments.some(x=>x.id===id))fail(422,'INVALID_REFERENCE','新引用附件须属于当前客户且可访问');}
 }
 function context(user,c,b){
  const input={cycle_id:field(b.cycle_id,'周期',100),cycle_version:b.cycle_version??null,visit_id:field(b.visit_id,'到店',100)};
  if(input.cycle_id?(!Number.isSafeInteger(input.cycle_version)||input.cycle_version<1):input.cycle_version!==null)fail(422,'VALIDATION','关联周期需明确固定版本');
  if(input.visit_id&&!db.prepare('SELECT 1 FROM visits WHERE id=? AND customer_id=?').get(input.visit_id,c.id))fail(422,'INVALID_CONTEXT','到店必须属于当前客户');
  if(input.cycle_id){const cycle=db.prepare("SELECT * FROM cycle_versions WHERE cycle_id=? AND version=? AND customer_id=? AND type='retail'").get(input.cycle_id,input.cycle_version,c.id);if(!cycle)fail(422,'INVALID_CONTEXT','请选择本客户配镜周期需求版本');if(input.visit_id){const ref=db.prepare('SELECT * FROM visit_cycle_versions WHERE visit_id=? AND cycle_id=? AND customer_id=?').get(input.visit_id,input.cycle_id,c.id);if(!ref||ref.basis!=='captured')fail(422,'UNKNOWN_CONTEXT','到店的历史需求版本未知');if(ref.version!==input.cycle_version)fail(409,'CONTEXT_CONFLICT','请选择到店固定的需求版本');}else if(db.prepare('SELECT max(version) v FROM cycle_versions WHERE cycle_id=?').get(input.cycle_id).v!==input.cycle_version)fail(409,'CONTEXT_CONFLICT','周期需求已修订，请读取最新版本');}
  return {...input,context_basis:input.visit_id?(input.cycle_id?'visit_cycle':'visit'):input.cycle_id?'cycle':'customer'};
 }
 function page(url){const limit=url.searchParams.get('limit')||'50',offset=url.searchParams.get('offset')||'0';if(!/^\d{1,3}$/.test(limit)||+limit<1||+limit>100||!/^\d{1,6}$/.test(offset))fail(422,'VALIDATION','分页范围不正确');return {limit:+limit,offset:+offset};}
 return async(req,path,url,user,json)=>{
  const products=path==='/api/retail/products',product=/^\/api\/retail\/products\/([\w-]+)(\/versions)?$/.exec(path),orders=path==='/api/retail/orders',order=/^\/api\/retail\/orders\/([\w-]+)(\/(versions|cancel)(?:\/(\d+))?)?$/.exec(path),customerOrders=/^\/api\/customers\/([\w-]+)\/retail-orders$/.exec(path),options=/^\/api\/retail\/customers\/([\w-]+)\/options$/.exec(path);
  if(!products&&!product&&!orders&&!order&&!customerOrders&&!options)return false;need(user,'retail:read');
  if(options){if(req.method!=='GET')fail(405,'METHOD','仅支持读取');const c=customer(user,options[1]);const cycles=db.prepare("SELECT c.*,v.version FROM service_cycles c JOIN cycle_versions v ON v.cycle_id=c.id AND v.version=(SELECT max(version) FROM cycle_versions WHERE cycle_id=c.id) WHERE c.customer_id=? AND c.type='retail' ORDER BY c.created_at DESC,c.id LIMIT 101").all(c.id),visits=db.prepare('SELECT * FROM visits WHERE customer_id=? ORDER BY created_at DESC,id LIMIT 101').all(c.id),documents=db.prepare('SELECT * FROM document_versions WHERE customer_id=? ORDER BY created_at DESC,id LIMIT 201').all(c.id),attachments=db.prepare('SELECT id,filename,revoked_at FROM attachments WHERE customer_id=? AND revoked_at IS NULL ORDER BY created_at DESC,id LIMIT 201').all(c.id);json(200,{customer:{id:c.id,name:c.name},cycles:cycles.slice(0,100),visits:visits.slice(0,100).map(v=>({...v,cycle_refs:db.prepare("SELECT r.*,c.goal,c.type FROM visit_cycle_versions r JOIN cycle_versions c ON c.cycle_id=r.cycle_id AND c.version=r.version WHERE r.visit_id=? AND r.basis='captured' AND c.type='retail'").all(v.id)})),documents:documents.slice(0,200),attachments:attachments.slice(0,200),contexts_truncated:cycles.length>100||visits.length>100,references_truncated:documents.length>200||attachments.length>200});return true;}
  if(products||product){
   const p=product?localProduct(user,product[1]):null;
   if(req.method==='GET'){
    if(p){const history=db.prepare('SELECT version,name,status,list_price_cents,reason,created_at,created_by FROM retail_product_versions WHERE product_id=? ORDER BY version DESC LIMIT 100').all(p.id);json(200,{product:p,history,history_truncated:p.version>100});return true;}
    const status=url.searchParams.get('status')||'all',category=url.searchParams.get('category')||'all',q=field(url.searchParams.get('q'),'检索内容',120)||'',{limit,offset}=page(url);if(!['all','active','inactive'].includes(status)||!['all',...productCategories].includes(category))fail(422,'VALIDATION','商品筛选不正确');
    const where="p.store_id=:store AND v.version=(SELECT max(version) FROM retail_product_versions WHERE product_id=p.id) AND (:status='all' OR v.status=:status) AND (:category='all' OR v.category=:category) AND (:q='' OR instr(lower(p.sku||' '||v.name||' '||COALESCE(v.brand,'')||' '||v.specification),lower(:q))>0)",params={store:user.store_id,status,category,q};const total=db.prepare('SELECT count(*) n FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id WHERE '+where).get(params).n,rows=db.prepare('SELECT p.id FROM retail_products p JOIN retail_product_versions v ON v.product_id=p.id WHERE '+where+' ORDER BY p.sku,p.id LIMIT :limit OFFSET :offset').all({...params,limit,offset});json(200,{items:rows.map(x=>productRecord(db,x.id)),total,limit,offset,next_offset:offset+rows.length<total?offset+rows.length:null});return true;
   }
   if(req.method!=='POST'||product&&!product[2])fail(405,'METHOD','不支持此请求');need(user,'retail:catalog');const b=await body(req,65536);keys(b,[...(p?['expected_version']:['sku']),'name','category','brand','specification','unit','list_price_cents','status','reason']);const input=productInput(b);if(!productCategories.includes(input.category)||!['active','inactive'].includes(input.status))fail(422,'VALIDATION','商品类别或状态不正确');if(p)input.expected_version=integer(b.expected_version,'所见商品版本',1,1000000000);else input.sku=field(b.sku,'商品编码',60,true).toUpperCase();
   json(201,mutation(req,user,p?'retail.product.revise:'+p.id:'retail.product.create',input,()=>{
    let id=p?.id,before=null;if(id){before=localProduct(user,id);if(before.version!==input.expected_version)fail(409,'PRODUCT_CONFLICT','商品已修订，请读取最新目录');if(['name','category','brand','specification','unit','list_price_cents','status'].every(k=>before[k]===input[k]))fail(409,'NO_CHANGE','商品资料没有变化');}else{if(db.prepare('SELECT 1 FROM retail_products WHERE store_id=? AND sku=?').get(user.store_id,input.sku))fail(409,'SKU_EXISTS','本店已使用该商品编码');id=randomUUID();db.prepare('INSERT INTO retail_products VALUES (?,?,?,?,?)').run(id,user.store_id,input.sku,new Date().toISOString(),user.id);}
    const after=insertProductVersion(db,id,input,user.id);audit(user,p?'retail.product.revise':'retail.product.create',id,after,before);return {product:after};
   }));return true;
  }
  if(orders||customerOrders){
   const c=customerOrders?customer(user,customerOrders[1]):null;
   if(req.method==='GET'){
    const status=url.searchParams.get('status')||'all',q=field(url.searchParams.get('q'),'检索内容',120)||'',{limit,offset}=page(url);if(!['all','draft','cancelled'].includes(status))fail(422,'VALIDATION','订单状态不正确');
    const where="o.store_id=:store AND (:customer='' OR o.customer_id=:customer) AND v.version=(SELECT max(version) FROM retail_order_versions WHERE order_id=o.id) AND (:status='all' OR v.status=:status) AND (:q='' OR instr(lower(o.order_number||' '||v.title||' '||c.name||' '||o.customer_id),lower(:q))>0)",params={store:user.store_id,customer:c?.id||'',status,q},from=' FROM retail_orders o JOIN retail_order_versions v ON v.order_id=o.id JOIN customers c ON c.id=o.customer_id WHERE '+where;
    const counts=db.prepare("SELECT count(*) total,COALESCE(sum(v.status='draft'),0) draft,COALESCE(sum(v.status='cancelled'),0) cancelled"+from).get(params),items=db.prepare('SELECT o.*,v.version,v.title,v.notes,v.status,v.subtotal_cents,v.currency,v.created_at version_created_at,c.name customer_name'+from+' ORDER BY v.created_at DESC,o.id DESC LIMIT :limit OFFSET :offset').all({...params,limit,offset});json(200,{items,counts,total:counts.total,limit,offset,next_offset:offset+items.length<counts.total?offset+items.length:null});return true;
   }
   if(!c||req.method!=='POST')fail(405,'METHOD','请从客户创建订单');need(user,'retail:write');const b=await body(req,65536);keys(b,['title','notes','items','document_version_ids','attachment_ids','reason','cycle_id','cycle_version','visit_id']);const input={...orderInput(b),cycle_id:field(b.cycle_id,'周期',100),cycle_version:b.cycle_version??null,visit_id:field(b.visit_id,'到店',100)};
   json(201,mutation(req,user,'retail.order.create:'+c.id,input,()=>{const current=customer(user,c.id),ctx=context(user,current,input);validateReferences(user,current,input);const id=randomUUID(),now=new Date().toISOString(),serial=db.prepare('SELECT COALESCE(max(serial),0)+1 n FROM retail_orders WHERE store_id=?').get(user.store_id).n,number='OW-'+now.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0');db.prepare('INSERT INTO retail_orders VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(id,user.store_id,c.id,serial,number,ctx.cycle_id,ctx.cycle_version,ctx.visit_id,ctx.context_basis,now,user.id);const after=insertOrderVersion(db,id,input,user.id,'draft',now);audit(user,'retail.order.create',id,after);return {order:after};}));return true;
  }
  const o=localOrder(user,order[1]);
  if(req.method==='GET'){
   if(order[3]==='cancel'||order[2]&&!order[4])fail(405,'METHOD','不支持此读取');const v=order[4]?integer(Number(order[4]),'版本',1,1000000000):null,record=orderVersion(db,o.id,v);if(!record)fail(404,'NOT_FOUND','订单版本不存在');json(200,{order:record,history:db.prepare('SELECT version,title,status,subtotal_cents,reason,created_at,created_by FROM retail_order_versions WHERE order_id=? ORDER BY version DESC LIMIT 100').all(o.id),history_truncated:orderVersion(db,o.id).version>100});return true;
  }
  if(req.method!=='POST'||!['versions','cancel'].includes(order[3])||order[4])fail(405,'METHOD','不支持此请求');need(user,'retail:write');const b=await body(req),cancel=order[3]==='cancel';keys(b,cancel?['expected_version','reason']:['expected_version','title','notes','items','document_version_ids','attachment_ids','reason']);const input={...(cancel?{reason:field(b.reason,'取消依据',300,true)}:orderInput(b)),expected_version:integer(b.expected_version,'所见订单版本',1,1000000000)};
  json(201,mutation(req,user,'retail.order.'+(cancel?'cancel:':'revise:')+o.id,input,()=>{localOrder(user,o.id);const before=orderVersion(db,o.id);if(before.version!==input.expected_version)fail(409,'ORDER_CONFLICT','订单已有新版本，请读取最新记录并核对');if(before.status!=='draft')fail(409,'ORDER_CANCELLED','订单草稿已取消，历史保留');const next=cancel?{title:before.title,notes:before.notes,items:before.items,document_version_ids:before.documents.map(x=>x.id),attachment_ids:before.attachments.map(x=>x.id),reason:input.reason}:input;if(!cancel){validateReferences(user,customer(user,o.customer_id),next,before);if(before.title===next.title&&before.notes===next.notes&&JSON.stringify(orderManifest(next))===JSON.stringify(orderManifest({items:before.items,document_version_ids:before.documents.map(x=>x.id),attachment_ids:before.attachments.map(x=>x.id)})))fail(409,'NO_CHANGE','订单内容没有变化');}const after=insertOrderVersion(db,o.id,next,user.id,cancel?'cancelled':'draft');audit(user,cancel?'retail.order.cancel':'retail.order.revise',o.id,after,before);return {order:after};}));return true;
 };
}
