export function hasAftercareWork(db){return Boolean(db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name='aftercare_work_events'").get());}
export function custody(db,caseId){const received=db.prepare('SELECT COALESCE(sum(return_quantity),0) n FROM aftercare_events WHERE case_id=?').get(caseId).n,returned=hasAftercareWork(db)?db.prepare("SELECT COALESCE(sum(quantity),0) n FROM aftercare_work_events WHERE case_id=? AND action='return'").get(caseId).n:0;const disposed=dispositionQuantity(db,caseId);return {received_quantity:received,returned_quantity:returned,disposed_quantity:disposed,hold_quantity:received-returned-disposed};}
export function productReturnCustody(db,productId){const received=db.prepare('SELECT COALESCE(sum(e.return_quantity),0) n FROM aftercare_events e JOIN inventory_outbounds o ON o.id=e.dispatch_id WHERE o.product_id=?').get(productId).n,returned=hasAftercareWork(db)?db.prepare("SELECT COALESCE(sum(w.quantity),0) n FROM aftercare_work_events w JOIN aftercare_events e ON e.id=w.return_id JOIN inventory_outbounds o ON o.id=e.dispatch_id WHERE o.product_id=? AND w.action='return'").get(productId).n:0;const disposed=hasDispositions(db)?db.prepare("SELECT COALESCE(sum(d.quantity),0) n FROM aftercare_disposition_events d JOIN aftercare_events r ON r.id=d.return_id JOIN inventory_outbounds o ON o.id=r.dispatch_id WHERE d.action='execute' AND o.product_id=?").get(productId).n:0;return {received_quantity:received,returned_quantity:returned,disposed_quantity:disposed,hold_quantity:received-returned-disposed};}

export function dispatchReturned(db,id,at=null){return hasAftercareWork(db)?db.prepare("SELECT COALESCE(sum(w.quantity),0) n FROM aftercare_work_events w JOIN aftercare_events e ON e.id=w.return_id WHERE e.dispatch_id=? AND w.action='return' AND (? IS NULL OR w.created_at<=?)").get(id,at,at).n:0;}
export function verifyReturnCustody(db){for(const {id,quantity} of db.prepare('SELECT id,quantity FROM inventory_outbounds').iterate()){for(const {created_at} of db.prepare('SELECT DISTINCT created_at FROM aftercare_events WHERE dispatch_id=?').iterate(id)){const received=db.prepare('SELECT COALESCE(sum(return_quantity),0) n FROM aftercare_events WHERE dispatch_id=? AND created_at<=?').get(id,created_at).n;if(received>quantity+dispatchReturned(db,id,created_at))throw Error('售后退回隔离来源或数量核对失败（原出库与再归还容量）');}}}
export function hasDispositions(db){return Boolean(db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name='aftercare_disposition_events'").get());}
export function dispositionReservations(db,caseId,sequence=null){return hasDispositions(db)?db.prepare("SELECT e.* FROM aftercare_disposition_events e WHERE e.case_id=? AND (? IS NULL OR e.sequence<=?) AND e.sequence=(SELECT max(x.sequence) FROM aftercare_disposition_events x WHERE x.root_id=e.root_id AND (? IS NULL OR x.sequence<=?)) AND e.status NOT IN('cancelled','rejected')").all(caseId,sequence,sequence,sequence,sequence):[];}
export function dispositionAllocation(db,caseId,returnId,sourceId=null,sequence=null){return dispositionReservations(db,caseId,sequence).filter(e=>e.return_id===returnId&&e.work_source_id===sourceId).reduce((n,e)=>n+e.quantity,0);}
export function dispositionQuantity(db,caseId){return hasDispositions(db)?db.prepare("SELECT COALESCE(sum(quantity),0) n FROM aftercare_disposition_events WHERE case_id=? AND action='execute'").get(caseId).n:0;}
