import {randomUUID} from 'node:crypto';
import {canonicalTime} from './training.mjs';
export {canonicalTime};
export const schedulingTables=['schedule_resources','schedule_resource_versions','schedule_slots','schedule_slot_events','schedule_bookings','schedule_booking_events'];
const insert=(db,t,o)=>db.prepare('INSERT INTO '+t+' ('+Object.keys(o).join(',')+') VALUES ('+Object.keys(o).map(()=>'?').join(',')+')').run(...Object.values(o));
export const scheduleSequence=(db,store)=>db.prepare('SELECT COALESCE(max(sequence),0) n FROM schedule_journal WHERE store_id=?').get(store).n;
export function scheduleState(db,store){return {resources:new Map(db.prepare('SELECT * FROM schedule_current_resources WHERE store_id=?').all(store).map(r=>[r.resource_id,r])),versions:new Map(db.prepare('SELECT * FROM schedule_resource_versions v JOIN schedule_resources r ON r.id=v.resource_id WHERE v.store_id=?').all(store).map(r=>[r.resource_id+':'+r.version,r])),slots:new Map(db.prepare('SELECT * FROM schedule_current_slots WHERE store_id=?').all(store).map(s=>[s.slot_id,s])),bookings:new Map(db.prepare('SELECT * FROM schedule_current_bookings WHERE store_id=?').all(store).map(b=>[b.booking_id,b]))};}
const err=(code,message)=>({code,message});
export function slotProblem(state,s){if(!canonicalTime(s.starts_at)||!canonicalTime(s.ends_at)||s.starts_at>=s.ends_at)return err('VALIDATION','请明确有效的UTC起止时段');const refs=JSON.parse(s.resources_json),resources=refs.map(x=>state.resources.get(x.id));if(resources.some((r,n)=>!r||r.version!==refs[n].version||r.status!=='active'))return err('SCHEDULE_SOURCE','资源已有修订或停用，请核对最新版本');if(resources.some(r=>r.capacity<s.capacity))return err('SCHEDULE_CAPACITY','时段容量超过明确录入的资源容量');if(s.kind!=='maintenance'&&(resources.filter(r=>r.kind==='staff').length!==1||!resources.some(r=>r.kind==='room')))return err('VALIDATION','训练时段须明确一名员工及至少一个房间');const conflicts=[];for(const other of state.slots.values()){if(other.slot_id===s.slot_id||other.status!=='active')continue;for(const ref of JSON.parse(other.resources_json)){const mine=resources.find(r=>r.resource_id===ref.id);if(!mine)continue;const old=state.versions.get(ref.id+':'+ref.version);if(Date.parse(s.starts_at)-mine.buffer_before*60000<Date.parse(other.ends_at)+old.buffer_after*60000&&Date.parse(other.starts_at)-old.buffer_before*60000<Date.parse(s.ends_at)+mine.buffer_after*60000){conflicts.push({slot_id:other.slot_id,resource_id:ref.id,starts_at:other.starts_at,ends_at:other.ends_at});break;}}}return conflicts.length?{...err('SCHEDULE_CONFLICT','员工、房间、设备或明确准备间隔与已有时段冲突'),conflicts}:null;}
export function bookingProblem(state,b,customer){const slot=state.slots.get(b.slot_id);if(!slot||slot.status!=='active'||slot.kind==='maintenance'||slot.revision!==b.slot_revision)return err('SCHEDULE_SOURCE','时段已有变化或不是可预约训练时段');for(const ref of JSON.parse(slot.resources_json)){const r=state.resources.get(ref.id);if(!r||r.version!==ref.version||r.status!=='active')return err('SCHEDULE_SOURCE','原时段资源已有变化，请先核对资源与安排');}let count=0;for(const other of state.bookings.values()){if(other.booking_id===b.booking_id||other.status==='cancelled')continue;const old=state.slots.get(other.slot_id);if(other.customer_id===customer&&(other.slot_id===b.slot_id||b.status==='booked'&&other.status==='booked'&&old.starts_at<slot.ends_at&&slot.starts_at<old.ends_at))return err('SCHEDULE_CUSTOMER','该客户已有同一时段记录或重叠预约');if(other.slot_id===b.slot_id&&other.status==='booked')count++;}return b.status==='booked'&&count>=slot.capacity?err('SCHEDULE_CAPACITY','时段已满，请登记候补或选择其他时段'):null;}
export function scheduleResource(db,id,{limit=30,offset=0}={}){const r=db.prepare('SELECT * FROM schedule_current_resources WHERE resource_id=?').get(id);if(!r)return null;return {...r,id,history:db.prepare('SELECT * FROM schedule_resource_versions WHERE resource_id=? ORDER BY version DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:r.version,next_offset:offset+limit<r.version?offset+limit:null};}
export function resourceVersion(db,id,i,actor,at=new Date().toISOString()){const root=db.prepare('SELECT * FROM schedule_resources WHERE id=?').get(id);insert(db,'schedule_resource_versions',{resource_id:id,store_id:root.store_id,version:(scheduleResource(db,id)?.version||0)+1,sequence:scheduleSequence(db,root.store_id)+1,name:i.name,capacity:i.capacity,buffer_before:i.buffer_before,buffer_after:i.buffer_after,status:i.status,source_note:i.source_note,reason:i.reason,created_at:at,created_by:actor});return scheduleResource(db,id);}
export function createResource(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){insert(db,'schedule_resources',{id,store_id:store,code:i.code,kind:i.kind,user_id:i.user_id??null,created_at:at,created_by:actor});return resourceVersion(db,id,i,actor,at);}
export function scheduleSlot(db,id,{limit=30,offset=0,revision=null}={}){const root=db.prepare('SELECT * FROM schedule_slots WHERE id=?').get(id);if(!root)return null;const e=revision?db.prepare('SELECT * FROM schedule_slot_events WHERE slot_id=? AND revision=?').get(id,revision):db.prepare('SELECT * FROM schedule_current_slots WHERE slot_id=?').get(id);if(!e)return null;const counts=db.prepare("SELECT status,count(*) n FROM schedule_current_bookings WHERE slot_id=? GROUP BY status").all(id);return {...root,...e,id,created_at:root.created_at,event_created_at:e.created_at,resources:JSON.parse(e.resources_json).map(x=>({...x,...db.prepare('SELECT v.name,v.capacity,v.buffer_before,v.buffer_after,r.kind,r.user_id FROM schedule_resource_versions v JOIN schedule_resources r ON r.id=v.resource_id WHERE v.resource_id=? AND v.version=?').get(x.id,x.version)})),booked:counts.find(x=>x.status==='booked')?.n||0,waiting:counts.find(x=>x.status==='waiting')?.n||0,history:db.prepare('SELECT * FROM schedule_slot_events WHERE slot_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function slotEvent(db,id,i,actor,at=new Date().toISOString()){const root=db.prepare('SELECT * FROM schedule_slots WHERE id=?').get(id),p=db.prepare('SELECT * FROM schedule_current_slots WHERE slot_id=?').get(id),s=i.action==='cancel'?p:i;const e={id:randomUUID(),slot_id:id,store_id:root.store_id,revision:(p?.revision||0)+1,sequence:scheduleSequence(db,root.store_id)+1,action:i.action,status:i.action==='cancel'?'cancelled':'active',kind:s.kind,capacity:s.capacity,starts_at:s.starts_at,ends_at:s.ends_at,resources_json:s.resources_json,note:i.note,reason:i.reason,created_at:at,created_by:actor};insert(db,'schedule_slot_events',e);return {event:e,slot:scheduleSlot(db,id)};}
export function createSlot(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){const serial=db.prepare('SELECT COALESCE(max(serial),0)+1 n FROM schedule_slots WHERE store_id=?').get(store).n;insert(db,'schedule_slots',{id,store_id:store,serial,slot_number:'SL-'+at.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),created_at:at,created_by:actor});return slotEvent(db,id,{...i,action:'create'},actor,at);}
export function scheduleBooking(db,id,{limit=30,offset=0}={}){const root=db.prepare('SELECT b.*,c.name customer_name,p.plan_number,v.title plan_title FROM schedule_bookings b JOIN customers c ON c.id=b.customer_id JOIN training_plans p ON p.id=b.plan_id JOIN training_plan_versions v ON v.plan_id=b.plan_id AND v.version=b.plan_version WHERE b.id=?').get(id);if(!root)return null;const e=db.prepare('SELECT * FROM schedule_current_bookings WHERE booking_id=?').get(id);if(!e)return null;const queue=db.prepare("SELECT booking_id FROM schedule_current_bookings WHERE slot_id=? AND status='waiting' ORDER BY queue_sequence").all(e.slot_id);return {...root,...e,id,created_at:root.created_at,event_created_at:e.created_at,slot:scheduleSlot(db,e.slot_id,{limit:1,revision:e.slot_revision}),queue_position:e.status==='waiting'?queue.findIndex(x=>x.booking_id===id)+1:null,history:db.prepare('SELECT * FROM schedule_booking_events WHERE booking_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function bookingEvent(db,id,i,actor,at=new Date().toISOString()){const root=db.prepare('SELECT * FROM schedule_bookings WHERE id=?').get(id),p=db.prepare('SELECT * FROM schedule_current_bookings WHERE booking_id=?').get(id),cancel=['cancel','leave'].includes(i.action),slot=cancel?p:db.prepare('SELECT * FROM schedule_current_slots WHERE slot_id=?').get(i.slot_id||p.slot_id),seq=scheduleSequence(db,root.store_id)+1,pr=cancel?p.plan_revision:db.prepare('SELECT max(revision) n FROM training_plan_events WHERE plan_id=?').get(root.plan_id).n,status=cancel?'cancelled':i.action==='promote'?'booked':i.action==='move'?p.status:i.status,e={id:randomUUID(),booking_id:id,store_id:root.store_id,revision:(p?.revision||0)+1,sequence:seq,action:i.action,status,slot_id:slot.slot_id,slot_revision:cancel?p.slot_revision:slot.revision,plan_revision:pr,queue_sequence:status==='waiting'?seq:null,previous_event_id:p?.id??null,note:i.note,reason:i.reason,created_at:at,created_by:actor};insert(db,'schedule_booking_events',e);return {event:e,booking:scheduleBooking(db,id)};}
export function createBooking(db,store,customer,plan,i,actor,at=new Date().toISOString(),id=randomUUID()){const serial=db.prepare('SELECT COALESCE(max(serial),0)+1 n FROM schedule_bookings WHERE store_id=?').get(store).n;insert(db,'schedule_bookings',{id,store_id:store,customer_id:customer,plan_id:plan.id,plan_version:plan.current_version,cycle_id:plan.cycle_id,cycle_version:plan.cycle_version,serial,booking_number:'BK-'+at.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),created_at:at,created_by:actor});return bookingEvent(db,id,{...i,action:'create'},actor,at);}
