import {randomUUID} from 'node:crypto';
import {canonicalTime} from './training.mjs';
export {canonicalTime};
export const specialtyTables=['specialty_protocols','specialty_protocol_versions','specialty_protocol_events','specialty_cases','specialty_case_versions','specialty_case_events','specialty_consents','specialty_consent_events'];
export const specialtySequence=(db,store)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM specialty_journal WHERE store_id=?').get(store).n;
export const protocolFields=['title','institution_scope_note','professional_duties_note','assessment_requirement_note','consent_requirement_note','parameter_requirement_note','product_trace_note','care_requirement_note','review_requirement_note','source_note','source_reference'];
export const caseFields=['title','assessment_note','suitability_note','source_note','next_step'];
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));
const page=(db,t,key,id,limit,offset)=>db.prepare('SELECT * FROM '+t+' WHERE '+key+'=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset);
export function specialtyProtocol(db,id,{version=null,limit=30,offset=0}={}){const r=db.prepare('SELECT * FROM specialty_protocols WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_protocol_current WHERE protocol_id=?').get(id);if(!r||!e)return null;const v=db.prepare('SELECT * FROM specialty_protocol_versions WHERE protocol_id=? AND version=?').get(id,version??e.version);if(!v)return null;return {...r,...v,...e,id,root_created_at:r.created_at,root_created_by:r.created_by,current_version:e.version,version:v.version,history:page(db,'specialty_protocol_events','protocol_id',id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function createSpecialtyProtocol(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){put(db,'specialty_protocols',{id,store_id:store,code:i.code,service_type:i.service_type,created_at:at,created_by:actor});return specialtyProtocolVersion(db,id,i,actor,at);}
export function specialtyProtocolVersion(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_protocols WHERE id=?').get(id),version=db.prepare('SELECT coalesce(max(version),0)+1 n FROM specialty_protocol_versions WHERE protocol_id=?').get(id).n,v={protocol_id:id,store_id:r.store_id,version,base_sequence:specialtySequence(db,r.store_id)};for(const k of protocolFields)v[k]=i[k];Object.assign(v,{require_assessment_evidence:Number(i.require_assessment_evidence),require_consent_evidence:Number(i.require_consent_evidence),reason:i.reason,created_at:at,created_by:actor});put(db,'specialty_protocol_versions',v);return specialtyProtocolEvent(db,id,{...i,action:version===1?'create':'revise'},actor,at);}
export function specialtyProtocolEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_protocols WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_protocol_current WHERE protocol_id=?').get(id);put(db,'specialty_protocol_events',{id:randomUUID(),protocol_id:id,store_id:r.store_id,revision:(e?.revision||0)+1,sequence:specialtySequence(db,r.store_id)+1,version:db.prepare('SELECT max(version) n FROM specialty_protocol_versions WHERE protocol_id=?').get(id).n,action:i.action,status:{create:'draft',revise:'draft',adopt:'adopted',retire:'retired'}[i.action],note:i.note,reason:i.reason,created_at:at,created_by:actor});return specialtyProtocol(db,id);}
export function specialtyConsent(db,id,{limit=30,offset=0}={}){const r=db.prepare('SELECT * FROM specialty_consents WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_consent_current WHERE consent_id=?').get(id);if(!r||!e)return null;return {...r,...e,id,root_created_at:r.created_at,root_created_by:r.created_by,document_ids:JSON.parse(r.document_ids_json),attachment_ids:JSON.parse(r.attachment_ids_json),history:page(db,'specialty_consent_events','consent_id',id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function specialtySources(db,c,v,consent=null,{current=true,at=null}={}){const failures=[],p=db.prepare('SELECT * FROM specialty_protocol_'+(current?'current':'events')+' WHERE protocol_id=?'+(current?'':' AND revision=?')).get(...(current?[c.protocol_id]:[c.protocol_id,c.protocol_revision]));if(!p||p.version!==c.protocol_version||p.revision!==c.protocol_revision||p.status!=='adopted'||at&&p.created_at>at)failures.push('启用条件来源已变化或未明确采用');const rule=db.prepare('SELECT * FROM specialty_protocol_versions WHERE protocol_id=? AND version=?').get(c.protocol_id,c.protocol_version);if(v.suitability!=='suitable')failures.push('本版本仍待进一步评估或不适用');if(!consent||consent.case_id!==c.id||consent.case_version!==v.version||consent.status!=='active')failures.push('须本条当前版本的有效明确同意');for(const [r,required,label]of [[v,rule?.require_assessment_evidence,'评估'],[consent,rule?.require_consent_evidence,'同意']]){if(!r)continue;const docs=JSON.parse(r.document_ids_json),attachments=JSON.parse(r.attachment_ids_json);if(required&&!docs.length&&!attachments.length)failures.push(label+'缺少明确配置要求的来源依据');for(const id of attachments){const a=db.prepare('SELECT * FROM attachments WHERE id=?').get(id);if(!a||a.customer_id!==c.customer_id||current&&a.revoked_at||!current&&a.revoked_at&&a.revoked_at<at)failures.push(label+'原附件已不可访问');}}return [...new Set(failures)];}
export function specialtyCase(db,id,{version=null,limit=30,offset=0}={}){const r=db.prepare('SELECT * FROM specialty_cases WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_case_current WHERE case_id=?').get(id);if(!r||!e)return null;const v=db.prepare('SELECT * FROM specialty_case_versions WHERE case_id=? AND version=?').get(id,version??e.version);if(!v)return null;const consent=e.consent_id?specialtyConsent(db,e.consent_id,{limit:1}):null,adoption=db.prepare("SELECT * FROM specialty_case_events WHERE case_id=? AND version=? AND action IN('adopt','resume') ORDER BY revision DESC LIMIT 1").get(id,v.version);return {...r,...v,...e,id,root_created_at:r.created_at,root_created_by:r.created_by,current_version:e.version,version:v.version,customer_name:db.prepare('SELECT name FROM customers WHERE id=?').get(r.customer_id).name,owner_name:db.prepare('SELECT display_name FROM users WHERE id=?').get(e.owner_id).display_name,protocol:specialtyProtocol(db,r.protocol_id,{version:r.protocol_version,limit:1}),document_ids:JSON.parse(v.document_ids_json),attachment_ids:JSON.parse(v.attachment_ids_json),consent,adoption:adoption||null,holds:specialtySources(db,{...r,id},v,consent),history:page(db,'specialty_case_events','case_id',id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function createSpecialtyCase(db,store,customer,i,actor,at=new Date().toISOString(),id=randomUUID()){const n=db.prepare('SELECT coalesce(max(serial),0)+1 n FROM specialty_cases WHERE store_id=?').get(store).n;put(db,'specialty_cases',{id,store_id:store,customer_id:customer,protocol_id:i.protocol_id,protocol_version:i.protocol_version,protocol_revision:i.protocol_revision,cycle_id:i.cycle_id,cycle_version:i.cycle_version,visit_id:i.visit_id,context_basis:i.context_basis,serial:n,case_number:'SP-'+at.slice(0,10).replaceAll('-','')+'-'+String(n).padStart(5,'0'),created_at:at,created_by:actor});return specialtyCaseVersion(db,id,i,actor,at);}
export function specialtyCaseVersion(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_cases WHERE id=?').get(id),version=db.prepare('SELECT coalesce(max(version),0)+1 n FROM specialty_case_versions WHERE case_id=?').get(id).n,v={case_id:id,store_id:r.store_id,customer_id:r.customer_id,version,base_sequence:specialtySequence(db,r.store_id)};for(const k of caseFields)v[k]=i[k];Object.assign(v,{suitability:i.suitability,assessed_at:i.assessed_at,document_ids_json:JSON.stringify(i.document_ids),attachment_ids_json:JSON.stringify(i.attachment_ids),reason:i.reason,created_at:at,created_by:actor});put(db,'specialty_case_versions',v);return specialtyCaseEvent(db,id,{...i,action:version===1?'create':'revise'},actor,at);}
export function specialtyCaseEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_cases WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_case_current WHERE case_id=?').get(id),adopt=['adopt','resume'].includes(i.action);put(db,'specialty_case_events',{id:randomUUID(),case_id:id,store_id:r.store_id,customer_id:r.customer_id,revision:(e?.revision||0)+1,sequence:specialtySequence(db,r.store_id)+1,version:db.prepare('SELECT max(version) n FROM specialty_case_versions WHERE case_id=?').get(id).n,action:i.action,status:{create:'draft',revise:'draft',adopt:'active',pause:'paused',resume:'active',stop:'stopped'}[i.action]||e.status,owner_id:!e||i.action==='assign'?i.owner_id:e.owner_id,consent_id:adopt?i.consent_id:['create','revise'].includes(i.action)?null:e.consent_id,consent_revision:adopt?i.consent_revision:['create','revise'].includes(i.action)?null:e.consent_revision,next_step:i.next_step,note:i.note,reason:i.reason,created_at:at,created_by:actor});return specialtyCase(db,id);}
export function createSpecialtyConsent(db,id,i,actor,at=new Date().toISOString(),consentId=randomUUID()){const c=specialtyCase(db,id);put(db,'specialty_consents',{id:consentId,case_id:id,store_id:c.store_id,customer_id:c.customer_id,case_version:c.current_version,initial_case_revision:c.revision,party:i.party,party_label:i.party_label,relationship_note:i.relationship_note,signed_at:i.signed_at,source_note:i.source_note,document_ids_json:JSON.stringify(i.document_ids),attachment_ids_json:JSON.stringify(i.attachment_ids),created_at:at,created_by:actor});return specialtyConsentEvent(db,consentId,{...i,action:'grant',occurred_at:i.signed_at},actor,at);}
export function specialtyConsentEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_consents WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_consent_current WHERE consent_id=?').get(id);put(db,'specialty_consent_events',{id:randomUUID(),consent_id:id,case_id:r.case_id,store_id:r.store_id,customer_id:r.customer_id,revision:(e?.revision||0)+1,sequence:specialtySequence(db,r.store_id)+1,action:i.action,status:i.action==='grant'?'active':'revoked',occurred_at:i.occurred_at,note:i.note,reason:i.reason,created_at:at,created_by:actor});return specialtyConsent(db,id);}
