import {randomUUID} from 'node:crypto';
import {specialtyCase,specialtySequence} from './specialty.mjs';
import {orderVersion} from './retail.mjs';
import {parameterRecord} from './parameters.mjs';
export const specialtyTraceTables=['specialty_order_links','specialty_order_approvals','specialty_product_lots','specialty_lot_versions','specialty_execution_refs'];
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));
export const traceSequence=(db,s)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM specialty_trace_journal WHERE store_id=?').get(s).n;
import {specialtyOrderContext} from './specialty-order-ledger.mjs';
export {specialtyOrderContext,guardSpecialtyOrder,specialtyExecutionRef} from './specialty-order-ledger.mjs';
export function lotRecord(db,id,{limit=30,offset=0}={}){const r=db.prepare('SELECT l.*,j.order_id,j.order_version,e.quantity receive_quantity,e.created_at received_recorded_at,i.product_id,i.product_version,p.sku,v.name product_name,v.unit FROM specialty_product_lots l JOIN processing_jobs j ON j.id=l.job_id JOIN processing_events e ON e.id=l.receive_event_id JOIN retail_order_items i ON i.order_id=j.order_id AND i.version=j.order_version AND i.position=l.position JOIN retail_products p ON p.id=i.product_id JOIN retail_product_versions v ON v.product_id=i.product_id AND v.version=i.product_version WHERE l.id=?').get(id),v=db.prepare('SELECT * FROM specialty_lot_current WHERE lot_id=?').get(id);if(!r||!v)return null;return {...r,...v,id,version_id:v.id,root_created_at:r.created_at,root_created_by:r.created_by,document_ids:JSON.parse(v.document_ids_json),attachment_ids:JSON.parse(v.attachment_ids_json),source_live:!db.prepare('SELECT 1 FROM json_each(?) x JOIN attachments a ON a.id=x.value WHERE a.revoked_at IS NOT NULL').get(v.attachment_ids_json),history:db.prepare('SELECT * FROM specialty_lot_versions WHERE lot_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:v.revision,next_offset:offset+limit<v.revision?offset+limit:null};}
export function traceOrderRecord(db,id,{limit=30,offset=0}={}){const l=db.prepare('SELECT l.*,o.order_number,c.name customer_name FROM specialty_order_links l JOIN retail_orders o ON o.id=l.order_id JOIN customers c ON c.id=l.customer_id WHERE l.order_id=?').get(id);if(!l)return null;const a=db.prepare('SELECT * FROM specialty_approval_current WHERE link_id=?').get(l.id),total=db.prepare('SELECT count(*) n FROM specialty_product_lots WHERE link_id=?').get(l.id).n;return {...l,context:specialtyOrderContext(db,id),approval:a,case:specialtyCase(db,l.case_id,{limit:1}),parameter:a?parameterRecord(db,a.parameter_version_id,{limit:1}):null,order:orderVersion(db,id,l.order_version),approvals:db.prepare('SELECT * FROM specialty_order_approvals WHERE link_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(l.id,limit,offset),approval_total:a?.revision||0,approval_next_offset:offset+limit<(a?.revision||0)?offset+limit:null,lots:db.prepare('SELECT id FROM specialty_product_lots WHERE link_id=? ORDER BY created_at DESC,id LIMIT ? OFFSET ?').all(l.id,limit,offset).map(x=>lotRecord(db,x.id,{limit:1})),lot_total:total,lot_next_offset:offset+limit<total?offset+limit:null,receipts:db.prepare("SELECT e.id,e.job_id,e.revision,e.position,e.quantity,e.created_at,j.serial,coalesce((SELECT sum(quantity) FROM specialty_product_lots WHERE receive_event_id=e.id),0) allocated FROM processing_events e JOIN processing_jobs j ON j.id=e.job_id WHERE j.order_id=? AND e.action='receive' ORDER BY e.created_at DESC,e.id LIMIT 101").all(id),coverage:db.prepare('SELECT c.* FROM specialty_lot_coverage c JOIN processing_jobs j ON j.id=c.job_id WHERE j.order_id=?').all(id)};}
export function approvalCandidates(db,orderId){const o=orderVersion(db,orderId),rows=db.prepare('SELECT c.id FROM specialty_cases c WHERE c.customer_id=? AND c.store_id=? AND c.cycle_id IS ? AND c.cycle_version IS ? ORDER BY c.serial DESC LIMIT 101').all(o.customer_id,o.store_id,o.cycle_id,o.cycle_version).map(x=>specialtyCase(db,x.id,{limit:1})),p=db.prepare('SELECT id FROM parameter_current WHERE order_id=? AND order_version=?').get(orderId,o.version);return {cases:rows.slice(0,100),truncated:rows.length>100,parameter:p?parameterRecord(db,p.id,{limit:1}):null};}
export function validateApproval(db,l,c,fail){if(c.status!=='active'||c.holds.length)fail(409,'SPECIALTY_ORDER_SOURCE','须明确采用的当前评估及有效本版同意：'+c.holds.join('；'));const o=orderVersion(db,l.order_id);if(o.version!==l.order_version||o.status!=='draft'||o.customer_id!==c.customer_id||o.store_id!==c.store_id||o.cycle_id!==c.cycle_id||o.cycle_version!==c.cycle_version)fail(409,'SPECIALTY_ORDER_SOURCE','请固定同客户、同店和原需求版本的有效镜片订单');if(!o.items.some(x=>x.category==='lens')||o.items.some(x=>!['lens','service'].includes(x.category)))fail(409,'SPECIALTY_ORDER_SOURCE','专项链当前接明确镜片及关联服务原单，其他实物另行办理');const p=db.prepare('SELECT * FROM parameter_current WHERE order_id=? AND order_version=?').get(o.id,o.version);if(!p||p.status!=='checked'||db.prepare('SELECT 1 FROM parameter_attachments p JOIN attachments a ON a.id=p.attachment_id WHERE p.version_id=? AND a.revoked_at IS NOT NULL').get(p.id)||o.items.filter(x=>x.category==='lens').some(x=>!JSON.parse(p.manifest_json).values.some(v=>v.position===x.position)))fail(409,'SPECIALTY_ORDER_PARAMETER','请先保存并专业核对每项镜片的明确原参数交接，未知单位不补造');const first=db.prepare('SELECT case_version FROM specialty_order_approvals WHERE link_id=? AND revision=1').get(l.id||'');if(first&&first.case_version!==c.current_version&&db.prepare("SELECT 1 FROM processing_jobs j JOIN processing_events e ON e.job_id=j.id WHERE j.order_id=? AND e.action='start'").get(o.id))fail(409,'SPECIALTY_ORDER_CHANGED','原单已开工，新的评估版本须另行处理变更，不能替换原执行依据');return p;}
export function approveSpecialtyOrder(db,orderId,caseId,i,actor,at=new Date().toISOString(),linkId=randomUUID()){let l=db.prepare('SELECT * FROM specialty_order_links WHERE order_id=?').get(orderId);if(!l){const o=orderVersion(db,orderId);l={id:linkId,order_id:orderId,order_version:o.version,case_id:caseId,store_id:o.store_id,customer_id:o.customer_id,created_at:at,created_by:actor};put(db,'specialty_order_links',l);}const c=specialtyCase(db,l.case_id,{limit:1}),p=db.prepare('SELECT * FROM parameter_current WHERE order_id=? AND order_version=?').get(orderId,l.order_version);put(db,'specialty_order_approvals',{id:randomUUID(),link_id:l.id,store_id:l.store_id,customer_id:l.customer_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM specialty_order_approvals WHERE link_id=?').get(l.id).n,sequence:traceSequence(db,l.store_id)+1,specialty_sequence:specialtySequence(db,l.store_id),case_version:c.current_version,case_revision:c.revision,consent_id:c.consent_id,consent_revision:c.consent_revision,parameter_version_id:p.id,parameter_sequence:p.sequence,note:i.note,reason:i.reason,created_at:at,created_by:actor});return traceOrderRecord(db,orderId);}
export function saveLotVersion(db,id,i,actor,at=new Date().toISOString()){const l=db.prepare('SELECT * FROM specialty_product_lots WHERE id=?').get(id);put(db,'specialty_lot_versions',{id:randomUUID(),lot_id:id,store_id:l.store_id,customer_id:l.customer_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM specialty_lot_versions WHERE lot_id=?').get(id).n,sequence:traceSequence(db,l.store_id)+1,trace_status:i.trace_status,lot_number:i.lot_number,serial_note:i.serial_note,manufacturer_note:i.manufacturer_note,supplier_note:i.supplier_note,source_note:i.source_note,document_ids_json:JSON.stringify([...i.document_ids].sort()),attachment_ids_json:JSON.stringify([...i.attachment_ids].sort()),note:i.note,reason:i.reason,created_at:at,created_by:actor});return lotRecord(db,id);}
export function createSpecialtyLot(db,orderId,i,actor,at=new Date().toISOString(),id=randomUUID()){const l=db.prepare('SELECT * FROM specialty_order_links WHERE order_id=?').get(orderId),e=db.prepare('SELECT * FROM processing_events WHERE id=?').get(i.receive_event_id);put(db,'specialty_product_lots',{id,link_id:l.id,receive_event_id:e.id,job_id:e.job_id,position:e.position,quantity:i.quantity,store_id:l.store_id,customer_id:l.customer_id,created_at:at,created_by:actor});return saveLotVersion(db,id,i,actor,at);}
