import {parameterSequence} from './parameter-ledger.mjs';
import {randomUUID} from 'node:crypto';
import {specialtyCase,specialtySequence} from './specialty.mjs';
import {traceSequence,specialtyOrderContext} from './specialty-trace.mjs';
export const careTables=['specialty_care_records','specialty_care_versions','specialty_care_events','specialty_care_execution_refs'];
export const careFields=['title','participant_label','relationship_note','guidance_note','material_note','practice_note','warning_note','contact_note','next_step'];
export const careSequence=(db,s)=>db.prepare('SELECT coalesce(max(sequence),0) n FROM specialty_care_events WHERE store_id=?').get(s).n;
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r));
export function careQuality(db,id){return db.prepare("SELECT q.*,j.order_id,j.order_version,j.customer_id,j.store_id,o.order_number,l.id link_id,l.case_id,a.case_version,a.id original_approval_id,ref.lot_basis_json,i.product_id,i.product_version,p.sku,v.name product_name,v.unit FROM fulfillment_events q JOIN processing_jobs j ON j.id=q.job_id JOIN retail_orders o ON o.id=j.order_id JOIN specialty_order_links l ON l.order_id=j.order_id JOIN specialty_execution_refs ref ON ref.event_id=q.id AND ref.kind='fulfillment' JOIN specialty_order_approvals a ON a.id=ref.approval_id JOIN retail_order_items i ON i.order_id=j.order_id AND i.version=j.order_version AND i.position=q.position JOIN retail_products p ON p.id=i.product_id JOIN retail_product_versions v ON v.product_id=i.product_id AND v.version=i.product_version WHERE q.id=? AND q.action='check_pass'").get(id)||null;}
export function careRecord(db,id,{limit=30,offset=0,version=null}={}){const r=db.prepare('SELECT * FROM specialty_care_records WHERE id=?').get(id),e=db.prepare('SELECT * FROM specialty_care_current WHERE care_id=?').get(id);if(!r||!e)return null;const v=version?db.prepare('SELECT * FROM specialty_care_versions WHERE care_id=? AND version=?').get(id,version):db.prepare('SELECT * FROM specialty_care_versions WHERE id=?').get(e.version_id);if(!v)return null;const c=specialtyCase(db,r.case_id,{limit:1}),context=db.prepare('SELECT * FROM specialty_care_context WHERE id=?').get(id),release=db.prepare("SELECT * FROM specialty_care_events WHERE care_id=? AND version_id=? AND action='release' ORDER BY revision DESC LIMIT 1").get(id,v.id);return {...r,...v,...e,id,version_id:v.id,current_version:db.prepare('SELECT version FROM specialty_care_versions WHERE id=?').get(e.version_id).version,version:v.version,root_created_at:r.created_at,root_created_by:r.created_by,source:careQuality(db,r.quality_id),case:c,document_ids:JSON.parse(v.document_ids_json),attachment_ids:JSON.parse(v.attachment_ids_json),can_handover:Boolean(context.can_handover),release:release||null,lot_basis:JSON.parse(r.lot_basis_json),history:db.prepare('SELECT e.*,v.version,v.title,v.outcome FROM specialty_care_events e JOIN specialty_care_versions v ON v.id=e.version_id WHERE e.care_id=? ORDER BY e.revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:e.revision,next_offset:offset+limit<e.revision?offset+limit:null};}
export function createCare(db,q,i,actor,at=new Date().toISOString(),id=randomUUID()){const n=db.prepare('SELECT coalesce(max(serial),0)+1 n FROM specialty_care_records WHERE quality_id=? AND timing=?').get(q.id,i.timing).n,d=i.timing==='after_handover'?db.prepare('SELECT * FROM fulfillment_events WHERE id=?').get(i.delivery_id):null;put(db,'specialty_care_records',{id,quality_id:q.id,delivery_id:d?.id||null,timing:i.timing,serial:n,link_id:q.link_id,order_id:q.order_id,case_id:q.case_id,case_version:q.case_version,original_approval_id:q.original_approval_id,store_id:q.store_id,customer_id:q.customer_id,position:q.position,quantity:d?.quantity||q.quantity,require_demonstration:Number(i.require_demonstration),requirement_source_note:i.requirement_source_note,lot_basis_json:q.lot_basis_json,created_at:at,created_by:actor});return saveCareVersion(db,id,i,actor,at);}
export function saveCareVersion(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_care_records WHERE id=?').get(id),n=db.prepare('SELECT coalesce(max(version),0)+1 n FROM specialty_care_versions WHERE care_id=?').get(id).n,v={id:randomUUID(),care_id:id,store_id:r.store_id,customer_id:r.customer_id,version:n,base_sequence:careSequence(db,r.store_id)};for(const k of careFields)v[k]=i[k];Object.assign(v,{guided_at:i.guided_at,outcome:i.outcome,document_ids_json:JSON.stringify([...i.document_ids].sort()),attachment_ids_json:JSON.stringify([...i.attachment_ids].sort()),reason:i.reason,created_at:at,created_by:actor});put(db,'specialty_care_versions',v);return careEvent(db,id,{...i,action:n===1?'create':'revise'},actor,at);}
export function careEvent(db,id,i,actor,at=new Date().toISOString()){const r=db.prepare('SELECT * FROM specialty_care_records WHERE id=?').get(id),v=db.prepare('SELECT * FROM specialty_care_versions WHERE care_id=? ORDER BY version DESC LIMIT 1').get(id),c=db.prepare('SELECT * FROM specialty_case_current WHERE case_id=?').get(r.case_id);put(db,'specialty_care_events',{id:randomUUID(),care_id:id,version_id:v.id,store_id:r.store_id,customer_id:r.customer_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM specialty_care_events WHERE care_id=?').get(id).n,sequence:careSequence(db,r.store_id)+1,action:i.action,status:{create:'pending',revise:'pending',review:'reviewed',release:'released',pause:'paused',resume:'pending',close:'closed'}[i.action],specialty_sequence:specialtySequence(db,r.store_id),case_revision:c.revision,trace_sequence:traceSequence(db,r.store_id),parameter_sequence:parameterSequence(db,r.order_id),approval_id:i.action==='release'?specialtyOrderContext(db,r.order_id)?.approval_id:null,next_step:i.next_step,note:i.note,reason:i.reason,created_at:at,created_by:actor});return careRecord(db,id);}
