import {randomUUID,createHash} from 'node:crypto';
export const staffRecordKinds=['qualification','shift','absence','training'];
export const staffRecordTables=['staff_record_roots','staff_record_versions','staff_record_events'];
export const canonicalTime=s=>typeof s==='string'&&s.length===24&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString()===s;
export const validDate=s=>typeof s==='string'&&s.length===10&&canonicalTime(s+'T00:00:00.000Z');
const text=(s,n)=>typeof s==='string'&&s.trim().length>0&&s.length<=n&&!s.includes('\0'),keys=(x,a)=>x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).length===a.length&&a.every(k=>Object.hasOwn(x,k));
export function canonicalStaffData(kind,x,at=new Date().toISOString()){
 if(kind==='qualification'){const names=['credential_label','identifier_status','identifier','issuer_status','issuer_note','issued_status','issued_date','expiry_status','expiry_date','scope_note'];if(!keys(x,names)||!text(x.credential_label,300)||!text(x.scope_note,2000))return null;for(const[s,k,check]of [['identifier_status','identifier',v=>text(v,300)],['issuer_status','issuer_note',v=>text(v,1000)],['issued_status','issued_date',v=>validDate(v)&&v<=at.slice(0,10)],['expiry_status','expiry_date',validDate]])if(!['unknown','recorded'].includes(x[s])||(x[s]==='unknown'?x[k]!==null:!check(x[k])))return null;return Object.fromEntries(names.map(k=>[k,x[k]]));}
 if(kind==='shift'||kind==='absence'){const names=['starts_at','ends_at',...(kind==='shift'?['place_note','duty_note']:['absence_note','coverage_note'])];if(!keys(x,names)||!canonicalTime(x.starts_at)||!canonicalTime(x.ends_at)||x.ends_at<=x.starts_at||names.slice(2).some(k=>!text(x[k],2000)))return null;return Object.fromEntries(names.map(k=>[k,x[k]]));}
 if(kind==='training'){const names=['time_status','occurred_at','training_label','participation_status','outcome_note'];if(!keys(x,names)||!['unknown','recorded'].includes(x.time_status)||(x.time_status==='unknown'?x.occurred_at!==null:!canonicalTime(x.occurred_at)||x.occurred_at>at)||!text(x.training_label,300)||!['not_recorded','attended','completed'].includes(x.participation_status)||!text(x.outcome_note,2000))return null;return Object.fromEntries(names.map(k=>[k,x[k]]));}
 return null;
}
export const staffRecordSequence=(db,store)=>db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name='staff_record_events'").get()?db.prepare('SELECT coalesce(max(sequence),0) n FROM staff_record_events WHERE store_id=?').get(store).n:0;
export function staffRecordCounts(db,store,id){const counts=Object.fromEntries(staffRecordKinds.map(k=>[k,{recorded:0,withdrawn:0}]));if(!db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name='staff_record_roots'").get())return counts;for(const x of db.prepare('SELECT r.kind,e.status,count(*) n FROM staff_record_roots r JOIN staff_record_current e ON e.root_id=r.id WHERE r.store_id=? AND r.staff_id=? GROUP BY r.kind,e.status').all(store,id))counts[x.kind][x.status]=x.n;return counts;}
export function employeeSource(db,id,store){const employee=db.prepare("SELECT u.id,u.display_name,u.role,u.store_id,u.active,coalesce(s.revision,1) revision,coalesce(s.must_change_password,0) must_change_password FROM users u LEFT JOIN user_security s ON s.user_id=u.id WHERE u.id=? AND u.store_id=? AND u.role<>'guardian'").get(id,store);return employee?{employee,source_token:createHash('sha256').update(JSON.stringify(employee)).digest('hex')}:null;}
const put=(db,t,r)=>db.prepare('INSERT INTO '+t+'('+Object.keys(r).join(',')+') VALUES('+Object.keys(r).map(()=>'?').join(',')+')').run(...Object.values(r)),atomic=(db,f)=>{db.exec('SAVEPOINT staff_record_apply');try{const r=f();db.exec('RELEASE staff_record_apply');return r;}catch(e){db.exec('ROLLBACK TO staff_record_apply;RELEASE staff_record_apply');throw e;}};
export function staffRecord(db,id,{version=null,limit=30,offset=0}={}){const root=db.prepare('SELECT * FROM staff_record_roots WHERE id=?').get(id),current=db.prepare('SELECT * FROM staff_record_current WHERE root_id=?').get(id);if(!root||!current)return null;const latest=db.prepare('SELECT * FROM staff_record_versions WHERE id=?').get(current.version_id),v=version?db.prepare('SELECT * FROM staff_record_versions WHERE root_id=? AND version=?').get(id,version):latest;if(!v)return null;const data=JSON.parse(v.data_json);return {...root,...v,id:root.id,root_created_at:root.created_at,root_created_by:root.created_by,version_id:v.id,data,current,current_version:latest.version,status:current.status,revision:current.revision,sequence:staffRecordSequence(db,root.store_id),employee_source:employeeSource(db,root.staff_id,root.store_id),professional_qualification_status:'not_verified',history:db.prepare('SELECT e.*,v.version FROM staff_record_events e JOIN staff_record_versions v ON v.id=e.version_id WHERE e.root_id=? ORDER BY revision DESC LIMIT ? OFFSET ?').all(id,limit,offset),total:current.revision,next_offset:offset+limit<current.revision?offset+limit:null};}
export function recordStaffVersion(db,id,i,actor,at=new Date().toISOString(),{versionId=randomUUID(),eventId=randomUUID()}={}){return atomic(db,()=>{const r=db.prepare('SELECT * FROM staff_record_roots WHERE id=?').get(id),data=r&&canonicalStaffData(r.kind,i.data,at);if(!data)throw Error('invalid explicit staff source data');const version=db.prepare('SELECT coalesce(max(version),0)+1 n FROM staff_record_versions WHERE root_id=?').get(id).n,base=staffRecordSequence(db,r.store_id);put(db,'staff_record_versions',{id:versionId,root_id:id,store_id:r.store_id,version,base_sequence:base,event_id:eventId,title:i.title,data_json:JSON.stringify(data),source_reference:i.source_reference,source_note:i.source_note,record_note:i.record_note,reason:i.reason,created_at:at,created_by:actor});put(db,'staff_record_events',{id:eventId,root_id:id,version_id:versionId,store_id:r.store_id,revision:db.prepare('SELECT coalesce(max(revision),0)+1 n FROM staff_record_events WHERE root_id=?').get(id).n,sequence:base+1,action:'record',status:'recorded',reason:i.reason,next_step:i.next_step,created_at:at,created_by:actor});return staffRecord(db,id);});}
export function createStaffRecord(db,store,i,actor,at=new Date().toISOString(),id=randomUUID()){return atomic(db,()=>{const firstVersion=randomUUID(),eventId=randomUUID(),serial=db.prepare('SELECT coalesce(max(serial),0)+1 n FROM staff_record_roots WHERE store_id=?').get(store).n;put(db,'staff_record_roots',{id,staff_id:i.staff_id,store_id:store,kind:i.kind,serial,record_number:'SR-'+at.slice(0,10).replaceAll('-','')+'-'+String(serial).padStart(5,'0'),first_version_id:firstVersion,created_at:at,created_by:actor});return recordStaffVersion(db,id,i,actor,at,{versionId:firstVersion,eventId});});}
export function withdrawStaffRecord(db,id,i,actor,at=new Date().toISOString()){const r=staffRecord(db,id);put(db,'staff_record_events',{id:randomUUID(),root_id:id,version_id:r.current.version_id,store_id:r.store_id,revision:r.revision+1,sequence:staffRecordSequence(db,r.store_id)+1,action:'withdraw',status:'withdrawn',reason:i.reason,next_step:i.next_step,created_at:at,created_by:actor});return staffRecord(db,id);}
