import { Buffer } from 'node:buffer';

export const timelineKinds=['specialty_review','specialty_care','specialty_order','specialty_lot','specialty_case','specialty_consent','external_record','referral','referral_contact','contact_case','contact_attempt','contact_receipt','customer_appointment','longitudinal','observation','review_plan','practice','reassessment','profile','cycle','visit','contact','document','attachment','authorization','task','retail','inventory','payment','processing','fulfillment','dispatch','aftercare','aftercare_work','aftercare_replacement','aftercare_disposition','refund','parameter','training_plan','training_session','entitlement','scheduling'];
// Read existing records. Only customer-related, explicitly allowed audit actions
// enter this projection; account/security logs and arbitrary audit JSON never do.
const eventsSQL=`WITH events AS (
 SELECT 'profile:'||printf('%012d',version) AS event_id,created_at AS at,'profile' AS kind,customer_id AS entity_id,created_by AS actor_id,
 json_object('version',version,'name',name,'source',source,'reason',revision_reason) AS details FROM customer_profile_versions WHERE customer_id=:customer

 UNION ALL SELECT 'external-record:'||e.record_id||':'||printf('%012d',e.revision),e.created_at,'external_record',e.record_id,e.created_by,json_object('title',v.title,'action',e.action,'version',e.version,'revision',e.revision,'status',e.status,'institution',v.institution,'source',v.kind,'condition_status',v.condition_status,'opinion_note',e.opinion_note,'reason',e.reason) FROM external_record_events e JOIN external_record_versions v ON v.record_id=e.record_id AND v.version=e.version WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'referral:'||e.case_id||':'||printf('%012d',e.revision),e.created_at,'referral',e.case_id,e.created_by,json_object('title',e.title,'action',e.action,'revision',e.revision,'status',e.status,'destination',e.destination,'scheduled_for',e.scheduled_for,'due_at',e.due_at,'outcome_kind',e.outcome_kind,'reason',e.reason) FROM referral_events e WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'referral-contact:'||e.id,e.created_at,'referral_contact',e.case_id,e.created_by,json_object('title','原实际联系关联','action','link','revision',e.revision,'result_note',e.result_note,'next_action',e.next_action,'due_at',e.due_at,'reason',e.reason) FROM referral_contact_links e WHERE e.customer_id=:customer AND e.store_id=:store

 UNION ALL SELECT 'specialty-review:'||e.id,e.created_at,'specialty_review',r.id,e.created_by,json_object('title',v.title,'action',e.action,'version',v.version,'revision',e.revision,'status',e.status,'decision',e.decision,'reason',e.reason,'order_id',r.order_id) FROM specialty_review_events e JOIN specialty_reviews r ON r.id=e.review_id JOIN specialty_review_versions v ON v.id=e.version_id WHERE r.customer_id=:customer AND r.store_id=:store
 UNION ALL SELECT 'specialty-review-link:'||e.id,e.created_at,'specialty_review',r.id,e.created_by,json_object('title',v.title,'action','关联原后续','version',v.version,'revision',e.review_revision,'reason',e.reason,'order_id',r.order_id) FROM specialty_review_links e JOIN specialty_reviews r ON r.id=e.review_id JOIN specialty_review_versions v ON v.id=e.version_id WHERE r.customer_id=:customer AND r.store_id=:store
 UNION ALL SELECT 'specialty-care:'||e.id,e.created_at,'specialty_care',r.id,e.created_by,json_object('title',v.title,'action',e.action,'version',v.version,'revision',e.revision,'status',e.status,'outcome',v.outcome,'reason',e.reason,'order_id',r.order_id) FROM specialty_care_events e JOIN specialty_care_records r ON r.id=e.care_id JOIN specialty_care_versions v ON v.id=e.version_id WHERE r.customer_id=:customer AND r.store_id=:store
 UNION ALL SELECT 'specialty-order:'||a.id,a.created_at,'specialty_order',l.order_id,a.created_by,json_object('title',o.order_number,'action','professional_approval','revision',a.revision,'case_id',l.case_id,'case_version',a.case_version,'parameter_version_id',a.parameter_version_id,'reason',a.reason) FROM specialty_order_approvals a JOIN specialty_order_links l ON l.id=a.link_id JOIN retail_orders o ON o.id=l.order_id WHERE l.customer_id=:customer AND l.store_id=:store
 UNION ALL SELECT 'specialty-lot:'||v.id,v.created_at,'specialty_lot',v.lot_id,v.created_by,json_object('title',coalesce(v.lot_number,'批号未知'),'action','trace_source','revision',v.revision,'reason',v.reason) FROM specialty_lot_versions v WHERE v.customer_id=:customer AND v.store_id=:store
 UNION ALL SELECT 'specialty-case:'||e.case_id||':'||printf('%012d',e.revision),e.created_at,'specialty_case',e.case_id,e.created_by,json_object('title',v.title,'action',e.action,'version',e.version,'revision',e.revision,'status',e.status,'suitability',v.suitability,'reason',e.reason) FROM specialty_case_events e JOIN specialty_case_versions v ON v.case_id=e.case_id AND v.version=e.version WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'specialty-consent:'||e.consent_id||':'||printf('%012d',e.revision),e.created_at,'specialty_consent',e.consent_id,e.created_by,json_object('title','本版本明确同意','action',e.action,'revision',e.revision,'status',e.status,'reason',e.reason) FROM specialty_consent_events e WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'cycle:'||cycle_id||':'||printf('%012d',version),created_at,'cycle',cycle_id,created_by,json_object('type',type,'goal',goal,'version',version,'source',source,'reason',revision_reason) FROM cycle_versions WHERE customer_id=:customer
 UNION ALL SELECT 'cycle-baseline:'||c.id,c.created_at,'cycle',c.id,c.created_by,json_object('type',c.type,'source','unrecorded','reason','早期周期创建；初始需求未留存') FROM service_cycles c WHERE c.customer_id=:customer AND EXISTS(SELECT 1 FROM cycle_versions v WHERE v.cycle_id=c.id AND v.version=1 AND v.source='legacy')
 UNION ALL SELECT 'visit:1-register:'||id,created_at,'visit',id,created_by,json_object('action','register','purpose',purpose,'cycle_count',(SELECT count(*) FROM visit_cycles WHERE visit_id=v.id),'cycle_refs',json((SELECT json_group_array(json_object('cycle_id',s.cycle_id,'version',s.version,'basis',s.basis,'type',COALESCE(cv.type,c.type),'goal',cv.goal)) FROM visit_cycle_versions s JOIN service_cycles c ON c.id=s.cycle_id LEFT JOIN cycle_versions cv ON cv.cycle_id=s.cycle_id AND cv.version=s.version WHERE s.visit_id=v.id))) FROM visits v WHERE customer_id=:customer
 UNION ALL SELECT 'visit:2-close:'||v.id,v.closed_at,'visit',v.id,(SELECT actor_id FROM audit_events WHERE action='visit.close' AND entity_id=v.id AND store_id=:store ORDER BY rowid DESC LIMIT 1),
 json_object('action','close','purpose',v.purpose,'reason',COALESCE((SELECT json_extract(after_json,'$.reason') FROM audit_events WHERE action='visit.close' AND entity_id=v.id AND store_id=:store AND json_valid(after_json) ORDER BY rowid DESC LIMIT 1),'历史记录未登记结束依据')) FROM visits v WHERE customer_id=:customer AND closed_at IS NOT NULL
 UNION ALL SELECT 'document:'||record_id||':'||printf('%012d',version),created_at,'document',record_id,created_by,json_object('version',version,'title',title,'source',source,'reason',revision_reason) FROM document_versions WHERE customer_id=:customer
 UNION ALL SELECT 'attachment:1-upload:'||id,created_at,'attachment',id,created_by,json_object('action','upload','filename',filename) FROM attachments WHERE customer_id=:customer
 UNION ALL SELECT 'attachment:2-revoke:'||id,revoked_at,'attachment',id,revoked_by,json_object('action','revoke','filename',filename,'reason',revocation_reason) FROM attachments WHERE customer_id=:customer AND revoked_at IS NOT NULL
 UNION ALL SELECT 'contact-audit:'||a.id,a.created_at,'contact',a.entity_id,a.actor_id,
 json_object('action',a.action,'name',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.name'),'relationship',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.relationship'),'active',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.active'),'previous_active',json_extract(CASE WHEN json_valid(a.before_json) THEN a.before_json ELSE '{}' END,'$.active'),'revision',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.revision'),'source',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.source'),'reason',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.reason'))
 FROM audit_events a WHERE a.store_id=:store AND a.action IN ('contact.create','contact.update') AND json_valid(a.after_json) AND json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.customer_id')=:customer
 UNION ALL SELECT 'contact-baseline:'||f.id,f.created_at,'contact',f.id,f.created_by,json_object('action','baseline','reason','早期联系人记录，详细初版未留存') FROM family_contacts f WHERE f.customer_id=:customer AND NOT EXISTS (SELECT 1 FROM audit_events a WHERE a.store_id=:store AND a.action='contact.create' AND a.entity_id=f.id AND json_valid(a.after_json) AND json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.customer_id')=:customer)
 UNION ALL SELECT 'task:'||e.task_id||':'||printf('%012d',e.revision),e.created_at,'task',e.task_id,e.actor_id,json_object('action',e.action,'title',t.title,'reason',e.reason,'revision',e.revision,'assignee_id',e.assignee_id,'assignee_name',u.display_name,'candidate_role',e.candidate_role,'assignment_status',e.assignment_status,'execution_status',e.execution_status,'lifecycle_status',e.lifecycle_status,'exception_reason',e.exception_reason,'restore_status',e.restore_status,'restore_reason',e.restore_reason,'cycle_id',t.cycle_id,'cycle_version',t.cycle_version,'visit_id',t.visit_id) FROM task_events e JOIN work_tasks t ON t.id=e.task_id LEFT JOIN users u ON u.id=e.assignee_id WHERE e.customer_id=:customer AND t.store_id=:store
 UNION ALL SELECT 'task-condition:'||c.task_id||':'||printf('%012d',c.version),c.created_at,'task',c.task_id,c.created_by,json_object('action','conditions','title',t.title,'reason',c.reason,'revision',c.version,'task_revision',c.task_revision,'description',c.description,'require_document',c.require_document,'require_attachment',c.require_attachment,'assignee_name',u.display_name,'candidate_role',e.candidate_role,'execution_status',e.execution_status,'lifecycle_status',e.lifecycle_status,'cycle_version',t.cycle_version) FROM task_conditions c JOIN work_tasks t ON t.id=c.task_id JOIN task_events e ON e.task_id=c.task_id AND e.revision=c.task_revision LEFT JOIN users u ON u.id=e.assignee_id WHERE c.customer_id=:customer AND t.store_id=:store
 UNION ALL SELECT 'task-evidence:'||d.task_id||':'||printf('%012d',d.version),d.created_at,'task',d.task_id,d.created_by,json_object('action','evidence','title',t.title,'reason',d.reason,'revision',d.version,'task_revision',d.task_revision,'condition_version',d.condition_version,'notes',d.notes,'source',d.source,'references',json(d.references_json),'assignee_name',u.display_name,'candidate_role',e.candidate_role,'execution_status',e.execution_status,'lifecycle_status',e.lifecycle_status,'cycle_version',t.cycle_version) FROM task_evidence d JOIN work_tasks t ON t.id=d.task_id JOIN task_events e ON e.task_id=d.task_id AND e.revision=d.task_revision LEFT JOIN users u ON u.id=e.assignee_id WHERE d.customer_id=:customer AND t.store_id=:store
 UNION ALL SELECT 'task-complete:'||c.task_id,c.completed_at,'task',c.task_id,c.completed_by,json_object('action','complete','title',t.title,'reason',c.reason,'output_summary',c.output_summary,'revision',c.task_revision,'condition_version',c.condition_version,'evidence_version',c.evidence_version,'scope',c.scope,'execution_status','completed','cycle_version',t.cycle_version,'snapshot_sha256',c.snapshot_sha256) FROM task_completions c JOIN work_tasks t ON t.id=c.task_id WHERE c.customer_id=:customer AND t.store_id=:store
 UNION ALL SELECT 'task-correction:'||c.task_id||':'||printf('%012d',c.version),c.created_at,'task',c.task_id,c.created_by,json_object('action','correct','title',t.title,'revision',c.version,'reason',c.reason,'output_summary',c.output_summary,'completion_sha256',c.completion_sha256) FROM task_completion_corrections c JOIN work_tasks t ON t.id=c.task_id WHERE c.customer_id=:customer AND t.store_id=:store
 UNION ALL SELECT 'task-followup:'||f.task_id,f.created_at,'task',f.task_id,f.created_by,json_object('action','followup','title',t.title,'parent_task_id',f.parent_task_id,'parent_title',p.title,'source_correction_version',f.source_correction_version,'source_output_summary',f.source_output_summary,'reason',f.reason,'cycle_version',t.cycle_version) FROM task_followups f JOIN work_tasks t ON t.id=f.task_id JOIN work_tasks p ON p.id=f.parent_task_id WHERE f.customer_id=:customer AND t.store_id=:store
 UNION ALL SELECT 'dispatch:'||e.id,e.created_at,'dispatch',e.delivery_id,e.created_by,json_object('action','dispatch','order_id',e.order_id,'order_version',e.order_version,'order_number',o.order_number,'position',e.position,'quantity',e.quantity,'reason',e.reason,'outbound_revision',e.outbound_revision) FROM inventory_outbounds e JOIN retail_orders o ON o.id=e.order_id WHERE o.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'aftercare_replacement:'||e.plan_id||':'||printf('%012d',e.revision),e.created_at,'aftercare_replacement',e.plan_id,e.created_by,json_object('action',e.action,'revision',e.revision,'order_id',p.new_order_id,'order_version',p.new_order_version,'order_number',o.order_number,'kind',p.kind,'quantity',p.quantity,'case_id',p.case_id,'reason',e.reason) FROM aftercare_replacement_events e JOIN aftercare_replacements p ON p.id=e.plan_id JOIN aftercare_cases c ON c.id=p.case_id JOIN retail_orders o ON o.id=p.new_order_id WHERE c.customer_id=:customer AND c.store_id=:store
 UNION ALL SELECT 'contact-case:'||e.id,e.created_at,'contact_case',c.id,e.created_by,json_object('action',e.action,'revision',e.revision,'title',e.title,'reason',e.reason) FROM contact_case_events e JOIN contact_cases c ON c.id=e.case_id WHERE c.customer_id=:customer AND c.store_id=:store
 UNION ALL SELECT 'contact-attempt:'||e.id,e.created_at,'contact_attempt',e.case_id,e.created_by,json_object('action','record','title','人工联系','result',e.result,'occurred_at',e.occurred_at,'reason',e.reason) FROM contact_attempts e WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'contact-receipt:'||e.id,e.created_at,'contact_receipt',e.case_id,e.created_by,json_object('action','receipt','title','实际回执','status',e.status,'revision',e.revision,'reason',e.reason) FROM contact_receipts e WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'customer-appointment:'||e.id,e.created_at,'customer_appointment',a.id,e.created_by,json_object('action',e.action,'title',e.purpose_note,'revision',e.revision,'starts_at',e.starts_at,'visit_id',e.visit_id,'reason',e.reason) FROM customer_appointment_events e JOIN customer_appointments a ON a.id=e.appointment_id WHERE a.customer_id=:customer AND a.store_id=:store
 UNION ALL SELECT 'longitudinal:'||e.id,e.created_at,'longitudinal',c.id,e.created_by,json_object('action',e.action,'title',v.title,'version',e.version,'revision',e.revision,'reason',e.reason) FROM longitudinal_case_events e JOIN longitudinal_cases c ON c.id=e.case_id JOIN longitudinal_case_versions v ON v.case_id=c.id AND v.version=e.version WHERE c.customer_id=:customer AND c.store_id=:store
 UNION ALL SELECT 'observation:'||v.observation_id||':'||printf('%012d',v.version),v.created_at,'observation',o.id,v.created_by,json_object('title',o.observation_number,'version',v.version,'measured_at',v.measured_at,'eye',v.eye,'source',v.source,'reason',v.reason) FROM longitudinal_observation_versions v JOIN longitudinal_observations o ON o.id=v.observation_id WHERE o.customer_id=:customer AND o.store_id=:store
 UNION ALL SELECT 'review-plan:'||e.id,e.created_at,'review_plan',p.id,e.created_by,json_object('action',e.action,'title',e.purpose,'revision',e.revision,'due_date',e.due_date,'reason',e.reason) FROM review_plan_events e JOIN review_plans p ON p.id=e.plan_id WHERE p.customer_id=:customer AND p.store_id=:store
 UNION ALL SELECT 'practice:'||e.id,e.created_at,'practice',a.id,e.created_by,json_object('action',e.action,'version',e.version,'title',v.title,'reason',e.reason) FROM practice_events e JOIN practice_assignments a ON a.id=e.assignment_id JOIN practice_versions v ON v.assignment_id=a.id AND v.version=e.version WHERE a.customer_id=:customer AND a.store_id=:store
 UNION ALL SELECT 'practice-report:'||r.id,r.created_at,'practice',a.id,r.created_by,json_object('action','submit','version',r.version,'source',r.source,'title',v.title,'reason',r.reason) FROM practice_reports r JOIN practice_assignments a ON a.id=r.assignment_id JOIN practice_versions v ON v.assignment_id=a.id AND v.version=r.version WHERE a.customer_id=:customer AND a.store_id=:store
 UNION ALL SELECT 'practice-review:'||f.id,f.created_at,'practice',a.id,f.created_by,json_object('action','feedback','version',r.version,'source',r.source,'title',v.title,'reason',f.reason) FROM practice_reviews f JOIN practice_reports r ON r.id=f.report_id JOIN practice_assignments a ON a.id=r.assignment_id JOIN practice_versions v ON v.assignment_id=a.id AND v.version=r.version WHERE a.customer_id=:customer AND a.store_id=:store
 UNION ALL SELECT 'reassessment:'||e.id,e.created_at,'reassessment',a.id,e.created_by,json_object('action',e.action,'version',e.version,'title',v.title,'reason',e.reason) FROM training_reassessment_events e JOIN training_reassessments a ON a.id=e.reassessment_id JOIN training_reassessment_versions v ON v.reassessment_id=a.id AND v.version=e.version WHERE a.customer_id=:customer AND a.store_id=:store
 UNION ALL SELECT 'scheduling:'||e.id,e.created_at,'scheduling',e.booking_id,e.created_by,json_object('action',e.action,'revision',e.revision,'booking_number',b.booking_number,'plan_version',b.plan_version,'slot_id',e.slot_id,'starts_at',s.starts_at,'ends_at',s.ends_at,'status',e.status,'reason',e.reason) FROM schedule_booking_events e JOIN schedule_bookings b ON b.id=e.booking_id JOIN schedule_slot_events s ON s.slot_id=e.slot_id AND s.revision=e.slot_revision WHERE b.customer_id=:customer AND b.store_id=:store
 UNION ALL SELECT 'entitlement:'||e.id,e.created_at,'entitlement',e.account_id,e.created_by,json_object('action',e.action,'revision',e.revision,'account_number',a.account_number,'package_version',a.package_version,'origin',e.origin,'quantity',e.quantity,'valid_start',e.valid_start,'valid_end',e.valid_end,'source_event_id',e.source_event_id,'reason',e.reason) FROM entitlement_events e JOIN entitlement_accounts a ON a.id=e.account_id WHERE a.customer_id=:customer AND a.store_id=:store AND :payment_allowed=1
 UNION ALL SELECT 'training-plan:'||e.plan_id||':'||printf('%012d',e.revision),e.created_at,'training_plan',e.plan_id,e.created_by,json_object('action',e.action,'revision',e.revision,'plan_version',e.plan_version,'plan_number',p.plan_number,'title',v.title,'status',e.status,'cycle_id',p.cycle_id,'cycle_version',p.cycle_version,'reason',e.reason) FROM training_plan_events e JOIN training_plans p ON p.id=e.plan_id JOIN training_plan_versions v ON v.plan_id=e.plan_id AND v.version=e.plan_version WHERE p.customer_id=:customer AND p.store_id=:store
 UNION ALL SELECT 'training-session:'||e.session_id||':'||printf('%012d',e.revision),e.created_at,'training_session',e.session_id,e.created_by,json_object('action',e.action,'revision',e.revision,'plan_id',s.plan_id,'plan_version',s.plan_version,'plan_number',p.plan_number,'status',e.status,'visit_id',s.visit_id,'visit_cycle_version',s.visit_cycle_version,'reason',e.reason) FROM training_session_events e JOIN training_sessions s ON s.id=e.session_id JOIN training_plans p ON p.id=s.plan_id WHERE s.customer_id=:customer AND s.store_id=:store
 UNION ALL SELECT 'parameter:'||e.order_id||':'||printf('%012d',e.sequence),e.created_at,'parameter',e.order_id,e.created_by,json_object('action',e.action,'revision',v.version,'order_version',v.order_version,'order_number',o.order_number,'source',v.source,'reason',e.reason) FROM parameter_events e JOIN parameter_versions v ON v.id=e.version_id JOIN retail_orders o ON o.id=e.order_id WHERE v.customer_id=:customer AND v.store_id=:store
 UNION ALL SELECT 'parameter-review:'||r.job_id||':'||printf('%012d',r.revision),r.created_at,'parameter',j.order_id,r.created_by,json_object('action','review','revision',r.revision,'order_version',j.order_version,'order_number',o.order_number,'outcome',r.outcome,'job_id',j.id,'reason',r.reason) FROM parameter_reviews r JOIN processing_jobs j ON j.id=r.job_id JOIN retail_orders o ON o.id=j.order_id WHERE j.customer_id=:customer AND j.store_id=:store
 UNION ALL SELECT 'refund:'||e.order_id||':'||printf('%012d',e.sequence),e.created_at,'refund',e.order_id,e.created_by,json_object('action',e.action,'revision',e.sequence,'order_version',e.order_version,'order_number',o.order_number,'amount_cents',e.amount_cents,'currency',e.currency,'receipt_id',e.receipt_id,'case_id',e.case_id,'reason',e.reason) FROM refund_events e JOIN retail_orders o ON o.id=e.order_id WHERE e.customer_id=:customer AND e.store_id=:store AND :payment_allowed=1
 UNION ALL SELECT 'aftercare_disposition:'||e.case_id||':'||printf('%012d',e.sequence),e.created_at,'aftercare_disposition',e.case_id,e.created_by,json_object('action',e.action,'revision',e.sequence,'order_id',j.order_id,'order_version',j.order_version,'order_number',o.order_number,'case_serial',c.serial,'position',d.position,'quantity',e.quantity,'kind',e.kind,'destination',e.destination,'reason',e.reason) FROM aftercare_disposition_events e JOIN aftercare_cases c ON c.id=e.case_id JOIN fulfillment_events d ON d.id=c.delivery_id JOIN processing_jobs j ON j.id=d.job_id JOIN retail_orders o ON o.id=j.order_id WHERE c.customer_id=:customer AND c.store_id=:store
 UNION ALL SELECT 'aftercare_work:'||e.case_id||':'||printf('%012d',e.revision),e.created_at,'aftercare_work',e.case_id,e.created_by,json_object('action',e.action,'revision',e.revision,'order_id',j.order_id,'order_version',j.order_version,'order_number',o.order_number,'case_serial',c.serial,'position',d.position,'quantity',e.quantity,'reason',e.reason) FROM aftercare_work_events e JOIN aftercare_cases c ON c.id=e.case_id JOIN fulfillment_events d ON d.id=c.delivery_id JOIN processing_jobs j ON j.id=d.job_id JOIN retail_orders o ON o.id=j.order_id WHERE c.customer_id=:customer AND c.store_id=:store
 UNION ALL SELECT 'aftercare:'||e.case_id||':'||printf('%012d',e.revision),e.created_at,'aftercare',e.case_id,e.created_by,json_object('action',e.action,'revision',e.revision,'order_id',j.order_id,'order_version',j.order_version,'order_number',o.order_number,'case_serial',c.serial,'title',c.title,'reason',e.reason,'return_quantity',e.return_quantity) FROM aftercare_events e JOIN aftercare_cases c ON c.id=e.case_id JOIN fulfillment_events d ON d.id=c.delivery_id JOIN processing_jobs j ON j.id=d.job_id JOIN retail_orders o ON o.id=j.order_id WHERE c.customer_id=:customer AND c.store_id=:store
 UNION ALL SELECT 'fulfillment:'||e.job_id||':'||printf('%012d',e.revision),e.created_at,'fulfillment',e.job_id,e.created_by,json_object('action',e.action,'revision',e.revision,'processing_revision',e.processing_revision,'order_id',j.order_id,'order_version',j.order_version,'order_number',o.order_number,'job_serial',j.serial,'position',e.position,'quantity',e.quantity,'source_id',e.source_id,'reason',e.reason) FROM fulfillment_events e JOIN processing_jobs j ON j.id=e.job_id JOIN retail_orders o ON o.id=j.order_id WHERE j.customer_id=:customer AND j.store_id=:store
 UNION ALL SELECT 'processing:'||e.job_id||':'||printf('%012d',e.revision),e.created_at,'processing',e.job_id,e.created_by,json_object('action',e.action,'revision',e.revision,'order_id',j.order_id,'order_version',j.order_version,'order_number',o.order_number,'job_serial',j.serial,'position',e.position,'quantity',e.quantity,'reason',e.reason) FROM processing_events e JOIN processing_jobs j ON j.id=e.job_id JOIN retail_orders o ON o.id=j.order_id WHERE j.customer_id=:customer AND j.store_id=:store
 UNION ALL SELECT 'payment:'||e.order_id||':'||printf('%012d',e.revision),e.created_at,'payment',e.order_id,e.created_by,json_object('action',e.action,'revision',e.revision,'order_version',e.order_version,'order_number',o.order_number,'amount_cents',e.amount_cents,'reason',e.reason,'source_id',e.source_id) FROM payment_events e JOIN retail_orders o ON o.id=e.order_id WHERE e.customer_id=:customer AND e.store_id=:store AND :payment_allowed=1
 UNION ALL SELECT 'inventory-order:'||e.order_id||':'||printf('%012d',e.revision),e.created_at,'inventory',e.order_id,e.created_by,json_object('action',e.action,'revision',e.revision,'order_version',e.order_version,'order_number',o.order_number,'reason',e.reason,'source_id',e.source_id) FROM inventory_order_events e JOIN retail_orders o ON o.id=e.order_id WHERE e.customer_id=:customer AND e.store_id=:store
 UNION ALL SELECT 'retail:'||v.order_id||':'||printf('%012d',v.version),v.created_at,'retail',v.order_id,v.created_by,json_object('version',v.version,'order_number',o.order_number,'title',v.title,'status',v.status,'subtotal_cents',v.subtotal_cents,'currency',v.currency,'reason',v.reason,'cycle_id',o.cycle_id,'cycle_version',o.cycle_version,'visit_id',o.visit_id) FROM retail_order_versions v JOIN retail_orders o ON o.id=v.order_id WHERE v.customer_id=:customer AND o.store_id=:store
 UNION ALL SELECT 'authorization:'||a.id,a.created_at,'authorization',a.entity_id,a.actor_id,
 json_object('action',a.action,'relationship',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.relationship'),'reason',json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.reason')) FROM audit_events a WHERE a.store_id=:store AND a.entity_id=:customer AND a.action IN ('guardian.authorize','guardian.revoke') AND json_valid(a.after_json) AND json_extract(CASE WHEN json_valid(a.after_json) THEN a.after_json ELSE '{}' END,'$.customer_id')=:customer
)`;

export function createTimelineHandler(db,{need,customer,fail}){
  const count=(table,id,extra='')=>db.prepare(`SELECT count(*) n FROM ${table} WHERE customer_id=? ${extra}`).get(id).n;
  function date(value){if(value===null)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value)fail(422,'VALIDATION','筛选日期不正确');return value;}
  return (req,path,url,user,json)=>{
    const match=/^\/api\/customers\/([\w-]+)\/(overview|timeline)$/.exec(path);if(!match)return false;
    need(user,'timeline:read');const c=customer(user,match[1]);if(req.method!=='GET')fail(405,'METHOD','不支持此请求');
    if(match[2]==='overview'){
      const last=db.prepare('SELECT id,purpose,created_at,status FROM visits WHERE customer_id=? ORDER BY created_at DESC,id DESC LIMIT 1').get(c.id)||null;
      json(200,{customer_id:c.id,profile_version:db.prepare('SELECT max(version) v FROM customer_profile_versions WHERE customer_id=?').get(c.id).v,cycle_drafts:count('service_cycles',c.id),visits_registered:count('visits',c.id,"AND status='registered'"),visits_closed:count('visits',c.id,"AND status='closed'"),contacts_active:count('family_contacts',c.id,'AND active=1'),documents:count('document_records',c.id),attachments_active:count('attachments',c.id,'AND revoked_at IS NULL'),last_visit:last,retail_orders_draft:count('retail_orders',c.id,"AND (SELECT status FROM retail_order_versions WHERE order_id=retail_orders.id ORDER BY version DESC LIMIT 1)='draft'"),retail_orders_cancelled:count('retail_orders',c.id,"AND (SELECT status FROM retail_order_versions WHERE order_id=retail_orders.id ORDER BY version DESC LIMIT 1)='cancelled'"),tasks_completed:count('task_completions',c.id),tasks_followups:count('task_followups',c.id),tasks_blocked:count('work_tasks',c.id,"AND lifecycle_status='blocked'"),tasks_cancelled:count('work_tasks',c.id,"AND lifecycle_status='cancelled'"),tasks_queued:count('work_tasks',c.id,"AND assignment_status='queued'"),tasks_running:count('work_tasks',c.id,"AND execution_status='running' AND NOT EXISTS(SELECT 1 FROM task_completions WHERE task_id=work_tasks.id)"),tasks_paused:count('work_tasks',c.id,"AND execution_status='paused' AND NOT EXISTS(SELECT 1 FROM task_completions WHERE task_id=work_tasks.id)"),tasks_awaiting:count('work_tasks',c.id,"AND assignment_status='awaiting'"),tasks_accepted:count('work_tasks',c.id,"AND assignment_status='accepted'")});return true;
    }
    const kind=url.searchParams.get('kind')||'all',from=date(url.searchParams.get('from')),to=date(url.searchParams.get('to'));
    if(kind==='scheduling')need(user,'scheduling:read');
    if(kind==='entitlement')need(user,'entitlements:read');
    if(['payment','refund'].includes(kind))need(user,'payments:read');
    if(kind!=='all'&&!timelineKinds.includes(kind))fail(422,'VALIDATION','记录类别不正确');if(from&&to&&from>to)fail(422,'VALIDATION','开始日期不能晚于结束日期');
    const rawLimit=url.searchParams.get('limit')??'20';if(!/^\d{1,3}$/.test(rawLimit)||Number(rawLimit)<1||Number(rawLimit)>50)fail(422,'VALIDATION','每页记录数为1至50');const limit=Number(rawLimit);
    let cursor=null;const rawCursor=url.searchParams.get('cursor');
    if(rawCursor!==null){
      try{
        if(!rawCursor||rawCursor.length>2048||!/^[\w-]+$/.test(rawCursor))throw Error();cursor=JSON.parse(Buffer.from(rawCursor,'base64url').toString('utf8'));
        if(!cursor||cursor.customer!==c.id||cursor.kind!==kind||cursor.from!==from||cursor.to!==to||typeof cursor.at!=='string'||cursor.at.length>40||Number.isNaN(Date.parse(cursor.at))||typeof cursor.id!=='string'||!/^[-\w:]{1,200}$/.test(cursor.id))throw Error();
      }catch{fail(422,'INVALID_CURSOR','分页标识无效或与当前筛选不一致');}
    }
    const params={payment_allowed:['manager','reception'].includes(user.role)?1:0,customer:c.id,store:c.store_id,kind,from,to,at:cursor?.at||'',id:cursor?.id||'',limit:limit+1};
    const rows=db.prepare(eventsSQL+` SELECT e.*,u.display_name AS actor_name FROM events e LEFT JOIN users u ON u.id=e.actor_id WHERE (:kind='all' OR e.kind=:kind) AND (:from='' OR substr(e.at,1,10)>=:from) AND (:to='' OR substr(e.at,1,10)<=:to) AND (:at='' OR e.at<:at OR (e.at=:at AND e.event_id<:id)) ORDER BY e.at DESC,e.event_id DESC LIMIT :limit`).all(params);
    const more=rows.length>limit,items=rows.slice(0,limit).map(({details,...row})=>({...row,details:JSON.parse(details)})),last=items.at(-1);
    const next_cursor=more?Buffer.from(JSON.stringify({customer:c.id,kind,from,to,at:last.at,id:last.event_id})).toString('base64url'):null;
    json(200,{items,next_cursor,limit,timezone:'UTC',order:'newest_first'});return true;
  };
}
